### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'Future<Response<dynamic>>'

### ISSUE THREAD

**Issue by arden** [flutterchina/dio#1]
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'Future<dynamic>' is not a subtype of type 'Future<Response<dynamic>>' where
  Future is from dart:async
  Future is from dart:async
  Response is from package:dio/src/Response.dart

#0      Dio._onError (package:dio/src/Dio.dart:526:12)
#1      Dio._makeRequest.<anonymous closure> (package:dio/src/Dio.dart:420:28)
#2      Dio._checkIfNeedEnqueue (package:dio/src/Dio.dart:554:22)
#3      Dio._makeRequest (package:dio/src/Dio.dart:416:35)
<asynchronous suspension>
#4      Dio._request.<anonymous closure> (package:dio/src/Dio.dart:316:16)
#5      Dio._checkIfNeedEnqueue (package:dio/src/Dio.dart:554:22)
#6      Dio._request (package:dio/src/Dio.dart:287:31)
<asynchronous suspension>
#7      Dio.request (package:dio/src/Dio.dart:270:12)
<asynchronous suspension>
#8      Dio.get (package:dio/src/Dio.dart:62:12)
#9      UserApi.getUser (package:saytoken_flutter/api/user_api.dart:12:31)
<asynchronous suspension>
#10     _LoginPageState.login (package:<…>
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
DioError [DioErrorType.DEFAULT]: type 'Future<dynamic>' is not a subtype of type 'Future<Response<dynamic>>' where
  Future is from dart:async
  Future is from dart:async
  Response is from package:dio/src/Response.dart
#0      Dio.resolve (package:dio/src/Dio.dart:112:21)
#1      Dio._onSuccess (package:dio/src/Dio.dart:509:18)
#2      Dio._makeRequest.<anonymous closure> (package:dio/src/Dio.dart:398:57)
#3      Dio._checkIfNeedEnqueue (package:dio/src/Dio.dart:554:22)
#4      Dio._makeRequest (package:dio/src/Dio.dart:393:33)
<asynchronous suspension>
#5      Dio._request.<anonymous closure> (package:dio/src/Dio.dart:316:16)
#6      Dio._checkIfNeedEnqueue (package:dio/src/Dio.dart:554:22)
#7      Dio._request (package:dio/src/Dio.dart:287:31)
<asynchronous suspension>
#8      Dio.request (package:dio/src/Dio.dart:270:12)
<asynchronous suspension>
#9      Dio.get (package:dio/src/Dio.dart:62:12)
#10     UserApi.getUser (package:saytoken_flutter/ap<…>
```

**Comment by Yaxian** [comment]
Hi, @wendux 
I meet this issue with version `0.1.3`, when I call `dio.download` method.
env:
* dio: ^0.1.3
* Flutter: Channel beta, v0.5.1

but version `0.0.14` works fine.

**Comment by wendux** [comment]
@Yaxian  fixed, please update to 0.1.4  and try again.

**Comment by zhouxianjun** [comment]
在2.1.7版本中，使用lock并且使用泛型response则会导致类型不匹配错误，初步原因：
![image](https://user-images.githubusercontent.com/5254523/60778938-7a7b8a00-a16b-11e9-8d11-e70d681586cb.png)
在980行`enqueue`这个函数并没有声明泛型类型。
![image](https://user-images.githubusercontent.com/5254523/60778982-9bdc7600-a16b-11e9-9b90-24d294f6c19d.png)

**Comment by zhouxianjun** [comment]
@wendux 请查看下

**Comment by lucien-theron** [comment]
I get this exception by simply returning: `.catchError((error, stackTrace) => Future.error(error, stackTrace))`.

**Comment by Xgamefactory** [comment]
get same error while calling dio.delete with lates dio package.

`An error occurred. type 'Future<Response<dynamic>>' is not a subtype of type 'Response<dynamic>'`

**Comment by shliama** [comment]
I was getting this error too, right after adding token refresh `InterceptorsWrapper`. I noticed that this error occurs when Dio is locked. 

`An error occurred. type 'Future<Response<dynamic>>' is not a subtype of type 'Response<dynamic>'`

In order to fix it, I changed the signature of `_dispatchRequest` method inside `Dio.dart` from

`FutureOr<Response<T>> _dispatchRequest<T>(RequestOptions options)`

to

`FutureOr _dispatchRequest<T>(RequestOptions options)`

P.S. I have no idea what I'm doing :(

**Comment by eelishiram** [comment]
this error happens again in latest version of dio (v.3.0.10)

**Comment by aboutlan** [comment]
I ran into the same error when locked. Has anyone solved this error?

**Comment by codekeyz** [comment]
@eelishiram  This PR: https://github.com/flutterchina/dio/pull/1296 fixes this.
