### ISSUE TITLE
Big file upload causes memory leak, and crash the app (iOS)

### ISSUE THREAD

**Issue by janosdupai** [flutterchina/dio#1000]
I try to upload biggest videos to own server, catching the file with php.

Everything works like charm at smaller videos, but the biggest videos (>1GB) causes memory leak and crashes the app, on my testing device (2016 iPad Pro).

In optimal case the videos should be 70-100minutes long, so they are almost everytime bigger then 1GB.

Do you have any solution or idea?

**Comment by IMR707** [comment]
I am wondering about this as well, is there not an option where you can upload the file as a chunk?

When i tested upload a big file (about 1GB) as formdata, it eats around 1GB of my iOS device's RAM away. If there is not enough memory left, it will crash the app. I tested this on iPhone 6S Plus with 2GB RAM

I hope that developer will help clarify this if there is possible solution. If there is not, i hope that the developer will be able to add chunk upload options to help resolve big file issues.

**Comment by Morris-Mao** [comment]
Is there any solution?
