### ISSUE TITLE
android 11 Dio().download FileSystemException: Cannot create file 

### ISSUE THREAD

**Issue by songjiabin** [flutterchina/dio#1005]
e = {FileSystemException} FileSystemException: Cannot create file, path = '/storage/emulated/0/文件A/1.txt' (OS Error: Is a dir
 message = "Cannot create file"
 path = "/storage/emulated/0/文件A/1.txt"
 osError = {OSError} OS Error: Is a directory, errno = 21
  message = "Is a directory"
  errorCode = 21

**Comment by Joseph0717** [comment]
同问

**Comment by liuan3756** [comment]
problem still exists

**Comment by JuniorFlorentino** [comment]
the problem happens simply because the file name was not informed

from 
directory
to
directory + 'video.mp4

`Dio _dio = Dio();`

`final directory = Platform.isAndroid
        ? (await getExternalStorageDirectory())?.path
        : (await getApplicationDocumentsDirectory()).path;`

`Response response = await _dio.download(
          "url",
          directory + 'video.mp4',
          onReceiveProgress: showDownloadProgress);`

`void showDownloadProgress(received, total) {
    if (total != -1) {
      print((received / total * 100).toStringAsFixed(0) + '%');
    }
  }`

**Comment by huynguyennovem** [comment]
In my case, when the file name **contains a space** (for eg: `sample doc.txt`), the same error was fired. So my simple solution is removing all space on file name:

```dart
final trimmedFileName = file.metadata.name.replaceAll(' ', '_');
```

And then it worked well!

**Comment by liuan3756** [comment]
its a point need to be notice,but i believe it must be something else.thks dude





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nguyen Quang ***@***.***&gt;; 
发送时间: 2021年12月22日(星期三) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flutterchina/dio] android 11 Dio().download FileSystemException: Cannot create file  (#1005)





 
In my case, when the file name contains a space (for eg: sample doc.txt), the same error was fired. So my simple solution is removing all space on file name:
 final trimmedFileName = file.metadata.name.replaceAll(' ', '_');
 
And then it worked well!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jinbaolu** [comment]
so, is solved?

**Comment by liuan3756** [comment]
之前我用'/sdcard/xxx.apk'的下载路径，后来改成'${(await getApplicationDocumentsDirectory()).path}${xxxx}.apk'就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月14日(星期一) 晚上6:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flutterchina/dio] android 11 Dio().download FileSystemException: Cannot create file  (#1005)





 
so, is solved?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
