### ISSUE TITLE
dio 3.0.10上传文件后端拿不到

### ISSUE THREAD

**Issue by eatfishs** [flutterchina/dio#1010]
dio 3.0.10  配合 image_picker  0.6.7＋14
上传图片后端解析不到file
使用 dio 3.0.9 上传成功
FormData.fromMap({
    "file": await MultipartFile.fromFile("./text.txt",filename: "upload.txt"),
    "files": [
      await MultipartFile.fromFile("./text1.txt", filename: "text1.txt"),
      await MultipartFile.fromFile("./text2.txt", filename: "text2.txt"),
    ]
 })

**Comment by wyl86** [comment]
我用 MultipartFile.fromBytes 可以，记得带上文件名，不然还是不行。
final File file = File('xxx/xxx/xxx.jpg');
MultipartFile.fromBytes(file, basename(file.path));

**Comment by shizidada** [comment]
Multiple parameters use 'files[]'
