### ISSUE TITLE
How to send array to a form data?

### ISSUE THREAD

**Issue by MuhammadAliKust** [flutterchina/dio#1011]

**Comment by chen412115** [comment]
form-data中传递数组怎么做？

**Comment by jakaria-acd** [comment]
Use this:

FormData.fromMap(data, ListFormat.multiCompatible);

ListFormat.multiCompatible is the solution to add array in form data.

**Comment by JakariaAmin** [comment]
Use this:

`FormData.fromMap(data, ListFormat.multiCompatible);`

`ListFormat.multiCompatible` is the solution to add array in form data.
