### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by kaisawind** [flutterchina/dio#1019]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter/web/android                          |      |
| Platform Version               | 1.25.0-9.0.pre.42                              |      |
| Dio Version                    | ^3.0.10                                  |      |
| Android Studio / Xcode Version | vscode 1.51.1             |      |
| Repro rate                     | 100%   |      |
| Repro with our demo prj        | yes           |      |
| Demo project link              | yes |      |

### Issue Description and Steps

Is there already a plan to migrate this library to null safety?

**Comment by zepfietje** [comment]
@kaisawind this is a duplicate of https://github.com/flutterchina/dio/issues/1002.

**Comment by kaisawind** [comment]
this is a duplicate of #1002.
