### ISSUE TITLE
[Feature Request] Upload files using ByteData or List<int>

### ISSUE THREAD

**Issue by Mrigank11** [flutterchina/dio#102]
Currently, one can only upload files using a `File` object which makes it difficult to upload which are not in phone's storage(or getting a `File` object is not feasable). 

For example, [multi_image_picker](https://github.com/Sh1d0w/multi_image_picker) plugin returns a `ByteData`.

I think there should be an option to upload files using `List<int>`. Which will add possibilites to upload files from in-memory buffers as well.

**Comment by wendux** [comment]
Please update to 1.0.7 version and try again.

**Comment by Mrigank11** [comment]
Awesome! Thanks.

**Comment by john-ravi** [comment]
For Someone looking for extended answer:
      
      final buffer = byteData.buffer;

      FormData formData = new FormData.from({
        "image":
            new UploadFileInfo.fromBytes(asUint8List(buffer, byteData), 'somename.jpg')
      });

**Comment by ElyDantas** [comment]
UploadFileInfo and FormData.from is [deprecated](https://github.com/flutterchina/dio/issues/501)
And there's no clue in [documentation](https://github.com/flutterchina/dio#sending-formdata) about uploading bytes/Uint8List? Any suggestions?
