### ISSUE TITLE
while Making any Http Request on real device to server by using IP and port getting SocketException and wrong port number in logs 

### ISSUE THREAD

**Issue by zubairshahzad** [flutterchina/dio#1023]
i have created web service on my personal server in same network .. this web server is working fine and available on same network .
i have test with postman from android device . and i also create one native andorid application using java .its working fine in native android .

but in a flutter using dio, i have test three libraries getting below results please help to fix this issue

static String baseurl ="http://10.183.121.43:5000/";

try { Response response = await Dio().get(constant.baseurl+"hello/"); print(response); } catch (e) { print(e); }
try {
await RawSocket.connect("10.183.121.43", 5000);
} catch (e) {
print(e);
}

Error :
SocketException: OS Error: Connection timed out, errno = 110, address = 10.183.121.43, port = 55705

http: 0.12.2
logs:
git:
url: https://github.com/pq/logs.git
ref: master
rflutter_alert: 1.0.3
shared_preferences: 0.5.12+4
image_picker: 0.6.7+17
dio: 3.0.10
progress_dialog: 1.2.4
location: 3.0.0

**Comment by zubairshahzad** [comment]
Note : same thing when i am trying using ngrok tool and passing ngrok address its working perfectly in flutter .. but with server ip url its not working

**Comment by zubairshahzad** [comment]
@darshankawar
] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.14.6 18G5033
darwin-x64, locale en-GB)
• Flutter version 1.25.0-8.1.pre at /Volumes/datamix/flutersdk/flutter
• Framework revision 8f89f65 (3 weeks ago), 2020-12-15 15:07:52 -0800
• Engine revision 92ae191c17
• Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at /Users/zubairarain/Library/Android/sdk
• Platform android-30, build-tools 30.0.3
• ANDROID_HOME = /Users/zubairarain/Library/Android/sdk
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6915495)
! Some Android licenses not accepted. To resolve this, run: flutter doctor
--android-licenses

[!] Xcode - develop for iOS and macOS
✗ Xcode installation is incomplete; a full installation is necessary for iOS
development.
Download at: https://developer.apple.com/xcode/download/
Or install Xcode via the App Store.
Once installed, run:
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -runFirstLaunch
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.47.3)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.13.2

[✓] Connected device (1 available)
• SM P555 (mobile) • 1c723593 • android-arm • Android 7.1.1 (API 25)

**Comment by zubairshahzad** [comment]
I just created a simple get request on the server-side .. this server available on the same network. I tried volley library in android native and in URL I am passing like http://10.183.121.43:5000/hello its working perfectly
but same this i did in a flutter by using dio, HTTP same URL http://10.183.121.43:5000/hello
i am getting this error
DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection timed out, errno = 110, address = 10.183.121.43, port = 37214

Actually, its change port number if you notice in url port no is 5000 and in logs it is port = 37214

note: if I am doing with domain name URL its working fine but by passing ip and port number its changing port number in logs

minimum code for testing ..
just create one get request on server-side and create one flutter application and try to access this application by IP and Port number ...

Future<List<Map<String, dynamic>>> fetch() async {
try {
Response response = await Dio().get("http://10.183.121.43:5000/hello");
print(response.toString());
} catch (e) {
print(e);
}

}

**Comment by zubairshahzad** [comment]
https://github.com/flutter/flutter/issues/73325

**Comment by paintingStyle** [comment]
<img width="1592" alt="image" src="https://user-images.githubusercontent.com/22866404/118207334-06147f00-b497-11eb-861c-e1135d753fe1.png">


I also encountered the same problem. When connecting to the local server, sometimes it will time out, and the port is inconsistent with the requested port

dio: 3.0.10

**Comment by panyamred** [comment]
This is still happening, I'm using latest version: 4.0.6.

**Comment by darul9061** [comment]
This issues still persist. Any solution?

**Comment by AlexV525** [comment]
The port is not the target port but a local port that sends the request. Do not reference it as the request-target port.
