### ISSUE TITLE
HandshakeException: Connection terminated during handshake

### ISSUE THREAD

**Issue by fengerwoo** [flutterchina/dio#1028]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios / android                          |      |
| Platform Version               | e.g.  1.22.5 /      / 11.0                              |      |
| Dio Version                    | e.g.  3.0.10                                 |      |
| Android Studio / Xcode Version | e.g. Android Studio 4.1.1              |      |
| Repro rate                     | e.g. 50%   |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps

Post 请求 https://api.ucenter.mayiwabao.com 时，有50%的几率报错：HandshakeException: Connection terminated during handshake

完整日志如下
```
E/flutter ( 9437): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: DioError [DioErrorType.DEFAULT]: HandshakeException: Connection terminated during handshake, stack trace: #0      DioMixin._request._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:870:17)
E/flutter ( 9437): #1      _RootZone.runUnary (dart:async/zone.dart:1450:54)
E/flutter ( 9437): #2      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 9437): #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 9437): #4      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 9437): #5      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 9437): #6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 9437): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 9437): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 9437): 
```

**Comment by nttra83** [comment]
Yes. I faced the same issue.

**Comment by kazbeksultanov** [comment]
In our project we also faced with this error. Any idea how to fix?

**Comment by javdev** [comment]
same problem here, no solution???

**Comment by javdev** [comment]
got a solution, that worked for me: I deleted the emulators and then created new emulators. Then it worked again.

**Comment by akshg05** [comment]
@javdev  Can you share your emulator configuration please?

**Comment by SinoMiles** [comment]
same issue.

**Comment by sqrg** [comment]
Any fixes?

**Comment by tanlianghao** [comment]
same problem here, no solution???

**Comment by Nafalaly** [comment]
Any Solution please ?

**Comment by Howard2595** [comment]
Change the time of the device and send the request again to have this problem.

**Comment by walterpa1952** [comment]
Solved that problem for me by adding the following to the AndroidManifest.xml file in android/app/src/main package/directory.  Added before <application ..... </application>

    <uses-permission android:name="android.permission.INTERNET" />

Hope this works for you.

**Comment by hamidwaezi** [comment]
i face this issue ...

**Comment by WoodyHang** [comment]
> 

Thank you. That solved my problem

**Comment by WoodyHang** [comment]
> Solved that problem for me by adding the following to the AndroidManifest.xml file in android/app/src/main package/directory. Added before <application .....
> 
> ```
> <uses-permission android:name="android.permission.INTERNET" />
> ```
> 
> Hope this works for you.

Thank you. That solved my problem

**Comment by datpt11** [comment]
SAME ISSUE

**Comment by Moonwing2020** [comment]
SAME ISSUE  is there any solution?
