### ISSUE TITLE
POST json array with formdata

### ISSUE THREAD

**Issue by jitendrapurohit12** [flutterchina/dio#1029]
Hey, I want to send a File with a complex JSON object containing JSON Array. How can I do it?

![Screenshot 2021-01-15 at 3 26 52 PM](https://user-images.githubusercontent.com/7421550/104710562-3b59cc00-5746-11eb-97eb-c78144d164f2.png)

I want to send this kind of FormData.
Here is how I have implemented it:

`final data = {
      "id": 60,
      "first_name": "Amit",
      "last_name": "Sharma",
      "email": "j.purohit198@gmail.com",
      "phone_no": "9506948522",
      "addr": "Lko",
      "status": "VERIFIED",
      "total_funds": 0,
      "bankDetails": [
        {"name": "ASD", "acc": "123"},
        {"name": "ASDFG", "acc": "1234"}
      ]
    };`
    `if (file != null) {
      data['pic'] =
          MultipartFile.fromFileSync(file.path, filename: 'profile_image');
    }`
    `final formData = FormData.fromMap(data);`

**Comment by JakariaAmin** [comment]
Use this:

`FormData.fromMap(data, ListFormat.multiCompatible);`

`ListFormat.multiCompatible` is the solution to add array in form data.

**Comment by iamjohnvesly** [comment]
> Use this:
> 
> `FormData.fromMap(data, ListFormat.multiCompatible);`
> 
> `ListFormat.multiCompatible` is the solution to add array in form data.
Thank you
