### ISSUE TITLE
Progress event(s) for FormData requests

### ISSUE THREAD

**Issue by jagged3dge** [flutterchina/dio#103]
Hi! Thank you for creating this package, it's a lifesaver when it comes to generic multipart/formdata requests.

Is there a way to consume file upload progress event(s)?

Consider this a feature request, if it doesn't exist yet, or please point me in a direction if it's possible to implement

**Comment by awazgyawali** [comment]
Want the same.

**Comment by jagged3dge** [comment]
I'm afraid I haven't. I couldn't pursue it further due to limited time constraints. I'm hoping package authoring team might have some pointers

**Comment by wendux** [comment]
I have no idea about it yet, because neither `HttpClientRequest` nor `HttpClient` didn't  provide some way to listen the progress event.

**Comment by salk52** [comment]
I made sample app which shows how to implement upload/download with progress bar, so maybe you find it useful to make dio.fileupload.

https://github.com/salk52/Flutter-File-Upload-Download

**Comment by salk52** [comment]
Yes, you are right.  But nevertheless this still works for displaying progess and I'll try to explain why. First of all sink.add(data); should be call first, then  onUploadProgress(byteCount, totalByteLength);

Calling sink.close(); is crucial for this example. Stream reads bytes in chunks and transforms them into network stream by sink.close() which is synchronous call. So if sink.close() cant add bytes to underlaying network stream it will throw an exception. So if you start uplading 100 MB file, and you turn off wifi on emulator/phone, the progress will stop. So you indirectly know that bytes are sent or not.

**Comment by wendux** [comment]
fixed! 
```dart
response = await dio.post(
  "http://www.dtworkroom.com/doris/1/2.0.0/test",
  data: {"aa": "bb" * 22},
  onUploadProgress: (int sent, int total) {
    print("$sent $total");
  },
);
```

**Comment by Xgamefactory** [comment]
> ```dart
> onUploadProgress
> ```

is it possible to connect this upload progress with a steam to handle on our bloc part for displaying progress instead a callbak ?

**Comment by EdgarMagalhaes** [comment]
> > ```dart
> > onUploadProgress
> > ```
> 
> is it possible to connect this upload progress with a steam to handle on our bloc part for displaying progress instead a callbak ?

I have the same question. I wanted to yield state updates with the current download progress but it seems that it's only a callback. Any ideas on implementing this in a future release?

**Comment by EdgarMagalhaes** [comment]
Ok, so I searched around and stumbled across this [answer](https://stackoverflow.com/a/56927006/3419447).
So you can create a StreamController before your request and add events via **onReceiveProgress** callback. I did this for downloading, I guess you can also do it for uploading.
This worked for me. Hope it helps someone. 
```dart
StreamController<int> progressStreamController = new StreamController();
dio.get(
  event.url,
  onReceiveProgress: (received, total) {
      progressStreamController.add(((received / total) * 100).round());
  },
  options: Options(
      responseType: ResponseType.bytes,
      followRedirects: false,
      validateStatus: (status) {
          return status < 500;
      }),
).then((Response response) async {
  //Do whatever you want with the response
}).whenComplete(() => progressStreamController.close());

await for (int p in progressStreamController.stream) {
    yield DownloadingUpdate(progress: p);
}
```

**Comment by Kamoba** [comment]
> ```dart
>   onUploadProgress: (int sent, int total) {
>     print("$sent $total");
>   },
> ```

Where is from this `onUploadProgress` i updated to the last version `dio: ^4.0.0` and still have `The named parameter 'onUploadProgress' isn't defined.`.

**Comment by ariefwijaya** [comment]
> > ```dart
> >   onUploadProgress: (int sent, int total) {
> >     print("$sent $total");
> >   },
> > ```
> 
> Where is from this `onUploadProgress` i updated to the last version `dio: ^4.0.0` and still have `The named parameter 'onUploadProgress' isn't defined.`.
> 
> Ok i use:
> 
> ```
> Dio().download(serverName+'/download', savePath,
>       options: Options(method: 'POST', headers: {HttpHeaders.acceptEncodingHeader: "*"},), 
>       data:  FormData.fromMap(params),
>       onReceiveProgress: (received, total) {
>         callBack(received, total);
>       });
> ```

How about on uploading progress?

**Comment by Jaidyn-B** [comment]
@ariefwijaya From their docs it looks like you use the onSendProgress method in a POST request:

`response = await dio.post(
  'http://www.dtworkroom.com/doris/1/2.0.0/test',
  data: {'aa': 'bb' * 22},
  onSendProgress: (int sent, int total) {
    print('$sent $total');
  },
);`
