### ISSUE TITLE
Always get "Unsupported operation: Platform._version" when using Dio in web

### ISSUE THREAD

**Issue by anoreg** [flutterchina/dio#1030]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Flutter                         |      |
| Platform Version               |  Flutter 1.25.0-8.2.pre • channel beta Framework • revision b0a2299859 Engine • revision 92ae191c17 Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)                             |      |
| Dio Version                    | 3.0.10                                  |      |
| Android Studio Version | 4.1.1              |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        | does it happen with our demo project            |      |

### Issue Description and Steps
When run for Chrome, the http request always show such error:
`
DioError [DioErrorType.DEFAULT]: Unsupported operation: Platform._version
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49     throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 289:5                  _version
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform_impl.dart 119:32                                        get version
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 68:37                                              get _version
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 802:8  get
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 225:32                                             get version
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http_impl.dart 3499:26                                        _getHttpVersion
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http_impl.dart 2296:23                                        new
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http.dart 1563:18                                             new
packages/dio/src/adapters/io_adapter.dart 121:28                                                                              [_configHttpClient]
packages/dio/src/adapters/io_adapter.dart 34:23                                                                               fetch
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54               runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:12              _async
packages/dio/src/adapters/io_adapter.dart 25:29                                                                               fetch
packages/dio/src/dio.dart 922:46                                                                                              _dispatchRequest
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50               <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1446:54                                             runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 150:18                                       handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 703:44                                       handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 732:32                                       _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 536:5                                        [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 574:7                                        callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 41:11                                 _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 50:5                                  _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15              <fn>
`

Here is the http client that I  created:
```
class DefaultDioClient with DioMixin {
  DefaultDioClient() {
    Log.i("Create Dio@$identify");
    //Options
    options = createOptions(_baseOptions);
    //Interceptors
    interceptors.add(DefaultDioLogInterceptor());
    //Adapter
    httpClientAdapter = createClientAdapter();
  }

  final BaseOptions _baseOptions = BaseOptions(
    baseUrl: "",
    connectTimeout: DEFAULT_TIMEOUT,
    sendTimeout: DEFAULT_TIMEOUT,
    receiveTimeout: DEFAULT_TIMEOUT,
  );

  @protected
  BaseOptions createOptions(BaseOptions baseOptions) {
    return baseOptions;
  }

  @protected
  HttpClientAdapter createClientAdapter() {
    //http2
    // return Http2Adapter(createConnectionManager());
    //http1
    return DefaultHttpClientAdapter()
      ..onHttpClientCreate = (HttpClient client) {
        onHttpClientCreate(client);
      };
  }

  @mustCallSuper
  @protected
  void onHttpClientCreate(HttpClient client) {
    Log.v("Socket create@$identify");
  }

  dynamic get identify {
    return hashCode;
  }
}
```

What I checked is when sending a request, it will invoke this method in "http_impl.dart" which will cause the error
```
String? userAgent = _getHttpVersion();
...
String _getHttpVersion() {
  var version = Platform.version;
  // Only include major and minor version numbers.
  int index = version.indexOf('.', version.indexOf('.') + 1);
  version = version.substring(0, index);
  return 'Dart/$version (dart:io)';
}
```

**Comment by manhluong** [comment]
I am having similar error when using dio with dart2js:

```
Decision response error: DioError [DioErrorType.DEFAULT]: Unsupported operation: Platform._version
Unsupported operation: Platform._version
    at Object.wrapException (http://localhost:3000/static/js/vendors~main.chunk.js:3036:17)
    at Object._Platform__version (http://localhost:3000/static/js/vendors~main.chunk.js:9419:15)
    at Object._Platform_version (http://localhost:3000/static/js/vendors~main.chunk.js:9468:16)
    at http://localhost:3000/static/js/vendors~main.chunk.js:29598:16
    at Object.holder.<computed> [as $get$Platform__version] (http://localhost:3000/static/js/vendors~main.chunk.js:993:66)
    at Object.HttpClient_HttpClient (http://localhost:3000/static/js/vendors~main.chunk.js:1230:19)
    at DefaultHttpClientAdapter._configHttpClient$2 (http://localhost:3000/static/js/vendors~main.chunk.js:24476:16)
    at http://localhost:3000/static/js/vendors~main.chunk.js:24348:41
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:3000/static/js/vendors~main.chunk.js:5987:13)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:3000/static/js/vendors~main.chunk.js:17055:12)
    at Object._asyncStartSync (http://localhost:3000/static/js/vendors~main.chunk.js:5954:20)
    at DefaultHttpClientAdapter.fetch$body$DefaultHttpClientAdapter (http://localhost:3000/static/js/vendors~main.chunk.js:24469:16)
    at DefaultHttpClientAdapter.fetch$3 (http://localhost:3000/static/js/vendors~main.chunk.js:24309:19)
    at http://localhost:3000/static/js/vendors~main.chunk.js:24694:37
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:3000/static/js/vendors~main.chunk.js:5987:13)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:3000/static/js/vendors~main.chunk.js:17055:12)
    at _awaitOnObject_closure.call$1 (http://localhost:3000/static/js/vendors~main.chunk.js:17041:32)
    at _RootZone.runUnary$2$2 (http://localhost:3000/static/js/vendors~main.chunk.js:19773:55)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:3000/static/js/vendors~main.chunk.js:17942:51)
    at Object._Future__propagateToListeners (http://localhost:3000/static/js/vendors~main.chunk.js:6217:111)
    at _Future._completeWithValue$1 (http://localhost:3000/static/js/vendors~main.chunk.js:17731:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:3000/static/js/vendors~main.chunk.js:17028:82)
    at Object._asyncReturn (http://localhost:3000/static/js/vendors~main.chunk.js:5962:17)
    at http://localhost:3000/static/js/vendors~main.chunk.js:24901:22
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:3000/static/js/vendors~main.chunk.js:5987:13)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:3000/static/js/vendors~main.chunk.js:17055:12)
    at _awaitOnObject_closure.call$1 (http://localhost:3000/static/js/vendors~main.chunk.js:17041:32)
    at _RootZone.runUnary$2$2 (http://localhost:3000/static/js/vendors~main.chunk.js:19773:55)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:3000/static/js/vendors~main.chunk.js:17942:51)
    at Object._Future__propagateToListeners (http://localhost:3000/static/js/vendors~main.chunk.js:6217:111)
    at _Future._completeWithValue$1 (http://localhost:3000/static/js/vendors~main.chunk.js:17731:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:3000/static/js/vendors~main.chunk.js:17860:18)
    at Object._microtaskLoop (http://localhost:3000/static/js/vendors~main.chunk.js:6277:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:3000/static/js/vendors~main.chunk.js:6284:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:3000/static/js/vendors~main.chunk.js:16965:9)
    at invokeClosure (http://localhost:3000/static/js/vendors~main.chunk.js:3244:26)
    at MutationObserver.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:3266:18)
```

**Comment by manhluong** [comment]
Nevermind me: I simply need to use [`BrowserHttpClientAdapter`](https://github.com/flutterchina/dio/blob/master/dio/lib/src/adapters/browser_adapter.dart) instead of `DefaultHttpClientAdapter`.

**Comment by huangbinjie** [comment]
Same issue here... have any plan to fix it?

**Comment by jerryrt** [comment]
I am hit hard by this issue in the middle of one project. This issue is still blocking the adoption of Flutter web project. I am wondering if there is any workaround of this? Or everybody is waiting for a very fundamental component?

**Comment by Pro-Z** [comment]
> ### Issue Info
> Info	Value	
> Platform Name	Flutter	
> Platform Version	Flutter 1.25.0-8.2.pre • channel beta Framework • revision b0a2299859 Engine • revision 92ae191c17 Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)	
> Dio Version	3.0.10	
> Android Studio Version	4.1.1	
> Repro rate	all the time (100%)	
> Repro with our demo prj	does it happen with our demo project	
> ### Issue Description and Steps
> When run for Chrome, the http request always show such error:
> `DioError [DioErrorType.DEFAULT]: Unsupported operation: Platform._version C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49 throw_ C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 289:5 _version C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform_impl.dart 119:32 get version C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 68:37 get _version C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 802:8 get C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 225:32 get version C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http_impl.dart 3499:26 _getHttpVersion C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http_impl.dart 2296:23 new C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http.dart 1563:18 new packages/dio/src/adapters/io_adapter.dart 121:28 [_configHttpClient] packages/dio/src/adapters/io_adapter.dart 34:23 fetch C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54 runBody C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:12 _async packages/dio/src/adapters/io_adapter.dart 25:29 fetch packages/dio/src/dio.dart 922:46 _dispatchRequest C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50 <fn> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1446:54 runUnary C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 150:18 handleValue C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 703:44 handleValueCallback C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 732:32 _propagateToListeners C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 536:5 [_completeWithValue] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 574:7 callback C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 41:11 _microtaskLoop C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 50:5 _startMicrotaskLoop C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15 <fn>`
> 
> Here is the http client that I created:
> 
> ```
> class DefaultDioClient with DioMixin {
>   DefaultDioClient() {
>     Log.i("Create Dio@$identify");
>     //Options
>     options = createOptions(_baseOptions);
>     //Interceptors
>     interceptors.add(DefaultDioLogInterceptor());
>     //Adapter
>     httpClientAdapter = createClientAdapter();
>   }
> 
>   final BaseOptions _baseOptions = BaseOptions(
>     baseUrl: "",
>     connectTimeout: DEFAULT_TIMEOUT,
>     sendTimeout: DEFAULT_TIMEOUT,
>     receiveTimeout: DEFAULT_TIMEOUT,
>   );
> 
>   @protected
>   BaseOptions createOptions(BaseOptions baseOptions) {
>     return baseOptions;
>   }
> 
>   @protected
>   HttpClientAdapter createClientAdapter() {
>     //http2
>     // return Http2Adapter(createConnectionManager());
>     //http1
>     return DefaultHttpClientAdapter()
>       ..onHttpClientCreate = (HttpClient client) {
>         onHttpClientCreate(client);
>       };
>   }
> 
>   @mustCallSuper
>   @protected
>   void onHttpClientCreate(HttpClient client) {
>     Log.v("Socket create@$identify");
>   }
> 
>   dynamic get identify {
>     return hashCode;
>   }
> }
> ```
> 
> What I checked is when sending a request, it will invoke this method in "http_impl.dart" which will cause the error
> 
> ```
> String? userAgent = _getHttpVersion();
> ...
> String _getHttpVersion() {
>   var version = Platform.version;
>   // Only include major and minor version numbers.
>   int index = version.indexOf('.', version.indexOf('.') + 1);
>   version = version.substring(0, index);
>   return 'Dart/$version (dart:io)';
> }
> ```

![1629257785(1)](https://user-images.githubusercontent.com/7971615/129832979-c99d7d43-90a7-40b1-92db-ffb5858fc3fb.png)

It seems that the DefaultHttpClientAdapter cause this problem...

**Comment by cardinalblues7** [comment]
Still got the same issue, how come this has already been marked closed???

**Comment by SYThomasNordmeyer** [comment]
Having same issue. 
This ticket is closed, can anyone post the solution? Pleas tell us, even if it's stupid and simple.

**Comment by vhdrjb** [comment]
I had the same issue. Project works fine on mobile but fails on Web. as @Pro-Z mentioned you should change adapter for web : 

`    HttpClientAdapter client;
    if (kIsWeb) {
      client = BrowserHttpClientAdapter();
    }else {
       client = DefaultHttpClientAdapter()..onHttpClientCreate = (client) {
        client..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
      };
    }

Dio dioInstance =       Dio()
        ..options.baseUrl = config.baseUrl
        ..options.connectTimeout = config.connectionTimeout
        ..options.receiveTimeout = config.readTimeout
        ..httpClientAdapter = client
        ..interceptors.addAll(config.interceptors),
    );
`

this solved for me

**Comment by vhdrjb** [comment]
hey @pedrodarma 
you should share your code between native app and web. import the basic dio `import 'package:dio/dio.dart';` and  instead of passing `DefaultHttpClientAdapter ` or `BrowserHttpClientAdapter ` pass the `HttpClientAdapter` :

`unsupported.dart` : 

`
import 'package:dio/dio.dart';

HttpClientAdapter getAdapter() {
  throw 'unsupported platform';
}
`
then create adapter for mobile apps :

`mobile_adapter.dart`  :

`import 'dart:io';

import 'package:dio/adapter.dart';
import 'package:dio/dio.dart';

HttpClientAdapter getAdapter() {
  return DefaultHttpClientAdapter()..onHttpClientCreate = (client) {
    client..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  };
}`

and for web apps :

`web_adapter.dart` : 

`import 'package:dio/adapter_browser.dart';
import 'package:dio/dio.dart';

HttpClientAdapter getAdapter() {
  return BrowserHttpClientAdapter();
}
`
create share file to handle platform automatically :

`shared.dart` : 

`export 'unsupported.dart'
if (dart.library.html) 'web_adapter.dart'
if (dart.library.io) 'mobile_adapter.dart';
`

and use it : 

```
import 'adapter/shared.dart';
import 'package:dio/dio.dart'

    NetworkConfig config = get();
    HttpClientAdapter client =  getAdapter();

      Dio()
        ..options.baseUrl = config.baseUrl
        ..options.connectTimeout = config.connectionTimeout
        ..options.receiveTimeout = config.readTimeout
        ..httpClientAdapter = client
        ..interceptors.addAll(config.interceptors);

```

**Comment by vhdrjb** [comment]
hey @pedrodarma
you should share your code between native app and web. import the basic dio import 'package:dio/dio.dart'; and instead of passing `DefaultHttpClientAdapter` or `BrowserHttpClientAdapter` pass the `HttpClientAdapter` :

`unsupported.dart` :

```
import 'package:dio/dio.dart';

HttpClientAdapter getAdapter() {
throw 'unsupported platform';
}

```
then create adapter for mobile apps :

`mobile_adapter.dart `:

```
import 'dart:io';

import 'package:dio/adapter.dart';
import 'package:dio/dio.dart';

HttpClientAdapter getAdapter() {
return DefaultHttpClientAdapter()..onHttpClientCreate = (client) {
client..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
};
}
```

and for web apps :

`web_adapter.dart` :

```
import 'package:dio/adapter_browser.dart';
import 'package:dio/dio.dart';

HttpClientAdapter getAdapter() {
return BrowserHttpClientAdapter();
}
```

create share file to handle platform automatically :

`shared.dart `:

```
export 'unsupported.dart'
if (dart.library.html) 'web/web_adapter.dart'
if (dart.library.io) 'mobile/mobile_adapter.dart';

```

and use it :

```
import 'adapter/shared.dart';
import 'package:dio/dio.dart'

    NetworkConfig config = get();
    HttpClientAdapter client =  getAdapter();

      Dio()
        ..options.baseUrl = config.baseUrl
        ..options.connectTimeout = config.connectionTimeout
        ..options.receiveTimeout = config.readTimeout
        ..httpClientAdapter = client
        ..interceptors.addAll(config.interceptors);
```

**Comment by huangbinjie** [comment]
I found Dio doesn't choose the proper `HttpClientAdapter` automatically. you cant even import the `dart.library.io` package on Web.

**Comment by ali-1989** [comment]
I comment this line

`client = HttpClient(context: httpItem.sslContext);`

and solved my this problem.
