### ISSUE TITLE
Dio replace comma-separated(,) with %2C in queryparameters.

### ISSUE THREAD

**Issue by DhavalRKansara** [flutterchina/dio#1032]
My Requirement is to pass below JSON in the query parameters but it replaces comma-separated(,) with%2C.

`Map<String,dynamic> queryParams = {'values': "1,2"};
`

- Expected URL after adding queryParams: 

> https://myurl:port/path?values='1,2'

- Url which I get using dio is: 

> https://myurl:port/path??values=1%2C2

Please help me out with this issue.

**Comment by kuhnroyal** [comment]
If you want to submit a list which it seems like, then you should use `{'values': [1,2]}` and the newly added (in 4.0.0) `ListFormat.csv`. Or with #1063 now merged you can soon do this: `{'values': MultiParam<int>([1,2], ListFormat.csv)}`.
