### ISSUE TITLE
Cannot POST binary data as body

### ISSUE THREAD

**Issue by tusharsadhwani** [flutterchina/dio#1036]
Uint8List 作为 `POST` 或 `PUT` 请求的 data 时会被转换成List<Int>的字符串，因此无法 POST/PUT 二进制数据。例如：

```dart
final response= await dio.put(
  url,
  data: File(filePath).readAsBytesSync(),
);
```

以上代码应该POST二进制数据，而收到的却是 `[127, 56, 14, 199...` 等。

**Comment by wendux** [comment]
Sending  Uint8List directly is not supported, please use Stream or FormData instead:
```dart
   var file = File(filePath)
    var r = await dio.put(
      url,
      data: f.openRead(),
      options: Options(
        contentType: 'application/octet-stream', // set right content-type
        headers: {
          Headers.contentLengthHeader: f.lengthSync(), // set content-length
        },
      ),
    );
```

**Comment by tusharsadhwani** [comment]
@wendux thanks for the response, but it seems that dio is no longer maintained, and I've already started migration to http instead.
