### ISSUE TITLE
Documentation , behaviour on mutiple request

### ISSUE THREAD

**Issue by billywatsy** [flutterchina/dio#1037]
thank you for the wonderful library , 

l have a question what is the behaviour of the concurrent request 

`response = await Future.wait([dio.post("/info"), dio.get("/token")]);
`

if l have more than 12 array of request ,  does the library have ie max of 4 and it will add more to the concurrent but keeping a max of 4 till it does all 12 of them or it just make them all at once , please advice

this will help if l can handle this logic on my own or its the library that does that 

Thanks

**Comment by hoc081098** [comment]
```dart
Future<List<T>> chunkedWait<T>(
  List<Future<T> Function()> futureFactories,
  int chunkedSize,
) async {
  final result = List<T>.filled(futureFactories.length, null);

  for (var i = 0; i < futureFactories.length; i += chunkedSize) {
    final end = min(futureFactories.length, i + chunkedSize);
    final chunkResult = await Future.wait(
      [for (var j = i; j < end; j++) futureFactories[j]()],
      eagerError: true,
    );
    result.setRange(i, end, chunkResult);
  }

  return result;
}
```

**Comment by hoc081098** [comment]
Using
```dart
Future<String> request(int i) async {
    return 'demo';
}

final List<String> strings = await chunkedWait(
  [
     for(var i = 0; i < 12; i++)
        () => request(i),
  ],
  4,
);
```
