### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: Hostname mismatch with valid certificate

### ISSUE THREAD

**Issue by Giles-W** [flutterchina/dio#1038]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter, ios & android app                         |      |
| Platform Version               | e.g.  1.22.2                             |      |
| Dio Version                    | e.g.  3.0.9                                  |      |
| Visual Studio Code | e.g. 1.52.1             |      |

### Issue Description and Steps

Our App connects to our API server which behind a Load Balancer. The Load Balancer uses a Certificate issued to a single CN, the SAN has multiple entries including a wildcard entry which matches the hostname of the server we are connecting to via DIO. e.g. *.domain.com with hostname = app_host.domain.com. (fictitious for purposes of post)

When I test the connection to the host using `openssl s_client -host app_host.domain.com -port 8443 -verify_return_error`  the connection succeeds and no errors are returned. When we connect using the below, we are forced to load our cert in manually as the badCertificateCallback is always called with the reason being a hostname mismatch.
```
    HttpClient httpClient = new HttpClient(context: SecurityContext.defaultContext);
      httpClient.badCertificateCallback =
          (X509Certificate cert, String host, int port) {
        if (myCert == cert.pem) {
          return true;
        }
```
The documentation on certificate validation is so light wait that I cannot find any information on how to further diagnose what is going wrong here. This is an extremely frustraiting problem as our certificate is automatically renewed and update on LB annually and as soon as that happens, our app cannot connect until we successfully publish an update which includes the latest version of myCert. 

What am I missing that DIO fails to verify our certificate using the default security Context. FYI: The certificate chain for the cert includes a global root certificate issuance provider. The final issuer is Amazon with the root being Starfield Class 2 Certification Authority.

**Comment by AlexQuidditch** [comment]
I faced the same issue

**Comment by GanievRenat** [comment]
I faced the same issue

**Comment by Giles-W** [comment]
Would be great if someone could actually look at this one....

**Comment by im-v** [comment]
Please use this 
https://github.com/dart-lang/io/issues/83#issuecomment-936130566

**Comment by jgoyvaerts** [comment]
@Giles-W A certificate error is not the responsibility of the library you're using to connect to a server. If you would have tried to use the native http library, you would have noticed that you would receive the same error, thus concluding you that the problem is not with dio and your frustrations should not be aimed at this package.

**Comment by Giles-W** [comment]
When it takes 11 months for anyone in the community to even reply to the thread. I think I totally justified in being frustrated with the package and the community that supports it.

To blame the native http library is, I believe inaccurate and a cop out. The wild card certificates are  used extensively within our Web infrastructure and WebViews within our apps have no problem accepting the certificate on iOS and Android alike. 

I believe this is a DIO problem.

**Comment by im-v** [comment]
Hi @Giles-W 

There is some issue with old android devices which don't have this certificate and iPhone devices running less than iOS 10.
There is one certificate called "DST Root CA X3" which expired in September 2021 (This is a global certificate used by billions)
Previously google add this certificate into their phone and when some service wants to use this certificate then they can use the certificate and make an API call and other stuff.
But as the certificate expires which makes the android device prior to android 7.1.1 doesn't have an alternate certificate to make an API call to authenticate the API calls which sign by counter key.
So if any user belongs to this android version ( Android 6 and Android 7) is not able to use your app at all.

https://www.thekashmirmonitor.net/if-you-have-any-of-these-android-ios-and-windows-phones-you-will-lose-your-internet-connection/

The solution will be to add an alternate certificate and make a call.

  `   
   
       (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
           (client) async {
          
          SecurityContext sc = SecurityContext();
          ByteData data =. await PlatformAssetBundle().load('assets/ca/lets-encrypt-r3.pem');
          SecurityContext.defaultContext.setTrustedCertificatesBytes(data.buffer.asUint8List());

        HttpClient httpClient = HttpClient(context: sc);
        return httpClient;
      }; `
      
  download "lets-encrypt-r3.pem" this from below site
  https://letsencrypt.org/certificates/

**Comment by Giles-W** [comment]
@im-v I believe you are misunderstanding the issue, which was logged long before the "DST Root CA X3" expired.

We're talking about wild card certificates e.g. `*.example.com` in the cert not being matched to `host1.example.com`. 

The validity of the certificate and it's chain is not the issue.

**Comment by Giles-W** [comment]
> @Giles-W Please provide a minimal code sample and an api to reproduce the issue, if not, we can't help you.

Not sure that I follow you. Is what was provided in the initial report not sufficient. If not, what exactly is it lacking. "An API" is pretty meaningless...

**Comment by jgoyvaerts** [comment]
Please write a minimal main.dart file in a comment, which when run by me will reproduce the issue you are having. This means the minimal main.dart file should use dio, talk to your website/API or any website/API which gives the same exception.

I'm still positive this is not a Dio issue, but I can't prove it to you until you provide us with a code sample which reproduces your problem.

**Comment by Giles-W** [comment]
The simplest test I can think of, would be to try and use DIO to connect to `www.google.com` as this also uses a wild card certificate

**Comment by jgoyvaerts** [comment]
This will be my last comment on this issue because you seem to be missing the point.

**You** have an issue, which you **THINK** is caused by the Dio library. It's not our job to chase and debug your issues. If you want us to invest any time in this, you can provide an **actual code sample in dart** which I can copy paste in my editor and run which **exactly** reproduces the issue you're having.

Connecting to google with dio works just fine, so obviously that's NOT the example you should be providing.

**Comment by bluemix** [comment]
> 

Solved my problem. Thanks
