### ISSUE TITLE
[proposal] add `https/3` support

### ISSUE THREAD

**Issue by iapicca** [flutterchina/dio#1041]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### proposal

please consider adding support for [http/3](https://en.wikipedia.org/wiki/HTTP/3) 
as it's unlikely that any first party support will be offered in the short term https://github.com/dart-lang/sdk/issues/38595
imho it would be great if the effort would be undertaken together with the `flutter community` https://github.com/fluttercommunity/community/issues/59

**Comment by wendux** [comment]
Sorry, we have no plans to support http3 at the moment, because it is a very big project 🤣。

**Comment by gustav3d** [comment]
Thanks for being honest.

**Comment by iapicca** [comment]
> Thanks for being honest.

I agree with @gustav3d 
I'm old enough to accept `no` as an answer :)
thank you @wendux

**Comment by Dhruv-Garg79** [comment]
Hey @wendux I love Dio. Do you think there is a possibility of HTTP/3 support in the near future since QUIC is a little bit more mature now?
