### ISSUE TITLE
dio支持mac的网络请求吗

### ISSUE THREAD

**Issue by 9527001** [flutterchina/dio#1043]
### 报错
SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = bop189.jvtd.cn, port = 443

### doctor
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.2 20D64 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.45.1)

**Comment by GrapevineLin** [comment]
你是怎么解决的呀
