### ISSUE TITLE
Dio.download - Access response in the savePath callback?

### ISSUE THREAD

**Issue by japostoles** [flutterchina/dio#1044]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / ios                         |      |
| Platform Version               | 1.22.5                              |      |
| Dio Version                    | 3.0.10                                  |      |

### Issue Description and Steps

Is it possible to access the request object in the Dio.download() savePath callback?  Currently it provides access to the Headers, but that doesn't have the information I need.

I'm trying to download a file that involves a redirect, and I would like to return the name of the basename of the redirect url, not the original,.

For example:  https://whatever.com/file/download  redirects to s3.amazonaws.com/somefile.jpg .  I would like to set savePath to "somefile.jpg", but I don't seem to have access to the redirected URL in the savePath callback -- I believe access to the redirected request would contain this.  

Thank you!

**Comment by wendux** [comment]
There are two extra info for download API  in 4.0.0-beta4:

```dart
var r = await Dio().download(
  uri,
  (Headers headers) {
    // redirect counts
    print(headers.value('redirects'));
    // real uri
    print(headers.value('uri'));
  },
);
```
