### ISSUE TITLE
error DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength. 1930202 bytes written while expected 1902606. [PNG

### ISSUE THREAD

**Issue by jinnyum** [flutterchina/dio#1050]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |android                          |      |
| Platform Version               | 10                              |      |
| Dio Version                    | 3.0.10                                  |      |
| Android Studio / Xcode Version | Android Studio 4.1.2              |      |
| Repro rate                     |  sometimes   |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps

      FormData formData = FormData.fromMap({
        "id": id.toString(),
        "imgFiles": files,
        "imgThumbFiles": thumbFiles
      });

 var response = await dio.post("http://www.myhome.com/imgreg.php", data: formData);

error DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength. 1930202 bytes written while expected 1902606. [PNG

Sometimes I get this error.
I sometimes get this error in the same operation.
I tested it with the same file, but sometimes I get an error or not.
Which is the problem?

**Comment by tyb9900** [comment]
I am still facing this issue.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: DioError [DioErrorType.other]: HttpException: Content size exceeds specified contentLength. 16477 bytes written while expected 1688. [PNG`
