### ISSUE TITLE
http修改成HTTP2

### ISSUE THREAD

**Issue by dancheng99** [flutterchina/dio#1051]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                                      | flutter / android  
| Platform Version                                    |  1.22.6  / 9.0   
| dio_http2_adapter Version                    |   1.0.1                                 |      |
| vscode |              |   1.53.2   |
| Repro rate                     |100% |      |
| Repro with our demo prj        |  yes          |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps
//http1.1 这样没问题

```_dio = Dio()
 ..options.baseUrl = ServerUrl.BASE_URL
        ..options.receiveDataWhenStatusError = true
        ..options.followRedirects = true；
```

//修改成http2.0 就报错 ，我网站已经改成HTTP2测试也没问题 是哪里有错啊
请求异常: DioError [DioErrorType.DEFAULT]: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).

```
_dio = Dio()
        ..options.baseUrl = ServerUrl.BASE_URL
        ..options.receiveDataWhenStatusError = true
        ..options.followRedirects = true
        ..httpClientAdapter = Http2Adapter(
          ConnectionManager(
            idleTimeout: 10000,
            onClientCreate: (_, clientSetting) =>
                clientSetting.onBadCertificate = (_) => true,
          ),
        );
    }
```

**Comment by kyn27500** [comment]
same too

**Comment by bigParis** [comment]
same question，sometimes get another error "HTTP/2 error: Connection error: Connection is being forcefully terminated. "
