### ISSUE TITLE
Empty formData attaching multipartfile

### ISSUE THREAD

**Issue by demo-Ashif** [flutterchina/dio#1052]
### Issue Info
Always empty formData when am attaching a multipartfile

| Dio Version                    | 3.0.10                                

### Issue Description and Steps

    `FormData formData = FormData.fromMap({
        "name": "wendux",
        "photo": await MultipartFile.fromFile(
          file.path,
          filename: fileName,
        ),
      });
      print(formData.fields);`

It printing `[MapEntry(name: wendux)]` 

'photo' formdata is never added. Couldn't find the solution. Need urgent help/suggestions.

**Comment by itsatifsiddiqui** [comment]
Having the same issue, How did you solved it?

**Comment by demo-Ashif** [comment]
> Having the same issue, How did you solved it?

Its little bit old issue. Can you share your code and issue?
