### ISSUE TITLE
Operand of null-aware operation '!' has type 'String' which excludes null.

### ISSUE THREAD

**Issue by technolion** [flutterchina/dio#1058]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter web                         |      |
| Platform Version               | Flutter Channel dev, 1.27.0-8.0.pre                              |      |
| Dio Version                    | 4.0.0-beta2                                  |      |
| Repro rate                     | always   |      |

### Issue Description and Steps

My app needs to be compiled with proper null-safety. Therefore I am using `dio` version 4.0.0-beta2.
In this version a warning appears on startup of the app, **when running on flutter for web**:

```
[+7709 ms] /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0-beta2/lib/src/adapters/browser_adapter.dart:30:22: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
[        ]       ..open(options.method!, options.uri.toString(), async: true)
```

When the app tries to send a dio.request() the following error occurs:

```
[  +16 ms] Error: Bad state: No element
               at Object.throw_ [as throw] (http://localhost:61764/portal/dart_sdk.js:5342:11)
               at http://localhost:61764/portal/dart_sdk.js:19611:27
               at _RootZone.runGuarded (http://localhost:61764/portal/dart_sdk.js:38923:11)
               at _DoneStreamSubscription.new.[_sendDone] (http://localhost:61764/portal/dart_sdk.js:36181:47)
               at Object._microtaskLoop (http://localhost:61764/portal/dart_sdk.js:39301:13)
               at _startMicrotaskLoop (http://localhost:61764/portal/dart_sdk.js:39307:13)
               at http://localhost:61764/portal/dart_sdk.js:34814:9
```

The request is not sent to the server which makes this a serious bug.

**Comment by wendux** [comment]
It is fixed  in 4.0.0-beta3 (preview version)

**Comment by technolion** [comment]
Thanks a lot @wendux !

**Comment by Spicely** [comment]
![image](https://user-images.githubusercontent.com/10075622/109650622-6edaa380-7b98-11eb-84c8-5d5b51cdd581.png)
还是没有解决这个问题

**Comment by Spicely** [comment]
[√] Flutter (Channel beta, 1.26.0-17.8.pre, on Microsoft Windows [Version 10.0.19042.804], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (4 available)

**Comment by joo** [comment]
This is my solution, can run on both web and non-Web platforms.
Donn't Importing 'package:dio/adapter_browser.dart', so build is OK!

```
      if (Platform.I.isWeb) {
        _dio = Dio(BaseOptions(connectTimeout: 60000, sendTimeout: 60000, receiveTimeout: 60000));
        // (_dio.httpClientAdapter as BrowserHttpClientAdapter).withCredentials = true;
        (_dio.httpClientAdapter as dynamic).withCredentials = true;
      } else {
        _dio = Dio(BaseOptions(connectTimeout: 60000, sendTimeout: 60000, receiveTimeout: 60000));
        (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client) {
          client.badCertificateCallback = (X509Certificate cert, String host, int port) {
            return true;
          };
        };
        _cookieJar = CookieJar();
        _dio.interceptors.add(CookieManager(_cookieJar));
      }
    }
```

**Comment by joo** [comment]
In my project everything is correct, run on web and non-Web platforms.

_dio = Dio(BaseOptions(connectTimeout: 60000, sendTimeout: 60000, receiveTimeout: 60000))
will create correct httpClientAdapter for web platform and non-Web platforms.
(_dio.httpClientAdapter as dynamic)
will not need BrowserHttpClientAdapter, but can set withCredentials attribute value.
