### ISSUE TITLE
Http Headers are not being recognized

### ISSUE THREAD

**Issue by fogaiht** [flutterchina/dio#1059]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | Beta Channel 1.26.0-17.8.pre                              |      |
| Dio Version                    | 4.0.0-beta3                                  |      |
| Repro rate                     | all the time (100%) |      |
### Issue Description and Steps

The http headers are not being recognized in this new nullsafety version

**Comment by wendux** [comment]
Sorry, I'm not sure what you mean.

**Comment by fogaiht** [comment]
![image](https://user-images.githubusercontent.com/16519851/110153700-29012380-7dc2-11eb-9aa0-9d83ff3919e8.png)

Request Headers is empty, but in image below, i'm setting the headers

![image](https://user-images.githubusercontent.com/16519851/110154232-c9efde80-7dc2-11eb-8470-e9265b5fd939.png)

**Comment by wendux** [comment]
Please check whether the submitted data is null, in this case, the request content-type could be deleted。

**Comment by wendux** [comment]
Yes！

**Comment by fogaiht** [comment]
but how can I use content-type with GET method??

**Comment by wendux** [comment]
content-type in request header indicates the content type of **request body** ,  but the `get `request has no request body, so I don't known why content-type need to be set .

**Comment by fogaiht** [comment]
the API that I use, need's be set content-type in header to works, so, i don't see justification to cleaning the header, let us define the content-type.... I made a pull request (#1082) to fix this.

It's not about only me, but a lot of people had the same issue :|

**Comment by wendux** [comment]
fixed in 4.0.0-prev2。
```dart
    var dio = Dio();
    
    var r1 = await dio.get(''); 
    assert(r1.requestOptions.headers[Headers.contentTypeHeader] == null);
   
    // global config
    dio.options.setRequestContentTypeWhenNoPayload = true;

    r1 = await dio.get('');
    assert(r1.requestOptions.headers[Headers.contentTypeHeader] ==
        Headers.jsonContentType);
   // reset
    dio.options.setRequestContentTypeWhenNoPayload = false;

    var r2 = await dio.get(
      '',
      options: Options(contentType: Headers.jsonContentType),
    );

    assert(r2.requestOptions.headers[Headers.contentTypeHeader] ==
        Headers.jsonContentType);
```

**Comment by fogaiht** [comment]
See the comment below

https://github.com/flutterchina/dio/pull/1082#issuecomment-802029784

**Comment by woprandi** [comment]
@fogaiht As you can see, you can use `dio.options.setRequestContentTypeWhenNoPayload = true`

**Comment by fogaiht** [comment]
thanks guys, this flag works here!!!! thanks a lot!
