### ISSUE TITLE
请问如何处理302状态码呢？

### ISSUE THREAD

**Issue by jelly-cai** [flutterchina/dio#106]

**Comment by wendux** [comment]
可以参考Options.followRedirects（HttpClientRequest.followRedirects）

**Comment by jp1017** [comment]
> Options.followRedirects（HttpClientRequest.followRedirects）

这是怎么玩的？followRedirects 是个bool，，

**Comment by ghyh22** [comment]
我用dio.request替换了dio.post方法就没报错了

**Comment by jiashaoying** [comment]
使用dio.request，请求可以自动跟随重定向。不区分是post还是get。
