### ISSUE TITLE
Packages Dependency Issue, incompatible with http >=0.13.0

### ISSUE THREAD

**Issue by yuhangang** [flutterchina/dio#1065]
I am currently using google font package 2.0.0, which depends on http >=0.13.0, while DIO currently doesn't support the following http packages 0.13.0. Is there any plan to migrate to the newer version of http package? (Sorry for my broken English)

**Comment by yuhangang** [comment]
the output of console:

Because no versions of dio match >3.0.10 <4.0.0 and dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0, dio ^3.0.10 requires http_parser >=0.0.1 <4.0.0.

And because http >=0.13.0 depends on http_parser ^4.0.0, dio ^3.0.10 is incompatible with http >=0.13.0.

So, because noname depends on both http ^0.13.0 and dio ^3.0.10, version solving failed.
pub get failed (1; So, because noname depends on both http ^0.13.0 and dio ^3.0.10, version solving failed.)
exit code 1

**Comment by yuhangang** [comment]
Ok, this issue solved in pre released version.

**Comment by saturngod** [comment]
@yuhangang  what version are you using ?

**Comment by yuhangang** [comment]
I got the issue with installed v3.0.1, solved the problem with using latest pre-release version.
