### ISSUE TITLE
implementing null-safety

### ISSUE THREAD

**Issue by explodus** [flutterchina/dio#1066]
after the current flutter engage show/livestream it could be nice that much more packages get null-safety versions

**Comment by kuhnroyal** [comment]
Duplicate of #1019, there is already a null-safe preview version available.

**Comment by explodus** [comment]
okay, thx, so if source_gen, build and retrofit_generator get also migrated i could update my project to null-safety

**Comment by kuhnroyal** [comment]
Feel free to close this if your question is answered.
