### ISSUE TITLE
MultipartFile is only supported where dart:io is available

### ISSUE THREAD

**Issue by esDotDev** [flutterchina/dio#1067]
### New Issue Checklist

- [x ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

**Web Build**
Flutter 1.27.0-8.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision b7d4806243 (13 days ago) • 2021-02-19 09:22:45 -0800
Engine • revision 6993cb229b
Tools • Dart 2.13.0 (build 2.13.0-30.0.dev)

### Issue Description and Steps

I am using the cloudinary package on web, which is in-turn using Dio to call `toMultipartFile`
```
 FormData formData = FormData.fromMap({
      'file': file.toMultipartFile() ?? file.url,
      'upload_preset': uploadPreset ?? _uploadPreset,
    });

  ```

This is causing an exception at runtime: 
```
Error: Unsupported operation: MultipartFile is only supported where dart:io is available.
    at Object.throw_ [as throw] (http://localhost:52896/dart_sdk.js:5342:11)
```

There is some discussion here with some proposed fix:
https://stackoverflow.com/questions/63314063/upload-image-file-to-strapi-flutter-web

**Comment by DaniEid** [comment]
I'm using flutter v2.2 and getting the same issue the exception is occurring when trying to get MultipartFile from bytes and this is the chunk of the code that is throwing the exception 
`        final bytes = await attachmentFile.readAsBytes();
        final dioLibrary.MultipartFile file =
            dioLibrary.MultipartFile.fromBytes(
          bytes,
          filename: "picture",
        );

        print("adding map entry");

        formData.files.add(MapEntry(
          "file",
          file,
        ));`

**Comment by eliasayele** [comment]
still I don't get real fix

**Comment by DavidIjsud** [comment]
Still, i dont get a real fix for this problem :(.

**Comment by TheSagarPatil** [comment]
Has anyone got fix on this one?

**Comment by s2yed** [comment]
Has anyone got fix on this one?

**Comment by zand-yasin** [comment]
It should be work:  

  ```
FormData formData = FormData.fromMap({
        "img": MultipartFile.fromBytes(
          await pickedFile.readAsBytes(),
          filename: pickedFile.path.split('/').last,
        )
      });
```

**Comment by makhloughi** [comment]
> It should be work:
> 
> ```
> FormData formData = FormData.fromMap({
>       "img": MultipartFile.fromBytes(
>         await pickedFile.readAsBytes(),
>         filename: pickedFile.path.split('/').last,
>       )
>     });
> ```

Nope!

**Comment by makhloughi** [comment]
this will do the job:
Upload Multipart Form Data from flutter Dio on the web platform.
any other ways leads to unsupported namespace or any other platform errors

```
XFile file = XFile(yourHavingFile.path);
Uint8List content = await file.readAsBytes();

FormData formData = FormData.fromMap({
  "file": MultipartFile.fromBytes(content, filename: "whatever.itis")
});

Response response = await Dio().post(
  Endpoints.uploadUrl,
  data: formData,
  options: Options(
    headers: {
      "Content-Type": "multipart/form-data"
    }
  )
);
```

thanks to [isuru ](https://stackoverflow.com/users/16578521/isuru-bandara) for: https://stackoverflow.com/a/75825712/6466343
