### ISSUE TITLE
If statusCode==500 ,in InterceptorsWrapper onError,I can't get the  Error message from server in response data, I Got NULL !!!

### ISSUE THREAD

**Issue by cn1001wang** [flutterchina/dio#1068]
### 在服务器返回500后, 服务器返回的错误信息无法获取

>like #332 issue

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter                        |      |
| Platform Version               | e.g.  1.26.0-17.6.pre • channel beta                              |      |
| Dio Version                    | e.g.  2.12.0-259.12.beta (beta)                                  |      |
| Android Studio / Xcode Version | e.g. VScode 1.53.2              |      |
| Repro rate                     | e.g. all the time (100%)    |      |
| Repro with our demo prj        | e.g. no          |      |
| Demo project link              | e.g. no |      |

### Issue Description and Steps

![image](https://user-images.githubusercontent.com/34416681/110077692-8d6fb300-7dc1-11eb-8389-5a0d4d9ef8f8.png)

if (!(statusOk || options.receiveDataWhenStatusError))
 it can‘t Enter the Code to get response.data

**Comment by wendux** [comment]
set `receiveDataWhenStatusError = true`

**Comment by cn1001wang** [comment]
thank U .Are there more detailed documents?
