### ISSUE TITLE
后台需要用流接收上传的文件，请问怎么用dio以流的方式上传？

### ISSUE THREAD

**Issue by didyqian** [flutterchina/dio#107]
一下是用java写的代码：
`InputStreamEntity entity = new InputStreamEntity(new ByteArrayInputStream(fileBytes));
			httpPost.setEntity(entity);
HttpClient httpClient = HttpClientPool.getHttpClient();
HttpResponse response = httpClient.execute(httpPost);
`
请问用dio应该怎么处理这种上传方式？

**Comment by wendux** [comment]
dio上传文件是通过FormData一次编码的，不支持直接流式上传，但支持二进制数组。
