### ISSUE TITLE
Update to http_parser : 4.0.0 

### ISSUE THREAD

**Issue by Joseph-Nathan** [flutterchina/dio#1071]
Because http >=0.13.0 depends on http_parser ^4.0.0 and dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0, http >=0.13.0 is incompatible with dio 3.0.10.
And because no versions of dio match >3.0.10 <4.0.0, http >=0.13.0 is incompatible with dio ^3.0.10.

**Comment by tjarvstrand** [comment]
Try the [beta](https://pub.dev/packages/dio/versions/4.0.0-beta5)?

**Comment by wendux** [comment]
Try 4.0.0-beta6
