### ISSUE TITLE
Disabling redirects no longer works for the io adapter.

### ISSUE THREAD

**Issue by hworld** [flutterchina/dio#1074]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | ios and android                          |      |
| Platform Version               | n/a                              |      |
| Dio Version                    | 4.0.0-beta6                                  |      |
| Android Studio / Xcode Version | n/a              |      |
| Repro rate                     | 100%   |      |
| Repro with our demo prj        |            |      |
| Demo project link              |  |      |

### Issue Description and Steps
When you set the option `followRedirects` to `false` on the `Options` object, it doesn't actually honor that setting. It'll still follow redirects. This used to work. It seems like the code was just removed completely in this commit: https://github.com/flutterchina/dio/commit/75cf9166c3d5d159895de123e24a9ce748804a1a

There wasn't any message about the removal, and I'm not sure why it was removed. The http2 adapter still works. It's just the io adapter that's not using those options.

**Comment by wendux** [comment]
Oh..., It was an accident, you're right, I  fixed  it at 4.0.0-beta7, thanks.
