### ISSUE TITLE
Migrate to nullable

### ISSUE THREAD

**Issue by britov** [flutterchina/dio#1075]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps

Lets migrate to flutter 2 with nullable
https://dart.dev/null-safety/migration-guide#step1-wait

**Comment by gabrielginter** [comment]
Beta version is already available [here](https://pub.dev/packages/dio/versions/4.0.0-beta7).

#1073 stable release will be available within a week according to dev

Cheers

**Comment by AliHoseinpoor** [comment]
please support sound null safety

**Comment by vytautas-pranskunas-** [comment]
?
