### ISSUE TITLE
POST PUT issue with certain server configuration in 4.0 and Web

### ISSUE THREAD

**Issue by jonasbark** [flutterchina/dio#1077]
Unfortunately, this very valid issue is closed:
https://github.com/flutterchina/dio/issues/1007#issuecomment-792879743

In essence:
E/flutter ( 5180): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Stream has already been listened to.
when using POST or PUT.

In my case, it's not working with Spring Boot 2.4.2 in a pretty standard microservice which is why I created this ticket. Everything works as expected with Dio 3.

**Comment by woprandi** [comment]
I have the same issue, but I don't see any request coming to my web server nor even launched from browser.

**Comment by jonasbark** [comment]
@woprandi that's because it errors out *before* it can make the actual request

**Comment by woprandi** [comment]
So why some comments in the other issue suggest s server-side fix if the error happens before any request ? And why did you specify your backend specification ?

**Comment by jonasbark** [comment]
Because (again, as far as I remember) it already errors out during the HTTP handshake and apparently can't properly handle the header values returned from a server.
If you're in doubt, feel free to send a complete stacktrace here.

**Comment by woprandi** [comment]
I just noticed I was still with beta5, upgrading to 4.0.0-beta7 fixed my issue.
