### ISSUE TITLE
dio.request can't accept RequestOptions anymore

### ISSUE THREAD

**Issue by naamapps** [flutterchina/dio#1078]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                          |      |
| Platform Version               | 2.0.1                              |      |
| Dio Version                    | 4.0.0-beta7                                 |      |

### Issue Description and Steps

I have an error interceptor to get a new token once I get 403/401 status.
Before the update I could fetch the new token and continue with the previous request like this:
```
      onError: (DioError error) async {
        if (error.type == DioErrorType.response &&
            (error.response.statusCode == 401 ||
                error.response.statusCode == 403)) {
          final RequestOptions options = error.response.request;
          dio.lock();
          dio.interceptors.requestLock.lock();
          dio.interceptors.errorLock.lock();
          if (!await _authService.refreshToken()) {
            await _authService.logout();
            dio.unlock();
            dio.interceptors.requestLock.unlock();
            dio.interceptors.errorLock.unlock();
            return dio.resolve(null);
          }
          dio.unlock();
          dio.interceptors.requestLock.unlock();
          dio.interceptors.errorLock.unlock();
          return dio.request(options.path, options: options);
        }
      },
```
But now the method `dio.request` can't accept `RequestOptions` anymore. it only accepts `Options`.
Why did you change this behaviour? maybe add an option to map between the two classes?

Please help,
Thanks.

**Comment by shashikantx** [comment]
Yes, I am facing the same issue. There is no documentation either on how to fix this.

**Comment by woprandi** [comment]
You can use `dio.fetch(RequestOptions)`

**Comment by vishna** [comment]
so I wrote this beautiful extension when migrating to new dio 😅 ...going to check `dio.fetch` now

```dart
extension _AsOptions on RequestOptions {
  Options asOptions() {
    return Options(
      method: method,
      sendTimeout: sendTimeout,
      receiveTimeout: receiveTimeout,
      extra: extra,
      headers: headers,
      responseType: responseType,
      contentType: contentType,
      validateStatus: validateStatus,
      receiveDataWhenStatusError: receiveDataWhenStatusError,
      followRedirects: followRedirects,
      maxRedirects: maxRedirects,
      requestEncoder: requestEncoder,
      responseDecoder: responseDecoder,
      listFormat: listFormat,
    );
  }
}
```

**Comment by naamapps** [comment]
`dio.fetch(RequestOptions)` is the solution.

**Comment by azeunkn0wn** [comment]
> You can use `dio.fetch(RequestOptions)`

This works well except for when I try to POST. I'm getting this error:
` Bad state: The FormData has already been finalized. This typically means you are using the same FormData in repeated requests.`

I'm using  to retry my POST request
