### ISSUE TITLE
Please support null safety asap

### ISSUE THREAD

**Issue by neiljaywarner** [flutterchina/dio#1079]
### New Issue Checklist

Yes, this links https://github.com/flutterchina/dio/issues/1002 but that issue is closed and has the PR not merged in, and this is urgent and important so i want to to highlight it - as far as I can tell this is a dealbreaker for dio to be used on new projects.

**Comment by ericmartineau** [comment]
Probably bad form, but I am impatient.  I published a fork of dio with nullsafety as `dio2` - I do not plan on maintaining that project, just until dio formally supports null-safety.

**Comment by AliHoseinpoor** [comment]
please support sound null safety

**Comment by wendux** [comment]
try `4.0.0-prev2` https://github.com/flutterchina/dio/tree/4.0
