### ISSUE TITLE
How to JWT with refresh/access tokens?

### ISSUE THREAD

**Issue by wellbranding** [flutterchina/dio#1088]
Why there is no guide for JWT access and refresh tokens? Previously I used the approach from this [issue](https://github.com/flutterchina/dio/issues/50).
However, after migrating to dio 4, the code no longer works. Please provide an example with a refresh token, used for retrieving access token, if the access token is expired.

**Comment by marwenbk** [comment]
any solution ?

**Comment by mauriziopinotti** [comment]
Here's what I came up with, hope it helps:

```dart
    // Add auth token to each request
    _dio.interceptors.add(InterceptorsWrapper(onRequest: (options, handler) {
      options.headers.addAll({
        if (_accessToken != null) "Authorization": "Bearer $_accessToken",
        Headers.contentTypeHeader: Headers.jsonContentType,
      });
      return handler.next(options);
    }, onError: (e, handler) async {
      if (e.response?.statusCode == 401 &&
          e.response.requestOptions.path != '/oauth/v2/token' &&
          _refreshToken != null) {
        // Update the access token
        _accessToken = null;
        final RequestOptions options = e.response.requestOptions;
        try {
          final Response<String> refreshResponse = await _dio.post<String>(
              '/oauth/v2/token',
              data: RefreshTokenRequest(refreshToken: _refreshToken).toJson());

          // Retry request
          saveTokens(LoginResponse.fromJson(jsonDecode(refreshResponse.data)));
          options.headers['Authorization'] = 'Bearer $_accessToken';
          final Response response = await _dio.fetch(options);

          return handler.resolve(response);
        } catch (e, s) {
          print(e);
          print(s);

          // Refresh token expired
          // Redirect user to login...
        }
      }

      return handler.next(e);
    }, onResponse: (response, handler) {
      return handler.next(response);
    }));
```

**Comment by marwenbk** [comment]
can you explain the role of the route /oauth/v2/token

**Comment by mauriziopinotti** [comment]
> can you explain the role of the route /oauth/v2/token

yeah, sorry, it's the endpoint to refresh the token, so basically:
- at login we receive access token and refresh token from server
- use access token for normal requests
- if access token is expired use the refresh token to get a new access token (`/refresh-token-endpoint`)
- if refresh token is expired as well then show the login page

I'va updated the answer to make it more clear.

**Comment by marwenbk** [comment]
thank you so much for help , so do we need to use this intercept method every time after initialisation of Dio class ?

**Comment by marwenbk** [comment]
can please give us a real implementation and use example

**Comment by wellbranding** [comment]
@mauriziopinotti  Thanks! One more question, how should I redirect to login from the service? I currently use flutter bloc, and after app loads, I call getUserInfo endpoint, should I when use await and receive a response? But what should I return, can you give an example?

**Comment by YoussefGheith** [comment]
@wellbranding  you can use get_it package  to navigate without context or you can create your own custom dio error 

class YourCustomError implements DioError {
  String _message;
  YourCustomError(message) : _message = message;

  @override
  var error;

  @override
  RequestOptions request;

  @override
  Response response;

  @override
  DioErrorType type;

  @override
  String get message => _message;
}

**Comment by YoussefGheith** [comment]
@mauriziopinotti 
after refreshing the token successfully the request doesn't work using  
final Response response = await _dio.fetch(options);
??

**Comment by loicgeek** [comment]
```
 static Dio _dio;
static IdTokenResult bigtoken;
  static int retryCount = 0;
  static int MAX_RETRY = 3;

  static Dio dioInstance() {
    if (_dio == null) {
      _dio = new Dio(BaseOptions(baseUrl: SERVER_URL));

      _dio.interceptors.add(
        InterceptorsWrapper(
          onError: (DioError error, handler) async {
            if (error.type == DioErrorType.response &&
                    error.response?.statusCode == 403 ||
                error.response?.statusCode == 401) {
              try {
               ///We reached the max  attempt, the reset retryCount and resolve as an error
                if (retryCount > MAX_RETRY) {
                  retryCount = 0;
                  return handler.next(error);
                }
                retryCount++;
               // I lock dio so all request will wait for the refresh to complete first
                _dio.lock();
                _dio.interceptors.errorLock.lock();
                _dio.interceptors.requestLock.lock();
                _dio.interceptors.responseLock.lock();
                RequestOptions options = error.response.requestOptions;

               
                ///All the following is to get the new access_token, I am using firebase but if you are not using firebase, you should 
               ///use a different dio instance to refresh the token 
                User user = FirebaseAuth.instance.currentUser;
                if (user == null || user?.isAnonymous == true) {
                  _dio.unlock();
                  _dio.interceptors.errorLock.unlock();
                  _dio.interceptors.requestLock.unlock();
                  _dio.interceptors.responseLock.unlock();
                  retryCount = 0;
                  return handler.next(error);
                }
                bigtoken = await user.getIdTokenResult(true);
                options.headers["Authorization"] = "Bearer " + bigtoken.token;
               // The token is updated, we can unlock dio now
                _dio.unlock();
                _dio.interceptors.errorLock.unlock();
                _dio.interceptors.requestLock.unlock();
                _dio.interceptors.responseLock.unlock();

                //this is in case your request content files
                if (options.data is FormData) {
                  FormData formData = FormData();
                  formData.fields.addAll(options.data.fields);
                  for (MapEntry mapFile in options.data.files) {
                    formData.files.add(MapEntry(
                        mapFile.key,
                        MultipartFileExtended.fromFileSync(
                            mapFile.value.filePath)));
                  }
                  options.data = formData;
                }
                final Response response = await _dio.fetch(options);
                retryCount = 0;

                return handler.resolve(response);
              } catch (e) {
                print(e);
                _dio.unlock();
                _dio.interceptors.errorLock.unlock();
                _dio.interceptors.requestLock.unlock();
                _dio.interceptors.responseLock.unlock();
                retryCount = 0;
                return handler.next(error);
              }
            } else {
              retryCount = 0;
              return handler.next(error);
            }
          },
        ),
      );
      (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
          (HttpClient client) {
        client.badCertificateCallback =
            (X509Certificate cert, String host, int port) => true;
        return client;
      };
    }

    return _dio;
  }
```

That is it guys!!

**Comment by Samio26** [comment]
this is the optimal solution :
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_pretty_dio_logger/flutter_pretty_dio_logger.dart';

import '../../feature_auth/domain/use_case/refresh_token_use_case.dart';
import 'constants.dart';
import 'package:http_parser/http_parser.dart';


class ApiClient {
  final Dio dio = getStandardClient();
  String? accessToken;

  final RefreshTokenUseCase _refreshTokenUseCase;

  ApiClient(this._refreshTokenUseCase) {
    dio.interceptors.add(
      InterceptorsWrapper(
        onRequest: (options, handler) async {
          options.headers[HttpHeaders.authorizationHeader] = "Bearer $accessToken";
           
          return handler.next(options);
        },
        onError: (DioError error, handler) async {
       
        if (error.response?.statusCode!=401||error.response?.statusCode==null)return handler.next(error);

          if (refreshTokenFuture == null) {
            refreshTokenFuture = refreshToken();
          }
          final isRefreshTokenSuccess = await refreshTokenFuture;
          if (isRefreshTokenSuccess == true) {
            print("retry");
            refreshTokenFuture = null;
            return handler.resolve(await _retry(error.requestOptions));
          }
         

          return handler.next(error);
        }
      )
    );
  }

  Future<bool>? refreshTokenFuture = null;

  Future<bool> refreshToken() async {
    try {
    final result = await _refreshTokenUseCase();
    print(result);
    return result.fold(
      (_) => false,
      (token) {
        print("true");
        accessToken = token.accessToken;
        return true;
      });
    }on Exception catch(_){
      return false;
    }
  }

  Future<Response<dynamic>> _retry(RequestOptions requestOptions) async {
    final options = Options(
      method: requestOptions.method,
      headers: requestOptions.headers,
    );
    try {
      return dio.request<dynamic>(
        requestOptions.path,
        data: requestOptions.data,
        queryParameters: requestOptions.queryParameters,
        options: options
      );
    } on DioError catch(e){
      throw Exception(e.message);
    }
  }



  void clearAccessToken(){
    accessToken=null;
  }

  static Dio getStandardClient() {
    final dio = Dio(
        BaseOptions(
          baseUrl: Urls.baseUrl,
          headers: {
            
            HttpHeaders.contentTypeHeader: "application/json",
            HttpHeaders.acceptHeader: "application/json",
      
          },
          receiveTimeout: 60000,
          connectTimeout: 60000,
        )
    );

    if (kDebugMode) {
      dio.interceptors.add(
          PrettyDioLogger(
              requestHeader: true,
              queryParameters: true,
              requestBody: true,
              responseHeader: true,
              responseBody: true,
              error: true,
              showProcessingTime: true,
              showCUrl: true,
              canShowLog: kDebugMode
          )
      );
    }

    return dio;
  }

}

**Comment by Samio26** [comment]
`import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_pretty_dio_logger/flutter_pretty_dio_logger.dart';

import '../../feature_auth/domain/use_case/refresh_token_use_case.dart';
import 'constants.dart';
import 'package:http_parser/http_parser.dart';


class ApiClient {
  final Dio dio = getStandardClient();
  String? accessToken;

  final RefreshTokenUseCase _refreshTokenUseCase;

  ApiClient(this._refreshTokenUseCase) {
    dio.interceptors.add(
      InterceptorsWrapper(
        onRequest: (options, handler) async {
          options.headers[HttpHeaders.authorizationHeader] = "Bearer $accessToken";
           
          return handler.next(options);
        },
        onError: (DioError error, handler) async {
       
        if (error.response?.statusCode!=401||error.response?.statusCode==null)return handler.next(error);

          if (refreshTokenFuture == null) {
            refreshTokenFuture = refreshToken();
          }
          final isRefreshTokenSuccess = await refreshTokenFuture;
          if (isRefreshTokenSuccess == true) {
            print("retry");
            refreshTokenFuture = null;
            return handler.resolve(await _retry(error.requestOptions));
          }
         

          return handler.next(error);
        }
      )
    );
  }

  Future<bool>? refreshTokenFuture = null;

  Future<bool> refreshToken() async {
    try {
    final result = await _refreshTokenUseCase();
    print(result);
    return result.fold(
      (_) => false,
      (token) {
        print("true");
        accessToken = token.accessToken;
        return true;
      });
    }on Exception catch(_){
      return false;
    }
  }

  Future<Response<dynamic>> _retry(RequestOptions requestOptions) async {
    final options = Options(
      method: requestOptions.method,
      headers: requestOptions.headers,
    );
    try {
      return dio.request<dynamic>(
        requestOptions.path,
        data: requestOptions.data,
        queryParameters: requestOptions.queryParameters,
        options: options
      );
    } on DioError catch(e){
      throw Exception(e.message);
    }
  }



  void clearAccessToken(){
    accessToken=null;
  }

  static Dio getStandardClient() {
    final dio = Dio(
        BaseOptions(
          baseUrl: Urls.baseUrl,
          headers: {
            
            HttpHeaders.contentTypeHeader: "application/json",
            HttpHeaders.acceptHeader: "application/json",
      
          },
          receiveTimeout: 60000,
          connectTimeout: 60000,
        )
    );

    if (kDebugMode) {
      dio.interceptors.add(
          PrettyDioLogger(
              requestHeader: true,
              queryParameters: true,
              requestBody: true,
              responseHeader: true,
              responseBody: true,
              error: true,
              showProcessingTime: true,
              showCUrl: true,
              canShowLog: kDebugMode
          )
      );
    }

    return dio;
  }

}`
