### ISSUE TITLE
flutter: DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'

### ISSUE THREAD

**Issue by getpu** [flutterchina/dio#1090]
This version is haven't finished yet ???

老铁你的这个最新版本是不是还没有写完啊。第一次请求没事第二次就卡在这里了。

**Comment by wendux** [comment]
请给出复现流程及相关代码

**Comment by getpu** [comment]
> 请给出复现流程及相关代码
我换低版本了好没事了，应该是新版null safety 引起的代码问题，不是 dio 引起的
