### ISSUE TITLE
Default Options copy throws

### ISSUE THREAD

**Issue by NicolaVerbeeck** [flutterchina/dio#1091]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |    
| ------------------------------ | ----------------------------------------------------- | 
| Platform Name                  | any                          | 
| Platform Version               | 2.0.x                              |
| Dio Version                    |  ^4.0.0-prev2                                  | 
| Repro rate                     | 100%   | 

### Issue Description and Steps
Creating a basic fetch request by overriding the default options using compose and copyWith throws an exception. This seems to be introduced by #1076 This is triggered even though no content type headers OR content type are explicitely set

`You cannot set both contentType param and a content-type header`

Minimall reproduction code:
```dart
  final dio = Dio();
  dio.fetch(Options(method: 'GET')
      .compose(dio.options, '/test')
      .copyWith(baseUrl: 'https://www.example.com'));
```

**Comment by wendux** [comment]
fixed in 4.0.0-prev3
