### ISSUE TITLE
Dio won't catch errors and get stuck on request when server throws an error

### ISSUE THREAD

**Issue by naamapps** [flutterchina/dio#1092]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                          |      |
| Platform Version               | 2.0.3                              |      |
| Dio Version                    | 4.0.0-prev3                                 |      |

### Issue Description and Steps
 I am making a request (of any type: get,post,delete,patch) and it works if the server return a value, but when the server throws an error it get stuck and won't catch the error.
This issue occurred when upgrading from 4.0.0-beta7 to 4.0.0-prev3.

This is how I make the request:
```
 try {
      final Response<dynamic> rs = await dio.get<dynamic>(
        requestInfo.path,
        queryParameters: requestInfo.queryParams,
        cancelToken: cancelToken,
      );

      // It won't reach this code if there is an error.

      return rs.data;
    } catch (error) {
      // And most surprisingly it won't reach this code if there is an error.

      _onError(error);
    }

```

Please help,
Thanks

**Comment by naamapps** [comment]
Hey @wendux can you please take a look at this? It is still happening in stable version 4.0.0.

**Comment by naamapps** [comment]
to anyone also having this problem, the solution is (for me at least) is to not forget to put `return handler.next(error);` at the end of the `onError` interceptor.

**Comment by ResoDev** [comment]
@naamapps Thank you!!! That new way of writing interceptors is not as trivial as I thought at first.
