### ISSUE TITLE
DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'

### ISSUE THREAD

**Issue by getpu** [flutterchina/dio#1094]
这bug 好像不是我代码引起的。。。

  Future post(url, {data, params}) async {
    Response response;
    try {
      response = await _dio.post(url, data: data, queryParameters: params);
      return response.data;
    } catch (e) {
      throw e;
    }
  }

我只要捕获这个  catch e 就有这个错误.

**Comment by jayjah** [comment]
Same here ...

Code:


    final _result = await _dio.fetch<List<dynamic>>(
        _setStreamType<List<NewsObject>>(Options(
                method: 'GET',
                headers: <String, dynamic>{
                  r'pageById': pageById,
                  r'pageByDate': pageByDate,
                  r'splitBy': splitBy,
                  r'onlyIds': onlyIds,
                  r'pageByIds': pageByIds
                },
                extra: _extra)
            .compose(_dio.options, '/news',
                data: _data, queryParameters: queryParameters)
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    ...

      RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
        if (T != dynamic &&
            !(requestOptions.responseType == ResponseType.bytes ||
                requestOptions.responseType == ResponseType.stream)) {
          if (T == String) {
            requestOptions.responseType = ResponseType.plain;
          } else {
            requestOptions.responseType = ResponseType.json;
          }
        }
        return requestOptions;
      }


Stacktrace:

    DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'
    #0      DefaultHttpClientAdapter.fetch.<anonymous closure> (package:dio/src/adapters/io_adapter.dart:55:64)
    #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
    #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:55:23)
    <asynchronous suspension>
    #3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>


Version: 
 dio: ^4.0.0-prev3

just in case: flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)

**Comment by DhavalRKansara** [comment]
I am also facing the same issue.
```
flutter: DioError [DioErrorType.response]: Http status error [500]
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
<asynchronous suspension>
```

**Comment by lianyagang** [comment]
DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'
[        ] I/flutter (22189): #0      DefaultHttpClientAdapter.fetch.<anonymous closure> (package:dio/src/adapters/io_adapter.dart:55:64)
[        ] I/flutter (22189): #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
[        ] I/flutter (22189): #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:55:23)
[        ] I/flutter (22189): <asynchronous suspension>
[        ] I/flutter (22189): #3      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:632:22)
[        ] I/flutter (22189): <asynchronous suspension>
[        ] I/flutter (22189): #4      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
[        ] I/flutter (22189): <asynchronous suspension>

**Comment by DhavalRKansara** [comment]
I fixed the issue by passing `contentType: 'application/json'` as inside **Dio BaseOption** on behalf of the header key-value pair.

**Before:**

```
 Map headers = <String, dynamic>{};
      'Content-Type': 'application/json',
    };

 var dio = Dio(BaseOptions(
      baseUrl: 'baseUrl',
      connectTimeout: 50000,
      receiveTimeout: 50000,
      headers: headers as Map<String, dynamic>?,
    ));
```

**After:**

```
var dio = Dio(BaseOptions(
      baseUrl: 'baseUrl',
      connectTimeout: 50000,
      receiveTimeout: 50000,
      contentType: 'application/json', // Added contentType here
      headers: headers as Map<String, dynamic>?,
    ));
```

**Comment by jayjah** [comment]
@DhavalRKansara 
If I use your suggestion I get an error like the following: 

 'package:dio/src/options.dart': Failed assertion: line 593 pos 7: '!(contentType != null && contentTypeInHeader)': You cannot set both contentType param and a content-type header
  dart:core                                      _AssertionError._throwNew
  package:dio/src/options.dart 593:7             new _RequestConfig
  package:dio/src/options.dart                   new _BaseOptions&_RequestConfig&OptionsMixin
  package:dio/src/options.dart 102:8             new BaseOptions
  package:dart_backend_client/client.dart 6:31   Client._dio
  package:dart_backend_client/client.dart        Client._dio
  package:dart_backend_client/client.dart 10:28  Client.getDio
  test/dart_backend_client_test.dart 9:16        main.<fn>.<fn>

If I remove the content-type from header, it's the same error like before:

  DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'
  #0      DefaultHttpClientAdapter.fetch.<anonymous closure> (package:dio/src/adapters/io_adapter.dart:55:64)
  #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
  #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:55:23)
  <asynchronous suspension>
  #3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
  <asynchronous suspension>
  
  package:dio/src/dio_mixin.dart 618:7                   DioMixin.fetch.<fn>
  ===== asynchronous gap ===========================
  dart:async                                             Future.catchError
  package:dio/src/dio_mixin.dart 609:8                   DioMixin.fetch
  package:dart_backend_client/api/news_api.g.dart 56:32  _NewsRestClient.getAll
  test/dart_backend_client_test.dart 14:34               main.<fn>.<fn>
  test/dart_backend_client_test.dart 13:20               main.<fn>.<fn>

**Comment by jayjah** [comment]
@DhavalRKansara You're right! That one worked!!! 


I received the error: ` type 'Null' is not a subtype of type 'Object' `
because I was sending null in my request headers. 
So I changed my request headers from

`
Options(
                method: 'GET',
                contentType: 'application/json',
                headers: <String, dynamic>{
                  r'pageById': pageById,
                  r'pageByDate': pageByDate,
                  r'splitBy': splitBy,
                 r'onlyIds': onlyIds,
                 r'pageByIds': pageByIds
                })
`

to

`
Options(
                method: 'GET',
                contentType: 'application/json',
                headers: <String, dynamic>{
                  if (pageById != null) r'pageById': pageById,
                  if (pageByDate != null) r'pageByDate': pageByDate,
                  if (splitBy != null) r'splitBy': splitBy,
                  if (onlyIds != null) r'onlyIds': onlyIds,
                  if (pageByIds != null) r'pageByIds': pageByIds
                })
`

**Comment by getpu** [comment]
Good, The latest version is normal worked. This issue can be closed, Thank's everyone efforts.

**Comment by getpu** [comment]
> I fixed the issue by passing `contentType: 'application/json'` as inside **Dio BaseOption** on behalf of the header key-value pair.
> 
> **Before:**
> 
> ```
>  Map headers = <String, dynamic>{};
>       'Content-Type': 'application/json',
>     };
> 
>  var dio = Dio(BaseOptions(
>       baseUrl: 'baseUrl',
>       connectTimeout: 50000,
>       receiveTimeout: 50000,
>       headers: headers as Map<String, dynamic>?,
>     ));
> ```
> 
> **After:**
> 
> ```
> var dio = Dio(BaseOptions(
>       baseUrl: 'baseUrl',
>       connectTimeout: 50000,
>       receiveTimeout: 50000,
>       contentType: 'application/json', // Added contentType here
>       headers: headers as Map<String, dynamic>?,
>     ));
> ```
good job

**Comment by duoguang** [comment]
我遇到同样的问题，升级后 ，header里面不要传入null。否则就报题主这个错误。

**Comment by Lawati97** [comment]
am still facing this issue as whenever I send a call to an API that needs or does not need header I get the same issue and this issue happens randomly

**Comment by Lawati97** [comment]
and i am using dio 4.0.3
