### ISSUE TITLE
🥶 客户端发送一次请求，服务端收到两次请求

### ISSUE THREAD

**Issue by SeongBrave** [flutterchina/dio#1095]
经测试最新版本**3.0.10**，客户端发送一次请求，服务端收到两次请求，通过Charles抓包为两次请求

但是如果版本改为**3.0.0**就可以了，所以确定是3.0.10的问题。

**Comment by getpu** [comment]
> 经测试最新版本**3.0.10**，客户端发送一次请求，服务端收到两次请求，通过Charles抓包为两次请求
> 
> 但是如果版本改为**3.0.0**就可以了，所以确定是3.0.10的问题。

看看第一次请求是不是 option restful 模式下 都有两次
