### ISSUE TITLE
Dio interceptor not firing the right error on 401, instead throws Socketexception

### ISSUE THREAD

**Issue by naveenreddyin** [flutterchina/dio#1099]
### New Issue Checklist

- [/ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
I am working on a flutter application which uses JWT to access backend endpoints. When the access token expires, I added an interceptor to refresh the token based on the solutions provided here: [](https://stackoverflow.com/questions/56740793/using-interceptor-in-dio-for-flutter-to-refresh-token)

Here is my code:
```
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / ios / android                          |      |
| Platform Version               |  2.0.3                              |      |
| Dio Version                    | 3.0.10                                 |      |

### Issue Description and Steps
import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:dummy/utils/config.dart';

Future<Response> uploadVideo(filePath, fileName, title, jwt) async {
  Dio dio = new Dio();
  var token = json.decode(jwt);
  dio.interceptors.clear();

  dio.options.headers["Authorization"] = "Bearer ${token['access']}";
  dio.interceptors.add(InterceptorsWrapper(onError: (error) async {
    print(error.response);
    if (error.response?.statusCode == 403 ||
     error.response?.statusCode == 401) {
    await refreshToken(jwt);
    _retry(error.request, dio);
     }
    return error.response;
  }));
  Response response;
  try {
    FormData formData = FormData.fromMap({
      "file_name": fileName,
      "content": await MultipartFile.fromFile(filePath),
      'title': title,
    });
    response = await dio.post("$BASE_URL/video/create/", data: formData);
    return response;
  } on DioError catch (e) {
    if (e.response) {
      print(e.response.data);
      print(e.response.headers);
      print(e.response.request);
    } else {
      // Something happened in setting up or sending the request that triggered an Error
      print(e.request);
      print(e.message);
    }
    return e.response;
  }
}

Future<Response<dynamic>> _retry(RequestOptions requestOptions, Dio dio) async {
  final options = new Options(
    method: requestOptions.method,
    headers: requestOptions.headers,
  );
  return dio.request<dynamic>(requestOptions.path,
      data: requestOptions.data,
      queryParameters: requestOptions.queryParameters,
      options: options);
}

Future<Response> refreshToken(jwt) async {
  print("COMING INSIDE");
  Dio dio = new Dio();
  var token = json.decode(jwt);
  var refreshToken = token['refresh'];
  Response response;
  try {
    FormData formData = FormData.fromMap({
      "refresh": refreshToken,
    });
    response = await dio.post("$BASE_URL/auth/login/refresh/", data: formData);
    return response;
  } catch (e) {
    return e.response;
  }
}
```
I tried with debugger as well, but its not executing the code after if statement where it checks for 401 and 403. Server clearly gives 401 as I am running it locally so I can see the logs. The error which I am getting is this : 
`DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Broken pipe, errno = 32, address = 172.22.22.55, port = 49552
`
I could confirm that the server is up and flutter app could interact with it on other endpoints where token is not needed, and I could clearly see 401 on endpoint logs.

**Comment by naveenreddyin** [comment]
Hi guys, 
Any clue on the above mentioned issue?

**Comment by y-alkhateeb** [comment]
Handle it without interpreter cuz when return 401 the onResponse override method not working 
after check if the error is 401 call this method:

on DioError catch (e) {
      if(e?.response?.statusCode == 401)
      return await handleUnAuthorizedResponse(e.response);
    }

handleUnAuthorizedResponse(Response response) async {
        _client.lock();
        final String accessToken = await getRefreshToken();
        _client.unlock();
        if (accessToken != null) {
          final prefs = await SpUtil.getInstance();
          await prefs.putString(KEY_TOKEN, accessToken);
          final RequestOptions request = response.request;
          request.headers[HEADER_AUTH] = '${HEADER_AUTH_BEARER+accessToken}';

          final Options options = Options(
            headers: request.headers,
            method: request.method,
          );
          Response responseFromSecondRequest = await _client.request(
            request.path,
            data: request.data,
            queryParameters: request.queryParameters,
            cancelToken: request.cancelToken,
            options: options,
            onReceiveProgress: request.onReceiveProgress,
          );
         /// TODO return data
        }
        /// return error // else return null;
  }

**Comment by kateile** [comment]
same issue here

**Comment by y-alkhateeb** [comment]
> same issue here. Have you found anything?

I found the solution by using onError function rather than onResponse, so I write intercepter

class TokenInterceptor extends Interceptor {

  final Dio _tokenDio = Dio(BaseOptions(
    connectTimeout: 30000,
    receiveTimeout: 30000,
    sendTimeout: 28000,
    responseType: ResponseType.json,
    headers: {"Content-type": "application/json"},
    baseUrl: BASE_URL,
  ));

  Future<String> getToken() async {
    _tokenDio.interceptors.add(LoggingInterceptor());
    final Map<String, String> params = <String, String>{};
    params['accessToken'] = await AccountRepository.authToken;
    params['refreshToken'] = await AccountRepository.authRefreshToken;
    try {
      final Response response = await _tokenDio.put<dynamic>('refresh', data: params);
      if (response.statusCode == 200) {
        if(response.data["result"] != null)
        return response.data["result"];
      }
    } catch(e) {
      print('Filed to get token function');
    }
    /// return null to continue error
    return null;
  }


  @override
  void onError(DioError err, ErrorInterceptorHandler handler) async{
    if (err.response != null && err.response.statusCode == 401) {
        inject<HttpClient>().instance.lock();
        inject<HttpClient>().instance.interceptors.responseLock.lock();
        inject<HttpClient>().instance.interceptors.errorLock.lock();
        final String accessToken = await getToken();
        inject<HttpClient>().instance.unlock();
        inject<HttpClient>().instance.interceptors.responseLock.unlock();
        inject<HttpClient>().instance.interceptors.errorLock.unlock();
        if (accessToken != null) {
          print('-----------NewToken: $accessToken ------------');
          final prefs = await SpUtil.getInstance();
          await prefs.putString(KEY_TOKEN, accessToken);
          final RequestOptions request = err.response.requestOptions;
          request.headers[HEADER_AUTH] = '${HEADER_AUTH_BEARER+accessToken}';

          final Options options = Options(
            headers: request.headers,
            method: request.method,
          );
          try {
            final Response response = await inject<HttpClient>().instance.request<dynamic>(
              request.path,
              data: request.data,
              queryParameters: request.queryParameters,
              cancelToken: request.cancelToken,
              options: options,
              onReceiveProgress: request.onReceiveProgress,
            );
            return handler.resolve(response);
          } on DioError catch (e) {
            return handler.reject(e);
          }
        }
        else {
          super.onError(err, handler);
        }
      }
    else super.onError(err, handler);
  }

}
