### ISSUE TITLE
Dio force header to lowercase

### ISSUE THREAD

**Issue by zhangxiongbiao** [flutterchina/dio#1102]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               |                              |      |
| Dio Version                    | 3.0.10                                  |      |
| Android Studio / Xcode Version |  Android Studio 4.1.2              |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        |    |      |
| Demo project link              | |      |
| Dart SDK|2.12.0 |      |

### Issue Description and Steps

When I set Dio header like this

```
dio.options.headers['Authorization'] = 'dGVzdDp0ZXN0';
```

I expect request header to look like this

```
Authorization: Basic dGVzdDp0ZXN0
```

Not like this (notice that capital "A" was transformed to "a")

```
authorization: Basic dGVzdDp0ZXN0
```

I found problem in `io_adpater.dart`

![image](https://user-images.githubusercontent.com/10623853/112324131-697efd80-8ced-11eb-893b-e3207dd5cd44.png)

**Comment by cirediew** [comment]
I think this is related to [this](https://github.com/dart-lang/http2/issues/49)

**Comment by amirulabu** [comment]
I also having this issue, this is mainly due to our flutter app is connecting to a service that is using AWS API Gateway and for the service, header field name is case-sensitive. 

> Header names and query parameters are processed in a case-sensitive way.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html
