### ISSUE TITLE
Issue with request Interceptor not locking dio properly

### ISSUE THREAD

**Issue by Halahala1993** [flutterchina/dio#111]
I am trying to follow the example [here](https://github.com/flutterchina/dio#interceptors), where I want to refresh the token before every request. 

However, whenever the first request starts, even if the same dio instance's request interceptor locked it still goes through completely returning a status 0(?) making the interceptor useless in this case.

**Comment by wendux** [comment]
In this case,  you shouldn't use `lock` API. Refreshing the token before **every request**, just do it as follows:
```dart
  dio.interceptor.request.onSend = (Options options) async{
    // Refresh token for every request
     return newDio.get("/token").then((response){
        options.headers["token"] = response.data["data"]["token"];
        return options; //continue   
     });  
 }

```

**Comment by Halahala1993** [comment]
Hello, thanks for getting back. I just tried it but noticed I actually made an error in including 'return options;' in the wrong places so it's working as expected for me thanks!

Also, I just tried it again with and without the lock and I needed the Dio Lock or else it would retry the request many many times.
