### ISSUE TITLE
文档和代码不一致

### ISSUE THREAD

**Issue by jinjilynn** [flutterchina/dio#1112]
升级到4.0.0,原来的代码都不能用了, 文档描述和新版本的实际代码不一致

**Comment by wendux** [comment]
1. 文档已更新
2. 4.0有一些breaking change，3.0升级的话需要一些改动，详情可参考https://github.com/flutterchina/dio/blob/master/migration_to_4.x.md

**Comment by jinjilynn** [comment]
好,辛苦
