### ISSUE TITLE
上传文件慢

### ISSUE THREAD

**Issue by cairuoyu** [flutterchina/dio#1119]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                      |      |
| Platform Version               | 2.0                              |      |
| Dio Version                    | 4.0.0                                  |      |
| Demo project link              | http://cairuoyu.com/flutter_admin/ |      |

### Issue Description and Steps

上传文件调用dio.request时会卡，文件越大，卡得越久，导致上传很慢，使用http则不会
代码：
[flutter_admin](https://github.com/cairuoyu/flutter_admin/blob/master/lib/pages/article/article_edit.dart)
[cry](https://github.com/cairuoyu/cry/blob/main/lib/cry_file.dart)

**Comment by licy183** [comment]
在adapters中的broswer_adapter.dart中，有这样的一段代码：
```dart
requestStream
.reduce((a, b) => Uint8List.fromList([...a, ...b]))
.then(xhr.send);
```

按照Uint8List.fromList的方法说明，这个方法会把参数的List进行拷贝，所以用其他的方法替代了这一部分代码可能可以解决问题。以下是我的解决方法：
```
  requestStream.toList().then((value) {
    var length = value.fold<int>(
        0, (previousValue, element) => previousValue + element.length);
    Uint8List res = Uint8List(length);
    int start = 0;
    for (Uint8List list in value) {
      res.setRange(start, start += list.length, list);
    }
    return res;
  }).then(xhr.send);
```

我试了试，应该不会很卡了。
