### ISSUE TITLE
Mock Http Client Adapter

### ISSUE THREAD

**Issue by chandrabezzo** [flutterchina/dio#1122]
### New Issue Checklist
- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
DioError [DioErrorType.other]: MissingStubError: 'fetch'
No stub was found which matches the arguments of this method call:
fetch(Instance of 'RequestOptions', Instance of '_BoundSinkStream<List<int>, Uint8List>', null)

Add a stub for this method using Mockito's 'when' API, or generate the mock for MockHttpClientAdapter with 'returnNullOnMissingStub: true'.
#0      Mock._noSuchMethod (package:mockito/src/mock.dart:190:7)
#1      Mock.noSuchMethod (package:mockito/src/mock.dart:184:45)
#2      MockHttpClientAdapter.fetch
#3      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:632:46)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter test                          |      |
| Dio Version                    | 4.0.0                                  |      |
| Android Studio / Xcode Version | Android Studio 4.1.3              |      |

### Issue Description and Steps
I use mockito generator `@GenerateMocks([HttpClientAdapter])` to mock HttpClientAdapter. Same issue when I use this implementation `class MockHttpClientAdapter extends Mock implements HttpClientAdapter {}`

**Comment by abnereel** [comment]
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
<asynchronous suspension>

**Comment by chandrabezzo** [comment]
Hi @abnereel you found the same issue with me?
