### ISSUE TITLE
使用Future.wait([])发起并发请求时，dio的拦截器中的lock()会失效

### ISSUE THREAD

**Issue by KingLight** [flutterchina/dio#1129]
### New Issue Checklist

- [ ] 使用`Future.wait([])`发起并发请求时，`dio`的拦截器中的`lock() 会失效

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios / android                          |      |
| Platform Version               | e.g.  1.5.0 / 12.0 / 9.0                              |      |
| Dio Version                    | e.g.  2.1.0 / 1.0.17                                  |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2 / Xcode 10.2.1              |      |
| Repro rate                     | e.g. all the time (100%) / sometimes x% / only once   |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps
在如下使用场景时，`dio`的拦截器中的`lock()`方法会失效
- 项目背景简介
项目中在用户登录后，会将服务端返回的token保存，之后的所有请求都会将token放入到请求头中，但是，token的有效期为5分钟，失效后，会利用登录接口返回的tiken值来重新换取token。
在dio的拦截器中判断保存token的时间戳和当前时间戳，如果token过期，则通过拦截器的`lock()`方法将其锁住，通过另外一个dio实例刷新token，成功后，`unlock()`。

- 拦截器中的`lock()`失效场景
 有一个需求，需要并发请求多个接口，于是便使用了
```
Future.wait([dio.request, dio.request...])
```
代码为简单示例。在并发请求中，恰巧token失效，此时拦截器`lock()`刷新token，但是，lock()方法被执行了多次，既wait方法中请求的次数，而刷新token的方法也会被执行多次，也就是说，在`Futrure.wait([])`中，lock是锁不住并发过来的多次请求，而是，每一个请求都会执行单独的一个lock方法，这就导致第一次过来的请求用新的token调用接口时，随即第二个请求又将token刷新了，导致上一个请求中的token立马失效了

**Comment by Zzy0706** [comment]
有什么新的解决方式吗
暂时不用Future.wait，改用顺序执行解决了这个问题🤔
