### ISSUE TITLE
如何进行抓包呢

### ISSUE THREAD

**Issue by huclengyue** [flutterchina/dio#113]
使用Flutter上使用Dio，PC端使用charles,代理设置正常，同一台手机普通app可以抓包看到连接信息，Flutter写的程序看不到。求解这是怎么回事，要怎么设置才行！

**Comment by mLiXin** [comment]
请问你解决这个问题了吗？

**Comment by huclengyue** [comment]
设置代理。

**Comment by mLiXin** [comment]
什么意思？手机设置了代理，其他app能抓到，但是flutter抓不到。

**Comment by mLiXin** [comment]
代码里面设置代理？
`  dio.onHttpClientCreate = (HttpClient client) {
    client.findProxy = (uri) {
      //proxy all request to localhost:8888
      return "PROXY localhost:8888";
    };
    // 你也可以自己创建一个新的HttpClient实例返回。
    // return new HttpClient(SecurityContext);
  };`

**Comment by manondidi** [comment]
用wireshark试过了吗

**Comment by huclengyue** [comment]
> 代码里面设置代理？
> ` dio.onHttpClientCreate = (HttpClient client) { client.findProxy = (uri) { //proxy all request to localhost:8888 return "PROXY localhost:8888"; }; // 你也可以自己创建一个新的HttpClient实例返回。 // return new HttpClient(SecurityContext); };`

对啊 就是这个。

**Comment by pljhonglu** [comment]
mark ，请问是什么原因呢？

**Comment by yk3372** [comment]
@huclengyue  请问你是怎么解决的呀？

**Comment by yk3372** [comment]
> @huclengyue 请问你是怎么解决的呀？

哦，知道了，把localhost需要换成代理pc的ip地址就可以啦

**Comment by lijy91** [comment]
我为 Flutter 开发了一个查看网络请求的调试库（基于 Facebook Flipper），希望可以 Flutter 开发有帮助。

https://github.com/blankapp/flutter_flipperkit

**Comment by JakeWoki** [comment]
请问下怎么解决？
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client) {
    // config the http client
    client.findProxy = (uri) {
        //proxy all request to localhost:8888
        return "PROXY localhost:8888";
    };
    // you can also create a HttpClient to dio
    // return HttpClient();
};
这样设置了不行的。旧版本不设置可以抓，最新版本3.0.6不管设不设置都不行
@wendux

**Comment by Vidtion** [comment]
代码里定义一个环境变量`PROXY_IP_PORT `：
```
const proxyIpAndPort = String.fromEnvironment('PROXY_IP_PORT', defaultValue: '');
if (proxyIpAndPort.isNotEmpty) {
    client.findProxy = (uri) => "PROXY $proxyIpAndPort;";
}
```
用下面命令启动App就会走代理：
`flutter run --dart-define=PROXY_IP_PORT=192.168.0.52`
