### ISSUE TITLE
DioError [DioErrorType.other]

### ISSUE THREAD

**Issue by liuhan-visva** [flutterchina/dio#1135]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter/android                     |      |
| Platform Version               | 2.0.5 / (8~11)                              |      |
| Dio Version                    | 4.0.0                                  |      |
| Android Studio  Version | AndroidStudio 4.1.3              |      |
| Repro rate                     | all the time (100%) |
| Repro with our demo prj        | does it happen with our demo project?            |      |
| Demo project link              | link to a demo project that highlights the issue |      |

### Issue Description and Steps

DioError [DioErrorType.other]: HttpException: Connection closed while receiving data, uri = xxxxxxxxxxxxx
I/flutter (12398): #0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
I/flutter (12398): #1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
I/flutter (12398): <asynchronous suspension>
I/flutter (12398): #2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
I/flutter (12398): <asynchronous suspension>

**Comment by Kamoba** [comment]
Same here after around 15mn of downloading a big file.
Server side look fine no timeout error.
Maye be need to set `keep-alive` on Dio side.
