### ISSUE TITLE
DioErrorType.other HandshakeException: Handshake error in client (OS Error:  	WRONG_VERSION_NUMBER(tls_record.cc:242))

### ISSUE THREAD

**Issue by tzt1994** [flutterchina/dio#1138]
dio 请求http报错
dio报错如下 （ios模拟器下）
╔╣ DioError ║ DioErrorType.other
flutter: ║  HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(tls_record.cc:242))

flutter版本
![image](https://user-images.githubusercontent.com/15625580/115493673-bc20ea80-a296-11eb-9c95-7f753bcda437.png)

dio设置如下 
![image](https://user-images.githubusercontent.com/15625580/115493686-ca6f0680-a296-11eb-9443-53350f4f0ec9.png)

握手失败，说是版本错误，有没有相似问题或者解决方案。

**Comment by Lawati97** [comment]
@tzt1994 what was the issue and how did you solve it?

**Comment by ydslib** [comment]
@Lawati97 what was the issue and how did you solve it?

**Comment by Lawati97** [comment]
@ydslib  am still looking for a solution i tried recalling the API but no point nothing happened
