### ISSUE TITLE
Continue Download even if current context is destroyed.

### ISSUE THREAD

**Issue by Shubham-Phatale** [flutterchina/dio#1139]
| Platform Name                 | flutter      |      |
| Platform Version               |2.0.3         |      |
| Dio Version                        | 3.0.10      |      |
| Android Studio Version    | 4.1           |      |

i want to continue downloading the file even if i visited another page and when returned on previous page downloading should continue and i should get the progress of that downloading task is there any way where i can get the downloading task and its progress value, i guess my context is being removed when i visit another page, Is it possible to continue download even if context is destroyed something like background download .

**Comment by boldDangdat** [comment]
> | Platform Name | flutter | | | Platform Version |2.0.3 | | | Dio Version | 3.0.10 | | | Android Studio Version | 4.1 | |
> 
> i want to continue downloading the file even if i visited another page and when returned on previous page downloading should continue and i should get the progress of that downloading task is there any way where i can get the downloading task and its progress value, i guess my context is being removed when i visit another page, Is it possible to continue download even if context is destroyed something like background download .

Has this been solved? I want to achieve same.

**Comment by HosseinAsadi** [comment]
I think  below link is thing you want

[https://stackoverflow.com/a/71815758/11831226](url)

**Comment by boldDangdat** [comment]
Let me check
