### ISSUE TITLE
拦截器里能否获取泛型

### ISSUE THREAD

**Issue by phoenixsky** [flutterchina/dio#1144]
有没有办法在拦截器里，获取request方法的泛型类型或者说期待返回的response泛型类型

这样在拦截器里，可以直接将json转换为对象

```dart
void onResponse(Response response, ResponseInterceptorHandler handler) {
     // 这里需要一个T的类型，才能将response.data转成需要的对象
    T data =  JsonConvert.fromJsonAsT<T>(response.data);
    response.data = data;
    return handler.next(response);
}

```

主要是不想对get、post等再包装一个method，里边对数据处理后再返回。
可能我的思路偏了，有没有其他方案

**Comment by chenyucheng97** [comment]
> 有没有办法在拦截器里，获取request方法的泛型类型或者说期待返回的response泛型类型
> 
> 这样在拦截器里，可以直接将json转换为对象
> 
> ```dart
> void onResponse(Response response, ResponseInterceptorHandler handler) {
>      // 这里需要一个T的类型，才能将response.data转成需要的对象
>     T data =  JsonConvert.fromJsonAsT<T>(response.data);
>     response.data = data;
>     return handler.next(response);
> }
> ```
> 
> 主要是不想对get、post等再包装一个method，里边对数据处理后再返回。
> 可能我的思路偏了，有没有其他方案

Future<Response<T>> post<T>(). 看方法签名是可以在调用时添加范型信息，但是我获取Response.data还是一个字符串，是我哪里设置不对吗 ，有人知道怎么处理吗
