### ISSUE TITLE
Persistent CookieJar

### ISSUE THREAD

**Issue by pedromorgan** [flutterchina/dio#115]
Using 
```
  dio: ^1.0.9
  cookie_jar: 0.0.7
```
I need a Persistant Cookie, so I follow example here..
https://github.com/flutterchina/dio#cookie-manager

```dart
var dio = new Dio();
dio.cookieJar = new PersistCookieJar("./cookies");
```
so a few issues....

There is no `PersistCookieJar` in dio, instead its in the "cookie_jar" package..

Importing the package and creating another way, is a compile  error..
```dart
import 'package:dio/dio.dart';
import 'package:cookie_jar/cookie_jar.dart';
Dio dioOb = new Dio(options);
dioOb.cookieJar = new PersistCookieJar("./cookies");

```
It seems I cant set the "cookieJar"..
https://github.com/flutterchina/dio/blob/flutter/lib/src/dio.dart#L45

Help appreciated as this is a blocker

**Comment by wendux** [comment]
1. In flutter, the path passed to `PersistCookieJar` must be valid, you can get the right path with [Path Provider](https://pub.dartlang.org/packages/path_provider) package.
2. please paste your compile error message.

**Comment by pedromorgan** [comment]
@wendux experimented across 2 apps, but below is info... from experimenting..

```dart
import 'package:dio/dio.dart';

// Need to include this, as `PersistCookieJar` is NOT in dio package
import 'package:cookie_jar/cookie_jar.dart';

Options options= new Options(
  baseUrl: "http://192.168.1.13/rpc", 
  connectTimeout: 5000,
  receiveTimeout: 10000,
  followRedirects: false,
  headers: {
    "Accept-Encoding": "gzip"
  }
);
Dio dioOb = new Dio(options);

// Line 24 = not compile.. crash etc
dioOb.cookieJar = new PersistCookieJar("./cookies");
```
```
error: The name 'dioOb' is already defined. (duplicate_definition at [gstl_lab_staff] lib/G.dart:24)
error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name. (missing_const_final_var_or_type at [gstl_lab_staff] lib/G.dart:24)
error: A function body must be provided. (missing_function_body at [gstl_lab_staff] lib/G.dart:24)
error: Functions must have an explicit list of parameters. (missing_function_parameters at [gstl_lab_staff] lib/G.dart:24)
error: Expected a method, getter, setter or operator declaration. (expected_executable at [gstl_lab_staff] lib/G.dart:24)
```

**Comment by pedromorgan** [comment]
Looking at it... and a newbie to dart/flutter.....

maybe the CookieJar should be an option... eg
```dart
new Options(
  cookieJar: null // no cookie
 //cookieJar // by default uses memory
  cookieJar: PersistCookieJar("./cookie") // persistant
)
```

**Comment by pedromorgan** [comment]
@wendux any news on this or a workaround? its kinda a showstopper unfortunately

**Comment by wendux** [comment]
In flutter, the path passed to `PersistCookieJar` must be valid(exists in phones and with write access). you can use [path_provider](https://pub.dartlang.org/packages/path_provider) package to get right path.
