### ISSUE TITLE
DioError [DioErrorType.other]: TlsException: Failure trusting builtin roots (OS Error: CERT_ALREADY_IN_HASH_TABLE(x509_lu.c:356), errno = 0)

### ISSUE THREAD

**Issue by Nickkorol** [flutterchina/dio#1151]
### New Issue Checklist

- [x]  I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                          |      |
| Platform Version               |  2.0.5                             |      |
| Dio Version                    |  4.0.0                                  |      |
| Android Studio / Xcode Version | Android Studio 4.0 / Xcode 12.4              |      |
| Repro rate                     |  all the time (100%)  |      |

### Issue Description and Steps

In my app I am using API, which requires .pem certificates to work properly. They are set when my http client is initialized (method definition on a screenshot below).
![Снимок экрана 2021-05-07 в 09 47 58](https://user-images.githubusercontent.com/9917941/117408970-4fa21e80-af19-11eb-84eb-6faf57d750ac.png)

Dio works fine with this client, but, when I am trying to provide CancelToken to my API Query, I am always getting an error DioError [DioErrorType.other]: TlsException: Failure trusting builtin roots (OS Error: CERT_ALREADY_IN_HASH_TABLE(x509_lu.c:356), errno = 0)

![Снимок экрана 2021-05-07 в 09 50 53](https://user-images.githubusercontent.com/9917941/117409303-b7586980-af19-11eb-96dc-81263630af9e.png)

This error doesn't appear, when I am sending POST or GET queries to any other URLs, which don't require certificates to work.

What can I do about that? Is there a way to fix this error myself?

**Comment by MrShakila** [comment]
@Nickkorol Did you fixed it?
