### ISSUE TITLE
how to get 422 status code data

### ISSUE THREAD

**Issue by ziasultan2** [flutterchina/dio#1153]
I'm using laravel and laravel validation return 422 status code for validation response. I need to access those data how can I able to access those data

**Comment by wwtssu** [comment]
BaseOptions baseOptions = BaseOptions(
      //...
      validateStatus: (status) => [200,422].contains(status), //add valid status code in array
);
Dio _dio = Dio(baseOptions);

**Comment by ziasultan2** [comment]
issue resolve with catch error
