### ISSUE TITLE
MultipartFile file with custom content-type always set to default "application/octet-stream" when submit to server

### ISSUE THREAD

**Issue by cuongmanhvo162** [flutterchina/dio#1154]
Hello,
I try to upload MultiplepartFile, they are all images file. I try try to set those files "content-type" to "image/jpeg" but send I submit to the server, the "content-type" always be recognized as "application/octet-stream".

List<MultipartFile> listOfFiles = [];
    for(int i=0; i<images.length; i++) {
      if(images[i].filePath != null) {
        listOfFiles.add(await MultipartFile.fromFile(images[i].filePath!,
            filename: 'test.jpeg',
            contentType: MediaType.parse('image/jpeg')));
      }
    }

var dio = Dio();
    dio.options.headers['content-Type'] = 'multipart/form-data';
    dio.options.headers['authorization'] = accessToken;
    var response = await dio.post(url, data: formData);

**Comment by cuongmanhvo162** [comment]
This is my server issue, it fixed.

**Comment by bagus-repository** [comment]
@cuongmanhvo162 hey I have same problem, but when using Postman the mime detected true jpeg, when using android detected as application/octet-stream, can you guess something that wrong ?

**Comment by bagus-repository** [comment]
I added the brackets to param name e.g `files[]` (I'm sending multiple files) and this fixed, for dio < 4.0.0 I do not need the brackets.
