### ISSUE TITLE
FormData.fromMap() empty list and list with one item become non-list on server

### ISSUE THREAD

**Issue by jezsung** [flutterchina/dio#1155]
``` dart
await put('/${userId}', data: FormData.fromMap({
    'emptyArray': [],
    'listWithOneItem': ['Hello'],
}));
```
Each of them is parsed as `undefined` and `'Hello'` on node.js server.

**Comment by geniuspegasus** [comment]
same issues

**Comment by geniuspegasus** [comment]
> ```dart
> await put('/${userId}', data: FormData.fromMap({
>     'emptyArray': [],
>     'listWithOneItem': ['Hello'],
> }));
> ```
> 
> Each of them is parsed as `undefined` and `'Hello'` on node.js server.

I found an answer. For element arrays, you have to add [] so that it can consider it as a list like this.

```
await put ('/ $ {userId}', data: FormData.fromMap ({
     'emptyArray []': [],
     'listWithOneItem []': ['Hello'],
}));
```

**Comment by Sipioteo** [comment]
@geniuspegasus when you create the "FormData" to send do it like this:

```
FormData.fromMap(  
            data,  
            ListFormat.multiCompatible  
)
```

**Comment by jezsung** [comment]
What worked for me was only using the @Sipioteo method without the @geniuspegasus suggestion like the below.
``` dart
FormData.fromMap(
{
    'arrayWithOneItem': ['Hello'],
}.
ListFormat.multiCompatible,
)
```
I parsed the form data using [multer](https://www.npmjs.com/package/multer) package with the [Express](https://expressjs.com/) server.

**Comment by abdalazeez1** [comment]
when i encode list like this 
 data['json_key'] = json.encode(listOfInt);///or something  else String .....
now can send list 
MapEntry(json_key: [1])
