### ISSUE TITLE
UI freeze on sending file as binary

### ISSUE THREAD

**Issue by krishnakumarcn** [flutterchina/dio#1156]
The UI is freezing when sending file as binary like below

### Issue Info

```
final File file = File(fileAttachment.path);
Uint8List fileBytes = await file.readAsBytes();
Options options = Options(
         contentType: fileAttachment.type, headers: {
             'Accept': "*/*",
             "Content-Type": fileAttachment.type,
             "Content-Length": fileAttachment.size.toString(),
             'Connection': 'keep-alive',
      }
);

var response = await Dio().put(
        url,
        data: Stream.fromIterable(fileBytes.map((e) => [e])),
        options: options,
        onSendProgress: (int send, int total) {
           print("$send / $total");
        },
);
```

| Info                           | Value                                                 |    
| ------------------------------ | ----------------------------------------------------- | 
| Platform Name                  |  ios / android                          |      
| Dio Version                    | ^4.0.0-prev3                                  |      
| Android Studio Version |  Android Studio 4.1.2            |      

When I'm just replacing the code with `http` client, it works smoothly without any issue.

**Comment by andoutica** [comment]
Any updates on this issue ?
I even cannot post a multipart file with form-data
