### ISSUE TITLE
Dio 网络请求报DioError 

### ISSUE THREAD

**Issue by lanzhu1993** [flutterchina/dio#116]
## Steps to Reproduce

  Options options = Options(
        baseUrl: Config.BASE_URL,
        //连接服务器超时时间，单位是毫秒.
        connectTimeout: 10000,
        receiveTimeout: 30000,
        headers: {
          "Content-Type": "application/json",
          "Accept": "application/json",
          "Authorization": "Bearer " + access_token
        }
    );
    if (params != null && params.isNotEmpty) {
      print("<net> params :" + params.toString());
    }

    String errorMsg = "";
    int statusCode;

    try {
      Response response;
      if (method == GET) {
        //组合GET请求的参数
        if (params != null && params.isNotEmpty) {
          response = await Dio(options).get(url,data: params);
        }else{
          response = await Dio(options).get(url);
        }
      } else {
        if (params != null && params.isNotEmpty) {
          response = await Dio(options).post(url, data: params);
        } else {
          response = await Dio(options).post(url);
        }
      }

## Logs
I/flutter ( 8396): DioError [DioErrorType.DEFAULT]: HttpException: Connection closed while receiving data, uri = http://wh.lanzhu1993.cn/rest/user/get_userinfo

**Comment by lanzhu1993** [comment]
有几次成功，但是访问网络错误和成功几乎交替出现
I/flutter ( 8396): lanzhu=5ObZC7EgTJ2YGF49OOUSmiT4rtMIgK
I/flutter ( 8396): DioError [DioErrorType.DEFAULT]: HttpException: Connection closed while receiving data, uri = http://wh.lanzhu1993.cn/rest/user/get_userinfo
I/flutter ( 8396): <net> errorMsg :DioError [DioErrorType.DEFAULT]: HttpException: Connection closed while receiving data, uri = http://wh.lanzhu1993.cn/rest/user/get_userinfo
I/flutter ( 8396): <net> url :<get>user/get_userinfo
I/flutter ( 8396): lanzhu=5ObZC7EgTJ2YGF49OOUSmiT4rtMIgK
I/flutter ( 8396): DioError [DioErrorType.DEFAULT]: HttpException: Connection closed while receiving data, uri = http://wh.lanzhu1993.cn/rest/user/get_userinfo
I/flutter ( 8396): <net> errorMsg :DioError [DioErrorType.DEFAULT]: HttpException: Connection closed while receiving data, uri = http://wh.lanzhu1993.cn/rest/user/get_userinfo
I/flutter ( 8396): <net> url :<get>user/get_userinfo
I/flutter ( 8396): lanzhu=5ObZC7EgTJ2YGF49OOUSmiT4rtMIgK
I/flutter ( 8396): 获取用户信息成功
I/flutter ( 8396): <net> url :<get>user/get_userinfo
I/flutter ( 8396): lanzhu=5ObZC7EgTJ2YGF49OOUSmiT4rtMIgK
I/flutter ( 8396): 获取用户信息成功

**Comment by wendux** [comment]
看错误信息应该是在接收数据时链接中断了，请检查你的网络是否稳定

**Comment by wsh794972562** [comment]
flutter: *** DioError ***:
flutter: uri: https://data.youww
flutter: DioError [DioErrorType.DEFAULT]: HttpException: Connection closed while receiving data, uri = https://data.youpin.mi.com/app/stat/pipe
flutter:
flutter: Instance of 'RequestOptions'
flutter: HttpException: Connection closed while receiving data, uri = https://data.youww

**Comment by fujiawei-dev** [comment]
I ran into the same problem. It was normal to use libraries in other languages such as Python, Go, or Postman, but only Dio had this error.

**Comment by Shimingli** [comment]
DioError [DioErrorType.other]: HttpException: Connection closed while receiving data,

I/flutter (17218): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
I/flutter (17218): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
I/flutter (17218): #2      DioMixin.post (package:dio/src/dio_mixin.dart:97:12)

It was normal to use libraries in other languages such as Java, 

but only Dio had this error.

so   this is question  can i do something  ？
