### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by RahulSharma-ji** [flutterchina/dio#1167]
**### CODE**
await _dio.download(
urlPath,
'${dir.path}/Download/$filename.mkv}',
cancelToken: _cancel,
onReceiveProgress: (count, total) {
progress = ((count / total) * 100).toInt();
filesize = total ~/ 1024;
downlaodResponse(progress, filesize);
},
);
} catch (e) {
print(e);
}

**### ERROR**
url :-https://eduid01-my.sharepoint.com/personal/mi_eduid01_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=aab222da-9e79-4389-bc27-5a90e4bd2823

I/flutter ( 5002): DioError [DioErrorType.response]: Http status error [403]
I/flutter ( 5002): #0 DioMixin.assureDioError
package:dio/src/dio_mixin.dart:819
I/flutter ( 5002): #1 DioMixin._dispatchRequest
package:dio/src/dio_mixin.dart:678
I/flutter ( 5002):
I/flutter ( 5002): #2 DioMixin.fetch.. (package:dio/src/dio_mixin.dart)
package:dio/src/dio_mixin.dart:1

**Comment by arbile26** [comment]
Facing the same problem on Android!

**Comment by RahulSharma-ji** [comment]
> Facing the same problem on Android!

are you also facing same problem 
?

**Comment by RahulSharma-ji** [comment]
> Facing the same problem on Android!

yes

**Comment by RahulSharma-ji** [comment]
**_all necessary permissions already exists_**     
 <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
