### ISSUE TITLE
4.0 Breaking change Options.listFormat default value multi

### ISSUE THREAD

**Issue by jonathantribouharet** [flutterchina/dio#1168]
Hello,
I think you should revert the commit `change default value of Options.listFormat from mutiComptible to multi`, it's a breaking change with 3.x version (not supported by Ruby On Rails framework).
Or at least add the information as a breaking change in the `Migration to 4.x` file.

**Comment by dawidope** [comment]
There is also an inconsistency in the documentation between those 2 lines:
https://github.com/flutterchina/dio/blob/4.0/dio/lib/src/options.dart#L189
and
https://github.com/flutterchina/dio/blob/4.0/dio/lib/src/options.dart#L714
