### ISSUE TITLE
queryParameters is overridden by BaseOption

### ISSUE THREAD

**Issue by narumishi** [flutterchina/dio#1169]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps
Similar to `extra` and `headers`, in `Dio.get/post/download...` the `queryParameters` should override `BaseOption`, rather be overridden. 
https://github.com/flutterchina/dio/blob/20506b496d41d7c2cc71d323e22634e99dc3ef21/dio/lib/src/options.dart#L285-L287

We should first add `baseOpt.queryParameters ` then `baseOpt.queryParameters `.

```dart
    var query = <String, dynamic>{};
    query.addAll(baseOpt.queryParameters);
    if (queryParameters != null) query.addAll(queryParameters);
```

**Comment by narumishi** [comment]
Any active maintainer? @wendux @harsimranmaan

**Comment by harsimranmaan** [comment]
Hi @narumishi, I don't have maintainer permissions on the project. you can use a forked version with the fix until this gets merged by @wendux

**Comment by narumishi** [comment]
@harsimranmaan thanks for your reply. Hope wendux will come back community soon.
