### ISSUE TITLE
TODO in code references a closed issue

### ISSUE THREAD

**Issue by deinspanjer** [flutterchina/dio#1176]
https://github.com/flutterchina/dio/blob/20506b496d41d7c2cc71d323e22634e99dc3ef21/dio/lib/src/adapters/browser_adapter.dart#L39

Appears to be referencing https://github.com/dart-lang/sdk/issues/18542 . It looks like it was originally based on a version of the send method from browser_client.dart in dart2js that also contained this TODO:
https://chromium.googlesource.com/external/github.com/dart-lang/http/+/eb11c61e7bc14553e3256acafdb4d0096df18c27/lib/browser_client.dart#46

That issue was closed (as not a bug). The browser_client.dart code has since been refactored to properly use an arraybuffer:
https://chromium.googlesource.com/external/github.com/dart-lang/http/+/refs/heads/master/lib/src/browser_client.dart#44

**Comment by deinspanjer** [comment]
still an issue

**Comment by supermuesli** [comment]
could this be related to https://github.com/flutterchina/dio/issues/1027#issuecomment-889474108 ?

**Comment by wendux** [comment]
Updated in the latest version
