### ISSUE TITLE
Dio error with web

### ISSUE THREAD

**Issue by georgesamirmansour** [flutterchina/dio#1178]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter 
| Platform Version               |  12.0 
| Dio Version                    |  4.0.0 
|Android Studio version   |  4.2.1 
| Repro rate                     |  all the time (100%) 
| flutter version             |  2.2.1
|dart support sdk          |  2.12

DioError [DioErrorType.response]: XMLHttpRequest error.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28   get current
packages/dio/src/dio_mixin.dart 819:20                                                                            assureDioError
packages/dio/src/dio_mixin.dart 678:13                                                                            _dispatchRequest
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1618:54                                 runBinary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 169:20                           handleError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 719:46                           handleError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 740:13                           _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 550:5                            [_completeError]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 606:7                            callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15  <fn>

**Comment by PaoloP98** [comment]
This happens to me too from the web. I send a Post request but the server gets an HTTP options request and I get this console error

**Comment by PaoloP98** [comment]
> This happens to me too from the web. I send a Post request but the server gets an HTTP options request and I get this console error

was a CORS problem in my case.

**Comment by GyuriMajercsik** [comment]
@PaoloP98 , how did you solved it ?

**Comment by PaoloP98** [comment]
> @PaoloP98 , how did you solved it ?

I modified the backend settings to accept incoming requests coming from the website domain
For example: http://localhost:7357

Since the port changes with every build you should set a fixed one
`flutter run -d chrome --web-hostname localhost --web-port 7357`

If you use vscode you can put this snippet in `launch.json` in the configuration list
```

```

**Comment by GyuriMajercsik** [comment]
Thanks @PaoloP98 . I'm trying to use a third party API so I'm afraid I cannot change anything on the backend side.

**Comment by alizera** [comment]
I have the same issue on web (with flutter 2 and dio)

**Comment by onguc** [comment]
I only get this error on the web

**Comment by alizera** [comment]
Isn't there anyone who cares?

**Comment by alizera** [comment]
Temporarily you can use this command on macOS to open a chrome browser without this security issue and run the release version on it:

`open /Applications/Google\ Chrome.app --args --user-data-dir="/var/tmp/Chrome dev session" --disable-web-security`

**Comment by rsree1210** [comment]
I am also facing this issue, can somebody help me on this? This issue is still not resolved.

**Comment by GoogleJ** [comment]
I have met this error sevel times

1.This error is caused by CORS, **add server support will solve this error.**

2.Hack solution will only work locally.

**Comment by himmatsingh019** [comment]
Any solution on this?
