### ISSUE TITLE
Adding CLI executable which is written in dart with the package itself.

### ISSUE THREAD

**Issue by EhsanAramide** [flutterchina/dio#1183]
### New Issue Checklist
- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                       | Value                   |
| -------------------------- | ----------------------- |
| Platform Name              | Windows / Linux / macOS |
| Platform Version Tested on | lastest version         |
| Dio Version                | 4.0.0                   |
| New Dependencies                | [![yaml][yaml-badge]][yaml-pub] [![args][args-badge]][args-pub] |

### Issue Description and Steps
I'm working on a new feature in the [Dio][dio-pub] package, with this feature (actually it is a CLI HTTP client that uses Dio as its client) the package users addition to using APIs they can use CLI client for their configuration and other operations that Dio can do them as an HTTP client. This app can be used as a client in Front-end or Back-end development.
You can contribute to this feature on [my forked repository][forked-repo] in `feature/cli-executable` branch, for more information about contributing and the application itself read [README.md file][dio-exe-doc]

You can contact me on [Twitter][twitter] or this issue.
***What is your idea about this feature to continue or not? (your ideas are important for me please let me know)***

[yaml-badge]: https://img.shields.io/badge/yaml-3.1.0-blue
[yaml-pub]: https://pub.dev/packages/yaml
[args-badge]: https://img.shields.io/badge/args-2.1.1-blue
[args-pub]: https://pub.dev/packages/args
[dio-pub]: https://pub.dev/packages/dio
[forked-repo]: https://github.com/EhsanAramide/dio
[dio-exe-doc]: https://github.com/EhsanAramide/dio/tree/feature/cli-executable/dio/bin
[twitter]: https://twitter.com/EhsanAramide

**Comment by prajwal27** [comment]
Hey, 
So, to put more thought into whether to continue this feature or not,
- Why would people need it, with the help of extensions in VS Code or postman or insomnia, it's very convenient.
on the other hand
- This tool would help in building more CLI tools that can depend on dio 
- It also enables us to test our flutter code.

**Comment by EhsanAramide** [comment]
Hi @prajwal27 
For your question about why people should use it, actually, my reason was to create a minimal HTTP client based on `dio` and with embed executable feature in the pub package manager, the package suggests it to its users my another reason was to make dart ecosystem more integrated and in the development process that uses completely dart (in back-end and front-end) we can use it easily.
This minimal CLI HTTP client isn't comparable with for example postman or REST-client on vscode because it is minimal and the power of this feature is its config files like postman you can document your tested requests or APIs and share with people.
The main idea is not complete and needs more feature and documentation to presents itself better to other.
I just wanna open the issue to get other's ideas to create this feature faster together with more features as now as it has.
You can read the documentation that I wrote and if you have ideas to make it better you can put comments here or open an issue on my forked repo.
**NOTE:** the documentation and its features aren't complete in this time.

**Comment by prajwal27** [comment]
@EhsanAramide , is this still active?

**Comment by EhsanAramide** [comment]
@prajwal27 Thank you about your comment, I am busy in this year and I can't work on code base it is active but not like previous. I added some new documentation last month to the executable on my forked repo after that I didn't update repo.
