### ISSUE TITLE
HttpException: Connection closed while receiving data

### ISSUE THREAD

**Issue by jianleepb** [flutterchina/dio#1185]
post 数据量比较大的时候直接报error。
[✓] Flutter (Channel stable, 1.22.5)
[✓] dio: ^3.0.8

**Comment by y-alkhateeb** [comment]
+1

**Comment by troncomputers** [comment]
I think it's same for me. Users are able to send request but there is no response. On server side (API) all data is saved correctly, no exception, no errors. I don't have an exception message from mobile devices because I'm not able to reproduce this behavior on my devices. All I have is duplications in ERP system because there is no response and app is not able to unflag data from "toSend" status.

**Comment by mirkancal** [comment]
I don't receive anything from Dio. It's like sending http request to blackhole. No exception or errors.

**Comment by mirkancal** [comment]
I find the issue, with the new Dio API, you need to return handler.next, otherwise interceptors just stuck.

```
dio.interceptors.add(InterceptorsWrapper(
    onRequest:(options, handler){
     // Do something before request is sent
     return handler.next(options); //continue
     // If you want to resolve the request with some custom data，
     // you can resolve a `Response` object eg: return `dio.resolve(response)`.
     // If you want to reject the request with a error message,
     // you can reject a `DioError` object eg: return `dio.reject(dioError)`
    },
    onResponse:(response,handler) {
     // Do something with response data
     return handler.next(response); // continue
     // If you want to reject the request with a error message,
     // you can reject a `DioError` object eg: return `dio.reject(dioError)` 
    },
    onError: (DioError e, handler) {
     // Do something with response error
     return  handler.next(e);//continue
     // If you want to resolve the request with some custom data，
     // you can resolve a `Response` object eg: return `dio.resolve(response)`.  
    }
));

```

**Comment by jianleepb** [comment]
service error , the post data is too large

**Comment by FakharAlyas119** [comment]
i am also facing the same issue 
any one how to solve this issue?

**Comment by sara010** [comment]
same problem

**Comment by guischpor** [comment]
same problem

**Comment by guischpor** [comment]
@FakharAlyas119 Could you solved this issue?

**Comment by FakharAlyas119** [comment]
> @FakharAlyas119 Could you solved this issue?

Nope looking for the soulation

**Comment by FakharAlyas119** [comment]
@guischpor 
Nope looking for the soulation

**Comment by Shimingli** [comment]
me too :  
 DioError [DioErrorType.other]: HttpException: Connection closed while receiving data

**Comment by KaranImaginationMedia** [comment]
flutter: DioException [unknown]: null
Error: HttpException: Connection closed while receiving data,

**Comment by santoshpatil2003** [comment]
Error downloading audio: DioException [unknown]: null
Error: HttpException: Connection closed while receiving data,

**Comment by nebulaqueen** [comment]
Me too
sometime: "Error: HttpException: Connection closed while receiving data, uri ="
sometime: "Error: HttpException: Connection reset by peer, uri ="
