### ISSUE TITLE
关于响应拦截器问题

### ISSUE THREAD

**Issue by itlwy** [flutterchina/dio#1188]
背景：
        在使用多个拦截器组成的链条进行拦截处理时，我有一个加解密的拦截器，在请求拦截时进行加密，然后在响应回来时进行解密

问题：
        在拦截器之前还会有其他拦截器处理工序，比如我前面还有一个对请求参数自动装箱成指定json格式和逆向的拆箱过程。但是目前dio的响应拦截链条的顺序和请求链条是一致的，这导致回来的响应不是最先调用我的最后一个解密拦截器，所以无法进行拆箱操作。

源码问题点如下：
代码地址：`src/dio_mixin.dart`
```
Future<Response<T>> fetch<T>(RequestOptions requestOptions) async {
           // Add response interceptors to request flow    
           interceptors.forEach((Interceptor interceptor) {      
                 future = future.then(_responseInterceptorWrapper(interceptor.onResponse));    
           });
}
```
建议：
         响应链条可支持正向或逆向（个人觉得逆向常见）

盼回复，谢谢！

**Comment by itlwy** [comment]
@wendux

**Comment by jiechic** [comment]
我也遇到这个问题
项目中，我们加了加了多个拦截器
1、map
2、cookie
3、log
4、decode-encode

按照现在拦截器的调用顺序是
request->map->cookie->log->encode->reponse->map->cookie->log->decode

但是，我们理解的拦截器应该是这么做的
request ->map->cookie->log->encode->reponse
              <-map<-cookie<-log<-decode<----|

**Comment by SheepYang1993** [comment]
最好是能设置拦截器优先级顺序

**Comment by jiechic** [comment]
any update?
