### ISSUE TITLE
QueryParameters with the same key 

### ISSUE THREAD

**Issue by GyuriMajercsik** [flutterchina/dio#1189]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps

Is there a way to achieve the following query parameter construction, as described [here](https://github.com/nestjsx/crud/wiki/Requests#filter): 

`?filter=isVillain||$eq||false&filter=city||$eq||Arkham`

Basically, we have the same key, `filter`, multiple times in the query. 
I don't see a way right now using the `DioForNative.get` method and `queryParameters` parameter, which is a `Map` and the same keys are just overwritten.

**Comment by JulianBissekkou** [comment]
We need this feature as well.

**Comment by JulianBissekkou** [comment]
Using `dio.options.listFormat = ListFormat.multi` should to the trick!

**Comment by GyuriMajercsik** [comment]
I found a workaround for this: 

```
      var uri = Uri.parse(baseUrl).resolveUri(
        Uri(
          path: 'url/path',
          queryParameters: {
            'param_name': [
              'first_value',
              'second_value',              
            ],
          },
        ),
      );

      Response response = await _client.getUri(uri);
```

**Comment by phuhk** [comment]
I have the same issue as well.

**Comment by Ruslanbek0809** [comment]
> I found a workaround for this:
> 
> ```
>       var uri = Uri.parse(baseUrl).resolveUri(
>         Uri(
>           path: 'url/path',
>           queryParameters: {
>             'param_name': [
>               'first_value',
>               'second_value',              
>             ],
>           },
>         ),
>       );
> 
>       Response response = await _client.getUri(uri);
> ```

This works. Thanks.

**Comment by aymendn** [comment]
My workaround for this:
- I made a funciton to turn `List` of map queries into a `String`
```dart
String queryParametersToString(List<Map<String, dynamic>> queryParameters) {
  String queryString = '?';
  for (var element in queryParameters) {
    queryString += '${element.keys.first}=${element.values.first}&';
  }
  return queryString.substring(0, queryString.length - 1);
}
```

- Then I pass queries like this:
```dart
 dio.get('notification/client/$query');
```

Instead of this:
```dart
dio.get(
  'notification/client/',
  queryParameters: {'query': ...},
);
```

**Comment by kuhnroyal** [comment]
@aymendn This can cause encoding problems. You should consider using `ListParam` and `ListFormat.multi`.
