### ISSUE TITLE
 [DioErrorType.DEFAULT]: FormatException: Invalid HTTP header field value: 

### ISSUE THREAD

**Issue by gonganruyi** [flutterchina/dio#119]
DioError [DioErrorType.DEFAULT]: FormatException: Invalid HTTP header field value: "iAkiGSemzGfQmsD8UzewgFpCbGQRjT3XSkKVdoS7e3Wl5XwgEry8Dnz/3v+QiMy92ukOMO2Hd34S\nZlN6NM4Uo/LL6k27CctDS01DeJfNTDxpd8SMJ3y4vyiACyl3HUUuIj3MjqusrdeHkvVtUfOG35O1\n7nnotcdhxQAsGRwQKfw=\n"

我设置的头部信息

**Comment by wendux** [comment]
去掉换行符试试
