### ISSUE TITLE
Dio slow on web

### ISSUE THREAD

**Issue by amirmhmdi** [flutterchina/dio#1194]
### WEB is so Slow

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Web                        |      |
| Platform Version               | 2.2.2                             |      |
| Dio Version                    |   3.0.0 / 4.0.0                                  |      |

I'm on flutter 2.2.2 and every thing okay on android and iOS ! but on web is so slow.
I used dio 3.0.0 and dio 4.0.0 but it took about 3 sec to fetch data but when I use http.get it take about 100ms .

**Comment by jgoyvaerts** [comment]
This issue has been fixed on our fork of dio, [dio_http](https://github.com/dart-tools/dio_http).

Package is available here: https://pub.dev/packages/dio_http
