### ISSUE TITLE
not receiving image on server

### ISSUE THREAD

**Issue by ziasultan2** [flutterchina/dio#1195]
Trying to upload image to server but not receiving image in server 
```
   var formData = FormData.fromMap({
      'first_name': 'zia sultan',
      'last_name': 'sultan',
      'email': 'stu@ss.cc',
      'phone': '2137009021',
      'profile_photo': await MultipartFile.fromFile(photo.path,
          filename: photo.path.split('/').last),
      'profile_video': await MultipartFile.fromFile(photo.path,
          filename: photo.path.split('/').last),
    });


dio.post(Url.register, data: formData1).then((r) async { 
   print(r.data);.
}
```

**Comment by ankur-arch** [comment]
Your sending **formData1** while the form data is initialized with **formData**.

**Comment by Manasmd** [comment]
Were you guys able to fix it? 
For me I am trying to upload videos, it works fine but sometimes the uploaded video is broken on the server. This happens like every 15 - 20 uploads. so it's very hard to troubleshoot and see whats going wrong
