### ISSUE TITLE
i am unable to catch dio error

### ISSUE THREAD

**Issue by mohadel92** [flutterchina/dio#1198]
### New Issue Checklist

- [true ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios / android                          |      |
| Platform Version               | e.g.  2.2.0 / 12.0 / 9.0                              |      |
| Dio Version                    | e.g.  4..0.0                                  |      |
| Android Studio  / Xcode Version | e.g. Android Studio 4.1 / Xcode 12.4              |      |

### Issue Description and Steps

i used to use dio since older version
i catch errors with
```
 e.response.data
e.response.headers

```

now after migrating to null safety
and flutter 2.2 i cannot catch any errors i get message 

any help?
<a href="https://ibb.co/9Ttr1dq"><img src="https://i.ibb.co/cFLrZsN/Whats-App-Image-2021-06-19-at-10-58-44-PM.jpg" alt="Whats-App-Image-2021-06-19-at-10-58-44-PM" border="0"></a>

**Comment by bagus-repository** [comment]
please make sure you are catching a DioError Object see [Handling Error](https://github.com/flutterchina/dio#handling-errors).

**Comment by dhsont** [comment]
DioError  is not capturing any 400 -> 500 errors

**Comment by mohadel92** [comment]
@bagus-repository  thanks but i have never used this method
and all apps used to work fine

**Comment by rymesaint** [comment]
DioError is not capturing any errors, because when i'm adding headers to the options

**Comment by ApoorvaAditya** [comment]
I had a similar problem when I migrated my app to null safety and dio from 3.0.10 to 4.0.0. After bunch of testing I found out that an `onError` interceptor was the cause of the problem for me. The interceptor basically consumed the error and didn't pass the error back to the calling function and therefore no exception/error was being caught. 

I fixed it by using the `ErrorInterceptorHandler` parameter of the `onError` function of the interceptor and adding a `ErrorInterceptorHandler.reject(error);` at the end of the `onError` function. Here's an example:
```
dio.interceptors.add(
  InterceptorsWrapper(
    onError: (error, handler) {
      // Do stuff here
      handler.reject(error); // Added this line to let error propagate outside the interceptor
    },
  ),
);
```

**Comment by sopherwang** [comment]
> I had a similar problem when I migrated my app to null safety and dio from 3.0.10 to 4.0.0. After bunch of testing I found out that an `onError` interceptor was the cause of the problem for me. The interceptor basically consumed the error and didn't pass the error back to the calling function and therefore no exception/error was being caught.
> 
> I fixed it by using the `ErrorInterceptorHandler` parameter of the `onError` function of the interceptor and adding a `ErrorInterceptorHandler.reject(error);` at the end of the `onError` function. Here's an example:
> 
> ```
> dio.interceptors.add(
>   InterceptorsWrapper(
>     onError: (error, handler) {
>       // Do stuff here
>       handler.reject(error); // Added this line to let error propagate outside the interceptor
>     },
>   ),
> );
> ```

Hi @ApoorvaAditya Thanks for the solution. But I's still not able to catch the exceptions. I can see the exceptions go through the intercepted callbacks but after `reject` the error, it exception still unhandled. Would you mind providing more detailed solution? Thanks.

**Comment by shakthizen** [comment]
I found a hacky solution. We are overriding all the exceptions thrown by default. Then we are going to create custom interceptor to handle and throw exceptions. This way we can catch the DioException as we did before.

1. Create a base client like this. You have to set validateStatus function to return `true`  whatever the status code is.
```dart
final baseOptions = BaseOptions(
  baseUrl: host,
  contentType: Headers.jsonContentType,
  validateStatus: (int? status) {
    return status != null;
    // return status != null && status >= 200 && status < 300;
  },
);

final dio = Dio(baseOptions);
```

2. Create a custom interceptor to raise exceptions
```dart
class ErrorInterceptor extends Interceptor {
  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    final status = response.statusCode;
    final isValid = status != null && status >= 200 && status < 300;
    if (!isValid) {
      throw DioException.badResponse(
        statusCode: status!,
        requestOptions: response.requestOptions,
        response: response,
      );
    }
    super.onResponse(response, handler);
  }
}
```

3. Add that to the Dio interceptors list
```dart
dio.interceptors.addAll([
    ErrorInterceptor(),
]);
```

Link to my gist https://gist.github.com/shakthizen/d644aaf19ca837a4a29a92ebad551055
