### ISSUE TITLE
使用cookiejar 报错

### ISSUE THREAD

**Issue by keluokeda** [flutterchina/dio#12]
_dio.cookieJar = new PersistCookieJar();

[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
FileSystemException: Creation failed, path = './.cookies/' (OS Error: Permission denied, errno = 13)
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)

**Comment by wendux** [comment]
flutter中cookie文件保存的路径要用pathprovider 这类插件去获取，因为每个app的存储目录都是私有的

**Comment by keluokeda** [comment]
@wendux 已经解决，感谢
