### ISSUE TITLE
IOS Release package, unlock after lock screen, interface call failed

### ISSUE THREAD

**Issue by xiaobo57block** [flutterchina/dio#1200]
In DIO 4.0.0, the IOS Release package,the interface is loading, lock the screen immediately, unlock after a few seconds, the interface call fails. The error message is as follows:
DioError [DioErrorType.other]: HttpException: , uri = https://viral-dev.finnplay.net/billfold-api/login
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>
but the IOS Debug package works.Android is normal too.

**Comment by hadi-neon** [comment]
@xiaobo57block did you find any solution ?
