### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by paulowender** [flutterchina/dio#1203]
I get this error on run flutter run on android 8, with dio 4.0.0
![image](https://user-images.githubusercontent.com/42776823/123197544-a5a33500-d479-11eb-9f0a-e2e721a34d01.png)

**Comment by BTPDarren** [comment]
I am also getting the exact same error when trying to build apk and when running builder

**Comment by BTPDarren** [comment]
```
[WARNING] /E:/Flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0/lib/src/dio_mixin.dart:678:7: Error: 'Cthrow' isn't a type.
      Cthrow assureDioError(e, reqOpt);
      ^^^^^^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0/lib/src/dio_mixin.dart:678:14: Error: Expected ';' after this.
      Cthrow assureDioError(e, reqOpt);
             ^^^^^^^^^^^^^^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0/lib/src/dio_mixin.dart:678:30: Error: Expected ')' before this.
      Cthrow assureDioError(e, reqOpt);
                             ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0/lib/src/dio_mixin.dart:627:23: Error: A non-null value must be returned since the return type 'Response<T>' doesn't allow null.
 - 'Response' is from 'package:dio/src/response.dart' ('/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0/lib/src/response.dart').
  Future<Response<T>> _dispatchRequest<T>(RequestOptions reqOpt) async {
                      ^
[INFO] Precompiling build script... completed, took 1.2s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

**Comment by BTPDarren** [comment]
By doing some experimenting with another project I have discovered that it must be retrofit that's causing this situation

if I do not include retrofit 4 in the pubspec.yaml it will not fail to build or run

**Comment by BTPDarren** [comment]
Sorry, i take that back,  looks like it is dio

retrofit is using this of course

**Comment by BTPDarren** [comment]
@paulowender I tried many things, eventually I deleted the dio folder from the E:\Flutter\.pub-cache\hosted\pub.dartlang.org and did a flutter pub get 

This re-downloaded the package and now its back as it was again.  all working

**Comment by BTPDarren** [comment]
Further to this. I know what happened

While debugging my retrofit it had a dio error when and I managed to accidently hit C and changed the dio_mixin.dart file

from
`    } catch (e) {
      throw assureDioError(e, reqOpt);
    }`

to

`    } catch (e) {
      Cthrow assureDioError(e, reqOpt);
    }`

As I am still new to flutter and vscode I did not realize that Cthrow was not a true keyword!

However, this has made me realize that removing dependencies from a project and saving does not remove the package so you need to force a re-download, or as I did, remove and do a pub get

**Comment by paulowender** [comment]
@BTPDarren, this worked for me, remove the folder from and download again. Thanks for your help :)

**Comment by irfan-429** [comment]
> @paulowender I tried many things, eventually I deleted the dio folder from the E:\Flutter.pub-cache\hosted\pub.dartlang.org and did a flutter pub get
> 
> This re-downloaded the package and now its back as it was again. all working

This also worked for me. Thanks!
