### ISSUE TITLE
There's no constant named 'RESPONSE' in 'DioErrorType'. dio version 4.0.0

### ISSUE THREAD

**Issue by myomyintaung1411** [flutterchina/dio#1208]
import 'package:dio/dio.dart';

class DioExceptions implements Exception {
    DioExceptions.fromDioError(DioError dioError) {
    switch (dioError.type) {
      case DioErrorType.CANCEL:
        message = "Request to API server was cancelled";
        break;
      case  DioErrorType.CONNECT_TIMEOUT:
        message = "Connection timeout with API server";
        break;
      case DioErrorType.DEFAULT:
        message = "Connection to API server failed due to internet connection";
        break;
      case DioErrorType.RECEIVE_TIMEOUT:
        message = "Receive timeout in connection with API server";
        break;
      case DioErrorType.RESPONSE:
        message =
            _handleError(dioError.response!.statusCode, dioError.response!.data);
        break;
      case  DioErrorType.SEND_TIMEOUT:
        message = "Send timeout in connection with API server";
        break;
      default:
        message = "Something went wrong";
        break;
    }
  }

  String? message;

  String _handleError(int statusCode, dynamic error) {
    switch (statusCode) {
      case 400:
        return 'Bad request';
      case 404:
        return error["message"];
      case 500:
        return 'Internal server error';
      default:
        return 'Oops something went wrong';
    }
  }

  @override
  String toString() => message;
}

**Comment by Rimextender** [comment]
@myomyintaung1411 hello, DioErrorType.RESPONSE it is now DioErrorType.response, they switched to camelCase, same applies to other DioErrorType constants. Also, DioErrorType.DEFAULT is now DioErrorType.other.
