### ISSUE TITLE
null response on dioerror [web]

### ISSUE THREAD

**Issue by oncul** [flutterchina/dio#1209]
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. web                          |      |
| Dio Version                    | e.g.  4.0.0                                   |      |

DioError returns empty response and cannot access status code of response. 401, 403, 404

```
try{} on DioError catch(e){
   e.response?.statusCode -> response is null
}
```

**Comment by oncul** [comment]
Also i added validateStatus option. its not working on web.

```
BaseOptions options = BaseOptions(
        baseUrl: Api.baseUri,
        headers: {"Accept": "application/json", "Authorization": "Bearer " + await getToken()},
        responseType: ResponseType.json,
        receiveDataWhenStatusError: true,
        followRedirects: true,
        validateStatus: (statusCode) {
          print("STATUS CODE: $statusCode");
          return true;
        });
```

**Comment by VirusEcks** [comment]
i also got this exception in web only

**Comment by oncul** [comment]
I found a comment in this file.
[Code](https://github.com/flutterchina/dio/blob/master/dio/lib/src/adapters/browser_adapter.dart#L71)

I think there is a limitation about CORS and 40* error codes.

**Comment by VirusEcks** [comment]
i tried it with calls to localhost and correct urls (works on android) still got the exception

**Comment by AhmedNasser7797** [comment]
i still got the same issue
dio: ^4.0.3

╔╣ DioError ║ Status: null null
║  null

flutter version :Channel stable, 2.5.3

**Comment by mxkdev** [comment]
It was a CORS issue for me, if you check the console output in chrome it will show you the CORS error. I had to set a specific localhost port for flutter web and used the --web-port=8000  argument for example. Then added the origin "http://localhost:8000" to my backend CORS policy.
Would be nice, if Dio could throw a CORS error, if something like that is even possible.

**Comment by vpositron** [comment]
I have the same issue for the web app!
For android it works fine....

**Comment by jgoyvaerts** [comment]
> I have the same issue for the web app! For android it works fine.... PS. It`s not CORS.

If you are confident it's not CORS please make a separate issue with a FULL minimal reproduction case and we can take a look at it.
