### ISSUE TITLE
请问如何使用https的IP直连(httpdns)?

### ISSUE THREAD

**Issue by ppyupp** [flutterchina/dio#121]
请问如何使用https的IP直连(httpdns)?

**Comment by wendux** [comment]
我说一下我目前的研究结果，如果有遗漏的点，欢迎补充。

如果是直连：
ping baidu.com, 我这得到的ip是：140.143.226.158

然后请求：
```
await dio.get("https://140.143.226.158",).then(print);
```
正如所料，证书校验不会通过，请求失败。主要原因是：
 1. ip直连时服务器获取不到host信息，所以不知道应该返回哪个证书，一般返回一个默认证书.
 2. ip地址肯定不在返回证书的dns 列表中，此步骤必然失败

### 对于问题2：
假设服务器返回的就是baidu.com的证书，但是由于HttpClient在收到证书后，校验时会发现ip地址证书的dns 列表中, 校验会失败。那么有没有办法来自定义host校验？
Android中是有的：

![image](https://user-images.githubusercontent.com/20411648/52839337-bcf6e880-3130-11e9-8669-425301a323f7.png)

上面代码中, hostname即为ip地址，我们在校验时换成host(baidu.com)即可。
**但是，很不幸，我在Dart SDK文档中目前没有找到自定义host校验的接口！**

### 对于问题1
关键就是在ssl握手时能否有机制告诉HttpClient ip地址对应的域名？这样在ssl握手时服务器就知道应该返回哪个host的证书了。这个在android中依然是有办法的(通过创建一个SSLSocketFactory)，但是在dart中依然很不幸，我没有找到相应的接口。

## 总结
综上所述，如果非要使用https ip直连，则只能将证书校验忽略，如：
```dart
  var dio = new Dio();
  dio.interceptors.add(LogInterceptor(responseBody: true));
  (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate=(client){
    client.badCertificateCallback=(X509Certificate cert, String host, int port){
      // 默认情况下，这个cert证书是网站颁发机构的证书，并不是网站证书，开发者可以验证一下
      return true; //忽略证书校验
    };
  };
  await dio.get("https://140.143.226.158",).then(print); //可以成功
```
但如此一下，https协议的安全策略全部废掉了，这样无法防御通过伪造证书的中间人攻击。

**Comment by ppyupp** [comment]
确实是这样, 我绕了一圈也放弃了, 暂时没找到答案
不说dart, ios我也没找到好的方案来实现https直连

**Comment by mrtian** [comment]
有人解决了这个问题了吗？弄得头大了，现在运营商劫持域名太烦人了

**Comment by kennir** [comment]
Any update after 2 years passed?

Thanks

**Comment by sunnyxibei** [comment]
Are there any plans to support this feature?
