### ISSUE TITLE
Create Options from RequestOptions in interceptors

### ISSUE THREAD

**Issue by hpoul** [flutterchina/dio#1212]
A common pattern in an error handler is to clone the `RequestOptions` to retry the request. in dio 3.0 this could simply be done by reusing the `RequestOptions` but in 4.0 one needs to create a new `Options` but as far as I can see there is no finished method to do so.

I'd propose to introduce either a `RequestOptions.toOptions()` or a `Options.fromRequestOptions`.

For example `fresh_dio` [manually copies all attributes of](https://github.com/felangel/fresh/blob/2b555c869860145bfbe109a38397119d7c12db9d/packages/fresh_dio/lib/src/fresh.dart#L147-L163) `RequestOptions` into `Options` which seems pretty error prone in the case dio changes anything.

**Comment by yannickvg** [comment]
Agree with the proposal. While upgrading to 4.0 I was looking for a similar constructor as proposed for retrying a request in case of an error.

**Comment by hpoul** [comment]
Ping
