### ISSUE TITLE
error: type 'Future<dynamic>' is not a subtype of type 'Response<dynamic>' in type cast

### ISSUE THREAD

**Issue by akadatsky** [flutterchina/dio#1214]
I use dio 4.0.0  and got an error type 'Future<dynamic>' is not a subtype of type 'Response<dynamic>' in type cast. 
It hapens in dio_mixin.dart in _dispatchRequest method in this lines:
https://github.com/flutterchina/dio/blob/master/dio/lib/src/dio_mixin.dart#L666
```
      if (statusOk) {
        return checkIfNeedEnqueue(interceptors.responseLock, () => ret)
            as Response<T>;
      } 
```
It happens cause checkIfNeedEnqueue() return Future instead of Response in case when lock.locked is true.
checkIfNeedEnqueue code:
https://github.com/flutterchina/dio/blob/master/dio/lib/src/dio_mixin.dart#L790
```
  static FutureOr checkIfNeedEnqueue(Lock lock, EnqueueCallback callback) {
    if (lock.locked) {
      return lock.enqueue(callback);
    } else {
      return callback();
    }
  }

  Future? enqueue(EnqueueCallback callback) {
    if (locked) {
      // we use a future as a queue
      return _lock!.then((d) => callback());
    }
    return null;
  }
```
Could you please fix it?

**Comment by luojt** [comment]
I also encountered this problem, who can solve it

**Comment by luojt** [comment]
My processing method is to ignore the error and continue to execute the subsequent application logic.

**Comment by akadatsky** [comment]
Any update?

**Comment by manhlh** [comment]
I also encountered this problem.. :(
