### ISSUE TITLE
Dio replace ':' to '%3A' when using queryParams

### ISSUE THREAD

**Issue by smartoryu** [flutterchina/dio#1217]
Hello, there's seems to be an issue when using queryParams
I made my API_URL as constant

```dart
const API_URL = "https://my-api.domain/"
```

I need to pass a bunch of query, so I have to use a queryParams like this

```dart
var uri = Uri(path: "$API_URL/transactions", queryParameters: {
  "userId": 123,
  "status": ["done", "failed"],
});
```

But I got `Invalid value` error and turns out the `uri` become
`https%3A//my-api.domain/user?userId=123?status=done?status=failed`

My current workaround is to convert uri as string then replace `%3A` with `:`

I hope this one could be solved.

**Comment by zubyf09** [comment]
I am facing the same issue in the latest version. : is replaced with %3A. Is there any work around?

**Comment by AlexV525** [comment]
> But I got `Invalid value` error and turns out the `uri` become `https%3A//my-api.domain/user?userId=123?status=done?status=failed`

This is nothing related to the package itself, but the wrong usage of `path`. Here you are using the `path` incorrectly.

**Comment by zubyf09** [comment]
@AlexV525 
I am using Retrofit with Dio.  in Get Request sending firebase token. Firebase token contains  **(:)** eh4mX76mi05UlcUHO4B2Ip:

 https://test.com/app/v5/push/add?key=123&udid=xxxxxxO4B2Ip%3AAPA91bEAd--TLEXXXXXX
 RequestOptions class line 580
  final query = Transformer.urlEncodeQueryMap(queryParameters, listFormat); lines  adds %30A in place of :
  
  I know it's not a good approach to send tokens in get Request. But these APIs are really old and written by a different team. We don't have access to them now. 
  
  Is there any workaround I can change uri on run time?
