### ISSUE TITLE
请问如何使用泛型

### ISSUE THREAD

**Issue by hustlemickey** [flutterchina/dio#122]
## Steps to Reproduce
`Dio dio = new Dio(); `
`Response<Users> users = await dio.get<Users>(API.Users);`
`print(users);`
## Logs
E/flutter (22135): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (22135): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Users'

**Comment by YWD** [comment]
泛型貌似没用了，dart不支持反射，数据只能自己解析了。

**Comment by wendux** [comment]
#77 
> `Response<T>` "T" must be one of `Map`、`List`、`String` 、`HttpClientResponse`, Which one ultimately depends on `Options.responseType`:
> 
> ![image](https://user-images.githubusercontent.com/20411648/46711460-fdc08b80-cc7e-11e8-81cb-4bb2a1c8c424.png)
> 
> T	responseType
> Map、List	ResponseType.JSON
> String	ResponseType.PLAIN
> HttpClientResponse	ResponseType.STREAM
