### ISSUE TITLE
Web and APK Error: Not found: 'dart:html'

### ISSUE THREAD

**Issue by twovs** [flutterchina/dio#1222]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1083], locale zh-CN)
    • Flutter version 2.2.3 at D:\flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at D:/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = D:/Android/Sdk
    • Java binary at: D:\Android_Studio_UP\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\gaosh\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android_Studio_UP
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at D:\myIdea\IntelliJ IDEA 2020.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • oppo r9 plustm a (mobile) • emulator-5554 • android-x86    • Android 5.1.1 (API 22)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                • edge          • web-javascript • Microsoft Edge 91.0.864.67
    ! Device 127.0.0.1:5555 is offline.

• No issues found!
Process finished with exit code 0

### Issue Description and Steps

Launching lib\main.dart on oppo r9 plustm a in debug mode...
Running Gradle task 'assembleDebug'...
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/http-0.13.3/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart:13:18: Error: 'HttpRequest' isn't a type.
  final _xhrs = <HttpRequest>[];
                 ^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/http-0.13.3/lib/src/browser_client.dart:34:18: Error: 'HttpRequest' isn't a type.
  final _xhrs = <HttpRequest>{};
                 ^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart:26:15: Error: The method 'HttpRequest' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio/src/adapters/browser_adapter.dart' ('/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
    var xhr = HttpRequest();
              ^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart:40:34: Error: The method 'Blob' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio/src/adapters/browser_adapter.dart' ('/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blob'.
      var blob = xhr.response ?? Blob([]);
                                 ^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart:41:20: Error: The method 'FileReader' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio/src/adapters/browser_adapter.dart' ('/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-4.0.0/lib/src/adapters/browser_adapter.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.
      var reader = FileReader();
                   ^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/http-0.13.3/lib/src/browser_client.dart:46:15: Error: The method 'HttpRequest' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/http-0.13.3/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
    var xhr = HttpRequest();
              ^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* UR
Is)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:36:7)
#1      asFileUri (package:vm/kernel_front_end.dart:599:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:738:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:562:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/se
rver.dart:180:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by twovs** [comment]
how to fix：

delete 

/// TODO: Web和APK冲突，删除一下引用
// import 'package:dio/adapter_browser.dart';
// import 'package:dio/browser_imp.dart';

**Comment by sittingbool** [comment]
I don't get it. How can this work on both platforms?
