### ISSUE TITLE
OAuth2 in Flutter with cookie?

### ISSUE THREAD

**Issue by cylak** [flutterchina/dio#123]
Hi,

I'm noob! How can I implement this in `Dio` and `cookie_jar`?

I want to use OAuth2 to login to a self hosted WordPress installation.

At the first request it goes success and I get login and get cookie. But in the second request i try to set responded cookie in the header and get token but response is 302 and I think cookie don't set correct in the header or something like this.

Swift working version:

https://github.com/wlcdesigns/iOS-WP-OAuth/blob/master/iOS%20WP%20OAuth/OAuthWP.swift

## Steps to Reproduce

    import 'package:http/http.dart';

    ajaxPost() async {

      String apiURL = "http://example.com/app/oauth/authorize";
      String username = 'admin';
      String password = 'pass';

      final identifier = "xxxxxxxxxxx";
      final secret = "xxxxxxxxxxx";

      var requestBody = {
        'client_id': identifier,
        "user_login": username,
        "user_password": password,
        'wpoauth_login': "1",
      };

      var headers = {
        'Accept': 'application/json',
      };

      Response r = await post(
        apiURL,
        body: requestBody,
        headers: headers
      );
      print(r.statusCode);
      print(r.body);

      var reqBody = {
        'client_id': identifier,
        'ios_wp_oauth': '1',
        'response_type': 'code',
      };

      String rawCookie = r.headers['set-cookie'];
      if (rawCookie != null) {
        int index = rawCookie.indexOf(';');
        headers['cookie'] =
            (index == -1) ? rawCookie : rawCookie.substring(0, index);
      }

      Response res = await post(
        apiURL,
        body: reqBody,
        headers: headers
      );

      print(res.statusCode);
      print(res.body);
    }

## Logs

**Comment by wendux** [comment]
In 2.x, you can implement an interceptor to manage cookie.  More details :
1. https://github.com/flutterchina/dio#cookie-manager
2. https://github.com/flutterchina/dio/blob/master/lib/src/interceptors/cookie_mgr.dart
