### ISSUE TITLE
Dio Mixin

### ISSUE THREAD

**Issue by stBogdan95** [flutterchina/dio#1232]
Error in the code dio_mixin.dart in line 816
![image](https://user-images.githubusercontent.com/86841271/127554923-54f82dde-9771-4582-8ac4-eec0be7d05a8.png)
Error in **StackTrace.current** because it is impossible to get the value. If I replace the string with **dioError.stackTrace = stackTrace ?? dioError.stackTrace ?? errorStackTrace ?? null;** then everything works

**Comment by wendux** [comment]
The relevant logic has changed in the latest version
