### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ductranit** [flutterchina/dio#1234]
I have a lot of connection timeout issue when using dio (but my device connection is normal). Then I found [this issue](https://github.com/flutterchina/dio/issues/1230) is reported but there is no response. 
And I also found that there are many issues & non merged pull requests, but the latest commit was 4 months ago.
So I wonder is this project dead?

**Comment by Rosco89** [comment]
I'm facing with the same issue. Is somebody know any alternative package? I'm using this package only for the connect timeout setting, but it's not working well.

**Comment by TshineZheng** [comment]
same here.🙁

**Comment by jgoyvaerts** [comment]
I've sent the maintainer an e-mail on his @qq.com address on his github profile. If there's no response in a few days, I'm considering forking this project to fix several issues.

**Comment by jgoyvaerts** [comment]
The fork is available at [dio_http](https://github.com/dart-tools/dio_http).

Package is available here: https://pub.dev/packages/dio_http

Issues and Pull Requests are welcome. Still looking for one or two more active contributors as well.

**Comment by kuhnroyal** [comment]
I agree with all the problems but I am not a fan of just forking and re-publishing.
Dio is a widely used library and this seems very disruptive to the whole eco-system.

It would be much better for the community if we can get @wendux to add 2-3 people as maintainers.

**Comment by jaumard** [comment]
Hum maybe @Sky24n has the right permissions to add more contributors? Might be good too if he can't contact @wendux  either. Of course, if there are no answers the only solution is to fork and republish, but better if it can be avoided.

**Comment by darwin-morocho** [comment]
> > I agree with all the problems but I am not a fan of just forking and re-publishing.
> > Dio is a widely used library and this seems very disruptive to the whole eco-system.
> > It would be much better for the community if we can get @wendux to add 2-3 people as maintainers.
> 
> I totally agree, but it's been 4 months, emails have been sent, issues and highlights have been sent, I've tried contacting both Sky and Wendux, no response from either. I'm not trying to disrupt the eco system but a forked package is better than a dead package. Trust me, I'd prefer it too if I didn't have to fork it, but yet here we are.

flutter community
https://github.com/fluttercommunity/transfer-guide

**Comment by jgoyvaerts** [comment]
> > > I agree with all the problems but I am not a fan of just forking and re-publishing.
> > > Dio is a widely used library and this seems very disruptive to the whole eco-system.
> > > It would be much better for the community if we can get @wendux to add 2-3 people as maintainers.
> > 
> > 
> > I totally agree, but it's been 4 months, emails have been sent, issues and highlights have been sent, I've tried contacting both Sky and Wendux, no response from either. I'm not trying to disrupt the eco system but a forked package is better than a dead package. Trust me, I'd prefer it too if I didn't have to fork it, but yet here we are.
> 
> flutter community
> https://github.com/fluttercommunity/transfer-guide

I don't understand the point you're trying to make. Can you explain?

If you thought "I'd prefer it too if I didn't have to fork it" meant "I don't want to maintain it", that's not what it meant. It meant that I'd prefer the scenario where wendux adds 1-2 maintainers instead of forking, but unfortunately that scenario is not possible if he's not responding.

**Comment by ductranit** [comment]
> > I agree with all the problems but I am not a fan of just forking and re-publishing.
> > Dio is a widely used library and this seems very disruptive to the whole eco-system.
> > It would be much better for the community if we can get @wendux to add 2-3 people as maintainers.
> 
> I totally agree, but it's been 4 months, emails have been sent, issues and highlights have been sent, I've tried contacting both Sky and Wendux, no response from either. I'm not trying to disrupt the eco system but a forked package is better than a dead package. Trust me, I'd prefer it too if I didn't have to fork it, but yet here we are.

I totally agree with you. There are too many problems on current project, it isn't stable now.
Unfortunately the owner isn't available to resolve these problems. So a fork would be definitely better than a dead project.

**Comment by darwin-morocho** [comment]
> > > > I agree with all the problems but I am not a fan of just forking and re-publishing.
> > > > Dio is a widely used library and this seems very disruptive to the whole eco-system.
> > > > It would be much better for the community if we can get @wendux to add 2-3 people as maintainers.
> > > 
> > > 
> > > I totally agree, but it's been 4 months, emails have been sent, issues and highlights have been sent, I've tried contacting both Sky and Wendux, no response from either. I'm not trying to disrupt the eco system but a forked package is better than a dead package. Trust me, I'd prefer it too if I didn't have to fork it, but yet here we are.
> > 
> > 
> > flutter community
> > https://github.com/fluttercommunity/transfer-guide
> 
> I don't understand the point you're trying to make. Can you explain?
> 
> If you thought "I'd prefer it too if I didn't have to fork it" meant "I don't want to maintain it", that's not what it meant. It meant that I'd prefer the scenario where wendux adds 1-2 maintainers instead of forking, but unfortunately that scenario is not possible if he's not responding.

the flutter team has killed some plugins (like device_info) and moved them to fluttercommunity i think the better option to help to maintenance DIO as a new project is store it in  fluttercommunity

**Comment by miDeb** [comment]
> the flutter team has killed some plugins (like device_info) and moved them to fluttercommunity i think the better option to help to maintenance DIO as a new project is store it in fluttercommunity

Transferring a package also requires the mantainers to actively collaborate, but we can't even get them to respond. While we all agree that transferring the package or adding more mantainers to it would be the best solution, this is not possible since the mantainers are not responsive. I'd also like to point out that the maintainers have absolutely no obligation to do so; the power of open source is precisely that forks can be created if necessary.

**Comment by 2shrestha22** [comment]
We should fork this project  for sure.

**Comment by kuhnroyal** [comment]
> @jgoyvaerts I prefer to continue maintenance in the current organization。 At that time, the name of the organization was really hasty. I didn't expect that many projects under the organization would have so many users from all over the world in the whole dart community. I think I can explain it in readme。

Keeping it here is also an option if it can be ensured that there is always someone available to manage it.

**Comment by kuhnroyal** [comment]
I think we can close this issue, a couple maintainers have been added.
