### ISSUE TITLE
Crash IOS 

### ISSUE THREAD

**Issue by fly512** [flutterchina/dio#125]
dio 1.0.13

0 #0 _File.throwIfError (dart:io/file_impl.dart:647)
--
1 #1 _File._deleteSync (dart:io/file_impl.dart:310)
2 #2 FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466)
3 #3 Dio.download.<anonymous closure> (package:dio/src/dio.dart:262)
4 #4 _rootRunUnary (dart:async/zone.dart:1132)
5 #5 _CustomZone.runUnary (dart:async/zone.dart:1029)
6 #6 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
7 #7 _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
8 #8 _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:370)
9 #9 _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272)
10 #10 _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:137)
11 #11 _addErrorWithReplacement (dart:async/stream_pipe.dart:188)
12 #12 _HandleErrorStream._handleError (dart:async/stream_pipe.dart:291)

**Comment by wendux** [comment]
保存文件的路径可能有问题，注意一定要是手机上的合法路径，要通过path_provider 获取
