### ISSUE TITLE
Can't catch error `assureDioError`

### ISSUE THREAD

**Issue by thep0y** [flutterchina/dio#1253]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | 2.2.3                             |      |
| Dio Version                    | 4.0.0                                |      |
| Android Studio / Xcode Version | Android Studio 2020.3.1            |      |
| Repro rate                     | all the time (100%)    |      |
| Repro with our demo prj        | no          |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps
*Disconnect from the network.*

```dart
  Future<Response> _get(String url) async {
    try {
      return await dio.get(url, options: Options(responseDecoder: _gbkDecoder));
    } catch (e) {
      print(e);
      return Future.error(e);
    }
  }
```

<img width="638" alt="屏幕截图 2021-08-22 163718" src="https://user-images.githubusercontent.com/51874567/130348128-70c7fb99-e614-466a-bfe6-50bccd569929.png">

**Comment by fernandomoraesvr** [comment]
+1

**Comment by Domzak** [comment]
Same here

**Comment by theowenyoung** [comment]
Same here

**Comment by a7md0** [comment]
Same here, and those issues too

 #1171 
#1306

**Comment by wendux** [comment]
try 4.0.3

**Comment by wendux** [comment]
try 4.0.3
