### ISSUE TITLE
[PLEASE READ] Due to contributor inactivity, this package has been forked as dio_http

### ISSUE THREAD

**Issue by jgoyvaerts** [flutterchina/dio#1260]
The fork is available at [dio_http](https://github.com/dart-tools/dio_http).

Package is available here: https://pub.dev/packages/dio_http

Issues and Pull Requests are welcome. Still looking for one or two more active contributors as well.

For more information about the fork, [click here](https://github.com/dart-tools/dio_http/blob/master/FORK.md)

**Comment by Rosco89** [comment]
Good news! This package really need fixes. I hope you can fix the timeout problems.

**Comment by enzodanjour** [comment]
Excelent news!
