### ISSUE TITLE
web环境下，dio返回的response.header里只有content-type

### ISSUE THREAD

**Issue by endison1986** [flutterchina/dio#1268]
### Issue Info
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter web， edge |      |
| Platform Version               | 93.x                            |      |
| Dio Version                    | 4.0.0                                  |      |
| Android Studio / Xcode Version | idea latest             |      |
| Repro rate                     | 100%  |      |
| Repro with our demo prj        | 没试            |      |
| Demo project link              |     |      |

发送post请求，返回的数据在微软edge的控制台的网络列表中可以看到响应头，有很多个，但是在代码里面，通过
rsp.headers获得的只有content-type一个，rsp.header.map.keys.length也等于1

**Comment by jgoyvaerts** [comment]
Can you post a simple code sample to reproduce this?
你能发布一个简单的代码示例来重现这个吗？

**Comment by endison1986** [comment]
这是pubspec.yaml中的依赖部分
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
```
这是完整的main.dart代码，仅仅修改了FloatingActionButton的onPressed方法，通过dio发起了get请求，并输出了header的个数和所有的key
```dart
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  Dio dio = Dio();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          dio.get("https://urswebzj.nosdn.127.net/webzj_cdn101/message.js").then((value) {
            print("length: ${value.headers.map.keys.length}");
            print("----------------------------------");
            value.headers.map.keys.forEach((element) {print(element);});
            print("----------------------------------");
            print(value.headers['Server']);
            print(value.headers['server']);
          });
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
这是输出的结果
```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 449ms.
length: 3
----------------------------------
cache-control
content-type
last-modified
----------------------------------
null
null
```
但这是界面返回的response headers
```
HTTP/1.1 200 OK
Date: Tue, 07 Sep 2021 14:57:47 GMT
Content-Type: application/javascript;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
x-nos-request-id: ff51a30d-418f-49c9-bfbe-0a66a6bd834f
x-nos-requesttype: GetObject
x-nos-object-name: webzj_cdn101%2Fmessage.js
ETag: dd4604dadec7c446abb9c6d80bc83338
x-nos-storage-class: STANDARD
Content-Disposition: inline; filename="webzj_cdn101%2Fmessage.js"
Last-Modified: Wed, 12 May 2021 16:06:09 Asia/Shanghai
Server: nos/v1.0.2
Content-Encoding: gzip
Age: 1
X-Cache: HIT from cache.51cdn.com
X-Via: 1.1 sx96:14 (Cdn Cache Server V2.0), 1.1 d205:11 (Cdn Cache Server V2.0)
X-Ws-Request-Id: 61377deb_d205_38513-24336
Access-Control-Allow-Origin: *
Cache-Control: max-age=61
cdn-ip: 223.95.211.205
```

**Comment by jgoyvaerts** [comment]
This bug only happens on Edge. It works correctly on Chrome and Windows
此错误仅发生在 Edge 上。 它在 Chrome 和 Windows 上正常工作

It's related to CORS, so maybe you can log a bug on the Edge browser. If you have control of the server, a possible workaround could be setting the header Access-Control-Expose-Headers with the value of the response headers you want readable.
它与 CORS 相关，所以也许您可以在 Edge 浏览器上记录一个错误。 如果您可以控制服务器，则可能的解决方法是将标头 Access-Control-Expose-Headers 设置为您希望可读的响应标头的值。

**Comment by endison1986** [comment]
谢谢你的回答，我确实使用了cors以帮助我在本地开发，我将会尝试修改他。
另外，我之后发的这个测试是在chrome上进行的，版本也是93.X，我无法认同您说的在chrome上是运行正常的

**Comment by jgoyvaerts** [comment]
Yes you are right, I'm sorry. I disabled cors on my chrome which affected my testing. It's also broken on chrome, but it's not a bug in Dio. Try the workaround with Access-Control-Expose-Headers

是的，你说得对，对不起。 我禁用了 chrome 上的 cors，这影响了我的测试。 它在 chrome 上也坏了，但它不是 Dio 中的错误。 尝试使用 Access-Control-Expose-Headers 的解决方法

**Comment by endison1986** [comment]
好的，我明白了，如果是CORS的原因导致的，那我知道搞如何解决了，十分感谢

**Comment by endison1986** [comment]
我尝试使用--disable-web-security关闭了chrome的cors，现在我确实可以拿到绝大部分的header，但是set-cookie仍然拿不到，
