### ISSUE TITLE
can't open downloaded file

### ISSUE THREAD

**Issue by Surk217** [flutterchina/dio#1271]
I'm trying to download a file in my flutter app using the Dio plugin.

The downloaded file appears in the download folder on my phone but I can't open it.
it doesn't have a mime type.

[how the downloaded file looks in the download folder]
 https://i.stack.imgur.com/JRhmR.png

Can anyone help?

**Comment by jgoyvaerts** [comment]
How are you downloading the file? Have you tried saving the file with an extension?

**Comment by Surk217** [comment]
@jgoyvaerts what do you mean saving with an extesion?
do you mean:
`"$fileName.$fileType"` ?

**Comment by jgoyvaerts** [comment]
Right now you are saving the file on your phone without an extension, which is probably why your phone can't open it. If it's a picture, you should save it as .jpg or .png. But if you provide some code how you are downloading the file it's easier to help you

**Comment by Surk217** [comment]
The code:

`void downloadDio(Uri uri) async {
    String path = (await DownloadsPathProvider.downloadsDirectory)!.path +
        '/test_${DateTime.now().microsecondsSinceEpoch}';
    File saveFile = File(path);
    Dio()
        .downloadUri(uri, saveFile.path)
        .whenComplete(() => print('download done'));
  }`

**Comment by Surk217** [comment]
@jgoyvaerts when I did that and tried opening the file I got a toast "cannot display pdf (invalid format)".
I tested the URL on the web and the download was successful with the correct file.

**Comment by jgoyvaerts** [comment]
Are you sure it's a pdf you're downloading? Maybe you should post this on stackoverflow.com, this isn't really a Dio issue
