### ISSUE TITLE
After update to flutter 2.5 Invalid internet address

### ISSUE THREAD

**Issue by fahdboudakim** [flutterchina/dio#1275]
Hi, after upgrading flutter to 2.5 i get error of Invalid internet address

**Comment by omateuscastro** [comment]
+1

**Comment by jgoyvaerts** [comment]
Can you provide some sample code that triggers this error? What platform are you running on? iOS/Android/Web/Windows?

**Comment by fahdboudakim** [comment]
i test it in iOS, android, the same problem. i need to reinstall the 2.5.0 version to reproduce the problem because now i return to the 2.2.3 version because the software is in production mode

**Comment by aarjan** [comment]
I am also getting this error while calling all the api endpoints, though they have valid certificates.
But astonishingly they work, even though they throw errors. 


![Screen Shot 2021-09-25 at 7 24 27 PM](https://user-images.githubusercontent.com/12951263/134773550-b9653825-3386-4782-b083-b8ce61d6856d.png)

**Comment by kimvdmeulen** [comment]
+1

**Comment by jgoyvaerts** [comment]
This is not a dio issue but a dart issue. More information here: https://github.com/flutter/flutter/issues/83792
