### ISSUE TITLE
使用onHttpClientCreate创建Proxy时Hot Reload失效

### ISSUE THREAD

**Issue by AbelZhou** [flutterchina/dio#128]
如题
创建proxy后，再次修改proxy地址  Hot Reload不生效
目前是否不支持这部分的hot reload
需要重新运行才可以生效

**Comment by wendux** [comment]
你是不是使用了全局单例dio？

**Comment by AbelZhou** [comment]
是的

**Comment by wendux** [comment]
你初始化全局单例时，初始化代码只执行了一次。hotReload只会从根widget重新build, 所以你改了dio配置后及时hotReload, 初始化代码也不会再执行。一种方法是将dio的配置代码再拷贝一份到一个相对靠近根的Widget的 ` reassemble() `回调中。
