### ISSUE TITLE
Error on avoid certificate errors

### ISSUE THREAD

**Issue by tuskinhu** [flutterchina/dio#1285]
- Using with platform: WEB
- dio: ^4.0.0
- Flutter: 2.5

Same request with non signed certificate that in windows, ios, android returns ok, mac not tested, with web project get this error:

Error: Expected a value of type 'DefaultHttpClientAdapter', but got one of type 'BrowserHttpClientAdapter'

This is the code used to avoid certificate error, as I said, work for Androis, iOS and Windows (not tested for Mac):

      (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
          (HttpClient client) {
        client.badCertificateCallback = (X509Certificate cert, String host, int port) => true;
        return client;
      };

**Comment by winfredwong** [comment]
I am facing the exact same issue on Flutter web.
1. Using with platform: WEB
2. dio: ^4.0.0
3. Flutter: 2.5

`Error: Expected a value of type 'DefaultHttpClientAdapter', but got one of type 'BrowserHttpClientAdapter'`

This error shows up in the browser console.
The step to reproduce is simple. Create a flutter web project and post to https endpoint that is self signed. Then the error pops up.

**Comment by jgoyvaerts** [comment]
See https://github.com/dart-tools/dio_http/issues/9
