### ISSUE TITLE
DioError [DioErrorType.response]: Http status error [401]

### ISSUE THREAD

**Issue by niteesh1215** [flutterchina/dio#1290]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / android               |      |
| Platform Version               | 2.14.0  / 9                          |      |
| Dio Version                    | 4.0.0                                |      |
| Android Studio  |  Android Studio 4.1.1         |      |
| Repro rate                     |  all the time (100%)    |      |

```final dio = Dio();
    try {
      await dio.request(
        'https://api.example.com/api/v1/auth/validateMobile',
        data: {"phoneNo": "+91999999999"},
        options: Options(
          method: 'GET',
          headers: {
            HttpHeaders.authorizationHeader:
                'Bearer $token',
            'content-Type': 'application/json'
          },
        ),
      );
    } on DioError catch (e) {
      print(e);
    }
```

```I/flutter (16336): DioError [DioErrorType.response]: Http status error [401]
I/flutter (16336): #0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
I/flutter (16336): #1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
I/flutter (16336): <asynchronous suspension>
I/flutter (16336): #2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
I/flutter (16336): <asynchronous suspension>
```

I'm getting 401 error even though I'm passing authorization header with correct token. Thank you for your help.

If I make a request to the same api endpoint with the same authorization header using the flutter http package, it works.

**Comment by jgoyvaerts** [comment]
Can you paste actual working code you are using for both the dio case and the http case? You can leave out the token obviously

**Comment by a7md0** [comment]
Same issue as #1171

I'm facing this too ...

**Comment by wendux** [comment]
try 4.0.3
