### ISSUE TITLE
手机网络跟WiFi能否同时使用？

### ISSUE THREAD

**Issue by zKidor** [flutterchina/dio#1293]
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter  android                          |      |
| Platform Version               | flutter  2.5.2  android 10.0                              |      |
| Dio Version                    | 4.0.0                                  |      |
| Repro rate                     |  all the time (100%)    |      |
| Repro with our demo prj        | it happen with the demo project            |      |

### Issue Description and Steps

使用场景：
WiFi连接的是内网（与互联网不通），另外还有一个手机网络4G

1.当只连接手机网络时，发送请求可以成功返回

2.当连接WiFi且手机网络也启用时，这时使用手机浏览器是可以正常打开网页。使用demo APP发送请求失败，日志如下
I/flutter (11911): DioError [DioErrorType.other]: SocketException: Failed host lookup: 'httpbin.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (11911): #0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:818:20)
I/flutter (11911): #1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
I/flutter (11911): <asynchronous suspension>
I/flutter (11911): #2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
I/flutter (11911): <asynchronous suspension>

请问，dio是否有相关的设置同时使用WiFi和手机网络，以上问题是否有解决方法，谢谢！

**Comment by wendux** [comment]
httpbin.org 国内访问需要梯子

**Comment by zhangyibo007** [comment]
怎么解决的呢？
