### ISSUE TITLE
how to catch "assureDioError"

### ISSUE THREAD

**Issue by guqun** [flutterchina/dio#1300]
### New Issue Checklist

how to catch "assureDioError", i can not cath the assureDioError.

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | android                          |      |
| Platform Version               | 11.0                              |      |
| Dio Version                    | 4.0.0                           |      |

**Comment by wendux** [comment]
Please provide reproducible steps
