### ISSUE TITLE
Get returns different response from flutter but when i call it from chrome on mobile it works..

### ISSUE THREAD

**Issue by habilgur** [flutterchina/dio#1307]
Hello,
The Api calls I used for a page that I reached with a simple code like the following were working without any problems before. But right now it is not working properly.

var response = await http.get(url);

There is no recaphta-like barrier on the web page I am trying to reach.

After the GET call I made to this page from the mobile application, something goes wrong in the response and the answer below is returned.

However, when I make the same GET call from Chrome on the phone, the response is as it should be.

Where could the problem be? Have you had a problem like this before?

"
<html>
<body>

</APM_DO_NOT_TOUCH>
 

<br class="Apple-interchange-newline">
</body>
</html>
<!DOCTYPE html>
<html><head>
<meta http-equiv="Pragma" content="no-cache"/>
<meta http-equiv="Expires" content="-1"/>
<meta http-equiv="CacheControl" content="no-cache"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="shortcut icon" href="data:;base64,iVBORw0KGgo="/>

<script type="text/javascript">
(function(){
window["bobcmn"] = "101110101010102000000062000000052000000062000000012e78d6aab200000096200000000200000002300000000300000000300000006/TSPD/300000008TSPD_10130000000cTSPD_101_DID300000005https3000000b0083d721e09ab200091f9b46fbd1d0c6a38db647f08db7c8a2cd56f1d60acff47c6a3279b7cbd2daa08f7a5e4900a2800b2da57a3e45b536260d2d5bf2a205e4ceda746550a6b1ab0d9f9603ce94b29a9258a488cfa21857e300000002TS200000000200000000";

window["failureConfig"] = "524f6f70732e2e2e2e736f6d657468696e672077656e742077726f6e672e2e2e2e20796f757220737570706f72742069642069733a2025444f534c372e6368616c6c656e67652e737570706f72745f6964252e142020383534343236363534393634383132313638062f545350442f171800";window.teIH=!!window.teIH;try{(function(){(function(){var J=-1,J={II:++J,oS:"false"[J],I:++J,SL:"false"[J],SI:++J,OLI:"[object Object]"[J],OO:(J[J]+"")[J],iL:++J,oO:"true"[J],LI:++J,iI:++J,OS:"[object Object]"[J],S:++J,Oj:++J,_lj:++J,Slj:++J};try{J.sL=(J.sL=J+"")[J.iI]+(J.Sl=J.sL[J.I])+(J.LS=(J.sl+"")[J.I])+(!J+"")[J.iL]+(J._l=J.sL[J.S])+(J.sl="true"[J.I])+(J.ZO="true"[J.SI])+J.sL[J.iI]+J._l+J.Sl+J.sl,J.LS=J.sl+"true"[J.iL]+J._l+J.ZO+J.sl+J.LS,J.sl=J.II[J.sL][J.sL],J.sl(J.sl(J.LS+'"\\'+J.I+J.iI+J.I+J.oS+"\\"+J.LI+J.II+"("+J._l+"\\"+J.I+J.Oj+
J.I+"\\"+J.I+J.S+J.II+J.oO+J.Sl+J.oS+"\\"+J.LI+J.II+"\\"+J.I+J.S+J.Oj+"\\"+J.I+J.iI+J.I+"\\"+J.I+J.iI+J.S+J.OO+J.Sl+"\\"+J.I+J.S+J.Oj+"['\\"+J.I+J.S+J.II+J.SL+"\\"+J.I+J.Oj+J.I+"false"[J.SI]+J.Sl+J.SL+J.OO+"']\\"+J.LI+J.II+"===\\"+J.LI+J.II+"'\\"+J.I+J.S+J.iL+J._l+"\\"+J.I+J.S+J.SI+"\\"+J.I+J.iI+J.I+"\\"+J.I+J.iI+J.S+"\\"+J.I+J.LI+J.Oj+"')\\"+J.LI+J.II+"{\\"+J.I+J.SI+"\\"+J.I+J.I+"\\"+J.I+J.S+J.S+J.SL+"\\"+J.I+J.S+J.SI+"\\"+J.LI+J.II+J.oO+J.OO+"\\"+J.I+J.S+J.S+J.OS+"\\"+J.I+J.Oj+J.I+J.ZO+"\\"+J.I+
J.iI+J.SI+"\\"+J.I+J.iI+J.iL+"\\"+J.I+J.S+J.II+"\\"+J.LI+J.II+"=\\"+J.LI+J.II+"\\"+J.I+J.S+J.Oj+"\\"+J.I+J.iI+J.I+"\\"+J.I+J.iI+J.S+J.OO+J.Sl+"\\"+J.I+J.S+J.Oj+"['\\"+J.I+J.S+J.II+J.SL+"\\"+J.I+J.Oj+J.I+"false"[J.SI]+J.Sl+J.SL+J.OO+"'].\\"+J.I+J.S+J.SI+J.oO+"\\"+J.I+J.S+J.II+"false"[J.SI]+J.SL+J.OS+J.oO+"(/.{"+J.I+","+J.LI+"}/\\"+J.I+J.LI+J.Oj+",\\"+J.LI+J.II+J.oS+J.ZO+"\\"+J.I+J.iI+J.S+J.OS+J._l+"\\"+J.I+J.iI+J.I+J.Sl+"\\"+J.I+J.iI+J.S+"\\"+J.LI+J.II+"(\\"+J.I+J.Oj+J.II+")\\"+J.LI+J.II+"{\\"+J.I+
J.SI+"\\"+J.I+J.I+"\\"+J.I+J.I+"\\"+J.I+J.I+"\\"+J.I+J.S+J.SI+J.oO+J._l+J.ZO+"\\"+J.I+J.S+J.SI+"\\"+J.I+J.iI+J.S+"\\"+J.LI+J.II+"(\\"+J.I+J.Oj+J.II+"\\"+J.LI+J.II+"+\\"+J.LI+J.II+"\\"+J.I+J.Oj+J.II+").\\"+J.I+J.S+J.iL+J.ZO+J.OLI+"\\"+J.I+J.S+J.iL+J._l+"\\"+J.I+J.S+J.SI+"("+J.SI+",\\"+J.LI+J.II+J.LI+")\\"+J.I+J.SI+"\\"+J.I+J.I+"\\"+J.I+J.I+"});\\"+J.I+J.SI+"}\\"+J.I+J.SI+'"')())()}catch(L){J%=5}})();var LJ=59;
try{var oJ,ZJ,SJ=l(987)?0:1,IJ=l(876)?0:1,jJ=l(116)?1:0,ol=l(844)?0:1,Ol=l(556)?0:1,Sl=l(963)?0:1,il=l(576)?0:1,Il=l(844)?0:1,jl=l(374)?1:0;for(var LL=(l(106),0);LL<ZJ;++LL)SJ+=(l(434),2),IJ+=l(379)?2:1,jJ+=l(53)?2:1,ol+=(l(592),2),Ol+=(l(80),2),Sl+=l(605)?1:2,il+=l(512)?1:2,Il+=l(307)?2:1,jl+=l(692)?2:3;oJ=SJ+IJ+jJ+ol+Ol+Sl+il+Il+jl;window.zO===oJ&&(window.zO=++oJ)}catch(OL){window.zO=oJ}var zL=!0;
function ZL(J){var L=67;!J||document[O(L,185,172,182,172,165,172,175,172,183,188,150,183,164,183,168)]&&document[O(L,185,172,182,172,165,172,175,172,183,188,150,183,164,183,168)]!==Z(68616527599,L)||(zL=!1);return zL}function s(J){var L=arguments.length,z=[];for(var S=1;S<L;++S)z.push(arguments[S]-J);return String.fromCharCode.apply(String,z)}function O(J){var L=arguments.length,z=[],S=1;while(S<L)z[S-1]=arguments[S++]-J;return String.fromCharCode.apply(String,z)}function sL(){}
ZL(window[sL[Z(1086795,LJ)]]===sL);ZL(typeof ie9rgb4!==Z(1242178186140,LJ));ZL(RegExp("\x3c")[Z(1372146,LJ)](function(){return"\x3c"})&!RegExp(Z(42830,LJ))[Z(1372146,LJ)](function(){return"'x3'+'d';"}));
var SL=window[O(LJ,156,175,175,156,158,163,128,177,160,169,175)]||RegExp(O(LJ,168,170,157,164,183,156,169,159,173,170,164,159),Z(-41,LJ))[O(LJ,175,160,174,175)](window["\x6e\x61vi\x67a\x74\x6f\x72"]["\x75\x73e\x72A\x67\x65\x6et"]),iL=+new Date+(l(520)?469313:6E5),jL,Jo,Lo,oo=window[O(LJ,174,160,175,143,164,168,160,170,176,175)],Oo=SL?l(149)?3E4:31470:l(31)?6E3:6374;
document[O(LJ,156,159,159,128,177,160,169,175,135,164,174,175,160,169,160,173)]&&document[O(LJ,156,159,159,128,177,160,169,175,135,164,174,175,160,169,160,173)](O(LJ,177,164,174,164,157,164,167,164,175,180,158,163,156,169,162,160),function(J){var L=13;document[s(L,131,118,128,118,111,118,121,118,129,134,96,129,110,129,114)]&&(document[O(L,131,118,128,118,111,118,121,118,129,134,96,129,110,129,114)]===Z(1058781970,L)&&J[O(L,118,128,97,127,130,128,129,114,113)]?Lo=!0:document[O(L,131,118,128,118,111,
118,121,118,129,134,96,129,110,129,114)]===Z(68616527653,L)&&(jL=+new Date,Lo=!1,so()))});function so(){if(!document[O(5,118,122,106,119,126,88,106,113,106,104,121,116,119)])return!0;var J=+new Date;if(J>iL&&(l(494)?640780:6E5)>J-jL)return ZL(!1);var L=ZL(Jo&&!Lo&&jL+Oo<J);jL=J;Jo||(Jo=!0,oo(function(){Jo=!1},l(736)?0:1));return L}so();var So=[l(175)?17795081:12519592,l(901)?2147483647:27611931586,l(749)?1491408616:1558153217];function Z(J,L){J+=L;return J.toString(36)}
function io(J){var L=14;J=typeof J===Z(1743045662,L)?J:J[s(L,130,125,97,130,128,119,124,117)](l(762)?46:36);var z=window[J];if(!z||!z[O(L,130,125,97,130,128,119,124,117)])return;var S=""+z;window[J]=function(J,L){Jo=!1;return z(J,L)};window[J][s(L,130,125,97,130,128,119,124,117)]=function(){return S}}for(var jl=(l(305),0);jl<So[s(LJ,167,160,169,162,175,163)];++jl)io(So[jl]);ZL(!1!==window[s(LJ,175,160,132,131)]);window.zo=window.zo||{};window.zo.J_="0804fa1acb020001c328cd8bff436888ff63bc23626d7383ebb78c77db54748112e491a089208d5a88fd469e12f5daa58044965949da2b82f649c3eff9c40501777f90d9d94bb8888563e866a8f6b8eb31a1741e4ad2c2711f3b8838361c8a2c2a9ff7a9cf7a7a59a9abec29aedb526089a5ae95e9abd043a32f5cf9f33f1e8831b7d8349f84008676a7aa47125a036301a171af77616689e408d5575359488928759767ad50f5e12f72e9ac83e37285ec0e8dc397cc32afdf250efa6b9a318749723a41f374bd6d2fd338be9c1c0dadb3b45733670a6de9f85faaa9448dc802c88916c78a7cce87cf3cbab5ed8ecafa9d96ace4a6360ba8a5f85e4a7fca47dbfc78573f05106575";
function jo(J){var L=+new Date,z;!document[O(6,119,123,107,120,127,89,107,114,107,105,122,117,120,71,114,114)]||L>iL&&(l(653)?415853:6E5)>L-jL?z=ZL(!1):(z=ZL(Jo&&!Lo&&jL+Oo<L),jL=L,Jo||(Jo=!0,oo(function(){Jo=!1},l(505)?0:1)));return!(arguments[J]^z)}function l(J){return 469>J}(function(J){J||setTimeout(function(){var J=setTimeout(function(){},250);for(var z=0;z<=J;++z)clearTimeout(z)},500)})(!0);})();}catch(x){}finally{ie9rgb4=void(0);};function ie9rgb4(a,b){return a>>b>>0};

})();

</script>

<script type="text/javascript" src="/TSPD/083d721e09ab20001f94c596437f3aa06cc7f0132d9f55115e6e45509235ae6c9396d8021fe8060b?type=5"></script>
<noscript>Please enable JavaScript to view the page content.<br/>Your support ID is:   854426654964812168.</noscript>
</head><body>
This question is for testing whether you are a human visitor and to prevent automated spam submission.
<br>
<br>
<b>What code is in the image?</b>
<input type = "text" id="ans" name = "answer" value = "" />

<br>
<button id="jar" type="button">submit</button>

<br>
"

**Comment by jgoyvaerts** [comment]
As you can see in the response, the server is checking if javascript is enabled. When you request a page through dio, only the html is downloaded, and javascript functions don't run. 

This is not a dio bug.
