### ISSUE TITLE
各位大佬，什么场景下同一个时间戳会请求服务器多次，是dio的问题吗

### ISSUE THREAD

**Issue by mdddj** [flutterchina/dio#1314]
服务器获取到的请求是同一个时间戳，导致业务错乱，
同事说在网络不好的情况下会出现

**Comment by CyJaySong** [comment]
请求重试

**Comment by mdddj** [comment]
> 请求重试


有办法解决吗，准备换http了

**Comment by CyJaySong** [comment]
如果不请求重试的话，弱网环境，你会收到一大堆的连接超时，用户体验极差

**Comment by mdddj** [comment]
> 如果不请求重试的话，弱网环境，你会收到一大堆的连接超时，用户体验极差

但是如果请求重试的话，我们的服务后端会连续处理两次以上或者多此的请求，导致业务和数据错乱，大佬请问这个问题在后端（PHP）能解决吗

**Comment by CyJaySong** [comment]
如果你要交给后端解决的话，每次请求带上一个 uuid, 加锁

**Comment by mdddj** [comment]
> 如果你要交给后端解决的话，每次请求带上一个 uuid, 加锁

多谢大佬的解答，最后问一下在dio层有暴露属性或者其他方法来取消这个弱网重试的机制吗

**Comment by CyJaySong** [comment]
这个我没注意，这请求重试应该是最近更新的版本加上去的。你换成上一个版本看看

**Comment by mdddj** [comment]
找了一圈没有相关介绍

**Comment by wendux** [comment]
dio并没有默认的请求重试逻辑，你可以在本地抓包来debug
