### ISSUE TITLE
Several issues from Dio Request

### ISSUE THREAD

**Issue by flutterdev9715** [flutterchina/dio#1319]
1.` DioError [DioErrorType.other]: SocketException: Failed host lookup: 'markaa.com' (OS Error: nodename nor servname provided, or not known, errno = 8)#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:821)#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)<asynchronous suspension>#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)<asynchronous suspension>`

2. `DioError [DioErrorType.other]: HttpException: Connection closed before full header was received, uri = https://markaa.com/customapi/api/getMyCartItems#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)<asynchronous suspension>#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)<asynchronous suspension>`

3. `DioError [DioErrorType.response]: Http status error [500]#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)<asynchronous suspension>#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)<asynchronous suspension>`

4. `DioError [DioErrorType.other]: HandshakeException: Handshake error in client (OS Error: 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:359))#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:821)#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)<asynchronous suspension>#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)<asynchronous suspension>`

Those are all errors for our some users when send the request with dio.

Any helps?

**Comment by jgoyvaerts** [comment]
Please don't open one issue for several random exceptions which you receive, without investigating if these are even caused by the package itself. We are not a flutter helpdesk.

For example, Error nr 1 and 4 indicate OS error, which means the error happens on the operating system level and not on the dio level. You can google these further to find out what they mean.

A HTTP status error 500 means the server threw an error while sending a request, so you should look into your server logs why it's throwing an error.

**Comment by flutterdev9715** [comment]
Okay, thanks

**Comment by zengbo88** [comment]
@jgoyvaerts [jgoyvaerts](https://github.com/jgoyvaerts) Hello, can you solve the issue #1192 . I encouter the same error for https.
