### ISSUE TITLE
关于代理抓包问题

### ISSUE THREAD

**Issue by coolxtc** [flutterchina/dio#132]
我是这样设置代理的：
    dio = new Dio(options);
    dio.onHttpClientCreate = (HttpClient client) {
      client.findProxy = (uri) {
        return "proxy localhost:8888";
      };
    };
但是pc端的charles还是抓不到包，报的异常是HttpException: Invalid proxy configuration proxy localhost:8888。
改成pc的ip（proxy 10.7.10.28:8888）后则可以抓包。
请问下如果不改成目标pc的ip，我该怎么做才能抓到包呢？

**Comment by Herb-Sun** [comment]
You should use this:
```
dio.onHttpClientCreate = (HttpClient client) {
   client.findProxy = (uri) {
      return 'PROXY localhost:8888';
    };
 };
```

**Comment by wendux** [comment]
必须得指明抓包工具运行设备的ip, 手机的localhost代表的手机地址，当然不行

**Comment by Huyamin150** [comment]
同上，这个问题怎么解决，合作开发IP地址不能写死

**Comment by wendux** [comment]
@Huyamin150 做一个调试页面 ，可以动态输ip地址

**Comment by fantasy525** [comment]
> @Huyamin150 做一个调试页面 ，可以动态输ip地址

没有办法可以设置默认走代理吗？

**Comment by fantasy525** [comment]
@wendux 有办法默认有代理就从代理走吗？我看其他线上app默认都是走代理的啊？为什么dio需要制定某个ip呢？

**Comment by gaoyangcr7** [comment]
从NA端获取手机代理
