### ISSUE TITLE
Allow payload for GET request too. (The same as POST, PUT, and other requests)

### ISSUE THREAD

**Issue by realshovanshah** [flutterchina/dio#1321]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found #252 , but it was closed.
- [ ] Make necessary changes for supporting request body in GET request.

As of version 4.0.3, there's no support for adding request body to GET requests. 

This was previously discussed in #252 and I this has been solved yet. This should be an open issue, so I'm reopening this.

I'm in need of for a project. I'll try to send a pull request if I'm free. 
Do let us know if anyone is interested in helping close this issue.

**Comment by wendux** [comment]
Oh... it is **not** a normal operation to carry a body in a GET request, and the browsers do not support it too...

**Comment by realshovanshah** [comment]
Yes, but there's nothing stopping a backend from adding request body to a GET request. Though browsers don't support it, I'd like to argue that many other client libraries do support this, and it's for a reason. 

After further research I found this- Even Elasticsearch makes use the above mentioned feature.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html

**Comment by wendux** [comment]
OK..Let's discuss it together，I want to hear your thoughts！
