### ISSUE TITLE
 DOWNLOAD FILE : DioError [DioErrorType.DEFAULT]: FormatException: Scheme not starting with alphabetic character (at character 1) 

### ISSUE THREAD

**Issue by SCTech100** [flutterchina/dio#1325]
Error when downloading file ​​​url
https://kiss.kanaan.sch.id/document/test/2a6fa1a0-ff69-11eb-99c4-ff29b4005dba.jpg

android 10
![WhatsApp Image 2021-11-23 at 09 41 44](https://user-images.githubusercontent.com/65840043/142968852-7df30cde-b2aa-4e7a-b7e5-98985f5ce0b0.jpeg)

how to solve problem?

**Comment by SCTech100** [comment]
using dio version ^3.0.10  and ^4.0.0

**Comment by jgoyvaerts** [comment]
This is not a Dio bug. Use google to google the error message "scheme not starting with alphabetic character" and try some of the proposed fixes.
