### ISSUE TITLE
不明原因，自动在提交的参数加上了\r\n

### ISSUE THREAD

**Issue by 85636682** [flutterchina/dio#133]
### ```是不是为了上传文件，是数组都加上了\r\n？```
![144381547177714_ pic](https://user-images.githubusercontent.com/1079461/51017033-80722300-15ad-11e9-88f8-7b2b108699e2.jpg)

**Comment by wendux** [comment]
请贴一下你的代码

**Comment by wendux** [comment]
已修复，请用最新版重试
