### ISSUE TITLE
dio.post请求，服务器返回给它status 是204 怎么还抛出如下错误？

### ISSUE THREAD

**Issue by goodforever** [flutterchina/dio#134]
dio.post请求，服务器返回给它status 是204 怎么还抛出如下错误？
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (23347): DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Valid value range is empty: 0#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:237:55)

**Comment by wendux** [comment]
请提供一下响应header和body

**Comment by wendux** [comment]
请用最新版重试，如有问题再打开，先关闭了
