### ISSUE TITLE
in flutter web I get 'XMLHttpRequest'

### ISSUE THREAD

**Issue by ali-1989** [flutterchina/dio#1340]
I wrote this:

```
Dio dio = Dio();

dio.options.baseUrl = 'http://localhost:6060';
dio.options.method = 'POST';
dio.options.responseType = ResponseType.plain;
    
var res = await dio.request('/login');
```

but got 'XMLHttpRequest' error in web.   on Device is ok.

I add headers in server but not solved.
res.headers.add('Access-Control-Allow-Origin', '*');
res.headers.add('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE, HEAD');

by 'Http package' is ok but, by Dio I have error.

I also send the request by post method, but it is received on the server as a options method! Why?

**Comment by GoogleJ** [comment]
I have met this error sevel times

1.This error is caused by CORS, **add server support will solve this error.**

2."I also send the request by post method, but it is received on the server as a options method! Why?"  The OPTIONS request is send by browser,not app client.

3.This hack solution will only work locally.

**Comment by JensHor** [comment]
I see the same problem in which `Dio` sends an `OPTIONS` request as well as a the intended `POST` request. 

This problem only occurs on `Web` not on `MacOS`. Any idea on how to work around this (except the proposed local solution?)

**Comment by jgoyvaerts** [comment]
You need to modify the server to allow CORS requests. Please read up on how CORS works.

**Comment by sunil91** [comment]
please follow these step it's works for me on mac m2

1- Go to flutter\bin\cache and remove a file named: flutter_tools.stamp

2- Go to flutter\packages\flutter_tools\lib\src\web and open the file chrome.dart.

3- Find '--disable-extensions'

4- Add '--disable-web-security'

**Comment by ali-1989** [comment]
Must set **CORS** for Options method request in server. 


sample:
```
server.options('/*', (req, res) async {
        res.headers.add('Access-Control-Allow-Origin', '*');
        res.headers.add('Access-Control-Allow-Headers', '*');
        res.headers.add('Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, OPTIONS, HEAD');

        res.statusCode = 204;
      }
    );
```
