### ISSUE TITLE
FormatException: Filter error, bad data

### ISSUE THREAD

**Issue by Aobanana-chan** [flutterchina/dio#1352]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter / ios / android                          |      |
| Platform Version               | flutter 2.5.2                             |      |
| Dio Version                    | 4.0.4                                |      |
| Repro rate                     | 20%   |      |
### Issue Description and Steps
产生原因不明，但经常会发生这样的异常（对于某一个URL会报错，其他URL正常）。
产生错误代码    
```
var res = await dio.post(GET_FORUM_PAGE,
        data: args,
        options: Options(
            responseType: ResponseType.bytes,
            headers: {"Content-Type": "application/x-www-form-urlencoded"}));
```
GET_FORUM_PAGE是const String类型，值是一个URL
```
DioError (DioError [DioErrorType.other]: FormatException: Filter error, bad data
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473:35)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:468:12)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:91:12)
```

跟踪调试，异常发生在
dio_mixin.dart:668
```
        ret.data =
            (await transformer.transformResponse(reqOpt, responseBody)) as T?;
```
调用的
transformer.dart:135
`await completer.future;`
![screenshot](https://user-images.githubusercontent.com/25476118/146728755-af18c0fd-afca-4e4b-bd6d-cef17944ea38.jpg)

**Comment by kuhnroyal** [comment]
Could be related to parsing the URL of `GET_FORUM_PAGE`, or the body.
Probably the data, is it a map? We need a reproducible sample.

Btw, you can use `contentType: ContentType.parse('application/x-www-form-urlencoded')`.

**Comment by Aobanana-chan** [comment]
> 

Yes,Exception thrown when parsing the body(Json String).
Actually,My code was 
```
var res = await dio.post(GET_FORUM_PAGE,
        data: args,
        options: Options(
            headers: {"Content-Type": "application/x-www-form-urlencoded"}));
```
After Exception thrown,I change ResponseType to ResponseType.bytes.
I checked chunks.
Chunks[5] is bad data (wrong sequence) that diffrent from Fiddler received.
I tried to use AutoResponeder(Fiddler's Function which can return previously generated responses instead of using the network) to reappearance the Exception.
But sometimes dio worked well,sometime dio threw Exception(Connection closed when receiving data) or FormatException: Filter error, bad data or other Exception.(same body)
There isn't a method to 100% occurrs FormatException: Filter error, bad data.

**Comment by kuhnroyal** [comment]
So the error happens on the response not the request?

**Comment by Aobanana-chan** [comment]
> 

Yes,error happens on the response.

**Comment by kuhnroyal** [comment]
Not sure how to proceed here. I assume this may just be corrupted data from the server.

**Comment by Aobanana-chan** [comment]
Fiddler proved to the data from the server is not corrupted. So I guess the problem is from Fiddler. However, error still exists after I replace Fiddler to LightProxy.

**Comment by kuhnroyal** [comment]
I doubt we can act on this unless you find a clean way to reproduce it.
Feel free to reopen the ticket with more information.
