### ISSUE TITLE
Dio adds extra braces and :  in to the request body json

### ISSUE THREAD

**Issue by Write4Dinesh** [flutterchina/dio#1353]
Hi,
Dio adds extra braces and :  in to the request body json.

 {"{\"notification\":{\"enabled\":true,\"fix\":true,\"trap\":true,\"all\":true,\"break\":true,\"maintenance\":true,\"summary\":false,\"eventNotifications\":true}}":""}

at the end :""}   is getting added by itself. the strange part is that when i print the  request body json before calling Dio, it looks fine without any additional text as shown above.
once the request passes through Dio, the extra text gets added.
Pls hlep.

**Comment by abdullahalamodi** [comment]
Dio directly convert your data to json you don't need to encode it **manually**

**Comment by DevDin** [comment]
I was putting my json body(String)  between braces(map) as below
await _dio?.request(request.apiName,
          data: **{body}**, options: requestOptions);

so, I resolved it by removing the braces. i.e data : body without braces

**Comment by DevDin** [comment]
Pls close the issue
