### ISSUE TITLE
Allow content compression with gzip

### ISSUE THREAD

**Issue by fvisticot** [flutterchina/dio#137]
Is it possible to compress POST request with gzip ?

**Comment by wendux** [comment]
Not yet!

**Comment by fvisticot** [comment]
Any news regarding this feature ?
It would be very interesting for every mobile developer to improve application speed !

**Comment by fzyzcjy** [comment]
Any news after 2 years? Thanks! @wendux

**Comment by omidraha** [comment]
Is it possible now?
How about receiving `json` response data as `gzip`?  
#307

**Comment by kmtong** [comment]
It can be simply implemented as requestEncoder:

```dart
    var dio = Dio(BaseOptions(
      requestEncoder: gzipEncoder,
    ));
```

`gzipEncoder` is a function for content encoding.

```dart
// gzip request
List<int> gzipEncoder(String request, RequestOptions options) {
  options.headers.putIfAbsent("Content-Encoding", () => "gzip");
  return gzip.encode(utf8.encode(request));
}
```

**Comment by hurelhuyag** [comment]
I tried this solution. But this throws FormatException. bad data.

This is the code I tried.
```
final baseOptions = BaseOptions(
      headers: {
        'accept-encoding': 'gzip',
        'content-encoding': 'gzip',
      },
      requestEncoder: (request, options) {
        final encoding = options.headers["content-encoding"];
        switch (encoding) {
          case null:
            return utf8.encode(request);
          case "gzip":
            return gzip.encode(utf8.encode(request));
          default:
            throw Exception("Unsupported encoding /$encoding/ used in request body");
        }
      },
      responseDecoder: (responseBytes, options, responseBody) {
        final encoding = options.headers["content-encoding"];
        switch (encoding) {
          case null:
            return utf8.decode(responseBytes);
          case "gzip":
            return utf8.decode(gzip.decode(responseBytes));
          default:
            throw Exception("unsupported encoding /$encoding/ used in response body");
        }
      },
    );
    final dio = Dio(baseOptions);
```

**Comment by Sangamesh-AT** [comment]
Mine maybe a big longer... But, this works for me:

`@lazySingleton
Dio dio(@Named('BaseUrl') String url) {
  final gZipCodec = GZipCodec();
  final dio = Dio(
    BaseOptions(
      baseUrl: url,
      contentType: Headers.jsonContentType,
      connectTimeout: const Duration(seconds: 120),
      receiveTimeout: const Duration(seconds: 120),
      sendTimeout: const Duration(seconds: 120),
    ),
  );

  dio.interceptors.add(InterceptorsWrapper(
    onRequest: (options, handler) {
      final jsonData = jsonEncode(options.data);
      final compressedData = gZipCodec.encode(utf8.encode(jsonData));
      options.data = compressedData;
      options.headers['Content-Encoding'] = 'gzip';
      options.headers['Accept-Encoding'] = 'gzip';
      options.headers['Content-Type'] = 'application/json';
      return handler.next(options);
    },
    onResponse: (response, handler) {
      return handler.next(response);
    },
  ));

  return dio;
}`

Hope it helps!

**Comment by Sangamesh-AT** [comment]
This worked for me! And I'm guessing that Dio automatically handles the decompression when the response is received in gzip format!

```
@lazySingleton
Dio dio(@Named('BaseUrl') String url) {
  final gZipCodec = GZipCodec();
  final dio = Dio(
    BaseOptions(
      baseUrl: url,
      contentType: Headers.jsonContentType,
      connectTimeout: const Duration(seconds: 120),
      receiveTimeout: const Duration(seconds: 120),
      sendTimeout: const Duration(seconds: 120),
    ),
  );

  dio.interceptors.add(InterceptorsWrapper(
    onRequest: (options, handler) {
      final jsonData = jsonEncode(options.data);
      final compressedData = gZipCodec.encode(utf8.encode(jsonData));
      options.data = compressedData;
      options.headers['Content-Encoding'] = 'gzip';
      options.headers['Accept-Encoding'] = 'gzip';
      options.headers['Content-Type'] = 'application/json';
      return handler.next(options);
    },
    onResponse: (response, handler) {
      return handler.next(response);
    },
  ));

  return dio;
}
```

**Comment by nafiskabbo** [comment]
Still I am getting the error. Any other way?

**Comment by bombicod** [comment]
Dio has no effect whatsoever. HttpClient already enables compression by default. https://api.flutter.dev/flutter/dart-io/HttpClient-class.html This means that it is also included in the dio.
