### ISSUE TITLE
Various timeout parameter should be durations instead of int

### ISSUE THREAD

**Issue by ueman** [flutterchina/dio#1375]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps

Currently Dio uses `int`s to represent milliseconds through out the code. Ideally this should be replaced by `Duration`s to make it easier to read and safer to work with.

**Comment by kuhnroyal** [comment]
Sounds good, we should probably plan a 5.0 release where we can break this.

**Comment by ueman** [comment]
> Sounds good, we should probably plan a 5.0 release where we can break this.

Is there a discussion/board for a 5.0 release?

**Comment by kuhnroyal** [comment]
No, there is no board. But I can probably set one up and add a 5.x branch later.

**Comment by ueman** [comment]
Fixed by #1376
