### ISSUE TITLE
some problem when using express res.clearCookie(key) 

### ISSUE THREAD

**Issue by BachCN** [flutterchina/dio#138]
完成登录后想要清除登录相关辅助cookie 时遇到阻塞 服务端取消发送clearCookie即正常

## Logs

I/flutter ( 2580): DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Valid value range is empty: 0#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:237:55)
I/flutter ( 2580): #1      _Cookie._validate (dart:_http/http_headers.dart:989:14)
I/flutter ( 2580): #2      _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:933:5)
I/flutter ( 2580): #3      new _Cookie.fromSetCookieValue (dart:_http/http_headers.dart:849:5)
I/flutter ( 2580): #4      new Cookie.fromSetCookieValue (dart:_http:1112:16)
I/flutter ( 2580): #5      _HttpClientResponse.cookies.<anonymous closure> (dart:_http/http_impl.dart:317:26)
I/flutter ( 2580): #6      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter ( 2580): #7      _HttpClientResponse.cookies (dart:_http/http_impl.dart:316:14)
I/flutter ( 2580): #8      Dio._makeRequest (package:dio/src/dio.dart:418:48)
I/flutter ( 2580): <asynchronous suspension>
I/flutter ( 2580): #9      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:337:26)
I/flutter ( 2580): #10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
I/flutter ( 2580): #11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
I/flutter ( 2580): #12     Future._propagateToListeners.ha
E/flutter ( 2580): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 2580): NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 2580): Receiver: null
E/flutter ( 2580): Tried calling: []("success")
E/flutter ( 2580): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)

**Comment by zhujian1989** [comment]
> 完成登录后想要清除登录相关辅助cookie 时遇到阻塞 服务端取消发送clearCookie即正常
> 
> ## Logs
> I/flutter ( 2580): DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Valid value range is empty: 0#0 _StringBase.[] (dart:core/runtime/libstring_patch.dart:237:55)
> I/flutter ( 2580): #1 _Cookie._validate (dart:_http/http_headers.dart:989:14)
> I/flutter ( 2580): #2 _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:933:5)
> I/flutter ( 2580): #3 new _Cookie.fromSetCookieValue (dart:_http/http_headers.dart:849:5)
> I/flutter ( 2580): #4 new Cookie.fromSetCookieValue (dart:_http:1112:16)
> I/flutter ( 2580): #5 _HttpClientResponse.cookies. (dart:_http/http_impl.dart:317:26)
> I/flutter ( 2580): #6 List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
> I/flutter ( 2580): #7 _HttpClientResponse.cookies (dart:_http/http_impl.dart:316:14)
> I/flutter ( 2580): #8 Dio._makeRequest (package:dio/src/dio.dart:418:48)
> I/flutter ( 2580): 
> I/flutter ( 2580): #9 Dio._request.. (package:dio/src/dio.dart:337:26)
> I/flutter ( 2580): #10 _RootZone.runUnary (dart:async/zone.dart:1379:54)
> I/flutter ( 2580): #11 _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
> I/flutter ( 2580): #12 Future._propagateToListeners.ha
> E/flutter ( 2580): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
> E/flutter ( 2580): NoSuchMethodError: The method '[]' was called on null.
> E/flutter ( 2580): Receiver: null
> E/flutter ( 2580): Tried calling: 
> E/flutter ( 2580): #0 Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)

我也遇到这个问题。。。然后吧源码拷出来 直接把cookie去掉了。项目里暂时用不到

**Comment by wendux** [comment]
能补充一下完整复现的步骤吗？  我需要本地模拟复现一下才能定位问题


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by zhujian1989** [comment]
> 能补充一下完整复现的步骤吗？ 我需要本地模拟复现一下才能定位问题
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

我看了下服务器返回的set-cookie：
sessionid=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/

然后对照源码http_headers.dart,989行中解析的过程
if (value[0] == '"' && value[value.length - 1] == '"') {
      value = value.substring(1, value.length - 1);
    }

解析sessionid=;，这里应该会报一个
RangeError (index): Invalid value: Valid value range is empty: 0

之前加您的qq没通过。。。方便的话我把我这个api发给您？

**Comment by wendux** [comment]
qq好久没用了，可以重新加一下，这个session的值是空吧？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
fixed! please update to 1.0.17 or 2.0.1
