### ISSUE TITLE
SocketException: Failed host lookup: 'abc.com' after disconnect -> reconnect internet

### ISSUE THREAD

**Issue by namdp** [flutterchina/dio#1382]
Try to turn off wifi -> wait for a while -> turn it on then reload api will got this error

SocketException: Failed host lookup: 'abc.com' (OS Error: No address associated with hostname, errno = 7)

**Comment by Lawati97** [comment]
@namdp how did you solve it?

**Comment by chao-ryan** [comment]
how did you solve it?
