### ISSUE TITLE
setting SSL pinning using certificate's public hashed key string (not a file)

### ISSUE THREAD

**Issue by murad1981** [flutterchina/dio#1388]
I currently use the following snippet to include my SSL certificate file into the http client:

```
final List<int>? _certBytes; //I read it from .cer file included in the project

(_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (client) {
      if (_certBytes != null) {
        SecurityContext sc = SecurityContext();
        sc.setTrustedCertificatesBytes(_certBytes!);
        HttpClient httpClient = HttpClient(context: sc);
        return httpClient;
      } else {
        client.badCertificateCallback =
            ((X509Certificate cert, String host, int port) => true);
        return client;
      }
    };
```

while this code works well, it will stop working if the certificate is expired, which means that I need to add a new certificate file into the app and upload again to the app stores, so I decided to host the certificate as a hashed string in Firebase's Remote Config and read it upon app launch, so I can change the certificate remotely without exporting new versions for the app, but couldn't find a way to set the `SecurityContext` with a certificate hashed string.

**Comment by jgoyvaerts** [comment]
SecurityContext is a dart class, not a dio class, so not much we can do about that on our end.

That being said, I'm not sure if your approach is considered best practice.

SSL pinning is supposed to be an extra security feature, but if you deliver the SSL certificate itself over a firebase connection, your security is only as good as the connection between the client and firebase. 

Anyways, you could base64 your certificate bytes, and decode them on client side from string back to bytes, then load them like you're doing now.
