### ISSUE TITLE
https相关问题

### ISSUE THREAD

**Issue by CaiJingLong** [flutterchina/dio#14]
因为ios要求必须使用https协议
而我们的服务器是自签名服务器,没有经过CA
dio底层使用httpclient来进行网络访问
而HttpClient又只支持构造方法创建自签名证书的相关配置
下版本能否增加httpClient的修改或者注入的相关配置

**Comment by fly512** [comment]
好像支持
var dio = new Dio();
dio.onHttpClientCreate

**Comment by CaiJingLong** [comment]
@fly512 
这个方法 我当时来看的话 是在内部创建好了以后,你可以获取到httpclient对象,修改参数
而我开始说了httpClient的自签名必须要在构造方法中传参,而dio中httpclient都是new出来的,没有提供自己注入httpclient的方案,所以我才会提这个issue,

**Comment by wendux** [comment]
已支持，先升级到>=0.1.2，如文档示例：
```dart
 dio.onHttpClientCreate = (HttpClient client) {
    // you can also create a new HttpClient to dio
    // return new HttpClient();  
  };
```

**Comment by shyandsy** [comment]
如何在dio 2.x中实现？
