### ISSUE TITLE
The web page and postman request are normal, and the error is reported with the DIO request on the flutter

### ISSUE THREAD

**Issue by quinoxz** [flutterchina/dio#1415]
The web page and postman request are normal, and the error “HttpException: Connection closed while receiving data” is reported with the DIO request on the flutter

If I directly request a server nginx from DIO in flutter, there is no problem, but if I request nginx with load balancing, this error will be reported
The nginx log also displays the request status code 200  But flutter reported this error

在网页和postman请求正常 在flutter上用dio请求 报错 HttpException: Connection closed while receiving data 
请问我需要配置什么东西吗
如果我在flutter中dio直接请求某台服务器nginx没有问题 但如果请求带有负载均衡的nginx就会报这个错误

**Comment by quinoxz** [comment]
![image](https://user-images.githubusercontent.com/63097011/152782984-c57b018c-af31-43be-9353-fffc8f1a922d.png)
This is my code in fluent

**Comment by mishaAe** [comment]
@quinoxz  I faced with similar issue, how do you fixed this ?
