### ISSUE TITLE
How to get custom headers response on web?

### ISSUE THREAD

**Issue by polpenyarrojaNik** [flutterchina/dio#1423]
I doing a Flutter app and I using dio to connect app with my web service. When I want to access to custom headers in response, on mobile I don't have any problem, but this headers on web not be available and get different.

My code:

` final dio = Dio();
        final response = await dio.getUri(requestUri,
          options: Options(headers: {
            'authorization': 'Bearer ${credentials!.accessToken}',
          }));`

How I do to on web and mobile get a same custom headers?

**Comment by jgoyvaerts** [comment]
This issue has been created many times in the past, please use the search feature before creating new issues.

More info here: https://github.com/flutterchina/dio/issues/1027#issuecomment-946825395
