### ISSUE TITLE
i cant do post request in flutter web

### ISSUE THREAD

**Issue by DEMONLEGENDARY** [flutterchina/dio#1426]
When i try a post request to an api from flutter web using Dio package i have this error: XMLHttpRequest, this error had happened in mobile but i fixed with this configuration, i think its for "DioForBrowser" which is being using as the DefaultHttpClientAdapter for dio, i have been searching a configuration for DioForWeb but i cant found it, if i cant use Dio for Http Request in web, how do you do http requests with flutter web? can you show me an example of a post request

 ```
Future<Response<dynamic>?>createAdmin(String` email, String password) async {
        Dio dio = Dio();
        if (dio.httpClientAdapter is DefaultHttpClientAdapter) {
          (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
              (HttpClient client) {
            client.badCertificateCallback =
                (X509Certificate cert, String host, int port) => true;
            return client;
          };
        }
        try {
          final response =
              await dio.post(('https://10.0.2.2:5001/api/Users/CreateAdmin'),
                  data: {
                    "item1": {
                      "userId": "string",
                      "name": "string",
                      "standardizedName": "string",
                      "lastName": "string",
                      "standardizedLastName": "string",
                      "fullName": "string",
                      "standardizedFullName": "string",
                      "profilePicUrl": "string",
                      "phoneNumber": "string",
                      "email": "string",
                      "roleId": 0,
                      "state": true,
                      "storeId": "string"
                    },
                    "item2": {
                      "image": "string",
                      "imageName": "string",
                      "folderName": "string"
                    }
                  },
                  options: Options(headers: {
                    HttpHeaders.contentTypeHeader: "application/json",
                    HttpHeaders.accessControlAllowOriginHeader: "*",
                    HttpHeaders.accessControlAllowCredentialsHeader: true,
                    HttpHeaders.accessControlAllowHeadersHeader:
                        "Origin,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,locale",
                    HttpHeaders.accessControlAllowMethodsHeader: "POST, OPTIONS"
                  }));
          if (response.statusCode == 201) {}
          return response;
        } catch (e) {
          print(e);
        }
        return null;
      }
 ```

![DioForNative](https://user-images.githubusercontent.com/99575452/153740114-c971cd2d-5e96-4e09-8fb6-00a506b5172e.png)
![DioForBrowser](https://user-images.githubusercontent.com/99575452/153740130-3f9967dd-6dcb-4a09-97a5-edf8ea6cd510.png)
![XMLHttpRequest error](https://user-images.githubusercontent.com/99575452/153740133-74a343d5-545e-41fb-9481-36952c20c16c.png)

**Comment by jgoyvaerts** [comment]
Are you only getting the errors in the browser?
Did you read up on CORS and how it works?

**Comment by DEMONLEGENDARY** [comment]
I'm kind of new in the CORS topic, how can I configure it in flutter? Do I need to configure it in my API as well?

**Comment by jgoyvaerts** [comment]
I'm sure CORS + flutter in google can help you out

**Comment by cedvdb** [comment]
@jgoyvaerts dio web adds headers to request which are not added in a  normal request, which means some request which shouldn't trigger preflight will trigger it.

You can google "Simple request" + "CORS"
