### ISSUE TITLE
FileSystemException: Cannot create file, path = 'null' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by Kayouyou** [flutterchina/dio#1430]
### download a zip file, but always return a failure: 

**FileSystemException: Cannot create file, path = 'null' (OS Error: Read-only file system, errno = 30)**

`final zipFile = await File(savePath).create(recursive: true);

Dio().download('https://....../20211104.zip'), zipFile);
`

**Comment by jgoyvaerts** [comment]
You are trying to save the file somewhere where you are not allowed, the system is preventing you from saving it.
This is not a Dio bug.
