### ISSUE TITLE
Error: DioError [DioErrorType.response]: XMLHttpRequest error. when request on localhost api => (on web)

### ISSUE THREAD

**Issue by Flutterry** [flutterchina/dio#1434]
`await Dio().get('http://localhost:3000/users');`

## note: 
It's Working fine in the emulator, problem in the web only

`Launching lib\main.dart on Chrome in debug mode...

Error: DioError [DioErrorType.response]: XMLHttpRequest error.
Source stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 910:28        get current
packages/dio/src/dio_mixin.dart 479:35                                                                                 fetch
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54        runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5        _async
packages/dio/src/dio_mixin.dart 478:31                                                                                 fetch
packages/dio/src/dio_mixin.dart 474:12                                                                                 request
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54        runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5        _async
packages/dio/src/dio_mixin.dart 444:33                                                                                 request
packages/dio/src/dio_mixin.dart 61:12                                                                                  get
packages/flutter_client/src/screen/splash/splash_provider.dart 21:17                                                   sendRequest
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54        runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5        _async
packages/flutter_client/src/screen/splash/splash_provider.dart 12:19                                                   sendRequest
packages/flutter/src/material/ink_well.dart 989:21                                                                     [_handleTap]
packages/flutter/src/gestures/recognizer.dart 198:24                                                                   invokeCallback
packages/flutter/src/gestures/tap.dart 608:48                                                                          handleTapUp
packages/flutter/src/gestures/tap.dart 296:5                                                                           [_checkUp]
packages/flutter/src/gestures/tap.dart 230:7                                                                           handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 563:9                                                                    handleEvent
packages/flutter/src/gestures/pointer_router.dart 94:12                                                                [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 139:9                                                                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13  forEach
packages/flutter/src/gestures/pointer_router.dart 137:17                                                               [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 123:7                                                                route
packages/flutter/src/gestures/binding.dart 439:19                                                                      handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                                                      dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                                                     dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                                                       [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                                                       handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                                                       [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                                                      [_handlePointerDataPacket]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1026:13       invoke1
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 184:5         invokeOnPointerDataPacket
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 130:39            [_onPointerData]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 543:18            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 496:21            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 210:16            loggedHandler
    at Object.throw_ [as throw] (http://localhost:6662/dart_sdk.js:5067:11)
at http://localhost:6662/packages/dio/src/interceptors/log.dart.lib.js:1038:21
    at _RootZone.runBinary (http://localhost:6662/dart_sdk.js:40445:59)
    at _FutureListener.catchError.handleError (http://localhost:6662/dart_sdk.js:35374:33)
    at handleError (http://localhost:6662/dart_sdk.js:35947:51)
    at Function._propagateToListeners (http://localhost:6662/dart_sdk.js:35973:17)
    at _Future.new.[_completeError] (http://localhost:6662/dart_sdk.js:35823:23)
    at _SyncCompleter.new.[_completeError] (http://localhost:6662/dart_sdk.js:35279:36)
    at _SyncCompleter.new.completeError (http://localhost:6662/dart_sdk.js:35203:29)
    at onError (http://localhost:6662/dart_sdk.js:35043:49)
    at _RootZone.runBinary (http://localhost:6662/dart_sdk.js:40445:59)
    at _FutureListener.then.handleError (http://localhost:6662/dart_sdk.js:35374:33)
    at handleError (http://localhost:6662/dart_sdk.js:35947:51)
    at Function._propagateToListeners (http://localhost:6662/dart_sdk.js:35973:17)
    at _Future.new.[_completeError] (http://localhost:6662/dart_sdk.js:35823:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:6662/dart_sdk.js:35859:31)
    at Object._microtaskLoop (http://localhost:6662/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:6662/dart_sdk.js:40714:13)
    at http://localhost:6662/dart_sdk.js:36191:9
`

**Comment by momoDragon** [comment]
https://github.com/flutterchina/dio/issues/1340

**Comment by Flutterry** [comment]
> #1340

Tanks it's work
