### ISSUE TITLE
JSON MIME Type detection incorrect

### ISSUE THREAD

**Issue by lukaskirner** [flutterchina/dio#1451]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps

The JSON Mime Type check in Dio is not correct. For example, a Response with the Content Type `application/vnd.example.com+json` is not detected as JSON (https://mimesniff.spec.whatwg.org/#json-mime-type). I have a PR to fix this https://github.com/flutterchina/dio/pull/1439

**Comment by wendux** [comment]
try 4.0.5
