### ISSUE TITLE
v4.0.5, connect time out will cause LateInitializationError of local variable ‘request’

### ISSUE THREAD

**Issue by jiangtian616** [flutterchina/dio#1452]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |             |      |
| Platform Version               |                           |      |
| Dio Version                    | 4.0.5                                 |      |
| Android Studio / Xcode Version |        |      |
| Repro rate                     | all the time (100%) |      |
| Repro with our demo prj        |         |      |
| Demo project link              | |      |

### Issue Description and Steps
Time out that occurs at connect phase leads to calling `request.abort()` , but local variable `request` hasn’t been initialized.
https://github.com/flutterchina/dio/commit/5ddb661ab0db2bf6570139e64ebe5463c08a1c41 Row 64

**Comment by wendux** [comment]
try with 4.0.6

**Comment by jomonson** [comment]
For me 4.0.6 didn't fix the issue. 4.0.4 did.

**Comment by linkaipeng** [comment]
> For me 4.0.6 didn't fix the issue. 4.0.4 did.

me too.
