### ISSUE TITLE
如何获取原始json数据？

### ISSUE THREAD

**Issue by kandroid29** [flutterchina/dio#147]
请问能否获取到响应的原始json数据？

**Comment by wendux** [comment]
可以指定请求options的responseType为PLAIN , 这样便会返回原始字符串

**Comment by kandroid29** [comment]
> 1. 如果dio版本>=v1.0.14，则可以直接通过` response.toString()`来获取响应body字符串
> 2. 通用的作法是：指定请求options的responseType为PLAIN , 这样便会返回原始字符串
非常感谢
