### ISSUE TITLE
Error: Getter not found

### ISSUE THREAD

**Issue by kai-xun-strong** [flutterchina/dio#148]
compiler message: file:///Users/treapp/Study/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/dio-1.0.14/lib/src/dio.dart:522:43: Error: Getter not found: 'contentTypeHeader'.
compiler message:           request.headers.set(HttpHeaders.contentTypeHeader,
compiler message:                                           ^^^^^^^^^^^^^^^^^
compiler message: file:///Users/treapp/Study/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/dio-1.0.14/lib/src/dio.dart:526:39: Error: Getter not found: 'contentTypeHeader'.
compiler message:           options.headers[HttpHeaders.contentTypeHeader] =
compiler message:                                       ^^^^^^^^^^^^^^^^^
compiler message: file:///Users/treapp/Study/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/dio-1.0.14/lib/src/dio.dart:616:60: Error: Getter not found: 'json'.
compiler message:     opt.contentType ??= options.contentType ?? ContentType.json;
compiler message:                                                            ^^^^
compiler message: file:///Users/treapp/Study/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/dio-1.0.14/lib/src/form_data.dart:131:46: Error: Getter not found: 'text'.
compiler message:         (fileInfo.contentType ?? ContentType.text).mimeType);
compiler message:                                              ^^^^
compiler message: file:///Users/treapp/Study/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/dio-1.0.14/lib/src/transformer.dart:71:55: Error: Getter not found: 'json'.
compiler message:       if (options.contentType.mimeType == ContentType.json.mimeType) {
compiler message:                                                       ^^^^
compiler message: file:///Users/treapp/Study/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/dio-1.0.14/lib/src/transformer.dart:104:66: Error: Getter not found: 'json'.
compiler message:         && response.headers.contentType?.mimeType == ContentType.json.mimeType) {
compiler message:                                                                  ^^^^
compiler message: file:///Users/treapp/Study/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/dio-1.0.14/lib/src/upload_file_info.dart:22:41: Error: Getter not found: 'binary'.
compiler message:   ContentType contentType = ContentType.binary;
compiler message:                                         ^^^^^^
Compiler failed on /Users/treapp/Study/Flutter/flutter_native_camera/flutter_native_camera/lib/main.dart

**Comment by wendux** [comment]
Flutter version: ____?
Dart Version: ______?

**Comment by kai-xun-strong** [comment]
Flutter Version:0.5.1
Dart Version：2.0.0
Upgrade to Flutter: 1.0.0 Dart: 2.1.0
The problem is solved
Thank you very much for reply

**Comment by wendux** [comment]
OK

**Comment by raipradeep** [comment]
static String handleError(Error error) {
    String errorDescription = "";
    if (error is DioError) {
      switch (error.type) {
        case DioErrorType.CANCEL:
          errorDescription = "Request to API server was cancelled";
          break;
        case DioErrorType.CONNECT_TIMEOUT:
          errorDescription = "Connection timeout with API server";
          break;
        case DioErrorType.DEFAULT:
          errorDescription = "Connection failed due to internet connection";
          break;
        case DioErrorType.RECEIVE_TIMEOUT:
          errorDescription = "Receive timeout in connection with API server";
          break;
        case DioErrorType.RESPONSE:
          errorDescription =
          "Received invalid status code: ${error.response.statusCode}";
          break;
        case DioErrorType.SEND_TIMEOUT:
          errorDescription = "Connection send timeout";
          break;
      }
    } else {
      errorDescription = "Unexpected error occured";
    }
    return errorDescription;
  }

//////////////////////////////////////////////////////////////////////////////////////////////////////////////

Getting this type of error
Error: The getter 'type' isn't defined for the class 'Error'.
 - 'Error' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.
      switch (error.type) {
