### ISSUE TITLE
网络不通情况下interceptor.response.onError里e.response为空拿不到options.extra怎么办

### ISSUE THREAD

**Issue by 513153980** [flutterchina/dio#149]
网络不通情况下interceptor.response.onError里e.response为空拿不到options.extra怎么办

_Originally posted by @513153980 in https://github.com/flutterchina/dio/issues/118#issuecomment-457806592_

**Comment by wendux** [comment]
e.request就是options


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by 513153980** [comment]
class DioError extends Error {
  DioError({this.response, this.message, this.type = DioErrorType
      .DEFAULT, this.stackTrace});

  /// Response info, it may be `null` if the request can't reach to
  /// the http server, for example, occurring a dns error, network is not available.
  Response response;

  /// Error descriptions.
  String message;

  DioErrorType type;

  String toString() =>
      "DioError [$type]: " + message + (stackTrace ?? "").toString();

  /// Error stacktrace info
  StackTrace stackTrace;
}


---e.request报错，没有这个属性

**Comment by wendux** [comment]
你dio不是最新版本，升级到最新版本再试


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by 513153980** [comment]
有了，谢谢
