### ISSUE TITLE
Throw exception when try to upload file to AWS3 （上传文件到AWS3时抛出异常）： SocketException: Connection reset by peer 

### ISSUE THREAD

**Issue by AtomLee4279** [flutterchina/dio#1499]
@wendux @wprater @falkorichter @vishna @trevorwang @hpoul 

- [✅] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               |  2.13.0-0.1.pre • channel beta                               |      |
| Dio Version                    |  2.17.0-266.1.beta (beta)                                  |      |
| Android Studio / Xcode Version | Android Studio 3.1.3 / Xcode 13.4.1              |      |
| Repro rate                     |  all the time (100%)   |      |

### Issue Description and Steps

尝试使用dio做put上传，上传文件到AWS3。我的上传地址由我方后台返回。例如：
https://hgcaputre-bucket.obs.cn-sz1.ctyun.cn/normal/2022/06/13/b7c7d0f43a35451ab94eeecdf3c6da5c.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220613T131120Z&X-Amz-SignedHeaders=content-md5%3Bhost&X-Amz-Expires=3600&X-Amz-Credential=HMJMJXJWPQISW4OV9ZN5%2F20220613%2Fcn-sz1%2Fs3%2Faws4_request&X-Amz-Signature=a264fa80da1e15cd8723165e65429ff1608de96bc2f20f6b459b29ae29a9a49d
代码如下：
```
try {
      Options options = Options(headers: {Headers.contentTypeHeader:"multipart/form-data","token":""});
      var formData = FormData.fromMap({
        'file': await MultipartFile.fromFile(filePath,filename: p.basename(filePath))
      });
      if (kDebugMode) {
        print("准备上传压缩文件：${p.basename(filePath)}");
      }
      var response = await Dio().put(toUrl,data: formData,options: options,cancelToken: cancelToken,
        onSendProgress: (int sent,int total){
          var percentage = sent/total;
          onUploading?.call(percentage);
        }
      );
      if (kDebugMode) {
        print(response);
      }
      return response.statusCode == 200;
    } on DioError catch (e) {
      if (kDebugMode) {
        if (e.response != null) {
          print(e.response!.data);
          print(e.response!.headers);
          print(e.response!.requestOptions);
        } else {
          // Something happened in setting up or sending the request that triggered an Error
          print(e.requestOptions);
          print(e.message);
        }
      }
      if(CancelToken.isCancel(e)){
        throw "取消上传：\n$filePath";
      }else{
        throw "===上传失败===\n$filePath";
      }
    }
```
运行时将抛出异常：
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = hgcaputre-bucket.obs.cn-sz1.ctyun.cn, port = 58077
我的请求调试截图：
![image](https://user-images.githubusercontent.com/30311596/173362595-16ef9bfe-c4e5-4911-84fe-c44c221738db.png)
我的Header展开部分：
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/30311596/173362874-4ab9c8f0-7df2-4620-90e8-145270769c7c.png">
===============
另外有一份网页demo：它能顺利put请求上传到AWS3。Header如下：
![image](https://user-images.githubusercontent.com/30311596/173363130-564baffd-bd0e-4240-b3cb-37c237c615f8.png)
Help！！！Thanks！！

**Comment by wuchuixu** [comment]
你好，请问你这个是怎么解决的？
