### ISSUE TITLE
使用download时如果返回的是json，response.data无法获取数据

### ISSUE THREAD

**Issue by jlcool** [flutterchina/dio#150]
## Steps to Reproduce
 比如没有下载权限，后台返回数据给以提示，但是response.data无法获取数据，应该怎么获取呢？

**Comment by wendux** [comment]
因为现在的文件可能较大，所以不会将内容保存在内存中，你可以下载结束后读取文件内容，下面是一个例子：
```dart
      var dio = new Dio();
      var url = "https://flutter.io/assets/flutter-lockup-4cb0ee072ab312e59784d9fbf4fb7ad42688a7fdaea1270ccf6bbf4f34b7e03f.svg";
      await dio.download(url, "./example/flutter.svg");
      // 读取文件
      var f = new File("./example/flutter.svg");
      var t = await f.open();
      t.close();
```

**Comment by jlcool** [comment]
我得先f.readAsStringSync()再确认是不是json，像你说的如果文件太大，这个方法是不是不太优

**Comment by jlcool** [comment]
暂时用try catch的方式，后台返回403，判断statusCode值来控制下载权限

**Comment by wendux** [comment]
只是一个示例，大文件你完全可以改成异步读取。另外你如果是想通过header判断是否下载，可以直接使用get方法，将responseType 设为流，自己处理流读取，具体可以参考download 的实现。你现在直接调download有个瑕疵就是如果是403也会保存响应流到文件。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
v2.x 中，在statusCode不对时，可以通过response.data获取返回的内容了
