### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by 1AlexFix1** [flutterchina/dio#151]
Hi, I looked at the source files for upload file with formData and found that if you submit the data parameter to the post, then
1) all that was in the options data is ignored
2) it is not possible to add query parameters if data is FromData
3) if there is a uploading progress and the request is canceled, the Uploading Progress continues
4) receiveTimeout no work with upload file

**Comment by wendux** [comment]
Most of your questions are changed in version 2.x. Please refer to the 2.x document firstly.
