### ISSUE TITLE
能否打印请求日志

### ISSUE THREAD

**Issue by kandroid29** [flutterchina/dio#152]
之前在Android原生开发中用的Retrofit+OkHttp中可以通过使用HttpLoggingInterceptor来打印请求日志到LogCat，这样对于调试非常方便，请问dio中有没有提供类似的功能？
PS: 日志内容包括请求url，header，body等信息

**Comment by wendux** [comment]
v2.x已添加Log Interceptor, 可以升级一下

**Comment by kandroid29** [comment]
谢谢！
