### ISSUE TITLE
interceptor.request.onSend reject does not block network call

### ISSUE THREAD

**Issue by ozeksi** [flutterchina/dio#155]
When I reject the network call with `dio.reject(DioError(message: "Authorization is failed"))` it still does the request. Instead, if I use `dio.resolve(null)`, request does not go to the server as expected.

I think "reject" should also cancel the request and should not reach to the server.

**Comment by wendux** [comment]
Could you paste your code segment?

**Comment by ozeksi** [comment]
It was my fault, I must do 'return dio.reject(DioError(message: "Authorization is failed"));'  instead `reject(DioError(message: "Authorization is failed"));` 

I missed `return` statement.
