### ISSUE TITLE
Login and retrieve internal page

### ISSUE THREAD

**Issue by AlejandroC90** [flutterchina/dio#157]
Well, sorry for asking for help here but I wanna if its posible to login and retrieve some web pages and then logout in some web page.
I use the same dio instance, and unique responses, first a post to login and then a get to retrieve the page, the **login works** but when trying to retrieve the internal page it does not, I don't get the page that I want, just a redirect to the main page.

Don't know if this is possible with dio or what I'm doing wrong, maybe it has something to do with cookies, hope you can help me. Thanks.
## Steps to Reproduce
    login = await dio.post(loginurl, data: logindata);
    profile = await dio.get(profileurl);

**Comment by wendux** [comment]
Please refer to:  https://github.com/flutterchina/dio#cookie-manager
