### ISSUE TITLE
Android-Perform Dio Download with certificate issue

### ISSUE THREAD

**Issue by LSmint** [flutterchina/dio#158]
how to solve this problem below, it only happen in android platform:
I/flutter (15996): file download error: DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error:
I/flutter (15996):      CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))

**Comment by wendux** [comment]
It seems to be your certificate is considered invalid in Android.

**Comment by shenglijin** [comment]
how to solve it ,or ignore the certificate ?

**Comment by LSmint** [comment]
@shenglijin ,

Before execute download function, add the following codes:
`if (Platform.isAndroid) {
        (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client) {
          // print('onHttpClientCreate entered...');  // this code is never reached
          client.badCertificateCallback = (X509Certificate cert, String host, int port) => true;
          return client;
        };
      }`

**Comment by parthvora-techypanther** [comment]
where to add this code?

**Comment by anantaramdas** [comment]
@parthvora-techypanther as @LSmint mentioned put that code just before request actual execution (post/get etc).

**Comment by renatojabreu** [comment]
> @shenglijin ,
> 
> Before execute download function, add the following codes:
> `if (Platform.isAndroid) { (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client) { client.badCertificateCallback = (X509Certificate cert, String host, int port) => true; return client; }; }`

When i put this code i get a error, can someone help me?

E/flutter (20020): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'httpClientAdapter' was called on null.
E/flutter (20020): Receiver: null

**Comment by ko3ak1990** [comment]
never ignore it if you care about security ! Read about MITM attacks! 
According to doc you should do following:

String PEM="XXXXX"; // certificate content
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
    client.badCertificateCallback=(X509Certificate cert, String host, int port){
        if(cert.pem==PEM){ // Verify the certificate
            return true;
        }
        return false;
    };
};

**Comment by Cge001** [comment]
> @shenglijin ,
> 
> Before execute download function, add the following codes:
> `if (Platform.isAndroid) { (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client) { client.badCertificateCallback = (X509Certificate cert, String host, int port) => true; return client; }; }`

solve my problem,good!

**Comment by martinfrouin** [comment]
https://github.com/dart-lang/http/issues/627#issuecomment-1824426263

It solves the problem for me
