### ISSUE TITLE
upload image stuck the UI on ios

### ISSUE THREAD

**Issue by pockyzhang** [flutterchina/dio#159]
I take a pic（about 7M） and post it to the server.It's good on my XIAOMI8 ,but on iOS(iPhone 6s ,ios10),the upload process
makes the UI stuck for about 8s. 

    FormData formData = new FormData.from({
      "images": UploadFileInfo(imgFile, "test.jpg")
    });
      Response response = await dio.post("/image/upload_t", data: formData);

**Comment by wendux** [comment]
please update to latest version and try again.
