### ISSUE TITLE
suggestion about  Interceptor (关于拦截器的一点建议)

### ISSUE THREAD

**Issue by songshitong** [flutterchina/dio#160]
## Steps to Reproduce
   version   dio: ^2.0.0 

    there is the Interceptor  in  OKHTTP 
   
```
public interface Interceptor {
  Response intercept(Chain chain) throws IOException;
  interface Chain {
    Request request();
    Response proceed(Request request) throws IOException;
  }
}
```

    English:
    in OkHttp , i  can  get   request , response and err  in one method -- **intercept(Chain chain)**.
    in your package , i  must get  request , response  and err  in  three method.
    in my  test , if  there is an error occur , only  onError  callback.
    but , i want to deal  it  in  response and return another response instead of  onError .
    how can i deal response  in  onError  and return  a response in onError  when  my  response broken??
     
     中文：
     在OkHttp的intercept里面，可以同时拿到request ,response,很方便进行处理
     在您的拦截器里面，他们被分为onRequest，onResponse，onError 这三个方法，但是如果response
     发生错误(比如401)的话，只有onError发生回调，onResponse 没有调用。
     如果我的response发生错误，那么只能在onError里面处理，但是重新请求后怎么返回新的response 
     在onError里面？目前的逻辑只能返回另一个DioError？？？

     使用场景是这样：
      1， 调用接口A，出现token失效
      2，在onError里面刷新token，刷新成功，重新调用接口A；刷新失败，跳转到登录页面
      3，重新调用接口A成功的情况下，由于是在onError中处理的，但是回调结果是response类型的，我没 
            办法把重新调用接口A的结果返回？？

      如果可以的话，能不能按OkHttp的方式设置拦截器
     如果您有其他好的建议，请回复，谢谢

**Comment by songshitong** [comment]
我找到了处理onError的代码，我可能对文档的理解不够清晰，谢谢您的指导

 english:
    i  found  the  source code of how to deal  onError.
    i   need to read document again.
   best regards

  ```
Future<Response<T>> _transFutureStatusIfNecessary<T>(Future future) {
    return future.then<Response<T>>((data) {
      // Strictly be a DioError instance, but we relax the restrictions
      // if (data is DioError)
      if (data is Error) {
        return reject<T>(data);
      }
      return resolve<T>(data);
    }, onError: (err) {
      if (err is Response) {
        return resolve<T>(err);
      }
      return reject<T>(err);
    });
  }
```

**Comment by pppshiwen** [comment]
> 可以在onError里处理，onError里也可以反回Response对象，返回后会认为是成功，就会走到then。拦截器的所有回调中，返回DioError就会直接走到catch, 返回Response,就会直接走到then.
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

我已经在onError里返回response 了,之后在onResponse里也被拦截到了，可没有返回给当初的接口调用结果

dio.interceptors.add(RefreshTokenInterceptor());
    //添加拦截器
    dio.interceptors.add(InterceptorsWrapper(
      //请求之前
     onRequest: (RequestOptions options) async{
      var token = await Storage.getString('Token');
      //统
      if(token != null) {
        options.headers[HttpHeaders.authorizationHeader] = 'Bearer ' + token;
      }
      return options; //continue
    }, onResponse: (Response response){//返回之前
       print('response1$response');
      return response; // continue
    }
    , onError: (DioError e)async{
    }
    ));
  }

//拦截器
class RefreshTokenInterceptor extends Interceptor {
  @override
  onError(DioError e) async{
    // TODO: implement onError
    print('错误码：${e.response.statusCode}');
    print("错误之前");
    var tokenDio = HttpUtil.getInstance().dio;
    Response _response = e.response;
    if(_response != null && _response.statusCode == 401) {//登录过期，重新登录

    }else if(_response != null && _response.statusCode == 419) { //重新获取token
      tokenDio.lock();
      tokenDio.interceptors.responseLock.lock();
      tokenDio.interceptors.errorLock.lock();
      String reToken = await Storage.getString("reToken");
      print('reToken$reToken');
      //刷新token
      getRetoken(reToken).then((val) async {//刷新token成功
      print('val${val.data['access_token']}');
        Storage.setString("Token", val.data['access_token']);
        //继续执行上个请求
        var _request = e.response.request;
        var token = await Storage.getString('Token');
        _request.headers[HttpHeaders.authorizationHeader] = 'Bearer ' + token;
        Response _response = await tokenDio.request(
            _request.path,
            data: _request.data,
            queryParameters: _request.queryParameters,
            cancelToken: _request.cancelToken,
            options: _request,
            onReceiveProgress: _request.onReceiveProgress);
//        print('response--------$_response');
        return _response;
      }).catchError((e) {// 刷新token失败
        print('getRetoken---e----$e');

      });
      tokenDio.unlock();
      tokenDio.interceptors.responseLock.unlock();
      tokenDio.interceptors.errorLock.unlock();
    }
    super.onError(e);
  }

  Future getRetoken(reToken) async {
    var dio = Dio();
    var data = {
      "grant_type": "refresh_token",
      "client_id": "mall",
      "client_secret": "secret",
      "refresh_token": reToken,
    };
    Options options = Options();
    options.contentType = Headers.formUrlEncodedContentType;
    var response = await dio.post(servicePath['reTokenPath'],data:data,options: options);
    return response;
  }
}

// 获取购物车列表
Future getShoppingCart() async{
//  Options options = Options();
//  options.contentType = Headers.jsonContentType;
  var response = await HttpUtil().dio.get(servicePath['shoppingCart']);
  print('getShoppingCart-----$response');
  return response.data;
}

 print('response1$response');有执行
print('getShoppingCart-----$response');没有被执行到
