### ISSUE TITLE
Version #2 - Cookie problem.

### ISSUE THREAD

**Issue by pedromorgan** [flutterchina/dio#162]
Version #2 does not save cookies.

**Comment by wendux** [comment]
v2.0 cookie manager: https://github.com/flutterchina/dio#cookie-manager

```dart
var dio = new Dio();
dio.interceptors.add(CookieManager(CookieJar()))
```

**Comment by BTPJ** [comment]
me too
var dio = new Dio();
dio.interceptors.add(CookieManager(CookieJar()))
do nothing

**Comment by pedromorgan** [comment]
I actually tried dio 2+ yesterday (latest)
and same issue..

it seems the ```.interceptors``` property is not "visible" somehow...

**Comment by wendux** [comment]
@BTPJ @pedromorgan 
1. If you are using dio singleton,  there is a known case that causes singleton will be initialized many times, please check if this case first:
https://stackoverflow.com/questions/52501327/strange-behavior-in-dart-singleton
2. I have created a [flutter demo](https://github.com/flutterchina/dio/tree/master/example/flutter_example) , and test the CookieManager worked well .

**Comment by weiwill** [comment]
我也有相同的问题，因为不知道原理，所以我在 onResponse里面添加了下面的代码来自己读取发送cookie

I have the same problem, because I don't know the principle, so I added the following code in onResponse to read and send cookies myself.

``` dart
List<String> cookieString = response.headers[HttpHeaders.setCookieHeader];
if (cookieString != null) {
  List<Cookie> cookies =
      cookieString.map((str) => Cookie.fromSetCookieValue(str)).toList();
  dio.options.headers['cookie'] =
      cookies.map((cookie) => cookie.toString()).join(';');
}
```

**Comment by wendux** [comment]
@weiwill  看看是不是这个问题http:s://stackoverflow.com/questions 
/52501327/strange-behavior-in-dart-singleton ， 你可以对比example 目录下的flutter demo，里面打了每次请求的日志看看。验证后希望能将结论同步出来。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by BTPJ** [comment]
@wendux 应该不是singleton的问题，因为同样的代码在1.x版本是可以正常获取cookie的，换到2.x就不行了，而且按照那个singleton的问题，我的确是正常导包的

**Comment by weiwill** [comment]
@wendux 我也是1切换到2就不行了，你说的我会再确认一下，但是我感觉不是这个问题， 同@BTPJ我这边也是正常导包

**Comment by wendux** [comment]
@BTPJ @BTPJ
1.  1.x和2.x使用cookiejar的方式有变化，2.0变成了拦截器。example下所有示例都是正常的。
2. 我在example下创建了一个flutter_demo, 里面有2.0使用Cookie，在每次请求时都户打印出请求头和响应头，我本地看，第二次点击“request”按钮后，请求头中都是能带上cookie的，你们运行一下看是否正确。
3. 如果还是不行，能否创建一个最简单的可复现demo，我拉下来调试一下，或者加我微信（Demons-du）一起联调一下。

**Comment by BTPJ** [comment]
后台接口比较特殊，登录时会使用302重定向，dio不支持就监听错误获取登录后返回的location键手动设置重新请求，并获取set-cookie键，统一在后面每次请求时手动添加cookie
dio..interceptors.add(InterceptorsWrapper(
          onRequest: (RequestOptions options) {
        if (cookieString!=null) {
              List<Cookie> cookies = cookieString
                  .map((str) => Cookie.fromSetCookieValue(str))
                  .toList();
              options.headers[HttpHeaders.cookieHeader] =
                  cookies.map((cookie) => cookie.toString()).join(';');
            }
              return options;
          }));

**Comment by wendux** [comment]
@BTPJ 也就是说正常情况下(非302)CookieManager是生效的吗？还有状态码不是成功时如果有cookie也应该保存一下的, 这个将在2.0.10版更新。
