### ISSUE TITLE
Flutter error "type '_OneByteString' is not a subtype of type 'Map<String, dynamic>'" after Dio call

### ISSUE THREAD

**Issue by feykro** [flutterchina/dio#1622]
### New Issue Checklist

- [ ✅] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                           |      |
| Platform Version               | 3.3.5                              |      |
| Dio Version                    | 4.0.6                                  |      |
| Android Studio / Xcode Version | Android Studio 2022.1.1 / Xcode 14.0.1              |      |
| Repro rate                     | Only in one specific set of circumstances   |      |

### Issue Description and Steps

On startup, my flutter app makes a request to the backend using `dio.get`. Both debug and release version work just fine for me and the testers in my team. When we have submitted the app to Apple for review, this startup call doesn't work. Or rather, it returns a value that fails to be read properly and throws the following error : "type '_OneByteString' is not a subtype of type 'Map<String, dynamic>'".

When making the same call using Postman, the result comes in normally, with proper json format and the header `Content-Type` has the value `application/json`.

I don't understand why the type would be interpreted as a OneByteString in that particular case, it's also a problem that only affects the tester, no matter how many times he re-launches and re-installs the app. I fail to reproduce it.

Steps we go through:
1. We run `await dio.get(...)` then return the data
2. We capture the data `as Iterable` and check if it's not empty
3. We take the first element of the data `as Map<String, dynamic>` and read the field we're looking for from the json
4. the `as Map` cast fails, throwing the error mentionned above.

**Comment by NiranjanShah** [comment]
same is happening with us too, in development mode, it is always working fine, however in production (apk) mode, it gives error as above.

**Comment by feykro** [comment]
@NiranjanShah Hello, I ended up figuring what was going on in my own app. The problem was a geo restriction on the server side, so it returned a code 200 that contained a « request rejected » message, thus the error.
There are other ways to get these kind of code 200 errors, check your production api with postman to see if that’s not the root of your issue.
