### ISSUE TITLE
Problem with refresh token interceptor and formdata 

### ISSUE THREAD

**Issue by lukajelacic** [flutterchina/dio#1626]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                         |      |
| Platform Version               |  3.7.0                              |      |
| Dio Version                    |   4.0.6                                |      |

### Issue Description and Steps

Hello everyone, I have a strange issue with refresh token interceptor when I'm trying to upload image to the server, in every other scenario everything is working as expected. If I try to to upload image and the token is not expired, everything is working fine. 
But when the token expires:
-onError interceptor is triggered
-new token is successfully obtained
-current request is sent again
-and I don't get any response

First request:
![prva](https://user-images.githubusercontent.com/32540065/216335806-2987b988-8cda-4b2b-a316-90a067739ae3.png)

Second request after obtaining new token:
![druga](https://user-images.githubusercontent.com/32540065/216335830-bbdc83fd-4224-4f79-9e40-ceb23104035c.png)

This is my interceptor:
```dart
apiClient.interceptors.add(
      QueuedInterceptorsWrapper(
        onRequest: (options, handler) async {
          final token = await storageRepository.get(AppConstants.accessToken);
          if (token != null) {
            options.headers['Authorization'] = 'Bearer $token';
          }
          return handler.next(options);
        },
        onError: (e, handler) async {
          if (e.response?.statusCode == 401 || e.response?.statusCode == 302) {
            final options = e.response?.requestOptions;

            try {
              final refreshToken = await storageRepository.get(AppConstants.refreshToken);

              final refreshResponse = await appAuth.token(
                TokenRequest(
                  appSettings.clientId,
                  appSettings.redirectUrl,
                  issuer: appSettings.issuer,
                  scopes:appSettings.scopes,
                  refreshToken: refreshToken as String,
                ),
              );
              await storageRepository.set(AppConstants.accessToken, refreshResponse?.accessToken);
              await storageRepository.set(AppConstants.refreshToken, refreshResponse?.refreshToken);

              final accessToken = await storageRepository.get(AppConstants.accessToken);

              if (options?.headers.containsKey(AppConstants.authorizationHeader) ?? false) {
                options?.headers.update(AppConstants.authorizationHeader, (v) => 'Bearer $accessToken');
              } else {
                options?.headers.addAll({AppConstants.authorizationHeader: 'Bearer $accessToken'});
              }

              final response = await apiClient.fetch(options!);

              return handler.resolve(response);
            } catch (err) {
              if (kDebugMode) {
                print(err);
              }
            }
          }
          exceptions.add(_getErrorMessageFromDioError(e));
          return handler.next(e);
        },
      ),
    );
```

This is api call where the problem occurs:

```dart
@override
  Future<bool> createReport(CreateTicketReportModel model) async {
    try {
      await apiProvider.post(
        url: '/api/app/ticket-report/create-report',
        data: FormData.fromMap(model.toMap()),
      );
      return true;
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
      return false;
    }
  }
```

This is toMap method of the model:

```dart
 Map<String, dynamic> toMap() {
    return {
      'ticketCheckRequestId': ticketCheckRequestId,
      'picture': picture != null ? MultipartFile.fromFileSync(picture!.path) : null,
    };
  }
```

Does anyone know what can be a problem?

**Comment by soniarojhwal** [comment]
I am facing the same issue with multipart/form-data request.

**Comment by lukajelacic** [comment]
@soniarojhwal please read this issue:
https://github.com/cfug/dio/issues/482?fbclid=IwAR0-dhbzFidjNpUnK8879QHzwz3si_3jf7lkFNFtsVVxasxnVhx2PPK27qo?fbclid=IwAR0-dhbzFidjNpUnK8879QHzwz3si_3jf7lkFNFtsVVxasxnVhx2PPK27qo
