### ISSUE TITLE
Two bytes added at end of file when posting FormData to upload file

### ISSUE THREAD

**Issue by svinchon** [flutterchina/dio#163]
Hello,
I am using DIO to post FormData to upload files from a Flutter Mobile App to a Storage Service.
After upload, all files have two bytes added at the end (0D / 0A = Carriage Return/ Line Feed).
This is an issue with DOCX files that are then considered as corrupted by Word.
Regards,
Seb

**Comment by wendux** [comment]
fixed! please update to latest version and try again.

**Comment by svinchon** [comment]
Excellent!
