### ISSUE TITLE
请教下，如何把cookie传送到后端？

### ISSUE THREAD

**Issue by Leadrive** [flutterchina/dio#165]
<prev>

	const fetchOptions = {
    url: url,
		credentials: 'include',
		method: 'POST',
		header: {
			'Accept': 'application/json',
			'Content-Type': 'application/json',
			'token': 'Bearer ' + token
		},
		data:JSON.stringify(send)
	}
</prev>
在RN中，可以通过添加 credentials: 'include'，前端把cookie传输到后端，
请问dio，应该如何实现类似功能？
谢谢。

**Comment by wendux** [comment]
https://github.com/flutterchina/dio#cookie-manager

**Comment by Leadrive** [comment]
@wendux 
谢谢你的回复，我看了你给出的链接，我的写法是这样的：
<prev>

    dio = new Dio(options);
    // API `getTemporaryDirectory` is from "path_provider" package. 加入后要重新 flutter run
    getApplicationDocumentsDirectory().then((Directory) {
      String dir = Directory.path;
      print("dir:"+dir);
      dio.interceptors.add(CookieManager(PersistCookieJar(dir)));
    });
<prev>

后台还是获取不到session。
我需要在程序中，显式地读取，附加到dio的headers之类/保存操作吗？
我的理解是这样的，既然dio是高度集成的，能否把cookie的存/取也集成进去？

另外，能否提供一个完整的写法？我相信其它网友也需要了解如何实现cookie，非常感谢！

**Comment by Leadrive** [comment]
请原谅我比较笨，实在没看懂如何写，实现dio.post后，自动接收后台返回的cookie的自动保存，dio.post时，能自动带上cookie。
能否详细指点一下，感谢！

**Comment by wendux** [comment]
这样写是正确的，我本地运行[测试示例](https://github.com/flutterchina/dio/blob/master/example/proxy.dart)，抓包后可以看到cookie, 如下图：
![image](https://user-images.githubusercontent.com/20411648/52715215-cd934b80-2fd6-11e9-9ef3-64c1d717124c.png)

**Comment by Leadrive** [comment]
@wendux 

我照抄你这段代码，也装了Charles抓包工具。

```javascript

  void test() async {
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (HttpClient client) {
      client.findProxy = (uri) {
        //proxy all request to localhost:8888
        print("proxy 8888");
        return "PROXY 192.168.1.110:8888";
      };
      client.badCertificateCallback=(X509Certificate cert, String host, int port)=>true;
    };
    // var dir=new Directory("./cookies"); // 此处会报 Permission denied
    // 这个目录，是根据getApplicationDocumentsDirectory得到的，每个模拟器会不同。
    var dir=new Directory("/Users/mac/Library/Developer/CoreSimulator/Devices/43AC3DCB-D3DE-43E2-8995-A5B97D7056E8/data/Containers/Data/Application/2F500600-F696-453F-A3A1-151460EABFA6/Documents/cookies");
    await dir.create();
    dio.interceptors.add(CookieManager(PersistCookieJar(dir.path)));
    Response<String> response;
    response = await dio.get("http://www.baidu.com");
    response = await dio.get("https://www.baidu.com");
    print(response.data);
  }

```

实际测试的结果是 http://www.baidu.com ，是可以看见cookie的，就象你贴出的图

https://www.baidu.com ，并没有cookie，
**_但请注意：你抓的包中，也是 host www.baidu.com，后面并没有 443_**
说明你跑的demo，并没有使用https

个人感觉，http是可以，https是有问题。
麻烦你重点测试下https。我试过
response= await dio.get("https://github.com/wendux/fly");
也是没有cookie的。

另外，我看cookies的保存目录下，是有生成相关的文件：
-rw-r--r--  1 mac  staff   76  2 14 00:10 www.baidu.com443
内容如下：
{"/":{"BD_NOT_HTTPS":"BD_NOT_HTTPS=1; Max-Age=300; Path=/;_crt=1550073635"}}% 

没看到www.baidu.com的文件（就是对应的http）

测试访问我自己的服务器，是有文件：
-rw-r--r--  1 mac  staff  193  2 13 23:46 www.xxxx.cn443
内容如下：
{"/":{"GoSessionID":"GoSessionID=6dd078eb9033c525dd4f535c3c74f1fa; Path=/; HttpOnly;_crt=1550072771","guid":"guid=0714f40d-b639-11e8-a01c-00163e0c90c0; Path=/;_crt=1550072771"}}%

贴不了图，麻烦抽时间看看，谢谢。

**Comment by Leadrive** [comment]
[https://github.com/Leadrive/Test/blob/master/a.png](https://github.com/Leadrive/Test/blob/master/a.png)

**Comment by Leadrive** [comment]
我现在上传不了截图，
你可以对比下你的抓包截图，你的测试，并没有走https协议。

**Comment by wendux** [comment]
我抓的就是https，其实cookiejar中cookie的存取只和域名有关，没有区分协议，你抓包看不到请求信息是因为你的Charles没有启用https抓包，开启方法可以右击域名：
![image](https://user-images.githubusercontent.com/20411648/52760611-20a6e600-304b-11e9-9794-e68ce7dd34b2.png)
这样就是ok的

**Comment by Leadrive** [comment]
非常感谢，现在可以了。
问题的关键，可能在每次post之前，都要调用
dio.interceptors.add(CookieManager(cookieJar));

我是在构造函数中，
cookieJar = PersistCookieJar(dir);

dir也是关键，要有写的权限。

**Comment by wendux** [comment]
@Leadrive  我们强烈推荐使用dio单例模式，所有请求都使用同一个dio实例发起，这样通用配置只需要配置一次即可。 另外使用单例会更省资源，性能会更优一些。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Leadrive** [comment]
@wendux 我现在用的就是单例，经测试，每次调用前，都要设置才行。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
@Leadrive  怎么可能，interceptors是dio实例属性，只需要添加一次，测试用例都是这么设置的，没有问题的。你可以通过以下方式来排错：
1. 可以给创建单例的地方下一个断点，看看是否会创建多次，
2. 目前已知的问题：dart中导入项目内文件有两种方式，第一种是通过相对路径，第二种是通过当前项目包名，通过不同方式导入会导致被导入文件代码执行两次。假设创建单例的代码在a.dart中，当前项目包名为b(yaml中的name字段)，则如下两种方式会导致a.dart中代码执行两次：
```dart
 import "./a.dart"
```
```dart
 import "package:b/a.dart"
```
可以排查一下导入方式是否一致。

**Comment by xiaotaiyang0568** [comment]
请教一下，我的配置如下，但是为什么后台request里面，cookie还是为空呢
`///http请求
class HttpManager {
  static const CONTENT_TYPE_JSON = "application/json";
  static const CONTENT_TYPE_FORM = "application/x-www-form-urlencoded";

  final TokenInterceptors _tokenInterceptors = new TokenInterceptors();

  HttpManager() {
    dio.interceptors.add(new HeaderInterceptors());

    dio.interceptors.add(_tokenInterceptors);

    dio.interceptors.add(new LogsInterceptors());

    dio.interceptors.add(new ErrorInterceptors(dio));

    dio.interceptors.add(new ResponseInterceptors());

//    dio.interceptors.add(new CookieManager(CookieJar()));

    cookieHandler();
  }

  cookieHandler () async {
    String dirName = (await getApplicationDocumentsDirectory()).path;
    var dir = Directory("${dirName}/cookies");
    await dir.create();
    print("path======>${dir.path}");
    dio.interceptors.add(CookieManager(PersistCookieJar(dir: dir.path)));
  }
}`
