### ISSUE TITLE
dio 2.0.2 如何设置证书

### ISSUE THREAD

**Issue by kingkadienm** [flutterchina/dio#169]
我在1.0的话可以使用 
dio.onHttpClientCreate = (HttpClient client) {
    client.badCertificateCallback =
        (X509Certificate cert, String host, int port) => true;
    return client;
  };
这个进行证书校验，但是2.0.2怎么设置

**Comment by wendux** [comment]
```dart
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
    client.badCertificateCallback=(X509Certificate cert, String host, int port)=>true
};

**Comment by shyandsy** [comment]
@wendux badCertificateCallback never called

```
Dio createDio(){
  BaseOptions options = new BaseOptions(
    connectTimeout: 5000,
    receiveTimeout: 3000,
  );
  Dio dio = new Dio(options);
  (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
    //HttpClient client= super.createHttpClient(context); //< <--- notice 'super'
    client.badCertificateCallback = (X509Certificate cert, String host, int port ){
      print("\n====================xxxxxxx==================\n");
      return true;
    };
  };
  return dio;
}
```

**Comment by cyd814** [comment]
> @wendux badCertificateCallback never called
> 
> ```
> Dio createDio(){
>   BaseOptions options = new BaseOptions(
>     connectTimeout: 5000,
>     receiveTimeout: 3000,
>   );
>   Dio dio = new Dio(options);
>   (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
>     //HttpClient client= super.createHttpClient(context); //< <--- notice 'super'
>     client.badCertificateCallback = (X509Certificate cert, String host, int port ){
>       print("\n====================xxxxxxx==================\n");
>       return true;
>     };
>   };
>   return dio;
> }
> ```

跟你一样的问题，没有执行到。解决了吗？
