### ISSUE TITLE
How to upload image 

### ISSUE THREAD

**Issue by alyfreym** [flutterchina/dio#170]
I created my server and I have a request for uploading images, but I can’t send a request using this library. I'll post screenshots with Postman, please tell me how to solve this problem.
<img width="942" alt="screenshot 2019-02-15 at 12 54 01 pm" src="https://user-images.githubusercontent.com/29518174/52842471-02131e80-3121-11e9-97e7-61269d0d93f3.png">
<img width="943" alt="screenshot 2019-02-15 at 12 54 30 pm" src="https://user-images.githubusercontent.com/29518174/52842472-02131e80-3121-11e9-9efa-8bfba6f71c85.png">

Whatever I do, I always get an error - 

> Current request is not a multipart request","path":"/gallery/. 

Please can someone write an example of how to create such a query using Dio

**Comment by wendux** [comment]
https://github.com/flutterchina/dio/blob/master/example/formdata.dart

**Comment by alyfreym** [comment]
`    Dio dio = Dio();
    FormData formData = FormData.from({
      "file":UploadFileInfo.fromBytes(utf8.encode("hello world"), "word.txt")
    });

    dio.post(APIClient().galleryUrl+path(APICatalogPaths.upload), data: formData, options: Options(
      method: "POST",
      responseType: ResponseType.JSON,
    )).then((response){

      print(response.data.toString());

    }).catchError((err){
      print((err as DioError).response.toString());
    })`

> "timestamp":"2019-02-15T16:22:36.344+0000","status":500,"error":"Internal Server Error","message":"Current request is not a multipart request"

I think the library incorrectly builds the request, because through the postman everything works, please tell me what the problem is, I specifically put the data from the example, my server would have given another error if there were not valid data.

**Comment by wendux** [comment]
Is the problem solved?


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by avinash-rath** [comment]
@alyfreym were you able to solve this issue? I am running into this issue and the server keeps throwing 500s at me. Everything works fine via postman though.
