### ISSUE TITLE
使用dio发送请求的请求体是List<String>时，无法被Spring的@RequestBody进行解析

### ISSUE THREAD

**Issue by AiHMin** [flutterchina/dio#172]
## Steps to Reproduce

使用dio发送请求的请求体是`List<String>`时，无法被Spring的`@RequestBody`进行解析
```dart
dio.post(path, data:["url"]);
```

## Logs
I/flutter (15624): dio request err: DioError [DioErrorType.RESPONSE]: Http status error [400]
I/flutter (15624): response err: {"timestamp":1550408455490,"status":400,"error":"Bad Request","message":"Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<ResultResponse<java.lang.String>> FeedbackController.removePhotos(java.util.List<java.lang.String>)","path":"/app/feedback/removePhotos"}

**Comment by wendux** [comment]
你这样传，后台期望收到的数据是什么样的？

**Comment by AiHMin** [comment]
后台希望请求体里是一个匹配 `List<String>` 类型的json
就是["string", "string", "string"]这样

**Comment by wendux** [comment]
目前只有传map时才会自动转为json, 如果是List<int>，会认为是上传的二进制数据，如果是其它类型则统一调用toString方法。 你可直接手动json.encode()一下：
```dart
dio.post(path, data:json.encode(["url"]));
```

**Comment by AiHMin** [comment]
好的，谢谢

**Comment by wendux** [comment]
追加： v2.0.12后，可以自动将数组转json了，如果要以二进制形式上传数据则必须使用stream（[点击查看示例](https://github.com/flutterchina/dio/blob/master/example/post_stream_and_bytes.dart)）
