### ISSUE TITLE
Standardizing development and release process.

### ISSUE THREAD

**Issue by pedromorgan** [flutterchina/dio#174]
I thanks @wendux who does most ..

So @wendux .. maybe.
a silent kiss = blow some air..
.
So @wendux can I please assist..
One problem is cookies..
and a few others...

We need more testing cases..
Thanks.. from

Peter Morgan
Pedro

**Comment by wendux** [comment]
Thank you for your kindness and advice. 
I'd like to hear your thoughts and receive your PR.
At present, all 2.0.x  version are pre-release version. and 2.1.0 will be the first v2 stable version. 

Considering that the 2.x has changed a lot compared to the 1.x version, I  hope users can use 2.x even though there is no v2 stable version yet.  So I publish the pre-release version to pub, and I know it's not friendly to 1.x users，but  if I don't, 1.0 users will grow more and more, which will increase the number of people who need to upgrade to 2.0 in the future. Now, I just want to release 2.1.0（stable version） as soon as possible，If there is no accident, it will be in these days.
I'm sorry to have caused you trouble. In future versions, the development process will be standardized。

If you would like to join us in maintaining this project, could you help improve the  test cases first? 
Thanks !
