### ISSUE TITLE
Dio dio = new Dio? in REAMDME.md

### ISSUE THREAD

**Issue by Hanggi** [flutterchina/dio#179]
Thank you

**Comment by wendux** [comment]
What do you mean?

**Comment by Hanggi** [comment]
The README.md file seems to be wrong, 
https://github.com/flutterchina/dio#dio-apis.

```
Dio dio = new Dio; // with default Options

// Set default configs
dio.options.baseUrl = "https://www.xx.com/api";
```

Is it right? new Dio.
Thank you.

**Comment by wendux** [comment]
Oh, yes, should be `Dio dio = new Dio()`, You are very careful！
