### ISSUE TITLE
不是https的request请求,请求时候baseUrl是空的.

### ISSUE THREAD

**Issue by DreamForStar** [flutterchina/dio#182]

**Comment by DreamForStar** [comment]
配置了RequestOption.baseUrl 但是请求失败了,
 RequestOptions _mergeOptions(
      Options opt, String url, data, Map<String, dynamic> queryParameters) {
    var query = (new Map<String, dynamic>.from(options.queryParameters ?? {}))
      ..addAll(queryParameters ?? {});
    return RequestOptions(
      method: opt.method?.toUpperCase() ?? "GET",
      headers: (new Map.from(options.headers))..addAll(opt.headers),
      baseUrl: options.baseUrl ?? "",
      path: url,
      data: data,
      connectTimeout: opt.connectTimeout ?? options.connectTimeout ?? 0,
      receiveTimeout: opt.receiveTimeout ?? options.receiveTimeout ?? 0,
      responseType:
          opt.responseType ?? options.responseType ?? ResponseType.json,
      extra: (new Map.from(options.extra))..addAll(opt.extra),
      contentType: opt.contentType ?? options.contentType ?? ContentType.json,
      validateStatus: opt.validateStatus ??
          options.validateStatus ??
          (int status) => status >= 200 && status < 300 || status == 304,
      followRedirects: opt.followRedirects ?? options.followRedirects ?? true,
      queryParameters: query,
      cookies: new List.from(options.cookies ?? [])..addAll(opt.cookies ?? []),
    );
  }
感觉这里的取值是不.

**Comment by wendux** [comment]
把你的代码贴出来


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
