### ISSUE TITLE
queryParameters和data的区别

### ISSUE THREAD

**Issue by q805699513** [flutterchina/dio#183]
你好，请问下 dio 2.0.x 版本 get 传参 ? 号后面的参数是否需要使用 queryParameters ，而使用data无效。1.0好像没有 queryParameters 这个参数，只有 data。

**Comment by wendux** [comment]
顾名思义，query参数是拼接到url问号后面的，data是在请求体里的，由于get方法没有请求体，所以只能接受query, 1.0中对get方法的data会当做query来处理，2.0标准化了参数语义，并允许所有请求都可以传query


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by q805699513** [comment]
好的

**Comment by loveuqian** [comment]
所以在封装的时候这里要判断一下，传进来的参数到底是放在 data 还是 queryParameters ？

![image](https://user-images.githubusercontent.com/9745332/59828540-d83b6400-936d-11e9-9e9d-f3a69084bc5c.png)
