### ISSUE TITLE
error download image from google doc 404

### ISSUE THREAD

**Issue by karnadii** [flutterchina/dio#184]
i don't know why all my images from google doc can't be downloaded using dio. it is a flutter issue or dio? I can open the image in browser but i can't download it with dio

## Steps to Reproduce
```dart
    try {
      await dio.download("https://i0.wp.com/lh3.googleusercontent.com/-ODy4jV0g-ZA/W4X4dgDAoNI/AAAAAAACj7g/-mKmQ7pmLN8GkFhX74sPB-d0TVrChw9CwCLcBGAs/s1600/00.jpg", "$path/0.jpg");
      print("sukses");
    } catch (e) {
      print(e);
    }
```

## Logs
```
I/flutter (26461): Downloading https://i0.wp.com/lh3.googleusercontent.com/-ODy4jV0g-ZA/W4X4dgDAoNI/AAAAAAACj7g/-mKmQ7pmLN8GkFhX74sPB-d0TVrChw9CwCLcBGAs/s1600/00.jpg in /data/user/0/com.manga.indonesia.manga.suka/app_flutter/100-man-no-inochi-no-ue-ni-ore-wa-tatteiru/100-man-no-inochi-no-ue-ni-ore-wa-tatteiru-chapter-04/0.jpg
I/flutter (26461): DioError [DioErrorType.RESPONSE]: Http status error [404]

```

**Comment by wendux** [comment]
However I can't open this image in browser:

![image](https://user-images.githubusercontent.com/20411648/53141381-d681af80-35ca-11e9-8b4a-58af8ee73b0d.png)

Which website is this image from? Perhaps the "refer" needs to be validated by server when requesting. You can set the "refer" of  request headers and try again.

**Comment by karnadii** [comment]
i try using wget with referer, and still 404, with browser private mode i can open the image with i0.wp.com, but removing it to directly and use lh3.googleusercontent.com i get 404,  this is weird. . . i think the problem is from the image source.
