### ISSUE TITLE
网络完全断开的情况下报错,NoSuchMethodError: The setter 'followRedirects=' was called on null

### ISSUE THREAD

**Issue by zhuzheng1991** [flutterchina/dio#190]
在网络完全断开的情况下,会出现报错.

最终报错的位置是在adapter.dart中的115行代码.
  request.followRedirects = options.followRedirects;

报错详情为
 *** Request ***
I/flutter (15066): uri: http://www.wanandroid.com/article/list/0/json
I/flutter (15066): method: GET
I/flutter (15066): contentType: application/json; charset=utf-8
I/flutter (15066): responseType: ResponseType.json
I/flutter (15066): followRedirects: true
I/flutter (15066): connectTimeout: 5000
I/flutter (15066): receiveTimeout: 5000
I/flutter (15066): extra: {}
I/flutter (15066): header: 
I/flutter (15066): 
I/flutter (15066): SocketException: Failed host lookup: 'www.wanandroid.com' (OS Error: No address associated with hostname, errno = 7)
I/flutter (15066): *** DioError ***:
I/flutter (15066): DioError [DioErrorType.DEFAULT]: NoSuchMethodError: The setter 'followRedirects=' was called on null.
I/flutter (15066): Receiver: null
I/flutter (15066): Tried calling: followRedirects=true#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)

**Comment by zhuzheng1991** [comment]
版本为dio: ^2.0.11

**Comment by zhuzheng1991** [comment]
切换回^1.0.13 异常消失

**Comment by wendux** [comment]
fixed in v2.0.14

**Comment by zhuzheng1991** [comment]
> fixed in v2.0.14

thanks.
