### ISSUE TITLE
怎么强制转换 text/plain 的json字符串 为 List<dynamic>

### ISSUE THREAD

**Issue by zxl777** [flutterchina/dio#191]
现在设置 dio.options.responseType = ResponseType.json; 无效，
返回的response.data.runtimeType 还是String

期望的应该是 List<dynamic>

**Comment by wendux** [comment]
如果响应头的content-type为text/plain，dio是不会自动decode的，可以手动转一下 `jsonDecode(response.data)`

**Comment by zxl777** [comment]
谢谢，加了 jsonDecode(response.data) 可以了。

但下面这句就没用了吧？
dio.transformer=new FlutterTransformer();

**Comment by wendux** [comment]
如果你请求的所有接口的json文本的content-type都是text/plain，那就没用了，你也可以在拦截器中统一decode，这样就不用每一个都decode一下；
但是，你得知道返回json时，content-type也应该是json的mime, 这样才规范，让你们后台改一下吧。
