### ISSUE TITLE
Android 网络请求报错 SocketException: Failed host lookup:

### ISSUE THREAD

**Issue by goingta** [flutterchina/dio#193]
## Steps to Reproduce

发送网络请求报错，iOS正常，Android模拟器和真机都有问题。用官方示例也是这样

Response response = await dio.post(
      "http://www.dtworkroom.com/doris/1/2.0.0/test",
      data: {"aa": "bb" * 22},
      onSendProgress: (int sent, int total) {
        print("$sent $total");
      },
    );
print("Response complete");

“Response complete”没打印，直接报错了。

## Logs

[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 6270): DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'www.dtworkroom.com' (OS Error: No address associated with hostname, errno = 7)
E/flutter ( 6270): #0      Dio._request (package:dio/src/dio.dart:643:12)
E/flutter ( 6270): <asynchronous suspension>
E/flutter ( 6270): #1      Dio.request (package:dio/src/dio.dart:552:12)
E/flutter ( 6270): <asynchronous suspension>
E/flutter ( 6270): #2      Dio.post (package:dio/src/dio.dart:109:12)
E/flutter ( 6270): #3      Server.post (package:toolchain_flutter/server/server.dart:23:35)
E/flutter ( 6270): <asynchronous suspension>
E/flutter ( 6270): #4      PGYNetwork.getList (package:toolchain_flutter/network/list.dart:12:46)
E/flutter ( 6270): <asynchronous suspension>
E/flutter ( 6270): #5      _ListPageContainerState._loadData (package:toolchain_flutter/pages/list/list.dart:197:41)
E/flutter ( 6270): <asynchronous suspension>
E/flutter ( 6270): #6      _ListPageContainerState._refresh (package:toolchain_flutter/pages/list/list.dart:190:11)
E/flutter ( 6270): <asynchronous suspension>

## Dio版本
2.0.14

**Comment by wendux** [comment]
这貌似是android设备的网络不通，你可以看看网络是否通畅，并检查一下Android APP是否在manifest.xml中申请了访问网络的权限。

**Comment by goingta** [comment]
@wendux 确实是Android网络权限的问题，搞定了。谢谢

**Comment by fantasy525** [comment]
@wendux 我也报这个错，加了访问网络的权限
```
  <uses-permission android:name="android.permission.INTERNET"/>
```
```SocketException: Failed host lookup: 'http:192.168.4.31' (OS Error: No address associated with hostname, errno = 7)```

**Comment by milaotou** [comment]
@fantasy525 我加了这段话，还是报错呢？

**Comment by idea-turtle** [comment]
> @fantasy525 我加了这段话，还是报错呢？

我也报错了 请问您的解决了吗？

**Comment by shichaohui** [comment]
我是在 debug 时正常，release 时无法访问网络，最后发现是 debug 默认添加了权限而 release 没有加。
debug 和 release 使用的是不同的 `AndroidManifest.xml` 文件。
要确保 `/android/app/src/main/` 目录下的 `AndroidManifest.xml` 中添加网络权限：
```xml
<uses-permission android:name="android.permission.INTERNET"/>
```

**Comment by zykoikaze** [comment]
请问这个问题解决了吗？我加上`<uses-permission android:name="android.permission.INTERNET"/>`这段，还是报错。

**Comment by zqy-hisense** [comment]
iOS 真机 报这个错误,安卓模拟器 正常,大家有知道原因的吗?

**Comment by mulieli** [comment]
请问 解决了吗？ 我也遇到了同样问题

**Comment by mulieli** [comment]
> 请问这个问题解决了吗？我加上`<uses-permission android:name="android.permission.INTERNET"/>`这段，还是报错。

请问你解决了吗

**Comment by HuangKai** [comment]
> iOS 真机 报这个错误,安卓模拟器 正常,大家有知道原因的吗?

我也是 iOS 调试报错

**Comment by daigewuwy** [comment]
> > iOS真机报这个错误，安卓模拟器正常，大家有知道原因的吗？
> 
> 我也是iOS调试报错

我也是啊，哥解决了没

**Comment by daigewuwy** [comment]
> > > iOS真机报这个错误，安卓模拟器正常，大家有知道原因的吗？
> > 
> > 
> > 我也是iOS调试报错
> 
> 我也是啊，哥解决了没
Android真机正常，iPhone上就不行

**Comment by zqy-hisense** [comment]
> > > iOS真机报这个错误，安卓模拟器正常，大家有知道原因的吗？
> > 
> > 
> > 我也是iOS调试报错
> 
> 我也是啊，哥解决了没
> Android真机正常，iPhone上就不行

基本上解决了
1.检查iOS是否开启网络权限(在设置中检查一下),(如果HTTP,在info中 添加 ATS)
2. 如果开启了,先关闭一下,再开启试试
3.如果1.2步都不行,把app删掉,重复1,2
我这么尝试后发现可以,但问题的本质原因还不知道

**Comment by lindan83** [comment]
如果确认添加了网络权限，仍然出现这个问题的话，建议执行一下命令：flutter clean

**Comment by sunshinenny** [comment]
可能是因为Dns的问题导致的模拟器无法联网

如果域名无法访问，试试直接用ip访问网页，如果可以访问，就说明是这个问题

解决方法自行搜索。
Mac端可以在网络设置-高级-TCP链接-Ipv6链接-改为“仅本地连接”

重启模拟器解决
