### ISSUE TITLE
How to stub the requests for tests cases

### ISSUE THREAD

**Issue by hjJunior** [flutterchina/dio#194]
At this first, I'd like to say congrats for this awesome library!
I'm looking for ways to test it, there is an way to mock the results? 

For example in http I usually do at this way on tests

```dart
      Client client = MockClient((request) async {
        return Response(json.encode(fakeResponse), 200);
      });
```

**Comment by wendux** [comment]
you can do this by custom HttpClientAdapter。 Examples:
1. [mock_adapter](https://github.com/flutterchina/dio/blob/master/package_src/test/mock_adapter.dart) (Used in [dio_test.dart](https://github.com/flutterchina/dio/blob/master/package_src/test/dio_test.dart))
2. [custom adapter demo](https://github.com/flutterchina/dio/blob/master/example/adapter.dart)

**Comment by hjJunior** [comment]
Thxs, what do u think about create a readme or wiki about tests? Maybe I can help with it
