### ISSUE TITLE
如何在拦截器的onError回调中重试请求？

### ISSUE THREAD

**Issue by jethroHuang** [flutterchina/dio#195]
我在拦截器中的onError中判断响应状态码是否为401，如果是则创建新的dio实例请求新token，然后重发之前的请求，但是我不知道怎么重发。

**Comment by wendux** [comment]
这里有一个在拦截器中检查token过期并刷新token例子，你可以参考下：https://github.com/flutterchina/dio/blob/master/example/interceptor_lock.dart

**Comment by jethroHuang** [comment]
> 这里有一个在拦截器中检查token过期并刷新token例子，你可以参考下：https://github.com/flutterchina/dio/blob/master/example/interceptor_lock.dart

我在更新token后按照示例中的那样重发请求
```
RequestOptions options = err.response.request; //千万不要调用 err.request
return dio.request(options.path,options: options);
```

遇到了一个问题，问题是重发的请求没带上原来的data和queryParameters参数。我只能手动指定，像这样
```
RequestOptions options = err.response.request; //千万不要调用 err.request
return dio.request(options.path,
    data: options.data,
    queryParameters: options.queryParameters,
    cancelToken: options.cancelToken,
    options: options,
    onReceiveProgress: options.onReceiveProgress);
```

**Comment by wendux** [comment]
2.0.22中可以直接使用第一种方法：
```
return dio.request(options.path,options: options);
```
之前的版本需要手动设置可选参数的值，也就是你的第二种写法。
