### ISSUE TITLE
BaseOptions 中 method参数无效

### ISSUE THREAD

**Issue by mimicode** [flutterchina/dio#196]
版本 v2.0.14

`    BaseOptions options = new BaseOptions(
      baseUrl: "https://github.com",
      method: "GET",
    );
    Dio dio = new Dio(options);
    Response<String> r =
        await dio.request<String>("/flutterchina/dio/issues/196");`

An Observatory debugger and profiler on MI 6 is available at: http://127.0.0.1:50775/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
I/zygote64(10723): Do partial code cache collection, code=29KB, data=20KB
I/zygote64(10723): After code cache collection, code=29KB, data=20KB
I/zygote64(10723): Increasing code cache capacity to 128KB
E/flutter (10723): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'method' was called on null.
E/flutter (10723): Receiver: null
E/flutter (10723): Tried calling: method
E/flutter (10723): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (10723): #1      Dio._mergeOptions (package:dio/src/dio.dart:895:19)
E/flutter (10723): #2      Dio._request (package:dio/src/dio.dart:681:9)
E/flutter (10723): <asynchronous suspension>
E/flutter (10723): #3      Dio.request (package:dio/src/dio.dart:613:12)
E/flutter (10723): <asynchronous suspension>
E/flutter (10723): #4      HttpUtils.name (package:demo/utils/http_utils.dart:13:19)
E/flutter (10723): <asynchronous suspension>
E/flutter (10723): #5      _HomeMainPageState._getData (package:ffxapp/ui/pages/home/home_main_page.dart:25:37)
E/flutter (10723): <asynchronous suspension>
E/flutter (10723): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (10723): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (10723): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (10723): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (10723): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (10723): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (10723): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
E/flutter (10723): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (10723): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (10723): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (10723): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (10723): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (10723): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (10723): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (10723): #20     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (10723): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter (10723):

**Comment by wendux** [comment]
2.0.16版本已修复，
