### ISSUE TITLE
Request in DioError

### ISSUE THREAD

**Issue by jhomlala** [flutterchina/dio#197]
Hi,
i'm using interceptor which has method:
```
 @override
  onError(DioError err) {
    print("Got error");
    if (err.request == null){
      print("Req is null");
    } else {
      print("Req is ok");
    }
}
```

And i'm using Dio:
`var dio = Dio();
dio.get("https://wendux.github.io/xsddddd");`

Dio sends request, but 404 happens, so onError is being invoked. DioError object always have request = null. Why Dio doesn't include Request object in DioError?

Thanks

**Comment by wendux** [comment]
fixed in v2.0.16
