### ISSUE TITLE
catchError does not expose the status and body

### ISSUE THREAD

**Issue by jasonlewicki** [flutterchina/dio#198]
>dio.post("https://local.xxxx.com/api/native/v1/login/email", data: {"email": 12, "password": "wendu"})
>    .then((response){
>      print(response);
>    })
>    .catchError((onError){      
>      print(onError);
>    });`

`print(onError);` prints:
DioError [DioErrorType.RESPONSE]: Http status error [422]

the server is sending:
status:422
message: `{errors: [{field: "email", error: "incorrect format"]}`

Do I need to regex `DioError [DioErrorType.RESPONSE]: Http status error [422]` to get 422? 
How do i get the message?

**Comment by wendux** [comment]
you can get statusCode by` DioError.response`, for example:
```dart
 dio.get("https://wendux.github.io/xsddddd").catchError((e)=>print(e.response?.statusCode));
```

**Comment by ziasultan2** [comment]
I've the same issue how can I get the body of 422 status. I'm using laravel and laravel return validation error detail with 422 status code. I need to extract the json of this return. Is there any way to do this

**Comment by marko-mlinarevic** [comment]
same here, did you get to the solution @ziasultan2

**Comment by Abror98** [comment]
same here,

**Comment by kunliu** [comment]
The body can be accessed with e.response.data
