### ISSUE TITLE
'_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by shadopanda** [flutterchina/dio#20]
So I am getting this Error on my data which is a Map. The request still completes (data changes on the server but can't get rid of this error) my code:
```
 Dio dio = new Dio();
  try {
    Response response = await dio.put(
      Uri.encodeFull(api+"/api/v1/auth/me/"), 
      options: new Options(headers: {
        "Authorization": "Token $token",
        "Content-Type": "application/json",
      }, 
      data: {
        "last_name": user.firstName,
        "first_name": user.lastName,
        "telephone": telephone,
        "send_notices": reminders.toString(),
      },
    ));

    if (response.statusCode != 400) {
      var data = json.decode(response.data);
      print(data);
      return true;
    }
  } catch (e) {
    print("Error updating UserInfo: $e");
  }

  return false;
}
```

**Comment by HappyMiao** [comment]
我也遇到这个问题了，它里面默认进行解码的，response.data['name'] 直接用即可。参照  https://github.com/flutterchina/dio/issues/3

**Comment by HappyMiao** [comment]
I also encountered this problem, the response.data['name']  has been decoded, you can use it directly, the same problem here at  https://github.com/flutterchina/dio/issues/3

**Comment by shadopanda** [comment]
Ahh I see. I thought the problem was with the data in the body of the request not the response. Thank you again for point this out. :) all works now 👍

**Comment by lyquocnam** [comment]
it's still happen when get with response is json like this:
```
{
    "message": "Please login first !"
}
```
i checked with Postman !

**Comment by wendux** [comment]
@lyquocnam  error.response.data["message "]


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by lyquocnam** [comment]
![zalo_screenshot_26_7_2018_58266](https://user-images.githubusercontent.com/8347826/43242682-592ce91e-9057-11e8-9287-b4a94d6b5d8a.png)

**Comment by spidgorny** [comment]
I had

    Response<String> response = await dio.get(url.toString());

which I copied from README.md. But Response works better without specific type.

    Response response = await dio.get(url.toString());

**Comment by md-siam** [comment]
> HappyMiao

Thanks for the help 🙂
