### ISSUE TITLE
PHP后台请求传参接收不到参

### ISSUE THREAD

**Issue by TRZhangjie** [flutterchina/dio#200]
PHP后台请求传参接收不到参数，使用postman 测试是可以的。我找PHP后台验证，他那边打印日志也是没有接收到参数。
dio: ^2.0.0

**Comment by wendux** [comment]
首先升级到最新版本，如果还有问题，请按issue模板补充复现步骤、示例代码等然后再打开本issue.

**Comment by TRZhangjie** [comment]
请求地址 http://erp.xlianba.com/Api.php?c=Approval&a=post
参数 company_id:27 user_id:204  page:0


postman和原生 日志；

```
{
  "retCode": {
    "company_id": "27",
    "user_id": "204",
    "page": "0"
  },
  "retMessage": false,
  "retData": []
}
```

Flutter 示例代码:

``
Future login(Function callback) async {

  String url = 'http://erp.xlianba.com/Api.php?c=Approval&a=post';

  Response response;
  Dio dio = new Dio();

  response = await dio.post(url,data: new FormData.from({
    "company_id": '27',
    "user_id": '204',
    "page":'0'
  }));

  print('↓↓↓↓↓↓登录信息↓↓↓↓↓↓↓');
  print(response);
  print('↑↑↑↑↑↑登录信息↑↑↑↑↑↑↑');

  callback(response);
  //var response2 = response.data['retData'];
}
```

错误日志：

```
flutter: ↓↓↓↓↓↓登录信息↓↓↓↓↓↓↓
flutter: {"retCode":[],"retMessage":false,"retData":[]}
flutter: ↑↑↑↑↑↑登录信息↑↑↑↑↑↑↑
```
