### ISSUE TITLE
php后台传参接收不到的问题

### ISSUE THREAD

**Issue by TRZhangjie** [flutterchina/dio#201]
PHP后台传参没有接收到，原生 和 Postman 请求又是可以的，请问是什么原因呢？我找了后台人员配合我排查，他说没有接收到传参。

请求地址 http://erp.xlianba.com/Api.php?c=Approval&a=post
参数 company_id:27 user_id:204  page:0

postman和原生 日志；

```
{
  "retCode": {
    "company_id": "27",
    "user_id": "204",
    "page": "0"
  },
  "retMessage": false,
  "retData": []
}
```

Flutter 示例代码:

``
Future login(Function callback) async {

  String url = 'http://erp.xlianba.com/Api.php?c=Approval&a=post';

  Response response;
  Dio dio = new Dio();

  response = await dio.post(url,data: new FormData.from({
    "company_id": '27',
    "user_id": '204',
    "page":'0'
  }));

  print('↓↓↓↓↓↓登录信息↓↓↓↓↓↓↓');
  print(response);
  print('↑↑↑↑↑↑登录信息↑↑↑↑↑↑↑');

  callback(response);
  //var response2 = response.data['retData'];
}
```

错误日志：

```
flutter: ↓↓↓↓↓↓登录信息↓↓↓↓↓↓↓
flutter: {"retCode":[],"retMessage":false,"retData":[]}
flutter: ↑↑↑↑↑↑登录信息↑↑↑↑↑↑↑
```

_Originally posted by @TRZhangjie in https://github.com/flutterchina/dio/issues/200#issuecomment-469141501_

**Comment by TRZhangjie** [comment]
前面提的 iusee 关闭了，我不知道怎么再重新打开。新提交了一个

**Comment by wendux** [comment]
那是因为你们后台参数的编码需要"application/x-www-form-urlencoded"，而默认的编码方式时json, 你可以在实例配置中设置默认编码方式，这样就不用每个请求都设置，如：
```dart
  dio.options.contentType=ContentType.parse("application/x-www-form-urlencoded");
  Response response = await dio.post("http://erp.xlianba.com/Api.php?c=Approval&a=post",
      data: {"company_id": '27', "user_id": '204', "page": '0'},
  );
  print(response);
```
日志：
```
{"retCode":{"company_id":"27","user_id":"204","page":"0"},"retMessage":false,"retData":[]}
```
