### ISSUE TITLE
Starting from version 2.0.14 it is not possible to pass multiple parameters with same name properly anymore

### ISSUE THREAD

**Issue by radzish** [flutterchina/dio#205]
Before one could pass Iterable and Dio would pass multiple parameters with the same name and with values from Iterable. Now Dio just makes toString() of iterable and passes it as value, which is not correct.

**Comment by wendux** [comment]
Please take an example.

**Comment by radzish** [comment]
Hi,

```

**Comment by wendux** [comment]
In current version, `queryParameters` are handled in the same way as jquery, but you can use `[method]Uri` API to ignore that, for example:
```dart
  dio.options.baseUrl="http://domain.com/";
  Response response = await dio.getUri(
    Uri(path: "api",queryParameters:  {
      "selectedId": ["1", "2"],
    })
  );
```

**Comment by scopendo** [comment]
Curious as to why the change was made, as it seems that the accepted way of passing multiple values for a single parameter is `selectedId=1&selectedId=2` rather than `selectedId[]=1&selectedId[]=2`.
