### ISSUE TITLE
最新版本的post没有反应请求超时

### ISSUE THREAD

**Issue by xiebao** [flutterchina/dio#206]
执行
Response response = await dio.post('/Public/Login', data: formData,options: options);
没有反应，get是可以的。不知道哪里的问题，估计是升级了flutter的原因吗？

版本信息如下：D:\flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.0.0 at D:\flutter\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at E:/Program Files/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:/Program Files/Android/SDK
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by xiebao** [comment]
1.0.17是正常的，但是高版本一点的都不行，求解

**Comment by wendux** [comment]
你有设置receiveTimeout吗？只有设置了才会生效。

**Comment by xiebao** [comment]
_dio.options.connectTimeout = 5000;
      _dio.options.receiveTimeout = 100000;
有设置的

**Comment by wendux** [comment]
太久了，你receiveTimeout设置小一点试试

**Comment by xiebao** [comment]
还是没有反应

**Comment by xiebao** [comment]
最简单的这样的代码，长时间没有反应，代码没有问题：
void _test() async{
    Dio dio = new Dio();

    dio.options.baseUrl = 'http://app.huka.com/';
    dio.options.connectTimeout = 5000;
    dio.options.receiveTimeout = 1000;
    dio.options.headers = {"access-token": 'ddd54654654d'};
    FormData formData = new FormData.from({
      "phone": "13981983532",
      "password": "983532",
    });

    Response response = await dio.post('http://app.hukabao.com/index.php/Api/Public/Login', data: formData);
    print(response.data.toString());
  }

**Comment by wendux** [comment]
我这复现不了，请按照模板填写复现步骤代码后再打开此issue.

**Comment by ginoz** [comment]
我今天更新flutter stable channel 到 1.2.1以后，发现post请求也不好用了，会返回HttpException: Connection closed while receiving data

**Comment by wendux** [comment]
你得给一个能复现的示例，否则也没法帮你了。

**Comment by ginoz** [comment]
> 你得给一个能复现的示例，否则也没法帮你了。

刚刚不知道为什么不再出现，我也不能重现。谢谢你。忽视我刚才发的那条吧。

**Comment by xiebao** [comment]
没法了a

**Comment by FerlySky** [comment]
我在2.1.0版本也遇到了同样的问题，请问您解决了嘛？

**Comment by dahuahe** [comment]
@FerlySky  和你一样 解决没有啊?

**Comment by ludawei** [comment]
出现一样的情况

**Comment by chenbo1992** [comment]
这个问题解决了吗 我也遇到同样的问题，
