### ISSUE TITLE
how to  mockito  dio request

### ISSUE THREAD

**Issue by onlychen** [flutterchina/dio#208]

**Comment by wendux** [comment]
please refer to #194

**Comment by LukaGiorgadze** [comment]
You can use [http-mock-adapter](https://pub.dev/packages/http_mock_adapter).

[Simulating HTTP request/response workflow for effective testing in Dart/Flutter via http-mock-adapter](https://lomsa.medium.com/simulating-http-request-response-workflow-for-effective-testing-in-dart-flutter-via-7d53ddb724d6)
