### ISSUE TITLE
为什么上传图片的时候不能用 相对路径？

### ISSUE THREAD

**Issue by SilenceZhou** [flutterchina/dio#209]
我的图片目录在项目主目录下面， 如果用formData4（相对路径）上传则失败， 如果是formData3(绝对路径)则成功
`  FormData formData3 = FormData.from({
      "reason": "上传图片原因",
      "idCardPositive": UploadFileInfo(File("/Users/zhouyun/Desktop/FlutterLearning/3_flutter_myself/9.3_cookiemanager_add_load_download/images/111.png"),"111.png"),
      "idCardNegative": UploadFileInfo(File("/Users/zhouyun/Desktop/FlutterLearning/3_flutter_myself/9.3_cookiemanager_add_load_download/images/2222.png"), "2222.png") });

    FormData formData4 = FormData.from({
      "reason": "上传图片原因",
      "idCardPositive": UploadFileInfo(File("../images/111.png"), "111.png"),
      "idCardNegative": UploadFileInfo(File("../images/2222.png"), "2222.png")
    });

    Response response = await dio.post(
      newUploadUserChangeCardInfo,
      data: formData3,
      options: option,
      onSendProgress: (received, total) {
        if (total != -1) {
          print((received / total * 100).toStringAsFixed(0) + "%");
        }
      },
    );
`

**Comment by wendux** [comment]
1. 肯定是你的相对路径不对，你要明白脚本运行的当前目录是啥，然后才能得出正确的相对路径，示例里面都有相对路径的示例,很容易看出程序运行的当前路径是啥
2. 其实你的问题和dio库并没有关系，而是dart File类的使用问题，用一个错误的路径当然打不开文件。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by SilenceZhou** [comment]
> 1. 肯定是你的相对路径不对，你要明白脚本运行的当前目录是啥，然后才能得出正确的相对路径
> 2. 其实你的问题和dio库并没有关系，而是dart File类的使用问题，用一个错误的路径当然打不开文件。
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

![image](https://user-images.githubusercontent.com/9305458/54406453-2d376080-4715-11e9-83c6-e6ba98ecae33.png)
你看下我的图片路劲哪里有问题了

**Comment by SilenceZhou** [comment]
用以下方式是可以 直接用file 不行
`
    /// 第五种：用UploadFileInfo.fromBytes上传图片
    ByteData img1_bytes = await rootBundle.load('images/111.png');
    ByteData img2_bytes = await rootBundle.load('images/2222.png');
    final Uint8List img1_unit8List = img1_bytes.buffer.asUint8List();
    final Uint8List img2_unit8List = img2_bytes.buffer.asUint8List();

    FormData formData5 = FormData.from({
      "reason": "上传图片原因",
      "idCardPositive": UploadFileInfo.fromBytes(img1_unit8List, "111.png"),
      "idCardNegative": UploadFileInfo.fromBytes(img2_unit8List, "2222.png")
    });
    print('=================formData5 = $formData5');
`

**Comment by SilenceZhou** [comment]
难道是相对路劲不能用这种方法：

UploadFileInfo(File("../images/111.png"), "111.png")

只能用这种： 
ByteData img1_bytes = await rootBundle.load('images/111.png');
final Uint8List img1_unit8List = img1_bytes.buffer.asUint8List();
UploadFileInfo.fromBytes(img1_unit8List, "111.png"),

**Comment by wendux** [comment]
Flutter中当然不能本地系统这样相对路径，每个APP都有自己独立的存储路径，可以通过path_provider包获取

**Comment by SilenceZhou** [comment]
path_provider只能获取沙盒路劲，没法获取我想要的文件相对路径，请问下你怎么通过 path_provider或者下面文件的相对路径：
![image](https://user-images.githubusercontent.com/9305458/56104071-af12e780-5f68-11e9-8a6c-7449f066697a.png)
