### ISSUE TITLE
get 请求怎么读取图片

### ISSUE THREAD

**Issue by 9-lives** [flutterchina/dio#210]
尝试 get 请求图片。
1. 如果使用泛型，报错；
2. 如果不使用泛型，rs 是 ResponseBody 类型，要怎么处理才能完成 flutter 显示图片？

## Steps to Reproduce
使用泛型
```dart
  testF () async {
    /// 下面一行的 Response、get后面有泛型HttpClientResponse，不知道为什么在issue里没显示
    Response<HttpClientResponse> rs = await Dio().get<HttpClientResponse>(
      'https://admin-test.shiguangkey.com/captcha.jpg',
      options: Options(
        responseType: ResponseType.stream,
      ),
    );
    print('-------result');
    print(rs);
  }
```
## Logs
type 'ResponseBody' is not a subtype of type 'HttpClientResponse'

**Comment by wendux** [comment]
2.x中`ResponseType.stream`对应的返回类型为ResponseBody， ResponseBody.stream即为响应流。
```dart
    Response<ResponseBody> rs = await Dio().get<ResponseBody>(
      'https://admin-test.shiguangkey.com/captcha.jpg',
      options: Options(
        responseType: ResponseType.stream,
      ),
    );
    print(rs.data.stream );
```

**Comment by 9-lives** [comment]
谢谢！建议更新 readme 文档。

**Comment by 9-lives** [comment]
> ```dart
>     Response<List<int>> rs = await Dio().get<List<int>>(
>       'https://admin-test.shiguangkey.com/captcha.jpg',
>       options: Options(
>         responseType: ResponseType.bytes,
>       ),
>     );
>     print(rs.data);
> ```

继续求助，用 byte 的方式得到的对象为 Response<List<int>>，怎么转换成 Uint8List 供MemoryImage 使用？

**Comment by AlexVincent525** [comment]
@wendux 你好！目前有一个需求是使用dio来获取一张图片，该图片资源在https下，由于根证书的问题**需要跳过https校验**。如何在利用dio跳过证书校验的同时，将response转为**ImageProvider**或者**Image**（**利用getImage代替NetworkImage**）？

部分代码如下：
```Dart
image: new DecorationImage(
    image: new NetworkImage(thumbImgUrl),
    fit: BoxFit.cover
)
```
```Dart
static Future<Stream> getImage(String url) async {
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
        client.badCertificateCallback =
            (X509Certificate cert, String host, int port) => true;
    };
    Response response = await dio.get(
        url,
        options: Options(responseType: ResponseType.stream)
    );
    return response.data.stream;
}
```
