### ISSUE TITLE
response headers 的 content-type 怎么修改？

### ISSUE THREAD

**Issue by 9-lives** [flutterchina/dio#214]
## Steps to Reproduce
接口通过其它库访问，请求头的 accept 字段默认设置为 application/json, text/javascript，响应头的 content-type 字段也是 application/json。

但是使用 dio 库返回的响应头 content-type 却是 text/html，导致 data 依然是 string 没有被dio 自动解析成 json。

我想像其他库一样返回application/json，让dio自动解析，怎么做？

备注：接口要求特定的请求体格式，已经写了 options.contentType = ContentType.parse("application/x-www-form-urlencoded");

**Comment by 9-lives** [comment]
请求头的 accept 属性指定为 application/json 应该可行吧，dio 库怎么手动修改accept？

**Comment by wendux** [comment]
```
dio.options.headers[HttpHeaders.acceptHeader]="application/json, text/javascript";
```
不过dio默认可以接受任何文本，一般不需要显示指定accept头，如果你们服务器判断accept头的话需要单独设置。如果设置了还不行，贴一下你的代码。

**Comment by 9-lives** [comment]
可以了，谢谢

**Comment by yypoi** [comment]
是如何解决的, 我现在也有这个困扰, 明明已经修改过响应头, 但在实际上却并不起作用
