### ISSUE TITLE
两个接口同时请求，然后都设置拦截器

### ISSUE THREAD

**Issue by 24Kshign** [flutterchina/dio#218]
dio2.x同时请求两个接口，并设置拦截器会报下面这个错，去掉一个之后就正常了，请问该如何解决呢？
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: Concurrent modification during iteration: Instance of 'Interceptors'.#0

**Comment by wendux** [comment]
拦截器是实例级的，应该只被设置一次；使用同一个实例发起不同请求即可。

**Comment by 24Kshign** [comment]
@wendux 没太理解你说的，给你看一下拦截器部分
  static changeBaseUrl(String baseUrl) {
    _dio.interceptors
        .add(InterceptorsWrapper(onRequest: (RequestOptions options) {
      options.baseUrl = baseUrl;
    }));
  }

**Comment by wendux** [comment]
意思就是dio实例就是指new 的一个dio对象；拦截器是应该在发送请求之前就设置好的，不应该在请求的同时去修改。另外：
1. 不建议动态改变baseUrl，一般一个dio实例对应一个baseUrl，如果要用该实例去发送其它域的请求可以在url参数中写完整链接,这样便会忽略baseUrl, 详情可以看example下面的示例。如：
```dart
  var dio = Dio();
  dio.options.baseUrl = "http://www.dtworkroom.com/doris/1/2.0.0/";
  // 下面使用完整域名访问会忽略baseUrl
  Response response = await dio.get("https://www.google.com/");
  print(response.data);
```
2. 如果非要动态改baseUrl，可以通过dio.options.baseUrl直接修改，没必要通过拦截器去设置。

**Comment by 24Kshign** [comment]
@wendux 好的，了解了，感谢
