### ISSUE TITLE
HttpException Failed to parse header value

### ISSUE THREAD

**Issue by 3ace** [flutterchina/dio#219]
I've encounter this error when receiving invalid login response from my api server (written using Golang + Gin with gin-jwt middleware).

It working fine when the login is successful and for other request.

## Steps to Reproduce

here's the response from the server when I'm using invalid credential to login

```
HTTP/1.1 401 Unauthorized
Content-Length: 36
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Mar 2019 05:52:12 GMT
Www-Authenticate: JWT realm=gin jwt

{
    "error": "Invalid user or password"
}
```

and here's the response when I'm using the right credential

```
HTTP/1.1 200 OK
Content-Length: 233
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Mar 2019 05:49:24 GMT

{
    "code": 200,
    "expire": "2019-03-14T12:50:24+07:00",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RlIjoiMDM5NTgxIiwiZXhwIjoxNTUyNTQyNjI0LCJpZCI6IjEwNDczIiwib3JpZ19pYXQiOjE1NTI1NDI1NjR9.0hhMBMpe9ASZC988fwTfKPfBbGvazlqniWdaboyRH1s"
}
```

Here's the sample flutter code I've used

```
static Future<bool> login(String user, String password) async {
    try {
      Response response = await Dio().post("http://localhost:8080/login", data: {
        "user": user,
        "password": password,
      });

      return true;
    } on DioError catch (e) {
      print(e);
    } catch (e) {
      print(e);
    }

    return false;
  }
```

## Logs

The only log I've received is

> flutter: DioError [DioErrorType.DEFAULT]: HttpException: Failed to parse header value

**Comment by wendux** [comment]
you can find more info with `DioError.error `.

**Comment by 3ace** [comment]
this is the value from DioError.error

```
HttpException (HttpException: Failed to parse header value)
hashCode: 985866208
runtimeType: Type (HttpException)
message: "Failed to parse header value"
uri: null
```

**Comment by wendux** [comment]
When statusCode is 401, the value of ”www-authenticate“ must be valid, "JWT realm=gin jwt" is not valid, you can use" jwt realm="gin"" instead.

**Comment by 3ace** [comment]
ah you're right. Thank you for the help

**Comment by RakaAlrian** [comment]
> When statusCode is 401, the value of ”www-authenticate“ must be valid, "JWT realm=gin jwt" is not valid, you can use" jwt realm="gin"" instead.

I got similar issue with header `WWW-Authenticate: Bearer realm="service" error="invalid_token" error_description="The access token is invalid or has expired"`. any suggestion please?

**Comment by luckv** [comment]
Seems caused by [dart-lang/sdk #46442](https://github.com/dart-lang/sdk/issues/46442)

**Comment by carlosriveroib** [comment]
any solution or workaround?

**Comment by arganaphangquestian** [comment]
> > When statusCode is 401, the value of ”www-authenticate“ must be valid, "JWT realm=gin jwt" is not valid, you can use" jwt realm="gin"" instead.
> 
> I got similar issue with header `WWW-Authenticate: Bearer realm="service" error="invalid_token" error_description="The access token is invalid or has expired"`. any suggestion please?

It's work!
Thanks sir

**Comment by arganaphangquestian** [comment]
> When statusCode is 401, the value of ”www-authenticate“ must be valid, "JWT realm=gin jwt" is not valid, you can use" jwt realm="gin"" instead.

> > When statusCode is 401, the value of ”www-authenticate“ must be valid, "JWT realm=gin jwt" is not valid, you can use" jwt realm="gin"" instead.
> 
> I got similar issue with header `WWW-Authenticate: Bearer realm="service" error="invalid_token" error_description="The access token is invalid or has expired"`. any suggestion please?

It's work!
Thanks sir

**Comment by Nei1eveN** [comment]
I'm experiencing the same error description `HttpException Failed to parse header value`, is there any workaround?
