### ISSUE TITLE
大量下载图片时部分图片损坏

### ISSUE THREAD

**Issue by creatint** [flutterchina/dio#22]
频繁调用Dio.download方法时，比如有2000个下载任务，下载的部分图片是损坏的，这是什么原因呢，有什么办法可以避免这种情况呢

**Comment by creatint** [comment]
突然发现flush设置为true之后就没问题啦，这个flush用于不用有什么区别吗

**Comment by wendux** [comment]
你的dio事哪个版本？最新版实际上已经忽略flush这个参数了。

**Comment by wendux** [comment]
请升级dio到最新版本试试 ，先关闭了，如有问题再打开
