### ISSUE TITLE
Delete请求后端无法获取传递的参数data，但是却能通过queryParams获取传递的参数

### ISSUE THREAD

**Issue by VFiee** [flutterchina/dio#223]
1.今天升级到dio到最新版本2.1.0
2.使用post请求和get请求都可以传递data参数
3.使用delete请求时，后台没有获取到data参数
4.请求正常结束，后台以没有获取到参数处理

**Comment by wendux** [comment]
按照http协议标准，delete请求一般是不能带body的（但可以带query），jdk中就是不允许的；用query就行，dio也计划在后面版本删除delete的data参数。

**Comment by VFiee** [comment]
OK，我已经处理为使用query方法了，谢谢答惑。。。。。

**Comment by VFiee** [comment]
@wendux 升级为2.1.0之后，get请求已data的方式传递参数也无法接受了，在1.x中是可以传递data参数的~

**Comment by wendux** [comment]
1.x中get方法的data内部会当做query处理，2.x中get直接传query就行


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by VFiee** [comment]
已经这样做了，建议在文档中标清，如果已标请忽略。

**Comment by lijy91** [comment]
但根据 Mozilla 的文档，DELETE Request 是允许包含 Body 的。

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

**Comment by wendux** [comment]
已放开限制，请升级到2.1.8重试。

**Comment by aboutmydreams** [comment]
想问一下现在 DELETE 还是支持 data 传参的嘛？我尝试过在 dio.delete 中传递 json 参数，无论将其放在queryParameters还是data中都没有用，如果是已经删除了这个方法 那么dio有其他什么方式可以detele传参吗
