### ISSUE TITLE
url编码问题

### ISSUE THREAD

**Issue by joker-fu** [flutterchina/dio#224]
get 请求url 如何不编码， 比如username=zhangsan,lisi  我需要保留,

**Comment by wendux** [comment]
使用getUri方法即可。

**Comment by joker-fu** [comment]
我用retrofit好像开源设置

**Comment by xiaojia21190** [comment]
YVlVilLjgecyiFXq%2FxO426Io4mOLXHavLGgcZ%2BRWdpPuurOmAu4z2zu8AfNDNBuV  像这样的如何不变吗

**Comment by xiaojia21190** [comment]
YVlVilLjgecyiFXq%2FxO426Io4mOLXHavLGgcZ%2BRWdpPuurOmAu4z2zu8AfNDNBuV 这样可以不编码吗

**Comment by stefanJi** [comment]
一般都在解码方做转码

**Comment by xiaojia21190** [comment]
燕京理工学院的纪阳吗？

**Comment by stefanJi** [comment]
> 燕京理工学院的纪阳吗？

 😂 不是
