### ISSUE TITLE
Post FormData，服务器端获取到请求的body为空

### ISSUE THREAD

**Issue by hong6234** [flutterchina/dio#225]
version: Dio v2.1.0
样例代码：
`FormData formData = FormData.from(data);`
`final response = await dio.post('/client/v1/user/info/update', data: {'name': 'test', 'file': UploadFileInfo(localAvatar, localAvatar.path)});`

PS：Dio v2.0.0没有问题

**Comment by wendux** [comment]
你这代码不对，要使用FormData，post的data参数应该是`formData`,你代码中是一个普通的map

**Comment by hong6234** [comment]
> 你这代码不对，要使用FormData，post的data参数应该是`formData`,你代码中是一个普通的map

非常抱歉，我粘贴代码的时候复制错误，其实post的data是一个formData
请再次确认，非常感谢

**Comment by wendux** [comment]
报什么错？不知道你后台怎么取得数据，'name': 'test' 这个有用吗？
