### ISSUE TITLE
 FileSystemException: Cannot open file, path = './example/book1.jpg' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by littlesalt** [flutterchina/dio#226]
使用官方的例子测试，无法下载
代码如下：
## Steps to Reproduce
  try {
      await dio.download(
        'https://cdn.jsdelivr.net/gh/flutterchina/flutter-in-action@1.0/docs/imgs/book.jpg',
            (HttpHeaders headers)=>"./example/book1.jpg",
          onReceiveProgress: (received, total) {
            if (total != -1) {
              print((received / total * 100).toStringAsFixed(0) + "%");
            }
          }
      );
    } catch (e) {
      print(e);
    }
错误提示详情：
## Logs
I/flutter (29537): FileSystemException: Cannot open file, path = './example/book1.jpg' (OS Error: No such file or directory, errno = 2)
I/HwPointEventFilter(29537): do not support AFT because of no config

**Comment by wendux** [comment]
文件路径不对，手机上应该用path_provider来获取


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by littlesalt** [comment]
是的，已解决！

**Comment by yangdong125845** [comment]
怎么解决的，求解答
  Directory tempDir = await getTemporaryDirectory();
                String tempPath = tempDir.path;
                var savePath =
                    tempPath + "/example/HBuilder.9.0.2.macosx_64.dmg";

 Future<Response> downloadChunk(url, start, end, no) async {
      progress.add(0); //progress记录每一块已接受数据的长度
      --end;
      String localUrl = savePath + "temp$no";
      return dio.download(url, localUrl, //临时文件按照块的序号命名，方便最后合并
          onReceiveProgress: createCallback(no), //创建进度回调，后面实现
          options: Options(
            headers: {"range": "bytes=$start-$end"}, // 指定请求的内容区间
          ));
    }

**Comment by yangdong125845** [comment]
我已经用了path_provider
