### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Strong-Man** [flutterchina/dio#227]
## Steps to Reproduce

     编译期间直接报错,不知道啥原因

## Logs

  日志如下:  
compiler message: file:///C:/Users/Administrator/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/dio-2.1.0/lib/src/dio.dart:392:32: Error: Getter not found: 'contentLengthHeader'.
compiler message:     lengthHeader = HttpHeaders.contentLengthHeader,
compiler message:                                ^^^^^^^^^^^^^^^^^^^

**Comment by wendux** [comment]
flutter版本多少，是否最新？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
