### ISSUE TITLE
Use custom DNS server?

### ISSUE THREAD

**Issue by hacker1024** [flutterchina/dio#228]
I think this may be a duplicate of #121 (from what I can understand through Google Translate), but I'm not sure, so I'm creating this issue.
I need to use a custom DNS server (or at least, manually specify the IP address) with dio. I can't find any way to do this at the moment.

You may think I can just use the IP address and manually set a HTTP `host` header, but this doesn't work with HTTPS, because the certificate is invalid (described in detail in #121 ).

**Comment by wendux** [comment]
Yes, it's the same issue with #121 ,  I create a issue here https://github.com/dart-lang/sdk/issues/36551

**Comment by hacker1024** [comment]
Closing as a duplicate of #121.
