### ISSUE TITLE
如何防抓包？

### ISSUE THREAD

**Issue by crazecoder** [flutterchina/dio#232]
类似okhttp的proxy(Proxy.NO_PROXY)设置，来防止代理抓包

**Comment by crazecoder** [comment]
@wendux 对于个人开发者来说，急需这个功能

**Comment by jp1017** [comment]
> https+证书校验可以防抓包

答非所问，尴尬

**Comment by wendux** [comment]
首先，如果是代理，那么肯定是可以拿到请求包的，我们能做的就是让攻击者看不到具体内容，所以，上面，我的意思是你如果用的是https并且有证书检验，代理能抓到包也是解不了密的。

**Comment by jp1017** [comment]
> 是代理，那么肯定是可以拿到请求包的

是的，作者的意思是如何不让代理，Proxy.NO_PROXY， 所以拿不到请求包，

**Comment by luojieerr** [comment]
可以换个思路，比如端对端加密什么的

**Comment by AnonAlpha** [comment]
> 首先，如果是代理，那么肯定是可以拿到请求包的，我们能做的就是让攻击者看不到具体内容，所以，上面，我的意思是你如果用的是https并且有证书检验，代理能抓到包也是解不了密的。

请问这种方式下需要使用什么代理方式呢，正向代理还是反向代理？谢谢🙂

**Comment by yuhanghate** [comment]
> 首先，如果是代理，那么肯定是可以拿到请求包的，我们能做的就是让攻击者看不到具体内容，所以，上面，我的意思是你如果用的是https并且有证书检验，代理能抓到包也是解不了密的。

绑定证书,也可以用Xposed + JustTrustMe 抓到包.hook就行了
