### ISSUE TITLE
How to upload video to AWS s3

### ISSUE THREAD

**Issue by Goolpe** [flutterchina/dio#233]
Hello, I tried this code, but received "Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [403]". 
```
 response = await Dio().put(
          linkUpload,
          options: Options(
            headers: { "conditions": [
                {"bucket": "bucketDir"},
                ["starts-with", "key", "dir/"],
                {"acl": "public-read"},
                ["starts-with", "Content-Type", "video/mp4"],
                {"x-amz-credential": "accessKeyId/20190229/ru-msk/s3/aws4_request"}
              ]
            },
          ),
          data: FormData.from({
            "file": UploadFileInfo(File(_videos[0].path), videoName),
          }),
          onSendProgress: (int sent, int total) {
            print("$sent $total");
          },
        );
```
Where and what params to pass for s3? Thank you.

**Comment by wendux** [comment]
Where is the AWS upload API doc?

**Comment by Goolpe** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/UploadInSingleOp.html
https://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html

**Comment by chengww5217** [comment]
Need signature. Please generate the signature of the S3 request. 
See [https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) to find how to sign.

**Comment by wendux** [comment]
It seems the request headers are not right. you can follow the API doc and check.

**Comment by simanlx** [comment]
> 您好，我尝试了此代码，但收到“未处理的异常：DioError [DioErrorType.RESPONSE]：Http状态错误[403]”。
> 
> ```
>  response = await Dio().put(
>           linkUpload,
>           options: Options(
>             headers: { "conditions": [
>                 {"bucket": "bucketDir"},
>                 ["starts-with", "key", "dir/"],
>                 {"acl": "public-read"},
>                 ["starts-with", "Content-Type", "video/mp4"],
>                 {"x-amz-credential": "accessKeyId/20190229/ru-msk/s3/aws4_request"}
>               ]
>             },
>           ),
>           data: FormData.from({
>             "file": UploadFileInfo(File(_videos[0].path), videoName),
>           }),
>           onSendProgress: (int sent, int total) {
>             print("$sent $total");
>           },
>         );
> ```
> 
> s3在哪里传递什么参数？谢谢。


请问您的程序做到了上传吗？
