### ISSUE TITLE
真机请求

### ISSUE THREAD

**Issue by wangchuanwen** [flutterchina/dio#235]
真机发送网络请求报错(使用公司Wi-Fi)：
SocketException: Failed host lookup: 'news-at.zhihu.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

yaml配置如下：
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.0

发送请求报错(https://blog.csdn.net/zww1984774346/article/details/84571473):
flutter: SocketException: Failed host lookup: 'blog.csdn.net' (OS Error: nodename nor servname provided, or not known, errno = 8)

**Comment by wendux** [comment]
检查一下APP有没有网络访问权限。

**Comment by aldychris** [comment]
Having this problem too, already double check, network is working but still get this exception. 

Error Message : SocketException: Failed host lookup: '{My_Host}' (OS Error: No address associated with hostname, errno = 7)

Usually after wait several minutes is working fine again... 

I'm using emulator btw

**Comment by hoya0** [comment]
我也碰到同样的问题。
请求里面包含图片base64字符串时，服务端获取提交的参数时，无法取到值。
如果把图片base64字符串去掉，也服务端可以获取到提交的参数。

**Comment by yanq** [comment]
我也遇到了同样的问题，手机端浏览器可以正常使用的网址，dio 请求报错。

**Comment by ganisback** [comment]
same issue,pls help fix which already blocked me

**Comment by yanq** [comment]
由此解决：
https://stackoverflow.com/questions/54551198/how-to-solve-socketexception-failed-host-lookup-www-xyz-com-os-error-no-ad

**Comment by ganisback** [comment]
oh, my problem already fixed. it caused by network permission closed. thanks all.
