### ISSUE TITLE
Dio post request file is too large

### ISSUE THREAD

**Issue by wangyankun33** [flutterchina/dio#237]
`Dio version:^2.0.18`
`File size:5.63M`
`Exception information`
D/mali_winsys(14682): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000

D/mali_winsys(14682): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000

W/InputMethodManager(14682): startInputReason = 1
I/flutter (14682): 错误码:DioErrorType.RESPONSE,错误信息:Http status error [500]

D/HwRTBlurUtils(14682): check blur style for HwToast-Toast, themeResId : 0x0103013f, context : io.flutter.app.FlutterApplication@32bafa4, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@52b4096

D/OpenGLRenderer(14682):   HWUI Binary is  enabled

W/ViewRootImpl[Toast](14682): EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.example.lcms) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0xb44f9ed,viewVisibility is0

W/ViewRootImpl[Toast](14682): EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.example.lcms) ( mSurfaceControllerIsValid =true) (mNativeObject  =7908182000)/@0xb44f9ed,relayoutResult is7

W/ViewRootImpl[Toast](14682): EGLdebug Surface isSurface(name=null)  (appName =com.example.lcms) ( mSurfaceControllerIsValid =true) (mNativeObject  =7908182000)/@0xb44f9ed

D/mali_winsys(14682): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000

I/zygote64(14682): Do full code cache collection, code=123KB, data=106KB

I/zygote64(14682): After code cache collection, code=115KB, data=79KB

W/libEGL  (14682): EGLNativeWindowType 0x7908182010 disconnect failed

`flutter doctor`

[√] Flutter (Channel unknown, v1.3.2-pre.13, on Microsoft Windows [Version 10.0.16299.1004], locale zh-CN)
    • Flutter version 1.3.2-pre.13 at D:\flutter
    • Framework revision f7d699525b (4 weeks ago), 2019-03-04 10:41:40 +0800
    • Engine revision a28329cb91
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidStudio\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidStudio\SDK
    • Java binary at: D:\AndroidStudio\AndroidStudio3.2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\AndroidStudio\AndroidStudio3.2
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at D:\softword\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[√] Connected device (1 available)
    • BAC AL00 • B7E5T17907002188 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by wendux** [comment]
I can't find some useful information from your logs above,  only a 500 error is not helpful. please give some detail info such as response error message, and then reopen this issue.

**Comment by xpader** [comment]
That happend on me, when upload a file, dio upload too large size to nginx, but the file is only 2.3M, and nginx set request limit is 50M, and this only happend on iOS, no problem on android.

**Comment by wangyankun33** [comment]
May need to set the file size of the server receiver!



------------------ 原始邮件 ------------------
发件人: "Pader"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 中午12:16
收件人: "flutterchina/dio"<dio@noreply.github.com>;
抄送: "小飞象"<2603109625@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [flutterchina/dio] Dio post request file is too large (#237)




That happend on me, when upload a file, dio upload too large size to nginx, but the file is only 2.3M, and nginx set request limit is 50M, and this only happend on iOS, no problem on android.
