### ISSUE TITLE
cookie_jar appears to no longer be being maintained: there should be an alternate way of managing cookies

### ISSUE THREAD

**Issue by Pebsie** [flutterchina/dio#238]
Cookie Jar hasn't been updated for over a month and no longer works according to its own documentation (the "Cookie" object no longer exists despite being essential to CookieJar's usage). An alternate way of dealing with cookies should be implemented.

**Comment by wendux** [comment]
CookieJar is still maintained, About this problem you can refer to https://github.com/flutterchina/cookie_jar/issues/12
