### ISSUE TITLE
请问如何使用http2协议的header？

### ISSUE THREAD

**Issue by xlyasdasd** [flutterchina/dio#239]
直接指定header返回FormatException: Invalid HTTP header field name: ":path"
`_dio.options.headers[':path'] = '/v1/batch'`

**Comment by wendux** [comment]
对于http2中头部压缩的字段，一般来说会由底层库来压缩，如果HttpClient(dio默认的http client)支持http2, 头部压缩也肯定会在内部，不会让用户手动指定。就像用浏览器访问一些支持http2的网站，用户访问的url是不变的。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by xlyasdasd** [comment]
> 对于http2中头部压缩的字段，一般来说会由底层库来压缩，如果HttpClient(dio默认的http client)支持http2, 头部压缩也肯定会在内部，不会让用户手动指定。就像用浏览器访问一些支持http2的网站，用户访问的url是不变的。
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

实际抓包发现，访问http2的网站是不会有头部字段压缩进来的。在dart的库里面，额外做了一个对http2的支持，但是没有直接放进HttpClient里面https://github.com/dart-lang/http2

**Comment by xlyasdasd** [comment]
可能需要针对http2额外写一个HttpAdapter
