### ISSUE TITLE
使用CookieJar时出现./cookies错误

### ISSUE THREAD

**Issue by misskter** [flutterchina/dio#241]
当我在使用CookieJar时使用PersistCookieJar(dir:  "./cookies")的时候出现很多意想不到的错误，尽管最后解决了，但是希望作者可以在readMe中加入对于这个问题的解决思路，比如使用path_provider这个插件可以放在readme中作为提示，不然后面的开发者可能需要花很多时间去解决这个错误

**Comment by luyunyu** [comment]
你好，请问是这个错误？ 是怎么解决的
Unhandled Exception: FileSystemException: Creation failed, path = './.cookies' (OS Error: Read-only file system, errno = 30)
