### ISSUE TITLE
正式签名和debug的问题

### ISSUE THREAD

**Issue by MaskEgo** [flutterchina/dio#242]
debug下运行apk，没问题
打了个realse包，出现以下错误?

I/flutter: TAG#0      Dio._makeRequest (package:dio/src/dio.dart:785)
    <asynchronous suspension>
    #1      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:704)
    #2      _rootRunUnary (dart:async/zone.dart:1132)
    #3      _CustomZone.runUnary (dart:async/zone.dart:1029)
    #4      _FutureListener.handleValue (dart:async/future_impl.dart:126)
    #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
    #6      Future._propagateToListeners (dart:async/future_impl.dart:668)
    #7      Future._complete (dart:async/future_impl.dart:473)
    #8      _SyncCompleter.complete (dart:async/future_impl.dart:51)
    #9      _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33)
    #10     _rootRun (dart:async/zone.dart:1120)
    #11     _CustomZone.run (dart:async/zone.dart:1021)
    #12     _CustomZone.runGuarded (dart:async/zone.dart:923)
    #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
    #14     _rootRun (dart:async/zone.dart:

**Comment by MaskEgo** [comment]
realse包访问不了网络

**Comment by wendux** [comment]
看看是不是设置了代理，另外检查一下网络和权限

**Comment by MaskEgo** [comment]
解决了，是打包的配置文件问题
