### ISSUE TITLE
是否支持连接池？

### ISSUE THREAD

**Issue by windrunner414** [flutterchina/dio#243]
是否支持连接池以复用连接？

**Comment by Vitaminaq** [comment]
I/ple.flutterdem(13985): ProcessProfilingInfo new_methods=323 is saved saved_to_disk=1 resolve_classes_delay=8000
I/flutter (13985): *** DioError ***:
I/flutter (13985): DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timeout[5000ms]

后台使用了node连接池，每过一段时间就会报上面的错误，很恶心。

**Comment by wendux** [comment]
这些是HttpClient内部逻辑，取决于HttpClient内部实现，如果想手动指定，可以通过HttpClientAdapter自定义HttpClient实现。
