### ISSUE TITLE
请求接口很慢

### ISSUE THREAD

**Issue by zhanglei829** [flutterchina/dio#247]
## Steps to Reproduce
直接用官方的案例，请求baidu，接口返回很慢，要3-6s才有返回，而web端没有这么慢
自己的项目也是一样的情况，同样的wifi情况下，比web端慢很多
## Logs
![image](https://user-images.githubusercontent.com/40270286/55783796-d5a4ce80-5ae1-11e9-8151-2f06ab9884d1.png)
![image](https://user-images.githubusercontent.com/40270286/55783980-2caaa380-5ae2-11e9-9bf4-946062b3c8c9.png)

**Comment by wendux** [comment]
你这是charles请求慢，请求代理到charles后，charles会去发起请求，这个时间是charles的请求时间。
