### ISSUE TITLE
Dio formdata request parse failed in rails application

### ISSUE THREAD

**Issue by 100cm** [flutterchina/dio#248]
![image](https://user-images.githubusercontent.com/12691638/55791624-81094f80-5af1-11e9-964e-9177887df846.png)
![image](https://user-images.githubusercontent.com/12691638/55791639-88305d80-5af1-11e9-86af-02e1980bf9db.png)
![image](https://user-images.githubusercontent.com/12691638/55791671-9b432d80-5af1-11e9-96a3-12990958fbc2.png)
不知道dio底层是怎么传递formdata的呢？

**Comment by 100cm** [comment]
我看了下headers 是没问题的。但是貌似rails 没有parser不识别这个格式？

**Comment by 100cm** [comment]
![image](https://user-images.githubusercontent.com/12691638/55792610-97b0a600-5af3-11e9-80bf-05269406b55f.png)
我用web的formdata 传递打印出来的rawdata 是这样的。但是dio的是空的

**Comment by 100cm** [comment]
![image](https://user-images.githubusercontent.com/12691638/55793887-8a48eb00-5af6-11e9-9da7-4d6550b19c91.png)
不知道为什么这里多了换行的

**Comment by 100cm** [comment]
像是转换成stream的时候格式有点问题？是标准的formdata格式吗。。

**Comment by wendux** [comment]
你可以抓包看看区别


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by 100cm** [comment]
找到原因了 @wendux 是因为DIO 在做formdata请求的时候没带上Content-Length 这个头，我后台PUMA 拿rawdata是以这个为标准的，所以是否可以在请求的时候自动加上这个头部？ 感谢🙏

**Comment by 100cm** [comment]
单纯的 transform-encoding 在我那边不生效。。

**Comment by 100cm** [comment]
可否加上去呢？直接关闭issue了。

**Comment by wendux** [comment]
修复了，提交后github自动关闭的，你升级到2.1.2试试，结果说一声。

**Comment by 100cm** [comment]
好的 谢谢了
