### ISSUE TITLE
当请求头是一个json字符串，无法发起请求

### ISSUE THREAD

**Issue by WindyChZh** [flutterchina/dio#249]
## Steps to Reproduce
当请求头是一个json字符串，无法发起请求，一下是log
I/flutter: DioError [DioErrorType.DEFAULT]: FormatException: Invalid HTTP header field value: "{\"device-model\":\"HUAWEINXT-AL10\",\"os-type\":\"Android\",\"idfa\":\"\",\"device-brand\":\"HUAWEI\"}"

**Comment by wendux** [comment]
报错才是正常的，header里不允许传特字符，如果非要传json可以encode一下


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by WindyChZh** [comment]
> 报错才是正常的，header里不允许传特字符，如果非要传json可以encode一下
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

json.encode后也是时好时坏，有时候生成的产物可以正常运行，有时候还是会报上面的问题

**Comment by wendux** [comment]
urlencode
