### ISSUE TITLE
Setting and sending the right content type of file.

### ISSUE THREAD

**Issue by aleksander351** [flutterchina/dio#250]
## Steps to Reproduce

I want to upload images or multiple different file types, like .pdf, .doc and .jpg

By default, the file type is mimetype: 'application/octet-stream'.
Even if I set `contentType: ContentType('image', 'jpeg')` in options, application/octet-stream gets saved as content-type.

How can I set the content type of the uploaded files automatically to the right content type.
All file upload plugins I have been using for web and mobile development, could get the right content type from the file and I did not need to set it manually.

Am I missing something?

**Comment by wendux** [comment]
```dart
 UploadFileInfo(file, fileName, contentType: ContentType('image', 'jpeg'))
```

**Comment by aleksander351** [comment]
I used `package:mime/mime.dart` to get the mime type of the file and then inserted it into UploadFileInfo, like you suggested.

**Comment by bhargavsejpalindianic** [comment]
what is content type for pdf and documents

**Comment by ASemeniuk** [comment]
> what is content type for pdf and documents

"application/pdf"

**Comment by daradonn** [comment]
For PDF I used below code, Hope it's help :)

import 'package:http_parser/src/media_type.dart';

MultipartFile.fromFile(file.path,
            filename: fileName,
            contentType:  MediaType(
                'application', 'pdf'))

**Comment by marinat** [comment]
MediaType not included in root dio.dart file in library
