### ISSUE TITLE
Sending a JSON body with GET request?

### ISSUE THREAD

**Issue by HelgeSverre** [flutterchina/dio#252]
How would I go about sending a GET request with a JSON body, have tried the following, but the server recieves and empty response (example is simplified).

```dart
main() {
  var body = {
    'auth': json.encode({
      'phone': "12312312",
    })
  };

  var response = await _client.request("/api/token",
      data: json.encode(body),
      options: Options(method: "get", contentType: ContentType.json));
}
```

**Comment by wendux** [comment]
Only "POST", "PUT", "PATCH" methods are allowed with request body, GET request just use `queryParameters`.

**Comment by Daimas** [comment]
Why this restriction? I have to deal with a server that wants the parameters in the request body and unfortunately, just because of that it means I have to use something else than Dio. It looks like a wrong design choice, as GET requests with a request body are becoming more and more popular.

**Comment by azizainunnajib** [comment]
@Daimas i think you can edit dio.dart to obtain your feature. this is my edit, i hope you can try it.

there are two place need to edit in dio.dart.
the **first part** is (you can search over the comment "Handy method .....").
change to the those part like this. (just add data in parameter in both part)
`/// Handy method to make http GET request, which is a alias of  [BaseDio.request].
  Future<Response<T>> get<T>(
    String path, {
    data,
    Map<String, dynamic> queryParameters,
    Options options,
    CancelToken cancelToken,
    ProgressCallback onReceiveProgress,
  });
` 

the **second part** is

`
/// Handy method to make http GET request, which is a alias of  [BaseDio.request].
  Future<Response<T>> get<T>(
    String path, {
    data,
    Map<String, dynamic> queryParameters,
    Options options,
    CancelToken cancelToken,
    ProgressCallback onReceiveProgress,
  }) {
    return request<T>(
      path, 
      data: data,
      queryParameters: queryParameters,
      options: checkOptions("GET", options),
      onReceiveProgress: onReceiveProgress,
      cancelToken: cancelToken,
    );
  }
`

hope it help..

**Comment by Daimas** [comment]
@azizainunnajib Thank you but actually I was already using `request(data: ...)` directly instead of `get()`, as it's the only way to pass a data parameter to a GET request. The problem is that the request body is empty, the data parameter is completely ignored.

After some digging I have found that you have to remove the second part of this `if` in dio.dart:

    if (data != null &&
        ["POST", "PUT", "PATCH", "DELETE"].contains(options.method)) {

Now it works as expected. I would really prefer if it was not deliberately restricted, especially since it's such a simple change. It's painful to have to manage a copy of the repo just to modify that line. Other clients do not have such restrictions, or have removed them since GET requests with a request body are (unfortunately) becoming popular.

**Comment by azizainunnajib** [comment]
@Daimas i had never tried it. so i dont even know my solution is working or not. and maybe not working because that `if`.
but it's really nice since you found solution of this problem.

**Comment by zie-alban** [comment]
@azizainunnajib could you please remove the second part of that if from your dio lib? It is unnecessary.

**Comment by azizainunnajib** [comment]
@zie-alban what do you mean by "my if"? I think you mention wrong account, aren't you?

**Comment by meipra** [comment]
@Daimas could you give some snippets how you do the request GET with json please? I have tried to use request(data:... , method:'GET') and my backend still says it doesn't have any body.

> @azizainunnajib Thank you but actually I was already using `request(data: ...)` directly instead of `get()`, as it's the only way to pass a data parameter to a GET request. The problem is that the request body is empty, the data parameter is completely ignored.
> 
> After some digging I have found that you have to remove the second part of this `if` in dio.dart:
> 
> ```
> if (data != null &&
>     ["POST", "PUT", "PATCH", "DELETE"].contains(options.method)) {
> ```
> 
> Now it works as expected. I would really prefer if it was not deliberately restricted, especially since it's such a simple change. It's painful to have to manage a copy of the repo just to modify that line. Other clients do not have such restrictions, or have removed them since GET requests with a request body are (unfortunately) becoming popular.

**Comment by ryanrahmans26** [comment]
The true version is body is only for POST,PUT,DELETE but because our fucking stupid back-end making creepy API that is need body with GET request, fuck... motherfucker...

**Comment by EmreKabali** [comment]
> The true version is body is only for POST,PUT,DELETE but because our fucking stupid back-end making creepy API that is need body with GET request, fuck... motherfucker...

:D

**Comment by KnucklesEQ** [comment]
@ryanrahmans26 is right, but perhaps it could be expressed in another, more concrete way :D

Using a request body is against the HTTP API Design Guidelines. Request-Bodys should only be used for POST or PUT/PATCH.

For further information: https://swagger.io/resources/articles/best-practices-in-api-design/

**Comment by tranhuycong** [comment]
Change dio.get to dio.request work for me:
```
  dio.request<dynamic>(
     'https://address',
     queryParameters: {'cn': 'iPhone_11', 'qt': '20'},
     options: Options(method: "GET"));
    }
```

**Comment by salvatoremiccio** [comment]
to correctly pass a body in a get request with dio you need to change in the dio_mixin.dart file on line 711:

`const allowPayloadMethods = ['POST', 'PUT', 'PATCH', 'DELETE'];`

adding 'GET' to the requests and making a call with the structure :

```
dio.request(
     'URL',
     data: {"KEY": "VALUE"},
     options: Options(method: "GET", contentType: "application/x-www-form-urlencoded"));
    );
```


I would like to suggest the developers to add this little fix to the library to solve this common problem.

**Comment by tomwyr** [comment]
If you reference [RFC-7231](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.1), it only discusses payloads from the semantics point of view, highlighting that doing so might be not a good practice. Since Dio is a HTTP client library and the standard doesn't restrict payloads in case of GET method, I find it an unexpected design decision to completely ignore body data for this kind of requests.

**Comment by martin-braun** [comment]
> If you reference [RFC-7231](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.1), it only discusses payloads from the semantics point of view, highlighting that doing so might be not a good practice. Since Dio is a HTTP client library and the standard doesn't restrict payloads in case of GET method, I find it an unexpected design decision to completely ignore body data for this kind of requests.

I don't care what the RFC says. If I have a large filter list (too long for the URL) and I still want to "get" information, not "post" any information, the GET verb makes absolute sense. 

Could this issue please reopened and re-addressed?
