### ISSUE TITLE
如何自定义状态码？

### ISSUE THREAD

**Issue by guodf** [flutterchina/dio#253]
## Steps to Reproduce
#19 
var dio=Dio();
dio.options.validateStatus=(int status){
return status >0;
}
dio.post()

## Logs

异常了，validateStatus并不生效

**Comment by wendux** [comment]
Http状态码都是大于0的，你可能没有搞清楚什么是http状态码，什么是API的状态码。
```javaScript
  /// `validateStatus` defines whether the request is successful for a given
  /// HTTP response status code. If `validateStatus` returns `true` ,
  /// the request will be perceived as successful; otherwise, considered as failed.
  ValidateStatus validateStatus;
```

**Comment by guodf** [comment]
明白了，我本想定义自己的业务错误码为http状态码，但dio不支持，本以为是http协议都不支持这么做，后来发现在浏览器端ajax是支持的。
最后发现大家甚少或者不推荐这么做，所以放弃了。
