### ISSUE TITLE
how to config request body size?

### ISSUE THREAD

**Issue by wwervin72** [flutterchina/dio#254]
## Steps to Reproduce

    static saveDeviceInspAnnexs (int xjDeviceResultId, List files, List urls, { Map<String, dynamic> data }) async {
    var res = await HttpUtil.netFetch(NetUrl.saveDeviceInspAnnexs(xjDeviceResultId), data ?? {
      "xjDeviceResultId": xjDeviceResultId,
      "files": files,
      "url": urls,
    }, null, Options(
      method: 'post'
    ));
    return DataResult(res.data, res.result);
  }

     annexs.forEach((deviceResultIds) {
                    List uploadAnnexList = deviceResultIds.map((annex) {
                      print('图片大小---------------------------');
                      print(File(annex['path']).lengthSync());
                      return UploadFileInfo(File(annex['path']), 'annex');
                    }).toList();
                    var json = {
                      'xjDeviceResultId': deviceResultIds[0]['xjDeviceResultId'],
                      "files": uploadAnnexList
                    };
                    _annexList.add(
                      InspTaskDao.saveDeviceInspAnnexs(json['xjDeviceResultId'], null, null, data: json)
                    );
                  });

## Logs

![image](https://user-images.githubusercontent.com/17847729/56017673-991be180-5d32-11e9-80ca-e3cb604b3a3a.png)

i use formData upload file, and server side request body size config is 100M, and my file is merely 1.14M。if file is smaller than 1M, it works.  how can i resolve my problem. please forgive my poor english, thanks.

**Comment by wendux** [comment]
你服务器对上传文件大小有限制（nginx默认是1M），可以配置一下你服务器，和客户端没关系
