### ISSUE TITLE
"content-type" gets added automatically after getting error like -> [DioErrorType.DEFAULT]: type 'int' is not a subtype of type 'String' of 'value'

### ISSUE THREAD

**Issue by divyang7777** [flutterchina/dio#255]
## Steps to Reproduce

So, on using the dio.post() method giving the data to be created and the url, i was getting the error as  

> I/flutter ( 5143): DioError [DioErrorType.DEFAULT]: type 'int' is not a subtype of type 'String' of 'value'#0      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection/runtime/libcompact_hash.dart)
I/flutter ( 5143): #1      Dio._transformData
package:dio/src/dio.dart:862
I/flutter ( 5143): <asynchronous suspension>
I/flutter ( 5143): #2      Dio._makeRequest
package:dio/src/dio.dart:725
I/flutter ( 5143): <asynchronous suspension>
I/flutter ( 5143): #3      Dio._request.<anonymous closure>.<anonymous closure>
package:dio/src/dio.dart:704
I/flutter ( 5143): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter ( 5143): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter ( 5143): #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter ( 5143): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter ( 5143): #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter ( 5143): #9      Future._complete (dart:async/future_impl.dart:473:7)
I/flutter ( 5143): #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
I/flutter ( 5143): #11     _AsyncAwaitCompleter.complete (dart:async/runtime/lib

 so i checked in my dio interceptor and found that this line 

> "content-type" -> "application/json; charset=utf-8"
 
gets added in my header on it own and the error also doesn't go ... checked with my Back-end team the model of the data and the data i send are both valid !

so, why do i get this error and why did that content-type get added and from where ?
How do i resolve this ?
![image (1)](https://user-images.githubusercontent.com/16624336/56018117-d24a5680-5d1e-11e9-9616-a9a805d9990e.jpg)
 
Thanks in advance !

**Comment by wendux** [comment]
In `BaseOptions`:
```dart 
  /// The request Content-Type. The default value is [ContentType.json].
  /// If you want to encode request body with "application/x-www-form-urlencoded",
  /// you can set `ContentType.parse("application/x-www-form-urlencoded")`, and [Dio]
  /// will automatically encode the request body.
  ContentType contentType;
```
BTY,  the header name is better to be lowercase for ignoring duplicating

**Comment by divyang7777** [comment]
thanks @wendux .. that resolved that,  but am still getting this error  

> DioError [DioErrorType.DEFAULT]: type 'int' is not a subtype of type 'String' of 'value'

could you guide me through this also ?

tryed with simple http.post() won't get me this error but dio.post() does ! what could be the reason to that ?

FIY, i am just a new beginner in this flutter world, and so will need Guidance for small things as well :D !

**Comment by wendux** [comment]
Please paste your request code.

**Comment by divyang7777** [comment]
here is the code :

> https://hastebin.com/imecisopos.coffeescript

**Comment by wendux** [comment]
`ToDoModel` class should implement `Map<String, dynamic> toJson()` method;

**Comment by divyang7777** [comment]
ya sorry, @wendux it was already implemented i didn't send it, as i thought the types were more important :laughing: 

---- here is the whole ToDoModel.dart ----
```
class ToDoModel {
  String completionDate;
  String createdAt;
  Creator creator;
  int creatorId;
  String description;
  int id;
  int status;
  String taskDate;
  String updatedAt;
  int updaterId;
  int userId;
  String uuid;

  ToDoModel(
      {this.completionDate,
      this.createdAt,
      this.creator,
      this.creatorId,
      this.description,
      this.id,
      this.status,
      this.taskDate,
      this.updatedAt,
      this.updaterId,
      this.userId,
      this.uuid});

  ToDoModel.fromJson(Map<String, dynamic> json) {
    completionDate = json['completion_date'];
    createdAt = json['created_at'];
    creator =
        json['creator'] != null ? new Creator.fromJson(json['creator']) : null;
    creatorId = json['creator_id'];
    description = json['description'];
    id = json['id'];
    status = json['status'];
    taskDate = json['task_date'];
    updatedAt = json['updated_at'];
    updaterId = json['updater_id'];
    userId = json['user_id'];
    uuid = json['uuid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['completion_date'] = this.completionDate;
    data['created_at'] = this.createdAt;
    if (this.creator != null) {
      data['creator'] = this.creator.toJson();
    }
    data['creator_id'] = this.creatorId;
    data['description'] = this.description;
    data['id'] = this.id;
    data['status'] = this.status;
    data['task_date'] = this.taskDate;
    data['updated_at'] = this.updatedAt;
    data['updater_id'] = this.updaterId;
    data['user_id'] = this.userId;
    data['uuid'] = this.uuid;
    return data;
  }
}
```

**Comment by wendux** [comment]
Could you locate the error source line?

**Comment by divyang7777** [comment]
not exactly @wendux ... this is how it looks like !?

![image (1)](https://user-images.githubusercontent.com/16624336/56333891-9fd3aa00-61b3-11e9-9b42-c0ae3c3a51ed.png)

 it says - dio.dart: 862, 725 & 704 :man_shrugging: !

**Comment by wendux** [comment]
Sorry, I couldn't reproduce this problem in my screen, could you give me an simple and completed repo to reproduce this case.  btw, paste the flutter version and Dart SDK version.

**Comment by divyang7777** [comment]
sorry, @wendux  i can't share the repo as it's company's property :man_shrugging:  ... and when i tryed with the `http.post()` it was successfull ... and with `dio.post()` i was getting this error ... all the data's keeping same ! ... so for now i am using the `http.post()` and deeply wanted to use `DIO` ... here's the verison's 

![image](https://user-images.githubusercontent.com/16624336/56339503-32804300-61cc-11e9-9121-a9946470f057.png)

**Comment by wendux** [comment]
> ```dart
> Future createToDos(ToDoModel todos) async {
>     final response = await apiHelper.postDioRequest("todo/", todos);
>     var res = json.decode(response.body);
>     return res;
> }
> ```
There are tow problems in this section code:
1. `response` is `Response` instance, and `Response` class has no "body" attribute, just use `response.data`
2. `response.data` has been decoded, you shouldn't call `json.decode` again.

**Comment by divyang7777** [comment]
yes, @wendux ... have changed it for the `http.post()` ... but this comes after i get response ... but due to this error i don't get any response :thinking: ?

**Comment by wendux** [comment]
> And , I don't ask for your source code, just expect a simple, executable demo .

Sorry, I can't do anything without   executable , reproducible code.

**Comment by saviourdog** [comment]
我的content-type也被自动设置为null了，不知道是不是dio的原因

**Comment by divyang7777** [comment]
thanks for the reply @saviourdog but i am no longer working on this project now :man_shrugging:

**Comment by norbertkross** [comment]
I have encountered this issue recently, My `Nodejs` and `Mongodb` server. The response is sent right from the server as I have tested it with postman.
Here's Postman's sample:
```
[
    {
        "_id": "60a9081ec278fcd740191f96",
        "creator": "norberta@gmail.com",
        "id": "0",
        "date-end": "",
        "date-start": "",
        "date-time": "2021-05-30 12:47:03.638",
        "people": [],
        "project-body": [
            {
                "id": "0",
                "color": "#0",
                "name": "me",
                "sub-children": [
                    {
                        "id": "0",
                        "color": "#0",
                        "state": "waiting",
                        "name": "aberor",
                        "description": "",
                        "people": [
                            {
                                "person-id": "id110",
                                "profile-pic": ""
                            }
                        ]
                    },
                    {
                        "id": "1",
                        "color": "#0",
                        "state": "waiting",
                        "name": "norbert",
                        "description": "",
                        "people": [
                            {
                                "person-id": "id110",
                                "profile-pic": ""
                            }
                        ]
                    }
                ]
            },
            {
                "id": "1",
                "color": "#0",
                "name": "for",
                "sub-children": [
                    {
                        "id": "0",
                        "color": "#0",
                        "state": "waiting",
                        "name": "this is ",
                        "description": "",
                        "people": [
                            {
                                "person-id": "id110",
                                "profile-pic": ""
                            }
                        ]
                    },
                    {
                        "id": "1",
                        "color": "#0",
                        "state": "waiting",
                        "name": "for you",
                        "description": "",
                        "people": [
                            {
                                "person-id": "id110",
                                "profile-pic": ""
                            }
                        ]
                    },
                    {
                        "id": "2",
                        "color": "#0",
                        "state": "waiting",
                        "name": "dy dx",
                        "description": "",
                        "people": [
                            {
                                "person-id": "id110",
                                "profile-pic": ""
                            }
                        ]
                    }
                ]
            }
        ],
        "project-name": "im the one "
    }
]
```

for the same this here's what DIO's `response.data` returns. It seems that the decoder in dio converted the STRING to CHARACTERS
```
[{_id: 60a9081ec278fcd740191f96, creator: norberta@gmail.com, id: 0, date-end: , date-start: , date-time: 2021-05-30 12:47:03.638, people: [], project-body: [{id: 0, color: #0, name: me, sub-children: [{id: 0, color: #0, state: waiting, name: aberor, description: , people: [{person-id: id110, profile-pic: }]}, {id: 1, color: #0, state: waiting, name: norbert, description: , people: [{person-id: id110, profile-pic: }]}]}, {id: 1, color: #0, name: for, sub-children: [{id: 0, color: #0, state: waiting, name: this is , description: , people: [{person-id: id110, profile-pic: }]}, {id: 1, color: #0, state: waiting, name: for you, description: , people: [{person-id: id110, profile-pic: }]}, {id: 2, color: #0, state: waiting, name: dy dx, description: , people: [{person-id: id110, profile-pic: }]}]}], project-name: im the one }]
```

**STRANGE**
