### ISSUE TITLE
Http status error 403 when using local network url

### ISSUE THREAD

**Issue by AlejandroC90** [flutterchina/dio#256]
## Steps to Reproduce
I have this simple code:

`import 'package:dio/dio.dart';`
`String rutaBase = "http://192.168.1.16:8080";`

`void probarInternet() async{`
  `   var respuesta = await Dio().get(rutaBase);`
   `  print(respuesta.data.toString());`
`}`

Which tries to load a simple page from a server in my local network.
I can access the page from my browser and also the **package http works flawlessly**
## Logs

`E/flutter (12655): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError``[DioErrorType.RESPONSE]: Http status error [403]`
`E/flutter (12655): #0      Dio._makeRequest package:dio/src/dio.dart:791`
`E/flutter (12655): <asynchronous suspension>`
`E/flutter (12655): #1      Dio._request.<anonymous closure>.<anonymous closure>`
`package:dio/src/dio.dart:707`

But with Dio I get an status error 403, is there something I missed? Thanks

**Comment by wendux** [comment]
Could you compare the request headers  of http package and Dio with network debuger(like Charles)?
