### ISSUE TITLE
Filename from URL.

### ISSUE THREAD

**Issue by krypticallusion** [flutterchina/dio#258]
is there anyway to get the filename from content-disposition headers aside from specifying a filename?

**Comment by wendux** [comment]
![image](https://user-images.githubusercontent.com/20411648/56214323-3dce5400-6090-11e9-8bb3-3c7dcfca0874.png)

```dart
 await dio.download(
      url,
      (HttpHeaders headers){
        // parse `content-disposition ` here
        return "$filename"
      },
    );
```

**Comment by krypticallusion** [comment]
Thanks!
