### ISSUE TITLE
升级dio到2.1.0后，报错：Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

### ISSUE THREAD

**Issue by linfeizhang** [flutterchina/dio#259]
## Steps to Reproduce

我想获取下载进度，所以我将dio升级到2.1.0版本了，然后在androidStutio上运行就报了这个错误，我查资料说是Androidx的影响，可是我的项目没有用androidx，请问这个要怎么修改啊？

## Logs
![image](https://user-images.githubusercontent.com/17806686/56112736-86054d80-5f8e-11e9-9d44-aec96e97573d.png)

**Comment by wendux** [comment]
和dio不相关，关闭了
