### ISSUE TITLE
https 证书报错

### ISSUE THREAD

**Issue by davewang** [flutterchina/dio#261]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error: 
E/flutter (19832): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))
E/flutter (19832): #0      Dio._makeRequest (package:dio/src/dio.dart:757:16)
E/flutter (19832): <asynchronous suspension>
E/flutter (19832): #1      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:697:22)
```

服务器证书是有效的。
![image](https://user-images.githubusercontent.com/555195/56267161-9f3e0380-6120-11e9-8b90-48d07086d6dc.png)

**Comment by Nealyang** [comment]
> ```
> [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error: 
> E/flutter (19832): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))
> E/flutter (19832): #0      Dio._makeRequest (package:dio/src/dio.dart:757:16)
> E/flutter (19832): <asynchronous suspension>
> E/flutter (19832): #1      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:697:22)
> ```
> 
> 服务器证书是有效的。
> ![image](https://user-images.githubusercontent.com/555195/56267161-9f3e0380-6120-11e9-8b90-48d07086d6dc.png)

请问你这个问题解决了么？

**Comment by huluxia** [comment]
球童，请问解决了吗。一样卡在这里，郁闷了


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
