### ISSUE TITLE
formdata 对 List<Map> 的序列化结果是怎么样的

### ISSUE THREAD

**Issue by 100cm** [flutterchina/dio#264]
我有这样一个参数 `Formdata.from({"key[]": [{"key": value}]})`

我后台期待收到的也是 `[{},{} ]`

实际上 我后台收到的是` ["{xx:xx}"]` 不知道为什么我后台把这部分Map当作字符串了？请问下是什么原因？

**Comment by 100cm** [comment]
貌似Map 不支持重复的key

并且formdata 不会转换成 key[][object_key]的形式放入到formdata name里去 这个要怎么办？

**Comment by 100cm** [comment]
![image](https://user-images.githubusercontent.com/12691638/56347441-d7177a80-61f6-11e9-922c-272f06ecc57a.png)
这里貌似把map 一并打成了 text_field 这样是不对的。。

**Comment by 100cm** [comment]
好吧 我直接把代码clone自己重写了。。formdata部分的坑实在是太多。

![image](https://user-images.githubusercontent.com/12691638/56353980-45fbd000-6205-11e9-9599-753239c2747f.png)


需要考虑嵌套Map的情况，转换成stream的时候。

**Comment by wendux** [comment]
修改好后，欢迎提个pr(ps:别忘了在test.dart 中添加一个测试用例)
