### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [302]

### ISSUE THREAD

**Issue by ghozay19** [flutterchina/dio#265]
hi !

when im using dio post,
the post was successfull and the data was saved on the db.

but i check the logs, and got error code 

> DioError [DioErrorType.RESPONSE]: Http status error [302]

here's my code

```
_submit() async {    
var url =
        "https://script.google.com/macros/s/AKfycbyZMw-4aNli_vfIucxNxAZvIfWOtWlQEBST8EtDh4zGcDnEHCA7/exec?";

    try {
      var dio = new Dio();
      var response = await dio.post(
        url,
        queryParameters: {
          'action': 'insert',
          'tableName': 'presensi',
          'nis': nis,
          'nama': nama,
          'status': status
        },
        options: Options(
          connectTimeout: 5000,
          receiveTimeout: 10000,
        ),
      );

      print(response.toString());
    } on DioError catch (error) {
      if (error.response.statusCode == 302) {
        print("nani kore ? : " + error.toString());
      }
    }
```

note :
post was success but logs show 302.
how to resolve 302 code?

**Comment by zaubererty** [comment]
302 is the status code for a redirect.
I face the kind a same issue. My POST request to log in is awnserd with a 302 response. But i'm not sure wether the responded cockie is saved to the cockie jar. 
The followup requests fail cause the cockie is not present.

**Comment by lyj0309** [comment]
# i have a same question too

**Comment by 2x2xplz** [comment]
I have the same concern as @zaubererty regarding cookies. Dio makes a `POST` request and receives a `302` response with a `Set-Cookie` header. However the redirected request does not appear to include the new cookie. I'm using the default CookieJar plugin with a `PersistentCookieJar`.

**Comment by alfawzaan** [comment]
Add followRedirects: false and validateStatus: (status) { return status < 500;} to the request

var response = await Dio().post("http://myurl",
    data: requestBody,
    options: Options(
        followRedirects: false,
        validateStatus: (status) { return status < 500; }
    ),
);

Source [](https://stackoverflow.com/questions/52537500/flutter-handle-status-code-302-in-post-request)

**Comment by 2x2xplz** [comment]
Thanks @alfawzaan   
I'd suggest `return status < 400;` , as you probably want `404 not found` , `401 unauthorized` , etc to still raise errors. Also keep in mind if you aren't following redirects you'll need a manual way to send Dio to the relocated page, perhaps by reading the Location header

**Comment by josephantonyk94** [comment]
add header with 
`"Accept":"application/json"` . henceforth it will only return json data otherwise it will prompt to redirect with html url, default dio configuration does not have response type so you have to mention it in header.

**Comment by jiashaoying** [comment]
use dio.request can solve this problem

**Comment by lucasromeiroTF** [comment]
> use dio.request can solve this problem

Hello, how did you do this?
I always get 400 error if I use dio.request.
Could you give me an example?

**Comment by emondd4** [comment]
Did Someone Finally Found the solution?

tried all the possible way that mentioned earlier but not working.

**Comment by gouravgarhwal** [comment]
@emondd4 
I have solved the error. 
im facing same issue in the code 
just use

        ```
final redirectUrl = response.headers.value("location");
        final redirectedResponse = await dio.get(redirectUrl!);
        print("Redirected response data: ${redirectedResponse.data}");
```

your api data will be recived on

` redirectedResponse.data`
