### ISSUE TITLE
Any way to pause a download?

### ISSUE THREAD

**Issue by krypticallusion** [flutterchina/dio#267]
Is there any way to pause an ongoing download? Much appreciated!

I'm using dio.download.

**Comment by wendux** [comment]
Not support directly, but you can implement this by  http "range" header, May [download_with_trunks](https://github.com/flutterchina/dio/blob/master/example/download_with_trunks.dart) example will help。

**Comment by krypticallusion** [comment]
Not a problem, I found my solution. Closing.

**Comment by soone** [comment]
> Not a problem, I found my solution. Closing.

Hello, could you tell me how you solved your problem?

**Comment by kareemX** [comment]
> Not a problem, I found my solution. Closing.

What is the solution please?

**Comment by krypticallusion** [comment]
> > Not a problem, I found my solution. Closing.
> 
> What is the solution please?

Sorry for the late reply, but I just cancel the download, and then start a new download with Range header function.

**Comment by Success-Technology** [comment]
It can simply done with Flowder package. Too much simple for me.
