### ISSUE TITLE
Is it possible to download multiple files simultaneously?

### ISSUE THREAD

**Issue by anticafe** [flutterchina/dio#268]
Thank you for such great library. I'm using Dio in a demo project of showing and downloading files. It works great and saves me a lot of times in comparison to write both native Android and iOS app.

However, I wonder can we download multiple files simultaneously with Dio? Or I must wait for the first download done before starting the second one? If possible, a small mode would be very helpful.

**Comment by wendux** [comment]
you can use `Future.wait([dio.download(...),dio.download(...)])` ;

**Comment by HabibuGodo** [comment]
how if I need to download multiple dynamic files?

**Comment by ajonno** [comment]
we have same use case - the multiple download URL's, are not known until during runtime. Can this be accommodated by Dio ?

**Comment by aniketsongara** [comment]
You can download multiple files using `flutter_downloader` [here](https://pub.dartlang.org/packages/flutter_downloader)
