### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by fyzs-n9001** [flutterchina/dio#27]
DioError [DioErrorType.DEFAULT]: FormatException: Unexpected character (at character 1)

**Comment by fyzs-n9001** [comment]
请求是成功的, 服务端返回的是一个Base64编码的字符串

**Comment by wendux** [comment]
请贴出错误栈及触发的源码

**Comment by fyzs-n9001** [comment]
随便弄个get接口,然后返回一个base64的字符串不就行了吗,你这个库里默认做了json格式校验吧

**Comment by wendux** [comment]
只有当返回头content-type指明为json时默认才会自动转换，如果你不想以让自动转换，可以指定接收的responseType， 文档里都有。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by akindone** [comment]
when api is 500, content-type is text/html and using default responseType will cause same error @wendux

**Comment by castrojr913** [comment]
I have a similar issue when field name has a camelCase format. For instance:

`  FormData.from({
"loginData": jsonEncode({
          "phone": phoneNumber,
          "zipcode": zipCode,
          "device_id": deviceId,
          "os_id": osId,
        }
})
`
It throws `FormatException: Unexpected character`. However, if I replace `loginData` by `logindata`, It works. I use PostMan, It works the request with `loginData`.

**Comment by gideonpeters** [comment]
I had this issue and turns out I was already decoding json in my base options and tried decoding it again in my logic to handle the response data. Like this:

```
BaseOptions options = new BaseOptions(
    contentType: ContentType.json.toString(),
    responseType: ResponseType.json,
    followRedirects: false,
    validateStatus: (status) {
      return status < 500;
    },
  );
```
and I was still trying to decode it here
`return jsonDecode(response.data);`

instead of just 
`return response.data;`

**Comment by riskiadi** [comment]
better use http :p
