### ISSUE TITLE
Not able to retrieve total size.

### ISSUE THREAD

**Issue by krypticallusion** [flutterchina/dio#270]
A Google drive link like [this](https://doc-14-38-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/f6uma7vvmv9r8ns7jvq8mlc6b5rda494/1556035200000/12149260036516767827/*/1qk1wdTafKRmq7Iz4mACOtiz_xEaOEfXi?e=download) when processed by dio.Download() doesn't send the total size and is been marked as -0.00mB

**Comment by wendux** [comment]
The [url](https://doc-14-38-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/f6uma7vvmv9r8ns7jvq8mlc6b5rda494/1556035200000/12149260036516767827/*/1qk1wdTafKRmq7Iz4mACOtiz_xEaOEfXi?e=download) you given responded with 403.

**Comment by d-apps** [comment]
@wendux Could you please try with this url: https://drive.google.com/uc?export=download&id=1N8D8lx1HlW0X99wovGEQxZRUtewN6-J2

I have this problem with my app, I almost opened a new issue with the same problem, Actually I opened a question on StackOverFlow: https://stackoverflow.com/questions/56133492/flutter-how-to-show-the-correct-progress-when-downloading-a-google-drive-direc

**Comment by d-apps** [comment]
Does dio can retrieve total size from Google Drives links?

**Comment by krypticallusion** [comment]
> Does dio can retrieve total size from Google Drives links?

Set a `range` header, solves the issue.
