### ISSUE TITLE
How about  install a github stale on dio repo

### ISSUE THREAD

**Issue by Insofan** [flutterchina/dio#275]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | all                     |      |
| Platform Version               |all         |      |
| Dio Version                    | all    |      |

### Issue Description and Steps
[Stale](https://github.com/apps/stale), a github bot to closes abandoned issues after a period of inactivity, and it can be refresh by a comment. After install it I'll help you write the stale.yml.

**Comment by wendux** [comment]
Well, I have installed stale. thanks

**Comment by Insofan** [comment]
> Well, I have installed stale. thanks

I have added your wechat account, but no reply :sob:

**Comment by wendux** [comment]
没有备注吧，重加一次吧（Demons-du）
