### ISSUE TITLE
How to add NetworkInterceptor

### ISSUE THREAD

**Issue by ykrank** [flutterchina/dio#276]
I want callback at every redirect, like NetworkInterceptor in OkHttp of java. but now http client only provide callback of last true link, how could i cancel request if server redirect to some unique host

**Comment by carmas123** [comment]
See it: https://github.com/flutterchina/dio/blob/master/README.md#interceptors

**Comment by ykrank** [comment]
Set followRedirects = false, but nothing happen

**Comment by ykrank** [comment]
At last, set followRedirects = false, judge and change request on error solve my problem.
