### ISSUE TITLE
Cancel while still keeping the file.

### ISSUE THREAD

**Issue by krypticallusion** [flutterchina/dio#278]
Is there anyway to cancel a file while still keeping the part that's downloaded? Thanks!

**Comment by wendux** [comment]
you can do this by implementing another method by yourself, Copy the source code of `dio.download` method, and then comment the follow line :
https://github.com/flutterchina/dio/blob/947e88040551178a571c91588665a5f578ee4b49/package_src/lib/src/dio.dart#L516

**Comment by krypticallusion** [comment]
> you can do this by implementing another method by yourself, Copy the source code of `dio.download` method, and then comment the follow line :
> 
> https://github.com/flutterchina/dio/blob/947e88040551178a571c91588665a5f578ee4b49/package_src/lib/src/dio.dart#L516

this does not look feasible.
