### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Only valid value is 0: 1#0 怎么解决

### ISSUE THREAD

**Issue by xy221150** [flutterchina/dio#280]
I/flutter (14785): 请求出错：DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Only valid value is 0: 1#0      List.[] (dart:core/runtime/libgrowable_array.dart:145:60)
I/flutter (14785): #1      RequestOptions.uri (package:dio/src/options.dart:217:29)
I/flutter (14785): #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapter.dart:100:67)
I/flutter (14785): <asynchronous suspension>
I/flutter (14785): #3      Dio._makeRequest (package:dio/src/dio.dart:732:46)
I/flutter (14785): <asynchronous suspension>
I/flutter (14785): #4      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:707:22)
I/flutter (14785): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (14785): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (14785): #7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter (14785): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter (14785): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter (14785): #10     Future._complete (dart:async/future_impl.dart:473:7)
I/flutter (14785): #11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
I/flutter (14785): #12     _AsyncAwait

**Comment by wendux** [comment]
请按Issue模板补充信息后再打开。

**Comment by Q14** [comment]
+1  怎么解决

**Comment by pheromone** [comment]
+10086

**Comment by dxjdqc** [comment]
有解决的大佬吗，出现了同样的问题

**Comment by pheromone** [comment]
@dxjdqc 
加上     

dio.options.contentType =
        ContentType.parse("application/x-www-form-urlencoded");

**Comment by dxjdqc** [comment]
> @dxjdqc
> 加上
> 
> dio.options.contentType = 
> ContentType.parse（“application / x-www-form-urlencoded”）;
加了不管用啊

**Comment by Zhengyi66** [comment]
我也遇到过，我的是url路径有问题   https://blog.csdn.net/sjdjdjdjahd/article/details/101438885

**Comment by Zhengyi66** [comment]
检查下url路径是否完整 https://blog.csdn.net/sjdjdjdjahd/article/details/101438885

**Comment by dxjdqc** [comment]
> 检查下url路径是否完整 https://blog.csdn.net/sjdjdjdjahd/article/details/101438885
是url问题

**Comment by zinwalin** [comment]
> 检查下url路径是否完整 https://blog.csdn.net/sjdjdjdjahd/article/details/101438885

我碰到的问题是因为　url前面没有https://

**Comment by xiaoai7904** [comment]
检查一下url地址是否带有http://或者https://
