### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [429]

### ISSUE THREAD

**Issue by omeryyildirim** [flutterchina/dio#282]
hi.
why this error give me 

Is there a solution?

`try {
      
      for (var i = 0; i <= 603; i++) {

        sleep(const Duration(seconds: 1));

        response = await dio.download(
            "http://api.alquran.cloud/v1/page/${i + 1}/tr.bulac",
            "${dir.path}/page${i + 1}.json",
            options: Options(
          //connectTimeout: 10000,
          receiveTimeout: 10000,
        ),
            onReceiveProgress: (rec, total) {
          print("Rec: $rec , Total: $total");
          setState(() {
            indirilen = i + 1;
            progressString = (rec / total * 100).toStringAsFixed(0) + "%";
          });
        });
      }
      
    } catch (e) {
      print(e);
    }
    `

**Comment by wendux** [comment]
429 Too Many Requests. It seems to be the sever safety policy.

**Comment by omeryyildirim** [comment]
> 429 Too Many Requests. It seems to be the sever safety policy.


yes I know. but is there a solution to this problem?

**Comment by wendux** [comment]
Sorry, It's not about dio. I think it shouldn't be discussed here.
