### ISSUE TITLE
Instance of 'RequestOptions' or FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by Young-Ken** [flutterchina/dio#283]
### Issue Info
I/flutter (31357): ----dio-boundary-2382299047
I/flutter (31357): Content-Disposition: form-data; name="latitude"
I/flutter (31357): 
I/flutter (31357): 1
I/flutter (31357): ----dio-boundary-2382299047
I/flutter (31357): Content-Disposition: form-data; name="longitude"
I/flutter (31357): 
I/flutter (31357): 1
I/flutter (31357): ----dio-boundary-2382299047
I/flutter (31357): Content-Disposition: form-data; name="address"
I/flutter (31357): 
I/flutter (31357): 北京朝阳区
I/flutter (31357): ----dio-boundary-2382299047
I/flutter (31357): Content-Disposition: form-data; name="image"; filename="pig.jpg"
I/flutter (31357): Content-Type: image/jpeg
I/flutter (31357): 
I/flutter (31357): ���ᕴExif
I/flutter (31357): Instance of 'RequestOptions'
I/flutter (31357): FormatException: Unexpected character (at character 1)
I/flutter (31357): Internal Server Error:
I/flutter (31357): ^

**Comment by wendux** [comment]
请按模板补充完信息后再打开
