### ISSUE TITLE
DIO拦截器中，如何打开弹窗呢？

### ISSUE THREAD

**Issue by HannibalKcc** [flutterchina/dio#285]
这或许不是dio本身的问题，但我还是希望能获得一些帮助，谢谢
## 场景：
想要在请求未完成时想要设置一个loading弹窗。但是希望是在拦截器经行全局的设置，而不是某个路由都单独设置。

此时考虑会使用拦截器完成这个任务
```
dio.interceptors.add(
    InterceptorsWrapper(
      onRequest: (RequestOptions options) {
        // showdialog 但是没有context
      },
      onResponse: (Response response) {
        // closedialog
      }，
   )
}
```

请问如何获取context？ 或者说采取什么别的方法实现所需场景？

**Comment by 100cm** [comment]
你可以在build 中把context 存储到全局变量里

**Comment by wendux** [comment]
```dart
// 请求时将context添加到extra中
dio.get(url,options:Options(extra: {"context": context}));
...
// 你可以在拦截器中通过 options.extra["context"]取到Context
```

**Comment by HannibalKcc** [comment]
> 你可以在build 中把context 存储到全局变量里

恩，你这个方法我下午想到了，在经过几次尝试后发现好像不太可行。

## 还原

1. 在 main.dart 中编写 MyApp （即顶级 widget），build 方法中 设置 Application.rootContext = context
2.设置 dio 拦截器中的 onResponse 加入
```
showDialog(
          context: Application.rootContext,
          builder: (_) {
           // xxxxxxxxxx
         }
}
```

#错误信息(部分)

```
E/flutter (26120): MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
E/flutter (26120): Localizations are used to generate many different messages, labels,and abbreviations which are used by the material library. 
E/flutter (26120): To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
E/flutter (26120): The specific widget that could not find a MaterialLocalizations ancestor was:
```

**Comment by HannibalKcc** [comment]
> ```dart
> // 请求时将context添加到extra中
> dio.get(url,options:Options(extra: {"context": context}));
> ...
> // 你可以在拦截器中通过 options.extra["context"]取到Context
> ```

感谢，这个方法可用。虽然每次dio请求必须显式地携带context。

也许flutter可以在某个地方方便地获取当前组件的context。（或许只是我还不知道）

**Comment by lvyandev** [comment]
大佬们，前面的讨论解决了我目前碰到的问题

但是还有个小问题想请教一下
```
_dio.interceptors
        ..add(InterceptorsWrapper(
          onRequest: (RequestOptions options) {
            WidgetsBinding.instance.addPostFrameCallback((_) {
              showDialog<Widget>(
                  context: options.extra['context'],
                  // 如果不加，点击外部导致dialog消失，在请求完成后会pop掉本来的界面
                  barrierDismissible: false,
                  builder: (context) => Container(child: Center(child: CircularProgressIndicator())));
            });
            return options;
          },
          onResponse: (Response response) {
            Navigator.pop(response.request.extra['context']);
            return response;
          },
          onError: (DioError error) {
            Navigator.pop(error.request.extra['context']);
            return error;
          },
        ))
```
有没有办法在onResponse和onError时候安全的dismiss掉dialog

**Comment by HannibalKcc** [comment]
> 大佬们，前面的讨论解决了我目前碰到的问题
> 
> 但是还有个小问题想请教一下
> 
> ```
> _dio.interceptors
>         ..add(InterceptorsWrapper(
>           onRequest: (RequestOptions options) {
>             WidgetsBinding.instance.addPostFrameCallback((_) {
>               showDialog<Widget>(
>                   context: options.extra['context'],
>                   // 如果不加，点击外部导致dialog消失，在请求完成后会pop掉本来的界面
>                   barrierDismissible: false,
>                   builder: (context) => Container(child: Center(child: CircularProgressIndicator())));
>             });
>             return options;
>           },
>           onResponse: (Response response) {
>             Navigator.pop(response.request.extra['context']);
>             return response;
>           },
>           onError: (DioError error) {
>             Navigator.pop(error.request.extra['context']);
>             return error;
>           },
>         ))
> ```
> 
> 有没有办法在onResponse和onError时候安全的dismiss掉dialog

其实我后面并没有使用 extra 携带 context，我的解决方案是使用 overlay 代替 dialog。
你可以参看一下 okToast ，这样就不用考虑 context 与 dialog的问题了

**Comment by lvyandev** [comment]
好的，多谢

**Comment by yannanna0920** [comment]
如果在拦截器里面想使用跳转 只能使用 extra 携带 context  使得拦截方法里面可以使用 NavigatorUtils.push(context, '路径')吗  还有其他办法吗 我的目的是希望在拦截401 状态处理完逻辑 之后想要刷新当前页面

**Comment by HannibalKcc** [comment]
> 如果在拦截器里面想使用跳转 只能使用 extra 携带 context 使得拦截方法里面可以使用 NavigatorUtils.push(context, '路径')吗 还有其他办法吗 我的目的是希望在拦截401 状态处理完逻辑 之后想要刷新当前页面

这个问题好久啦，说一下我的解决方案。

其实只要把 context 全局化就好了，阅读 `Navigator.push() ` 的源码就知道它需要 context 来寻根 Navigator 实例，所以只要给一个在根 Navivgator 实例下的 context 就可以了。

给你的 `MaterialApp.navigatorKey` 赋值一个全局变量 `Application.navKey`，然后调用 `Application.navKey.currentState.push()` 就可以了。
