### ISSUE TITLE
json的解码通过compute方法在后台进行 巨慢

### ISSUE THREAD

**Issue by summer789** [flutterchina/dio#287]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | ios                 |      |
| Platform Version               | 1.5.4                             |      |
| Dio Version                    | 2.1.0                        |      |
|  Xcode Version |  Xcode 10.1           |      |

### Issue Description and Steps

按照文档提示使用，导致接口返回巨慢无比（真机正常），删除此配置后恢复正常
![63C7D7A1-A2AD-4CAF-A369-5DD4D7AC21DA](https://user-images.githubusercontent.com/20252366/57432461-8aa8e300-7268-11e9-94d9-9b454f69a5e1.png)
以下为代码实现
![E1D79C7E-2AA4-46E8-8272-A77BD507DA55](https://user-images.githubusercontent.com/20252366/57432549-c5128000-7268-11e9-987a-3ab5a713d500.png)
![18EEBF53-274C-4895-9FA6-5BCF57BEB8D2](https://user-images.githubusercontent.com/20252366/57432596-e2dfe500-7268-11e9-95d1-ac0ccc4a48e1.png)

以下为抓包的时间线
![屏幕快照 2019-05-09 上午10 46 09](https://user-images.githubusercontent.com/20252366/57432677-102c9300-7269-11e9-8197-647f9b4fc9e5.png)

以下为版本信息
![E9642067-5875-4CC5-8B1C-464F8BF66C36](https://user-images.githubusercontent.com/20252366/57432695-1c185500-7269-11e9-9b84-ab6821ad4e04.png)

**Comment by wendux** [comment]
compute方法确实有时会非常慢，这个可以去flutter 提issue


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
