### ISSUE TITLE
请求本地host出现Invalid header field name

### ISSUE THREAD

**Issue by Foronia** [flutterchina/dio#288]
DioError [DioErrorType.DEFAULT]: HttpException: Invalid header field name, uri = http://192.168.2.200:8088/api/

**Comment by wendux** [comment]
请按issue 模板补充信息后再打开。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by badrobot15** [comment]
Receiving same error. Server seems to be getting the request but app crashes
