### ISSUE TITLE
@wendux 关啥评论了？心虚了吧

### ISSUE THREAD

**Issue by jaggerwang** [flutterchina/dio#29]
你把 Issue #28 关闭了评论别人就没地儿说了？既然说都头头是道，那就不要怕别人反驳阿。

1. 代码里总共就出现两处 `response.data`，一处还是通过 `interceptor` 打日志，相信你作为一个项目开发者应该能够看得懂吧。 
1. 我贴出的就是已经裁剪后的代码，也通过 VSCode 的 debug 功能调试过，在调试器里一展开 `response` 变量就报异常，并不是没有自己分析过，另外这个代码量在 GitHub 的 Issue 里并不算长。
1. 我反感的是你的态度，如果有描述不清楚的，指明之后我定会补充。
1. 别把国人搬出来为你挡箭，我也不是瞎说，是之前提了那么多 Issue 的感受，国人对开源项目的态度和敬业精神至少在目前来说跟老外还是有差距。

**Comment by wendux** [comment]
我再说一遍，对于你这种直接复制大量代码，不作注释，并且也没有将自己调试结果等信息贴出的行为，我认为是浪费别人时间，你指望看你issue的人用眼睛把你的代码从头执行一遍？即使这样我也看了你的问题，在栈中也没找到dio相关错误，让你补充信息，你倒向大爷似的，嫌别人态度不好，关闭issue是不想理你，也不想让大家起哄，还有，就事论事是一个理性人该有的素养，你在我们开源项目下抱怨国人态度不好，貌似全世界都欠你的，现在还另起issue来喷，也只能block了你，惹不起
