### ISSUE TITLE
请求本地host出现Invalid header field name

### ISSUE THREAD

**Issue by Foronia** [flutterchina/dio#290]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | 12.0                          |      |
| Dio Version                   2.1.2                            |      |
| Android Studio  | Android Studio 3.3.2           |      |
| Repro rate                     | all the time (100%)  |      |
| Repro with our demo prj        |happened with demo project          |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by Foronia** [comment]
I/flutter (26459): DioError [DioErrorType.DEFAULT]: HttpException: Invalid header field name, uri = http://192.168.2.200/api/index.php/ 
一请求80端口就会这样

**Comment by wendux** [comment]
提示header 中有字段不合法，贴一下你的请求头和响应头，以及复现代码


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Foronia** [comment]
您好，我分别以相同方式请求了一下线上服务器和本地服务器的同一接口，在抓包工具里看到两者都有返回所需json内容，但是请求本地服务器时在android studio里依旧提示以上错误。
这是线上服务器返回的响应头
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 20 May 2019 07:22:25 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.6.31

这是本地服务器返回的响应头
HTTP/1.1 200 OK
Server: nginx/1.12.2
Date: Mon, 20 May 2019 07:22:40 GMT
Content-Type: application/json; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/5.6.36
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials : true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Connection, User-Agent, Cookie
Content-Length: 2261

**Comment by wendux** [comment]
你是手机吗？手机上没有使用代理是不能直接请求局域网地址的。

**Comment by Foronia** [comment]
您的意思是要根据dio给出的方法设置代理吗

**Comment by Foronia** [comment]
您说手机上没有使用代理是不能直接请求局域网地址的，可是ios 那边是可以的呀。

**Comment by Foronia** [comment]
您好，解决了，是因为服务端请求头返回不规范造成的。感谢您的耐心回复。

**Comment by badrobot15** [comment]
Receiving same error. Server seems to be getting the request but app crashes

**Comment by wangkeshuai** [comment]
> 您好，解决了，是因为服务端请求头返回不规范造成的。感谢您的耐心回复。

服务器的头信息需要怎么规范 ，JWT Token 能不能支持

**Comment by blensmile** [comment]
同样问题, 检查了服务端的返回头, 发现格式有不正确的地方, 修改了就好了
