### ISSUE TITLE
dio请求gbk编码网站会乱码

### ISSUE THREAD

**Issue by honking** [flutterchina/dio#293]
dio请求gbk编码网站会乱码

>import 'package:dio/dio.dart';
>import 'package:gbk2utf8/gbk2utf8.dart';
>void main() async {
>  try {
>    Response response = await Dio().get("http://www.honking.me/test.php");
>    print(response.data);
>    print(response.data.codeUnits);
>    print(gbk.decode(response.data.codeUnits));
>  } catch (e) {
>    print(e);
>  }
>}

内容乱码
��
[65533, 65533]

**Comment by wendux** [comment]
1. 升级到2.1.4版本或以上
2. 通过`options.responseDecoder`自定义解码器

**Comment by honking** [comment]
```
import 'package:gbk_codec/gbk_codec.dart';

String gbkDecoder(List<int> responseBytes, RequestOptions options, ResponseBody responseBody) {
  return gbk_bytes.decode(responseBytes);
}

void main() async {
  
  Response response = await Dio(BaseOptions (responseDecoder: gbkDecoder)).get("http://www.honking.me/test.php",options: Options(responseDecoder: gbkDecoder));
  print(response.data);
}
```

版本更新并设置 options.responseDecoder后依旧乱码，尝试在dio.dart中往requestOptions中添加responseDecoder后正常

```
    RequestOptions requestOptions =
        _mergeOptions(options, path, data, queryParameters);
    requestOptions.onReceiveProgress = onReceiveProgress;
    requestOptions.onSendProgress = onSendProgress;
    requestOptions.cancelToken = cancelToken;
    requestOptions.responseDecoder = options.responseDecoder;
```


目前还有个问题是针对post的gbk编码会乱码，建议对request body可以自定义encoder
