### ISSUE TITLE
Adding instruction to add Firebase Performance framework

### ISSUE THREAD

**Issue by fvisticot** [flutterchina/dio#294]
I need to add Firebase Performance to get network performances.
[](https://pub.dev/packages/firebase_performance#-readme-tab-)

As it is not natively supported by Firebase Performance, we need to wrap each http call with the Firebase Performance Framework.

I was thinking to add Interceptor Feature of Dio for before / end interception.
But Is it possible to insert a variable (started metric) in this inteceptor context ? 

```
Future<StreamedResponse> send(BaseRequest request) async {
    final HttpMetric metric = FirebasePerformance.instance
        .newHttpMetric(request.url.toString(), HttpMethod.Get);

    await metric.start();

    StreamedResponse response;
    try {
      response = await _inner.send(request);
      metric
        ..responsePayloadSize = response.contentLength
        ..responseContentType = response.headers['Content-Type']
        ..requestPayloadSize = request.contentLength
        ..httpResponseCode = response.statusCode;
    } finally {
      await metric.stop();
    }

    return response;
  }
}
```

**Comment by andredealmei** [comment]
any news on this ?

**Comment by EthanGr** [comment]
any news?

**Comment by vishna** [comment]
I've created a [package](https://pub.dev/packages/dio_firebase_performance) that uses interceptor API to achieve this reporting

https://github.com/eyeem/dio_firebase_performance/blob/master/lib/src/dio_firebase_performance.dart

Might not be the most accurate but it's a start.
