### ISSUE TITLE
SocketException: Connection failed (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by shuyanzi** [flutterchina/dio#295]
## Steps to Reproduce
void main() {
  // add interceptors
  dio.interceptors..add(CookieManager(CookieJar()))..add(LogInterceptor());
  (dio.transformer as DefaultTransformer).jsonDecodeCallback = parseJson;
  dio.options.receiveTimeout = 15000;
  (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
      (client) {
    client.findProxy = (uri) {
      //proxy to my PC(charles)
      return "PROXY xx.xx.xx.xx:8888";
    };
  };
  runApp(MyApp());
}

## Logs(把example/flutter_example/lib/main.dart中的findProxy那段代码注释放开后，报错如下)

```
flutter: DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: Permission denied, errno = 13), address = xx.xx.xx.xx, port = 8888
```

**Comment by wendux** [comment]
那是设置代理的代码，你没有起代理，当然有问题


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by cakipaul** [comment]
我也遇到类似的问题，是在 `run --release` 时才出现。查了好些帖子发现是权限问题，我在 flutter/flutter 的 issue 里回复你了，再在这里回一遍可能帮到有缘人：
[参考](https://github.com/flutter/flutter/issues/2138)

**Comment by shuyanzi** [comment]
@cakipaul 再次谢谢你有缘人😄
