### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Operation timed out, errno = 60

### ISSUE THREAD

**Issue by gmw-zjw** [flutterchina/dio#296]
try {
    print('开始获取首页数据.........');
    Response response;
    Dio dio = new Dio();
    dio.options.contentType = ContentType.parse("application/x-www-form-urlencoded");
    var formData = {'lon': '115.02932' , 'lat': '35.76189'};
    response = await dio.post(servicePath['homePageContent'], data: formData);
    if (response.statusCode == 200) {
      return response.data;
    } else {
      throw Exception('获取后端数据出错.....');
    }
  } catch(e) {
    return print('ERROR: ============> ${e}'); 
  }

获取后端数据超时

**Comment by wendux** [comment]
问题是什么？描述详细一些


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by gmw-zjw** [comment]
问题已解决、原因是我传入参数多了一个“/”
