### ISSUE TITLE
json解析异常

### ISSUE THREAD

**Issue by juyao** [flutterchina/dio#30]
response.data.toString()后json字符串中的双引号都消失了，导致无法正常json解析

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
如果返回数据是json(content-type)，dio默认会自动将数据转为json，无需再手动转。详情可以参考文档中`Options`的`ResponseType`字段。

**Comment by wendux** [comment]
长时间没反馈，先关闭了，如有问题再重新打开。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
