### ISSUE TITLE
为什么我的到的请求结果都是BaseOptions呢？

### ISSUE THREAD

**Issue by 550609334** [flutterchina/dio#300]
![image](https://user-images.githubusercontent.com/12495031/57765061-4ec5c000-7737-11e9-88d2-1100e96c1a01.png)
这是我的请求，请求是成功了的，但是结果都是BaseOptions对象，并不是一个字符串或者json对象之类的

**Comment by wendux** [comment]
Web环境？

**Comment by 550609334** [comment]
> Web环境？

移动端，我发现原因了，我加上了InterceptorsWrapper 这个拦截器就会出现，图里这样写的。就是每个请求默认加了一些header。去掉就正常了。这个问题咋整？
![image](https://user-images.githubusercontent.com/12495031/58074804-b026dc80-7bd8-11e9-84ad-dcca6ccc3974.png)

**Comment by 550609334** [comment]
我找到原因了，是我返回值写错了。我的问题。
