### ISSUE TITLE
在使用dio时, 导入dio包是, App在启动时, 报一下错误信息

### ISSUE THREAD

**Issue by hightfly** [flutterchina/dio#301]
Compiler message:
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:74:3: Error: Type 'HttpClientAdapter' not found.
  HttpClientAdapter _httpClientAdapter = new DefaultHttpClientAdapter();
  ^^^^^^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:76:3: Error: Type 'HttpClientAdapter' not found.
  HttpClientAdapter get httpClientAdapter => _httpClientAdapter;
  ^^^^^^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:78:25: Error: Type 'HttpClientAdapter' not found.
  set httpClientAdapter(HttpClientAdapter adapter) {
                        ^^^^^^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/transformer.dart:29:52: Error: Type 'ResponseBody' not found.
  Future transformResponse(RequestOptions options, ResponseBody response);
                                                   ^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/transformer.dart:90:31: Error: Type 'ResponseBody' not found.
      RequestOptions options, ResponseBody response) async {
                              ^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:74:46: Error: Method not found: 'DefaultHttpClientAdapter'.
  HttpClientAdapter _httpClientAdapter = new DefaultHttpClientAdapter();
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:74:3: Error: 'HttpClientAdapter' isn't a type.
  HttpClientAdapter _httpClientAdapter = new DefaultHttpClientAdapter();
  ^^^^^^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:78:25: Error: 'HttpClientAdapter' isn't a type.
  set httpClientAdapter(HttpClientAdapter adapter) {
                        ^^^^^^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:406:14: Error: 'ResponseBody' isn't a type.
    Response<ResponseBody> response;
             ^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/dio.dart:732:5: Error: 'ResponseBody' isn't a type.
    ResponseBody responseBody;
    ^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/transformer.dart:29:52: Error: 'ResponseBody' isn't a type.
  Future transformResponse(RequestOptions options, ResponseBody response);
                                                   ^^^^^^^^^^^^
file:///Users/ywf/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.3/lib/src/transformer.dart:90:31: Error: 'ResponseBody' isn't a type.
      RequestOptions options, ResponseBody response) async {
                              ^^^^^^^^^^^^

**Comment by zhangjianying1** [comment]
Launching lib\main.dart on vivo Y66 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:392:32: Error: Getter not found: 'contentLengthHeader'.
compiler message:     lengthHeader = HttpHeaders.contentLengthHeader,
compiler message:                                ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:457:44: Error: Getter not found: 'contentEncodingHeader'.
compiler message:         response.headers.value(HttpHeaders.contentEncodingHeader);
compiler message:                                            ^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:461:37: Error: Getter not found: 'contentLengthHeader'.
compiler message:     if (lengthHeader == HttpHeaders.contentLengthHeader && compressed) {
compiler message:                                     ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:576:32: Error: Getter not found: 'contentLengthHeader'.
compiler message:     lengthHeader = HttpHeaders.contentLengthHeader,
compiler message:                                ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:759:54: Error: Getter not found: 'contentTypeHeader'.
compiler message:               responseBody.headers.value(HttpHeaders.contentTypeHeader);
compiler message:                                                      ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:761:32: Error: Getter not found: 'contentTypeHeader'.
compiler message:               .set(HttpHeaders.contentTypeHeader, ContentType.json.toString());
compiler message:                                ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:761:63: Error: Getter not found: 'json'.
compiler message:               .set(HttpHeaders.contentTypeHeader, ContentType.json.toString());
compiler message:                                                               ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:766:48: Error: Getter not found: 'contentTypeHeader'.
compiler message:           responseBody.headers.set(HttpHeaders.contentTypeHeader, contentType);
compiler message:                                                ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:833:48: Error: Getter not found: 'contentLengthHeader'.
compiler message:           if (key.toLowerCase() == HttpHeaders.contentLengthHeader) {
compiler message:                                                ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:841:39: Error: Getter not found: 'contentTypeHeader'.
compiler message:           options.headers[HttpHeaders.contentTypeHeader] =
compiler message:                                       ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:867:35: Error: Getter not found: 'contentTypeHeader'.
compiler message:       options.headers[HttpHeaders.contentTypeHeader] ??=
compiler message:                                   ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:870:37: Error: Getter not found: 'contentLengthHeader'.
compiler message:         options.headers[HttpHeaders.contentLengthHeader] = length;
compiler message:                                     ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio.dart:954:74: Error: Getter not found: 'json'.
compiler message:       contentType: opt.contentType ?? options.contentType ?? ContentType.json,
compiler message:                                                                          ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/form_data.dart:82:63: Error: Getter not found: 'text'.
compiler message:             UploadFileInfo(null, "", contentType: ContentType.text),
compiler message:                                                               ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/form_data.dart:84:35: Error: Getter not found: 'text'.
compiler message:           utf8.encode(ContentType.text.mimeType).length;
compiler message:                                   ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/form_data.dart:117:50: Error: Getter not found: 'text'.
compiler message:       buf.write((info.contentType ?? ContentType.text).mimeType);
compiler message:                                                  ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/form_data.dart:316:65: Error: Getter not found: 'text'.
compiler message:         "Content-Type: " + (fileInfo.contentType ?? ContentType.text).mimeType);
compiler message:                                                                 ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/transformer.dart:78:55: Error: Getter not found: 'json'.
compiler message:       if (options.contentType.mimeType == ContentType.json.mimeType) {
compiler message:                                                       ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/transformer.dart:99:46: Error: Getter not found: 'contentLengthHeader'.
compiler message:           response.headers.value(HttpHeaders.contentLengthHeader) ?? "-1");
compiler message:                                              ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/transformer.dart:147:63: Error: Getter not found: 'json'.
compiler message:         response.headers.contentType?.mimeType == ContentType.json.mimeType) {
compiler message:                                                               ^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/upload_file_info.dart:7:55: Error: Getter not found: 'binary'.
compiler message:         this.contentType = contentType ?? ContentType.binary;
compiler message:                                                       ^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/upload_file_info.dart:11:55: Error: Getter not found: 'binary'.
compiler message:         this.contentType = contentType ?? ContentType.binary;
compiler message:                                                       ^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/interceptors/cookie_mgr.dart:39:56: Error: Getter not found: 'cookieHeader'.
compiler message:     if (cookie.isNotEmpty) options.headers[HttpHeaders.cookieHeader] = cookie;
compiler message:                                                        ^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/interceptors/cookie_mgr.dart:50:59: Error: Getter not found: 'setCookieHeader'.
compiler message:       List<String> cookies = response.headers[HttpHeaders.setCookieHeader];
compiler message:                                                           ^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/adapter.dart:119:19: Error: The setter 'connectionTimeout' isn't defined for the class 'dart._http::HttpClient'.
compiler message: Try correcting the name to the name of an existing setter, or defining a setter or field named 'connectionTimeout'.
compiler message:       _httpClient.connectionTimeout = null;
compiler message:                   ^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:32:47: Error: Getter not found: 'defaultHttpPort'.
compiler message:         int defaultPortForScheme = HttpClient.defaultHttpPort,
compiler message:                                               ^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:73:29: Error: Getter not found: 'transferEncodingHeader'.
compiler message:     if (name == HttpHeaders.transferEncodingHeader) {
compiler message:                             ^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:89:29: Error: Getter not found: 'transferEncodingHeader'.
compiler message:     if (name == HttpHeaders.transferEncodingHeader && value == "chunked") {
compiler message:                             ^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:114:28: Error: Getter not found: 'connectionHeader'.
compiler message:         remove(HttpHeaders.connectionHeader, "close");
compiler message:                            ^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:121:25: Error: Getter not found: 'connectionHeader'.
compiler message:         add(HttpHeaders.connectionHeader, "keep-alive");
compiler message:                         ^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:125:25: Error: Getter not found: 'connectionHeader'.
compiler message:         add(HttpHeaders.connectionHeader, "close");
compiler message:                         ^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:127:28: Error: Getter not found: 'connectionHeader'.
compiler message:         remove(HttpHeaders.connectionHeader, "keep-alive");
compiler message:                            ^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:140:24: Error: Getter not found: 'contentLengthHeader'.
compiler message:       _set(HttpHeaders.contentLengthHeader, contentLength.toString());
compiler message:                        ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:142:29: Error: Getter not found: 'contentLengthHeader'.
compiler message:       removeAll(HttpHeaders.contentLengthHeader);
compiler message:                             ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:158:50: Error: Getter not found: 'transferEncodingHeader'.
compiler message:       List<String> values = _headers[HttpHeaders.transferEncodingHeader];
compiler message:                                                  ^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:161:31: Error: Getter not found: 'transferEncodingHeader'.
compiler message:         _addValue(HttpHeaders.transferEncodingHeader, "chunked");
compiler message:                               ^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:166:26: Error: Getter not found: 'transferEncodingHeader'.
compiler message:       remove(HttpHeaders.transferEncodingHeader, "chunked");
compiler message:                          ^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:181:48: Error: Getter not found: 'ifModifiedSinceHeader'.
compiler message:     List<String> values = _headers[HttpHeaders.ifModifiedSinceHeader];
compiler message:                                                ^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:195:22: Error: Getter not found: 'ifModifiedSinceHeader'.
compiler message:     _set(HttpHeaders.ifModifiedSinceHeader, formatted);
compiler message:                      ^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:199:48: Error: Getter not found: 'dateHeader'.
compiler message:     List<String> values = _headers[HttpHeaders.dateHeader];
compiler message:                                                ^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:217:48: Error: Getter not found: 'expiresHeader'.
compiler message:     List<String> values = _headers[HttpHeaders.expiresHeader];
compiler message:                                                ^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:231:22: Error: Getter not found: 'expiresHeader'.
compiler message:     _set(HttpHeaders.expiresHeader, formatted);
compiler message:                      ^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:244:22: Error: Getter not found: 'contentTypeHeader'.
compiler message:     _set(HttpHeaders.contentTypeHeader, contentType.toString());
compiler message:                      ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:263:25: Error: Getter not found: 'dateHeader'.
compiler message:         if (HttpHeaders.dateHeader == name) {
compiler message:                         ^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:267:25: Error: Getter not found: 'hostHeader'.
compiler message:         if (HttpHeaders.hostHeader == name) {
compiler message:                         ^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:273:25: Error: Getter not found: 'expiresHeader'.
compiler message:         if (HttpHeaders.expiresHeader == name) {
compiler message:                         ^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:279:25: Error: Getter not found: 'connectionHeader'.
compiler message:         if (HttpHeaders.connectionHeader == name) {
compiler message:                         ^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:285:25: Error: Getter not found: 'contentTypeHeader'.
compiler message:         if (HttpHeaders.contentTypeHeader == name) {
compiler message:                         ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:291:25: Error: Getter not found: 'contentLengthHeader'.
compiler message:         if (HttpHeaders.contentLengthHeader == name) {
compiler message:                         ^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:297:25: Error: Getter not found: 'transferEncodingHeader'.
compiler message:         if (HttpHeaders.transferEncodingHeader == name) {
compiler message:                         ^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:301:25: Error: Getter not found: 'ifModifiedSinceHeader'.
compiler message:         if (HttpHeaders.ifModifiedSinceHeader == name) {
compiler message:                         ^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:323:29: Error: Getter not found: 'transferEncodingHeader'.
compiler message:       _addValue(HttpHeaders.transferEncodingHeader, value);
compiler message:                             ^^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:331:24: Error: Getter not found: 'dateHeader'.
compiler message:       _set(HttpHeaders.dateHeader, value);
compiler message:                        ^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:341:24: Error: Getter not found: 'expiresHeader'.
compiler message:       _set(HttpHeaders.expiresHeader, value);
compiler message:                        ^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:351:24: Error: Getter not found: 'ifModifiedSinceHeader'.
compiler message:       _set(HttpHeaders.ifModifiedSinceHeader, value);
compiler message:                        ^^^^^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:362:27: Error: Getter not found: 'defaultHttpPort'.
compiler message:         port = HttpClient.defaultHttpPort;
compiler message:                           ^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:370:29: Error: Getter not found: 'defaultHttpPort'.
compiler message:           port = HttpClient.defaultHttpPort;
compiler message:                             ^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:379:24: Error: Getter not found: 'hostHeader'.
compiler message:       _set(HttpHeaders.hostHeader, value);
compiler message:                        ^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:396:22: Error: Getter not found: 'contentTypeHeader'.
compiler message:     _set(HttpHeaders.contentTypeHeader, value);
compiler message:                      ^^^^^^^^^^^^^^^^^
compiler message: file:///D:/Program%20Files%20(x86)/flutter/.pub-cache/hosted/pub.dartlang.org/dio-2.1.7/lib/src/dio_http_headers.dart:426:29: Error: Getter not found: 'setCookieHeader'.
compiler message:     if (name == HttpHeaders.setCookieHeader ||
compiler message:                             ^^^^^^^^^^^^^^^
Compiler failed on D:\learn\flutter_app\lib\main.dart
我的引入dio也报错android-studio v-3.4.1,flutter和dart都是最新版本
