### ISSUE TITLE
unhandled cancel Exception

### ISSUE THREAD

**Issue by zhengbomo** [flutterchina/dio#306]
after cancel the request by token, dio has also occurred an unhandled Exception like this

<img width="934" alt="unhandle_cancel_exception" src="https://user-images.githubusercontent.com/4704147/57994462-d91f7280-7aef-11e9-99b3-85b3a9cf704d.png">

here is my code

```dart
import 'package:dio/dio.dart';

...

void _testDio() async {
  CancelToken token = CancelToken();
  var url = "https://github.com/flutterchina12121/dio";

  Future.delayed(const Duration(milliseconds: 0), () async {
    try {
      Response response = await Dio().get(url, cancelToken: token);
      if (response.statusCode == 200) {
        print("request success");
      } else {
        print("request failed");
      }
    } catch (e) {
      print("request failed with exception");
    }
  });

  Future.delayed(const Duration(milliseconds: 250), () {
    print("manual cancel");
    if (!token.isCancelled) {
      token.cancel();
    }
  });
}
```

when i call `_testDio` frequently, the Exception occurred

version: 
* flutter: 1.5.4-hotfix.2
* platform: iOS
* dart: 2.3.0

**Comment by wendux** [comment]
Not bug! Dio will throw a ` DioError` error with` DioErrorType.CANCEL` when  request is cancelled.

**Comment by zhengbomo** [comment]
> Not bug! Dio will throw a ` DioError` error with` DioErrorType.CANCEL` when request is cancelled.

@wendux  is there any idea to fix it?

**Comment by wendux** [comment]
you can refer to  https://github.com/flutterchina/dio/blob/master/example/cancel_request.dart

**Comment by micsan13br** [comment]
dio.download(url, filePath, cancelToken: _cancelToken, /*...*/) still throws an exception when using catchError() after cancelling with the token.

the workaround seems to be a try/catch using DioError
try {} on DioError catch (exception) { print("something"); }

**Comment by ganeshrvel** [comment]
@micsan13br both
catchError and ```try {} on DioError catch (exception) { print("something"); } ``` doesn't seem to work.

**Comment by rvn9** [comment]
what to do if i only want to cancel once ? lets say im donwloading something and user want to manual cancel that donwload, when im calling token.cancel() for the next request auto exception, must keep making diffrent cancel token for each req ?

**Comment by Sp4Rx** [comment]
if you want to cancel once assign a new cancelToken after the first request has been canceled.

```
    CancelToken _cancelToken = CancelToken();
   Response response = await _dio.get(
      url,
      options: Options(headers: headers),
      cancelToken: _cancelToken,
    );

    //After some operation
    _cancelToken.cancel('Logged out');
    //Some operation
    _cancelToken = CancelToken();
```

**Comment by testOccu16** [comment]
> you can refer to https://github.com/flutterchina/dio/blob/master/example/cancel_request.dart

404 - Page Not Found

**Comment by choijaegwon** [comment]
취소처리될때 에러 반환 안하는방법
```
} catch (e) {
    if (e is DioException && e.type == DioExceptionType.cancel) {
    // 취소처리 로직추가
    return;

    // 에러처리 로직
}
```
