### ISSUE TITLE
Is there a way to gzip request?

### ISSUE THREAD

**Issue by Elvis5566** [flutterchina/dio#307]
I'd like to gzip my http request to reduce network traffic.
I've tried
```
var gzipedData = GZipEncoder().encode(utf8.encode(jsonEncode(params)));
headers['Content-Encoding'] = 'gzip';
headers['Content-Length'] = '${gzipedData.length}';
headers['Content-Type'] = 'application/json';

client.post(path,
            data: gzipedData,
            options: options(headers),)
```
but It doesn't work.

**Comment by wendux** [comment]
Maybe you can post the gzip data with` Stream`:

```dart
// Binary data
List<int> postData = <int>[...];
await dio.post(
  url,
  data: Stream.fromIterable(postData.map((e) => [e])), //create a Stream<List<int>>
  options: Options(
    headers: {
      HttpHeaders.contentLengthHeader: postData.length, // set content-length
    },
  ),
);
```

**Comment by Elvis5566** [comment]
@wendux 
Thank you, it works very well.
It turns out there is another issue in my code.
header 'Content-Length' should be lower case, otherwise, request headers will have two 'Content-Length', one has value of int type, the other one is String, which cause server retunes status 503.

**Comment by qq326646683** [comment]
@wendux hi，auther，if the postData is too large, Will it be oom? If it will,how to resolve it?
