### ISSUE TITLE
Version 2.1.4 Regression - Catching DioError doesn't work

### ISSUE THREAD

**Issue by liviuls** [flutterchina/dio#309]
Hi, since version 2.1.4 catching DioError doesn't work anymore. I've written a unit test that fails, but should pass, using the syntax in the documentation:

```
import 'package:flutter_test/flutter_test.dart';
import 'package:dio/dio.dart';

void main() {
  test("dio error test", () async {
    final dio = Dio();

    bool hasError = false;

    try {
      await dio.get("https://wendux.github.io/xsddddd");

      hasError = false;
    } on DioError catch (e) {
      hasError = true;
    }

    expect(hasError, true);
  });
}
```

**Comment by wendux** [comment]
fixed, please upgrade to v2.1.5, and try again.

**Comment by liviuls** [comment]
It's working with 2.1.5. Thank you! Awesome job on the library btw!

**Comment by passsy** [comment]
@wendux can you push the code to `2.1.5`? I'd like to PR another fix.
