### ISSUE TITLE
Content size exceeds specified contentLength on formdata upload

### ISSUE THREAD

**Issue by vinters768** [flutterchina/dio#312]
=====================================
```

var formData = new FormData.from({
          "param1": "-1",
          "param2": "-1",
          "param3": "-1",
          "param4": "-1",
          "param5": "-1",
          "music": new UploadFileInfo(new File(fileUrl), "audio.m4a"),
        });

 final response = await _api.post(uploadUrl, data:formData,
        onSendProgress: (sent, total) {
      print("uploadFile ${sent / total}");
    });

```

- fileUrl comes from device storage.
- fileUrl is valid, as upload process begins, and it was tested;

Produces this error:
============================================
`flutter: DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength. 234777 bytes written while expected 234769. [----dio-boundary-0252882641--]
`
Can someone help we with this?

**Comment by wendux** [comment]
Dio version?

**Comment by Kiwake** [comment]
I believe this error appears with the dio version 2.1.4

**Comment by vinters768** [comment]
```
dio: ^2.1.5
```

Flutter doctor:
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

**Comment by vinters768** [comment]
@wendux any ideas? if you need more info, let me know how I can help..

**Comment by wendux** [comment]
@vinters768 The value of `Content-length` is `formData.length`. you can test with follow code:
```dart
 var t= await formData.asBytesAsync();  // Stream size.
 print(formData.length==t.length);  // Should be `true`
```
If `formData.length` is not equal to` t.length`, please upload the "audio.m4a" and I'll help you to check it.

**Comment by vinters768** [comment]
```
[final.m4a.zip](https://github.com/flutterchina/dio/files/3222464/final.m4a.zip)


 var fileLenght = file.lengthSync();

        print("fileLenght = $fileLenght");

        var formStreamSize = await formData.asBytesAsync(); // Stream size.

        print("formStreamSize = ${formStreamSize.length}");
        print("formData.length = ${formData.length}");

        print("formData.length == formStreamSize.length ${formData.length == formStreamSize.length}"); // Should be `true`
```
```
flutter: fileLenght = 239166
flutter: formStreamSize = 240231
flutter: formData.length = 240223
```
```
flutter: DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength. 240231 bytes written while expected 240223. [----dio-boundary-1735630428--]
```

**Comment by vinters768** [comment]
@wendux sorry for the trouble, but we are kind waiting on this for production release.. could you please confirm that this isn't a problem on dio side? 

thanks again

**Comment by wendux** [comment]
@vinters768 This is my test code:
```dart
import 'dart:io';
import 'package:dio/dio.dart';

main() async {
  var formData = new FormData.from({
    "param1": "-1",
    "param2": "-1",
    "param3": "-1",
    "param4": "-1",
    "param5": "-1",
    "music": new UploadFileInfo(new File("./example/audio.m4a"), "audio.m4a"),
  });
  var t= await formData.asBytesAsync();
  print("formStreamSize = ${t.length}"); 
  print("formData.length = ${formData.length}"); //
  print(formData.length==t.length);

}
```
The output is:
```
formStreamSize = 239748
formData.length = 239748
true
```
Any other params in `formdata` ?

**Comment by vinters768** [comment]
@wendux the only difference is that "file" comes from device storage, not flutter project path.. will try v2.1.3 and let you now.

**Comment by vinters768** [comment]
@wendux downgrade worked.. don't know why though.

anyway, thanks again!

**Comment by kkroid** [comment]
this error appears on version 2.1.7 also

**Comment by mo-ah-dawood** [comment]
same proplem here 2.1.7

**Comment by Ethiel97** [comment]
Same problem here 2.1.7. The downgrade to 2.1.3 resolved my problem.

**Comment by wendux** [comment]
fixed in v2.1.8

**Comment by Berial** [comment]
this error appears on version 2.1.8 also @wendux

 Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength. 282 bytes written while expected 194.

**Comment by HouPoc** [comment]
This exception happens to me, either. It only happens when I test my app on Android but not IOS. Wish these details can help.

**Comment by dfalmeida** [comment]
Same thing happens to me with an audio file. 
My dio version is 2.1.13

**Comment by UnDer-7** [comment]
> Same thing happen to me with an audio file.
> My dio version is 2.1.13

same

**Comment by AteqEjaz** [comment]
same error for dio: 2.1.16

**Comment by wendux** [comment]
please update to 3.0.x and try again .


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by gersonjaber** [comment]
> please update to 3.0.x and try again .
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

Hi @wendux, this is happening in 3.0.3 version too.

**Comment by NidheeshMt** [comment]
Content size exceeds specified contentLength. 66130 bytes written while expected 627
error caught while uploading PDF

dio: ^3.0.8

**Comment by AdnanKazi** [comment]
Same problem in 3.0.9

**Comment by waqaryounusjatt788** [comment]
Content size exceeds specified contentLength. 418 bytes written while expected 257. in text files

**Comment by SanderMuniz** [comment]
I have the same problem in version 3.0.9    I can't solve

**Comment by petra-bios** [comment]
Hi guys, anyone got the answer for this issue yet? still happening on version 3.0.9 with audio file.

**Comment by AdnanKazi** [comment]
@petra-bios It had been a year that this issue isn't solved still its status is closed 
and most of us tried but din't get what we want so don't stuck on same problem try alternative for audio files request

**Comment by petra-bios** [comment]
Hi @AdnanKazi , I think i found the solution for this (at least for the case i'm facing).
I will leave it here in case other people need it.

what solved mine was: 
I use `MultipartFile.fromBytes` instead of `MultipartFile.fromFile`

For example : 
from this :
`final file = await MultipartFile.fromFile(filePath);`
to this : 
`final file = MultipartFile.fromBytes(File(filePath).readAsBytesSync(), filename: filePath.split("/").last);`

Thanks and i hope it helps.

**Comment by AdnanKazi** [comment]
@petra-bios Thank you very much for solution i will try it in mean time

**Comment by rodrigo-bueno** [comment]
@petra-bios awesome save my day! 
Follow my solution with mp3:

```
FormData formData = FormData.fromMap({
      "file": MultipartFile.fromBytes(
          File(recordFilePath).readAsBytesSync(),
          filename: fileName),
    });
```

**Comment by lbjlsy** [comment]
Same problem in 3.0.10

**Comment by djade007** [comment]
If you are using this package https://pub.dev/packages/record

Ensure you wait for the recording to completely stop before you start uploading the file.
`Record.stop()` is a future, so you need to add await to it


```
await Record.stop()
// Start uploading
```
