### ISSUE TITLE
Support flutter web

### ISSUE THREAD

**Issue by ctrysbita** [flutterchina/dio#313]
Any plan to support flutter for web?

**Comment by zp19931128** [comment]
flutter for web compile fail, me too

**Comment by mordeccai** [comment]
Yes it would be pretty helpful if we were also able to use dio on the web. It has a good design

**Comment by vanlooverenkoen** [comment]
Flutter web is currently in a separate package. I will be merged into the flutter core package when stable. I think if you want to use dio at this point you will have to fork dio and remove the flutter dependencies and add the flutter_web dependencies

**Comment by ctrysbita** [comment]
@vanlooverenkoen That's not about flutter dependencies. Flutter_web doesn't support using `dart:io` package so that we should use `dart:html` instead. I think using condition import to seprate the dependencies is a good choice. Refer to official http package.

**Comment by kapil708** [comment]
did u get any solution

**Comment by Triipaxx** [comment]
shouldn't it be enough to change the imports like the following?

`import 'dart:io' if (dart.library.html) 'dart:html';`

**Comment by ctrysbita** [comment]
@kapil708 not yet. Use official http library instead

**Comment by godot0413301** [comment]
还没支持就关闭本issues了？


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by javdev** [comment]
How is the status. The GET goes out, but doesn't return
