### ISSUE TITLE
Uncaught exception, try/catch not working

### ISSUE THREAD

**Issue by cosinus84** [flutterchina/dio#314]
Making dio.post throws uncaught exception
```
myAsync() async{
try {
      Response response = await dio
          .post(_appStore.getURL("test/1"), data: formData);
      return true;
    } catch (e) {
      print(e);
    }
}

```
The server requires GET and not POST so I should get an error 405. 
The problem is that the try/catch is not working somehow. When I run the app is pointing as an uncaught exception the exception not being caught.

Flutter (Channel dev, v1.6.3, on Mac OS X 10.14.4 18E226, locale en-RO)
    • Flutter version 1.6.3 at /Users/cosinus/flutter
    • Framework revision bc7bc94083 (5 days ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

![Screenshot 2019-05-28 at 10 59 40](https://user-images.githubusercontent.com/1459132/58461188-ba485e00-8137-11e9-86ff-46d92e300249.png)

Thank you

**Comment by cosinus84** [comment]
I think is something wrong with the debugger, it seems that it treats handled exceptions as uncaught.

**Comment by cosinus84** [comment]
Yes running flutter run everything is working fine.

**Comment by cosinus84** [comment]
There is some issue inside the lib, it may require some fix

https://github.com/flutter/flutter/issues/33427

**Comment by akuma06** [comment]
Same problem here I was wondering why my stream wouldn't work :')

**Comment by ppyupp** [comment]
Same problem...

**Comment by MichaelPriebe** [comment]
Getting this.

**Comment by jaasaria** [comment]
Any update on this?  Got the same problem.

**Comment by wendux** [comment]
Please update to 3.0.x and try again.

**Comment by fdonzello** [comment]
@wendux just added the dependencies and the bug is still there

**Comment by jobehi** [comment]
same here

**Comment by Chris1234567899** [comment]
Still getting this issue  (version 3.0.9)

**Comment by RKasinCDRK** [comment]
Still getting this issue (version 3.0.8)

**Comment by hugotai101** [comment]
```dart
  myAsync() async {
    Response response = await dio
        .post(_appStore.getURL("test/1"), data: formData)
        .catchError((error) {
      print(error);
    });
  }
```
I'm able to catch error this way, using the `.catchError`

**Comment by bhaskar-nair2** [comment]
This is not an error with Dio. Try running your code with `flutter run` and it will work fine.

**Comment by elganiesta** [comment]
i recently had this error .. so i don't use try/catch anymore.. 
like in this case : 
`_auth.signInWithEmailAndPassword(email: email, password: password)
                  .then((user) {
                    if (user != null) {
                      setState(() {
                        showSpinner = false;
                      });
                      Navigator.push(context,
                          MaterialPageRoute(builder: (context) => HomeScreen()));
                    }
                  }).catchError((onError) => print(onError));`

**Comment by orestesgaolin** [comment]
Having this issue with dio 3.0.10 on iOS 14 with Flutter beta 1.22. Doesn't occur on Android though.

**Comment by RaoSaqib7860** [comment]
i am handle in this way on debug mode I know its not good practice 
 Options(
            headers: {'Authorization': 'Bearer $token'},
             followRedirects: false,
              validateStatus: (status) {
                return status <= 500;
              }
          )

**Comment by GuyGenZ** [comment]
> This is not an error with Dio. Try running your code with `flutter run` and it will work fine.

it work with me !!!

**Comment by AlexandrFarkas** [comment]
It's not error with dio, but with then/catchError async flow. Debugger works fine with async/await code (which is the standard way to write async code). I've never had similar problem with any other library.

**Comment by imedboumalek** [comment]
I have the same problem on 5 different machines (all running different linux distros).

**Comment by Lipe1994** [comment]
I have to problem...

**Comment by Lipe1994** [comment]
I solved, using last stable version of flutter. 

if using interceptor to take errors, no forget to implement the "@override onError" with "handler.next(error)" in final.

exemple:
`
class ErrorAuthInterceptor extends Interceptor {
  @override
  onError(DioError err, ErrorInterceptorHandler handler) async {

      switch (err.type) {
        case DioErrorType.connectTimeout:
        case DioErrorType.sendTimeout:
        case DioErrorType.receiveTimeout:
        case DioErrorType.response:
        case DioErrorType.cancel:
        case DioErrorType.other:

          err = YourCustomizeErrorDioException(//Your implement your Exeption implements of DioError, if you want
          'Your message',
          error: err.error, 
          requestOptions: err.requestOptions, 
          response: err.response,
          type: err.type );
      }

    //super.onError(err, handler);
    handler.next(err); //<------ very important
  }
}
`

**Comment by SNNafi** [comment]
@Lipe1994 Thanks for sharing.

**Comment by AndersonSchmidt** [comment]
> I solved, using last stable version of flutter (Flutter 2.8.0 • channel stable) and DIO (dio: ^4.0.4) .
> 
> if using interceptor to take errors, no forget to implement the "override onError" with "handler.next(error)" in final.
> 
> exemple:
> 
> ```
>  class ErrorAuthInterceptor extends Interceptor {
>       @override
>       onError(DioError err, ErrorInterceptorHandler handler) async {
>     
>           switch (err.type) {
>               case DioErrorType.connectTimeout:
>               case DioErrorType.sendTimeout:
>               case DioErrorType.receiveTimeout:
>               case DioErrorType.response:
>               case DioErrorType.cancel:
>               case DioErrorType.other:
>       
>                 err = YourCustomizeErrorDioException(//Your implement your Exeption implements of DioError, if you want
>                 'Your message',
>                 error: err.error, 
>                 requestOptions: err.requestOptions, 
>                 response: err.response,
>                 type: err.type );
>           }
>     
>         //super.onError(err, handler);
>         handler.next(err); //<------ very important
>       }
>   }
> ```

Lipe, voce ta vendendo uma BMW 330i?
