### ISSUE TITLE
How to send an array of queryParameters?

### ISSUE THREAD

**Issue by MilesAdamson** [flutterchina/dio#315]
### New Issue Checklist

- [x ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                     
| ------------------------------ | --------------------------------------------------
| Platform Name                  |  flutter          
| Platform Version               | 1.5.4-hotfix.2                           
| Dio Version                    | 2.1.0                          
| Repro rate                     | 100% 

### Issue Description and Steps

How do I send an array of queryParameters? 

In postman, I am able to send a GET with an array of parameters. The URL looks like this and it works fine:
```
/v2/tickets?templateId=5&templateId=7
```

I have tried a lot of different ways to do the same in flutter with Dio and can't get it to work:

```
queryParameters['templateId'] = [1, 2];
queryParameters['templateId'] = ['1', '2'];
queryParameters['templateId'] = `[1, 2]`;
```

**Comment by wendux** [comment]
```dart
  var uri = Uri(
    ...
    queryParameters: {
      "templateId": ['1', '2']
    },
  );
  dio.getUri(uri);
```

**Comment by MilesAdamson** [comment]
> ```dart
>   var uri = Uri(
>     ...
>     queryParameters: {
>       "templateId": ['1', '2']
>     },
>   );
>   dio.getUri(uri);
> ```

Thank you, works perfectly

**Comment by ThinkDigitalSoftware** [comment]
Why is this closed if the issue still exists?

**Comment by yousifAlneamy** [comment]
This issue should be reopened

**Comment by shinsenter** [comment]
This issue should be reopened

**Comment by shubhamhackz** [comment]
We're still facing this issue, please reopen.

**Comment by jonorozcoc** [comment]
Please reopen the issue

**Comment by kczpl** [comment]
I am also facing this issue. Can you please reopen this issue?

**Comment by shinolex** [comment]
I'm facing this error too, I just want to send a simple int list but can't

**Comment by wizetLee** [comment]
```
queryParameters: {
   "templateId[]": ['1', '2']
}
```
This format helped me solve this problem

**Comment by adar2378** [comment]
It doesn't work with `dio.request` method. There are multiple keys with different value from list when dio sends requests

For example:
```
final _queryParameters = <String, dynamic>{
"categoriesIn": [1,2,3]
}

final response = await dio.request<Object>(path, queryParameters: _queryParameters ....);

```
When it calls the api I notice that it uses `path?categoriesIn=1&categoriesIn=2` instead of `path?categoriesIn=1,2`

**Comment by wizetLee** [comment]
这是来自QQ邮箱的假期自动回复邮件。。。。收到了哦~~！

**Comment by wizetLee** [comment]
这是来自QQ邮箱的假期自动回复邮件。。。。收到了哦~~！
