### ISSUE TITLE
Sometimes Dio 'cuts off' Rest API responses

### ISSUE THREAD

**Issue by fkranenburg** [flutterchina/dio#317]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Flutter                          |      |
| Platform Version               | 1.5.4                              |      |
| Dio Version                    | 2.1.0                                 |      |
| Android Studio / Xcode Version | both             |      |
| Repro rate                     |  sometimes 25%   |      |
| Repro with our demo prj        | no           |      |
| Demo project link              | don't have it |      |

### Issue Description and Steps

I have some issues with Dio and need some help to resolve it. I'm calling a Rest API while building a flutter page and sometimes I receive some really strange issues because the response is being cut off. I'm 100% sure the webserver is return a full and valid Json response, because I have access to the server backend too.

I receive sometimes, randomly unexpected errors like this:

> I/flutter (14410): *** Request ***
I/flutter (14410): uri: https://dev07.changetocomm.net/ac/api/client/C1001005/klantprofiel
I/flutter (14410): method: GET
I/flutter (14410): contentType: application/json; charset=utf-8
I/flutter (14410): responseType: ResponseType.json
I/flutter (14410): followRedirects: true
I/flutter (14410): connectTimeout: 4000
I/flutter (14410): receiveTimeout: 5000
I/flutter (14410): extra: {}
I/flutter (14410): header:
I/flutter (14410):   Authorization:Basic ZmVycnk6bG90dXNub3Rlcw==
I/flutter (14410):   Content-Type:application/json
I/flutter (14410):   Cache-Control:no-cache
I/flutter (14410):   cookie:SessionID=69E21BF718C38B35B8D41692D6F0879BC6DF2696
I/flutter (14410):
I/flutter (14410): *** DioError ***:
I/flutter (14410): DioError [DioErrorType.DEFAULT]: FormatException: Unterminated string (at character 16385)
I/flutter (14410): ...":"Nog te bepalen","id":"2AD67D180C49D744C125824400434336","portal":"N"},{"
I/flutter (14410):                                                                               ^
I/flutter (14410): DIO error DioError [DioErrorType.DEFAULT]: FormatException: Unterminated string (at character 16385)
I/flutter (14410): ...":"Nog te bepalen","id":"2AD67D180C49D744C125824400434336","portal":"N"},{"
I/flutter (14410):                                                                               ^
I/flutter (14410): DioError [DioErrorType.DEFAULT]: FormatException: Unterminated string (at character 16385)
I/flutter (14410): ...":"Nog te bepalen","id":"2AD67D180C49D744C125824400434336","portal":"N"},{"
I/flutter (14410): 

And the same request on another moment I receive this:

> I/flutter (14410): *** Request ***
I/flutter (14410): uri: https://dev07.changetocomm.net/ac/api/client/C1001005/klantprofiel
I/flutter (14410): method: GET
I/flutter (14410): contentType: application/json; charset=utf-8
I/flutter (14410): responseType: ResponseType.json
I/flutter (14410): followRedirects: true
I/flutter (14410): connectTimeout: 4000
I/flutter (14410): receiveTimeout: 5000
I/flutter (14410): extra: {}
I/flutter (14410): header:
I/flutter (14410):   Authorization:Basic ZmVycnk6bG90dXNub3Rlcw==
I/flutter (14410):   Content-Type:application/json
I/flutter (14410):   Cache-Control:no-cache
I/flutter (14410):   cookie:SessionID=69E21BF718C38B35B8D41692D6F0879BC6DF2696
I/flutter (14410):
I/flutter (14410): *** DioError ***:
I/flutter (14410): DioError [DioErrorType.DEFAULT]: FormatException: Unexpected end of input (at character 8193)
I/flutter (14410): ...xnummer":"FFFFFF","naam":"hap","geslacht":"m","titelvoor":"","partner_naam"
I/flutter (14410):                                                                               ^
I/flutter (14410): DIO error DioError [DioErrorType.DEFAULT]: FormatException: Unexpected end of input (at character 8193)
I/flutter (14410): ...xnummer":"FFFFFF","naam":"hap","geslacht":"m","titelvoor":"","partner_naam"

**Comment by wendux** [comment]
Please update dio to latest version and try again.

**Comment by fkranenburg** [comment]
Looks like this works. Thanks

**Comment by Dhaval2404** [comment]
Still facing this issue with v2.1.8. And the strange thing is it occurred in Android Emulator only.
