### ISSUE TITLE
https over self-signed certificate

### ISSUE THREAD

**Issue by pepie** [flutterchina/dio#32]
'CERTIFICATE_VERIFY_FAILED'  exception is thrown,  when connection to server with self-signed certificate.

```dart
var url = 'https://jsonplaceholder.typicode.com/posts/1';
Dio dio = new Dio();
await dio.get(url).then((response){
  print(response.data);
}).catchError((err){
   print(err);
});
```

**Comment by wendux** [comment]
You should create a `SecurityContext` object to trust your certificate in  `onHttpClientCreate ` callback, for examples:
```dart 
  dio.onHttpClientCreate = (HttpClient client) {
    // create a `SecurityContext` to trust you certificate
    return HttpClient(securityContext)
  };
```

More about `SecurityContext` please refer to  [dart doc -SecurityContext ](https://api.dartlang.org/stable/1.24.3/dart-io/SecurityContext-class.html)

**Comment by pepie** [comment]
Consider adding support for badCertificateCallback.
```
 HttpClient httpClient = new HttpClient()
      ..badCertificateCallback =
      ((X509Certificate cert, String host, int port) => trustSelfSigned);
```

perhaps as an option to the constructor:
```new Dio({acceptSelfSignedCert: false})```

**Comment by wendux** [comment]
Are you sure? I have run the code as follows:
```dart
    dio.onHttpClientCreate = (HttpClient client) {
      print("dio xxxx");
      client.badCertificateCallback =
          (X509Certificate cert, String host, int port) {
        return true;
      };
    };
```
## Console log
```
I/flutter (18963): dio xxxx
```

**Comment by pepie** [comment]
Yes, It never ran on my box.
It's a little weird.

I've submitted a pull request to support self-signed certs.
https://github.com/flutterchina/dio/pull/33

Please consider. This works.
Another option would be to allow one to pass the entire callback, instead of setting trustSelfSignedCerts to true.

Great plugin btw!!

**Comment by pepie** [comment]
I'm guessing that's the case.
I'll send an update if I discover anything strange.
Thanks!

**Comment by lyquocnam** [comment]
what about this issuse ?

**Comment by cdvv7788** [comment]
It seems that @pepie found a solution (check https://github.com/flutterchina/dio/pull/33). Should this issue be closed? Does this specific case need to be documented?

**Comment by pepie** [comment]
Closing this issue since a solution was found.
class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext context){
    HttpClient client= super.createHttpClient(context);   //<<--- notice 'super'
    client.badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
    return client;
  }
}


void main(){
  HttpOverrides.global = new MyHttpOverrides();
  runApp(new App());
}

**Comment by grandpa-guru** [comment]
```
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (HttpClient client) {
    client.badCertificateCallback = (X509Certificate cert, String host, int port) => true;
    return client;
};
```

**Comment by abgrano** [comment]
Dio dio = new Dio();
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
    (HttpClient client) {
  client.badCertificateCallback =
      (X509Certificate cert, String host, int port) => true;
  return client;
};

**Comment by arnbut** [comment]
DioForNative dio = DioForNative();
    DefaultHttpClientAdapter httpClient = dio.httpClientAdapter;
    httpClient.onHttpClientCreate = (HttpClient client) {
      client.badCertificateCallback =
          (X509Certificate cert, String host, int port) {
        return true;
      };
    };
and then you can make dio.post and dio.get requests.

**Comment by bambinoua** [comment]
How to disable SSL certificate check using Dio in **WEB ENVIRONMENT**?

**Comment by LukeDaniel16** [comment]
> ```
> (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (HttpClient client) {
>     client.badCertificateCallback = (X509Certificate cert, String host, int port) => true;
>     return client;
> };
> ```

This is not SAFE for production versions!

We need other reply to resolve it, anyone?

**Comment by samatzhusup** [comment]
@bambinoua Have you found a solution for flutter web?

**Comment by jparsoft** [comment]
In my case I needed to use an auto signed certificate and the solution was this:

```
Future<Response> secureRequest(
    String path, {
    method = 'GET',
    Map<String, dynamic>? queryParameters,
    dynamic data,
    Map<String, String>? headers,
  }) async {
    
   // convert my certificate to pem

   // openssl x509 -in client.crt -out client.pem 
   // openssl rsa -in client.key -out clientkey.pem
     

    ByteData dataCRT = await rootBundle.load('assets/ca/client.pem');
    ByteData dataKey = await rootBundle.load('assets/ca/clientkey.pem');

    Dio dio = Dio();
    dio.interceptors.add(_interceptor);
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (client) {
      SecurityContext serverContext = SecurityContext();

      serverContext.useCertificateChainBytes(dataCRT.buffer.asUint8List());
      serverContext.usePrivateKeyBytes(dataKey.buffer.asUint8List());
      // use a new client for add the certificate and accept auto signed certificate and return it
      var newClient = HttpClient(context: serverContext);
      newClient.badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
      return newClient;
    };
    logger.i("secureRequest");
    logger.d("path: $path");

    return await dio.request(path,
        data: data,
        queryParameters: queryParameters,
        options: Options(
          headers: headers,
          method: method,
        ));
  }
```

**Comment by lukas-pierce** [comment]
Changes from Mart 2024:

~~`onHttpClientCreate`~~ callback is deprecated. Now you should use `createHttpClient` and return own your [`HttpClient`](https://api.flutter.dev/flutter/dart-io/HttpClient-class.html) instance:

```dart
Dio createDio({required String baseUrl, bool trustSelfSigned = false}) {
  // initialize dio
  final dio = Dio()
    ..options.baseUrl = baseUrl;

  // allow self-signed certificate
  (dio.httpClientAdapter as IOHttpClientAdapter).createHttpClient = () {
    final client = HttpClient();
    client.badCertificateCallback = (cert, host, port) => trustSelfSigned;
    return client;
  };
  
  return dio;
}
```
