### ISSUE TITLE
No all exceptions have stackTrace method

### ISSUE THREAD

**Issue by kascote** [flutterchina/dio#321]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                            |      |
| Platform Version               | v1.5.4-hotfix.2                              |      |
| Dio Version                    | 2.1.6                                 |      |
| Android Studio / Xcode Version | 3.4.1              |      |
| Repro rate                     | 100%   |      |
| Repro with our demo prj        | unknown            |      |
| Demo project link              | posted here |      |

### Issue Description and Steps

```
import 'package:dio/dio.dart';

main() async {
  try {
    await Dio().get("https://does.not.exist");
  } on DioError catch (e) {
    print(e.message);
  }
}
```

fails with

```
◆ dart bin/main.dart
NoSuchMethodError: Class 'SocketException' has no instance getter 'stackTrace'.
Receiver: Instance of 'SocketException'
Tried calling: stackTrace
```
expected result

```
◆ dart bin/main.dart
SocketException: Failed host lookup: 'does.not.exist' (OS Error: Name or service not known, errno = -2)
```

offending line

https://github.com/flutterchina/dio/blob/master/package_src/lib/src/dio.dart#L987

**Comment by tangyue0924** [comment]
Same problem...

**Comment by HaijunWei** [comment]
一样的问题，Post请求，Debug状态没问题，Release有崩溃信息

**Comment by wendux** [comment]
please upgrade to 2.1.7 and try again.

**Comment by gzf6** [comment]
> please upgrade to 2.1.7 and try again.

still same issuse
