### ISSUE TITLE
How to Get Error Code?

### ISSUE THREAD

**Issue by searchy2** [flutterchina/dio#322]
### New Issue Checklist

- [ ✅ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps

Does Dio have a method to return the error code? I would like to get the HTTP error codes such as (404, 500). Dio also returns system error codes such as errno = 7 (no connection) which I would like to handle too. 

Currently, it seems that DioError does not return an error code.

**Comment by searchy2** [comment]
For an invalid exception, this is the message DioError returns:
`SocketException: Failed host lookup: 'InvalidWebsite' (OS Error: No address associated with hostname, errno = 7)`

I was able to get the system error with the following code:
```
      if (e.error != null && e.error is SocketException) {
        print("Error Code [" +
            (e.error as SocketException).osError.errorCode.toString() +
            "]");
      }
```
Going to see if I can get the status code the same way.

**Comment by wendux** [comment]
`error.response.statusCode`

**Comment by searchy2** [comment]
Thanks! I figured it out but forgot to close this ticket :D
