### ISSUE TITLE
Upload file not detected by request laravel

### ISSUE THREAD

**Issue by rymesaint** [flutterchina/dio#324]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                          |      |
| Platform Version               |   1.5.4-hotfix2                              |      |
| Dio Version                    |   2.1.0                                  |      |
| Android Studio / Xcode Version | Visual Studio Code              |      |
| Repro rate                     | sometimes   |      |
| Repro with our demo prj        | -           |      |
| Demo project link              | - |      |

### Issue Description and Steps

```
FormData formData = FormData.from({
        'photo': UploadFileInfo(photo, basename(photo.path))
      });

Response response;
    try {
      response =  await _dio.post(url, data: formData, options: Options(
        headers: headers,
      ),
      onSendProgress: onSendProgress
      );
    } on DioError catch(e) {
      if(e.response != null) {
        throw Exception(e.response.data['meta']['message']);
      }
    }
    return response;
```

I have a problem with sending data from flutter android to backend laravel using $request->file('photo') the file data is always null, and then i found the problem that dio can only accepted by native php **$_FILES** instead using **$request->file('photo')** in laravel. Can you make it somehow when dio sending request to laravel backend **$request->file** so that it can accept the file.

**Comment by wendux** [comment]
https://stackoverflow.com/a/38226876/9461849

**Comment by gioVerdiansyah** [comment]
there are new update? I got some error
