### ISSUE TITLE
响应阶段 调用了未知实例方法FormatException::stackTrace

### ISSUE THREAD

**Issue by uaex** [flutterchina/dio#329]
抓包发现响应200正常,返回的也是常规的json
没有另外注入拦截器或者是转换器
异常信息:
DioError [DioErrorType.DEFAULT]: NoSuchMethodError: Class 'FormatException' has no instance getter 'stackTrace'.
Receiver: Instance of 'FormatException'
Tried calling: stackTrace

**Comment by uaex** [comment]
错误来自CookieJar插件中产生的throw new FormatException(
            "Invalid character in cookie value, code unit: '$codeUnit'");
但在_assureDioError函数中调用了err.stackTrace

**Comment by uaex** [comment]
是官方库的Cookie验证导致的
https://github.com/dart-lang/sdk/issues/37166
针对这种情况,我们要如何normalizeCookies?

**Comment by wendux** [comment]
首先升级dio至最新版，然后尝试升级Dart和Flutter，这个问题官方应该已经解了
