### ISSUE TITLE
Post multiple images to server

### ISSUE THREAD

**Issue by kamrancr7** [flutterchina/dio#330]
Single file post to a server is working fine, now i want to post multiple images to server that user selects from gallery, following is the code from documentation for uploading multiple files 
 
FormData formData = new FormData.from({
    "name": "wendux",
    "age": 25,
    "file1": new UploadFileInfo(new File("./upload.txt"), "upload1.txt"),
    // upload with bytes (List<int>)
    "file2": new UploadFileInfo.fromBytes(
        utf8.encode("hello world"), "word.txt"),
    // Pass multiple files within an Array
    "files": [
      new UploadFileInfo(new File("./example/upload.txt"), "upload.txt"),
      new UploadFileInfo(new File("./example/upload.txt"), "upload.txt")
    ]
});

my question is that how can i implement this in my code for images?? because i don't know that how many images are selected by user.

Following is the screenshot pf postman image_list key is an array key
![image](https://user-images.githubusercontent.com/29223946/58950489-5a415f80-87a8-11e9-9f5d-137ec6f41ca4.png)

**Comment by kamrancr7** [comment]
![unknown 1](https://user-images.githubusercontent.com/29223946/58953330-8e6c4e80-87af-11e9-9098-620ddb02b329.png)

**Comment by basselch** [comment]
I'm not sure if this is what you need, but I'm doing a similar thing and using [multi_image_picker ](https://pub.flutter-io.cn/packages/multi_image_picker) to allow the user to pick images. Here's the code I'm using for the upload:
```Dart
final imagesBytes = {};
for (Asset a in images) {
  final bytes = await a.requestOriginal();
  imagesBytes[a.identifier] = bytes.buffer.asUint8List();
}
final imagesData = images.map((a) => UploadFileInfo.fromBytes(imagesBytes[a.identifier], a.name)).toList();
final response = await Dio(_myBaseOptions()).post('page.php',
  data: FormData.from({
    'images[]': imagesData,
}));
```

Make sure to add the `[]` in your key for the images list. I struggled for hours trying to realize why I was getting only one file in the backend even when uploading multiple ones, but it worked after I changed my key from `images` to `images[]`

**Comment by kamrancr7** [comment]
i solved my issue with the following code:
`List uploadList = [];
    for (var imageFiles in _list) {
      uploadList.add(UploadFileInfo(File(imageFiles), "job.jpg"));
    }`
and then pass uploadList in a key value 
"image_list": uploadList

**Comment by SunnyBearLittle** [comment]
> i solved my issue with the following code:
> `List uploadList = [];`
> `for (var imageFiles in _list) { uploadList.add(UploadFileInfo(File(imageFiles), "job.jpg")); }`
> and then pass uploadList in a key value
> "image_list": uploadList

I do it in the same way, but why my springboot application cannot get list
`List<MultipartFile> imageList = new List();
    for (Asset asset in images) {
      ByteData byteData = await asset.getByteData();
      List<int> imageData = byteData.buffer.asUint8List();
      MultipartFile multipartFile = new MultipartFile.fromBytes(
        imageData,
        filename: 'load_image',
        contentType: MediaType("image", "jpg"),
      );
      imageList.add(multipartFile);
    }

    FormData formData = FormData.fromMap({
      "multipartFiles": imageList,
      // "blogTitle" : blogTitleController.text,
      // "blogContent" : blogContentController.text,
      // "blogUserId" : 8
    });`

**Comment by SunnyBearLittle** [comment]
> i solved my issue with the following code:
> `List uploadList = [];`
> `for (var imageFiles in _list) { uploadList.add(UploadFileInfo(File(imageFiles), "job.jpg")); }`
> and then pass uploadList in a key value
> "image_list": uploadList

'''
List<MultipartFile> imageList = new List();
    for (Asset asset in images) {
      ByteData byteData = await asset.getByteData();
      List<int> imageData = byteData.buffer.asUint8List();
      MultipartFile multipartFile = new MultipartFile.fromBytes(
        imageData,
        filename: 'load_image',
        contentType: MediaType("image", "jpg"),
      );
      imageList.add(multipartFile);
    }

    FormData formData = FormData.fromMap({
      "multipartFiles": imageList,
      // "blogTitle" : blogTitleController.text,
      // "blogContent" : blogContentController.text,
      // "blogUserId" : 8
    });
'''

**Comment by SunnyBearLittle** [comment]
> i solved my issue with the following code:
> `List uploadList = [];`
> `for (var imageFiles in _list) { uploadList.add(UploadFileInfo(File(imageFiles), "job.jpg")); }`
> and then pass uploadList in a key value
> "image_list": uploadList

I do it in the same way, but I cannot get my list. Could help me?
`List<MultipartFile> imageList = new List();
    for (Asset asset in images) {
      ByteData byteData = await asset.getByteData();
      List<int> imageData = byteData.buffer.asUint8List();
      MultipartFile multipartFile = new MultipartFile.fromBytes(
        imageData,
        filename: 'load_image',
        contentType: MediaType("image", "jpg"),
      );
      imageList.add(multipartFile);
    }

    FormData formData = FormData.fromMap({
      "multipartFiles": imageList
    });`

**Comment by Woyram** [comment]
> Single file post to a server is working fine, now i want to post multiple images to server that user selects from gallery, following is the code from documentation for uploading multiple files
> 
> FormData formData = new FormData.from({
> "name": "wendux",
> "age": 25,
> "file1": new UploadFileInfo(new File("./upload.txt"), "upload1.txt"),
> // upload with bytes (List)
> "file2": new UploadFileInfo.fromBytes(
> utf8.encode("hello world"), "word.txt"),
> // Pass multiple files within an Array
> "files": [
> new UploadFileInfo(new File("./example/upload.txt"), "upload.txt"),
> new UploadFileInfo(new File("./example/upload.txt"), "upload.txt")
> ]
> });
> 
> my question is that how can i implement this in my code for images?? because i don't know that how many images are selected by user.
> 
> Following is the screenshot pf postman image_list key is an array key
> ![image](https://user-images.githubusercontent.com/29223946/58950489-5a415f80-87a8-11e9-9f5d-137ec6f41ca4.png)

Please I am a little confused with how you uploaded multiple images. Are you using the package dio or the regular http package. And how will the api look like. Cos, I have tried all and I still can't get it to work.

**Comment by SunnyBearLittle** [comment]
> > Single file post to a server is working fine, now i want to post multiple images to server that user selects from gallery, following is the code from documentation for uploading multiple files
> > FormData formData = new FormData.from({
> > "name": "wendux",
> > "age": 25,
> > "file1": new UploadFileInfo(new File("./upload.txt"), "upload1.txt"),
> > // upload with bytes (List)
> > "file2": new UploadFileInfo.fromBytes(
> > utf8.encode("hello world"), "word.txt"),
> > // Pass multiple files within an Array
> > "files": [
> > new UploadFileInfo(new File("./example/upload.txt"), "upload.txt"),
> > new UploadFileInfo(new File("./example/upload.txt"), "upload.txt")
> > ]
> > });
> > my question is that how can i implement this in my code for images?? because i don't know that how many images are selected by user.
> > Following is the screenshot pf postman image_list key is an array key
> > ![image](https://user-images.githubusercontent.com/29223946/58950489-5a415f80-87a8-11e9-9f5d-137ec6f41ca4.png)
> 
> Please I am a little confused with how you uploaded multiple images. Are you using the package dio or the regular http package. And how will the api look like. Cos, I have tried all and I still can't get it to work.

This is my answer in the end. May it could help

`String url = "http://192.168.1.101:8989/users/user/sendBlog";
    List<MultipartFile> imageList = new List<MultipartFile>();
    if (null != blogUser_id) {
      for (Asset asset in images) {
        ByteData byteData = await asset.getByteData();
        List<int> imageData = byteData.buffer.asUint8List();
        MultipartFile multipartFile = new MultipartFile.fromBytes(
          imageData,
          filename: 'load_image',
          contentType: MediaType("image", "jpg"),
        );
        imageList.add(multipartFile);
      }
      FormData formData = FormData.fromMap({
        "multipartFiles": imageList,
        "blogTitle": blogTitleController.text,
        "blogContent": blogContentController.text,
        "blogUserId": blogUser_id
      });

      Dio dio = new Dio();
      var response = await dio.post(url, data: formData);`

**Comment by SunnyBearLittle** [comment]
> > Single file post to a server is working fine, now i want to post multiple images to server that user selects from gallery, following is the code from documentation for uploading multiple files
> > FormData formData = new FormData.from({
> > "name": "wendux",
> > "age": 25,
> > "file1": new UploadFileInfo(new File("./upload.txt"), "upload1.txt"),
> > // upload with bytes (List)
> > "file2": new UploadFileInfo.fromBytes(
> > utf8.encode("hello world"), "word.txt"),
> > // Pass multiple files within an Array
> > "files": [
> > new UploadFileInfo(new File("./example/upload.txt"), "upload.txt"),
> > new UploadFileInfo(new File("./example/upload.txt"), "upload.txt")
> > ]
> > });
> > my question is that how can i implement this in my code for images?? because i don't know that how many images are selected by user.
> > Following is the screenshot pf postman image_list key is an array key
> > ![image](https://user-images.githubusercontent.com/29223946/58950489-5a415f80-87a8-11e9-9f5d-137ec6f41ca4.png)
> 
> Please I am a little confused with how you uploaded multiple images. Are you using the package dio or the regular http package. And how will the api look like. Cos, I have tried all and I still can't get it to work.

this is my answer in the end.it could help upload images to your server.
```
String url = "http://192.168.1.101:8989/users/user/sendBlog";
    List<MultipartFile> imageList = new List<MultipartFile>();
    if (null != blogUser_id) {
      for (Asset asset in images) {
        ByteData byteData = await asset.getByteData();
        List<int> imageData = byteData.buffer.asUint8List();
        MultipartFile multipartFile = new MultipartFile.fromBytes(
          imageData,
          filename: 'load_image',
          contentType: MediaType("image", "jpg"),
        );
        imageList.add(multipartFile);
      }

      FormData formData = FormData.fromMap({
        "multipartFiles": imageList,
        "blogTitle": blogTitleController.text,
        "blogContent": blogContentController.text,
        "blogUserId": blogUser_id
      });

      Dio dio = new Dio();
      var response = await dio.post(url, data: formData);
```

**Comment by hovanhung98hust** [comment]
> > > Single file post to a server is working fine, now i want to post multiple images to server that user selects from gallery, following is the code from documentation for uploading multiple files
> > > FormData formData = new FormData.from({
> > > "name": "wendux",
> > > "age": 25,
> > > "file1": new UploadFileInfo(new File("./upload.txt"), "upload1.txt"),
> > > // upload with bytes (List)
> > > "file2": new UploadFileInfo.fromBytes(
> > > utf8.encode("hello world"), "word.txt"),
> > > // Pass multiple files within an Array
> > > "files": [
> > > new UploadFileInfo(new File("./example/upload.txt"), "upload.txt"),
> > > new UploadFileInfo(new File("./example/upload.txt"), "upload.txt")
> > > ]
> > > });
> > > my question is that how can i implement this in my code for images?? because i don't know that how many images are selected by user.
> > > Following is the screenshot pf postman image_list key is an array key
> > > ![image](https://user-images.githubusercontent.com/29223946/58950489-5a415f80-87a8-11e9-9f5d-137ec6f41ca4.png)
> > 
> > 
> > Please I am a little confused with how you uploaded multiple images. Are you using the package dio or the regular http package. And how will the api look like. Cos, I have tried all and I still can't get it to work.
> 
> this is my answer in the end.it could help upload images to your server.
> 
> ```
> String url = "http://192.168.1.101:8989/users/user/sendBlog";
>     List<MultipartFile> imageList = new List<MultipartFile>();
>     if (null != blogUser_id) {
>       for (Asset asset in images) {
>         ByteData byteData = await asset.getByteData();
>         List<int> imageData = byteData.buffer.asUint8List();
>         MultipartFile multipartFile = new MultipartFile.fromBytes(
>           imageData,
>           filename: 'load_image',
>           contentType: MediaType("image", "jpg"),
>         );
>         imageList.add(multipartFile);
>       }
> 
>       FormData formData = FormData.fromMap({
>         "multipartFiles": imageList,
>         "blogTitle": blogTitleController.text,
>         "blogContent": blogContentController.text,
>         "blogUserId": blogUser_id
>       });
> 
>       Dio dio = new Dio();
>       var response = await dio.post(url, data: formData);
> ```

something went wrong, i apply same but not work for me

**Comment by hovanhung98hust** [comment]
@SunnyBearLittle commented on May 31
something went wrong, i apply same but not work for me

**Comment by kiran321** [comment]
> @SunnyBearLittle commented on May 31
> this work for me

It is  uploading only one image, Not all selected images.
