### ISSUE TITLE
dio.post服务器返回403错误,并且包含message:" user not exists", 上层在catch error 时, error的response为null, 没办法获取错误

### ISSUE THREAD

**Issue by NetFly-VPN** [flutterchina/dio#332]
### New Issue Checklist

- [ 1 ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  flutter                          |      |
| Platform Version              1.5                             |      |
| Dio Version                    2.1.3                              |      |
| Android Studio  3.4.              |      |
| Repro rate                     all the time (100%)  |      |

### Issue Description and Steps
客户端post 登录请求到服务器(填写错误的用户名)
服务器返回403错误, message:user not exists
返回的异常DioError 为DioErrorType.Default, response null, DioError.error 显示的信息却是:
```
NoSuchMethodError: Class 'FormatException' has no instance getter 'stackTrace'.
Receiver: Instance of 'FormatException'
```
这个情况百分百出现, 我觉得只要服务器有response, 在任何情况下都应该把服务器的response 返回给上层, 而不应该是null, 实在不行可以吧最原始底层的response跑出来给上层, 上层也好根据具体情况做对应处理, 我现在就一脸抓瞎, 不知道该怎么做处理了

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by NetFly-VPN** [comment]
这个问题仍然存在

**Comment by LinXiaoTao** [comment]
新版本还有这个问题吗？我也遇到了。
类似 FormatException 这种错误，导致 onError 回调中 response 为 null，没办法获取 statusCode 之类的信息。

**Comment by xinlangzi** [comment]
这个问题一直到现在还存在，只要是4xx 错误的，服务器返回的错误信息都获取不到？这是为什么？

**Comment by xinlangzi** [comment]
@wendux 

这个问题一直到现在还存在，只要是4xx 错误的，服务器返回的错误信息都获取不到？请教下！

**Comment by cn1001wang** [comment]
有知道怎么解决的吗，后台丢出来的信息根本获取不到，比如后台验证登录密码不对，丢出xxx信息. response.data 一直为null
