### ISSUE TITLE
Dio freezes UI

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutterchina/dio#333]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | android                          |      |
| Platform Version               | 8.0                              |      |
| Dio Version                    | 2.1.17                                  |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.5 beta1              |      |
| Repro rate                     | all the time (100%) |      |
| Repro with our demo prj        | no |      |

### Issue Description and Steps

```
import 'package:device_kast_manager/di/injector.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:html/parser.dart' show parse;
import 'package:kiwi/kiwi.dart' as kiwi;

class ImageRepository {
  final Dio _api;

  ImageRepository(this._api);

  Future<List<String>> getTeamImages({CancelToken cancelToken}) async {
    final dio = kiwi.Container().resolve<Dio>(SIMPLE_DIO);
    print(DateTime.now().toString());
    final result = await dio.get<String>('https://icapps.com/team');
    print(DateTime.now().toString());
    return compute(parseHtml, result.data);
  }
}

Future<List<String>> parseHtml(String html) async {
  try {
    print(DateTime.now().toString());
    final body = parse(html).body;
    final employeeList = body.getElementsByClassName('employee');
    final list = employeeList.map((employeeElement) => employeeElement.getElementsByTagName('img')[0].attributes['src']).toList();
    print(DateTime.now().toString());
    return list;
  } catch (e) {
    return [];
  }
}
```

When your widget tree is just a ProgressIndicator your UI will freeze.  Am I doing something wrong? Most of the time the UI freezes a couple seconds before the call is finished

**Comment by vanlooverenkoen** [comment]
We worked all day on finding out why this api call blocks my UI. 
We improved one of our own libraries that had issues with http requests.
But we found that when executing the call with 
`http.get('https://icapps.com/team');` we had no issues. 

This leads us to believe we are doing something wrong with dio. Or the performance of dio is not great. Can you help us out?

**Comment by wendux** [comment]
Could you provide a min runnable demo?
