### ISSUE TITLE
Debug 模式下，第一次网络会很慢，30s以上！

### ISSUE THREAD

**Issue by z234009184** [flutterchina/dio#335]
Debug 模式下，第一次网络会很慢，30s以上！请求数据回来之后，再次请求就正常了，是什么原因呢？

**Comment by god-long** [comment]
我这Debug模式下，Dio请求在iOS设备上时好时坏，有时候请求挺快的，但有时候一段时间内请求都超时，大家有遇到过吗？

**Comment by z234009184** [comment]
对我也是iOS设备，debug模式下，第一次请求特别慢

**Comment by mzF414** [comment]
我的应用在安卓移动网络的情况下请求非常慢, 都是超时, 但是在iphone上很快 @wendux

**Comment by mzF414** [comment]
DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'xxx.xxxxx.com' (OS Error: No address associated with hostname, errno = 7)

**Comment by god-long** [comment]
> 我的应用在安卓移动网络的情况下请求非常慢, 都是超时, 但是在iphone上很快 @wendux

我的正好相反，在测试环境下，安卓机很快，基本不失败，到时iPhone好几分钟，坏几分钟。怎么都找不到原因......

**Comment by z234009184** [comment]
@wendux 作者可以帮忙查看下吗？

**Comment by wendux** [comment]
@mzF414  看看是否有网络权限

**Comment by mzF414** [comment]
有网络权限的, 我连公司内部的wifi请求很快就响应了, 我切到移动、联通、电信的时候就很慢, 经常超时. @wendux
