### ISSUE TITLE
获取Cookie 与发送的 cookie不一致

### ISSUE THREAD

**Issue by MrChen2016-08-27** [flutterchina/dio#337]
目前在做一个图形验证码功能，因为cookie不一致导致验证码无法验证，参考了其他 issues 保存和获取cookie, 但是发现获取到的cookie和实际cookie不一致.
关键代码

![1560390378(1)](https://user-images.githubusercontent.com/21265867/59397933-ebc05b00-8dc0-11e9-8b18-1a84ee8eae5a.png)

![1560390352(1)](https://user-images.githubusercontent.com/21265867/59397956-f67af000-8dc0-11e9-8cac-2704d60df84b.png)

调试结果:

![1560390328(1)](https://user-images.githubusercontent.com/21265867/59397993-15798200-8dc1-11e9-81e0-63a2a7bb232a.png)

**Comment by wendux** [comment]
1. 首先，你post的是一个子路径，但下面却是取得根路径取cookie.
2. 看header, 传了两个JSESSIONID, 也就是说子路径和根路径有同名cookie；对于这种情况， 建议业务最好避免这种情况，另外cookieJar库将会在下个版本处理一下这种case。

**Comment by SongZhaoJie** [comment]
你只怎么解决的我请求一个链接，总是请求头错误，这是我的代码，麻烦帮帮忙看看一下谢谢
这是我抓取iOS请求的参数，我模拟请求下面是代码
<img width="736" alt="截屏2019-12-26下午2 34 31" src="https://user-images.githubusercontent.com/29090582/71462193-862c3d00-27ed-11ea-8fc1-3adcd21542b4.png">
Map<String,dynamic> params ={
// "Host": "apihome.ishangbuluo.com",
 "Content-Type" : "application/json",

"Cookie": "PHPSESSID=213123132123",
"User-Agent": "AishanTribal/2.1.0 (iPhone; iOS 13.2.3; Scale/3.00)",
"Accept-Language": "zh-Hans-CN;q=1",
"Accept-Encoding": "gzip, deflate",
"Connection": "keep-alive",
"Accept": "/"

  };

var dio =  Dio(
);
var cookieJar=CookieJar();
  //http://apihome.ishangbuluo.com/versionCheck
  //http://www.mocky.io/v2/5e02db7e31000059006b2a14
  // dio.options.baseUrl='http://apihome.ishangclub.com/';
  // dio.options.headers=params;
  dio.interceptors..add(CookieManager(cookieJar));
  dio.options.headers=params;
  dio.options.baseUrl="apihome.ishangbuluo.com";
  // dio.options.contentType=Headers.jsonContentType;
  
  

  Response response= await dio.get("http://apihome.ishangbuluo.com/versionCheck");
