### ISSUE TITLE
No content even though contentLength was specified to be greater than 0: 134

### ISSUE THREAD

**Issue by samsoft00** [flutterchina/dio#338]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / Android                         |      |
| Platform Version               | >=2.1.0 <3.0.0                              |      |
| Dio Version                    | ^2.1.7                                  |      |
| Android Studio  | Android Studio 3.3.2              |      |

### Issue Description and Steps

I got while trying to make GET request to API

Exception occurred: DioError [DioErrorType.DEFAULT]: HttpException: No content even though contentLength was specified to be greater than 0: 134., 
`uri = https://app.meatified.com/api/v1/transactions/verify/1e7807a0-80b4-4951-b6f0-72b329010bda stackTrace: #0`

The GET request is not hinting my endpoint, See log below for more info

![dio](https://user-images.githubusercontent.com/5300891/59400685-3675af00-8d90-11e9-831f-f62b44a71a15.PNG)

Below is my Interceptor class
```
import 'dart:convert';
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:meatify/app/resources/firebase_auth_provider.dart';

class MeatityHttpInterceptor implements Interceptor {
  Map<String, dynamic> _header;
  FireBaseAuthProvider _auth;

  MeatityHttpInterceptor()  {
    _auth = new FireBaseAuthProvider();
    _header = {
      HttpHeaders.contentTypeHeader: "application/json"
    };
  }

  @override
  onError(DioError err) {
    // TODO: implement onError
    return null;
  }

  @override
  onRequest(RequestOptions options) async {
    //Hope this will work.
    FirebaseUser loggedInUser = await _auth.currentUser();
    
    if(loggedInUser != null){
      String token = await loggedInUser.getIdToken(refresh: true);
      _header.addAll({HttpHeaders.authorizationHeader: token});
    }

    options.connectTimeout  = 10000;
    options.responseType    = ResponseType.json;
    options.baseUrl         = "https://app.meatified.com/api/v1";
    options.contentType     = ContentType.parse("application/json");
    options.receiveTimeout  = 10000;
    options.headers         = _header;

    print('send request：path:${options.path}，baseURL:${options.baseUrl}');
    return options;
  }

  @override
  onResponse(Response response) {
    print('HTTP INTERCEPTOR RESPONSE');
    print(response.data);
    // print(response.realUri);
    return null;
  }
  
}
```

Will appreciate your quick response on this issue.

**Comment by wendux** [comment]
please update to latest version and retry.

**Comment by softboy99** [comment]
already latest version. i have same problem.

**Comment by wjy397** [comment]
> already latest version. i have same problem.
Have you solved the problem

**Comment by wjy397** [comment]
Have you solved the problem

**Comment by UttamPanchasara** [comment]
Facing same issue, when calling multiple APIs at the same time, like POST and GET at the same time when POST with body content and GET without body content, And somehow the GET request header get override by POST in result dio throws exception saying GET request does not have body but the content-length is specified,

Anyone else facing this kind of issue which above scenario? and solution if you have?

**Comment by wjy397** [comment]
> Facing same issue, when calling multiple APIs at the same time, like POST and GET at the same time when POST with body content and GET without body content, And somehow the GET request header get override by POST,
> In result dio throws exception saying GET request does not have body but the content-length is specified,
> 
> To solve: I have added interceptor to remove content-length header while requesting but no luck!
> 
> Anyone else facing this kind of issue and above scenario? Any solution?

Don't redefine Headers  : options.headers = headers;
should options.headers['xxx']=xxx;
hope this helps
