### ISSUE TITLE
Post image in the right way, but sent null?

### ISSUE THREAD

**Issue by XenonChau** [flutterchina/dio#339]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | macOS Mojave                          |      |
| Platform Version               | 10.14.4 (18E226)                              |      |
| Dio Version                    | 2.1.5                                 |      |
| Xcode Version | 10.2.1 (10E1001)              |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        | not sure if it's backend's issues.          |      |
| Demo project link              | N/A |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Here is my code:

```dart
// fetch file from gallery.
var imageFile = await ImagePicker.pickImage(source: ImageSource.gallery);

// then console log:
// flutter: File: '/Users/xxxx/Library/Developer/CoreSimulator/Devices/A8334045-EBBF-4984-B8F8-B779EEB7B10E/data/Containers/Data/Application/277A5762-2E6D-445E-8797-631EA9ADAB59/tmp/image_picker_B1F8E4A1-E22C-40F9-B76F-7BB602A151FF-79551-0001A0E21B7E7FA6.jpg'

// image_picker_B1F8E4A1-E22C-40F9-B76F-7BB602A151FF-79551-0001A0E21B7E7FA6.jpg
var imageName = imageFile.path.split('/').last;

// jpg
var imageType = imageName.split('.').last;

// replace 'jpg' with 'jpeg'
imageType = imageType == "jpg" ? "jpeg" : imageType;

// post request.
dio
        .post("/upload",
            queryParameters: FormData.from({
              "images": UploadFileInfo(imageFile, imageName,
                  contentType: ContentType.parse("image/$imageType"))
            }))
        .then((response) {
      print(response);
    });

// then console log:
// flutter: ----dio-boundary-3410544964
// Content-Disposition: form-data; name="images"; filename="image_picker_B1F8E4A1-E22C-40F9-B76F-7BB602A151FF-79551-0001A0E21B7E7FA6.jpg"
// Content-Type: image/jpeg
// ����    <---- I think this is the image binary.
```

By using other tools, like postman or paw.

postman set body with form-data, chose value type with "File", it works.
paw set body with Multipart, right click to add a File Content, it works.

I don't know what type will 'UploadFileInfo' actually turns image file into?

**Comment by XenonChau** [comment]
Sometime, there was an exception with php logs:
```bash
[2019-06-14 14:53:51] local.INFO: Instance+of+'UploadFileInfo'
```

**Comment by XenonChau** [comment]
That's awkward, I just put the files into parameters.

**Comment by arpandesai** [comment]
how did you resolve this issue?
I am getting the same issue.
