### ISSUE TITLE
Adding path dynamically

### ISSUE THREAD

**Issue by akshaybenk** [flutterchina/dio#343]
I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |flutter                      |      |
| Platform Version               |v1.5.4-hotfix.2                             |      |
| Dio Version                    | 2.1.7                                 |      |
| Android Studio | Android Studio 3.4              |      |

Issue : Not able to add @Path parameter using dio
Lets say we have a url below, and using retrofit we can put the value dynamically for  'PRODUCT_ID' using @Path 
some.com/test/{PRODUCT_ID}

How do i achieve this in dio , I tried using the extras parameters but did not get the result.

The response of dio :DioError [DioErrorType.RESPONSE]: Http status error [404]

This could be due to the parameter that am not able to set.
Any help appreciated
Thanks in advance

**Comment by dew-ankurs** [comment]
I am also facing this issue. Please help to solve this.
