### ISSUE TITLE
Use FutureOr<dynamic> in interceptors

### ISSUE THREAD

**Issue by aloisdeniel** [flutterchina/dio#346]
Hello,

I'm a little bit confused on how to implement an asynchronous interceptor. The `onRequest` and `onResponse` return `dynamic` while stated that they can be asynchronous in the documentation. 

```dart
class CustomInterceptor extends Interceptor { 
    @override
    onRequest(RequestOptions options) async {
       if(options.extra["custom"]) {
           await customProcess(options);
       }
       return await base.onRequest(options); // <- Don't know what is returned by base, but could potentially be a Future since Interceptors can be chained
    }
}
```

While awaiting a value that isn't `Future` seems to work, a better choice would be to use `FutureOr<dynamic>` instead to make it clear.

**Comment by wendux** [comment]
Fixed in v2.1.8
