### ISSUE TITLE
need upload file notification with progress bar

### ISSUE THREAD

**Issue by cgowthamanmca** [flutterchina/dio#348]

**Comment by wendux** [comment]
```dart
response = await dio.post(
  "http://www.dtworkroom.com/doris/1/2.0.0/test",
  data: {"aa": "bb" * 22},
  onSendProgress: (int sent, int total) {
    print("$sent $total");
  },
);
```

**Comment by wreyford** [comment]
Hello Wendux,
Been unable to successfully implement onSendProgress.
The following snippet below is self explanatory.
The progress prints just fine to the console output in ide.
The _syncBlocs are added, but only executed once the upload complete.
How do I get realtime upload feedback that I can use to display a progress bar in flutter, while upload busy, as currently I get them all at once at end of upload.
Thx.

 try {
      print('Request URL: $postPhotoImageURL with name = $photoName');
      Response response = await _dio.post(
        postPhotoImageURL,
        data: formData,
        onSendProgress: (int sent, int total) {
          print("$sent $total");
          _syncBloc.add(SyncUploadProgress(sent,total));
        },
      );
