### ISSUE TITLE
含有dio请求的crash

### ISSUE THREAD

**Issue by diaotongt** [flutterchina/dio#351]
在练习flutter的网络请求，使用的dio（2.1.0版本），项目在iOS设备上运行时第一次总会闪退，可能是苹果手机对APP请求网络都有一个验证需要用户同意使用网络，而在验证没有通过时就请求网络，就会出现这种闪退。在三个demo中，每次运行的第一次都会出现这种闪退。请问如何解决。

**Comment by JacobWang** [comment]
ddddff
