### ISSUE TITLE
Is there a way to differentiate between no internet and bad host ?

### ISSUE THREAD

**Issue by modulovalue** [flutterchina/dio#355]
When trying to GET a URL like google.com1 with an internet connection
the following error is thrown: 

`flutter: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'google.com1' (OS Error: nodename nor servname provided, or not known, errno = 8)`

When trying to GET a URL like google.com without an internet connection
the same error is throw:

`flutter: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'google.com' (OS Error: nodename nor servname provided, or not known, errno = 8)`

Is there a way to differentiate the two error cases? If not, then why?

**Comment by modulovalue** [comment]
Yes, this is still an issue.

**Comment by amreniouinnovent** [comment]
@modulovalue it could be an extension to the client not by the client itself because it has to ping to google website or similar websites
check my answer on StackOverflow maybe it could help
https://stackoverflow.com/questions/49648022/check-whether-there-is-an-internet-connection-available-on-flutter-app/56920492#56920492

**Comment by modulovalue** [comment]
@amreniouinnovent thank you for the link. I see your solution uses flutters connectivity plugin. I'd like to not depend on flutter for that part of my logic. I'm curious why this differentiation cannot be made just with an exception alone.

**Comment by amreniouinnovent** [comment]
@amreniouinnovent you can use **interceptor** before every call 
google.com is always reliable IP while your server maybe not
how would Dio call knows if  unknown-website.com is a bad host or no internet without a ping to googe.com?

**Comment by modulovalue** [comment]
> you can use interceptor before every call

Yes, I guess you're correct. a clean solution could be achieved that way.


>how would Dio call knows if unknown-website.com is a bad host or no internet without a ping to googe.com?

I am not too familiar with the TCP/IP protocol, but I speculate the `or` in `(OS Error: nodename nor servname provided, or not known, errno = 8)` is the reason why this differentiation is not possible.

Each HTTP call needs to resolve the URL into an IP address. This happens through a DNS. 
If the DNS can't be reached then this should mean that there is no internet connection. If the DNS didn't know how to resolve the provided url, then the url was invalid but an internet connection was present.

>google.com is always reliable IP while your server maybe not

Pinging google is not a satisfactory solution for all application like those focused around privacy.


@amreniouinnovent thanks for the discussion, now I'm not even sure if Dio could do anything about it. I'll probably have to ask at dart-lang/sdk

**Comment by yuhaocan** [comment]
> 

now how to do  let it slove ?
