### ISSUE TITLE
DioError [DioErrorType.DEFAULT]:

### ISSUE THREAD

**Issue by waitwalker** [flutterchina/dio#359]
### New Issue Checklist
Dior 请求异常,结果正常返回,状态码200,在StreamHandlerTransformer报错.

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios / android                          |      |
| Platform Version               | e.g.  1.5.0 / 12.0 / 9.0                              |      |
| Dio Version                    | e.g.  2.1.0 / 1.0.17                                  |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.4 / Xcode 10.2.1              |      |

### Issue Description and Steps

DioError [DioErrorType.DEFAULT]: type '_StreamHandlerTransformer<List<int>, List<int>>' is not a subtype of type 'StreamTransformer<Uint8List, List<int>>' of 'streamTransformer'#0      Stream.transform (dart:async/stream.dart)
    #1      DefaultTransformer.transformResponse (package:dio/src/transformer.dart:102:48)
    <asynchronous suspension>
    #2      Dio._makeRequest (package:dio/src/dio.dart:771:38)
    <asynchronous suspension>
    #3      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:710:22)
    #4      _rootRunUnary (dart:async/zone.dart:1132:38)
    #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
    #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
    #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
    #9      Future._complete (dart:async/future_impl.dart:473:7)
    #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
    #11

**Comment by prasant10050** [comment]
Please check this issue..My Production has crashed..

**Comment by wendux** [comment]
duplicated #357
