### ISSUE TITLE
[Request Feature] Add Query param to Options

### ISSUE THREAD

**Issue by lyquocnam** [flutterchina/dio#36]
Dear author, thanks for useful package.
I think we should add Query param to Options for easily use with GET method like this:
```
/products?search=How to become a hero like LyNam
```
Or we can allow add `Uri` type with `path` param beside just `String`.

Currently, i make by hand like this:
```dart
var url = _buildPath(path, {
  'search': 'How to become a hero like LyNam'
});

var result = await dio.post(url,....);

String _buildPath(String path, Map<String, String> query) {
    String url = path;
    if (query != null) {
      url += "?";
      var temp = "";
      query.forEach((k, v) {
        if (v != null && v.isNotEmpty)
          temp += "&$k=$v";
      });

      url += temp.replaceFirst("&", "");
      url = url.replaceFirst("?", "", url.length - 1);
    }
    
    return url;
  }

**Comment by wendux** [comment]
you can use `TransFormer.urlEncodeMap(queryMap)` directly:

```dart
var queryMap={
  'search': 'How to become a hero like LyNam'
}；
var result = await dio.post('$url?${TransFormer.urlEncodeMap(queryMap)}',....);
```

**Comment by lyquocnam** [comment]
yes, we can process the string, but if dio can support, that will be simpler and safer by parse from URI in dio core

**Comment by lyquocnam** [comment]
i remember i did like that, but the url be dupplicate with something like:
```
http://demo.com/http://demo.com/...........
```
i think dio has not handled full url like that yet.

**Comment by wendux** [comment]
If the `path` starts with "http:" or "https:", the baseUrl will be ignored.  This feature will not be supported. Thanks !
