### ISSUE TITLE
有没有配置可以过滤掉queryParameters中值为null的参数？

### ISSUE THREAD

**Issue by CCY0122** [flutterchina/dio#361]
有没有配置可以过滤掉queryParameters中值为null的参数？

**Comment by programadorthi** [comment]
Dio should provide a way to avoid placing null query parameter in the URL, such as Retrofit.

```
void _fetchOptionalData(String optionalParameter) async {
    var response = await dio.get('/somepath', queryParameters: {'param': optionalParameter});
    // do something
  }
```

When I call: `_fetchOptionalData(null)` then result `http://endpoint/somepath?param=null` when the expected is `http://endpoint/somepath`.

You can put a `boolean safeQuery` parameter in the `_mergeOptions` method with default `false` and when it be true you apply `queryParameters.removeWhere((key, value) => value == null);` before merge with default queryParameters in the line below:

https://github.com/flutterchina/dio/blob/cad527f645edb52b3927c6cfdce7e3aa30f96090/package_src/lib/src/dio.dart#L948

**Comment by samuelg123** [comment]
I'm really need this fix. Thanks for working in this issue @programadorthi

**Comment by wendux** [comment]
Fixed, please upgrade to latest version and try again.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
