### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength.

### ISSUE THREAD

**Issue by Qudratullo** [flutterchina/dio#362]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |    
| ------------------------------ | ----------------------------------------------------- |
| Platform Name                  | e.g. flutter / android                          |
| Dio Version                    | e.g.  2.1.10                                  |
| Android Studio | Android Studio 3.3.2              |
| Repro rate                     | sometimes ~10%   |

### Issue Description and Steps
**I uploaded a picture and then got this error. Interestingly, this error is sometimes reproduced with one file.**

E/flutter ( 5836): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength. 393380 bytes written while expected 344261. [eQÇBÊµÀ%­ý¼·ÓÇòrØ-nG+ð1Qð®~

**Comment by wendux** [comment]
fixed in latest version

**Comment by jinjilynn** [comment]
not fixed in 3.0.9 if the audio is just 14seconds

**Comment by FrancisIje** [comment]
I'm experiencing it too, but when the first audio is more than 14 secs, subsequent audios can be less. I have no idea why this is like that

**Comment by FrancisIje** [comment]
> not fixed in 3.0.9 if the audio is just 14seconds

how did you work around it?

**Comment by kuhnroyal** [comment]
This issue was closed 5 years ago. Please open a new issue with a reproducible sample.
