### ISSUE TITLE
为什么我获取不到这个网站的数据呢？

### ISSUE THREAD

**Issue by earclink** [flutterchina/dio#364]
数据地址：https://haohuo.snssdk.com/productcategory/getShopList?shop_id=kizqLu&type=5&sort=1&page=1&size=10&b_type_new=0

以上地址通过浏览器可以直接看到，但是为什么我通过Dio获取不到呢？

**Comment by wendux** [comment]
我这边可以获取到，你升级到最新版试试，我的代码如下：
```dart
  Response response = await Dio().get("https://haohuo.snssdk.com/productcategory/getShopList?shop_id=kizqLu&type=5&sort=1&page=1&size=10&b_type_new=0");
  print(response);
```

**Comment by wendux** [comment]
我这边可以获取到，你升级到最新版试试，我的代码如下：
```dart
  Response response = await Dio().get("https://haohuo.snssdk.com/productcategory/getShopList?shop_id=kizqLu&type=5&sort=1&page=1&size=10&b_type_new=0");
  print(response);
```

**Comment by ChessLuo** [comment]
@wendux  我用了最新版dio: ^2.1.16，请求确实是没有数据
![image](https://user-images.githubusercontent.com/23535605/63921586-a7fef880-ca75-11e9-896b-0a91ee0967c7.png)
