### ISSUE TITLE
post请求如果参数，response.body一直为空，没有任何信息输出，如果不传参数，可以返回一些错误信息，不知道什么原因

### ISSUE THREAD

**Issue by wukongGit** [flutterchina/dio#366]
var url = Constants.URL_SMS;

    var dio = new Dio();
    Response response = await dio.post(url,
        data: {
          "account_type": "0",
          "msg_type": "3",
          "phone_area": "86",
          "type": "1",
          "phone": "18888888888"
        },

    );
    if (response.statusCode == 200) {
      // If the call to the server was successful, parse the JSON
      print("response.data: ${response.data}");
      //return Login.fromJson(json.decode(response.data));
    } else {
      // If that call was not successful, throw an error.
      throw Exception('Failed to load post');
    }
    return "";
如果把data去掉，可以打印出返回结果：
response.data: {sMsg: Signature error, iRet: -109}
不去掉的话，就打印：
response.data: 
没有任何信息输出，按道理也应该输出一些信息呀，不管成功还是失败

**Comment by 370966584** [comment]
设置   contentType: ContentType.parse("application/x-www-form-urlencoded"), 试下

**Comment by wukongGit** [comment]
> 设置 Dio options contentType: ContentType.parse("application/x-www-form-urlencoded"), 试下

试过了   没用

**Comment by taok109** [comment]
data = FormData.from({
      "account_type": "0",
      "msg_type": "3",
      "phone_area": "86",
      "type": "1",
      "phone": "18888888888"
    });
