### ISSUE TITLE
"type 'List<int>' is not a subtype of type 'Uint8List'" 

### ISSUE THREAD

**Issue by muyi0728** [flutterchina/dio#367]
I upgraded to 2.1.11 and found that the problem still exists

 FormData formData = FormData.from({
      "file": UploadFileInfo.fromBytes(result, '${key}Image'),
      "key": key
    });

**Comment by muyi0728** [comment]
Only downgrading to 2.1.7 is working properly

**Comment by hcaz** [comment]
Likely related to https://github.com/dart-lang/sdk/issues/36900

**Comment by wendux** [comment]
@muyi0728 please upgrade to v2.2.0 and try again.
