### ISSUE TITLE
Empty result list as String in response.data instead of json

### ISSUE THREAD

**Issue by egodefroy** [flutterchina/dio#368]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter (ios)                      |      |
| Platform Version               | flutter 1.8.0                              |      |
| Dio Version                    | 2.1.11                                  |      |
| Android Studio / Xcode Version |  Xcode 10.2.1              |      |
| Repro rate                     | all the time (100%)    |      |
| Repro with our demo prj        |  not tested             |      |
| Demo project link              |  see below code |      |

### Issue Description and Steps

When the response data is an empty list ([]), its type is a String and not json

````
  var dio = Dio();
  dio.options.baseUrl = 'https://demo-formation.egylis.com/MDFormation/admin/webServices/traduction.php?f=commonMessages&lang=c';
  dio.options.headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  };
  try {
    final response = await dio.get(url);
    if (response.statusCode != 200) {
      return;
    }
    print('response.data is String ${(response.data is String)}');
````

**Comment by wendux** [comment]
![image](https://user-images.githubusercontent.com/20411648/60883829-d6363800-a27d-11e9-8624-56c765c11c4e.png)
 The response content-type should be  "application/json" .

**Comment by egodefroy** [comment]
@wendux: thanks. Sorry, regression from the site..
