### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: type '_StreamHandlerTransformer<List<int>, List<int>>' is not a subtype of type 'StreamTransformer<Uint8List, List<int>>' of 'streamTransformer'#0      Stream.transform (dart:async/stream.dart) 

### ISSUE THREAD

**Issue by haomeirong** [flutterchina/dio#372]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios / android                          |      |
| Platform Version               | e.g.  1.8.1 / 10.14.5 / 4.0                              |      |
| Dio Version                    | e.g.  2.1.8                                   |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.4.1 / Xcode 10.2.1              |      |
| Repro rate                     | e.g. all the time (100%)  |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps
flutter upgrade latest, 
 Dio dio = new Dio();
    Response response=await dio.get("https://www.google.com/");
    print(response.data);

   lease fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: type '_StreamHandlerTransformer<List<int>, List<int>>' is not a subtype of type 'StreamTransformer<Uint8List, List<int>>' of 'streamTransformer'#0      Stream.transform (dart:async/stream.dart)
    #1      DefaultTransformer.transformResponse (package:dio/src/transformer.dart:102:48)
    <asynchronous suspension>
    #2      Dio._makeRequest (package:dio/src/dio.dart:771:38)
    <asynchronous suspension>
    #3      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:710:22)
    #4      _rootRunUnary (dart:async/zone.dart:1132:38)
    #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
    #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
    #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
    #9      Future._complete (dart:async/future_impl.dart:473:7)
    #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
    #11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
    #12     _rootRun (dart:async/zone.dart:1120:38)
    #13     _CustomZone.run (dart:async/zone.dart:1021:19)
    #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #16     _rootRun (dart:async/zone.dart:1124:13)
    #17     _CustomZone.run (dart:async/zone.dart:1021:19)
    #18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by haomeirong** [comment]
dio: ^2.1.13  问题仍然存在啊

**Comment by apm29** [comment]
same issue

**Comment by haomeirong** [comment]
解决了

**Comment by wendux** [comment]
清空本地package缓存，重新下载一下再试

**Comment by SSuperYe** [comment]
> 解决了

咋解决的，说一下啊老铁
