### ISSUE TITLE
Dio tests with Mockito.

### ISSUE THREAD

**Issue by bmatheus91** [flutterchina/dio#374]
How can i mock Dio requests with Mockito?

Would like to do something like this:

`
when(
          client.post(Api.BASE_URL_AUTH + "/auth",
              data: credentials.toJson(),
              options: Options(headers: {
                'Content-type': 'application/json',
                'Accept': 'application/json'
              }))).thenAnswer((_) async => Response(data: {
            "data": {
              "id": "5d166a5e9081294ed4b71016",
              "personCode": "221205",
              "username": "user.mock",              
            }
          }, statusCode: 200));
`

**Comment by wendux** [comment]
You can custom adapter to mock. A test example is[ here](https://github.com/flutterchina/dio/tree/master/package_src/test).

**Comment by zaralockheart** [comment]
actually the mocking works without the `Options`. Feels weird that after adding `Options`, `Dio` can't be mocked / only return null if mocked. As a workaround, I introduced another layer for `Dio`.

**Comment by bmatheus91** [comment]
Actually i achieved Mocking requests with Dio and using options. As soon i'm available i will try to write a post on Medium about it

**Comment by zaralockheart** [comment]
@bmatheus91 can I ask for gist of the mocking?

**Comment by cahyofendhi** [comment]
i've tried `dio` with `mockito `, you can check this https://github.com/cahyofendhi/Flutter-Cinema/blob/develop/test/service_test.dart, may be can help you @zaralockheart

**Comment by zaralockheart** [comment]
@cahyofendhi thanks for the suggestion, but from the example, `dio` is wrapped in another class (in this case `Service` class) and that instance is the one that is mocked. Yeah, it does do the work (and currently I am doing it this way too). But I am looking for direct mock to `dio`. cheers.

**Comment by hjJunior** [comment]
I'm trying to use Mockito to create a mocked Adapter, but I'm getting an exception

### The example
1. I defined `DioAdapterMock` as subclass of Mock
2. I create instance of mock
3. And I mock the calls for `dioAdapterMock.fetch`

```dart
class DioAdapterMock extends Mock implements HttpClientAdapter {}

void main() {
 group('UserRemoteDataSource', () {
   final Dio dio = Dio();
   UserRemoteDataSource dataSource;
   DioAdapterMock dioAdapterMock;

   setUp(() {
     dioAdapterMock = DioAdapterMock();
     dio.httpClientAdapter = dioAdapterMock;
     dataSource = UserRemoteDataSource(dio);
   });

   group('login', () {
     test('when credentials are valid should return UserLoginResponse with token', () async {
       final userCredentials = UserLoginRequestBody(password: 'password', email: 'email');
       final responsePayload = json.encode({ 'token': 'token' });
       final httpResponse = ResponseBody.fromString(responsePayload, 200);

       when(dioAdapterMock.fetch(any, any, any)).thenAnswer((_) async => httpResponse);

       final subject = await dataSource.login(userCredentials);
       final expected = UserLoginResponse(token: 'token');

       expect(subject, expected);
     });
   });
 });
}
```` 

### The Exception
It looks a casting exception, but I can't get the reason, since I'm using json.encode to convert my map to String

```
package:dio/src/dio.dart 886:9  DioMixin._request.<fn>
dart:async                      _completeOnAsyncReturn
package:dio/src/dio.dart        DioMixin._dispatchRequest
===== asynchronous gap ===========================
dart:async                      Future.catchError
package:dio/src/dio.dart 884:8  DioMixin._request

DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>'
#0      DioMixin.assureResponse (package:dio/src/dio.dart:1120:9)
#1      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:883:14)
#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#3      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
```

**Comment by hjJunior** [comment]
### Update

I just updated the ResponseBody to pass the headers and define contentType and it solved!

```dart
       final httpResponse = ResponseBody.fromString(responsePayload, 200, headers: {
         Headers.contentTypeHeader: [Headers.jsonContentType],
       },);
```

**Comment by bmatheus91** [comment]
As requested, this is how i do my tests with Dio and Mockito

### api_task.dart

```dart
class APITask {
  static final _log = Logger('APITaskDatasource');

  final Dio client;

  APITask({this.client});

  @override
  Future<void> updateTask(Task task) async {
    await client.patch(
      url: '/v1/calendar/tasks/${task.id}status=${TaskStateExtension.getString(task.state)}&finish=$now',
    );
  }
}
```

### api_task_test.dart
```dart
class MockDioClient extends Mock implements Dio {}

void main() {
  Dio client;
  APITask source;

  setUp(() {
    client = MockDioClient();
    source = APITask(client);
  });

  group('updateTaskState', () {
    test('should update Task state with correct given ID and Status', () async {
      when(client.patch(any, queryParameters: anyNamed('queryParameters')))
          .thenAnswer((realInvocation) async =>
              Response(data: json.decode(fixture('task.json'))));

      await source.updateTaskState('7dYZkG4ZMSBseIz6uwVr',
          state: TaskState.accepted);

      verify(client.patch('/v1/calendar/tasks/7dYZkG4ZMSBseIz6uwVr',
          queryParameters: {'status': 'ACCEPTED'}));
      verifyNoMoreInteractions(client);
    });

    test('should throw a Exception when the request fails', () async {
      when(client.patch(any, queryParameters: anyNamed('queryParameters')))
          .thenThrow(DioError(
              request:
                  RequestOptions(method: 'PATCH', path: '/v1/calendar/tasks'),
              response: Response(
                  statusCode: 400, statusMessage: 'Falha na requisição')));

      expect(
          () async => await source.updateTaskState('7dYZkG4ZMSBseIz6uwVr',
              state: TaskState.accepted),
          throwsA(TypeMatcher<DioError>()));
    });
  });
}
```

**Comment by shan-shaji** [comment]
How can i do this with get request?

**Comment by mateuscelio** [comment]
Thanks @bmatheus91 this is useful when using with named argument option:


```dart
when(mockHttpClient.get('url',  options: anyNamed('options'))).thenAnswer(...);
```

**Comment by JeganGitHub** [comment]
> Thanks @bmatheus91 this is useful when using with named argument option:
> 
> ```dart
> when(mockHttpClient.get('url',  options: anyNamed('options'))).thenAnswer(...);
> ```

Thanks a lot and appreciate it, your answer helped me to resolve a unit test which I have been fighting to solve it.
