### ISSUE TITLE
raw请求使用方式？

### ISSUE THREAD

**Issue by mcxinyu** [flutterchina/dio#375]
请问 postman 中 body->raw->JSON(application/json) 这种方式使用 dio 应该怎么传值呢？
![image](https://user-images.githubusercontent.com/9566116/61168102-f8300300-a57a-11e9-942f-0909288c902f.png)

**Comment by mcxinyu** [comment]
解决了

**Comment by LittleHans8** [comment]
@mcxinyu ,遇到同样的问题,请问下是如何解决的?

**Comment by mcxinyu** [comment]
@LittleHans8 直接把对象或者map放到 data 里
![image](https://user-images.githubusercontent.com/9566116/62093246-2ae03800-b2ab-11e9-8e83-78137e363639.png)
