### ISSUE TITLE
HttpException: Connection closed before full header was received

### ISSUE THREAD

**Issue by GeekLZL** [flutterchina/dio#376]
[√] Flutter (Channel master, v1.8.2-pre.33, on Microsoft Windows [Version 10.0.17763.615], locale zh-CN)
    • Flutter version 1.8.2-pre.33 at C:\flutter
    • Framework revision e3ee5c6bbb (28 hours ago), 2019-07-13 16:02:09 -0700
    • Engine revision 919e353236
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidSdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received

**Comment by parthgodhani** [comment]
did you get any solution @GeekLZL

**Comment by BelongsH** [comment]
I have encountered this problem。I found post big data to server has this error .i close vpn。everything is ok 。So,I try change dio options  sendTimeout value. It works for me！

**Comment by yaochangliang159** [comment]
请问解决了吗，我也遇到了这个问题，我用的Dio 4.0.0
