### ISSUE TITLE
不抛出异常

### ISSUE THREAD

**Issue by YQjiuhao** [flutterchina/dio#377]
return await _listenCancelForAsyncTask<Response<T>>(
            cancelToken, _onError<T>(err));
出现异常。
DioError (DioError [DioErrorType.RESPONSE]: Http status error [500])

已经做异常抛出处理了，刚更新到2.1.13 Flutter SDK 1.7.8遇到这种情况，之前没有

**Comment by big-MuMu** [comment]
I have the same issue

**Comment by huanxsd** [comment]
same issue，在flutter: 1.7.8上出现。在1.5.4上正常

**Comment by guokangf** [comment]
same issue, dio: ^2.1.0, flutter: ^1.7.8

**Comment by guokangf** [comment]
可能是 vscode 的问题,
![image](https://user-images.githubusercontent.com/17818179/61573307-ce2c9280-aade-11e9-8059-a3b3f26450b3.png)

尝试关闭这两个

**Comment by YQjiuhao** [comment]
> 可能是 vscode 的问题,
> ![image](https://user-images.githubusercontent.com/17818179/61573307-ce2c9280-aade-11e9-8059-a3b3f26450b3.png)
> 
> 尝试关闭这两个

你是对的

**Comment by huanxsd** [comment]
All Exceptions一直是关闭的。Uncaught Exceptions是未捕获异常，不能关。。因为我外层是已经捕获了，但是app还是会因为未捕获而中断。
你们不能因为你们的库有bug，而让开发者关掉未捕获异常选项，这很搞笑。

**Comment by ovaldi** [comment]
> All Exceptions一直是关闭的。Uncaught Exceptions是未捕获异常，不能关。。因为我外层是已经捕获了，但是app还是会因为未捕获而中断。
> 你们不能因为库有问题，而让开发者关掉未捕获异常选项。这不是解决问题，而是忽略问题。

+10086

**Comment by fg2q1q3q** [comment]
这问题不处理就关闭了，也真是可以

**Comment by moonljt521** [comment]
[看看这个解决了没](https://github.com/flutterchina/dio/issues/398)

**Comment by huanxsd** [comment]
对这个项目很失望，一个这么重要的库，跟开玩笑似的。已经一个多月了，没有处理。

**Comment by YQjiuhao** [comment]
> 对这个项目很失望，一个这么重要的库，跟开玩笑似的。已经一个多月了，没有处理。

早就处理了，你更新到最新版本

**Comment by xuetongiqn** [comment]
dio 2.1.16 下依然报这个错

**Comment by wendux** [comment]
@huanxsd @fg2q1q3q  我这边一直复现不了，我这边的版本是2.1.16，flutter sdk 是v1.8.1-pre.21, 我用下面代码在断网的情况下测试是能catch到错误的：
```dart

import 'package:dio/dio.dart';
void getHttp() async {
  try {
    Response response = await Dio().get("http://www.google.com");
    print(response);
  } catch  (e) {
    print("--"*20);
    print(e);
  }
}

main() async{
  await getHttp();
}
```
控制台输出：
![image](https://user-images.githubusercontent.com/20411648/64665792-695e3a80-d486-11e9-8c24-136ee66d0be6.png)

另外如果future用catchError能捕获错误而用try...catch不行的话，这就是dart sdk的bug，try...catch是语言级别支持的，而dio只是对future的使用。
看大家反馈，感觉很可能是flutter 1.7.8中携带的dart sdk的bug，建议大家升级flutter至最新版本再试，如还有问题，可以详细描述一下复现步骤，和版本信息。

**Comment by fg2q1q3q** [comment]
这个问题跟环境有很大关系，1.7.8的时候有，估计更新flutter之后就没了

**Comment by fxxkscript** [comment]
同样遇到一样的问题，catchError 能捕获，try catch不行！

**Comment by fantasy525** [comment]
android studio也是卡断点，
```
return await _listenCancelForAsyncTask<Response<T>>(
            cancelToken, _onError<T>(err));
```
401的时候回卡在这里
我想知道release未捕获异常是不是就崩了？

**Comment by YQjiuhao** [comment]
@wendux Flutter:1.12.13,dio:3.0.7，这个问题依然存在，用sqlif,shared_preferences都能抛出

**Comment by Creolophus** [comment]
Flutter (Channel stable, v1.12.13+hotfix.8)
我也碰到了，这问题一直在，居然给关了。。

**Comment by xinde** [comment]
flutter 1.17.3 dio 3.0.9 还是会又这个问题

**Comment by asjqkkkk** [comment]
> @huanxsd @fg2q1q3q 我这边一直复现不了，我这边的版本是2.1.16，flutter sdk 是v1.8.1-pre.21, 我用下面代码在断网的情况下测试是能catch到错误的：
> 
> ```dart
> import 'package:dio/dio.dart';
> void getHttp() async {
>   try {
>     Response response = await Dio().get("http://www.google.com");
>     print(response);
>   } catch  (e) {
>     print("--"*20);
>     print(e);
>   }
> }
> 
> main() async{
>   await getHttp();
> }
> ```
> 
> 控制台输出：
> ![image](https://user-images.githubusercontent.com/20411648/64665792-695e3a80-d486-11e9-8c24-136ee66d0be6.png)
> 
> 另外如果future用catchError能捕获错误而用try...catch不行的话，这就是dart sdk的bug，try...catch是语言级别支持的，而dio只是对future的使用。
> 看大家反馈，感觉很可能是flutter 1.7.8中携带的dart sdk的bug，建议大家升级flutter至最新版本再试，如还有问题，可以详细描述一下复现步骤，和版本信息。

使用弱网模式，比如vpn全局代理，就可以复现到问题

**Comment by sou1maker** [comment]
同样的问题，无法捕捉，什么提示都没有
![image](https://user-images.githubusercontent.com/58240137/117534106-9cbde780-b022-11eb-9f61-f8aab9873dd4.png)

**Comment by Quietly-20201113** [comment]
2022啦 10月啦  我还遇到这个问题   flutter 2.10.5 dio 4.0.6
