### ISSUE TITLE
没有网络的时候请求dio,直接报错抛出异常,不会在error中返回DioError类型,页面卡死

### ISSUE THREAD

**Issue by itMcdull** [flutterchina/dio#382]
抛出的异常如下,
DioError (DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'xxxxxxxxURL' (OS Error: No address associated with hostname, errno = 7))

**Comment by YQjiuhao** [comment]
看看是不是[这个](https://github.com/flutterchina/dio/issues/377)的问题

**Comment by huanxsd** [comment]
All Exceptions一直是关闭的。Uncaught Exceptions是未捕获异常，不能关。。因为我外层是已经捕获了，但是app还是会因为未捕获而中断。
你们不能因为库有问题，而让开发者关掉未捕获异常选项。这不是解决问题，而是忽略问题。

**Comment by LeiYao123** [comment]
@itMcdull 可能是你的设备没网了
