### ISSUE TITLE
文档示例中直接post data传map类型服务器接受不到

### ISSUE THREAD

**Issue by DylanXing** [flutterchina/dio#387]
服务器接收的Body是Raw中的application/json类型
在post方法的data参数中直接传字典或者传json字符串都不行
必须将map转成FormData这个类型的传进去才可以.
而本身服务器是不接受form-data的

**Comment by DylanXing** [comment]
忽略,服务器支持form-data,抱歉

**Comment by HeQuanLi** [comment]
@DylanXing 你是咋个解决的啊 我现在也遇到这个问题了

**Comment by DylanXing** [comment]
将map转成FormData这个类型
