### ISSUE TITLE
Post提交数据,设置contentType不支持ContentType.json

### ISSUE THREAD

**Issue by DylanXing** [flutterchina/dio#388]
如题,提交post数据,设置BaseOptions中的contentType时
设置为`ContentType.json`无效会丢失数据,设置成`ContentType.parse("application/json")`才可正常post.

**Comment by FingerArt** [comment]
`post` 时传递的`RequestOptions`有没设置 `contentType`呢？，`RequestOptions` 的优先级高于 `BaseOptions` 默认是 `ContentType.json`

**Comment by DylanXing** [comment]
并没有设置RequestOptions,在添加拦截器时的onRequest回调方法收到有RequestOptions的参数,不过也没做任何处理
问题代码如下

BaseOptions options = new BaseOptions(
      //请求基地址,可以包含子路径
      baseUrl: baseUrl,
      //连接服务器超时时间，单位是毫秒.
      connectTimeout: 50000,
      //响应流上前后两次接受到数据的间隔，单位为毫秒。
      receiveTimeout: 15000,
      contentType: ContentType.parse("application/json"),

      // 如果按以下设置ContentType.json会丢失body中的数据.
      // contentType:ContentType.json,

      //Http请求头.
      headers: header,
    );

**Comment by DylanXing** [comment]
还有一个下载的问题,下载中杀掉app,重启后重新开启下载,会超时..
谢谢

**Comment by wendux** [comment]
1. 升级到最新的版本重试
2. 如果还有问题，抓包看一下请求体重是否有数据
3. 如果还不行，请给一个在线可访问的，可复现的url 或代码块
 
如果还有问题，再重新打开此issue


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
1. 升级到最新的版本重试
2. 如果还有问题，抓包看一下请求体重是否有数据
3. 如果还不行，请给一个在线可访问的，可复现的url 或代码块
 
如果还有问题，再重新打开此issue


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
