### ISSUE TITLE
dio Post Error

### ISSUE THREAD

**Issue by sunguotao** [flutterchina/dio#391]
method: POST
I/flutter (28968): contentType: application/json; charset=utf-8
I/flutter (28968): responseType: ResponseType.json
I/flutter (28968): followRedirects: true
I/flutter (28968): connectTimeout: 10000
I/flutter (28968): receiveTimeout: 3000
I/flutter (28968): extra: {}
I/flutter (28968): header: 
I/flutter (28968):   Accept-Charset:utf-8
I/flutter (28968):   Connection:keep-alive
I/flutter (28968):   Accept:*/*
I/flutter (28968):   Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey
I/flutter (28968):   IMEI:865987049034061
I/flutter (28968): data:
I/flutter (28968): {}
I/flutter (28968): 
I/flutter (28968): *** DioError ***:
I/flutter (28968): DioError [DioErrorType.DEFAULT]: type 'int' is not a subtype of type 'String' of 'value'#0      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart)
I/flutter (28968): #1      Dio._transformData (package:dio/src/dio.dart:879:24)
I/flutter (28968): <asynchronous suspension>
I/flutter (28968): #2      Dio._makeRequest (package:dio/src/dio.dart:738:26)
I/flutter (28968): <asynchronous suspension>
I/flutter (28968): #3      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:711:22)
I/flutter (28968): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (28968): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (28968): #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter (28968): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter (28968): #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter (28968): #9      Future._complete (dart:async/future_impl.dart:473:7)
I/flutter (28968): #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
I/flutter (28968): #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patc

**Comment by lucien-theron** [comment]
Same error.

Tracked down to this line, as per strack trace, its not happy with that int:
https://github.com/flutterchina/dio/blob/cad527f645edb52b3927c6cfdce7e3aa30f96090/package_src/lib/src/dio.dart#L879
![image](https://user-images.githubusercontent.com/7767248/62999897-189bf780-be70-11e9-83cf-504ff1f6c2f7.png)

**Comment by lucien-theron** [comment]
I believe length.toString(); is the answer here

**Comment by lucien-theron** [comment]
I believe this can be closed now
