### ISSUE TITLE
网络请求同意所有证书

### ISSUE THREAD

**Issue by XiaoCheng123** [flutterchina/dio#392]
你好，我产品的功能需要dio的Https证书校验那里，可以通过所有https的协议通过和android一样，例如[Android okhttp3.0配置https的自签证书和信任所有证书](https://juejin.im/post/5c831d4d6fb9a049dd81190a)，请问可以做到吗

**Comment by changgongxinshi** [comment]
@XiaoCheng123 ，你好，请问https证书校验这里有解决的办法了吗？我跟你有同样的问题

**Comment by changgongxinshi** [comment]
@XiaoCheng123 
应该是可以的
![image](https://user-images.githubusercontent.com/16306138/62272851-a9390780-b46e-11e9-9399-cc6394f6231a.png)
参考该处
https://book.flutterchina.club/chapter10/dio.html
