### ISSUE TITLE
DioError response data Map

### ISSUE THREAD

**Issue by rtmrodrigues** [flutterchina/dio#397]
Issue Info

| Platform Name              | flutter
| Dio Version                    | 2.1.13
| Editor                             | VSCode

After a post, the server can sometimes respond with the following JSON:

{
    "Message": "An error has occurred.",
    "ExceptionMessage": "The customer is blocked"
}

However, when i catch the DioError, the body of the response.data (a MAP), is only showing one element (Message).

How can I get the ExceptionMessage also?

**Comment by wendux** [comment]
https://github.com/flutterchina/dio#handling-errors

**Comment by rtmrodrigues** [comment]
Hello.

Thank you for your response, however, I´m already catching the error but it only gets 1 item of the error response and I need to get the others.

CODE sample:

`

      on DioError catch (dio_e) {
       if (dio_e.response != null) {
        if (dio_e.response.data != null) {
          if (dio_e.response.statusCode == 500) {
            if (dio_e.response.data != null) {
              if (dio_e.response?.data["Message"] != null) {
                error = dio_e.response?.data["Message"]?.toString();
                if (dio_e.response?.data["ExceptionMessage"] != null) {
                  error =
                      "$error Details: ${dio_e.response?.data["ExceptionMessage"]?.toString()}";
                }
              }
            }
          } else {
            error = dio_e.response.toString();
          }
        }
      }
`

Please check the images attached to see that POSTMAN catches more info than DioError.

DIO resulta on Debug watch:
![Debug-watch](https://user-images.githubusercontent.com/30235882/62277705-9d355180-b43e-11e9-82f3-083d3d0c8f7f.png)
POSTMAN results:
![POSTMAN](https://user-images.githubusercontent.com/30235882/62277706-9dcde800-b43e-11e9-8190-be0bf2eb276a.png)

**Comment by rtmrodrigues** [comment]
No solution? :(

**Comment by rtmrodrigues** [comment]
Hello.
I´m sory to insist on this issue, however, I can not find a way to get the information I need because I have not enough experience to see where DIO catches only one MAP and not a list of MAP.
Can you please provide me some help?

Thank you.
