### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: SocketException

### ISSUE THREAD

**Issue by moonljt521** [flutterchina/dio#398]
Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup:

dio请求已经try catch了，在无网络的时候只打印了上边的log，没有走我的catch，请问如何捕获无网络产生的异常或有什么返回值响应码，我之前搜索了有相同的issue，但没有解决就直接关闭了，所以我又提问了一次 

flutter 环境
[✓] Flutter (Channel v1.5.4-hotfixes, v1.5.4-hotfix.2-pre.1, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

使用的是dio: ^2.1.13

**Comment by moonljt521** [comment]
fixed， 算是我使用问题吧， 因为dio.post返回值是个Future， 它当然也有个catchError方法，源码内部是用.catchError((err) => throw _assureDioError(err)); 来抛出异常的，所以 直接用try{  } on DioError catch (e){ } 的方式不能捕获请求异常。所以需要用 dio.post().then(){ }.catchError(){ 捕获请求异常 } 的方式来捕获

**Comment by huanxsd** [comment]
牛逼的库，一个5k多star的网络库。居然不支持try catch。还是老老实实用官方的库安全

**Comment by wukuy** [comment]
感觉这库问题很多呀。。。没法玩。

**Comment by wendux** [comment]
我这边一直复现不了，我这边的版本是2.1.16，我用下面代码在断网的情况下测试是能catch到错误的：
```dart

import 'package:dio/dio.dart';
void getHttp() async {
  try {
    Response response = await Dio().get("http://www.google.com");
    print(response);
  } catch  (e) {
    print("--"*20);
    print(e);
  }
}

main() async{
  await getHttp();
}
```
控制台输出：
![image](https://user-images.githubusercontent.com/20411648/64665792-695e3a80-d486-11e9-8c24-136ee66d0be6.png)

另外如果future用catchError能捕获错误而用try...catch不行的话，这就是dart sdk的bug！
建议大家升级flutter至最新版本再试，如还有问题，可以详细描述一下复现步骤，和版本信息
