### ISSUE TITLE
How to handled error in onError ?

### ISSUE THREAD

**Issue by lyquocnam** [flutterchina/dio#40]
Dear author, i handled error in `onError`, so i don't want use `try catch` it again in my code. How to do that ?
i tried `return null;` in `onError` but not work.

```dart
 dynamic _onError(DioError e) {
    // handled..
   // ....
    return null; // <---
  }
```

currently i must do this to ignore exception, because it was handled as above:
```
try {
var response = await dio.post(....);
} catch (e) {}
```

**Comment by wendux** [comment]
A request must correspond to a response, even if it failed.  
you can  handle successful response by only  suppling callback to `then` instead of using `async...await `  to  ignore exception:
```dart
dio.get(...).then((r)=>print(r))
```

**Comment by jlcool** [comment]
@wendux 请求需要做单独的异常处理还必须得用await，不能用then。使用then，有异常catch不到，能不能不抛出异常而是返回一个异常状态，直接用then获取处理，比如这样
`.then((response,error){
if(error!=null){
}
})
`

**Comment by jlcool** [comment]
> @wendux 请求需要做单独的异常处理还必须得用await，不能用then。使用then，有异常catch不到，能不能不抛出异常而是返回一个异常状态，直接用then获取处理，比如这样
> `.then((response,error){ if(error!=null){ } })`

onError 返回Response 就可以
