### ISSUE TITLE
弱弱的问一个小白问题，flutter下载的依赖包怎么查看最新版本

### ISSUE THREAD

**Issue by quert999** [flutterchina/dio#405]
既然是flutterchina，中文应该没问题吧。。。
新接触flutter，下载的packages位于flutter\.pub-cache\hosted\pub.flutter-io.cn
但是我怎么查看最新版本是多少啊，比如我android studio里面依赖的如果不是最新的会黄色警告提示最新版本。这个flutter的依赖怎么查看最新的。
还有一点，我依赖了shared_preferences: ^0.4.2这个包。
在flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences-0.4.3\ios&android这个目录可以看到原生代码实现。但是为什么例如dio等等的其他包都不包含原生代码实现呢，里面只有一个lib文件夹，文件夹里面全是dart文件。
求各位大佬们指点。

**Comment by RainFool** [comment]
在https://pub.dev/上搜索即可
当然可以搞一些IDE插件去自动搜索，不过库升级需要考虑的问题很多，有插件报出来，直接就升级其实是一种不负责任的行为
正常流程是：
1. 插件提示有最新版本
2. 在https://pub.dev/上搜索对应库，查看更新说明
3. 评估是否需要更新
4. 手动改动版本号，获取最新版，处理兼容问题
