### ISSUE TITLE
Dio delete error :"Http status error [400]"

### ISSUE THREAD

**Issue by zgramming** [flutterchina/dio#406]
Hello i get some problem with delete data , I'm using this code
`
void _makeApiCall(String id) async{
    Dio dio = Dio();
    Response apiResponse =await dio.delete("${Urls.BASE_API_URL}mahasiswa/delete?id=$id");
    print(apiResponse.data.toString());
  }
`
But i get "Http status error [400]" , I check my rest api code, it's mean my ID Null / not passing in url rest API.
But if i try in POSTMAN it's working perfectly .
It's my API Url :
http://192.168.43.159/wpu-rest-server/apii/mahasiswa/delete/
please correct me if i wrong.

**Comment by Kalela** [comment]
@zgramming Did you find a solution for this?
