### ISSUE TITLE
How to queue all requests?

### ISSUE THREAD

**Issue by Sp4Rx** [flutterchina/dio#408]
I need to queue all the requests for some specific use case. How to achieve this in dio? I tried with locks. Then I felt its purpose is different,

**Comment by prasant10050** [comment]
i have same issue,can someone have solution?

**Comment by wendux** [comment]
Dio doesn't support this feature default, you should do this by hand.

**Comment by amreniouinnovent** [comment]
@wendux we don't know how we could achieve that

**Comment by Sp4Rx** [comment]
Are you suggesting this?
I will implement a `queue` where I will push my requests and a function like `processRequests` . I will call the `processRequests` if its not processing anything during each insertion of requests in the `queue` also after each requests finished processing will call the `processRequests` method.

This logic can be refined more.

**Comment by amreniouinnovent** [comment]
@Sp4Rx do you able to find a solution or not yet?

**Comment by Sp4Rx** [comment]
We changed the use case , so haven't implemented it. But the logic I mentioned can work.
