### ISSUE TITLE
Invalid character in cookie value 

### ISSUE THREAD

**Issue by Nerixyz** [flutterchina/dio#412]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found #8 , but using Dart 2.4.1 this also happens.

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Dart Version | Dart VM version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "windows_x64"
| Platform Name                  | windows_x64                          |      |
| Platform Version               | Windows 10 1903                              |      |
| Dio Version                    |  2.1.13                                  |      |
| IntelliJ Version | IntelliJ IDEA 2019.2 (Ultimate Edition) Build #IU-192.5728.98, built on July 23, 2019  |      |
| Repro rate                     | 100% / when signed  |      |
| Repro with our demo prj        | - |      |
| Demo project link              | - |      |

### Issue Description and Steps

Console:
```
DioError [DioErrorType.DEFAULT]: FormatException: Invalid character in cookie value, code unit: '92' (at character 3)
"{\"200...
  ^
#0      Dio._makeRequest (package:dio/src/dio.dart:799:16)
<asynchronous suspension>
#1      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:711:22)
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._complete (dart:async/future_impl.dart:473:7)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#10     Dio._executeInterceptors (package:dio/src/dio.dart) 
<asynchronous suspension>
#11     Dio._request.<anonymous closure> (package:dio/src/dio.dart:703:20)
#12     Dio._checkIfNeedEnqueue (package:dio/src/dio.dart:990:22)
#13     Dio._request (package:dio/src/dio.dart:702:9)
<asynchronous suspension>
#14     Dio.request (package:dio/src/dio.dart:614:12)
<asynchronous suspension>
#15     Dio.post (package:dio/src/dio.dart:129:12)

```
I'm requesting POST `https://i.instagram.com/api/v1/accounts/login/`, but the request has to be signed.
However, you can see the cookie-value in the console.

**Comment by Nerixyz** [comment]
Apparently this line causes the Exception: https://github.com/dart-lang/sdk/blob/cd46a39bb73ed53d1b17ec53c39ce70fc88ea865/sdk/lib/_http/http_headers.dart#L1023

**Comment by msarkrish** [comment]
@Nerixyz How did you solved the issue?

**Comment by Nerixyz** [comment]
> @Nerixyz How did you solved the issue?

I copied the code and removed the validation: [insta_cookie.dart](https://github.com/Nerixyz/instagram_private_api/blob/master/lib/src/utilities/insta_cookie.dart).
