### ISSUE TITLE
Handling Error Exception 404 

### ISSUE THREAD

**Issue by zgramming** [flutterchina/dio#413]
I got some problem with handling error exception 404 in Dio, I'm already handling this exception with this code, but nothing work's 
can you help me with this error ? 
Thank's
```
Future<List<Mosque>> getMahasiswaById(String id) async{
       try {
         var apiRespon = await dio.get('$baseURL/mahasiswa/get/id/$id');
        if(apiRespon.statusCode == 200){
            final apiResponJson = apiRespon.data;
            return (apiResponJson['data'] as List).map((p)=>Mosque.fromJson(p)).toList();
        }else{
          print(apiRespon.statusCode.toString());
            throw Exception('Failed Load Data with status code ${apiRespon.statusCode}');
        }
       }on DioError catch (e) {
         print(e);
         return null;
       }
  }
```

**Comment by trevorwang** [comment]
#385

**Comment by koalaylj** [comment]
you should handle the HTTP error in this way.
```
Future<List<Mosque>> getMahasiswaById(String id) async{
       try {
         var apiRespon = await dio.get('$baseURL/mahasiswa/get/id/$id');
         final apiResponJson = apiRespon.data;
         return (apiResponJson['data'] as List).map((p)=>Mosque.fromJson(p)).toList();
       }on DioError catch (e) {
          //http error(statusCode not 20x) will be catched here.
          print(apiRespon.statusCode.toString());
          throw Exception('Failed Load Data with status code ${apiRespon.statusCode}');
       }
  }
```

**Comment by elmissouri16** [comment]
@wendux  whats about error 400 , 404 500 ???

**Comment by pmrajani** [comment]
Why dio throw error in release mode for iOS?
ios debug and android release/debug build works fine.

using :   dio: ^3.0.10

ERROR: DioError [DioErrorType.RESPONSE]: Http status error [400] \nSTACK: #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:966)\n<asynchronous suspension>\n#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart)\n<asynchronous suspension>

**Comment by sebastiandenis** [comment]
> Why dio throw error in release mode for iOS?
> ios debug and android release/debug build works fine.

I have the same issue. @pmrajani Have you found a fix for that?
