### ISSUE TITLE
data Map not working 

### ISSUE THREAD

**Issue by Mostafa-SA-developer** [flutterchina/dio#415]
- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |flutter                        
| Dio Version                    |2.1.13                                  |      |
| Android Studio 

this my code when i use FormData its working but the map not working 
when i posting to server its show me successful but the data not sending 
and on my php server show me undefin index for evry param 

var map=Map.from(
              {"image":"img",
               "name": fileName,
               "title": title.text,
               "sub": subject.text,
               "admin": admin,
             });
  
     Response res =await dio.post(url,data:
     map,onSendProgress: (int send,int total){
      setState(() {
        //val=((send/total)*10)/10;
        download=((send/total)*10).toStringAsFixed(0)+"%";
      });
      
     });

**Comment by wendux** [comment]
You should use `FormData` instead `Map`.
