### ISSUE TITLE
发起get请求，一直报错：DioError [DioErrorType.RESPONSE]: Http status error [403]

### ISSUE THREAD

**Issue by JD-CP** [flutterchina/dio#417]
Dio version：2.1.13。
1. 请求相关代码：
class HomePageState extends State<HomePage> {
  void httpGet() async {
    var dio = Dio();
    dio.interceptors.add(LogInterceptor());
    var response =
        await dio.get('http://baobab.kaiyanapp.com/api/v2/feed?num=1',
            options: Options(headers: {
              "accept": "*/*",
            }));
    print(response.toString());
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      child: GestureDetector(
        child: Text('点我发起网络请求'),
        onTap: httpGet,
      ),
    );
  }
}

2. 请求日志
*** Request ***
I/flutter (15518): uri: http://baobab.kaiyanapp.com/api/v2/feed?num=1
I/flutter (15518): method: GET
I/flutter (15518): contentType: application/json; charset=utf-8
I/flutter (15518): responseType: ResponseType.json
I/flutter (15518): followRedirects: true
I/flutter (15518): connectTimeout: 0
I/flutter (15518): receiveTimeout: 0
I/flutter (15518): extra: {}
I/flutter (15518): header:
I/flutter (15518):   accept:*/*
I/flutter (15518):
I/flutter (15518): *** DioError ***:
I/flutter (15518): DioError [DioErrorType.RESPONSE]: Http status error [403]
I/flutter (15518): uri: http://baobab.kaiyanapp.com/api/v2/feed?num=1
I/flutter (15518): statusCode: 403
I/flutter (15518): headers:
I/flutter (15518):  connection: keep-alive
I/flutter (15518):  content-type: text/html
I/flutter (15518):  transfer-encoding: chunked
I/flutter (15518):  date: Thu, 15 Aug 2019 01:03:23 GMT
I/flutter (15518):  content-encoding: gzip
I/flutter (15518):  server: Tengine/2.1.2
I/flutter (15518):
I/flutter (15518):
E/flutter (15518): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [403]

**Comment by jp1017** [comment]
Options要用BaseOptions

**Comment by koalaylj** [comment]
可以这么处理
```
try{
  dio.request()//dio.get/put/post/delete...
}catch(e){
//http级的错误会抛exception，需要在这里catch住处理。
//这个403 可能是服务器不允许跨域吧？
}
```
