### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: InternalError: 'Filter error, bad data'

### ISSUE THREAD

**Issue by sldboy** [flutterchina/dio#419]
### New Issue Checklist
DioError [DioErrorType.DEFAULT]: InternalError: 'Filter error, bad data'
- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                   flutter                           |      |
| Platform Version               | 1.7.0                              |      |
| Dio Version                    |2.1.7                                |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2 / Xcode 10.2.1              |      |
| Repro rate                     | all the time (100%)  |      |
| Repro with our demo prj        |       |      |
| Demo project link              |  |      |

### Issue Description and Steps
Get request throws error
Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by sldboy** [comment]
dio.dart: line number:771  throw exception:
ret.data = await _listenCancelForAsyncTask(cancelToken, transformer.transformResponse(options, responseBody));

**Comment by wukuy** [comment]
同样的问题.
![image](https://user-images.githubusercontent.com/26781738/63504799-e12eea00-c504-11e9-822c-dfdc650300d4.png)

**Comment by wendux** [comment]
please  update to  3.0 and try again, if the problem still exists,  reopen  the issue and provide detailed steps to reproduce  this  problem.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
