### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [302]

### ISSUE THREAD

**Issue by longdw** [flutterchina/dio#420]
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | android                          |      |
| Platform Version               | 9.0                              |      |
| Dio Version                    | 2.1.0                                  |      |
| Android Studio / Xcode Version | Android Studio 3.4.2              |      |
| Repro rate                     | all the time (100%)    |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps
when use dio in pure flutter project, it can request data. but when i embed flutter project to native project, the dio can't request data, and always throws `DioError [DioErrorType.RESPONSE]: Http status error [302]`

**Comment by longdw** [comment]
sorry,i made a mistake.

**Comment by alfawzaan** [comment]
Add followRedirects: false and validateStatus: (status) { return status < 500;} to the request

var response = await Dio().post("http://myurl",
data: requestBody,
options: Options(
followRedirects: false,
validateStatus: (status) { return status < 500; }
),
);

Source [https://stackoverflow.com/questions/52537500/flutter-handle-status-code-302-in-post-request](url)
