### ISSUE TITLE
拦截器中onResponse返回的类型可以自定义吗？

### ISSUE THREAD

**Issue by zhangyu1818** [flutterchina/dio#421]
``` dart
// dio
onResponse: (Response response) {
    return BaseRequest.fromJson(response.data);
}
// request
final BaseRequest res = await dio.post("/api/pmLogin");
```
我想在onResponse里取出数据统一转换一下，但是这样写好像不行

**Comment by koalaylj** [comment]
你可以自定义`HttpClientAdapter `，在这里统一转。
你可以参考下这两个  [adapter](https://github.com/flutterchina/dio/blob/master/example/adapter.dart),[mock_adapter](https://github.com/flutterchina/dio/blob/master/package_src/test/mock_adapter.dart)

ps: 这样应该是可以的，我是测试时候mock dio时候发现的这个方法。
