### ISSUE TITLE
无网络或是服务端异常爆500错误，没有捕获到异常,导致断点和App卡顿该如何解决

### ISSUE THREAD

**Issue by speanut-land** [flutterchina/dio#423]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                     |      |
| Platform Version               | flutter: 1.8.5-pre.130                          |      |
| Dio Version                    | e.g.  2.1.13                                 |      |
| Android Studio / Xcode Version |Xcode 10.2.1              |      |

![错误图片](https://s2.ax1x.com/2019/08/16/mm4eYT.png)
请问当服务器异常与断网时候 ，HTTP曝500错误导致断点，官网的捕获异常方法并没有用处，App直接停止卡住，这个时候该如何处理，我试过其他issus的方法并没有所帮助，请开发者大大或者有其他的大佬能够告知有何解决方法吗？ 呜呜呜

**Comment by koalaylj** [comment]
```
try{
  dio.request()
}catch(e){
//在这处理就好了
}
```

**Comment by speanut-land** [comment]
> ```
> try{
>   dio.request()
> }catch(e){
> //在这处理就好了
> }
> ```

**Comment by speanut-land** [comment]
还是会导致vscode出现断点！！我询问一下是出现这些错误的时候，就会导致断点，但是在真机环境中不会出现卡死的情况是吗？

**Comment by koalaylj** [comment]
你把 vscode里面调试窗口 breakpoints下 的  all exception 取消勾选就好了。
这个选项勾上vscode会停在当前发生exception的地方，不管这个exception你有没有catch。
编辑器设置的问题。

**Comment by huanxsd** [comment]
你这个关掉，其他异常都看不了了
