### ISSUE TITLE
 [IOS] interceptor onError is not triggered only when losing connectivity

### ISSUE THREAD

**Issue by amrosama2020** [flutterchina/dio#426]
### New Issue Checklist

- [Yes] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  ios                         |      |
| Platform Version               | All                              |      |
| Dio Version                    | 2.1.13                           |      |
| Android Studio / Xcode Version | Xcode 10.2.1              |      |
| Repro rate                     | all the time (100%)    |      |
| Repro with our demo prj        | Can't reproduce because response is too fast           |      |
| Demo project link              | Can prepare it|      |

### Issue Description and Steps

Issue is that the interceptor onError doesn't trigger in IOS in the following scenario:

1. initiate a slow request
2. disable/lose connectivity (e.g. close mobile network)

Interceptor onRequest, onResponse, and onError normally work with regular scenarios on all platforms, but in IOS onError is not triggered only when losing connectivity after sending the request.

Interceptor is setup like this:
```dart
var client = Dio();
    client.interceptors
        .add(InterceptorsWrapper(onError: (DioError e) {
      // Do something with response error
      // if (e.error is HttpException || e.error is SocketException)
      //   e.message = "Connection Failed, Please check your internet connection";
      return e; //continue
    }));
```

I tried placing breakpoints in all catch statements in dio library but none fire on losing connection.

**Comment by koalaylj** [comment]
I have encountered a similar problem to you.
The interceptor can not intercept `DioErrorType.CANCEL` either.
For now, I solve the problem like this:
```
try {
      Response res = await _dio.request(
        path,
        data: data,
        cancelToken: _cancelToken,
        queryParameters: queryParameters,
        options: Options(method: method, extra: {'reqId': _reqId}),
      );
      return res.data;
    } catch (e) {
	
      //if e.type == DioErrorType.CONNECT_TIMEOUT
      //you can handle the error at here
      
      return {};
    }
```

**Comment by bishopmorton** [comment]
in **adapter.dart.** 
it makes sense to work around all `awaits`, not only _httpClient.openUrl... 

await request.addStream(requestStream)**.timeout(Duration(milliseconds:options.connectTimeout));**
      }

HttpClientResponse responseStream = await request.close()**.timeout(Duration(milliseconds:options.connectTimeout));**

^^^ it helps on iOS to finally start getting connect timeouts

**Comment by amrosama2020** [comment]
I ended up adding a timeout but still users with disconnected network will have to wait for the timeout to finish before getting an error.

**Comment by quantela-ashutosh** [comment]
Still facing this issue.
