### ISSUE TITLE
接口返回的中文字符【怎么处理:DioError [DioErrorType.DEFAULT]: FormatException: Control character in string

### ISSUE THREAD

**Issue by huangxiaoyu** [flutterchina/dio#427]
I/flutter (16255): DioError [DioErrorType.DEFAULT]: FormatException: Control character in string (at character 140)
I/flutter (16255): ...596dc901a784287ea","DEPTNAME":"茶城","DESP":"水位表006液位低于预警值【0.1m】(水位表006)
I/flutter (16255):                                                                               ^
E/flutter (16255): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'data' was called on null.
E/flutter (16255): Receiver: null
E/flutter (16255): Tried calling: data
E/flutter (16255): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)

**Comment by huangxiaoyu** [comment]
水位表006液位低于预警值【0.1m】(水位表006)    接口返回的数据中包含:【   解析不了

**Comment by wendux** [comment]
请升级Dart/Flutter/Dio到最新版重试，如果最新版还有问题请给一个可复现的url，然后重新打开此issue
