### ISSUE TITLE
dio delete 服务器返回204报错

### ISSUE THREAD

**Issue by keluokeda** [flutterchina/dio#43]
error = DioError [DioErrorType.DEFAULT]: FormatException: Unexpected end of input (at character 1)
rest delete成功，服务器返回内容为空，dio报错。

**Comment by wendux** [comment]
你的dio是最新版吗？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by keluokeda** [comment]
@wendux 升级到0.1.7还会有同样的问题。

**Comment by wendux** [comment]
已修复，请用0.1.8重试

**Comment by keluokeda** [comment]
测试ok,十分感谢。
