### ISSUE TITLE
Why I upload a large file is to re-initialize the dio instance so that my loadingdialog will not be catton

### ISSUE THREAD

**Issue by zhcAndroid** [flutterchina/dio#433]
static Future<T> putFiles<T>(String uri,Map<String, dynamic> params, List<String> filePaths) async{
    List<UploadFileInfo> uploadList = new List();
    for(var i=0;i<filePaths.length;i++){
      String filePath = filePaths[i];
      var name =filePath.substring(filePath.lastIndexOf("/") + 1, filePath.length);
      var suffix = name.substring(name.lastIndexOf(".") + 1, name.length);
      uploadList.add(new UploadFileInfo(new File(filePath), name,
          //contentType: ContentType.parse("image/$suffix")
      ));
    }

    if(params == null){
      params = new Map();
    }
    params["file"] = uploadList;
    FormData formData = new FormData.from(params);
   // var enToken = token == null ? "" : Uri.encodeFull(token);
 
    Options ops = new Options(contentType: ContentType.parse("application/x-www-form-urlencoded"));
    ops.method = "post";
    ops.headers["Authorization"] = "Bearer "+SpUtil.getString('Authorization');

    _dio =  new Dio(new BaseOptions(
      method: "get",
      baseUrl: baseUrl,
      connectTimeout: 5000,
      receiveTimeout: 5000,
      followRedirects: true,
    ));
    return _dio
        .post<Map<String, dynamic>>(uri, data: formData,options: ops)
        .then(logicalErrorTransform);
  }

**Comment by wendux** [comment]
请按模板补充信息后再打开
