### ISSUE TITLE
transformer: question

### ISSUE THREAD

**Issue by jamesdixon** [flutterchina/dio#435]
### New Issue Checklist

- [X ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

This is a question about transformers. The documentation says that they're only called on PUT, POST, and PATCH requests. Is this actually meant to say that `Transformer.transformRequest` is only called on those methods?

If that applies to `transformResponse` as well, why would that be the case?

For example, my API uses the JSON-API spec, so on every request, I want to deserialize that into standard JSON. I need to do this for GET requests as well.

Thanks for any clarification!

**Comment by wendux** [comment]
`transformResponse ` works  for all request,  just `transformRequest` is limited.
