### ISSUE TITLE
post请求的body为map或json时服务端接收不到body

### ISSUE THREAD

**Issue by xiubojin** [flutterchina/dio#436]
Map body = new Map();
body['userId'] = 'xxxxxx';
body['token'] = 'xxxxx';

Dio dio = new Dio();
dio.options.headers = headers;
Response response = await dio.post(
        'https://xxxxxxxxxx/xxxx/xxxx',
        data: jsonEncode(body));

**Comment by vampirealone** [comment]
请问解决了吗，我也遇到这个问题

**Comment by xiubojin** [comment]
> 请问解决了吗，我也遇到这个问题

没有

**Comment by DylanXing** [comment]
Duplicate of #388
怀疑跟我这边情况一样,将ContentType换一下看下能不能解决问题
```
contentType: ContentType.parse("application/json"),
// 如果按以下设置ContentType.json会丢失body中的数据.
// contentType:ContentType.json,
```

**Comment by xiubojin** [comment]
> Duplicate of #388
> 怀疑跟我这边情况一样,将ContentType换一下看下能不能解决问题
> 
> ```
> contentType: ContentType.parse("application/json"),
> // 如果按以下设置ContentType.json会丢失body中的数据.
> // contentType:ContentType.json,
> ```

还是不行

**Comment by DylanXing** [comment]
contentType设置成`ContentType.parse("application/json")`还不行的话,你跟我的区别应该就只有baseUrl的不同了,我是设置了baseUrl的..

**Comment by wendux** [comment]
不需要手动jsonEncode, body是map的话直接传就行

**Comment by xiubojin** [comment]
> 不需要手动jsonEncode, body是map的话直接传就行

也试过直接传body，也不行。。

**Comment by wendux** [comment]
@xiubojin 请给一个最小的可复现可运行的demo


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by xiubojin** [comment]
> @xiubojin 请给一个最小的可复现可运行的demo
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

内部项目，我copy一些脱敏的代码吧。。

var data = {
      "ownerId": user.userId,
      "token": user.token,
      "userName": user.username,
      "subtime": "2019-09-01"
    };

Dio dio = new Dio();
    BaseOptions options = new BaseOptions(
      baseUrl: "xxxxxxx",
      connectTimeout: 50000,
      headers: headers,
    );
    dio.options = options;
    dio.post('xxxxxxxxxx', data: data).then((value) {
      print('value:' + value.toString());
      setState(() {
      });
    }).catchError((e) {
      print('e   >> $e');
    });

Server可以接收到请求，但是看不到post请求的body。

**Comment by z234009184** [comment]
我也有同样的问题。

**Comment by z234009184** [comment]
麻烦作者看下 body 一直为空。或者给个紧急解决方案～

**Comment by wendux** [comment]
你可以将请求地址改为http://httpbin.org/post ，这是一个http测试地址，会回显你的请求数据，我用最新的dio版本（2.2.0）请求是没有问题的：
```dart
main() async {
  var data = {
    "ownerId": "ccccc",
    "token":"cvvvvvvvv",
    "userName": "dffffffff",
    "subtime": "2019-09-01"
  };

  Dio dio = new Dio();
  BaseOptions options = new BaseOptions(
    baseUrl: "xxxxxxx",
    connectTimeout: 50000,
  );
  dio.options = options;
  await dio.post('http://httpbin.org/post', data: data).then((value) {
    print('value:' + value.toString());
  }).catchError((e) {
    print('e >> $e');
  });
}
```
![image](https://user-images.githubusercontent.com/20411648/65045945-481fb180-d992-11e9-924b-dab72b148d6f.png)

**Comment by xiubojin** [comment]
> 你可以将请求地址改为http://httpbin.org/post ，这是一个http测试地址，会回显你的请求数据，我用最新的dio版本（2.2.0）请求是没有问题的：
> 
> ```dart
> main() async {
>   var data = {
>     "ownerId": "ccccc",
>     "token":"cvvvvvvvv",
>     "userName": "dffffffff",
>     "subtime": "2019-09-01"
>   };
> 
>   Dio dio = new Dio();
>   BaseOptions options = new BaseOptions(
>     baseUrl: "xxxxxxx",
>     connectTimeout: 50000,
>   );
>   dio.options = options;
>   await dio.post('http://httpbin.org/post', data: data).then((value) {
>     print('value:' + value.toString());
>   }).catchError((e) {
>     print('e >> $e');
>   });
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/20411648/65045945-481fb180-d992-11e9-924b-dab72b148d6f.png)

感觉很奇怪，用你的这个链接测试是没问题的，用我的这个api测试就是收不到body，哭笑 - -!

**Comment by z234009184** [comment]
@xiubojin 作者已经给我回复了，你看看是不是你的Content-Type 设置的有问题，作者默认的是json 你改成其他的试试

**Comment by z234009184** [comment]
The request Content-Type. The default value is "application/json; charset=utf-8".
  If you want to encode request body with "application/x-www-form-urlencoded",
  you can set [Headers.formUrlEncodedContentType], and [Dio]
  will automatically encode the request body.

你设置成“application/x-www-form-urlencoded” 试一下，可以用 [Headers.formUrlEncodedContentType] 代替

**Comment by xiubojin** [comment]
> Headers.formUrlEncodedContentType

Headers.formUrlEncodedContentType 请问这是个什么？我直接用，Headers报错。

**Comment by wendux** [comment]
@xiubojin 
1. 检查一下你的接口读取数据的方式是否有问题
2. 请求是抓包看一下请求包中是否有data 
3. 如果以上两步已经做了，还是没能发现问题，请给一个可以在线访问的，可复现的urine 

以上三点确认后，还有问题的话再重新打开此issue


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by xpader** [comment]
我这边测试在 iOS 上，dio 2.1.12 会提交远超过文件大小的数据，导致 nginx 直接返回 413 了，实际上文件只有 2.3M，nginx 设置的可接收数据最大大小是 50M，在安卓上则没有这个问题。

**Comment by vampirealone** [comment]
> > Headers.formUrlEncodedContentType
> 
> 没有找到Headers.formUrlEncodedContentType。
> 用contentType: ContentType.parse("application/x-www-form-urlencoded"),试了一下，还是不行。

由于我们服务器的接口配置，json是不行的，所以我只能用contentType: ContentType.parse("application/x-www-form-urlencoded")，是可以的
BaseOptions options = BaseOptions(
      baseUrl: api.URL_BASE,
      connectTimeout: 5000,
      receiveTimeout: 3000,
      contentType: ContentType.parse("application/x-www-form-urlencoded"), 
      );

**Comment by xiubojin** [comment]
已解决。

**Comment by hygtjm** [comment]
@xiubojin 怎么解决的求代码

**Comment by Huuuuuub** [comment]
> 
您好，我也发现了这个问题，您这边解决了吗？

**Comment by Huuuuuub** [comment]
> 我这边测试在 iOS 上，dio 2.1.12 会提交远超过文件大小的数据，导致 nginx 直接返回 413 了，实际上文件只有 2.3M，nginx 设置的可接收数据最大大小是 50M，在安卓上则没有这个问题。

您好，我也发现了这个问题，请问您这边解决了吗
