### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: type 'Future<HttpClient>' is not a subtype of type 'HttpClient'#0      DefaultHttpClientAdapter._configHttpClient

### ISSUE THREAD

**Issue by Aronlong1001** [flutterchina/dio#437]
Dio _createDio() {
    Dio _dio = new Dio(_options);
    //开启请求日志
    if(APPConfig.env != 0) {
      _dio.interceptors.add(LogInterceptor(requestBody: false));
    }

    (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (client) async {
        String cer = await rootBundle.loadString("assets/res/xx.pem");
        SecurityContext sc = new SecurityContext(withTrustedRoots: true);
        sc.useCertificateChainBytes(utf8.encode(cer));
        return HttpClient(context: sc);
    };
    return _dio;
  }

**Comment by wendux** [comment]
去掉`async`关键字
