### ISSUE TITLE
Invalid response status code

### ISSUE THREAD

**Issue by 450347873** [flutterchina/dio#438]
```
try {
    Response response = await Dio().get("https://go-api.qbaor.com/v1/user/loginRegister");
} on DioError catch (e) {
    if (e.response != null) {
      print(e.response.data);
      print(e.response.headers);
      print(e.response.request);
    } else {
      print(response.statusCode);
      print(e.response.statusCode);
    }
}

```

browser response HTTP statusCode 902 and Object  (Postman too)
`
{
  "err_code": "inputDataError",
  "err_msg": "\u8f93\u5165\u7684\u6570\u636e\u6709\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165\u3002",
  "redirect_to": "",
  "data": null
}
`

but TERMINAL output **[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'statusCode' was called on null.**

TERMINAL show response ==>> **null**
so i can't get any **statusCode**
how can i get "statusCode"

**Comment by 450347873** [comment]
Now i know why.
It's because of the code of "http_parser.dart" in the Flutter SDK.
`case _State.RESPONSE_LINE_ENDING:
          _expect(byte, _CharCode.LF);
          _messageType == _MessageType.RESPONSE;
          if (_statusCode < 100 || _statusCode > 599) {
            throw new HttpException("Invalid response status code");
          } else {
            // Check whether this response will never have a body.
            if (_statusCode <= 199 ||
                _statusCode == 204 ||
                _statusCode == 304) {
              _noMessageBody = true;
            }
          }
          _state = _State.HEADER_START;
          break;`

But I want to use the HTTP statusCode 600 or more than 600, such as 901.
How can i do

**Comment by 450347873** [comment]
Now i know why.
It's because of the code of "http_parser.dart" in the Flutter SDK.

` 
          if (_statusCode < 100 || _statusCode > 599) {
            throw new HttpException("Invalid response status code");
          } 
`

But I want to use the HTTP statusCode 600 or more than 600, such as 901.
How can i do

**Comment by wendux** [comment]
No way yet!

**Comment by lyf571321556** [comment]
> ```
> try {
>     Response response = await Dio().get("https://go-api.qbaor.com/v1/user/loginRegister");
> } on DioError catch (e) {
>     if (e.response != null) {
>       print(e.response.data);
>       print(e.response.headers);
>       print(e.response.request);
>     } else {
>       print(response.statusCode);
>       print(e.response.statusCode);
>     }
> }
> ```
> 
> browser response HTTP statusCode 902 and Object (Postman too)
> `{ "err_code": "inputDataError", "err_msg": "\u8f93\u5165\u7684\u6570\u636e\u6709\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165\u3002", "redirect_to": "", "data": null }`
> 
> but TERMINAL output **[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'statusCode' was called on null.**
> 
> TERMINAL show response ==>> **null**
> so i can't get any **statusCode**
> how can i get "statusCode"



> Now i know why.
> It's because of the code of "http_parser.dart" in the Flutter SDK.
> 
> ` if (_statusCode < 100 || _statusCode > 599) { throw new HttpException("Invalid response status code"); } `
> 
> But I want to use the HTTP statusCode 600 or more than 600, such as 901.
> How can i do

i have same issue,how do you solve it?

**Comment by ctcx** [comment]
在使用腾讯阿里等某些第三方接口时，会返回大于600的状态码；会导致程序抛出异常，建议不要限制statusCode的范围～
