### ISSUE TITLE
多文件上传失败

### ISSUE THREAD

**Issue by 331299** [flutterchina/dio#439]
上传文件时，如果是嵌套的参数，会导致多文件上传失败，得到的是"[Instance of 'UploadFileInfo', Instance of 'UploadFileInfo']"。
```
{
   "quantity": {
         "images[]": [UploadFileInfo]
    }
}
```
如上情况下，上传多个文件失败
```
{
   "quantity": {
         "image": UploadFileInfo
    }
}
```
如上情况，上传单个文件成功
```
{
   "quantity": { }，
   "images[]": [UploadFileInfo]
}
```
如上情况，上传正常

**Comment by wendux** [comment]
2.1.x多文件上传不支持嵌套，2.2.0中开始支持，可以升级到2.2.0试试（PS, 由于2.2.0开始支持Flutter web，更新较大，部分API做了调整，升级可以参考[从2.1升级到2.2指南](https://github.com/flutterchina/dio/blob/master/migration_to_2.2.x.md) ）

**Comment by jiandandkl** [comment]
原来是放在` FormData.fromMap`,但是服务端只能从body里拿到string
~~List _upimgData = List();~~
~~_imageCat.forEach((img) {~~
~~_upimgData.add(MultipartFile.fromFileSync(img.path));~~
~~});~~

改为这样,就能正确拿到files了
```
FormData formData = FormData.fromMap({
    "name": _name,
     "age": _age,
     "imgId": MultipartFile.fromFileSync(_imageId.path),
     "imgAvatar": MultipartFile.fromFileSync(_imageAvatar.path),
     "imgCats": _imageCat.map((img) => MultipartFile.fromFileSync(img.path)).toList(),
    // "imgCats": _upimgData
 });
```
