### ISSUE TITLE
Access the HTTP address error FormatException: Bad utf-8 encoding 0x89

### ISSUE THREAD

**Issue by pyp163** [flutterchina/dio#44]
dio: ^0.1.7

Access the HTTP address error FormatException: Bad utf-8 encoding 0x89, the correct return content of HTTP is binary
```dart
try {
       Response responses = await DioUtils.DioHttp().post(url, data: formData);
       print('返回:${responses.data.toString()}');
     }on DioError catch(e){
       print('错误:'+e.message);
     }
```
 错误:FormatException: Bad UTF-8 encoding 0x89 (at offset 0)

**Comment by pyp163** [comment]
@wendux 
FormData formData = new FormData.from({
      "token": token,
      "nonce": nonce8,
      "timestamp": time.toString(),
      "sign": sign,
    });
{token: v6b3aSqLJp6YpWmnWvuCip7W, nonce: BMnMKZXE, timestamp: 1533005903, sign: ea9efa98cf29e992db8b1ce9138ee6a26313e43ee67f9ef6bd900408efc95864}

url = Constants.api + "/GetVerify" 
接口返回的是二进制图片，其实的接口都正常就这个不行，这个接口在java代码上是正常的

**Comment by wendux** [comment]
二进制数据要指定responseType为stream , 这样response.data便会是steam, dio默认是以字符串方式来解码的


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
