### ISSUE TITLE
VSCode一直存在的一个被忽略问题(There has always been an overlooked problem)

### ISSUE THREAD

**Issue by YQjiuhao** [flutterchina/dio#440]
VSCode: 1.38.0
Flutter: 1.7.8
Dio: 2.1.16[#377 ](https://github.com/flutterchina/dio/issues/377)
希望能得到解决，谢谢

**Comment by YQjiuhao** [comment]
这个问题一直没人遇到吗？多顶顶。。。

**Comment by wendux** [comment]
@YQjiuhao 请升级到最新的3.0.x版本重试，如还有问题，再重新打开比issue


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by YQjiuhao** [comment]
> @YQjiuhao 请升级到最新的3.0.x版本重试，如还有问题，再重新打开比issue
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

依然没有解决，Flutter 1.9.1+hotfix.2 Dio:3.0.1
