### ISSUE TITLE
请求有些用户会出现HandshakeException

### ISSUE THREAD

**Issue by qq3144225600** [flutterchina/dio#442]
HandshakeException: Handshake erro in client(os Error:CERTIFICATE_VERIFY_FAILED:unable to get local issuer certificate()handshake.cc:352

**Comment by GesanTung** [comment]
me too,DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error: 
I/flutter (22119): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))

**Comment by wendux** [comment]
这是Https证书校验失败，考虑网络环境可能不安全（存在代理或被劫持），如果是测试环境想抓包，可以先禁用证书校验，详情可以参考文档。
