### ISSUE TITLE
Dio for FlutterWeb

### ISSUE THREAD

**Issue by rafaldziuryk** [flutterchina/dio#443]
Is there any plan to support Flutter for web? For now, Flutter give a option for create Web app. As far as I know, Flutter for Web use dart:html instead of dart:io

**Comment by godot0413301** [comment]
希望dio支持flutter web

**Comment by wendux** [comment]
We will support flutter web in a week.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by godot0413301** [comment]
good job!太棒了

**Comment by wendux** [comment]
Refer to https://github.com/flutterchina/dio/issues/443
