### ISSUE TITLE
HttpException: Connection closed before full header was received

### ISSUE THREAD

**Issue by charliezzo** [flutterchina/dio#445]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |  
| ------------------------------ | ----------------------------------------------------- |
| Platform Name                 |android                          |
| Platform Version                |9.0                              |
| Dio Version                   | 2.4.0                                 |
| Android Studio / Xcode Version |Android Studio 3.5.0              |
| Repro rate                     |  all the time (100%)   |
| Repro with our demo prj        | no           |
| Demo project link              | no  |

### Issue Description and Steps

onPressed: () async => {await getSetting()，await setSetting()}

two dio function run always catch the error:

HttpException: Connection closed before full header was received

**Comment by wendux** [comment]
Please update to 3.0.x and try again.

**Comment by skinadm** [comment]
In flutter dio after his query, I get the same error. 

Request

Response response = await dio.post(
    'https://www.xxx.yy/server/history',
    data: {
      'tid': '0',
    },
    options: Options(
      headers: {
        'X-Requested-With': 'XMLHttpRequest',
        'Content-Type': 'application/x-www-form-urlencoded',
      },
    ),
  );

Response

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received, uri = https://www.xxx.yy/server/history

Here is screenshots of request and response. 

![Screenshot_1568985034](https://user-images.githubusercontent.com/42117589/65329592-70412780-dbc1-11e9-8f7e-57de1c74ac20.png)
![Screenshot_1568985043](https://user-images.githubusercontent.com/42117589/65329593-70412780-dbc1-11e9-9cd8-5294dc04636f.png)

When I send same request from Postman comes full response. 
How to solve?

**Comment by wendux** [comment]
@skinadm dio 3.0 ?


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by skinadm** [comment]
Using dio 2.2.1 version due to the fact that Inspector tool for Flutter Alice does not support the version of dio 3

**Comment by charantft** [comment]
> ### New Issue Checklist
> * [x]  I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none
> 
> ### Issue Info
> Info	Value
> Platform Name	android
> Platform Version	9.0
> Dio Version	2.4.0
> Android Studio / Xcode Version	Android Studio 3.5.0
> Repro rate	all the time (100%)
> Repro with our demo prj	no
> Demo project link	no
> ### Issue Description and Steps
> onPressed: () async => {await getSetting()，await setSetting()}
> 
> two dio function run always catch the error:
> 
> HttpException: Connection closed before full header was received

Hey, have you found a solution to this issue? Im also facing the same issue. It would be great if you can help

**Comment by ovaldi** [comment]
+1

**Comment by YuriOliveiraAbel** [comment]
+1

**Comment by 18710849877** [comment]
In my project ,the reason is I used the VPN , just close it.

**Comment by motefaker** [comment]
i have same issue any solution?
