### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: NoSuchMethodError: The method 'startsWith' was called on null

### ISSUE THREAD

**Issue by Alexwsc** [flutterchina/dio#449]
版本号：2.1.16，dio的post请求，使用ApiPost测试URL地址以及参数都没问题，可以返回数据，但是运行flutter，报错DioError [DioErrorType.DEFAULT]: NoSuchMethodError: The method 'startsWith' was called on null，请问是哪里出错了。

**Comment by Alexwsc** [comment]
原先我将获取数据的包含URL地址和参数的方法聚合到其他文件，不能获取到数据，现在我将获取方法直接耦合当前dart，却又能获取到数据，这是为啥？PS：使用VSCode工具

**Comment by Alexwsc** [comment]
是我自己的错，我提取参数，没提取对

**Comment by Lee-42** [comment]
我也遇到这个问题了，请问你是怎么解决的？

**Comment by myNameIsHamza** [comment]
Hi, how did u solve this

**Comment by virenvvarasadiya** [comment]
I am facing same issue.

**Comment by virenvvarasadiya** [comment]
I was facing issue because my url was null.
