### ISSUE TITLE
求 SOCKS5 代理

### ISSUE THREAD

**Issue by wuujiann** [flutterchina/dio#450]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps

dio 的文档提到如何设置 Http 代理。但是 PROXY 代理好像只支持 HTTP。不知是否能加 SOCKS5 的代理，如下：

  "PROXY [protocol://][user:password@]proxyhost[:port]>"

  “PROXY http://proxy:8888"
  "PROXY https://user:password@secureproxy:5443"
  "PROXY socks5://sockshost:1080"

**Comment by wendux** [comment]
dio对代理的支持依赖于HttpClientAdapter的实现，而默认的Adapter是通过dart:io库中的`HttpClient`，所以是否支持，依赖于`HttpClient`，这个建议具体查看一下HttpClient相关文档。

**Comment by wuujiann** [comment]
谢谢您的回复。我会去了解如何依赖 HttpClientAdatper 来实现 SOCKS5 代理。如果能支持，我也会将答案公布在这里 :-)

**Comment by NetFly-VPN** [comment]
> 谢谢您的回复。我会去了解如何依赖 HttpClientAdatper 来实现 SOCKS5 代理。如果能支持，我也会将答案公布在这里 :-)
HttpClientAdatper 支持socks5嘛

**Comment by tayoji-io** [comment]
@wuujiann https://pub.dev/packages/flutter_socks_proxy
