### ISSUE TITLE
cookie_jar在flutter1.9下用不了.

### ISSUE THREAD

**Issue by Playfullycat** [flutterchina/dio#451]
flutter pub get了好几次都不行

**Comment by boyan01** [comment]
很奇怪的问题。在 Android Studio 提示找不到 dio 相关的类， 但 vs code 上没问题，而且都能正常通过编译。

![image](https://user-images.githubusercontent.com/17426470/65142749-fcc6db00-da45-11e9-979d-fd2587050163.png)

**Comment by wendux** [comment]
升级一下flutter版本和as版本试试

**Comment by boyan01** [comment]
今天有空看了一下 @wendux 

我的问题可能依赖引入导致的。

之前项目的引入方式是这样的的
```yaml
  dio: ^2.1.xx
```

然后由于 dio  2.2.x 版本不兼容 2.1.x 的版本， 于是就产生问题了。

**Comment by wendux** [comment]
@boyan01 ok, 建议升级到最新的3.0.x版本。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
