### ISSUE TITLE
请求的编码为multipart/form-data，日志输出的仍然是json格式

### ISSUE THREAD

**Issue by li-xiaojun** [flutterchina/dio#454]
必现

**Comment by wendux** [comment]
手动指定content-type为multipart/form-data是没有用的，要使用multipart/form-data编码，请使用`Formdata`对象。

**Comment by li-xiaojun** [comment]
使用的就是FormData对象，输出的request的content-type还是json

**Comment by wendux** [comment]
这个可以忽略，因为默认的content-type是json，而正发送时dio如果检测到发送的对象是FormData会自动将content-type设置为multipart/form-data。http://httpbin.org/post是一个http测试网站，它可以回显你的请求信息，你可以向它提交数据查看最终提交的数据。
