### ISSUE TITLE
The await expression can only be used in an async function

### ISSUE THREAD

**Issue by zjypp** [flutterchina/dio#457]
Response response;
                    Dio dio = new Dio();
                    response = await dio.get("http://www.baidu.com");
                    print(response.data.toString());

dio是2.1.16，flutter是1.9
就这样的案例代码报错，没看到问题在哪里
error: The await expression can only be used in an async function. (await_in_wrong_context at [flutter2] lib/pages/login/login.dart:70)

**Comment by zjypp** [comment]
解决了

**Comment by JUN-95** [comment]
> 解决了
怎么解决的
