### ISSUE TITLE
弱弱的问下response是json格式的,response.data不是标准的json式了,

### ISSUE THREAD

**Issue by YanHe2018** [flutterchina/dio#460]
双引号没有了,是什么原因?
Flutter v1.9.1+hotfix.2
Dio 2.1.16

**Comment by YanHe2018** [comment]
更新版本解决

**Comment by hao751333636** [comment]
所以你是如何解决这个问题的

**Comment by YanHe2018** [comment]
> 所以你是如何解决这个问题的

更新到最新版本即可

**Comment by hao751333636** [comment]
嗯 我的问题也是双引号没有了，不过在后面的issues中找到了答案，dio拿到的data已经是处理之后的了。
