### ISSUE TITLE
Access to XMLHttpRequest has been blocked by CORS policy Error

### ISSUE THREAD

**Issue by vico-aguado** [flutterchina/dio#461]
Hi!!

I add dio to Flutter Web and It show this error in console:

Access to XMLHttpRequest at '<URL>' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Uncaught (in promise) Error: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.
    dart:sdk_internal 41685:30                           get current
package:dio/src/adapters/browser_adapter.dart 75:20  <fn>
dart:sdk_internal 99367:96                           <fn>
    at Object.createErrorWithStack (dart_sdk.js:4602)
    at Object._rethrow (dart_sdk.js:28602)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:28598)
    at Object._microtaskLoop (dart_sdk.js:25256)
    at _startMicrotaskLoop (dart_sdk.js:25262)
    at dart_sdk.js:25337

But if I try get this <URL> data with 'package:http/http.dart', It's work correctly.

My <URL> have all access control.

Help me!!

**Comment by ymback** [comment]
Nothing wrong with dio, you should add 'Access-Control-Allow-Origin' header with value 'http://127.0.0.1:8080' or '*' in your server side.
I run a server using php/laravel, all works after add below headers.
```php
         $response->header('Access-Control-Allow-Origin', $origin);
        $response->header('Access-Control-Allow-Headers', 'Origin, Content-Type, Cookie, X-CSRF-TOKEN, Accept, Authorization, X-XSRF-TOKEN, Access-Control-Allow-Origin');
        $response->header('Access-Control-Expose-Headers', 'Authorization, authenticated');
        $response->header('Access-Control-Allow-Methods', 'GET, POST, PATCH, PUT, OPTIONS');
        $response->header('Access-Control-Allow-Credentials', 'true');
```

**Comment by vico-aguado** [comment]
Why with 'package:http/http.dart' works correctly ? 

With the same URL...

This request (http.get) works correctly:
<img width="876" alt="Screen Shot 2019-09-18 at 22 50 51" src="https://user-images.githubusercontent.com/22483705/65212273-1af10300-da67-11e9-9f40-f8d5835d6ce1.png">

And this request (dio.get) works wrong:
<img width="994" alt="Screen Shot 2019-09-18 at 22 51 04" src="https://user-images.githubusercontent.com/22483705/65212291-2c3a0f80-da67-11e9-9ec2-b3c72fb82620.png">

**Comment by wendux** [comment]
@vico-aguado Could you give an online access url by which http package works but dio can't ?

**Comment by vico-aguado** [comment]
Sure! https://www.thelotent.com/WSVistaWebClient/OData.svc/GetNowShowingSessions?$format=json&$filter=CinemaId+eq+'100'

**Comment by wendux** [comment]
@vico-aguado  In my box, all things are right with dio.
My request codes as follows:
```dart
 dio.get<String>("https://www.thelotent.com/WSVistaWebClient/OData.svc/GetNowShowingSessions?\$format=json&\$filter=CinemaId+eq+%27100%27").then((r) {
   print(r.data);
 }).catchError(print);
```
![image](https://user-images.githubusercontent.com/20411648/65322609-e3569800-dbd9-11e9-9c18-33ed2f9e2e2e.png)

**Comment by vico-aguado** [comment]
Yeah! Thank you very much! The problem was the Flutter version. This works with the new 1.10.5 (master) versión. The problem was with 1.9.1 versión.
