### ISSUE TITLE
connectTimeout

### ISSUE THREAD

**Issue by 330676687** [flutterchina/dio#462]
2.2.1删除了Option里的connectTimeout，通过在BaseOption里设置的connectTimeout无效，拦截器打印接口connectTimeout显示为0

**Comment by 330676687** [comment]
而且通过options设置的connectTimeout，实测是可以覆盖BaseOptions里的connectTimeout，为什么要删除呢 如果需要多个接口不同超时时间怎么办 我是把dio弄的单例

**Comment by wendux** [comment]
1. 在通过`dio.options.connectTimeout`是有效的，拦截器中是可以打印出的。
2. 删除options的connectTimeout的原因见[2.2.x升级指南](https://github.com/flutterchina/dio/blob/master/migration_to_2.2.x.md)

**Comment by carmas123** [comment]
Sorry but after some test the connectTimeout property into baseOption does not work like the 2.x version.
