### ISSUE TITLE
When cancel called. Requests isn't canceled.

### ISSUE THREAD

**Issue by jasin755** [flutterchina/dio#463]
I have problem with canceling requests.

```
        final cancelToken = CancelToken();

        final request = host.request(path,
            data: data,
            queryParameters: query,
            options: Options(method: describeEnum(method)),
            cancelToken: cancelToken);

        final cancelableRequest = CancelableOperation.fromFuture(request, onCancel: () {
          cancelToken.cancel();
        });
```

When `cancelToken.cancel();` is called I receive `DioErrorType.CANCEL` but request is not canceled (checked in Charles web proxy). I have tried throttling request but it always waits for response.

![image](https://user-images.githubusercontent.com/10629189/65143535-84482600-da15-11e9-8215-b8d2b60c80c1.png)

All this requests should be canceled.

**Comment by wendux** [comment]
When request  is cancelled, dio will call `httpClient.close(force:true)` and close the connection, but  I'm not sure whether the proxy app can also close the connection in this situation.

**Comment by alfianandinugraha** [comment]
> When request is cancelled, dio will call `httpClient.close(force:true)` and close the connection

Make sense. I think cancel and abort are different things. The cancel means close the connection but the request still going, and abort is close the connection and stop the request. I don't know if Dio has abort method. The abort is available on HttpClient https://api.flutter.dev/flutter/dart-io/HttpClientRequest/abort.html #cmiiw

**Comment by fullflash** [comment]
it seem there is already a fix for it
https://github.com/flutterchina/dio/pull/1440
