### ISSUE TITLE
Flutter Web 跨域问题

### ISSUE THREAD

**Issue by yococoxc** [flutterchina/dio#465]
Console 输出的错误信息：

Access to XMLHttpRequest at 'https://www.baidu.com/' from origin 'http://localhost:51714' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
browser_adapter.dart:94 GET https://www.baidu.com/ net::ERR_FAILED

如题，我在Flutter Web 遇到了跨域问题，不知道在 dio 上面应该如何解决。

Flutter 1.10.4-pre.71
dio: ^3.0.0

void test() async {
  var dio = Dio();
  dio.httpClientAdapter = BrowserHttpClientAdapter();

  Response<String> response;
  response = await dio.get("https://www.baidu.com");
  print(response.statusCode);
}

还有，dio 在 Flutter Web 上面收如何设置 http 代理的，我看过文档的好像不适用。

**Comment by wendux** [comment]
Web下受浏览器同源策略影响是不能跨域的. 建议服务端支持CORS相关的请求头，可以参考这个 https://github.com/flutterchina/dio/issues/461#issuecomment-532913008

**Comment by yococoxc** [comment]
@wendux  Flutter Web 怎么实现代理

**Comment by wendux** [comment]
flutter web下网络库是不能实现代理的，因为最终会转为js，浏览器xmlhttprequest是不支持的，具体的方法可以百度“前端如何测试跨域请求”。

**Comment by TomLiu-GitHub** [comment]
如果我编译后放静态资源，直接/api/xxx来访问接口，那么编译的时候如何区分是web还是安卓还是ios，没有看到isweb的选项。

**Comment by philos3** [comment]
> 如果我编译后放静态资源，直接/api/xxx来访问接口，那么编译的时候如何区分是web还是安卓还是ios，没有看到isweb的选项。

用了一个比较偷巧的方法，web必备的库[dart.library.html]( https://api.dartlang.org/stable/2.5.2/dart-html/dart-html-library.html)，如果存在就是web


![image](https://user-images.githubusercontent.com/8424317/67547232-11774c80-f731-11e9-926d-69ae4596f6f9.png)


vm.dart
```
const isBrowser = false;
```

js.dart
```
const isBrowser = true;
```

在需要的地方调用
```
import 'is_browser/vm.dart' if (dart.library.html) 'is_browser/js.dart';

if (isBrowser) {

    }
```

**Comment by yk3372** [comment]
针对Flutter Web跨域问题，我有一个方案：https://juejin.im/post/5e5d1674e51d4526c1481991
使用了这个库来做的：shelf_proxy，中间件的方式
