### ISSUE TITLE
更新过3.0.0之后，无法get的问题

### ISSUE THREAD

**Issue by jahnli** [flutterchina/dio#466]
![image](https://user-images.githubusercontent.com/20943608/65210550-2fb4b180-dace-11e9-9b15-0cee950e4da6.png)
在2.1.16  是OK的， 但是更新过后报错， 只是单纯的get

**Comment by wendux** [comment]
信息太少，复现不了，请给一个可复现的代码片段。

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/65211286-c4201380-dad0-11e9-8b03-38ecd9c608ed.png)
![image](https://user-images.githubusercontent.com/20943608/65211316-ddc15b00-dad0-11e9-8d94-fbca57450e0d.png)

**Comment by wendux** [comment]
。。。。这个怎么复现，给一个可以复现的裸请求就行，比如：
```
Response response = await Dio().get("http://www.google.com");
```
另外，这个是flutter web还是？

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/65211619-f54d1380-dad1-11e9-89c3-6d061afb6497.png)
 不是web

**Comment by jahnli** [comment]
我在尝试 是不是接口问题， 请稍等

**Comment by wendux** [comment]
你好好调试一下，服务器能返回400就证明请求发出了，你也可以将请求发送至 http://httpbin.org/ ，这是一个http测试网站，会回显你的请求，这样可以验证请求是否有问题。 先关闭了，如果确认是dio问题再打开吧。

**Comment by jahnli** [comment]
这个问题原因已经找到了。
 之前2.1.16 版本， 不需要指定   contentType: 'json' 
但是现在写类型就会有报错。
![image](https://user-images.githubusercontent.com/20943608/65226954-60aadb80-dafa-11e9-832e-88f58e874b04.png)
![image](https://user-images.githubusercontent.com/20943608/65226984-6ef8f780-dafa-11e9-9404-4085c42447c2.png)
