### ISSUE TITLE
dio3.0 get请求失败原因

### ISSUE THREAD

**Issue by jahnli** [flutterchina/dio#467]
这个问题原因已经找到了。
之前2.1.16 版本， 不需要指定 contentType: 'json'
但是现在不写类型就会有报错。

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/65227936-204c5d00-dafc-11e9-9c58-d3c9f4eccb9d.png)
![image](https://user-images.githubusercontent.com/20943608/65227966-30fcd300-dafc-11e9-9b8f-ad96f92e934c.png)

**Comment by wendux** [comment]
1. 3.0中如果默认contentType是“application/json”，不需要手动设置，如果按你代码中所示是`contentType: 'json'` 反而是会报错的。不会是你说的这个原因。
2. 我这边完全复现不了你的场景，也没有别人来反馈。我现在就差一个豆瓣的Token，但是没找到申请的地方。
3. 可以加我qq（824783146），联调一下 ，这样可以找到真正的原因。

**Comment by jahnli** [comment]
我已添加好友，  你有时间通过下。
