### ISSUE TITLE
升级3.0后,多个Dio实例应该怎么封装

### ISSUE THREAD

**Issue by phoenixsky** [flutterchina/dio#469]
如果应用内要连多个服务器,会采用不同的dio实例,来进行不同的调用
比如2.x版本:
1. 通过继承将公共的**transformer**,**interceptors**等,放在父类构造函数中
    ![image](https://user-images.githubusercontent.com/6359214/65294703-93ec7980-db91-11e9-95e7-aa66ded49cb0.png)
2.分别继承父类来定义私有的 **interceptors** or **cookie**
    ![image](https://user-images.githubusercontent.com/6359214/65294886-31e04400-db92-11e9-8392-c8c8bb119bba.png)
    ![image](https://user-images.githubusercontent.com/6359214/65294911-47ee0480-db92-11e9-8c5f-c498b5f0099e.png)
3. 在不同的类,引入不同的dio实例,进行调用
    ![image](https://user-images.githubusercontent.com/6359214/65294954-6c49e100-db92-11e9-8cbd-61dcbf099cb0.png)

升级3.x版本后,Dio加入了自己的factory构造,无法再通过继承的方式实现公共的部分的预定义.请问有没有推荐的办法呢

**Comment by wendux** [comment]
先升级到3.0.1， 然后参照 https://github.com/flutterchina/dio#extends-dio-class

**Comment by phoenixsky** [comment]
感谢反馈.我记得3.0.0刚出那天文档里有几句话是说, baseUrl不再放到Interceptor中的文字,后来怎么找不到了
