### ISSUE TITLE
3.0.1版本json解析会出现问题

### ISSUE THREAD

**Issue by zhanghaigang666** [flutterchina/dio#473]
网上查询的方法都是使用json.decode(response.data.toString()) 这个方法解析json字符串成Map再转成相应的数据模型，但是3.0.1版本dio测试发现使用json.decode(response.data.toString()) 解析一段服务器返回的{"result":1,"data":"send sms success 800478"} 这个json格式数据会报错FormatException: Unexpected character (at character 2)

分析原因后发现response.data.toString()生成的字符串是“{result: 1, data: send sms success 336959}”，内部的""双引号都没了导致json解析报错

**Comment by timrijckaert** [comment]
English please!

**Comment by jicg** [comment]
/api/      ====>      {"code":0,"errmsg":"ok"}
# 
# 2.1.13
```
Response<Map> resp = await dio.post("/api/")
```
no error

# 3.0.1
```
Response<Map> resp = await dio.post("/api/")
```
has error ：type 'Response<dynamic>' is not a subtype of type 'Response<Map<dynamic, dynamic>>'

**Comment by wendux** [comment]
@zhanghaigang666  dio已经帮你把json转为Map了,不需要再手动decode了。如果你要获取字符串(不想让dio自动转Map)，可以指定泛型参数，如：
```dart
Response response = await dio.get<String>(...)
// response.data is String
```

**Comment by wendux** [comment]
@jicg I can't reproduce your case, Maybe you can try again as follow:
```dart
Response<Map> resp = await dio.post<Map>("/api/")
```
If the problem still exists, giving a complete url please.

**Comment by jicg** [comment]
url ：https://tj.hellowcloud.com/text.json
![question](https://user-images.githubusercontent.com/6479672/65505328-87528300-defb-11e9-9395-5140dd6d60d2.jpg)

**Comment by wendux** [comment]
@jicg 
![image](https://user-images.githubusercontent.com/20411648/65578200-e968c200-dfa7-11e9-844b-51faf7da9400.png)

Dio transform the response data to JSON object only when the content-type of response is "application/json" .

**Comment by jicg** [comment]
@wendux 非常谢谢。是这个原因。
