### ISSUE TITLE
HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10)

### ISSUE THREAD

**Issue by xellDart** [flutterchina/dio#475]
On every request I get:
HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10)

Code
```
Dio dio = new Dio()
  ..options.baseUrl = 'https://192.168.0.11:3020/'
  ..options.connectTimeout = 10000
  ..options.receiveTimeout = 10000
  ..httpClientAdapter = Http2Adapter(
    ConnectionManager(
    idleTimeout: 10000,
    /// Ignore bad certificate
    onClientCreate: (_, clientSetting) => clientSetting.onBadCertificate = (_) => true,
  ),
  );
```

On server side I use express with node-spy

**Comment by wendux** [comment]
There is a built-in http2 package in node. My test codes as follow:
```javascript
var fs = require('fs');
const http2 = require('http2');

var options = {
    key: fs.readFileSync('./example.com.key'),
    cert: fs.readFileSync('./example.com.crt')
};

const server = http2.createSecureServer(options, (req, res) => {
    res.setHeader('Content-Type', 'text/html');
    res.setHeader('X-Foo', 'bar');
    res.writeHead(200, {'Content-Type': 'text/plain'});
     let str = "";
     res.stream.on("data", data => {
         str += data;
         console.log(str);
     });
    res.end(req.stream.body + req.url);
});
server.listen(443);
```

**Comment by Sp4Rx** [comment]
After adding `Http2Adapter` this error starts coming.

     Dio()
     ..httpClientAdapter = Http2Adapter(ConnectionManager());

All requests are failing.

And my server is properly configured for `http2`

**Comment by robin12210325** [comment]
me too

**Comment by 350054665** [comment]
me too

**Comment by wonpyohong** [comment]
same here

**Comment by mouryaavadhesh** [comment]
same here version 4 giving this error

**Comment by M144-Coder** [comment]
I have the same problem on all requests and I am using dio version 4.0.6 and http2_adapter 2.0.0.
If I remove the http2 adapter the connection works fine.
I hope this issue is resolved soon so we can upgrade to Http/2.

**Comment by tyy** [comment]
It seems to be an issue with using uppercase in the headers. See: https://github.com/dart-lang/http2/issues/49
