### ISSUE TITLE
Uploading files to PUT endpoint with dio 3.x

### ISSUE THREAD

**Issue by nruotsal** [flutterchina/dio#478]
Is there some way to upload files to PUT endpoint with dio version 3?
FormData documentation say that it is supported only for POST, but is there some other way to upload files to PUT endpoint than using FormData?

**Comment by nruotsal** [comment]
Ok, Great! I may have some other problem then in my code. There is this mention

> Note: Just the post method suppots FormData.

in the end of the [Sending FormData chapter](https://github.com/flutterchina/dio#sending-formdata)

**Comment by wendux** [comment]
Ok, I will update the documentation.
