### ISSUE TITLE
Upload image with Uint8List in FormData sent string instead of binary

### ISSUE THREAD

**Issue by AlexVincent525** [flutterchina/dio#485]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and **found one related issue #371 but not worked.**

### Issue Info

| Info                           | Value                                                 |
| ------------------------------ | ----------------------------------------------------- |
| Platform Name                  | flutter                          |
| Platform Version               | Not specific                              |
| Dio Version                    | 3.0.0                                  |
| Android Studio / Xcode Version | Android Studio 3.5            |
| Repro rate                     | all the time (100%)   |
| Repro with our demo prj        | demo does not including related content       |
| Demo project link              | can't provided |

### Issue Description and Steps

First congratulate with the brand new version of Dio released.
首先恭喜Dio的新版本发布~

In my case, `Uint8List` image data will be converted to `str` instead of `binary` according to PyCharm's log.
在我的业务中，根据PyCharm的日志，`Uint8List`形式的图片数据被转化成了字符串而不是二进制数据。

As I proceed with the same method, adding a transformer, etc. It just post a string, still.
在我使用了与相关方法后，添加了数据转换等，问题依旧。

Some of my code provided below:
下面提供部分上传实现代码：
```
static Future updateUserAvatar(Uint8List avatar) async {
    FormData formData = FormData.fromMap({
        "avatar": MultipartFile.fromBytes(avatar),
    });
    return NetUtils.post(
        API.saveUserInfo,
        data: formData,
    );
}

static Future post(String url, {data, headers}) async {
    Dio _dio = Dio();
    return await _dio.post(
        url,
        data: data,
        options: Options(
            headers: headers ?? buildAuthHeader(),
        )
    );
}
```
Please help me with this when you have spare time, thx a lot.
若您有时间，请帮助我解决这个问题，非常感谢！

**Comment by wendux** [comment]
FormData所有的内容最终都是以2进制上传的，你说“完整log中显示我传出的是string”，这个是根据什么判断的？如果是根据content-type，那么你可以指定一下MultipartFile的contentType

**Comment by AlexVincent525** [comment]
后端的PyCharm显示我传出的内容是str，正常接收应该为binary。稍后我附上截图。

**Comment by wendux** [comment]
1. 不用重新定义Transformer,把你的transformer删了，很可能你的transformer就写
2. 把你的requestEncoder也删了，干扰，formdata本身就是以二进制流上传的。
3. Formdata上传的示例example目录中有，请仔细查看。Formdata是经过严格测试的，上传二进制文件是没有问题的，
另外Formdata上传时content-type是multipart/form-data，#371 并不是说以Formdata方式上传，你这个QueryDict看起来貌似是query参数，你要确认一下后端是以哪种方式接受的。另外和后端调试建议使用抓包工具去排查问题。

**Comment by AlexVincent525** [comment]
恰逢国庆，只能节后再继续调试了，国庆快乐！

**Comment by AlexVincent525** [comment]
1、在formdata example中，并没有使用`fromBytes`构造`FormData`的示例，还麻烦进一步补充；
2、在使用`fromBytes`时，根据业务代码转换出来的`Uint8List`发送一直被接收为str (PyCharm)，为`MultipartFile`指定`contentType`为`MediaType("image", "png")`无效；
3、最终将数据存至File后构建上传成功。

仍认为其中存在部分问题。

**Comment by YQjiuhao** [comment]
同样的问题

**Comment by AlexVincent525** [comment]
根据群友做的大量测试，目前已定位问题，解决方法：

**Comment by YQjiuhao** [comment]
> 根据群友做的大量测试，目前已定位问题，`fromBytes`方法指定`filename`可解决。请考虑将文档及example完善。此原因由何导致？

我都是指定filename的，反正不行

**Comment by UttamPanchasara** [comment]
Having same kind of issue in dio, As in our back-end they are accepting only binary data for file, I would like to have option to pass binary in body instead string,

I'm trying to pass byte[] in body but automatically converting into string and the **content-type:application/octet-stream**  which I'm not sure it's doing anything with that, please help or suggest any solution

**Comment by AlexVincent525** [comment]
@wendux Please take a look.

**Comment by AlexVincent525** [comment]
Still, it's an issue.

**Comment by AlexVincent525** [comment]
@wendux

**Comment by idootop** [comment]
> 
> 
> Having same kind of issue in dio, As in our back-end they are accepting only binary data for file, **I would like to have option to pass binary in body instead string,**
> 
> I'm trying to pass byte[] in body but automatically converting into string and the **content-type:application/octet-stream** which I'm not sure it's doing anything with that, please help or suggest any solution.
> 
> **Solution:**
> What I have done is converting bytes into stream and passing in the body
> 
> ```
>   List<int> imageBytes = File(path).readAsBytesSync();
>   var file = MultipartFile.fromBytes(imageBytes).finalize();
> 
>   Dio().post('api/', data: file);
> ```

Thanks! It works :)

**Comment by Purelightme** [comment]
> > Having same kind of issue in dio, As in our back-end they are accepting only binary data for file, **I would like to have option to pass binary in body instead string,**
> > I'm trying to pass byte[] in body but automatically converting into string and the **content-type:application/octet-stream** which I'm not sure it's doing anything with that, please help or suggest any solution.
> > **Solution:**
> > What I have done is converting bytes into stream and passing in the body
> > ```
> >   List<int> imageBytes = File(path).readAsBytesSync();
> >   var file = MultipartFile.fromBytes(imageBytes).finalize();
> > 
> >   Dio().post('api/', data: file);
> > ```
> 
> Thanks! It works :)

这样怎么指定上传的文件的key呢？
dio在文件上传这里确实有问题，试了很多办法都不行

**Comment by AlexVincent525** [comment]
Again.

**Comment by AlexVincent525** [comment]
Eww, another library waiting for abandon...
