### ISSUE TITLE
I/flutter (10204): HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).

### ISSUE THREAD

**Issue by iamriajul** [flutterchina/dio#486]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter / ios / android                          |      |
| Platform Version               | 9.0                              |      |
| Dio Version                    | ^3.0.2                                  |      |
| Android Studio | Android Studio 3.5             |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        | no           |      |

### Issue Description and Steps
After adding: 
`Dio(BaseOptions(
                    responseType: ResponseType.json
                  ))..httpClientAdapter = Http2Adapter(ConnectionManager())`
Error in Console:
I/flutter (10204): HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).

**Comment by rotosix** [comment]
me too. when this question may be fix?

**Comment by elisamuelps** [comment]
I can confirm having this issue as well, I tried doing multiple HTTP requests to a different set of APIs with no avail :(

the stack trace is as follows:

`ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).
E/flutter (14143): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:942:7)
E/flutter (14143): <asynchronous suspension>
E/flutter (14143): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)
E/flutter (14143): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1099:22)
E/flutter (14143): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)
E/flutter (14143): #4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter (14143): #5      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (14143): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (14143): #7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (14143): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (14143): #9      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (14143): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (14143): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (14143): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (14143): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (14143): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (14143): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)`

**Comment by cirediew** [comment]
It seems to be an issue when using uppercase in the headers. See https://github.com/dart-lang/http2/issues/49

**Comment by JCKodel** [comment]
Same here.

**Comment by virskor** [comment]
Same here.

**Comment by elisamuelps** [comment]
it is still an issue that needs to be solved

**Comment by kitmoovup** [comment]
Same here

**Comment by xellDart** [comment]
same here

**Comment by FrantisekGazo** [comment]
it's still an issue

**Comment by pcqpcq** [comment]
fix with lower case on headers. thanks to @cirediew 

> It seems to be an issue when using uppercase in the headers.
 See [dart-lang/http2#49](https://github.com/dart-lang/http2/issues/49)

**Comment by peterpan21** [comment]
I have the same issue. My headers are all lower case

**Comment by TENX-S** [comment]
same here. any updates ?

**Comment by mouryaavadhesh** [comment]
issue is still happning

**Comment by xrr2016** [comment]
Still an issue
