### ISSUE TITLE
Custom Response Code

### ISSUE THREAD

**Issue by usbaru** [flutterchina/dio#487]
### New Issue Checklist

- [ x ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / ios                       |      |
| Platform Version               | v1.9.1+hotfix.2 / iOS - 12.1                    |      |
| Dio Version                    |  ^3.0.2                         |      |
| Android Studio / Xcode Version | XCode - 10.1         |      |
| Repro rate                     | 100%   |      |
| Repro with our demo prj        |  no related content
| Demo project link              | Can't Provide |      |

### Issue Description and Steps

When making a post request using Dio().post() to an api that does not return a standard response code (e.g. 900), the request gets stuck and does not hit a catch block.

Is there any way to handle non-standard response codes?

**Comment by loregr** [comment]
Same issue, any update on this?
