### ISSUE TITLE
[ Web ] Problem with dio package in flutter web

### ISSUE THREAD

**Issue by DisIsGAndhi** [flutterchina/dio#489]
We have started with the Flutter web project. This project is working on mobile application when we run on web, dio is giving the following error. I thought some plugins or dependencies not working with dio package on flutter web.

 ```
Error ::: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.
Stacktrace ::: package:build_web_compilers/src/dev_compiler/dart_sdk.js 3992:11   throw_
package:dio/src/dio.dart 848:13

```

Flutter version :

```
[✓] Flutter (Channel master, v1.10.7-pre.23, on Linux, locale en_IN)
    • Flutter version 1.10.7-pre.23 at /home/ag-purplle/Downloads/flutter
    • Framework revision e0247442d0 (8 days ago), 2019-09-26 02:49:41 -0400
    • Engine revision 3713ecf107
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 c6a14f4459)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ag-purplle/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/ag-purplle/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/ag-purplle/Downloads/android-studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!

```
Dio dependency version

`dio: ^3.0.3
`

**Comment by MrThanksgiving** [comment]
Flutter 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.137, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.1)
[✓] Connected device (2 available)

• No issues found!


Dio 
dio: ^3.0.3


DioError [DioErrorType.RESPONSE]: XMLHttpRequest error

**Comment by w3ggy** [comment]
Any progress?
I am also receiving this error on web, but it perfectly works on mobile.

**Comment by w3ggy** [comment]
I think it is related to the CORS issue. You can check it via developer console in Chrome. Should be the error like this:

> Access to XMLHttpRequest at 'http://www.google.com/' from origin 'http://localhost:49901' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by softmarshmallow** [comment]
definitly dio side problem, i checked more that 20 times, dio does not work as expected. cors being blocked from 2nd requests (no rules detected)

dio keep saying cors is blocked, but when i run it via browser's console or postwoman/postman/insomnia, all browser based api client works just fin with cors allow *.

fill so stupid and angry after finally found out it was dio's problem.

**Comment by daothanhduy305** [comment]
> definitly dio side problem, i checked more that 20 times, dio does not work as expected. cors being blocked from 2nd requests (no rules detected)
> 
> dio keep saying cors is blocked, but when i run it via browser's console or postwoman/postman/insomnia, all browser based api client works just fin with cors allow *.
> 
> fill so stupid and angry after finally found out it was dio's problem.

No, I can confirm that it's CORS configuration on the server-side. I'm running a project using Spring Boot server side and ran into this very same problem. However, all is fine after I configure CORS allowed methods and hosts and headers properly.

**Comment by btphan95** [comment]
Disabling CORS policy on Chrome is a temporary solution. It's just frustrating that you have to manually call it before starting Chrome every. single. time.
https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by daothanhduy305** [comment]
> Disabling CORS policy on Chrome is a temporary solution. It's just frustrating that you have to manually call it before starting Chrome every. single. time.
> 
> https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

If you own the server side setup then go configure the god damn CORS properly. I don’t understand why you needed to complicate thing unnecessarily like that. If you don’t own the backend then bad luck.

**Comment by arualana** [comment]
> No, I can confirm that it's CORS configuration on the server-side thing. I'm running a project using Spring Boot server side and ran into this very same problem (insomnia, mobiles worked fine but not flutter web). However, all has been fine after I configure CORS allowed methods and hosts and headers properly within Spring Boot.

No, it's not, cannot access google.com that does not have problems with other methods

**Comment by NiranjanShah** [comment]
@daothanhduy305 , can you please guide us what needs to be done for CORS on Spring Boot server side

**Comment by daothanhduy305** [comment]
> @daothanhduy305 , can you please guide us what needs to be done for CORS on Spring Boot server side

You could set the Cross origin to each API you exposed by adding the @CrossOrigin(origins = ["*"], methods = [RequestMethod.GET]) - I set it to * for instance, you should take care of which origin to allow by yourself. Or search Google for how to set the CORS config system-wide.

**Comment by softmarshmallow** [comment]
Try with this proxy to see whats the problem (a cors proxy service)
https://cors.bridged.cc/
