### ISSUE TITLE
建议添加一个类似okhttp的HttpLoggingInterceptor的拦截器 方便查看log，调试接口问题

### ISSUE THREAD

**Issue by 403462630** [flutterchina/dio#49]

**Comment by wendux** [comment]
这个可以直接在拦截器中print，很简单。
另外，okhttp中拦截器是分类的，并且其拦截器是一个队列。而dio中拦截器只有一个，这样会更灵活，因为，dio拦截器中你可以取到所有请求/响应数据，可以随意修改这些数据或干涉其执行流，也完全可以自己实现一个队列机制(在拦截器中分别调用队列中的处理器)。dio和okhttp在这一点上设计模式是不同的, 因此官方不会提供这样类。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by 403462630** [comment]
这是我写的flutter练习项目 https://github.com/403462630/flutter_zhifudaily  ，供大家学习参考
