### ISSUE TITLE
DioError Stacktrace Removed in v3.0.0+

### ISSUE THREAD

**Issue by searchy2** [flutterchina/dio#490]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
DioError used to have a stacktrace property that is now removed on v3.0.0. Why was the stacktrace property removed?

Is error.toString meant as the replacement for the Stacktrace variable?

**Comment by searchy2** [comment]
Please provide some guidance as to the implementation.

**Comment by searchy2** [comment]
Please provide some guidance as to the implementation.

**Comment by searchy2** [comment]
Not stale...

**Comment by searchy2** [comment]
Not stale...

**Comment by searchy2** [comment]
Still an issue

**Comment by searchy2** [comment]
Does anyone know the answer?

**Comment by searchy2** [comment]
Please update, thanks!

**Comment by amankr** [comment]
@searchy2 if you want to get Stacktrace, take a  look at `toString()` method in  `dio_error.dart`.
https://github.com/flutterchina/dio/blob/f1485e6ff77a77fefd1f1ed99df409d628e2e4d7/dio/lib/src/dio_error.dart#L50-L56

**Comment by searchy2** [comment]
Great find. Thanks for the clarification!
