### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Broken pipe, errno = 32

### ISSUE THREAD

**Issue by fabianogadenz** [flutterchina/dio#492]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

Dio Version :^3.0.3

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Broken pipe, errno = 32, address = teste.coopercredi.com.br, port = 48161
E/flutter ( 6640): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:942:7)
E/flutter ( 6640): <asynchronous suspension>
E/flutter ( 6640): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)
E/flutter ( 6640): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1099:22)
E/flutter ( 6640): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)
E/flutter ( 6640): #4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter ( 6640): #5      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 6640): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6640): #7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6640): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6640): #9      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6640): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6640): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter ( 6640): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter ( 6640): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter ( 6640): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter ( 6640): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

I am doing a post sending files and information and I am experiencing an error only on the phone, so the emulator works normally.

**Comment by breederComrade** [comment]
i get same error

**Comment by fabianogadenz** [comment]
can anyone help?

**Comment by fabianogadenz** [comment]
I believe the problem is occurring because I am not using SSL certificate. From Android 6, this problem happens, on an Android 6 device the error does not occur. I will enable an SSL certificate to see if this is the problem

**Comment by fabianogadenz** [comment]
I managed to find the error. An API that was uploading my file was not expecting a file type, so this error message would appear every time my file upload was larger than 2mb

**Comment by yasinarik** [comment]
I can successfully run my app on iOS Simulator but after a successful build, I am having problems with Dio.

Http package works as normal. I'd like to use Dio for multipart file uploading but it gave a similar error on my iPhone 8 device. 

I don't think it's about the file type. The receiving point is Google Cloud Storage. I also tried it with no file, just simple fields like username, bio, etc. The result is the same.

**Comment by yasinarik** [comment]
> I can successfully run my app on iOS Simulator but after a successful build, I am having problems with Dio.
> 
> Http package works as normal. I'd like to use Dio for multipart file uploading but it gave a similar error on my iPhone 8 device.
> 
> I don't think it's about the file type. The receiving point is Google Cloud Storage. I also tried it with no file, just simple fields like username, bio, etc. The result is the same.

Hmm... I've just discovered something. If I use my local server API address, it works on the iOS simulator.
`"http://localhost:8080"`
But if I change it to production configs as for example:
`"https://mysecretappaddress.appspot.com"` 
it doesn't work in the iOS simulator either. So it is not related to the iOS simulator nor the real iPhone device. It is about `http://` or `https://`

What can I do? Any recommendations? @fabianogadenz

**Comment by fabianogadenz** [comment]
@yasinarik I can't give more details, because the responsible API team made the changes.

The steps I followed were as follows:
1 - Turn my http into https. (maybe that didn't help at all).
2 - After a long time of testing, I found that files larger than 2mb returned this error. I contacted the responsible API team and they informed me that the parameter was not programmed to receive files but text. (their mistake).

Finally, it worked perfectly for me. Check these steps above and tell me if it worked because I made it work and I don't know what was causing the error

**Comment by nathansdev** [comment]
I have got fixed by changing the localhost to my network ip

**Comment by Pawelek55** [comment]
I had similar problem. My solution: I removed from header again declared content-text
` options: Options(
      headers: {
        "Authorization": "Bearer $token",
     //   "Content-type": "multipart/form-data"
      },
    ),`

**Comment by MahdiArabpour** [comment]
`SocketException` is thrown when there is a problem in server connection (e.g. when internet is not connected).
but dio package catches the framework default exceptions that are thrown inside of the package and throws it's own exception `DioError`, and differentiates the default exceptions from it's own exceptions using `type` field.
`SocketException` is a default exception so the `type` in `DioError` instance will be `DioErrorType.DEFAULT` and the `SocketException` instance itself will be in `error` field.
If you like to catch only the `SocketException` you can do something like this:
```
    try {
      //...
    } on DioError catch (e) {
      if (e.error is SocketException) {
        // TODO: handle SocketException
      }
      throw e.error;
    }
```

**Comment by henriquetroiano** [comment]
Thank you, @MahdiArabpour !
Just to help other people, with a ready-working example, just do the following:
run your function with a try catch, as async.
If you handle the socket exception, call itself as return await, and store a error count outside the function.
Example:
```
  int errorsCount = 0;
  checkAuthUser() async {
    try {
      await Dio().post("/auth/me");
      errorsCount = 0;
    } on DioError catch (e) {
      if (e.error is SocketException) {
        // TODO: handle SocketException
        // limit of 3 tries
        if (errorsCount <= 2) {
          await Future.delayed(const Duration(seconds: 1));
          errorsCount++;
          return await checkAuth();
        }
      }
      errorsCount = 0;
      // TODO: whatever you want to do
    }
  }
```
This example can be adapted to other languages, the idea is the same.
