### ISSUE TITLE
connectTimeout differ from 2.x

### ISSUE THREAD

**Issue by carmas123** [flutterchina/dio#494]
### New Issue Checklist

- [ x] I have searched for a similar issue in the THIS
(https://github.com/flutterchina/dio/issues) and found
https://github.com/flutterchina/dio/issues/462 <-- But is is closed :(

### Issue Info
Hello everyone, I found a problem with the 3.0.3 version. I see into [migration guide](https://github.com/flutterchina/dio/blob/e19ac920c662dfbae05ba5bbe082943852b0569a/migration_to_3.0.md) that from 3.x version `connectTimeout` property can be used only into the BaseOption and not for every connection (this could be a problem but not for me). Now after some test I see that this property does not work like 2.x version, this timeout exception is not fired never. The only exception fired when server was gone is CONNECTION_REFUSED (after response timeout). Into the 2.x version this work great.

Please investigate on that because this is really a big problem to handle connection problem expecially when we need to get from server a very long response. With the 2.x we use connectTimeout to get if the server is alive and use responseTimeout with an highest value because the server can be handle the request after some seconds or minutes.

With by best regards,
Massimo

**Comment by Attrezzi** [comment]
Hi Massimo, I've just got the same problem, I've noticed that whenever a BaseOptions is instantiated the connectTimeout value passed to the constructor is ignored. To solve this I simply set the value on the instantiated BaseOptions object.

var options = BaseOptions(
    baseUrl: Configuration.serverUrl,
    receiveTimeout: 5000,
    sendTimeout: 4000,
  );
  options.connectTimeout = 4000;

Hope it works for you!

**Comment by carmas123** [comment]
It does not wok
