### ISSUE TITLE
走到DioError直接卡死

### ISSUE THREAD

**Issue by pdliuw** [flutterchina/dio#495]
### 走到DioError直接卡死

使用Flutter 1.9-stable版本 + Dio3.xxx版本，当网络响应成功时，没有出现此问题；
当网络响应失败时（例如：断开网路,xxx），导致设备卡死！

### 日志/错误信息

当出现此情况时，没有任何日志输出。。。

### 问题描述和步骤

断开网络，执行网络操作！

### 特殊说明

当Flutter 1.9-stable版本+Dio2.xxx版本时，不会出现此问题！
当Flutter 1.10-master版本 + Dio3.xxx版本时，不会出现此问题！

初步推测是：Dio3.xxx版本为了适配Flutter web开发所做出的兼容，而忽略了可能会使用Flutter 1.9-stable或其他不支持web开发的版本+Dio3.xxx版本一起使用的情况，进而导致出现此问题！

**Comment by YQjiuhao** [comment]
这个问题从flutter1.7就有了~~#377

**Comment by ushang000** [comment]
+1

**Comment by fantasy525** [comment]
+1
我目前1.7.8，dio:2.1.0
如果服务器401的话就直接卡在android studio的断点了
![image](https://user-images.githubusercontent.com/22516157/69041590-b9c7ba80-0a2a-11ea-8b67-936cd1816624.png)

DioError [DioErrorType.RESPONSE]: Http status error [401]

**Comment by singleseeker** [comment]
Any update?
