### ISSUE TITLE
使用Future.wait并发请求一组url相同的操作，返回的结果回出现重复

### ISSUE THREAD

**Issue by yyc123** [flutterchina/dio#498]
当我把两个或多个url相同，只有参数不同的请求放进Future.wait方法中后，得到的response会异常，具体表现为两个请求的结果是相同的内容，但实际上他们应该是不同的相应结果（因为请求参数不同）
![D3C07409167CF987F1E62E90D3A67270](https://user-images.githubusercontent.com/13059922/66618573-19e96680-ec0c-11e9-9a0a-d4d92db14415.jpg)
是我的使用方法有问题吗？

**Comment by yyc123** [comment]
![5F8198EB-D76C-4303-A6FE-83A0685C6853](https://user-images.githubusercontent.com/13059922/66618693-ab58d880-ec0c-11e9-965a-6533443f0587.png)

**Comment by wendux** [comment]
不同的参数是不同的请求，这个是不会有问题的，你这个截图可能的原因有：
1. AS日志打印时顺序错了
2. 后台实现有问题
3. 是否使用了实现有问题的dio缓存插件？

建议抓包来验证一下。贴上我测试的代码（结果是正常的）：
```
import 'package:dio/dio.dart';

void getHttp() async {
  var dio = Dio();
  dio.interceptors.add(LogInterceptor(responseBody: true));
  dio.options.baseUrl = "http://httpbin.org";
  try {
    await Future.wait([
      dio.get("/get", queryParameters: {"id": 1}),
      dio.get("/get", queryParameters: {"id": 2})
    ]);
  } catch (e) {
    print(e);
  }
}

main() async {
  await getHttp();
}
```

**Comment by yyc123** [comment]
感谢，经过抓包，发现确实是后台返回的数据有问题。
