### ISSUE TITLE
opt.connectTimeout was ignored.

### ISSUE THREAD

**Issue by sososdk** [flutterchina/dio#500]
```
dependencies:
  dio: ^3.0.3
```

I request by `dio.get(url, options: RequestOptions(connectTimeout: 30 * 1000));`, `connectTimeout` is not work.

https://github.com/flutterchina/dio/blob/ec11282471276b3ce6abcbddc9080aebef1e6d79/dio/lib/src/dio.dart#L1063

**Comment by carmas123** [comment]
Duplicate of #494

**Comment by wendux** [comment]
Fixed at v3.0.4
