### ISSUE TITLE
MultipartFile和UploadFileInfo

### ISSUE THREAD

**Issue by StimeKe** [flutterchina/dio#505]
MultipartFile和UploadFileInfo

未升级3.0前我采用的是
FormData.form({“file”:UploadFileInfo()})
升级后采用
FormData.formMap({“file”:MultipartFile.formFile()})

但是我并未上传成功，得到的是一个错误
我是用在了上传阿里云OSS上面，下面是他的接口文档，希望能有其他办法解决一下
https://help.aliyun.com/document_detail/31988.html

**Comment by wendux** [comment]
`MultipartFile.formFile()`是异步的，使用它要给前面添加`await`关键字，也有一个同步方法，`MultipartFile.fromFileSync`

**Comment by StimeKe** [comment]
不好意思，我已经加了的，但是还是不可以，我这里是忘了打出来了

**Comment by MrLiuYS** [comment]
> 不好意思，我已经加了的，但是还是不可以，我这里是忘了打出来了

我也遇到同样的问题。请问你是怎么解决的呢？
