### ISSUE TITLE
服务器返回的错误是input is null

### ISSUE THREAD

**Issue by yuyongmao** [flutterchina/dio#51]
公司内部项目，不方便提供复现步骤，说一下问题吧；
     问题是出在Post请求，一直报错 ，返回错误信息如下：
{result: null, targetUrl: null, success: false, error: {code: 0, message: Your request is not valid!, details: The following errors were detected during validation.

 - input is null!

, validationErrors: [{message: input is null!, members: [input]}]}, unAuthorizedRequest: false, __abp: true}

但是用postman 测试是好用的，这个post请求是可以的
body->raw->JSON(application/json) 将数据的json文本填入其中，请求返回数据正常，
但是如果body中什么也不填，会得到上面同样的错误信息。

所以以为是没有给body赋值成功，故打印request.data ，发现是有数据的，而且是已经json过的

另外，用Dart Team的http 插件,post是可以成功的，不过赋值的参数名是body，很是疑惑

WHY?

**Comment by wendux** [comment]
公司源码不便公开的话，你可以写一个类似场景可重现的demo贴出来，没有代码的话根本看不到你的请求数据，没法定位……


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
