### ISSUE TITLE
Content Type is always becoming null

### ISSUE THREAD

**Issue by droidluv** [flutterchina/dio#510]
### Issue Info
| Platform Name                  |  flutter 
| Dio Version                    | 3.0.5
| Android Studio / Xcode Version | Xcode 1.39.0
| Repro rate                     | e.g. all the time (100%)
| Repro with our demo prj        | e.g. haven't checked

### Issue Description and Steps
The content type gets removed from all my requests

**Comment by droidluv** [comment]
temporarily I have downgraded to 2.1.16 and everything works fine again

**Comment by wendux** [comment]
Only when the request body is not null and the method is one of "POST", "PUT", "PATCH", "DELETE", the content-type will be valid. otherwise it is will be removed.

**Comment by droidluv** [comment]
![Screenshot 2019-11-20 at 5 56 25 PM](https://user-images.githubusercontent.com/9896966/69238996-40150580-0bbf-11ea-8c0b-47c8a13597af.png)
I have dio configured like this 

final Dio dio = Dio(
  BaseOptions(
    baseUrl: BASE_URL,
    connectTimeout: 60000,
    receiveTimeout: 60000,
    contentType: Headers.jsonContentType
  ),
)
  ..interceptors.add(
    InterceptorsWrapper(
      onRequest: (RequestOptions options) async {
        var prefs = await SharedPreferences.getInstance();
        String accessToken = prefs.getString(ACCESS_TOKEN);
        if (accessToken != null)
          options.headers = {
            "authtoken": accessToken,
          };
        // Do something before request is sent
        return options; //continue
        // If you want to resolve the request with some custom data，
        // you can return a `Response` object or return `dio.resolve(data)`.
        // If you want to reject the request with a error message,
        // you can return a `DioError` object or return `dio.reject(errMsg)`
      },
      onResponse: (Response response) {
        // Do something with response data
        return response; // continue
      },
      onError: (DioError e) {
        // Do something with response error
        return e; //continue
      },
    ),
  )
  ..interceptors.add(alice.getDioInterceptor())
  ..interceptors.add(PrettyDioLogger());

**Comment by droidluv** [comment]
Also I have the above code in the top level of a project and rely on the same instance for making all api calls throughout the app

**Comment by droidluv** [comment]
And again for the same code above 2.1.16 works just fine and dandy, but now I am encountering the need to update dio because of other dependencies I need

**Comment by droidluv** [comment]
This is still happening

**Comment by droidluv** [comment]
Is there any update on this @wendux, is this happening because I have my dio instance as a global variable? Because it seemingly doesn't happen for anyone else

**Comment by ShRyDeR** [comment]
I'm having this issue aswell.

**Comment by droidluv** [comment]
This still happens even in 3.0.9 my solution has been to add it through an interceptor, @wendux can you reopen his ticket?

**Comment by ahmedalrifai** [comment]
@droidluv  I am also having this issue. Did you found a solution?

**Comment by nimi0112** [comment]
My solution with `dio: 4.0.4`

```dart

class CustomInterceptor extends Interceptor {
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    options.contentType = Headers.jsonContentType;
    return super.onRequest(options, handler);
  }
}

//and call the interceptor

_dio!.interceptors.add(CustomInterceptor());

```

**Comment by yusufpats** [comment]
## **WORKING SOLUTION:**
The solution exists in the package itself, although it should have been well documented. A little digging into the SourceCode helped.

### **In Dio (`v4.x.x`):**
**SOURCE CODE** Reference: https://github.com/cfug/dio/blob/archive-4.x/dio/lib/src/options.dart
```
static const _allowPayloadMethods = ['POST', 'PUT', 'PATCH', 'DELETE'];

/// if false, content-type in request header will be deleted when method is not on of `_allowPayloadMethods`
bool setRequestContentTypeWhenNoPayload;
```

**SOLUTION:** Therefore, we have to set the flag when creating the `BaseOptions` object for the `Dio` object. 
Example:
```
dio.options = BaseOptions(
  baseUrl: "<baseUrl>",
  headers: {
    "accept": "application/json",
    "content-type": "application/json"
  },
  sendTimeout: "<int>",
  requestTimeout: "<int>",
  setRequestContentTypeWhenNoPayload: true, // <-- This is what we need to set to `true`
)
```

---


### **In Dio (`v5.x.x` and above):**
**SOURCE CODE** Reference: 
1. https://github.com/cfug/dio/blob/main/dio/lib/src/interceptors/imply_content_type.dart
```
/// {@template dio.interceptors.ImplyContentTypeInterceptor}
/// The default `content-type` for requests will be implied by the
/// [ImplyContentTypeInterceptor] according to the type of the request payload.
/// The interceptor can be removed by
/// [Interceptors.removeImplyContentTypeInterceptor].
/// {@endtemplate}
class ImplyContentTypeInterceptor extends Interceptor {
  const ImplyContentTypeInterceptor();
  ...
  ...
  ...
}
```
2. https://github.com/cfug/dio/blob/main/dio/test/interceptor_test.dart
```
test('can be removed with the helper method', () async {
  final dio = createDio();
  dio.interceptors.removeImplyContentTypeInterceptor();
  expect(
    dio.interceptors.whereType<ImplyContentTypeInterceptor>(),
    isEmpty,
  );
});

```

**SOLUTION:** Therefore, we have to call the method of the `Interceptors` object inside the `Dio` object. 
Example:
```
dio.interceptors.removeImplyContentTypeInterceptor();
```

Thanks, Goodluck.
