### ISSUE TITLE
Option.merge() ： ContentType bug

### ISSUE THREAD

**Issue by zhaojiewen** [flutterchina/dio#512]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                      |      |
| Platform Version               | 1.9.0                               |      |
| Dio Version                    |  3.0.1                                  |      |
| Repro rate                     | all the time (100%) |      |

### Issue Description and Steps

When I call "Option.merge()" method，an exception happened in "option.dart" file.
And I find this method go wrong for "ContentType" value,it should be "contentType ?? this.contentType" ,not "String ?? this.contentType ". The source code is as follow!

=============
Options(
      method: method ?? this.method,
      sendTimeout: sendTimeout ?? this.sendTimeout,
      receiveTimeout: receiveTimeout ?? this.receiveTimeout,
      extra: extra ?? Map.from(this.extra ?? {}),
      headers: headers ?? Map.from(this.headers ?? {}),
      responseType: responseType ?? this.responseType,
      contentType: String ?? this.contentType,
      validateStatus: validateStatus ?? this.validateStatus,
      receiveDataWhenStatusError:
          receiveDataWhenStatusError ?? this.receiveDataWhenStatusError,
      followRedirects: followRedirects ?? this.followRedirects,
      maxRedirects: maxRedirects ?? this.maxRedirects,
      requestEncoder: requestEncoder,
      responseDecoder: responseDecoder ?? this.responseDecoder,
    );
===============

**Comment by Deain** [comment]
old content-type
```dart
contentType = Headers.formUrlEncodedContentType

```
new
```
```

**Comment by wendux** [comment]
Fixed >=v3.0.3
