### ISSUE TITLE
put方式上传文件有问题

### ISSUE THREAD

**Issue by yousaywhat** [flutterchina/dio#513]
用FormData上传文件的时候，打印输出流里面发现多了四行，
----dio-boundary-3269679000
Content-Disposition: form-data; name="file"; filename="1568954750825.png"
Content-Type: application/octet-stream

流里面多了这4行导致文件内容后台解析失败了，这4行如何去掉。

**Comment by online2** [comment]
后面你是怎么解决的？

**Comment by online2** [comment]
> 用FormData上传文件的时候，打印输出流里面发现多了四行，
> ----dio-boundary-3269679000
> Content-Disposition: form-data; name="file"; filename="1568954750825.png"
> Content-Type: application/octet-stream
> 
> 流里面多了这4行导致文件内容后台解析失败了，这4行如何去掉。

后面你是怎么解决的？

**Comment by liufeihe** [comment]
这个问题你是怎么解决的？是因为用FormData上传文件，只能用post方法？

**Comment by liufeihe** [comment]
> 用FormData上传文件的时候，打印输出流里面发现多了四行，
> ----dio-boundary-3269679000
> Content-Disposition: form-data; name="file"; filename="1568954750825.png"
> Content-Type: application/octet-stream
> 
> 流里面多了这4行导致文件内容后台解析失败了，这4行如何去掉。

这个问题你是怎么解决的？是因为用FormData上传文件，只能用post方法？
