### ISSUE TITLE
dio 3.0.3 post 上传mp3文件还是会DioError

### ISSUE THREAD

**Issue by davyduan** [flutterchina/dio#514]
报错信息：DioError [DioErrorType.DEFAULT]: HttpException: Content size exceeds specified contentLength. 9733 bytes written while expected 214.
 • Flutter version 1.9.1+hotfix.4
 • Dart version 2.5.0
[20191016175108989.mp3.zip](https://github.com/flutterchina/dio/files/3737885/20191016175108989.mp3.zip)
上传图片没问题，音频文件就会报这个错

**Comment by wendux** [comment]
我在本地试过了，没有问题，我测试代码如下：
```dart
Future<FormData> FormData3() async {
  return FormData.fromMap({
    "file": await MultipartFile.fromFile("./example/20191016175108989.mp3.zip",
        filename: "20191016175108989.mp3.zip"),
  });
}
 response = await dio.post(
    //"/upload",
    "http://localhost:3000/upload",
    data: await FormData3(),
    onSendProgress: (received, total) {
      if (total != -1) {
        print((received / total * 100).toStringAsFixed(0) + "%");
      }
    },
  );
```

**Comment by davyduan** [comment]
不是上传zip文件，是上传mp3文件，zip文件解压之后的mp3文件

**Comment by davyduan** [comment]
i think this issue is still exist,can anyone reopen it ?
