### ISSUE TITLE
升级2.1.13 到3.0.3 版本，拦截器报错， 400返回码

### ISSUE THREAD

**Issue by superLiuYiPeng** [flutterchina/dio#521]
DioError [DioErrorType.RESPONSE]: Http status error [400]

**Comment by juncaixinchi** [comment]
可能是header的问题，我这边遇到过header里同时存在Content-Type, content-type大小写不同的两个字段，然后后端把stream用json去解析了。解决方案是统一用小写的

**Comment by harloom** [comment]
I same , app get respon 400 app crash

**Comment by pmrajani** [comment]
Why dio throw error in release mode for iOS?
ios debug and android release/debug build works fine.

using :   dio: ^3.0.10

ERROR: DioError [DioErrorType.RESPONSE]: Http status error [400] \nSTACK: #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:966)\n<asynchronous suspension>\n#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart)\n<asynchronous suspension>
