### ISSUE TITLE
使用dio请求报错，直接使用postman请求时可以的

### ISSUE THREAD

**Issue by philos3** [flutterchina/dio#525]
使用dio请求报错，直接使用postman请求时可以的

RequestUrl: https://api.huobi.vn/market/history/kline?period=1min&size=10&symbol=btcusdt
RequestMethod: GET
RequestHeaders:{content-type: application/json; charset=utf-8}
RequestContentType: application/json; charset=utf-8
RequestData: null
----------Error-----------
DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.

![image](https://user-images.githubusercontent.com/8424317/67544332-96f5ff00-f727-11e9-9d7c-8218ed38e43a.png)

**Comment by wendux** [comment]
跨域了吧

**Comment by philos3** [comment]
> 跨域了吧

这个是国内可以直接访问的地址， https://api.huobi.vn  应该不是跨域吧，https://api.huobi.pro才是国外的服务器地址

**Comment by philos3** [comment]
#465
