### ISSUE TITLE
cookie_jar ^0.0.4 is forbidden

### ISSUE THREAD

**Issue by sheteng63** [flutterchina/dio#53]
## Logs

the current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because cookie_jar 0.0.4 requires SDK version >=1.20.1 <2.0.0 and no versions of cookie_jar match >0.0.4 <0.1.0, cookie_jar ^0.0.4 is forbidden.
So, because idota depends on dio ^1.0.0 which depends on cookie_jar ^0.0.4, version solving failed.
pub get failed (1)

**Comment by wendux** [comment]
please update dio up to 1.0.1 and try again.
