### ISSUE TITLE
在web中请求无法获取response的headers中的相关信息

### ISSUE THREAD

**Issue by glj0209** [flutterchina/dio#531]
![1](https://user-images.githubusercontent.com/8816552/67655443-952c7580-f98b-11e9-9ce3-f53f37808723.png)
![3](https://user-images.githubusercontent.com/8816552/67655528-e177b580-f98b-11e9-8215-c17528e7efa8.png)

**Comment by mumumusuc** [comment]
@glj0209 我在v1.10.15-pre.384下运行flutter web，debug模式下确实拿不到完整的headers，不过在release模式下就能拿到完整headers了，你可以试试。

**Comment by mumumusuc** [comment]
@glj0209 确认了一下，同域下flutter web 的dio response可以拿到全部headers，跨域则不能。解决方法是设置你的web服务器expose headers字段，把你想要跨域获取的headers暴露出来，和dio没有什么关系。
“exposed headers indicates which headers are safe to expose to the API of a CORS”

**Comment by LoveRain1997** [comment]
> @glj0209 确认了一下，同域下flutter web 的dio response可以拿到全部headers，跨域则不能。解决方法是设置你的web服务器expose headers字段，把你想要跨域获取的headers暴露出来，和dio没有什么关系。 “exposed headers indicates which headers are safe to expose to the API of a CORS”

添加 Access-Control-expose-headers 修复了我的问题 :-)
