### ISSUE TITLE
上传aliOss报错，原因是header中Content-Disposition和Content-Type位置颠倒

### ISSUE THREAD

**Issue by zhanglei829** [flutterchina/dio#534]
首先感谢作者大大，开源这么好用的工具！

最近将公司原项目dio版本升级到3.0.4，发现原先正常上传图片到aliOss的功能不能用了，aliOss返回错误：The body of your POST request is not well-formed multipart/form-data。

经过比对2.x.x和3.x.x，发现如下不同点：

dio2.x.x上传文件header：
![191572402229_ pic](https://user-images.githubusercontent.com/40270286/67830748-d4d39880-fb16-11e9-9d58-22e7f7f1f14c.jpg)

dio 3.x.x上传文件header：
<img width="973" alt="WechatIMG20" src="https://user-images.githubusercontent.com/40270286/67830756-ddc46a00-fb16-11e9-99d1-4b152236e443.png">

dio 2.x.x 源码：
<img width="1259" alt="2 x" src="https://user-images.githubusercontent.com/40270286/67830764-e9179580-fb16-11e9-8ab2-e10a1d28d494.png">
dio 3.x.x源码：
<img width="1377" alt="3 x" src="https://user-images.githubusercontent.com/40270286/67830779-f3399400-fb16-11e9-97e9-fb9e776949a6.png">

解决办法：
手动更改源码，将二者调换位置，成功上传到AliOss。
![image](https://user-images.githubusercontent.com/40270286/67830834-2e3bc780-fb17-11e9-96a5-124a0baee25b.png)

希望作者能早日修复此bug，在issue中也有人提出类似问题，例如：例如#505。

**Comment by fvisticot** [comment]
I have the same issue and I can not upload picture with this current version. Can you please fix this issue ?

**Comment by wendux** [comment]
@zhanglei829 @fvisticot fixed it at v3.0.5, please update and try again.

**Comment by zhanglei829** [comment]
完美解决，👍
