### ISSUE TITLE
请求状态码414怎么处理？

### ISSUE THREAD

**Issue by MuZiLee** [flutterchina/dio#535]
I/ViewRootImpl(20960): jank_removeInvalidNode all the node in jank list is out of time
E/flutter (20960): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [414]

**Comment by MuZiLee** [comment]
我需要提交一些base64的图片，单个请求长度超出了限制，dio状态返回414.请问这个如何解决？

**Comment by MuZiLee** [comment]
@wprater @trevorwang @hpoul @passsy 
麻烦帮我看这我的问题。谢谢。
![image](https://user-images.githubusercontent.com/7467318/67859118-bb057600-fb55-11e9-8af7-71311614c745.png)
![image](https://user-images.githubusercontent.com/7467318/67859162-d7a1ae00-fb55-11e9-8318-b6d4813f90be.png)

**Comment by prasant10050** [comment]
Please solve it, i want to implement on my production app

**Comment by hpoul** [comment]
what am i having to do with all this?

**Comment by trevorwang** [comment]
please provide the code sample for this method

**Comment by trevorwang** [comment]
data 放到query parameter了

**Comment by MuZiLee** [comment]
是的，应该放到data里
