### ISSUE TITLE
使用你这个dio框架我文件一直没有办法传到后端

### ISSUE THREAD

**Issue by misskter** [flutterchina/dio#536]
使用formdata的方式传输文件，后台使用的是
@RequestParam("file") MultipartFile multipartFile, 一直获取不到文件，
错误信息是这样的 Required request part 'file' is not present
这个问题可以解决吗？

**Comment by prasant10050** [comment]
我的項目中也有問題，請有人解決此問題

**Comment by misskter** [comment]
我在项目中加入了
    Options options = Options();
    options.contentType = Headers.formUrlEncodedContentType;
这样的方式解决的，
如果还有这个问题，检查一下后端提供的值和你传入的值是否一样
