### ISSUE TITLE
FormatException: Invalid character in cookie name, code unit: '91'

### ISSUE THREAD

**Issue by dujianchi** [flutterchina/dio#54]
一直报DioError [DioErrorType.DEFAULT]: FormatException: Invalid character in cookie name, code unit: '91'错误。。。

使用步骤如下（基本按照官方教程）：
1.定义了个全局的Dio：
  static final _options = Options(
    connectTimeout: 15000,
    receiveTimeout: 15000,
    responseType: ResponseType.PLAIN,
  );
  static final _dio = Dio(_options);
2.get方法
  static Future<ResultEntity> get(BuildContext context, url) async {
    try {
      var response = await _dio.get(
        'http://xxxxxxxxx?xxx=xxx&xxxx=xxxx',
      );
      return _convert(context, response);
    } catch (e) {
      debugPrint('get request error = $e');
      _error(context, '网络错误，请稍后重试');
    }
    return null;
  }
3.报错：
DioError [DioErrorType.DEFAULT]: FormatException: Invalid character in cookie name, code unit: '91'

一开始以为是cookie没设置，但是设置了cookie也不行，不管是用dio自带的defaultcookiejar还是那个持久化的cookiejar，抑或是自己写了一个cookie jar，始终抱着个错误……

**Comment by dujianchi** [comment]
dio: ^1.0.1

**Comment by wendux** [comment]
duplicate #8


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by buxiaoxia** [comment]
@wendux   我使用的环境版本 dio: ^2.1.13    cookie_jar: ^1.0.1  dart 2.4

**Comment by buxiaoxia** [comment]
@wendux   我使用 ` _dio.interceptors.add(CookieManager(CookieJar()));` 的方式管理cookie。我的cookie里面包含了 `USER[visit_times]`。 提示我 “ Invalid character in cookie name, code unit: '91'”  表示cookie中 “[” 字符无效。  是什么原因？
 
我使用的环境版本 dio: ^2.1.13 cookie_jar: ^1.0.1 dart 2.4

**Comment by lixiangthinker** [comment]
@buxiaoxia  我也遇到了，跟踪了一下，Dart SDK 是按协议实现的，没有问题。可以参考一下我写的文章 https://juejin.im/post/5d6e34f1f265da03e5235109
