### ISSUE TITLE
send a request by dio.post()  in flutter web 

### ISSUE THREAD

**Issue by lyf571321556** [flutterchina/dio#548]
dio: ^3.0.4

flutter run -d chrome

send request in this way

var response =await dio.post(url,data:formdata)

result in web:
![image](https://user-images.githubusercontent.com/2295872/68377909-2a96e900-0186-11ea-96a4-d5c345163457.png)

 i did't get a expected response body in web ,but i got expected result in android and ios device;
result in mobile device:
![image](https://user-images.githubusercontent.com/2295872/68380593-1c979700-018b-11ea-8eb9-663ff7a33c91.png)

 incorrectly 'http method' lead to that result,how do i solve it?

**Comment by nukotsuka** [comment]
@lyf571321556 
How did you solve this problem?
