### ISSUE TITLE
2.1.0升级到3.0.0之后,无法使用ContentType.parse()

### ISSUE THREAD

**Issue by Kyou-sha-Belle-House** [flutterchina/dio#558]
当版本从2.1.0升级到3.0.0之后,
这行代码报错: options.contentType = ContentType.parse("application/x-www-form-urlencoded");
错误信息:
A value of type 'ContentType' can't be assigned to a variable of type 'String'.
Try changing the type of the variable, or casting the right-hand type to 'String'.

**Comment by wangyuan0108** [comment]
确实不能使用这个配置了，请问解决了吗？是哪里的问题？如何解决

> 当版本从2.1.0升级到3.0.0之后，
> 这行代码报错：options.contentType = ContentType.parse（“ application / x-www-form-urlencoded”）;
> 错误信息：
> 类型为ContentType的值可以不会被分配给'String'类型的变量。
> 尝试更改变量的类型，或将右侧类型转换为“字符串”。

**Comment by Kyou-sha-Belle-House** [comment]
木有解决, 还是用的2.1, 等作者给解决办法

**Comment by wendux** [comment]
`options.contentType =Headers.formUrlEncodedContentType`
