### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by wuhuaqing** [flutterchina/dio#559]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | android                          |      |
| Platform Version               | 9.0                              |      |
| Dio Version                    | 2.2.2                                 |      |
| Android Studio / Xcode Version | Android Studio 3.5           |      |
| Repro rate                     |  sometimes 20% /      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps

 DioError [DioErrorType.DEFAULT]: SocketException: OS Error: No route to host, errno = 113

**Comment by HeQingHua2018** [comment]
+1

**Comment by siyukok** [comment]
+1

**Comment by zengyifei** [comment]
+1
