### ISSUE TITLE
Can not upload file with FomData

### ISSUE THREAD

**Issue by fvisticot** [flutterchina/dio#563]
Platform Name flutter / android
Platform Version 1.9
Dio Version 3.04

I try to upload a file from bytes or from file and I get an error from server => "Current request is not a multipart request"

It was working with Dio Version 2.X

```
Future<UpdatePictureResponse> updateUserPicture(
      {File file, List<int> bytes}) async {
    FormData formData;
    if (file != null) {
      formData = FormData.fromMap({
        "image":
            await MultipartFile.fromFile(file.path, filename: "picture.jpg"),
      });
    } else if (bytes != null) {
      final multiPartBytes =
          await MultipartFile.fromBytes(bytes, filename: "picture.jpg");
      formData = FormData.fromMap({
        "image": multiPartBytes,
      });
    } else {
      throw ApiException('No image set');
    }

    try {
      final response = await _dio.post('/uaa/account/image',
          data: formData,
          options: Options(contentType: Headers.formUrlEncodedContentType),
          onSendProgress: (send, total) {});
      return UpdatePictureResponse(
          imageUrl: response.data['image_url'],
          thumbnailUrl: response.data['thumbnail_url']);
    } on DioError catch (e) {
      throw ApiException(e.message);
    } catch (e) {
      throw ApiException(e);
    }
  }
```

**Comment by fvisticot** [comment]
Same issue with 3.0.5

**Comment by fvisticot** [comment]
Adding logging interceptor I have this request:

Not sure content Type is correct


```
I/flutter (12327): *** Request ***
I/flutter (12327): uri: https://api.ticatag.com/v2/uaa/account/image
I/flutter (12327): method: POST
I/flutter (12327): responseType: ResponseType.json
I/flutter (12327): followRedirects: true
I/flutter (12327): connectTimeout: 5000
I/flutter (12327): receiveTimeout: 5000
I/flutter (12327): extra: {}
I/flutter (12327): headers:
I/flutter (12327):  content-type: application/json; charset=utf-8
I/flutter (12327):  Accept: application/json
I/flutter (12327):  Content-Type: application/json
I/flutter (12327): data:
I/flutter (12327): Instance of 'FormData'

```

**Comment by IkhwanSI13** [comment]
in version 3.0.5 too

**Comment by madboy1987** [comment]
`try {
      final response = await _dio.post('/uaa/account/image',
          data: formData,          
          onSendProgress: (send, total) {});
      return UpdatePictureResponse(
          imageUrl: response.data['image_url'],
          thumbnailUrl: response.data['thumbnail_url']);
    } on DioError catch (e) {
      throw ApiException(e.message);
    } catch (e) {
      throw ApiException(e);
    }`

try this,remove `options: Options(contentType: Headers.formUrlEncodedContentType),`

**Comment by fvisticot** [comment]
I have tried to remove the option as you was suggesting..
But issue is still there.

**Comment by PiN73** [comment]
It seems 213a476 breaks uploading files

**Comment by wendux** [comment]
@fvisticot   Check whether the request body  is correct with proxy tool (e.g charles).

**Comment by fvisticot** [comment]
I have checked with 3.0.7 and still the same issue.

Additional information:
- Can not see FormData in Alice Dio Plugin :(
- In Alice I can see that Content Type is present 2 times in header
content-type (lower case) : multipart ...
Content-Type (upper case): application/json

for information I'm using the same dio client for json and formData

![Screenshot_20191127-161019](https://user-images.githubusercontent.com/153679/69735510-19138200-1131-11ea-92ec-c89e53f8cea6.jpg)

**Comment by fvisticot** [comment]
If i create a "dedicated" DIO instance to upload the file it is OK, 
If i use a "global" DIO instance used for JSON and FormData it does not Work

**Comment by rio45ka** [comment]
@fvisticot what mean "dedicated", you solved your problem?

**Comment by droidluv** [comment]
Yup this is happening to me as well, also I'm not sure whether you guys noticed but content type randomly becomes null for other types of POST requests, @rio45ka I think he means a dynamic instance type when @fvisticot says a dedicated dio instance, I tried it and its not resolving the issue for me though, working with dio 3.x is causing way too many problems, version 2.1.16, doesn't give me any problems at all though, sad such an amazing library has become like this, just because it rushed to add web support.

**Comment by Joezzy** [comment]
> If i create a "dedicated" DIO instance to upload the file it is OK,
> If i use a "global" DIO instance used for JSON and FormData it does not Work

how did you create this dedicated instance
