### ISSUE TITLE
Cannot upload image on 3.0.5

### ISSUE THREAD

**Issue by bagus-repository** [flutterchina/dio#566]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
Platform : Android
Platform Version : 10
Dio Version: 3.0.5
Repro rate: 100%

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

I can still upload image on 3.0.3 but the timeout bug is there, today I upgrade to 3.0.5, the timeout bug is gone but then the Multipart file not send in server using this code, if i print the Future result the file content-type is application/octet-stream

> await MultipartFile.fromFile(image.path)

However, the image shown in preview, if I debug the headers is multipart/form-data, but null when received at server

**Comment by fvisticot** [comment]
Same issue with this code: 

```
Future<UpdatePictureResponse> updateUserPicture(
      {File file, List<int> bytes}) async {
    FormData formData;
    if (file != null) {
      formData = FormData.fromMap({
        "image":
            await MultipartFile.fromFile(file.path, filename: "picture.jpg"),
      });
    } else if (bytes != null) {
      final multiPartBytes =
          await MultipartFile.fromBytes(bytes, filename: "picture.jpg");
      formData = FormData.fromMap({
        "image": multiPartBytes,
      });
    } else {
      throw ApiException('No image set');
    }

    try {
      final response = await _dio.post('/uaa/account/image',
          data: formData,
          onSendProgress: (send, total) {});
      return UpdatePictureResponse(
          imageUrl: response.data['image_url'],
          thumbnailUrl: response.data['thumbnail_url']);
    } on DioError catch (e) {
      throw ApiException(e.message);
    } catch (e) {
      throw ApiException(e);
    }
  }
```

**Comment by liraku** [comment]
We also encountered the same situation and had to return 3.0.4.

**Comment by Slihao** [comment]
me too

**Comment by PiN73** [comment]
It seems 213a476 breaks uploading files

**Comment by dfmiller** [comment]
I've found this package very unreliable.  It has to be hardcoded to a specific version.  Doesn't anyone test it first?

**Comment by fvisticot** [comment]
Our app will be in production in a near feature. Can you please fixe the issue ?
