### ISSUE TITLE
下载大文件时，网络不好的情况下，会报 DioErrorType.RECEIVE_TIMEOUT

### ISSUE THREAD

**Issue by cy20061121** [flutterchina/dio#568]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

### Issue Description and Steps

请求出错：DioError [DioErrorType.RECEIVE_TIMEOUT]: Receiving data timeout[30000ms]
I/flutter (16121): #0      DioForNative.download.<anonymous closure> (package:dio/src/entry/dio_for_native.dart:211:9)
I/flutter (16121): <asynchronous suspension>
I/flutter (16121): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (16121): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (16121): #3      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
I/flutter (16121): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
I/flutter (16121): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:24)
I/flutter (16121): #6      Future._completeError (dart:async/future_impl.dart:530:5)
I/flutter (16121): #7      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:759:16)
I/flutter (16121): #8      _rootRun (dart:async/zone.dart:1120:38)
I/flutter (16121): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (16121): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter (16121): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
I/flutter (16121): #12     _rootRun (dart:async/zone.dart:1124:13)

只设置全局的超时时间
BaseOptions options = BaseOptions(
        connectTimeout: CONNECT_TIMEOUT,
        receiveTimeout: RECEIVE_TIMEOUT,
      );
本地模拟网络环境不好的情况时，会报以上错误
<img width="465" alt="image" src="https://user-images.githubusercontent.com/5145741/69292831-105b1180-0c42-11ea-8b8a-c3a365367d2a.png">

**Comment by wendux** [comment]
download(..., options: Options(
        receiveTimeout: 0 //0代表不设置超时
      ))

**Comment by cy20061121** [comment]
好的。验证是 ok的，谢谢了。

**Comment by MongieLee** [comment]
> download(..., options: Options( receiveTimeout: 0 //0代表不设置超时 ))

2025年了 还是有效方法 🤪
