### ISSUE TITLE
图片上传，Postman请求成功，但是dio上传失败~

### ISSUE THREAD

**Issue by cuixiaodong** [flutterchina/dio#570]
dio: 3.0.4
Dart: 2.5.0
Flutter:  1.9.1+hotfix.6

上传文件代码：
 static Future upLoadFile(String method, String uri, String filePath,
      ResponceSuccess responceSuccess, ResponceError responceError,
      {Map<String, dynamic> body}) async {
    // 头部
    Map<String, dynamic> heads = {
      "Content-Type": "multipart/form-data",
      "platform-type": "SHOP_KEEPER"
    };
    // token
    if (!StringUtils.isEmpty(Api.getInstance().token)) {
      heads['token'] = Api.getInstance().token;
    }
    Options op = Options(method: method, headers: heads);

    String name =
        filePath.substring(filePath.lastIndexOf("/") + 1, filePath.length);

    FormData formData = FormData.fromMap(
        {"file": await MultipartFile.fromFile(filePath, filename: name)});

    return _dio
        .request<Map<String, dynamic>>(uri,
            queryParameters: body ?? Map<String, dynamic>(),
            data: formData,
            options: op)
        .then((resp) {
      doResponse(resp, responceSuccess, responceError);
    });
  }

上传一直失败，dio还尝试3.0.0还有3.0.5版本，一样失败~

**Comment by ShshyDevooo** [comment]
我也遇到同样的情况一致 [DioErrorType.RESPONSE]: Http status error [404]报这个错误

**Comment by ShshyDevooo** [comment]
后台报错是MissingServletRequestParameterException,说是没有"file"参数。

**Comment by wendux** [comment]
1. 用v3.0.6
2. method是什么？
3. 抓一下请求包，截图贴出来

**Comment by ShshyDevooo** [comment]
> 1. 用v3.0.6
> 2. method是什么？
> 3. 抓一下请求包，截图贴出来

3.0.6现在下载不下来

**Comment by ShshyDevooo** [comment]
![TIM图片20191122141837](https://user-images.githubusercontent.com/9620338/69402582-3ad8c780-0d33-11ea-93e5-b9ee7d4571d7.png)
![TIM图片20191122141842](https://user-images.githubusercontent.com/9620338/69402584-3b715e00-0d33-11ea-911d-94c3692fead7.png)
这是我昨天抓的包

**Comment by Slihao** [comment]
3.0.6可以了

**Comment by cuixiaodong** [comment]
> 3.0.6可以了

还是不行！

**Comment by cuixiaodong** [comment]
> > 3.0.6可以了
> 
> 还是不行！

3.0.6可以了，但是问题还在~

**Comment by naijab** [comment]
> > > 3.0.6可以了
> > 
> > 
> > 还是不行！
> 
> 3.0.6可以了，但是问题还在~

me too. but I got 422 error

**Comment by wendux** [comment]
@cuixiaodong “可以了，问题还在”是什么问题？还有我无法复现，你后台是怎么接收的，贴一下代码吗？还有请对比postman的请求头看看和dio的请求头，看看差异在什么地方。我这没法帮你调试。

**Comment by cuixiaodong** [comment]
> @cuixiaodong @naijab 刚merge了一个FormData的MR，可以先升级到3.0.7试试是否OK.
> 如果问题依然存在请对比postman的请求头看看和dio的请求头，看看差异在什么地方。我这没法帮你调试。

Postman请求：
![1574686375889](https://user-images.githubusercontent.com/11581208/69542147-c8cbe100-0fc5-11ea-9666-093ae7fed37b.jpg)
![1574686405978](https://user-images.githubusercontent.com/11581208/69542191-e1d49200-0fc5-11ea-8bea-f8357e171d08.jpg)

Dio请求:
![1574686338156](https://user-images.githubusercontent.com/11581208/69542261-09c3f580-0fc6-11ea-9c6e-3c91a6f015e3.jpg)
![1574686304055](https://user-images.githubusercontent.com/11581208/69542323-295b1e00-0fc6-11ea-9ca4-934c544aa19c.jpg)
服务端返回数据:{"code":"500","msg":"后台异常","data":""}

**Comment by wendux** [comment]
@cuixiaodong 是3.0.7吗？如果是的话，需要抓一下dio的请求包，来对比postman和dio的请求包。还有,服务端报500的话也可以看一下服务端日志，看看什么问题导致了服务端错误

**Comment by cuixiaodong** [comment]
> @cuixiaodong 是3.0.7吗？如果是的话，需要抓一下dio的请求包，来对比postman和dio的请求包。还有,服务端报500的话也可以看一下服务端日志，看看什么问题导致了服务端错误

![TIM图片20191126164331](https://user-images.githubusercontent.com/11581208/69613132-fa978300-106b-11ea-906d-94b38f8e2fb4.png)
![TIM图片20191126164450](https://user-images.githubusercontent.com/11581208/69613184-18fd7e80-106c-11ea-9fea-4b1a46bcdbf0.png)

用的是3.0.7，其实请求方式、params、请求头都没问题，唯一不太一样的就是异常情况下，也就是图二，红色区域少了一个文件的Content-Length。MultipartFile之前也有打印，也有数据的。

**Comment by wendux** [comment]
看不出问题啊，500是服务端异常了，看看服务端日志吧。要么就提供一下服务端的代码，我本地跑一下，要不然我也追查不了了....

**Comment by cuixiaodong** [comment]
> 看不出问题啊，500是服务端异常了，看看服务端日志吧。要么就提供一下服务端的代码，我本地跑一下，要不然我也追查不了了....

好，这边先跟服务端排查下。

**Comment by luohs** [comment]
> > 看不出问题啊，500是服务端异常了，看看服务端日志吧。要么就提供一下服务端的代码，我本地跑一下，要不然我也追查不了了....
> 
> 好，这边先跟服务端排查下。

hello [问题解决了吗？我们报如下错误：
![dio-3 0 7-upload-error](https://user-images.githubusercontent.com/4815712/71135492-b5b2d680-223c-11ea-9f5f-be8f59fd4d5e.png)
postman可以正常上传

**Comment by luohs** [comment]
> > 看不出问题啊，500是服务端异常了，看看服务端日志吧。要么就提供一下服务端的代码，我本地跑一下，要不然我也追查不了了....
> 
> 好，这边先跟服务端排查下。

你好，问题解决了吗？我们报“未选择文件上传”，服务端小伙伴说没有收到图片的二进制流。postman是可以正常上传的，传的自定义参数都是一样的，但是不知道postman和dio默认参数哪里存在差异。我用的是dio 3.0.7 版本

**Comment by MeDeity** [comment]
之前用的是2.x的版本上传成功,我现在采用的版本是3.0.7.
`
FormData requestParams = FormData.fromMap({
      "image_file": MultipartFile.fromFile(imageFile.path,filename:PortraitUtils.getFileName(imageFile)),
 });
`
接口调用时，会告诉我image_file文件没有上传

![image](https://user-images.githubusercontent.com/25357490/71500572-82a5be00-28a0-11ea-9151-7cbd7aa2b516.png)

**Comment by pheromone** [comment]
我的也是500报错. 其他图片可以,就几张不行. 但是小程序都可以.后台完全没有收到这条请求.而上传其他图片又是可以....
![image](https://user-images.githubusercontent.com/14305431/71607034-19c88980-2bb1-11ea-8f1c-0bae75d32ee1.png)

**Comment by pheromone** [comment]
我这边弄好了,上传之前需要对图片先压缩一下,不敢多大都压缩下就好,不压缩的话,有时2-3M都可以成功,几百k的却失败,这个时候压缩一下就好了.压缩我是用 https://github.com/OpenFlutter/flutter_image_compress

**Comment by cuixiaodong** [comment]
我这边后期让服务端配合修改了，现在上传没问题了。

**Comment by shingsoso** [comment]
> 我这边后期让服务端配合修改了，现在上传没问题了。

請問一下服务端是做了什麼修改？

**Comment by Hu-Wentao** [comment]
> > 我这边后期让服务端配合修改了，现在上传没问题了。
> 
> 請問一下服务端是做了什麼修改？

我让后端把文件格式校验的代码去掉了, 然后就成功了

**Comment by CauliflowerGoer** [comment]
同失败 ,  在后台就没拿到数据
![image](https://user-images.githubusercontent.com/59127546/87017129-2a158d00-c202-11ea-82ec-53df15d27aa1.png)

**Comment by AcYangle** [comment]
我也遇到了同样的问题，我使用for循环上传多张图片，循环次数<=2时都能成功，>2时只会成功2次，其余的全报500
有遇到同样问题的吗
for (var item in resultList) {
    HttpManager().uploadAsync(
      url: Api.uploadImage(),
      tag: 'uploadimage' + item.path,
      options: Api.getHeader(),
      data: FormData.fromMap({
        // "file": await MultipartFile.fromFile(widget.file.path,
        //     filename: "file.jpg"),
        'file': MultipartFile.fromBytes(
          File(item.path).readAsBytesSync(),
          filename: item.path.split("/").last,
        ),
      }),
      onSendProgress: (count, total) {
        print(count.toString() + '-----' + total.toString());
        // setState(() {
        //   isUpLoading = true;
        //   progress = (count / total).toDouble();
        // });
      },
      jsonParse: (code, data) {
        // widget.uploadFinishCall(data);
        // print(widget.file);
        // setState(() {
        //   progress = 1.0;
        //   isUpLoading = true;
        // });
      },
      errorCallback: (code, data) {
        CustomToast.showToast(msg: data);
      },
    );
  }

**Comment by Hu-Wentao** [comment]
可能与文件头的media type有关, 多与后端沟通一下
