### ISSUE TITLE
dio post请求问题

### ISSUE THREAD

**Issue by dyjmlf** [flutterchina/dio#571]
### Issue Info
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name              | flutter  / android                          |      |
| Platform Version            | 1.9.0 / 9.0                              |      |
| Dio Version                    | 3.0.5                                  |      |

### Issue Description and Steps
请问大神 为什么我 直接利用案例向请求后台数据，无论post还是get都获取不到uname和passwd
dio.post("test.php", data: {"passwd": 123, "uname": "tom"});
但是利用
FormData formData = new FormData.fromMap({
    "uname": "wendux", "passwd": 123,});
dio.post("test.php", data: formData);
包装后，后台post可以获取到uname和passwd
所以我想请问 dio.post("test.php", data: {"passwd": 123, "uname": "tom"}); 这种向后台发送什么方式的请求，后台用什么方式处理能获取uname和passwd

**Comment by wendux** [comment]
FormData 会按照multipart/form-data编码，而直接post 则是json编码，另外还有[application/x-www-form-urlencoded](https://github.com/flutterchina/dio/#using-applicationx-www-form-urlencoded-format)的编码方式。FormData 一般用于文件上传，而json和application/x-www-form-urlencoded用于普通数据提交。

**Comment by dyjmlf** [comment]
非常感谢。
