### ISSUE TITLE
请求取消之后如何再恢复

### ISSUE THREAD

**Issue by yousaywhat** [flutterchina/dio#572]
我上传10张图片，因为某些原因现在将用户挤出，然后使用 token.cancel("cancelled");将后面的上传接口全部取消掉，但是用户如果重新登录再使用上传接口时，无法上传，这个取消如何恢复

**Comment by yousaywhat** [comment]
DioError [DioErrorType.CANCEL]: cancelled

**Comment by xiejibiao** [comment]
@yousaywhat 应该怎么恢复呢？有点看不懂上面的操作

**Comment by yousaywhat** [comment]
@xiejibiao 就是我调用它的upload上传文件，配置了cancelToken，然后在上传很多文件，到某一个文件时可能出现用户被挤掉的情况，这时候我调用了token.cancel("cancelled"); 让用户未上传完的图片不再上传，退回到登录页面，然后用户登录进来以后再想上传文件时，Dio就报错DioError [DioErrorType.CANCEL]: cancelled

**Comment by KinedYK** [comment]
I also encountered the same problem。Did you find a solution？？

**Comment by qcdys** [comment]
> @xiejibiao 就是我调用它的upload上传文件，配置了cancelToken，然后在上传很多文件，到某一个文件时可能出现用户被挤掉的情况，这时候我调用了token.cancel("cancelled"); 让用户未上传完的图片不再上传，退回到登录页面，然后用户登录进来以后再想上传文件时，Dio就报错DioError [DioErrorType.CANCEL]: cancelled



> I also encountered the same problem。Did you find a solution？？

两位解决了吗？

**Comment by qcdys** [comment]
> 我上传10张图片，因为某些原因现在将用户挤出，然后使用 token.cancel("cancelled");将后面的上传接口全部取消掉，但是用户如果重新登录再使用上传接口时，无法上传，这个取消如何恢复

楼主怎么解决的 能分享一下吗

**Comment by SinoMiles** [comment]
same issue.

**Comment by ninosroger** [comment]
@SinoMiles @Pluto1219 @KinedYK 
两个方式
第一个是把DioError的type换成非CANCEL类型的值。
第二个是把传入的cancelToken对象赋一个新的实例。
`CancelToken cancelToken = CancelToken();

//接口调用传入cancelToken 
_dio.request<String>(
      url,
      data: data,
      queryParameters: queryParameters,
      options: _checkOptions(method, options),
      cancelToken: cancelToken,
    )

//取消请求
cancelToken.cancel();

//逻辑处理完为cancelToken赋个新实例
cancelToken= CancelToken();
`
