### ISSUE TITLE
Unsupported operation: Unsupport download API in browser

### ISSUE THREAD

**Issue by zenkog** [flutterchina/dio#573]
My project is using Flutter Web. It's not for production but we need the functionality for something else..
However, I got an exception caught when I used .downloaded method:
"Unsupported operation: Unsupport download API in browser"

The code I wrote is like this:

void downloadImage() async {
    Dio dio = Dio();
    String urlTest = 'some url string';
    try {
      await dio.download(urlTest, './testPic123.png');  //trying to save in local directory of my own computer
      print('Success!');
    } catch (error) {
      print(error);
    }
  }

Its just a simple code

I'm using Dio version 3.0.6

Here is my Flutter doctor: 

[✓] Flutter (Channel dev, v1.12.2, on Mac OS X 10.14.6 18G95, locale en-US) 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (3 available)

• No issues found!

I don't know if these next information is relevant but I also have disabled CORS by adding this to my http.conf: Access-Control-Allow-Origin "*"
Moreover, this is my httpd -v

Server version: Apache/2.4.34 (Unix)
Server built:   Feb 22 2019 20:20:11

I'm using MacBook Pro with Mojave OS ver 10.14.6

Any clue?? 

Thank you everyone!

**Comment by mahmoudsalah37** [comment]
i have the save error:
import 'package:dio/dio.dart as dio;
        dio.Response response = await dio.Dio()
                       .download("https://www.google.com/", "./xx.html");
                   print(response.data.toString());

**Comment by shashwatadi** [comment]
Same for me. Flutter web seems to have some issue :(

**Comment by handersonc** [comment]
I'm getting the same build for web

**Comment by aragonet** [comment]
The same is happening to me. Hope they reopen this issue.

I've solve it using  `html.window.open(url, '');` if `dart:html` is available. If not, use dio as usual.

**Comment by abdullah432** [comment]
If anyone finds a solution then please share it. I'm facing the same problem.

**Comment by cbanaspk** [comment]
> If anyone finds a solution then please share it. I'm facing the same problem.

Was this ever resolved?

**Comment by yunxingyu** [comment]
The same is happening to me 
Unsupported operation: Unsupport download API in browser
E/flutter (15503): #0      DioMixin.download (package:dio/src/dio_mixin.dart:362:5)
E/flutter (15503): #1      ObtainM3u8Imp.startDownload (package:app/ui/player/obtainm3u8imp.dart:302:34)

**Comment by HaraldRichter** [comment]
Still an issue...
Error: Unsupported operation: download() is not available in the current environment.

**Comment by lele9191** [comment]
It seems that still the same. Reopen pls !! :'(

**Comment by DanielJaramillo94** [comment]
Still uncompleted in web right now 😢
