### ISSUE TITLE
ResponseType设置为Json不生效

### ISSUE THREAD

**Issue by gehangAndroid** [flutterchina/dio#58]
ResponseType设置为JSON，返回的请求体还是String的，所以在接收请求结果时就报错DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, Object>'等

**Comment by wendux** [comment]
![image](https://user-images.githubusercontent.com/20411648/44966331-29a86d00-af6d-11e8-86df-bfa22d5fa32a.png)
你先检查一下`content-type`是否正确

**Comment by wendux** [comment]
长时间没回复，先关了，若有问题再打开

**Comment by gehangAndroid** [comment]
响应头中的content-type不为json,为text/html;charset=utf-8,，dio设置ResponseType能转为json吗

**Comment by wendux** [comment]
默认不能，除非你自定义一个transformer, 自定义transformer比较简单，示例可以在项目示例目录中找到。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
