### ISSUE TITLE
Uploading files in Flutter Web

### ISSUE THREAD

**Issue by rjcalifornia** [flutterchina/dio#580]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Flutter Web                          |      |
| Platform Version               |   12.0                           |      |
| Dio Version                    | 3.0.7                                  |      |
| Android Studio / Xcode Version |  . Android Studio 3.5              |      |
| Repro rate                     |  all the time (100%)    |      |
 

### Issue Description and Steps
Issue: Flutter Web File Upload

I'm developing a Flutter Web app. I am able to save data (string values) with Dio without issues. Everything works as expected. However, when I'm trying to upload a file I get this error:

**Uncaught (in promise) Error: Unsupported operation: MultipartFile is only supported where dart:io is available.**
 

I'm following the official documentation instructions without success. Any workaround this?

**Comment by mumumusuc** [comment]
Flutter has not fully support the IO operation on web platform. Check this [Link](https://flutter.dev/docs/development/platform-integration/web#can-i-use-dartio-with-a-web-app) for more details.

**Comment by rjcalifornia** [comment]
Alright, I checked that. Is there a workaround this? Would you consider to update the docs to let others know about not being fully compatible with Flutter Web?

**Comment by rjcalifornia** [comment]
Nevermind, the example code in the package page works.

**Comment by Chethanpoojary17** [comment]
> Nevermind, the example code in the package page works.

Can you share the code which works?? Thank you

**Comment by Rouvo** [comment]
> > Nevermind, the example code in the package page works.
> 
> Can you share the code which works?? Thank you

Hi @Chethanpoojary17 , I kinda hit the same issue in flutter web without using dio, this one is working in web, guess you can utilize ".fromBytes" with some uint8List aswell in dio 


```
import 'package:http/http.dart' as http;

[..]

var request = http.MultipartRequest('POST', Uri.parse(serviceUrl));
request.files.add(http.MultipartFile.fromBytes('file', excel.bytes, filename: excel.name));
http.StreamedResponse res = await request.send();
```

**Comment by aumb** [comment]
If anyone is still wondering how to get it working on both mobile and web (This is using the `image_picker`'s `PickedFile` as the `image` variable type) :

```dart
 FormData body;
 final bytes = await image.readAsBytes();
 final MultipartFile file = MultipartFile.fromBytes(bytes, filename: "picture");
 MapEntry<String, MultipartFile> imageEntry = MapEntry("image", file);
 body.files.add(imageEntry);
```
The catch is that the filename is required.

**Comment by haroonkhan9426** [comment]
@aumb Thank you so much. The above solution worked.

**Comment by HKTareen** [comment]
@aumb  Very Very Thanks to you for your support .
