### ISSUE TITLE
how can i  print FormData as a string 

### ISSUE THREAD

**Issue by philos3** [flutterchina/dio#581]
how can i  print FormData as a string 

if dio has  a method like FormData.toString()

**Comment by wendux** [comment]
```dart
String str=utf8.decode(await formdata.readAsBytes(),allowMalformed: true);
```
Notice: `formdata.readAsBytes()`  can be called only once, because `Formdata`  is based on `Stream`, and one `Stream`  can only be consumed  by one consumer.

**Comment by YaoShuwei** [comment]
print(FormData.fields)
