### ISSUE TITLE
Cookie manager for flutter web

### ISSUE THREAD

**Issue by developerandre** [flutterchina/dio#585]
Do you plan for support **Cookie manager** in **web**?

**Comment by wendux** [comment]
No, cookies are automatically managed by the browser

**Comment by whimthen** [comment]
> No, cookies are automatically managed by the browser

Use flutter web to develop websites, and background services use golang, but cookies cannot always be set automatically when I request an interface. The headers returned by dio printing in flutter are only Content-Type and Content-Length, but in the browser developer mode, There is a Set-Cookie option in the Response header. The cookie-manager with the dio plug-in also has no effect. How to solve this situation?

![image](https://user-images.githubusercontent.com/26761592/71390445-6228fa00-263b-11ea-9542-c64bae22bfc6.png)
![image](https://user-images.githubusercontent.com/26761592/71390460-77058d80-263b-11ea-99ce-7b7c0ef05c45.png)
![image](https://user-images.githubusercontent.com/26761592/71390482-88e73080-263b-11ea-803c-e6e94bc6526c.png)

**Comment by whimthen** [comment]
I solved the problem. 
Using http package
```dart
BrowserClient _client = BrowserClient();
// This property will automatically set cookies
_client.withCredentials = true;
await client.get("http://localhost:1234/islogin");
```

**Comment by whimthen** [comment]
I solved this problem.
```dart
BaseOptions options = new BaseOptions(
    baseUrl: _baseUrl,
    connectTimeout: 10000,
    receiveTimeout: 5000,
    headers: {
        "Accept": "application/json",
    },
);
DioForBrowser _d = DioForBrowser(options);
var adapter = BrowserHttpClientAdapter();
// This property will automatically set cookies
adapter.withCredentials = true;
_d.httpClientAdapter = adapter;
_d.get("http://localhost:1234/login...")
```

**Comment by chitgoks** [comment]
> I solved this problem.
> 
> ```dart
> BaseOptions options = new BaseOptions(
>     baseUrl: _baseUrl,
>     connectTimeout: 10000,
>     receiveTimeout: 5000,
>     headers: {
>         "Accept": "application/json",
>     },
> );
> DioForBrowser _d = DioForBrowser(options);
> var adapter = BrowserHttpClientAdapter();
> // This property will automatically set cookies
> adapter.withCredentials = true;
> _d.httpClientAdapter = adapter;
> _d.get("http://localhost:1234/login...")
> ```

this didnt work for me. i also am encountering the same issue as you did. content length and type are available but cookies are not.

same issue with http and httpclientresponse aside from dio.

**Comment by chitgoks** [comment]
My original comment was it did not work but i was mistaken. It does. the thing is, withCredentials is required in order for cookies to be written to browser.

Shouldnt the default dio object have this property?  instead of having to use DioForBrowser?

**Comment by LucaIaconelli** [comment]
> I solved this problem.
> 
> ```dart
> BaseOptions options = new BaseOptions(
>     baseUrl: _baseUrl,
>     connectTimeout: 10000,
>     receiveTimeout: 5000,
>     headers: {
>         "Accept": "application/json",
>     },
> );
> DioForBrowser _d = DioForBrowser(options);
> var adapter = BrowserHttpClientAdapter();
> // This property will automatically set cookies
> adapter.withCredentials = true;
> _d.httpClientAdapter = adapter;
> _d.get("http://localhost:1234/login...")
> ```

Hello,

I performed this procedure but flutter continues to print as content-type headers only: `application/json; charset = utf-8` and not all data present in the console. How can I solve it?

Thanks in advance

**Comment by tstrg** [comment]
I'm still not able to see the cookie in chrome tab

> > I solved this problem.
> > ```dart
> > BaseOptions options = new BaseOptions(
> >     baseUrl: _baseUrl,
> >     connectTimeout: 10000,
> >     receiveTimeout: 5000,
> >     headers: {
> >         "Accept": "application/json",
> >     },
> > );
> > DioForBrowser _d = DioForBrowser(options);
> > var adapter = BrowserHttpClientAdapter();
> > // This property will automatically set cookies
> > adapter.withCredentials = true;
> > _d.httpClientAdapter = adapter;
> > _d.get("http://localhost:1234/login...")
> > ```
> 
> Hello,
> 
> I performed this procedure but flutter continues to print as content-type headers only: `application/json; charset = utf-8` and not all data present in the console. How can I solve it?
> 
> Thanks in advance

I'm facing the same issue. I set the withCredentials to true, but I'm still not able to see the cookies in the chrome dev tab.
