### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by BaroneX** [flutterchina/dio#587]
### New Issue Checklist

#14,#33,#444

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / ios / android                          |      |
| Platform Version               | 1.9.1 / 13.0 / 9.0                              |      |
| Dio Version                    | 3.0.7                                  |      |
| Android Studio / Xcode Version | Android Studio 3.4 / Xcode 11.2              |      |
| Repro rate                     | all the time (100%)    |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

the server support mutual authentication
```
ByteData chainString = await rootBundle.load("assets/client.crt");
ByteData keyString = await rootBundle.load("assets/client.key");
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
          (client) {
        SecurityContext sc = new SecurityContext(withTrustedRoots: true);
        
        sc.useCertificateChainBytes(chainString.buffer.asUint8List());
        sc.usePrivateKeyBytes(keyString.buffer.asUint8List());
        HttpClient httpClient = new HttpClient(context: sc);

       httpClient.badCertificateCallback = ((X509Certificate cert, String host, int port) => true);

        return httpClient;
      };
```
I have configured the certificate and private key
in Android Device 
```
DioError (DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:352)))
```

in iOS Device 
```
DioError (DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: ok(handshake.cc:352)))
```
I tried postman and it was good

![image](https://user-images.githubusercontent.com/6743367/70026018-9af42700-15d9-11ea-89cc-df2382ac6901.png)

**Comment by s2yed** [comment]
8182): ╔╣ DioError ║ DioErrorType.DEFAULT
I/flutter ( 8182): ║  HandshakeException: Handshake error in client (OS Error: 
I/flutter ( 8182): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))

**Comment by yukon-pasindujayanath** [comment]
Dio Error Occured  : DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error: 
I/flutter (32670): │ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:359)).
