### ISSUE TITLE
Debug模式下，post请求结果正确，但很慢。Release模式下，结果错误。

### ISSUE THREAD

**Issue by zxl777** [flutterchina/dio#588]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter /iOS/ android                          |      |
| Platform Version               | e.g.  1.9.1 + hotfix.6 / 13.2 / 8.1                             |      |
| Dio Version                    | e.g.  2.1.7 和 3.0.7                              |      |
| Android Studio / Xcode Version | e.g. VSCODE 1.40.2 / Xcode 11.2.1             |      |
| Repro rate                     | e.g. all the time (100%)    |      |

### Issue Description and Steps

代码如下 
```
Future login(String username, String password) async {
  if (username == "" || password == "") {
    BotToast.showText(text: "🧐 Username or Password Empty");
    return;
  }
  BotToast.showLoading();
  try {
    response = await dio.post(hubURL + "/login",
        data: {"username": username, "password": passwordHash(password)});

    if (response.statusCode == HttpStatus.ok) {
      var json = jsonDecode(response.toString());
      GG.apiToken = json['token'];
      print(GG.apiToken);
    }
  } on DioError catch (e) {
    print(e.response); //密码错误401
    BotToast.showText(text: "🧐 Username or Password Error");
  } finally {
    BotToast.closeAllLoading();
  }
}

```

另外看到Issue下也有网友提到“请求很慢”的问题，但都因为无法重现而被关闭了。
但问题终究是没有解决。

能不能告诉我怎么提供DIO的log，以便在无法重现的情况下，也能解决这个问题。谢谢。

**Comment by zxl777** [comment]
用iPhone 7 Plus实验了一下，也有请求慢的问题。
启动app后，第一次请求最慢。后面几次请求就快了数倍。

**Comment by 390057892** [comment]
我用安卓机器也有这个问题,不知道如何解决
