### ISSUE TITLE
请教下这种图片返回的数据如何放在flutter里面显示？

### ISSUE THREAD

**Issue by sidealice** [flutterchina/dio#59]
https://login.sina.com.cn/cgi/pin.php?r=

没有找到image可以设置data的。不知道有没有解决方案？

    Options options = Options(
      responseType: ResponseType.STREAM,
      contentType: ContentType.parse('image/png'),
      method: 'get',
      headers: headers,
    );
    Response<dynamic> response = await dio.get(
      url,
      options: options,
    );

这种方式是对的吗？

**Comment by sidealice** [comment]
已经解决。抱歉这个问题和dio没关系。

**Comment by w4mxl** [comment]
> 已经解决。抱歉这个问题和dio没关系。

@sidealice 请问能说一下是如何解决的吗？

**Comment by LoveRain1997** [comment]
这样写就行  
static Future<Uint8List> getCaptchaByMobile(String mobile) async {

    Options options = Options(
      responseType: ResponseType.stream,
    );

    Response   response = await http
        .get(Urls.GetCaptchaByMobile, queryParameters: {"mobile": mobile},options: options);
    ResponseBody resp = response.data;

  return  resp.stream.first;

  }
