### ISSUE TITLE
Dio throws exception with [500], but I can print the response code and it's a successful 204

### ISSUE THREAD

**Issue by MilesAdamson** [flutterchina/dio#592]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  android                          |      |
| Dio Version                    | 2.1.7                                  |      |
| Repro rate                     |100%   |      |
| Repro with our demo prj        | No            |      |

### Issue Description and Steps

```
      try {
        String binding = await userRepository.getEnvBinding(event.subDomain);
        Response r =  await apiTwilioBinding.deleteBinding(
            event.subDomain, event.accessToken, binding);
        print(r.statusCode);
        await userRepository.deleteEnvBinding(event.subDomain);
        yield TwilioBindingNotSet();
      } catch (e) {
        String message = '${event.subDomain} unbinding failure: $e';
        print(message);
        yield TwilioBindingFailed(message: message);
      }
```

```
I/flutter (26701): 204
I/flutter (26701): demo unbinding failure: DioError [DioErrorType.RESPONSE]: Http status error [500]
```

What happened here, is that the server gave me a 204 code. The operation was certainly successful. I can print the response code to console and it says 204. Yet, dio still throws an exception saying there was a 500 server error.

In no circumstances would I expect both print statements to print, especially with 2 different status codes. I'm not even sure if this is an issue with Dio specifically, but it is very strange.

**Comment by rakakhrl** [comment]
I have the same issue.

My http request is successful and i can print the data i get to console but Dio keep throwing exception so my app thought there's an error and not displaying any data.

**Comment by lreardon** [comment]
I'm also encountering the same issue!

**Comment by Ruslanbek0809** [comment]
In my case, my solution was to make dio return type `dynamic` like this:

```
dio.delete<dynamic>('delete/api');
```
