### ISSUE TITLE
Post Body  Empty in backend 

### ISSUE THREAD

**Issue by harloom** [flutterchina/dio#595]
service dio
```
 class DioService {
  FirebaseAuth _auth = FirebaseAuth.instance;
  Dio _dio;
  DioService() {
    BaseOptions options = BaseOptions(
        connectTimeout: 6000, receiveTimeout: 6000, baseUrl: BASEAPI);
    this._dio =  Dio(options);
    _setupDioInterceptor();
  }

  get connect{
    return _dio;
  }
```

 ```
post
final response = await dioService.DioService().connect.post("/users",data:{
        "_uid" : user.uid,
        "nameUser" : user.nameUser,
        "thumbail" : user.thumbail,
        "emailUser" : user.emailUser
      });
```

this interceptor respon:

> I/flutter ( 3082): Method : POST
I/flutter ( 3082): Options request url: https://"secret API"/api/v1/
D/FirebaseAuth( 3082): Notifying id token listeners about user ( huu9aBsrRmMqrO7dnuwenlbsxao2 ).
I/flutter ( 3082): Content-type  application/json; charset=utf-8
I/flutter ( 3082): options data {_uid: huu9aBsrRmMqrO7dnuwenlbsxao2, nameUser: Harloom Developer, thumbail: https://lh3.googleusercontent.com/a-/AAuE7mBZM2EAo0CKsT8BNyKBl0BF-qfjNlREctvmfyqD=s96-c, emailUser: harloom.developer@gmail.com}
I/flutter ( 3082): Method : POST
I/flutter ( 3082): Options request url: https://jarimanisbackend.herokuapp.com/api/v1/
I/flutter ( 3082): Received invalid status code: 500
I/flutter ( 3082): Dio Error DioError [DioErrorType.RESPONSE]: Http status error [500]
I/flutter ( 3082): Received invalid status code: 500

backend:
```
     console.log(req.body); //still empty
        const user= new userModel({
            _id  : new mongoose.Types.ObjectId(),
            _idFirebase : req.body._uid,
            nameUser  :req.body.nameUser,
            birthDayUser  : req.body.birthDayUser,
            emailUser  :req.body.emailUser, //@required
            thumbail : req.body.thumbail,
            numberPhone : req.body.numberPhone,
        });
```

i use http module dart is running and working
```
http.Response response = await http.post(BASEAPIUSER,body: {
     "_uid" : user.uid,
   "nameUser" : user.nameUser,
       "thumbail" : user.thumbail,
      "emailUser" : user.emailUser
 });

```

**Comment by toplinuxsir** [comment]
I have the same problem ,Dio Can not post body ?Thanks !
