### ISSUE TITLE
文件下载 FileSystemException

### ISSUE THREAD

**Issue by tinoPeng** [flutterchina/dio#609]
使用dio的downLoad ()下载文件的时候，报这个错误，存储权限也是开着的

FileSystemException: Cannot open file, path = '/storage/emulated/0/Android/data/com.jsxfedu.mathematics_android/files/hsx.apk' (OS Error: Is a directory, errno = 21)

**Comment by shakesVan** [comment]
me to 

FileSystemException: Cannot open file, path = 'https://tfs.fzfactor.com/mq-pim/201912181576656730697.pdf' (OS Error: No such file or directory, errno = 2)

**Comment by wendux** [comment]
update at v3.0.9
