### ISSUE TITLE
How to make https (ssl/tls) request with dio package in flutter?

### ISSUE THREAD

**Issue by obsessedwithperfection** [flutterchina/dio#612]
I have tried so hard to make the https(ssl/tls) request to the server with self signed certificate and with remote server letsencrypt certificate but I am not able to make it working. I tried this code as well.

```
  Dio dio = new Dio()
    ..options.baseUrl = "https://10.0.2.2:8080"
    ..httpClientAdapter = Http2Adapter(
      ConnectionManager(
          idleTimeout: 10000,
          onClientCreate: (uri, clientSetting) {
            print(uri);
            clientSetting.onBadCertificate = (cert) {
            print(cert);
            return true;
            };
          }),
    );
```

I tried to return the value false and true both in onClientCreate but still it is not working.

Code below giving me error because it can not cast dio.httpClientAdapter as DefaultHttpClientAdapter

```
String PEM="XXXXX"; // certificate content
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
    client.badCertificateCallback=(X509Certificate cert, String host, int port){
        if(cert.pem==PEM){ // Verify the certificate
            return true;
        }
        return false;
    };
};
```

```
(dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
    SecurityContext sc = new SecurityContext();
    //file is the path of certificate
    sc.setTrustedCertificates(file);
    HttpClient httpClient = new HttpClient(context: sc);
    return httpClient;
};
```

Please help Thank you

**Comment by hardypatel30** [comment]
Gives issue 

https://stackoverflow.com/questions/59487568/dio-ssl-pinning-futurehttpclient-is-not-type-of-httpclient

**Comment by obsessedwithperfection** [comment]
Hi hardypatel30, I have developed my own http client and I am using it instead of dio package.I have not worked on the problem "can not cast dio.httpClientAdapter as DefaultHttpClientAdapter" and I am still unable to set my own trusted certificates in dio but I want to give you a quick solution.Actually if your remote server has a valid ssl certificate then dio http client with automatically verify your certificate.I would suggest you to use "fullchain.pem" file instead of "cert.pem" file on your remote server (in case you are using letsencrypt ssl) otherwise dio will not be able to validate your certificate.On your localhost you can still test your flutter app with just http connection.If you still want to set your own trusted certificate like self signed certificate then use dart package dart:io httpclient.You can easily set your certificate with securitycontext class.In my opinion dio package has been designed poorly that is why I do not use it anymore.If you need a code of http client developed by me then let me know.If you need further help then let me know.Hope it helps.

**Comment by hardypatel30** [comment]
@obsessedwithperfection  Hey thanks for your response. Actually I am trying it from 'httpclient' used trusted bytes but thats also not working. Even though that code is working smoothly from native android application with same certificate. Any idea regarding it?

**Comment by obsessedwithperfection** [comment]
Could you please copy paste error in the comment section?

**Comment by obsessedwithperfection** [comment]
Use this code.
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter/services.dart';

var sccontext = SecurityContext.defaultContext;

setCert() async {
  String data = await rootBundle.loadString("assets/cert.pem");
//it can be "cert.crt" as well.
  List<int> bytes = utf8.encode(data);
  sccontext.setTrustedCertificatesBytes(bytes);
}

**Comment by hardypatel30** [comment]
Thanks I guess that was the issue. i was setting it every time and thats why it was showing me.. cert is already in hash_table

**Comment by DayBreakOb** [comment]
hello !  i have override the httpoverrides . and set it global ,but i got this exception  when i load networkimage ..══╡ 
EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _TypeError was thrown resolving an image codec:
type 'Future<dynamic>' is not a subtype of type 'HttpClient'
When the exception was thrown, this was the stack:
,is there any solve for it ?
thank you

**Comment by mario-neb** [comment]
> Use this code.
> import 'package:flutter/services.dart' show rootBundle;
> import 'package:flutter/services.dart';
> 
> var sccontext = SecurityContext.defaultContext;
> 
> String data = await rootBundle.loadString("assets/cert.pem");
> //it can be "cert.crt" as well.
> List bytes = utf8.encode(data);
> sccontext.setTrustedCertificatesBytes(bytes);
> 
> HttpClient client = new HttpClient(context: sccontext);
> 
> Remember that set the security context just once.Do not set the security context in each and every call of http request.
> 
> Hope it helps

Where are you exactly adding this piece of code?

**Comment by hapmishra** [comment]
how can we use multipart request with HttpClient

**Comment by DayBreakOb** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'
