### ISSUE TITLE
Question: Should Dio object created as singleton

### ISSUE THREAD

**Issue by lazarvgd** [flutterchina/dio#613]
Since I did not find an answer to this question in the documentation, I must ask here :) 

Question: 
I am creating class/service that will handle http requests, I will use Dio library, but I have a concern regarding the performance, do I need to declare dio object as static instance in order to save some resources? Is It necessary? 

For example:
static const Dio http = Dio();

And do I have to call close() method every time I finished with http request?

Please advice.

Thanks,
Lazar

**Comment by jonataslaw** [comment]
I'm just taking a look at this plugin, so I didn't read the documentation, but in Flutter you can instantiate anything using factory.

An example:

class CustomDio {
  static CustomDio _singletonHttp;
  Dio _http;

  factory CustomDio() {
    if (_singletonHttp == null) _singletonHttp = CustomDio._();
    return _singletonHttp;
  }
  CustomDio._() {
     _http = Dio();
  }
  get client => _http;
  dispose() {
    _httpClient.close();
  }
}
I built this class out of the data from your question, I don't know if it's objectively what you want, but it's learning anyway.
CustomDio().client will always call the same instance in this example, and will take advantage of the keep alive of your server. 

Even using http and thinking of using Dio for the first time today, to my knowledge you should close the http connection when no more requests are made, or when a downtime limit is reached.

**Comment by jonataslaw** [comment]
> Since I did not find an answer to this question in the documentation, I must ask here :)
> 
> Question:
> I am creating class/service that will handle http requests, I will use Dio library, but I have a concern regarding the performance, do I need to declare dio object as static instance in order to save some resources? Is It necessary?
> 
> For example:
> static const Dio http = Dio();
> 
> And do I have to call close() method every time I finished with http request?
> 
> Please advice.
> 
> Thanks,
> Lazar

I'm just taking a look at this plugin, so I didn't read the documentation, but in Flutter you can instantiate anything using factory.

An example:

class CustomDio {
static CustomDio _singletonHttp;
Dio _http;

factory CustomDio() {
if (_singletonHttp == null) singletonHttp = CustomDio.();
return singletonHttp;
}
CustomDio.() {
_http = Dio();
}
get client => _http;
dispose() {
_httpClient.close();
}
}
I built this class out of the data from your question, I don't know if it's objectively what you want, but it's learning anyway.
CustomDio().client will always call the same instance in this example, and will take advantage of the keep alive of your server.

Even using http and thinking of using Dio for the first time today, to my knowledge you should close the http connection when no more requests are made, or when a downtime limit is reached.

**Comment by Allan-Nava** [comment]
> Since I did not find an answer to this question in the documentation, I must ask here :)
> 
> Question:
> I am creating class/service that will handle http requests, I will use Dio library, but I have a concern regarding the performance, do I need to declare dio object as static instance in order to save some resources? Is It necessary?
> 
> For example:
> static const Dio http = Dio();
> 
> And do I have to call close() method every time I finished with http request?
> 
> Please advice.
> 
> Thanks,
> Lazar

Any news if is correct to create a singleton?

**Comment by tijanirf** [comment]
@Allan-Nava Yes, it is correct in my opinion. Already used singleton for my production apps and it's working fine.

**Comment by cesc1802** [comment]
> @Allan-Nava Yes, it is correct in my opinion. Already used singleton for my production apps and it's working fine.

can you share your code to create dio with singleton partten?

**Comment by RoBiN-HoOd-1** [comment]
> > @Allan-Nava Yes, it is correct in my opinion. Already used singleton for my production apps and it's working fine.
> 
> can you share your code to create dio with singleton partten?

you can just create is using get_it dependency injection package and use it in every file.. i am doing the same here's the code: getIt.I
                    ..registerSingleton<Dio>(Dio());

**Comment by naumanahmed19** [comment]
I have created this dio service please check here.

https://gist.github.com/naumanahmed19/9b5a42bb0eeeb7d0f6a76ac023a20eae``
