### ISSUE TITLE
request has been blocked by CORS policy

### ISSUE THREAD

**Issue by fvisticot** [flutterchina/dio#614]
looking on the previous issue, I don't understand if it is an issue or a configuration pb.
Can you please clarify ?

Beta channel with Flutter Web 
Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale fr-FR)

Error: 
> from origin 'http://localhost:65327' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by alevittoria** [comment]
I have the same problem and furthermore with Flutter web the header isn't considered.
I tried:
``` dart
options: Options(
          headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
          },
          contentType: "application/json",
        ),
```
and
``` dart
options: Options(
          headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
          },
        ),
```
and
``` dart
options: Options(contentType: Headers.jsonContentType, headers: {
          Headers.acceptHeader: Headers.jsonContentType,
          Headers.contentTypeHeader: Headers.jsonContentType
        }
```
but always my request results without this options.

**Comment by softmarshmallow** [comment]
need support for web

**Comment by uniquejava** [comment]
support web or not ? if not we have to rollback to http.

**Comment by softmarshmallow** [comment]
reopen this issue

**Comment by ashutosh1211** [comment]
Its not an issue with library, You web server should have access-control-policy set for particular method.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1

**Comment by softmarshmallow** [comment]
might be related to https://github.com/flutter/flutter/issues/41977

**Comment by brunodmn** [comment]
this worked for me:
[https://stackoverflow.com/a/66879350/9914638](https://stackoverflow.com/a/66879350/9914638)

**Comment by LeonidVeremchuk** [comment]
> this worked for me: https://stackoverflow.com/a/66879350/9914638

This solution worked on local build but not in release after deployed to hosting...
