### ISSUE TITLE
拦截器里添加token的问题

### ISSUE THREAD

**Issue by JianRuHong** [flutterchina/dio#616]
我是dart2.5版本下，在拦截器里添加如下代码：
```
dio.interceptors
        .add(InterceptorsWrapper(onRequest: (RequestOptions options) async {
          
          if(userLocalModel.token != null && userLocalModel.tokenType != null) {
            //添加token
            dio.options.headers["Authorization"] = "${userLocalModel.tokenType} ${userLocalModel.token}";
          }

      print("请求发出之前，可以进行拦截处理:${dio.options.headers}");
      return options;
    }, onResponse: (Response response) async {
      print("返回数据之前，可以对响应数据进行处理，比如用户是否已经登录");
      return response;
    }, onError: (DioError error) async {
      print("请求发生错误之前，可以进行一些处理");
      return error;
    }));
  }
```

第一次请求，携带不上请求头，我确定有值，但是发送get请求时，第一次请求接口，是携带不上拦截器里设置的token的；

不影响我正常使用，我只能把拦截器去掉了，在每个请求上添加上options字段，这样是正常的

**Comment by JianRuHong** [comment]
我这边让后台配合查找，我断点去测，确实是接口第一次token携带不上，后续都是正常的，我在如下设置，是正常的：
```
response = await dio.get(url, queryParameters: data, options: Options(headers: {"Authorization": "${userLocalModel.tokenType ?? ""} ${userLocalModel.token ?? ""}"}));
```
这样处理，每次header都能设置上。

**Comment by huobazi** [comment]
看不出来哪里毛病啊, 我基本上也这样用的,就是没携 async 而已,其他都一样啊

```dart
_client.interceptors.add(
        InterceptorsWrapper(onRequest: (RequestOptions options) {
          if (ApplicationContext.current.credentials != null &&
              ApplicationContext.current.credentials.access_token != null) {
            options.headers.addAll({
              "Authorization": "Bearer " +
                  ApplicationContext.current.credentials.access_token
            });
          }
          return options;
        }, onResponse: (Response response) {
          return response; /
        }, onError: (DioError error) {
          if (error != null && error.response != null) {
            locator<EventBus>().fire(DioErrorEvent(error: error));
          }
          return error; 
        }),
      );
```

**Comment by JianRuHong** [comment]
我看出来点不同了，我是把请求头设置`dio.options`上了，你这边是直接设置在单个请求的options上了，应该是拦截器走完，单个请求的options把dio.options给顶替掉了，但是我不理解为啥就第一次请求携带不上，往后都正常了。

**Comment by wendux** [comment]
@JianRuHong 走到拦截器时全局配置（dio.options）已经合并过了，所以需要将token也在本次请求的配置中设置一下：
```dart
 //添加token
 dio.options.headers["Authorization"] =options.headers["Authorization"]  "${userLocalModel.tokenType} ${userLocalModel.token}";
```

**Comment by catmaomao** [comment]
you can do it like this:
dio.interceptors
        .add(InterceptorsWrapper(onRequest: (RequestOptions options) async {
          **dio.lock;**
          if(userLocalModel.token != null && userLocalModel.tokenType != null) {
            //添加token
            dio.options.headers["Authorization"] = "${userLocalModel.tokenType} ${userLocalModel.token}";
          }
         **dio.unlock;**
      print("请求发出之前，可以进行拦截处理:${dio.options.headers}");
      return options;
    }, onResponse: (Response response) async {
      print("返回数据之前，可以对响应数据进行处理，比如用户是否已经登录");
      return response;
    }, onError: (DioError error) async {
      print("请求发生错误之前，可以进行一些处理");
      return error;
    }));
  }
