### ISSUE TITLE
Dio cookie manage can't get cookie when a request send by Image.network?

### ISSUE THREAD

**Issue by tokenl** [flutterchina/dio#618]
### Dio support to get cookie from Image.network request?

how to get cookie from Image.network request, seem like dio only can get cookie if a request send by dio?

how to mange app cookie, whatever request is send by dio or else?

some people can help me to solve this ? thx

**Comment by liujiakuoyx** [comment]
you can add headers:
headers[HttpHeaders.cookieHeader] = cookies

**Comment by tokenl** [comment]
thanks for your reply,

but how to get cookie from Image.network request, like this:

```
/* this is a captcha url,
** this request will response a set-cookie header, like set-cookie: session=xxxxxxxx
** but i can't get session cookie by this way
** i know i can set headers by Image.network, by this is second step
** the first step is how to get cookies
Image.network(https://xxx.com/captcha);

```
