### ISSUE TITLE
我该怎么做才能在响应拦截器里直接return data

### ISSUE THREAD

**Issue by chavesgu** [flutterchina/dio#621]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | 1.12                             |      |
| Dio Version                    | 2.1.0                                  |      |
| Android Studio / Xcode Version | Android Studio 3.3.2 / Xcode 10.2.1              |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        |             |      |
| Demo project link              |  |      |

### Issue Description and Steps

```dart
final Dio api = Dio();
api.interceptors.add(InterceptorsWrapper(
      onResponse:(Response response) {
        return response.data;
      },
));
```

**Comment by wendux** [comment]
这样是可以的啊

**Comment by chavesgu** [comment]
> 这样是可以的啊

可是我这样写了之后  还是需要返回了response

**Comment by wendux** [comment]
哦哦，理解错了，最终返回的类型必须是Response，你可以修改response.data的值和类型
