### ISSUE TITLE
Negative fileSize in onReceiveProgress

### ISSUE THREAD

**Issue by wizlif** [flutterchina/dio#637]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / android                          |      |
| Platform Version               | v1.12.13+hotfix.5 / 9.0                              |      |
| Dio Version                    | 2.1.0                                 |      |
| Android Studio / Xcode Version | Android Studio 3.5.3              |      |
| Repro rate                     | all the time (100%)    |      |
| Repro with our demo prj        | No            |      |

### Issue Description and Steps
Dio returns a -1 fileSize in onReceiveProgress,  [sample file](https://sandbox.registry.co.ug/payment_transactions/127.pdf)
```dart
Future downloadFile(
    String url, {
    Function(int progress, int fileSize) onProgress,
    Function(String path) onComplete,
    Function(String e) onError,
  }) async {
    try {
      await ready;

      String localPath = join(documentsDirectory.path, basename(url));

      File file = File(localPath);

      if (file.existsSync()) {
        onComplete(localPath);
      } else {
        _dio.download(url, localPath,
            onReceiveProgress: (int progress, int fileSize) {
          onProgress(progress, fileSize);
          if (progress == fileSize) {
            onComplete(localPath);
          }
        });
      }
    } catch (e) {
      onError(e.toString());
    }
}
```

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by bilaloz** [comment]
some problems ?

**Comment by gtu-myowin** [comment]
It is documented in the doc [https://pub.dev/documentation/dio/latest/dio/ProgressCallback.html](documentation). 

Saying that

> When receiving data: total will be -1 if the size of the response body is not known in advance, for example: response data is compressed with gzip or no content-length header.
