### ISSUE TITLE
关于request方法中，get、post参数名不统一的问题

### ISSUE THREAD

**Issue by DongyunLee** [flutterchina/dio#640]
### 关于request方法中，get、post参数名不统一的问题

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps
首先感谢中文社区对dio的贡献！

在项目中对dio进行了封装，所有的请求最终都走到了request方法中，但发现在get请求下，使用data传参无效。PHP的后端$_GET无法接受flutter通过get传递的data数据。

困扰了几天之后，发现需要用queryParameters参数传递。

因为文档中没有对request()方法的queryParameters参数的特殊说明，所以想请教下：

将queryParameters参数和data参数在不同请求下分离，是有什么额外考虑吗？
如果没有的话，为什么不直接使用data来统一处理呢？

希望能有大佬帮忙解惑！感谢！

**Comment by crsgit** [comment]
queryParameters 是拼接在url上的
data 在请求body里面
即使在加密通信中url也是可见的

不在get里面用data可能是form表单的习惯
html表单用get会把内容以queryParameters的形式拼接发送

另外不是不能发只是作者在源代码中有限制会抛弃

**Comment by DongyunLee** [comment]
> queryParameters 是拼接在url上的
> data 在请求body里面
> 即使在加密通信中url也是可见的
> 
> 不在get里面用data可能是form表单的习惯
> html表单用get会把内容以queryParameters的形式拼接发送
> 
> 另外不是不能发只是作者在源代码中有限制会抛弃

您说的会抛弃是指之后版本计划统一这两个的调用方式吗？

**Comment by crsgit** [comment]
> > queryParameters 是拼接在url上的
> > data 在请求body里面
> > 即使在加密通信中url也是可见的
> > 不在get里面用data可能是form表单的习惯
> > html表单用get会把内容以queryParameters的形式拼接发送
> > 另外不是不能发只是作者在源代码中有限制会抛弃
> 
> 您说的会抛弃是指之后版本计划统一这两个的调用方式吗？

可能有误解，会抛弃意思是你用了GET方法dio会忽略data中的数据不发送。
这俩个控制着http协议不同位置的数据
[参考代码位置](https://github.com/flutterchina/dio/blob/5e3eb797a4202b9aca0acc74d325c10523b79584/dio/lib/src/dio.dart#L988)

**Comment by DongyunLee** [comment]
> > > queryParameters 是拼接在url上的
> > > data 在请求body里面
> > > 即使在加密通信中url也是可见的
> > > 不在get里面用data可能是form表单的习惯
> > > html表单用get会把内容以queryParameters的形式拼接发送
> > > 另外不是不能发只是作者在源代码中有限制会抛弃
> > 
> > 
> > 您说的会抛弃是指之后版本计划统一这两个的调用方式吗？
> 
> 可能有误解，会抛弃意思是你用了GET方法dio会忽略data中的数据不发送。
> 这俩个控制着http协议不同位置的数据
> [参考代码位置](https://github.com/flutterchina/dio/blob/5e3eb797a4202b9aca0acc74d325c10523b79584/dio/lib/src/dio.dart#L988)

理解了，感谢！
但是也建议在文档上突出说明一下这个问题~
