### ISSUE TITLE
Dio is forcing headers to lowercase

### ISSUE THREAD

**Issue by shaxxx** [flutterchina/dio#641]
**Dio version:** `dio: ^3.0.8`

When I set Dio header like this

`dio.options.headers['Authorization'] = 'dGVzdDp0ZXN0';`

I expect request header to look like this

`Authorization: Basic dGVzdDp0ZXN0`

Not like this (notice that capital "A" was transformed to "a")

`authorization: Basic dGVzdDp0ZXN0`

Reason for this is [HERE](https://github.com/flutterchina/dio/blob/5e3eb797a4202b9aca0acc74d325c10523b79584/dio/lib/src/options.dart#L354). All headers are transformed to lower case.
I can only guess what your motivation for this was, but this is wrong.

Please read about it [HERE](https://github.com/dart-lang/sdk/issues/25120) and [HERE](https://github.com/dart-lang/sdk/issues/33501)

Even Dart team is currently reverting this 
https://dart-review.googlesource.com/c/sdk/+/119100

Dio 2.1.5 did not have this behavior. I was able to use [AltHttpClient](https://pub.dev/packages/alt_http) with Dio and headers where left AS IS.

**Comment by shaxxx** [comment]
After some inspection I can confirm that version Dio 3.0.7 works as expected, it doesn't change headers casing. Problem is [commit ](https://github.com/flutterchina/dio/commit/f77d6db80bfdbd3a32877aedd2273e2116666340#diff-d8b422c1405a3050f793a93dbd587b4d) by @wendux 12 days ago.
I'm even more sure now that this is bug since entire commit was marked as "[code style improvement](dio/lib/src/options.dart)". Please revert changes.

**Comment by shaxxx** [comment]
Yes, this issues is very much still open

**Comment by yangyangyyluck** [comment]
same problem. 
Dio version 3.0.8
the bug came to assail me.
I need headers like CamelCase.
user-agent => User-Agent 
referer => Referer
content-type => Content-Type
and so on...
as @shaxxx  say, please revert changes.

**Comment by shaxxx** [comment]
FYI: Dart team has enabled support for case sensitive headers in the new upcoming version.
New Dart (and Flutter) release will support case sensitive headers, so should Dio.

**Comment by masseelch** [comment]
But the RFC clearly states, that headers are case-insensitive. 
This means it should not matter if dio sends "content-type" or "Content-Type" or "cOntEnt-TyPE". 
The server has the bug here. Not this package.

**Comment by shaxxx** [comment]
@masseelch I'm aware what RFC states, and I'm aware how servers should work.
I'm also aware there are millions of server in the wild that are not acting according to RFC.
Forcing all headers to lowercase does not make Dio act more or less according to RFC. 
RFC doesn't care about the headers casing, neither should Dio. Let developers worry about it.
Only possible reasons why Dio forces this:
- because it's easier to maintain one codebase for HTTP and HTTP/2 (which expects lowercase)
- because that's the way Dart team has implemented this (and reverted this in the next Dart version)
Dart authors are aware of this and decided to revert this same behavior Dio is trying to force.

Are you aware of millions of people using apps that talk with devices running some kind of web server (like TV, Cable, Satellite receivers)? Do you think it realistic for users of my app to contact their cable provider, or maybe manufacturer of hardware to change their behavior?

Authors of Google Chrome are aware of this, yet they're sending 'Authorization' header, not 'authorization'. Why do you think this is the case?

And like I said in my previous post, I don't believe that someone has given any thought about this. Whole commit was marked as "code style improvement". If something breaks previous behavior it's but not "code style improvement".

**Comment by masseelch** [comment]
> RFC doesn't care about the headers casing, neither should Dio. Let developers worry about it.
This indeed is a valid point. 

>  If something breaks previous behavior it's all but not "code style improvement".
Yes. This should be at least a new minor version.

If i think about it, it does not hurt to leave the header key untouched.

**Comment by jibiel** [comment]
Also I believe it is causing the following case:

```
flutter: headers:
flutter:  content-type: application/json; charset=utf-8
flutter:  x-auth-token: null
flutter:  X-Auth-Token: QcD7S_nbLJ7prcyU95pN
```
[via `LogInterceptor`]

I don't mind double assignments of headers that overwrite one another in my codebase (which would be the case if the lowercasing was not the case), but I do mind having to go over it to find out the reason behind these header values.

Both headers were assigned as `options.headers['X-Auth-Token'] = ...`, but the downcased one was passed to `Dio(options)` and the latter one was assigned during `onRequest` in an `Interceptor`.

**Comment by wstrange** [comment]
Just got bit by this as well.

**Comment by MaYunFei** [comment]
same problem.

**Comment by shaxxx** [comment]
Still an issue.

**Comment by pengshaomin** [comment]
same problem.

**Comment by conghaonet** [comment]
same problem.

**Comment by matejthetree** [comment]
same problem

**Comment by matejthetree** [comment]
what version works good?

**Comment by rdsuncn** [comment]
same problem.

**Comment by vickyleu** [comment]
io_adapter.dart====>>>

      options.headers.forEach((k, v) {
       ##### if header value is null, build BytesBuilder will crash,set preserveHeaderCase true to keep case
        request.headers.set(k, v??"null",preserveHeaderCase: true);
      });

**Comment by SteveOye** [comment]
Same problem. Has anyone gotten a solution yet?

**Comment by hnxyzhw** [comment]
same problem.

**Comment by szlxz** [comment]
Same problem. Has anyone gotten a solution yet?

**Comment by zhangxiongbiao** [comment]
> io_adapter.dart====>>>
> 
> ```
>   options.headers.forEach((k, v) {
>    ##### if header value is null, build BytesBuilder will crash,set preserveHeaderCase true to keep case
>     request.headers.set(k, v??"null",preserveHeaderCase: true);
>   });
> ```

should change io_adapter.dart like this.

**Comment by johnnycook** [comment]
same problem :/

**Comment by fernando-s97** [comment]
@vickyleu  how can I apply your fix?

**Comment by dev-abdiel** [comment]
If someone still having this issue, I recommend you to use the HttpClient class from dart:io.

I fixed it with the following code block:
```dart
HttpClient client = new HttpClient();
await client
  .getUrl(Uri.parse("YOUR URL"))
  .then((HttpClientRequest request) {
     request.headers.set(
       "Authorization",
       "Bearer TOKEN",
        preserveHeaderCase: true,
     );
     // Optionally write to the request object...
     // Then call close.
     return request.close();
   }).then((HttpClientResponse response) {
      final completer = Completer<String>();
      final contents = StringBuffer();
      response.transform(utf8.decoder).listen((data) {
      contents.write(data);
      print(data);
      }, onDone: () => completer.complete(contents.toString()));
});
```

**THIS CODE BLOCK WILL NOT WORK IN FLUTTER WEB**, use http or Dio packages instead.

I suggest you check out the official documentation:
[HttpClient class](https://api.dart.dev/stable/2.14.2/dart-io/HttpClient-class.html)
[HttpHeader class](https://api.dart.dev/stable/2.14.2/dart-io/HttpHeaders-class.html)

**Comment by johnnycook** [comment]
Yes, this was also my workaround, but I don't think it's that nice. I'd prefer if dio would implement some property that would propagate to underlying client to set this.

**Comment by MikeAndrson** [comment]
Just got bit by this as well... tracking it down took a good 4 hours :/

> io_adapter.dart====>>>
> 
> ```
>   options.headers.forEach((k, v) {
>    ##### if header value is null, build BytesBuilder will crash,set preserveHeaderCase true to keep case
>     request.headers.set(k, v??"null",preserveHeaderCase: true);
>   });
> ```

My workaround was, instead of editing an already existing file of dio, I found it safer to copy the adapter from io_adapter.dart to another file in my own project and do the changes there. Then I used httpClientAdapter property of my Dio client to use it.

I shared the gist [here](https://gist.github.com/MikeAndrson/817cee930546af9b890e812e54130d19) in case anyone is interested.

With that being said, I do think dio should implement a way (like a flag) for us to be able to disable case-insensitive header names, as workarounds like this are dirty.

**Comment by Toavina23** [comment]
still no updates of dio to support this ?
that bug is really frustrating me right now

**Comment by manjarqo** [comment]
same problem

**Comment by T-moz** [comment]
Should be opened

**Comment by NRMrYang** [comment]
Should be opened. 
Same problem

**Comment by NRMrYang** [comment]
> Reference in new

it works.Thx!

**Comment by AlexV525** [comment]
Hey guys. I saw there is a commit that removes `.toLowerCase()`, is that mean the commit is valid or does not cover all cases? If so, can you guys provide a minimum example that fails?

Also, can anyone provide any commit link that the Dart team reverted in the previous Dart SDK? That helps to apply new fixes too.

cc @shaxxx @vickyleu

**Comment by dr-samrat** [comment]
I hope this gets fixed soon. Still facing the issue. Since we are newly making the api contract, we are migrating to case-insensitive headers.

**Comment by onayem** [comment]
This issue still alive. I am facing the same issue. Please solve this out, even adding a flag could help the ones facing this issue.

**Comment by brunogc** [comment]
The issue is 'closed' but I keep experiencing this issue in version 5.3.2.

**Comment by mayankHype** [comment]
Same the issue is 'closed' but I keep experiencing this issue in version 5.3.2.

**Comment by AlexV525** [comment]
We no longer handle issues before 12th Mar 2023. Please submit new issues with new requirements.
