### ISSUE TITLE
save path

### ISSUE THREAD

**Issue by HassanDev13** [flutterchina/dio#643]
How i chose the right path 
 await download1(dio, url, "/Download/book.jpg");
i change it many times but he give me this problem :
 FileSystemException: Cannot open file, path = '/Download/book.jpg' (OS Error: No such file or directory, errno = 2)

**Comment by shinayser** [comment]
I am having this exact same problem here. Running the dart code on windows always give me those erros. 
It seems that DIO is not creating the directories before tryign to save it.

**Comment by shinayser** [comment]
I think this issue can now be closed

**Comment by wendux** [comment]
update at v3.0.9
