### ISSUE TITLE
Timeout doesn't work on mobile data without internet connection

### ISSUE THREAD

**Issue by ManoyloK** [flutterchina/dio#654]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / ios / android                          |      |
| Dio Version                    | 3.0.7                              |      |

### Issue Description and Steps

When working on mobile data and there is no internet connection for some reason, request timeout isn't work it takes about 30 seconds despite  connectTimeout  and receiveTimeout values

**Comment by nashfive** [comment]
Just ran into the same issue. With the Developer mode ON and Network Link Conditioner set to 100% packet loss on my iPhone, requests always have a 30s timeout, no matter the value I specify in the connectTimeout and/or receiveTimeout values...

**Comment by iNima** [comment]
Exactly the same happens to me as well.
Please open this issue.

**Comment by pfistnerm** [comment]
same here
