### ISSUE TITLE
files are not downloading by using dio.download on real IOS devices.

### ISSUE THREAD

**Issue by ranjit41771** [flutterchina/dio#656]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios                           |      |
| Dio Version                    e.g.  3..0.8 

### Issue Description and Steps
The issue is that when we download the files form server those files are not getting to save to the local storage in real iOs device, I am using the iPhone 11 with the latest os version. All working fine with android and ios Simulator. problem is with the real ios devices.

**Comment by asarkar1990** [comment]
Any update?

**Comment by DeepashreeB** [comment]
facing same issue. Any Updates?

**Comment by asarkar1990** [comment]
I think as it was not working I had used something else.

**Comment by ToanBarcelona1998** [comment]
Same issue.

**Comment by kuhnroyal** [comment]
Please create a new issue with a reproducible example.
