### ISSUE TITLE
请问如何获取download的header?

### ISSUE THREAD

**Issue by YaoShuwei** [flutterchina/dio#66]
` var dir=(await getApplicationDocumentsDirectory()).path;
  Dio dio=new Dio();
  Response response;
  response = await dio.download(url, dir+"/img.png",);
  print(response.header);
`
现在header是null

**Comment by YaoShuwei** [comment]
header可以从response.data.header取到

**Comment by wendux** [comment]
@YaoShuwei 这样确实可以，但应该通过response.headers取出，这样会统一，我待会会修复一下。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by YaoShuwei** [comment]
甚好，辛苦了
