### ISSUE TITLE
dio 3.0.7 和  http_server 0.9.8+3 的FormData兼容性问题

### ISSUE THREAD

**Issue by llinzzi** [flutterchina/dio#664]
在这样使用FormData进行文件上传的时候
`      
  FormData formData = FormData.fromMap({
          "title":"中文",
          "file":  await MultipartFile.fromFile(_path,contentType:MediaType('video','mp4'))
        });
`
http_server 会返回
`HttpException: Unsupported contentTransferEncoding: binary`

经过排查，注释掉dio里form_data.dart的_headerForField后可解决。
```
    // if (!isPlainAscii(value)) {
    //   header = '$header\r\n'
    //       'content-type: text/plain; charset=utf-8\r\n'
    //       'content-transfer-encoding: binary';
    // }
```
对比浏览器抓包实现，发现并没有增加binary的这个header， 看看作者建议如何解决更好。

**Comment by zcb1603999** [comment]
同样遇到了这个问题。。。

**Comment by 1232209** [comment]
我也碰到了，我现在是如果参数是中文的话，用wireShark抓包抓不到http包，看起来连包都没有发出去。
而且很容易崩溃

**Comment by 1232209** [comment]
> 在这样使用FormData进行文件上传的时候
> ` FormData formData = FormData.fromMap({ "title":"中文", "file": await MultipartFile.fromFile(_path,contentType:MediaType('video','mp4')) });`
> http_server 会返回
> `HttpException: Unsupported contentTransferEncoding: binary`
> 
> 经过排查，注释掉dio里form_data.dart的_headerForField后可解决。
> 
> ```
>     // if (!isPlainAscii(value)) {
>     //   header = '$header\r\n'
>     //       'content-type: text/plain; charset=utf-8\r\n'
>     //       'content-transfer-encoding: binary';
>     // }
> ```
> 
> 对比浏览器抓包实现，发现并没有增加binary的这个header， 看看作者建议如何解决更好。

我注释之后也解决了，you saved me!

**Comment by Shrike-zjm** [comment]
我也遇到了类似的问题 FormData中 fields某一项的值如果是中文字符串 那在后台就会被解析成文件... 用楼主()的这个方法成功解决了 太感谢了！
