### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: FormatException

### ISSUE THREAD

**Issue by mohamed6996** [flutterchina/dio#67]
I get this error when i want to download an image
DioError [DioErrorType.DEFAULT]: FormatException: Invalid character in cookie value, code unit: '34'

the image link is: 
https://pixabay.com/get/ea33b70b2bf5093ed1584d05fb1d4591e67eebd119ac104496f6c671a0eeb1ba_640.jpg

the code to download the image is:
`  await dio.download(model.webformatURL, 'path',onProgress: _updateProgress);
`

**Comment by wendux** [comment]
#8
