### ISSUE TITLE
Creating swagger-codegen for Flutter with the Flutter dio HTTP package

### ISSUE THREAD

**Issue by fzyzcjy** [flutterchina/dio#671]
Hi, thanks for the library! Currently the [swagger-codegen](https://github.com/swagger-api/swagger-codegen), a popular tool to generate API clients from specs, only generates dart code without the `dio` library (also without things like `json_serialize`). Thus, I am going to implement it. Is it OK? (Or is there already one hidden in the corner...?)

**Comment by dvaldivia** [comment]
did you implement t @fzyzcjy ? it would be really useful

**Comment by fzyzcjy** [comment]
No :/ Indeed I created my own codegen

**Comment by iamshabell** [comment]
@fzyzcjy  can you share any link the one you created?

**Comment by fzyzcjy** [comment]
Sorry it is not open sourced yet
