### ISSUE TITLE
PUT not working with Http2Adapter

### ISSUE THREAD

**Issue by cirediew** [flutterchina/dio#673]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
It looks like PUT is not working with the `Http2Adapter`.
I will get the following error:
```
HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1)
```
I know of issue #486 in which I referenced [dart-lang/http2/issues/49](https://github.com/dart-lang/http2/issues/49) but as you can see I don't use headers in my example or my real code.

My code:
``` dart
    var d = Dio()
      ..httpClientAdapter = Http2Adapter(ConnectionManager(idleTimeout: 8000));
    d.putUri(
      Uri.parse("https://jsonplaceholder.typicode.com/posts/1"),
      data: json.encode({"id": 1, "title": 'foo', "body": 'bar', "userId": 1}),
    ).then((response) async {
      LOG.info(response);
}
```
This example is just a fake API which should also return data, but I get the same error using my own.
When I use `DefaultHttpClientAdapter` there is no problem.

**Comment by cirediew** [comment]
Still an issue

**Comment by cirediew** [comment]
Still An Issue 🙃

**Comment by hongyiweiwu** [comment]
#760

**Comment by ylogx** [comment]
I also face similar error with POST calls when using dio_http2_adapter

**Comment by kitmoovup** [comment]
POST method has this issue as well.
