### ISSUE TITLE
Dio response.data.toString() returns malformed json data

### ISSUE THREAD

**Issue by giaur500** [flutterchina/dio#675]
Webservice call:

```
final response = await dio.get(url);
String body = response.data.toString();
```

Expected result - raw json returned from server. Actual data: malformed json with string field values not wrapped in double quotes.

How to get raw body data, not touched by Dio?

**Comment by kastil79** [comment]
In your case you should put: 
Response**<String>** response = await dio.get(url);
String body = response.data.toString();

the body variable returns a json with string field values in wrapped in double quotes

**Comment by kastil79** [comment]
In your case you should put:
`Response<String> response = await dio.get(url);
String body = response.data.toString();`

the body variable returns a json with string field values in wrapped in double quotes

**Comment by giaur500** [comment]
Let me understand that, is there some auto mapping performed? Why `Response<String>`?

**Comment by beerline** [comment]
@giaur500 hi!
You can also use 

```dart
final response = await dio.get(
    url, 
    options: Options(
        responseType: ResponseType.plain,
    ),
);
String body = response.data;
```

in this case `response.data` will String without additional `toString()`.
it may be looks little bit massive, but on other hand more clearly.
