### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by darkducke** [flutterchina/dio#676]
How do I configure the encoding of the received content? I get accented words like in the example below:

```
    Dio dio = new Dio();
    var cookieJar = CookieJar();
    dio.interceptors.add(CookieManager(cookieJar));
    dio.options.followRedirects = true;
    dio.options.contentType = Headers.formUrlEncodedContentType;
    dio.options.responseType = ResponseType.plain;


    Response response = await dio.post("www.url.com/pagina.asp",
          data: {
            "param1" : "1" ,
            "param2" : "aaaaa",
            "param3" : "bbbbb",
            "param4" : "1"
      });

    print(response.data.toString());

```

`Usu�rios e Op��o por Servi�os`

the correct would be

`Usuários e Opções por Serviços`

Thanks!

**Comment by Helzio** [comment]
> How do I configure the encoding of the received content? I get accented words like in the example below:
> 
> ```
>     Dio dio = new Dio();
>     var cookieJar = CookieJar();
>     dio.interceptors.add(CookieManager(cookieJar));
>     dio.options.followRedirects = true;
>     dio.options.contentType = Headers.formUrlEncodedContentType;
>     dio.options.responseType = ResponseType.plain;
> 
> 
>     Response response = await dio.post("www.url.com/pagina.asp",
>           data: {
>             "param1" : "1" ,
>             "param2" : "aaaaa",
>             "param3" : "bbbbb",
>             "param4" : "1"
>       });
> 
>     print(response.data.toString());
> ```
> 
> `Usu�rios e Op��o por Servi�os`
> 
> the correct would be
> 
> `Usuários e Opções por Serviços`
> 
> Thanks!

Can you solve this?

**Comment by Abel1027** [comment]
I set up a latin1 decoder and it worked:

`Response response = await dio.post("www.url.com/pagina.asp",
     data: {
            "param1" : "1" ,
            "param2" : "aaaaa",
            "param3" : "bbbbb",
            "param4" : "1"
      },
       options: Options(
          responseDecoder: (responseBytes, _, __) {
            return latin1.decode(responseBytes);
          },
        ),
);`
