### ISSUE TITLE
HTTP error 415 with FormData

### ISSUE THREAD

**Issue by don-prog** [flutterchina/dio#679]
Hello, I'm trying to use [retrofit.dart](https://github.com/trevorwang/retrofit.dart) for API requests to my Spring server, which has the following endpoint:
```
@Transactional
@PostMapping("/test")
public void test(@Valid @RequestPart(value = "MyModel") MyModel myModel)
```
Before retrofit.dart I successfully used Retrofit in Java, here is the code:
```
@Multipart
@POST("/test")
Call<Void> test(@Part("MyModel") MyModel myModel);
```
This code generated next request:

> POST /test HTTP/1.1
> Content-Type: multipart/form-data; boundary=62b81b81-05b1-4287-971b-c32ffa990559
> Content-Length: 275
> Host: 192.168.0.107:8443
> Connection: Keep-Alive
> Accept-Encoding: gzip
> User-Agent: okhttp/3.8.0
> 
> --62b81b81-05b1-4287-971b-c32ffa990559
> Content-Disposition: form-data; name="MyModel"
> Content-Transfer-Encoding: binary
> Content-Type: application/json; charset=UTF-8
> Content-Length: 35
> 
> {"testString":"hello from Java"}
> --62b81b81-05b1-4287-971b-c32ffa990559--

Now I use retrofit.dart:

```
@MultiPart()
@POST("/test")
Future<void> test(@Part("MyModel") MyModel myModel);
```
It generates next `Dio` code:
```
  @override
  test(myModel) async {
    ArgumentError.checkNotNull(myModel, 'myModel');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = FormData.fromMap(<String, dynamic>{
      'MyModel': jsonEncode(myModel ?? <String, dynamic>{}).toString()
    });
    await _dio.request<void>('/test',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    return Future.value(null);
  }
```
Which generates next request:

> POST /test HTTP/1.1
> user-agent: Dart/2.8 (dart:io)
> content-type: multipart/form-data; boundary=--dio-boundary-3791459749
> accept-encoding: gzip
> content-length: 151
> host: 192.168.0.107:8443
> 
> ----dio-boundary-3791459749
> content-disposition: form-data; name="MyModel"
> 
> {"testString":"hello from flutter"}
> ----dio-boundary-3791459749--

But unfortunately this `Dio` request doesn't work, and I get this error:

> "status" -> 415,
> "error" -> "Unsupported Media Type",
> "message" -> "Content type 'application/octet-stream' not supported"

So, what is the problem and how can I solve it?

**Comment by trevorwang** [comment]
It seems that `formdata` needs a parameter to support content-type for each part.

**Comment by don-prog** [comment]
@trevorwang yes, and how can I set it?

**Comment by trevorwang** [comment]
https://github.com/dart-lang/http/issues/283

**Comment by Artur512** [comment]
Its still the same problem. Somebody found solution for that?

**Comment by Prashanth-dlpr** [comment]
RRRRR

**Comment by MostafaSolimanMO** [comment]
Still!
