### ISSUE TITLE
Option to set `Content-Length` header

### ISSUE THREAD

**Issue by craigloftus** [flutterchina/dio#68]
The default behaviour for simple JSON post requests does not set a `Content-Length` header, resulting in a chunked transfer encoding being used, which is causing us issues in development when we're using a Django development server that doesn't support chunked encoding.

We can work around it using an interceptor, but because `onSend` is triggered before `_transformData` we have to do quite a bit more than just set the content length header.

```
dio.interceptor.request.onSend = (Options options) async {
    if (options.data is! String && options.contentType.mimeType == ContentType.json.mimeType) {
        options.data = jsonEncode(options.data);
        options.headers['Content-Length'] = options.data.length.toString();
    }
    return options;
};
```

Would you consider a PR to add such an option?

**Comment by craigloftus** [comment]
Ah, I assumed it was deliberate behaviour, rather than a bug. Thanks, that has fixed the issue for us.

**Comment by wendux** [comment]
🙂，I know it is a feature  request, but Set Content-Length explicitly by default is a better choice.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
