### ISSUE TITLE
Importing 'package:dio/adapter_browser.dart' fails compilation on non-Web platforms

### ISSUE THREAD

**Issue by technolion** [flutterchina/dio#683]
### New Issue Checklist

- [ x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

```
porcupine:skp-client tom$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.4-pre.115, on Mac OS X 10.15.3 19D76, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

Dio Version 3.0.8   

### Issue Description and Steps

I am writing a cross platform application. I am using DIO for making XHR-Calls to the server. This works for all platforms (ios, android, macOS, web) which I want to support.

For web compiled builds I need the BrowserHttpClientAdapter and I am using the code only if compiled for web:

```
    if(SkpPlatform.isWeb) {
      BrowserHttpClientAdapter bca = new BrowserHttpClientAdapter();
      bca.withCredentials = true;
      _dio.httpClientAdapter = bca;
    } 
```
However compilation **fails on the import statement** when I compile for macOS, iOS or Android:
`import 'package:dio_cookie_manager/dio_cookie_manager.dart';`

These are the errors, that I am seeing:

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
flutter: false
flutter: 2020-02-20 17:11:12.327357: L10n: Successfully loaded server translations
                                                                        
Compiler message:
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';                                                     
       ^                                                                
flutter: 2020-02-20 17:11:12.548163: _LoginState: Successfully fetched server environment
flutter: 2020-02-20 17:11:12.924392: _LoginState: Disposing skpState other screen
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart:13:18: Error: 'HttpRequest' isn't a type.
  final _xhrs = <HttpRequest>[];                                        
                 ^^^^^^^^^^^                                            
Syncing files to device macOS...                                        
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart:26:15: Error: The method 'HttpRequest' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio/src/adapters/browser_adapter.dart' ('/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.               
    var xhr = HttpRequest();                                                                                       
              ^^^^^^^^^^^                                                                                          
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart:40:34: Error: The method 'Blob' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio/src/adapters/browser_adapter.dart' ('/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blob'.                      
      var blob = xhr.response ?? Blob([]);                                                                         
                                 ^^^^                                                                              
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart:41:20: Error: The method 'FileReader' isn't defined for the class 'BrowserHttpClientAdapter'.
 - 'BrowserHttpClientAdapter' is from 'package:dio/src/adapters/browser_adapter.dart' ('/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/dio-3.0.8/lib/src/adapters/browser_adapter.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.                
      var reader = FileReader();                                                                                   
                   ^^^^^^^^^^                                                                                      
Syncing files to device macOS...                                 6.099ms (!)             
```                          

Please fix `browser_adapter.dart` compilation on non-web platforms, since it is not possible to conditionally import this file just for web builds.

**Comment by technolion** [comment]
You can do that with conditional imports: https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files

**Comment by OHeroJ** [comment]
同样报错

**Comment by chitgoks** [comment]
this should not be closed.
perhaps use universal:html instead of dart:html so that both platforms will compile with no issues?

**Comment by jaripekkala** [comment]
> You can do that with conditional imports: https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files

Could dio export this conditionally? Could just export the `createAdapter()` that's now hidden

**Comment by a-elhaddad** [comment]
Any solution ?

**Comment by Spicely** [comment]
使用universal_html包也无法解决这个问题
![image](https://user-images.githubusercontent.com/10075622/109591477-8ab65900-7b48-11eb-9953-d61034d00029.png)
他讲会得到
![image](https://user-images.githubusercontent.com/10075622/109591508-9bff6580-7b48-11eb-966b-c0a64cfaf3f5.png)
目前是只能在web下使用

**Comment by technolion** [comment]
I wrote a new ticket regarding this problem
我写了一张关于这个问题的新票
https://github.com/flutterchina/dio/issues/1058

**Comment by joo** [comment]
This is my solution, can run on both web and non-Web platforms.
Donn't Importing 'package:dio/adapter_browser.dart', so build is OK!

`      if (Platform.I.isWeb) {
        _dio = Dio(BaseOptions(connectTimeout: 60000, sendTimeout: 60000, receiveTimeout: 60000));
        // (_dio.httpClientAdapter as BrowserHttpClientAdapter).withCredentials = true;
        (_dio.httpClientAdapter as dynamic).withCredentials = true;
      } else {
        _dio = Dio(BaseOptions(connectTimeout: 60000, sendTimeout: 60000, receiveTimeout: 60000));
        (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client) {
          client.badCertificateCallback = (X509Certificate cert, String host, int port) {
            return true;
          };
        };
        _cookieJar = CookieJar();
        _dio.interceptors.add(CookieManager(_cookieJar));
      }
    }`

**Comment by joo** [comment]
In my project everything is correct, run on web and non-Web platforms.

```_dio = Dio(BaseOptions(connectTimeout: 60000, sendTimeout: 60000, receiveTimeout: 60000))```
will create correct httpClientAdapter for web platform and non-Web platforms.
```(_dio.httpClientAdapter as dynamic)```
will not need BrowserHttpClientAdapter, but can set withCredentials attribute value.

**Comment by gurupatel107** [comment]
Though @jaripekkala already mentioned, Took a little while to figure it out. As browser adapter will fail in other platforms apart from web. We need to add conditional importing for web and mobile.

Create stub for abstract implementation 
https://gist.github.com/gurupatel107/66e3f72c9f173e0bdd4cc3a751348675

Add platform specific adapter in separate files 
Web -> https://gist.github.com/gurupatel107/bbf6aaeac513dd895628472e6264122d
Mobile -> https://gist.github.com/gurupatel107/8e8004af7bd997d21d405c7b02512d95

Now use conditional importing in file in api implementation file.

```
import 'dio_adapter_stub.dart'
    if (dart.library.io) 'dio_adapter_mobile.dart'
    if (dart.library.js) 'dio_adapter_web.dart';
```

Use adapter by platform specific code

```
  AppDio._([BaseOptions? options]) {
    options = BaseOptions(
      baseUrl: apiBaseUrl,
      contentType: 'application/json',
      connectTimeout: 30000,
      sendTimeout: 30000,
      receiveTimeout: 30000,
    );
    if (kIsWeb) {
      httpClientAdapter = getAdapter();
    } else {
      httpClientAdapter = getAdapter();
    }
  }
```

**Comment by salihagic** [comment]
Thank you very much, that worked for me.
