### ISSUE TITLE
dio and brotli?

### ISSUE THREAD

**Issue by pro100svitlo** [flutterchina/dio#684]
I wondered, do you have any plans to add `brotli` compression support?

there is nice article: [gzip vs brotli](https://medium.com/oyotech/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4).

**Comment by pro100svitlo** [comment]
hey-hey

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks

**Comment by AlexV525** [comment]
Please submit new issues since we don't handle old issues that are submitted before v5.0, thanks.

**Comment by pro100svitlo** [comment]
> Please submit new issues since we don't handle old issues that are submitted before v5.0, thanks.

Sure. Like this is the reason ... 😅
