### ISSUE TITLE
MultipartFile.fromFile end with error

### ISSUE THREAD

**Issue by shpy2001** [flutterchina/dio#688]
My code:
```
try{
var mpart = MultipartFile.fromFileSync("/storage/emulated/0/SFLink/1582254336015.png",);
}
catch (e){
print(e);
}
```

And it end with:
RangeError (index): Invalid value: Only valid value is 0: 1

And value of e is :
#0      List.[] (dart:core-patch/growable_array.dart:149:60)
#1      FileUploader.uploadFile (package:xxxxxx/helper/file_upload.dart:25:58)
.....

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / ios / android                          |      |
| Platform Version               |   v1.12.13+hotfix.8/ / 10.0                              |      |
| Dio Version                    |   3.0.8                                |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2 /              |      |
| Repro rate                     | e.g. all the time (100%)    |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by AdnanKazi** [comment]
@shpy2001 how do you solved this
