### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received,

### ISSUE THREAD

**Issue by bineanzhou** [flutterchina/dio#694]
dio3.0.9有类似问题 如何解决

**Comment by bineanzhou** [comment]
2020-03-06 00:46:54.568 1249-1433/system_process D/HwGameAssistantController: registerGameObserver:com.android.server.wm.HwDisplayPolicyEx$4@c0507b2, result=true
2020-03-06 00:46:54.590 13548-21048/com.mpc.tramp I/flutter: qdio <-- URL
2020-03-06 00:46:54.591 13548-21048/com.mpc.tramp I/flutter: qdio DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received, uri = http://xxx
2020-03-06 00:46:54.591 13548-21048/com.mpc.tramp I/flutter: qdio <-- End error

**Comment by leszekkrol** [comment]
Anu update?

**Comment by dhruvan2912** [comment]
I'm also facing this issue in iOS build. Any solution?

**Comment by HyBLF** [comment]
I'm also facing this issue. Any solution?

**Comment by whatamelon** [comment]
This issue isn't solved, so it must be reopen.

**Comment by LLemonGreen** [comment]
Any solution?

**Comment by whatamelon** [comment]
If you guys getting many images at a time, how about change url https -> http.

It solved my problem. But not a perfect solution.

**Comment by leszekkrol** [comment]
@whatamelon It won't work on Android 10 which requires an https connection

**Comment by hkeyz** [comment]
I have the same problem! Any solution plz?

**Comment by Jamsheer-touchworld** [comment]
I have the same issue.

**Comment by ImTung** [comment]
Same here

**Comment by ImTung** [comment]
4 me: turn off `cached_network_image` and it's worked

**Comment by InTheClodus** [comment]
This problem is generally a bug on the server side. Please communicate with your back-end development colleagues.

**Comment by InTheClodus** [comment]
This problem is generally a bug on the server side. Please communicate with your back-end development colleagues.

**Comment by Ssiswent** [comment]
> This problem is generally a bug on the server side. Please communicate with your back-end development colleagues.

But our website doesn't have this problem.
