### ISSUE TITLE
DioErrorType.CONNECT_TIMEOUT异常无法处理，总是给我抛出！

### ISSUE THREAD

**Issue by ddxl123** [flutterchina/dio#696]
### New Issue Checklist
- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
| Dio Version：                   all version
我尝试了任何版本，都会出现这个问题，但是我始终没解决，只有在断点里的Uncaught Exceptions去掉勾选才能不抛出，但这并不是解决方案！

### Issue Description and Steps
```
try {

      Dio dio = new Dio();

      dio.options.connectTimeout = 5000; // 服务器链接超时，毫秒

      Response res = await dio.post(

        url,

        data: data,

        options: Options(contentType: "application/x-www-form-urlencoded"),

      );

    } catch (e) {

      print(e);

    }
```

抛出DioError (DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out [5000ms])
异常后，我点击“单步跳过(F10)”，`print(e)`会被执行。

**Comment by trlanfeng** [comment]
同样遇到这个错误，所有的异常，均不会被捕获到，例如404、500、请求超时、响应超时。
onError拦截器、catchError、try-catch均无法捕获到错误。

**Comment by devSC** [comment]
me too..

**Comment by huscarter** [comment]
me too..

**Comment by kennenfromchina** [comment]
me too

**Comment by pratamatama** [comment]
any update on this? It happened to me as well. Please fix this..

**Comment by heimabailang** [comment]
me too

**Comment by z234009184** [comment]
the same

**Comment by sj1910** [comment]
me too. Do you have a solution？

**Comment by hiperioncn** [comment]
me too
