### ISSUE TITLE
unable to send post request in dio - flutter

### ISSUE THREAD

**Issue by dineshsy** [flutterchina/dio#698]
- Hi, I'm trying to send Post request from my flutter(dio) to my flask restful-api.
- I want to give my request body in form-data because i need to send a image file.
- I built this flask app with the help of postman it works fine with my postman's form-data.
- but when i try with flutter's dio package to Post the form-data to my flask I'm getting an error in flask which is mentioned below.

The dio code is :
```

Future<List> apiRequest(int N ,File file) async {
  String url = "http://10.0.2.2:5000/";
  // HttpClient httpClient = new HttpClient();
          Post _post = Post();

  var bytes = await file.readAsBytes();
  //TODO : dio post request
  var dio = new Dio();
  MultipartFile  multipartFile = new MultipartFile.fromBytes(bytes);
  FormData formData = new FormData();
  dio.options.headers = {"content-type" :"multipart/form-dataitem"};
  formData.fields.add(MapEntry("index" , N.toString()));
  formData.files.add(MapEntry("file",multipartFile));
  print(formData);
   await dio.post(url, data: formData,options: Options(
            method: 'POST',
            responseType: ResponseType.json // or ResponseType.JSON
        )).then((response){
             //response stuffs
        });
```
postman's request: [this image consists of my postman's Post request which works fine](https://i.stack.imgur.com/V7eeQ.png)

my flask statements that using this form-data is:
```

        fromJson = request.form['index']
        Img = request.files['file']
```
the error in my flask console is:

```
{exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.}


```

**Comment by dineshsy** [comment]
I figured out the ERROR. the file I'm send is not available in the files of the request. But it is available in the fields I don't know why..! So I looked into the normal HTTP.multipart() request's documentation and I tried that It works fine.

**Comment by shadyshrif** [comment]
The same error happened after upgrading to flutter version 1.22.2 on both Android an IOS.

The problem was that I'm sending a header in the multipart request which was working on the old flutter version
