### ISSUE TITLE
Force WiFi only

### ISSUE THREAD

**Issue by skydiablo** [flutterchina/dio#699]
hi,
is there any chance to make an request that will be forced over the WiFi, regardless of an existing mobil-connection-uplink?!
so, if i connected to an WiFi and there is no internet-uplink available, some android devices will always use the mobil-connection-uplink. so is there an "dio" flag that can i set to force use the WiFi only?

volker.

**Comment by mo-aro-etailer** [comment]
Hey, any update to this? @harrowmykel
