### ISSUE TITLE
onProgress for FormData file upload

### ISSUE THREAD

**Issue by rasumo** [flutterchina/dio#7]
How could I go about adding an onProgress callback for file uploads similar to what you have for downloads? This would all me to give the user feedback about the upload (progress bar).

**Comment by wendux** [comment]
Sorry,  because dio depends on dart `HttpClient`, but it doesn't seem to exists any ways to retrieve upload progress.

**Comment by fvisticot** [comment]
Any progress on this,really need upload progress info !

**Comment by Xgamefactory** [comment]
it is possible to add stream to http package would be nice to add stream support for dio too

```
Stream<List<int>> streamUpload = msStream.transform(
      new StreamTransformer.fromHandlers(
        handleData: (data, sink) {
          sink.add(data);

          byteCount += data.length;

          if (onUploadProgress != null) {
            onUploadProgress(byteCount, totalByteLength);
            // CALL STATUS CALLBACK;
          }
        },
        handleError: (error, stack, sink) {
          throw error;
        },
        handleDone: (sink) {
          sink.close();
          // UPLOAD DONE;
        },
      ),
    );

    await request.addStream(streamUpload);

```
