### ISSUE TITLE
No onSendProgress callback for PUT method

### ISSUE THREAD

**Issue by zinwalin** [flutterchina/dio#702]
`  
Response response = await dio.put(url,
          data: Stream.fromIterable(fileData.map((e) => [e])),
          options: Options(
            headers: headers,
          ), onSendProgress: (int sent, int total) {
        print("$sent $total");
      }, onReceiveProgress: (int recev, int total) {
        print("$recev $total");
      });
`

nothing happened in onSendProgress callback. any suggestion?

----
dio: 3.0.8
flutter: v1.12.13+hotfix.8
platform: iOS & Android

**Comment by MattyBoy4444** [comment]
Any update on this.  It is also happening to me

**Comment by KikiLetGo** [comment]
Same issues to me, **onSendProgress** executed with **Post** method, but noting happed with **Put** method
