### ISSUE TITLE
Disable encoding on queryParams

### ISSUE THREAD

**Issue by lcaprini** [flutterchina/dio#704]
Hi,
I'm using the Firebase Realtime Database in a simple app, but when I try to filter results with `orderBy` parameter I fetch a 400 HTTP error.

```dart
final query = {
  'auth': authToken,
  'orderBy': '"creatorId"',
  'equalTo': userId,
};
final url = '/products.json';
try {
  final response = (await _dio.get(url, queryParameters: query)).data;
....
}
```
The value of `orderBy` must be included into double quotes ([Retrieving Data | Filtering by key](https://firebase.google.com/docs/database/rest/retrieve-data?hl=it#filtering-by-key)), but if using the `onRequest` interceptor, I see that the `options.uri.query` string is:

`auth=<authKey>&orderBy=%22creatorId%22&equalTo=JclawOgVodehj5kEIvnen4sKKIg1` 

instead of 

`auth=<authKey>&orderBy="creatorId"&equalTo=JclawOgVodehj5kEIvnen4sKKIg1`.

If I append the queries to the `url` param all works fine.

There is a way to bypass/disable the encode of `queryParameters`?

Thanks
--Luca

**Comment by Juniorlpes** [comment]
I have the same problem. any solution?
