### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: (OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by mulieli** [flutterchina/dio#711]
flutter 安卓 9.0 访问接口失败 报一下错误  IOS上访问正常
<img width="1530" alt="WeChate6b80e1d3a42f4a5b4ec5af02832e702" src="https://user-images.githubusercontent.com/24307960/77224102-3ca97f00-6b9d-11ea-833e-7ee859cdd144.png">

**Comment by mulieli** [comment]
网络权限也添加了

**Comment by daigewuwy** [comment]
你可能需要加网络权限，具体百度一下。我是iOS上不行，会爆和你一样的错误，请问又遇到过嘛，怎么解决的，或者说iOS需要加什么网络权限嘛，我已经允许http访问了

**Comment by Kun8018** [comment]
楼主解决了吗？我在Androidmanifest.xml加了权限代码，但是还是不行啊

**Comment by mulieli** [comment]
> 楼主解决了吗？我在Androidmanifest.xml加了权限代码，但是还是不行啊

我感觉是安卓访问不了本地host 的域名吧  我本地用ip访问就可以了  正式版我没试过  正式版用域名应该没问题

**Comment by mulieli** [comment]
> 你可能需要加网络权限，具体百度一下。我是iOS上不行，会爆和你一样的错误，请问又遇到过嘛，怎么解决的，或者说iOS需要加什么网络权限嘛，我已经允许http访问了

IOS 我没遇见过这个问题 我就在安卓上遇到过

**Comment by kennenfromchina** [comment]
我是iOS异常

**Comment by jinxiaodong** [comment]
> 你可能需要加网络权限，具体百度一下。我是iOS上不行，会爆和你一样的错误，请问又遇到过嘛，怎么解决的，或者说iOS需要加什么网络权限嘛，我已经允许http访问了

我IOS也遇到同样的问题，请问你那边有解决吗

**Comment by kennenfromchina** [comment]
> > 你可能需要加网络权限，具体百度一下。我是iOS上不行，会爆和你一样的错误，请问又遇到过嘛，怎么解决的，或者说iOS需要加什么网络权限嘛，我已经允许http访问了
> 
> 我IOS也遇到同样的问题，请问你那边有解决吗

我还原网络设置重启手机之后好了，应该是DNS缓存导致的

**Comment by Kun8018** [comment]
> > 你可能需要加网络权限，具体百度一下。我是iOS上不行，会爆和你一样的错误，请问又遇到过嘛，怎么解决的，或者说iOS需要加什么网络权限嘛，我已经允许http访问了
> 
> IOS 我没遇见过这个问题 我就在安卓上遇到过
我之前开了权限无法访问网络，然后发现手机没连wifi，在手机上连上wifi，然后可以了.....

**Comment by shxlxa** [comment]
> 我是iOS异常



> > 你可能需要加网络权限，具体百度一下。我是iOS上不行，会爆和你一样的错误，请问又遇到过嘛，怎么解决的，或者说iOS需要加什么网络权限嘛，我已经允许http访问了
> 
> 我IOS也遇到同样的问题，请问你那边有解决吗

![WX20200513-182010](https://user-images.githubusercontent.com/12759292/81801199-a06d7a00-9546-11ea-8fe9-92855db5e4e7.png)
检查一下iphone设置中，你的app无线网络那里有没有打开网络，我的是这里的问题，诡异的是，我切换到 WLAN与蜂窝网络， 系统会自动切回到 关闭，最后app换了个bundle ID才可以，希望有帮助。

**Comment by jinxiaodong** [comment]
我把手机重启了下，然后卸载重装后好了，我觉得可能是Iphone开发者模式下的网络问题

发自我的iPhone

**Comment by nooto** [comment]
iOS 上遇到这个问题了。在进行审核时被拒。目前还没找到解决方法

**Comment by OHeroJ** [comment]
这个问题还是挺严重的，还没修复就关了？

**Comment by ichenwanbing** [comment]
我也遇到了这个问题，线上环境遇到(偶现)，很久了都没解决。有人解决的话联系我一下，谢谢。
很多说配置网络权限，模拟器等等都跟我的情况不同

**Comment by ichenwanbing** [comment]
为什么没解决就草率的关了，这个问题问的人那么多

**Comment by yuhaocan** [comment]
same issue 
mark it

**Comment by git-boya** [comment]
同样的问题,生产环境偶现,ios和android都有遇到.
android和ios错误略有不同.
可以确定网络没问题,只在移动网络下出现,wifi网络没出现过.
Android:
```
DioError [DioErrorType.other]: SocketException: Failed host lookup: 'sc.ieducc.com' (OS Error: No address associated with hostname, errno = 7)
```
iOS:
```
DioError [DioErrorType.other]: SocketException: Failed host lookup: 'sc.ieducc.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
```
![image](https://user-images.githubusercontent.com/17589102/188595635-f63de64b-37eb-4fed-aa46-c4d2e858e121.png)

**Comment by ichenwanbing** [comment]
经过验证，这个错误断网必现


| |
陈万兵
|
|
***@***.***
|
签名由网易邮箱大师定制


On 09/6/2022 ***@***.***> wrote：

同样的问题,生产环境偶现,ios和android都有遇到.
android和ios错误略有不同.
可以确定网络没问题,只在移动网络下出现,wifi网络没出现过.
Android:

DioError [DioErrorType.other]: SocketException: Failed host lookup: 'sc.ieducc.com' (OS Error: No address associated with hostname, errno = 7)



iOS:

DioError [DioErrorType.other]: SocketException: Failed host lookup: 'sc.ieducc.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

**Comment by git-boya** [comment]
> 经过验证，这个错误断网必现 | | 陈万兵 | | ***@***.*** | 签名由网易邮箱大师定制 On 09/6/2022 ***@***.***> wrote： 同样的问题,生产环境偶现,ios和android都有遇到. android和ios错误略有不同. 可以确定网络没问题,只在移动网络下出现,wifi网络没出现过. Android: DioError [DioErrorType.other]: SocketException: Failed host lookup: 'sc.ieducc.com' (OS Error: No address associated with hostname, errno = 7) iOS: DioError [DioErrorType.other]: SocketException: Failed host lookup: 'sc.ieducc.com' (OS Error: nodename nor servname provided, or not known, errno = 8) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

断网情况出现是正常的.
我这里是没有断网,其他app都是可以正常访问网络.只有我们的app访问不了,切换到wifi网络又可以访问了.
而且同一时间其他手机都可以正常访问.
