### ISSUE TITLE
 HttpException: Connection closed while receiving data

### ISSUE THREAD

**Issue by ravitejaavv** [flutterchina/dio#713]
HttpException: Connection closed while receiving data

**Comment by KyawSoeW1n** [comment]
Reopen It

**Comment by fullflash** [comment]
there are many issue for this "Connection closed while receiving data" all of them are closed but we still have this issue.

**Comment by kuhnroyal** [comment]
@fullflash Please provide a reproducible sample and create a new ticket, otherwise it is impossible to follow up on it.
