### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [500]

### ISSUE THREAD

**Issue by Silerqin** [flutterchina/dio#715]
I have error about `DioError [DioErrorType.RESPONSE]: Http status error [500]`. Anyone can help me?
我有这个问题`DioError [DioErrorType.RESPONSE]: Http status error [500]`。 请问有人知道怎样解决吗？

这是我的代码： 
Here is my code:

````
Future upload(BuildContext context) async {
Response response;
      Dio dio = new Dio();
      dio.options.headers = {
        'Content-type': 'multipart/form-data',
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + token,
      };

FormData formData = new FormData.fromMap({
        "photo": await MultipartFile.fromFile(imageFile.path,filename: "photo.jpg"),
        "title": titleController.text,
        "description": descriptionController.text,
      });
      response = await dio.post("API_URL", data: formData);
      print(response.data);
}
````

**Comment by omarsherifs** [comment]
this means that you may send a wrong data or that may a server issue ... can you catch the exception and print the response?

**Comment by herarya** [comment]
yes same issue

**Comment by sonywibisono** [comment]
Same as me. just searching from yesterday, but not find any solution.

**Comment by Ranjith306** [comment]
same issue  Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [500]

**Comment by mohammadeslim22** [comment]
i have the same issue here

**Comment by Joezzy** [comment]
this issue from the server side , the server is not accepting one or more of the parameters you are sending, if you are in control with the backend you can send everything as string and convert them to whatever you want on the other side

**Comment by vipinmtvipin** [comment]
I have faced the same issue

**Comment by Cs-Infotech-bd** [comment]
i have faced same issue. what is the exact solution?

**Comment by heinaungzan** [comment]
I have faced same issue ,i see response.data but cann't get.Why?

**Comment by Rammehar** [comment]
I also have same issue

**Comment by fullflash** [comment]
same issue here and this error not catched with try catch

**Comment by abhimanyu95** [comment]
same Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [500] 
Usually this error is from backend but when i hit my api with the HTTP package then it works fine and also tried on postman, it works fine there.  
This problem is only with dio package.

**Comment by anggaaryas** [comment]
Same here. Why dio not handle the response when the status code is 500?

**Comment by abirajabi** [comment]
Same here, have you guys figured out the solution? I'm trying to upload an image, it works with several accounts, but for some others dio kept throwing error 500. I tried to hit directly from Postman, it works fine and the response is 200.

**Comment by lreardon** [comment]
I'm encountering the same or a similar issue -- the requests are actually successful, but the Dio package reports that they are unsuccessful with error code 500. I'm wondering if it is a bug or undocumented configuration of the package Dio.

**Comment by nehal076** [comment]
Facing same issue for Flutter web. I'm getting `Http status error [500]` when I send Multipart Request. I works on Android & iOS but not on web.

**Comment by kuhnroyal** [comment]
Please create a reproducible sample and open a new issue.

**Comment by abirajabi** [comment]
Sorry for late posting, I finally found the issue and how to fix it.

In my case, I was trying to send and image file within the multipart data. It seems, Dio needs to know what format/type of file that we send by passing some value to the contentType parameter. So, we need to pass the mime type dynamically to the contenType parameter. 

To accomplish that, I use the [mime ](https://pub.dev/packages/mime) package from pub dev, then lookup the mime type before parsing it to FormData. Here's the code:

```Dart
/// file is the function parameter
String fileName = file.path.split('/').last;
FormData data = FormData.fromMap({
      "file": await MultipartFile.fromFile(file.path,
          filename: fileName,
          contentType: MediaType.parse("${lookupMimeType(fileName)}")),
    });
```

It works fine on my case. Hope it helps.

**Comment by Alvish0407** [comment]
> Sorry for late posting, I finally found the issue and how to fix it.
> 
> In my case, I was trying to send and image file within the multipart data. It seems, Dio needs to know what format/type of file that we send by passing some value to the contentType parameter. So, we need to pass the mime type dynamically to the contenType parameter.
> 
> To accomplish that, I use the [mime ](https://pub.dev/packages/mime) package from pub dev, then lookup the mime type before parsing it to FormData. Here's the code:
> 
> ```dart
> import 'package:mime/mime.dart';
> 
> ....
> 
> /// file is the function parameter
> String fileName = file.path.split('/').last;
> FormData data = FormData.fromMap({
>       "file": await MultipartFile.fromFile(file.path,
>           filename: fileName,
>           contentType: MediaType.parse("${lookupMimeType(fileName)}")),
>     });
> ```
> 
> It works fine on my case. Hope it helps.

add [http_parser](https://pub.dev/packages/http_parser) along with the [mime](https://pub.dev/packages/mime) to pubspec.yaml
