### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>

### ISSUE THREAD

**Issue by fengdeyingzi** [flutterchina/dio#716]
遇到一个很神奇的问题，其它的接口都是好的，就这个json解析失败
 DioMixin.assureResponse (package:dio/src/dio.dart:1138:9)
I/flutter (14318): #1      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:904:14)
I/flutter (14318): #2      _rootRunUnary (dart:async/zone.dart:1134:38)
I/flutter (14318): #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
I/flutter (14318): #4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
I/flutter (14318): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
I/flutter (14318): #6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
I/flutter (14318): #7      Future._complete (dart:async/future_impl.dart:514:7)
I/flutter (14318): #8      _SyncCompleter.complete (dart:async/future_impl.dart:53:12)
I/flutter (14318): #9      Future.any.<anonymous closure> (dart:async/future.dart:459:45)
I/flutter (14318): #10     _rootRunUnary (dart:async/zone.dart:1134:38)

**Comment by fengdeyingzi** [comment]
我写了一个复现这个错误的例子
~~~
  Future<void> onGetData() async {
    Dio dio = new Dio( new BaseOptions(
      connectTimeout: 10000, //连接超时时间
      receiveTimeout: 10000, //接收超时时间
    ));
    Response<Map<String,dynamic>> response =  await dio.post<Map<String,dynamic>>("http://app.yzjlb.net/temp/jsontest.php", data: {
      "id":1
    });
//    json_result = response.data;
    setState(() {

    });
  }
~~~

**Comment by fengdeyingzi** [comment]
找到原因了.....原来服务器必须加上json类型的header QAQ
~~~
header( 'Content-Type:application/json;charset=utf-8 ');
~~~

**Comment by s2yed** [comment]
╔ Body
I/flutter ( 6463): ║
I/flutter ( 6463): ║ {"status_code":"200","status":"true","data":{"id":"52","name":"jkj","linestatus":0}}
I/flutter ( 6463): ║
I/flutter ( 6463): ╚══════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6463): DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>'

**Comment by hfbi360** [comment]
> 找到原因了.....原来服务器必须加上json类型的header QAQ
> 
> ```
> header( 'Content-Type:application/json;charset=utf-8 ');
> ```

服务器不改的情况下，有没有办法解决这个问题？

**Comment by hfbi360** [comment]
> 找到原因了.....原来服务器必须加上json类型的header QAQ
> 
> ```
> header( 'Content-Type:application/json;charset=utf-8 ');
> ```

后台不修改的情况下，自己处理，需要decode成json格式：json.decode(response.data) 使用这个方式也可以
