### ISSUE TITLE
拦截器刷新token的问题

### ISSUE THREAD

**Issue by pppshiwen** [flutterchina/dio#720]
我已经在拦截器的onError里返回response 了,之后在onResponse里也被拦截到了，可没有返回给当初的函数的调用接口

dio.interceptors.add(RefreshTokenInterceptor());
//添加拦截器
dio.interceptors.add(InterceptorsWrapper(
//请求之前
onRequest: (RequestOptions options) async{
var token = await Storage.getString('Token');
//统
if(token != null) {
options.headers[HttpHeaders.authorizationHeader] = 'Bearer ' + token;
}
return options; //continue
}, onResponse: (Response response){//返回之前
print('response1$response');
return response; // continue
}
, onError: (DioError e)async{
}
));
}

//刷新token 拦截器
class RefreshTokenInterceptor extends Interceptor {
@override
onError(DioError e) async{
// TODO: implement onError
print('错误码：${e.response.statusCode}');
print("错误之前");
var tokenDio = HttpUtil.getInstance().dio;
Response _response = e.response;
if(_response != null && _response.statusCode == 401) {//登录过期，重新登录

}else if(_response != null && _response.statusCode == 419) { //重新获取token
  tokenDio.lock();
  tokenDio.interceptors.responseLock.lock();
  tokenDio.interceptors.errorLock.lock();
  String reToken = await Storage.getString("reToken");
  print('reToken$reToken');
  //刷新token
  getRetoken(reToken).then((val) async {//刷新token成功
  print('val${val.data['access_token']}');
    Storage.setString("Token", val.data['access_token']);
    //继续执行上个请求
    var _request = e.response.request;
    var token = await Storage.getString('Token');
    _request.headers[HttpHeaders.authorizationHeader] = 'Bearer ' + token;
    Response _response = await tokenDio.request(
        _request.path,
        data: _request.data,
        queryParameters: _request.queryParameters,
        cancelToken: _request.cancelToken,
        options: _request,
        onReceiveProgress: _request.onReceiveProgress);
// print('response--------$_response');
return _response;
}).catchError((e) {// 刷新token失败
print('getRetoken---e----$e');

  });
  tokenDio.unlock();
  tokenDio.interceptors.responseLock.unlock();
  tokenDio.interceptors.errorLock.unlock();
}
super.onError(e);
}

Future getRetoken(reToken) async {
var dio = Dio();
var data = {
"grant_type": "refresh_token",
"client_id": "mall",
"client_secret": "secret",
"refresh_token": reToken,
};
Options options = Options();
options.contentType = Headers.formUrlEncodedContentType;
var response = await dio.post(servicePath['reTokenPath'],data:data,options: options);
return response;
}
}

// 获取购物车列表
Future getShoppingCart() async{
// Options options = Options();
// options.contentType = Headers.jsonContentType;
var response = await HttpUtil().dio.get(servicePath['shoppingCart']);
print('getShoppingCart-----$response');
return response.data;
}

print('response1$response');有执行
print('getShoppingCart-----$response');没有被执行到

所以最后的结果没有返回给getShoppingCart()函数

**Comment by pppshiwen** [comment]
#160 @wendux

**Comment by xiaobeifeng** [comment]
兄弟，你怎么解决的，可以分享下吗？

**Comment by pppshiwen** [comment]
@xiaobeifeng 
     var tokenDio = HttpUtil().dio;
      var _request = e.response.request;
      var token = await Storage.getString('Token');
      _request.headers[HttpHeaders.authorizationHeader] = 'Bearer ' + token;
      Response _response = await tokenDio.request(_request.path,options: _request);

难点在于把新的token拿到之后，要继续执行上一个请求，那就用 var _request = e.response.request; 拿到上个请求体，再把新的token放到请求头，去请求，思路跟关键代码就这样

**Comment by xiaobeifeng** [comment]
感谢

2020年9月8日 上午10:19，pppshiwen <notifications@github.com<mailto:notifications@github.com>> 写道：



@xiaobeifeng<https://github.com/xiaobeifeng>
var tokenDio = HttpUtil().dio;
var _request = e.response.request;
var token = await Storage.getString('Token');
_request.headers[HttpHeaders.authorizationHeader] = 'Bearer ' + token;
Response _response = await tokenDio.request(_request.path,options: _request);

难点在于把新的token拿到之后，要继续执行上一个请求，那就用 var _request = e.response.request; 拿到上个请求体，再把新的token放到请求头，去请求，思路跟关键代码就这样
