### ISSUE TITLE
connectTimeout/receiveTimeout doesn't work

### ISSUE THREAD

**Issue by JCKodel** [flutterchina/dio#722]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / android                          |      |
| Platform Version               | 1.12.13+hotfix.8 / 7.0                              |      |
| Dio Version                    |  3.0.9                                 |      |
| Repro rate                     | all the time (100%) |      |

### Issue Description and Steps

Dio options:
```dart
 __dio = Dio(BaseOptions(
      headers: {"Accept": "application/json"},
      responseType: ResponseType.json,
      receiveTimeout: 30000,
      connectTimeout: 5000,
      followRedirects: false,
      receiveDataWhenStatusError: true,
      baseUrl: _baseUrl,
    ));
```

When my server takes more then 5s to process something, it fails with timeout. BUT the CONNECT timeout is 5s, not the RECEIVE timeout.

I expect that connect has resolved since it has successfully connected to the client (it didn't receive any response yet, hence the bigger receiveTimeout setting).

**Comment by MoacirSchmidt** [comment]
It seems a duplicate from #494 ?

**Comment by liufeihe** [comment]
i have the same issue.
my app is linked to a Wifi which is not connected to internet.
and i set the connnect timeout to 2 seconds.
but the dio took almost 2 minutes to timeout.

i try it on dio 3.0.4,3.0.8,3.0.9, they all have the same problem

my debeug info is below:
`I/flutter (25438): [debug], [DioCloud], [Wed, 22 Apr 2020 06:10:57 GMT], request get, uri=http://api.lebai.ltd/ds/test/app/user/feedbacks, data=null, params={current: 1, size: 30}, headers=null
I/flutter (25438): connectTimeout, 2000
I/flutter (25438): {content-type: application/json; charset=utf-8, Authorization: eyJhbGciOyk}
I/flutter (25438): [debug], [DioCloud], [Wed, 22 Apr 2020 06:12:02 GMT], uri=/app/user/feedbacks, e=DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'api.lebai.ltd' (OS Error: No address associated with hostname, errno = 7)
I/flutter (25438): [debug], [DioCloud], [Wed, 22 Apr 2020 06:12:02 GMT], e response=null`



> It seems a duplicate from #494 ?
> 
> Does it used to work in 2.x version?

**Comment by yunnywu** [comment]
i have some problem, version v3.0.9. pls help to fix this

**Comment by JCKodel** [comment]
**This is NOT about not working timeout! This is about connection timeout being different than receive timeout!!!**

**Comment by MoacirSchmidt** [comment]
Please do not close. Problem still persists in latest version.

**Comment by Yuliang-Lee** [comment]
same problem in v3.0.9

**Comment by gabcarneiro** [comment]
Please reopen this issue

**Comment by shijianit** [comment]
3.0.9 still has this problem，Please reopen this issue

**Comment by shijianit** [comment]
This problem still exists in 3.0.9. Please reopen this problem. This problem will appear every time and is easy to find. Why not solve it as soon as possible?

3.0.9还存在此问题，请重新开启这个问题，这个问题必现，很容易发现，为什么不尽快解决呢？

**Comment by heimabailang** [comment]
3.0.9 still has this problem，Please reopen this issue

**Comment by colabra1000** [comment]
Please reopen this issues. am really facing problems with this

**Comment by patuoynageek** [comment]
Same issue on 3.0.10

**Comment by Jjagg** [comment]
Please consider reopening this issue, or at least clarifying how `connectTimeout` works and/or pinning this issue. In my app, for operations involving potentially large images this issue caused intermittent crashes for some users (depending on their internet speed).

Not a great issue to debug because — like others — I assumed the `connectTimeout` was only relevant for actually connecting to the server. My server handled requests successfully so I did not figure out the actual issue until I logged errors in the app to the cloud.

**Comment by amberfan** [comment]
version 3.0.10 
Please resolve this bug.

**Comment by mikezander** [comment]
This is still an issue! I'm having an issue with downloading. Connection timeout never throws an error and then receive timeout throws an error even in the middle of a successful download.

Has anyone found a workaround? I tried [#844](https://github.com/flutterchina/dio/issues/844) but no luck.

**Comment by Jojoooo1** [comment]
Having the same problem anyone had success resolving it ?

**Comment by rirjkl19** [comment]
Still not working to the lastest Dio version

**Comment by Mohamed-Emara-ADV** [comment]
The issue still exists in version 3.0.10

**Comment by jaripekkala** [comment]
Would be great to get more clear documentation on what these properties actually mean. It is rather unclear is the connectTimeout the theoretical maximum time for a network request (before it succeeds/fails on timeout) or is it all combined.

**Comment by falconeta** [comment]
Hi, We`ve tested on v 4.0.0 and the problem still persist, for us the connectTimeout would be implemented:

```
HttpClient client = new HttpClient();
client.connectionTimeout = Duration(seconds: 3); // this is the connectTimeout
try {
  final request =
      await client.getUrl(Uri.parse("http://server_url/api"));
  final response = await request.close();
  print(response);
} catch (e) {
  print(e);
}
```

instead of 

```
if (options.connectTimeout > 0) {
        request = await reqFuture
            .timeout(Duration(milliseconds: options.connectTimeout));
} else {
        request = await reqFuture;
}
```

please, consider to reopen the issue.

**Comment by Emarcode** [comment]
Thank you @falconeta, I'm asking if this code is working for you and where can I use it?

**Comment by falconeta** [comment]
Hi @Emarcode, this code is an example with the httpClient and it work very well. On Dio the connectTimeout implementation is not a connectTimeout but a requestTimeout (the timeout is applied on the request generated by httpClient).

**Comment by Emarcode** [comment]
Hi @falconeta, do you have a way to use this code with dio instead of dio's one, because it seems that none is solving the problem.

**Comment by falconeta** [comment]
@Emarcode right now I implemented the [httpClient](https://api.dart.dev/stable/2.13.4/dart-io/HttpClient-class.html)  without dio (a wrapper of dart httpClient).

**Comment by yebgi83** [comment]
I've posted as a proposal about it.
https://github.com/flutterchina/dio/issues/1282

**Comment by 86linksrain** [comment]
The issue still exists in version  4.0.6

**Comment by totdlinnyy1** [comment]
The issue still exists in version 5.0.0

**Comment by Utitofon-Udoekong** [comment]
I think this is an issue with the parameter names. Changing the connection timeout fixes the error. The connectionTimeout is the time taken to connect to the server not to transfer data.

**Comment by HosamHasanRamadan** [comment]
I implemented a workaround for it :
```dart
final cancelToken = CancelToken();
try {
  final response = await Dio()
      .get(
        "url",
        cancelToken: cancelToken,
      )
      .timeout(const Duration(seconds: 10));
} on TimeoutException {
  cancelToken.cancel();
}
```

**Comment by NathansLiu** [comment]
> 我为此实施了一个解决方法：
> 
> ```dart
> final cancelToken = CancelToken();
> try {
>   final response = await Dio()
>       .get(
>         "url",
>         cancelToken: cancelToken,
>       )
>       .timeout(const Duration(seconds: 10));
> } on TimeoutException {
>   cancelToken.cancel();
> }
> ```

Unfortunately, it didn't work

**Comment by houssam15** [comment]
> I implemented a workaround for it :
> 
> ```dart
> final cancelToken = CancelToken();
> try {
>   final response = await Dio()
>       .get(
>         "url",
>         cancelToken: cancelToken,
>       )
>       .timeout(const Duration(seconds: 10));
> } on TimeoutException {
>   cancelToken.cancel();
> }
> ```

solution of [HosamHasanRamadan] work file , this is how  i impement it 
  Future<bool> checkServerAvailability() async {
    try {
      final response = await dio
          .get(this.getResourceUrl())
          .timeout(const Duration(seconds: 10));
      return true;
    } on TimeoutException catch (ex) {
      return false;
    }
  }
  
 thank you all !

**Comment by georrge1994** [comment]
Was problem resolved? Where is the fix?
