### ISSUE TITLE
How to close and cancel a response stream properly?

### ISSUE THREAD

**Issue by renenucci** [flutterchina/dio#729]
Hi!

In the documentation, talk about get a stream response, like this:

`Response<ResponseBody> rs = await Dio().get<ResponseBody>(url,
 options: Options(responseType: ResponseType.stream), // set responseType to `stream`
);
print(rs.data.stream); //response stream`

But, and if I want to close that TCP Connection? I tried with cancelToken into request, but no successful, the response keep coming via stream.listen.

I'm Afraid that just cancel the StreamSubscription is not enough, and GC keeps the response object runing in background.

Is there another way to close connection properly? (TCP)

**Comment by 1232209** [comment]
same here,my question is upload file
in release mode,cancelToken is not work expected,I want to close the connection!

**Comment by jethroHuang** [comment]
Me too. How do I close the connection

**Comment by hurelhuyag** [comment]
There is a method `ResponseBody.close()` But it seems doesn't do anything.
