### ISSUE TITLE
如何接收json字符串，禁用dio自动转换Json对象

### ISSUE THREAD

**Issue by WhyNoter** [flutterchina/dio#73]
返回的 response.data.toString()  后，自动把双引号去掉了，我没有用convert解析，用其他库解析结果报错，请问怎么保留原来返回字段里的双引号，谢谢。

**Comment by wendux** [comment]
有两种方法：
1. 可以不让dio自动转换json，可以配置请求参数`responseType=ResponseType.PLAIN`.
2. `json.encode(response.data)`或`jsonEncode(response.data)`

**Comment by WhyNoter** [comment]
可以了，thanks！
