### ISSUE TITLE
flutter web https 请求无法使用dio.httpClientAdapter as DefaultHttpClientAdapter 

### ISSUE THREAD

**Issue by SystemTce** [flutterchina/dio#733]
dio.httpClientAdapter as DefaultHttpClientAdapter 在web中会报错，因为flutter web 中dio使用的是 BrowserHttpClientAdapter。
BrowserHttpClientAdapter 中没有设置onHttpClientCreate 方法，请问有解决办法吗？

**Comment by CoderHln** [comment]
crash ：Cannot find kernel2js compiler for packages/dio/src/entry/dio_for_browser.dart
同问

**Comment by shyandsy** [comment]
同问，升级3.6以后这个类没有了

**Comment by CoderHln** [comment]
> 同问，想设置代理解决跨域问题，浏览器会报： Uncaught (in promise) Error: Expected a value of type 'DefaultHttpClientAdapter', but got one of type 'BrowserHttpClientAdapter'

已经解决了跨域的问题，没有使用dio设置代理的方式。使用了issues465中有个大神的解决方案，使用中间件，启动了本地服务，把localhost映射到了要访问的API地址，终于可以在本地跨域调试了。
https://github.com/flutterchina/dio/issues/465
