### ISSUE TITLE
respone 的 realUri 属性可能会发生下标越界

### ISSUE THREAD

**Issue by mytaia** [flutterchina/dio#735]
问题重现

访问一个需要跳转的页面（即响应码为302）的页面
使用下面代码 

`Response response = await dio.request(appLoginPath,options: Options(followRedirects: false, responseType:ResponseType.plain  ));`

即可以重现，报错信息为

`DioError [DioErrorType.DEFAULT]: Bad state: No element`

对应问题的源代码

`  /// Return the final real request uri (maybe redirect).
  ///
  /// ** Attention **: Whether this field is available depends on whether the
  /// implementation of the adapter supports it or not.
  Uri get realUri => redirects.last?.location ?? request.uri;`

**Comment by dpossas** [comment]
I have the same problem happening in my application
