### ISSUE TITLE
请问web版本的Dio是不是没用连接池，会造成大量的链接发生？

### ISSUE THREAD

**Issue by baigui** [flutterchina/dio#736]
### 请问web版本的Dio是不是没用连接池，会造成大量的链接发生

最近用Dio调用githubPage的接口，有些时候访问一次网络后，githubpage的接口就会拒绝访问了，因为我使用的接口最多只能访问60次，请问你们库不会不会错误后连续重复请求？
因为flutter web不支持HttpClient()，我暂时也不清楚如何寻找其他的测试方法，请告知。

**Comment by Lillls** [comment]
我遇到了同样的问题，服务端在1s内收到了大量的请求，请问最新的版本这个issue修复了吗
