### ISSUE TITLE
Handling unexpected Content-Type in responses

### ISSUE THREAD

**Issue by edwardaux** [flutterchina/dio#737]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | 2.6.0                              |      |
| Dio Version                    | 3.0.9                                  |      |
| Android Studio / Xcode Version | VS Code              |      |
| Repro rate                     | 100%  |      |
| Repro with our demo prj        | N/A            |      |
| Demo project link              | N/A |      |

### Issue Description and Steps
Sadly, not all APIs return `Content-Type = application/json`. When this happens, Dio throws the following unhelpful error:
```
"type 'String' is not a subtype of type 'Map<String, dynamic>'"
```
After a lot of mucking around, I finally figured out that unless the returned content type is `application/json`, Dio just returns the utf-8 decoded String.

While this may be "technically" correct, unfortunately we don't all have the ability to change the server behaviour. I can see that there's been a few others that have stumbled across this error in the past (and I can see there's a PR #599 that hasn't been merged).

While the PR I mentioned above is a good attempt, it is still a closed solution in that it won't help for other content types that aren't in its list. If I might suggest a solution, you could add another property to the `RequestOptions` called something like `assumeAllResponsesAreJSON`.

In any case, here's how I managed to work around it in case other folks have the same challenges I face:

```
class AlwaysJSONTransformer extends DefaultTransformer {
  @override
  Future transformResponse(RequestOptions options, ResponseBody response) {
    response.headers['content-type'] = ['application/json'];
    return super.transformResponse(options, response);
  }
}

let dio = Dio(...);
dio.transformer(AlwaysJSONTransformer());
```

**Comment by amondnet** [comment]
@edwardaux #599 This pr covers most json [media types](https://en.wikipedia.org/wiki/Media_type).  

(https://www.iana.org/assignments/media-types/media-types.xhtml). 
```dart
final mediaType = MediaType.parse(contentType);
return mediaType.type == "application" && mediaType.subtype.contains("json");
```
Only one of the media types registered in iana,`model/gltf+json`, cannot be processed. In order to cover all json types, `media subtype` need to be checked.
```dart
final mediaType = MediaType.parse(contentType);
return mediaType.subtype.contains("json"); // or RegExp(r'\+?json')
```

**Comment by edwardaux** [comment]
Your PR does indeed handle a bunch of cases where the server is returning a sensible media type.

However, there are /many/ servers that return a custom media type (if they have their own scheme), or `text/plain`, or whatever (I've even seen some API servers return JSON with `text/html`). Your PR won't assist in any of these cases.

The feature I'm requesting is an easier way for the developer to tell Dio that it should try to parse the returned data as JSON.

**Comment by HemlockBane** [comment]
Still here in 2022
