### ISSUE TITLE
HTT2 adptor never work

### ISSUE THREAD

**Issue by virskor** [flutterchina/dio#738]
### New Issue Checklist

flutter: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).
flutter: onError: DioError [DioErrorType.DEFAULT]: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
DIO version: 3.0.9
Http2Adaptor 1.0

[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.18.0 at /Users/virs/flutter
    • Framework revision 8f7327f83a (6 天前), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/virs/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • iPhone 11  • 967776AF-A12B-4CAA-ACDF-F2D3A2177D76 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome     • chrome                               • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

### Issue Description and Steps

Almost all request return this error when using Http2Adptor

```dart
_dio.httpClientAdapter = Http2Adapter(
        ConnectionManager(
          idleTimeout: BuildInfo().info().idleTimeout, /// 15000

          /// Ignore bad certificate
          onClientCreate: (_, clientSetting) => clientSetting.onBadCertificate =
              (_) => BuildInfo().info().onBadCertificate, /// true
        ),
      );
```

HTTP2 OPENED ON SERVER SIDE.

ALL RESPONSE GOT:

flutter: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).
flutter: onError: DioError [DioErrorType.DEFAULT]: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).

**Comment by virskor** [comment]
ALL PLATFORM CONTAINS THIS PROBLEM

**Comment by LHWen** [comment]
Have you solved it? I met it, too

**Comment by virskor** [comment]
@LHWen  No, but DIO add uppercases on request header may cause this problem, we can not event modify this headers automatically added. LOL

**Comment by LHWen** [comment]
header be set all lowercase, or not set header. That's what happens.😅💔

**Comment by hongyiweiwu** [comment]
#760
