### ISSUE TITLE
上传大文件时会出现CONNECT_TIMEOUT

### ISSUE THREAD

**Issue by heyman0823** [flutterchina/dio#739]
上传文件时，我设置的connectTimeout = 10s
上传时间超过10秒就会CONNECT_TIMEOUT，但实际建立连接没有超时
定位问题发现是request.close();超时
看实现是不是把上传文件的时间也算到了connectTimeout里？

    Future future = request.close();
    if (options.connectTimeout > 0) {
      future = future.timeout(Duration(milliseconds: options.connectTimeout));
    }
    HttpClientResponse responseStream;
    try {
      responseStream = await future;
    } on TimeoutException {
      _throwConnectingTimeout();
    }

**Comment by thestarmaker** [comment]
Hi guys, sorry my Chinese is limited to Google Translate, but it seems I am also having the same issue. When I am uploading 1.5 MB file (to Google Storage in my case) I am getting CONNECT_TIMEOUT exception even when upload succeeds. I am also getting this pretty consistently.

The upload code is quite simple:
```
await _dio.put("/some/upload/url",
        data: file.readAsBytesSync(),
        options: Options(
          //10 minutes
          sendTimeout: 600000
        )
      );
```

I have also tried setting larger timeout to base Dio options:
```
//10 minutes
dio.options.connectTimeout = 600000;
dio.options.receiveTimeout = 600000;
dio.options.sendTimeout = 600000;
``` 
The upload itself actually succeds as I can see the uploaded files on the server and the file is healthy (not corrupted).

The exception stacktrace:
```
#0      DioMixin._dispatchRequest (package:dio/src/dio.dart:963:7)
<asynchronous suspension>
#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
#3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#5      _rootRun (dart:async/zone.dart:1180:38)
#6      _CustomZone.run (dart:async/zone.dart:1077:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#9      _rootRun (dart:async/zone.dart:1184:13)
#10     _CustomZone.run (dart:async/zone.dart:1077:19)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
#12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
