### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by H-Mongo** [flutterchina/dio#740]
在使用dio的post提交数据时，答应了下面的错误信息：
* url中，带有http://协议头，
* options:  Options(contentType: "application/x-www-form-urlencoded")也加上了，
* data为Map<String,dynamic>类型

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Only valid value is 0: 1
E/flutter ( 1632): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
E/flutter ( 1632): #1      RequestOptions.uri (package:dio/src/options.dart:301:29)
E/flutter ( 1632): #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:35:72)
E/flutter ( 1632): #3      DioMixin._dispatchRequest (package:dio/src/dio.dart:919:46)
E/flutter ( 1632): <asynchronous suspension>
E/flutter ( 1632): #4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)       
E/flutter ( 1632): #5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1118:22)
E/flutter ( 1632): #6      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter ( 1632): #7      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter ( 1632): #8      _rootRun (dart:async/zone.dart:1122:38)
E/flutter ( 1632): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 1632): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 1632): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 1632): #12     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 1632): #13     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 1632): #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter ( 1632): #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 1632): #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter ( 1632): #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter ( 1632): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 1632):
E/flutter ( 1632): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:963:7)
E/flutter ( 1632): <asynchronous suspension>
E/flutter ( 1632): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)       
E/flutter ( 1632): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1118:22)
E/flutter ( 1632): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter ( 1632): #4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter ( 1632): #5      _rootRun (dart:async/zone.dart:1122:38)
E/flutter ( 1632): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 1632): #7      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 1632): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 1632): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 1632): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 1632): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter ( 1632): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 1632): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter ( 1632): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter ( 1632): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 1632):

**Comment by massilva** [comment]
@H-Mongo how did you fix it ?

**Comment by SandroMaglione** [comment]
@massilva [here](https://github.com/flutterchina/dio/issues/700#issuecomment-605402517)
