### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: HttpException: Invalid proxy configuration PROXY http:

### ISSUE THREAD

**Issue by nufeng74** [flutterchina/dio#742]
DioError [DioErrorType.DEFAULT]: HttpException: Invalid proxy configuration PROXY http:

**Comment by leqiang222** [comment]
> XY http:

@nufeng74 hi，老哥！Do you know how to solve this exception？

**Comment by nufeng74** [comment]
> > XY http:
> 
> @nufeng74 hi，老哥！Do you know how to solve this exception？
弃用
