### ISSUE TITLE
Flutter Web read cookies

### ISSUE THREAD

**Issue by incon** [flutterchina/dio#745]
I'm wanting to read a cookie. A system I'm working with requires me to read a cookie value and return it as a HTTP header to prevent CSRF.  It appears there is currently no way to get the cookie value from the response when using the web platform.

**Comment by incon** [comment]
I ended up using `'dart:html'` to read browser cookies.

**Comment by renittobb** [comment]
> I ended up using `'dart:html'` to read browser cookies.

can you please share the code snippet for that? I tried to read like following but the response was empty. Able to see the set-cookie value in my chrome network tab.

```
import 'dart:html';
var cookies = document.cookie;
 var cookies = html.window.document.cookie;
        log('Cookie Data: $cookies');
```

**Comment by Luro02** [comment]
In case someone else is searching for a solution:

Using `dart:html` is suboptimal, because then it will not work with non-web platforms like android. Instead add the `universal_html` dependency and then one can read cookies with:
```dart
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:universal_html/html.dart' show document;

String? readWebCookie(String name) {
  if (!kIsWeb) {
    return null;
  }

  String cookies = document.cookie ?? "";
  for (String value in cookies.isNotEmpty ? cookies.split(";") : []) {
    List<String> map = value.split("=");
    String key = map[0].trim();
    if (name == key) {
      return map[1].trim();
    }
  }

  return null;
}
```
