### ISSUE TITLE
网络断开的时候 dio拦截器没有拦截到异常而是抛了一个异常

### ISSUE THREAD

**Issue by DNetORM** [flutterchina/dio#748]
SocketException: Connection failed (OS Error: Network is unreachable, errno = 101)

![image](https://user-images.githubusercontent.com/32695729/79713996-0bd67a00-8302-11ea-877b-c0d52eb555b8.png)

  dio.interceptors
        .add(InterceptorsWrapper(onRequest: (RequestOptions options) async {
      return options; //continue
    }, onResponse: (Response response) async {
      return response; // continue
    }, onError: (DioError e) async {
      if (e.type == DioErrorType.DEFAULT) {}
      if (e.type == DioErrorType.CONNECT_TIMEOUT) {

拦截器这里为啥没有拦截到

**Comment by jackandjack** [comment]
我也遇到这个问题
