### ISSUE TITLE
为什么拦截器里拦截不到异常呢？

### ISSUE THREAD

**Issue by DNetORM** [flutterchina/dio#749]
![image](https://user-images.githubusercontent.com/32695729/79720015-58c24c80-8312-11ea-8d5c-32f7ffe4b54a.png)

   throw assureDioError(e, options);会抛出异常！

      checkCancelled(cancelToken);
      if (statusOk) {
        return checkIfNeedEnqueue(interceptors.responseLock, () => ret);
      } else {
        throw DioError(
          response: ret,
          error: 'Http status error [${responseBody.statusCode}]',
          type: DioErrorType.RESPONSE,
        );
      }
    } catch (e) {
      throw assureDioError(e, options);
    }
  }

**Comment by scofield-hello** [comment]
解决了吗？我也遇到相同问题了

**Comment by amou-zeng** [comment]
同问，没有任何办法捕捉到错误！！！！

**Comment by GustavoFigueira** [comment]
Same here! **Can't** capture DioError.

**Comment by bladeofgod** [comment]
在future后 加上.catchError就可以，但是这个不是我想要的，外层try{}catch依然不可以（可以捕捉到自己抛的，但是dio的就不行），不知道为何。

**Comment by asjqkkkk** [comment]
这个问题到现在都没有被解决，为什么直接关闭了
