### ISSUE TITLE
Get Fails With No Delay Before

### ISSUE THREAD

**Issue by eopeter** [flutterchina/dio#75]
Why does this fail (with not await before)
-------------------
Response<List> response = await dio.get("$baseRoute/clients");
      var list = response.data;
      for (var item in list) {
        clients.add(ClientModel.fromJson(item));
      }

And this Works (has an async function before)
-----------------
// Delay
await SomeCodeAsync();

Response<List> response = await dio.get("$baseRoute/clients");
      var list = response.data;
      for (var item in list) {
        clients.add(ClientModel.fromJson(item));
      }

**Comment by wendux** [comment]
`await` must be used  inside `async`  function . could you paste the full code?


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by eopeter** [comment]
I am no longer using this package as it is has more issues than using the httpClient in Dart directly. Requests that work fine using the httpClient fails with Dio.
