### ISSUE TITLE
Flutter Web - XMLHttpRequest error

### ISSUE THREAD

**Issue by cankarabag** [flutterchina/dio#750]
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter web                          |      |
| Platform Version               | 1.12.13+hotfix.9                              |      |
| Dio Version                    | 3.0.9                                 |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      

```
Future<Response> get({
    String innerPath = "",
    CancelToken cancelToken,
    Map<String, String> queryParameters = const {},
  }) async {
    try {
      final response = await _client.get(
        "/$_path/$innerPath",
        cancelToken: cancelToken,
        queryParameters: queryParameters,
      );
      throwIfNoSuccess(response);
      return response;
    } catch (e) {
      throw e;
    }
  }
```

It works on Android and iOS side. I get this error on the flutter-web.

Request path : [GET] 'A url to make get request'
Request data : null
Error message : XMLHttpRequest error.
DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.

**Comment by wpajqz** [comment]
the same for me

**Comment by d-apps** [comment]
I had the problem, I add this in my site (index.php) and it worked.

header("Access-Control-Allow-Origin: *");

**Comment by cankarabag** [comment]
No, still same problem.

**Comment by azalisa** [comment]
@cankarabag Did you check the browser console for errors? I searched the dio source code for this error, and I found this:
```dart
// Unfortunately, the underlying XMLHttpRequest API doesn't expose any
// specific information about the error itself.
completer.completeError(
  ClientException('XMLHttpRequest error.', request.url),
  StackTrace.current);
```
So dio itself can't print a more helpful error message, but it will get logged in the browser console.

**Comment by johnathanbreshears** [comment]
Has anyone found what the fix for this might be?

**Comment by a-elhaddad** [comment]
Has anyone found solution?

**Comment by blue7wings** [comment]
Same problem here, I maybe will give up to use Dio if the issue not fixed. so sad...

**Comment by blue7wings** [comment]
Hey, Dio does not work on the web may because CORS which not appear in APP. I fixed the problem by adding this in response's header.
``` "Access-Control-Allow-Origin": "*", // Required for CORS support to work
  "Access-Control-Allow-Credentials": true, // Required for cookies, authorization headers with HTTPS
  "Access-Control-Allow-Headers": "Origin,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
```

**Comment by leononly** [comment]
> Hey, Dio does not work on the web may because CORS which not appear in APP. I fixed the problem by adding this in response's header.
> 
> ```
>   "Access-Control-Allow-Credentials": true, // Required for cookies, authorization headers with HTTPS
>   "Access-Control-Allow-Headers": "Origin,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
>   "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
> ```

Does this means dont use dio?

**Comment by cankarabag** [comment]
The solution that I found is do not use Dio on web.

**Comment by jtoy** [comment]
I have the exact same issue, works perfectly fine on mac and ios.

**Comment by srinivasPaidisetti** [comment]
same issue

**Comment by gittycoder02** [comment]
Encountering same issue

**Comment by songsongtao** [comment]
same issue

**Comment by MoshDev** [comment]
have the same issue, i had to add:
```
        httpServletResponse?.setHeader("Access-Control-Allow-Origin", "*")
        httpServletResponse?.setHeader("Access-Control-Allow-Headers", "*")
        httpServletResponse?.setHeader("Access-Control-Allow-Methods", "*")
        httpServletResponse?.setHeader("Access-Control-Allow-Credentials", "true")
```
to make it work, haven't tested it yet on production as im working on development environment for now

**Comment by shinsenter** [comment]
Works well with `GET` requests, but error with `POST`. It says browser should make a `preflight` request before `POST`.

**Comment by sedhha** [comment]
Did someone solve this problem? :(

**Comment by sedhha** [comment]
> > Hey, Dio does not work on the web may because CORS which not appear in APP. I fixed the problem by adding this in response's header.
> > ```
> >   "Access-Control-Allow-Credentials": true, // Required for cookies, authorization headers with HTTPS
> >   "Access-Control-Allow-Headers": "Origin,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
> >   "Access-Control-Allow-Methods": "GET, POST, OPTIONS"
> > ```
> 
> Does this means dont use dio?

Doesn't work with any other http libraries as well.

**Comment by sedhha** [comment]
> Info	Value	
> Platform Name	flutter web	
> Platform Version	1.12.13+hotfix.9	
> Dio Version	3.0.9	
> Repro with our demo prj	e.g. does it happen with our demo project?	
> ```
> Future<Response> get({
>     String innerPath = "",
>     CancelToken cancelToken,
>     Map<String, String> queryParameters = const {},
>   }) async {
>     try {
>       final response = await _client.get(
>         "/$_path/$innerPath",
>         cancelToken: cancelToken,
>         queryParameters: queryParameters,
>       );
>       throwIfNoSuccess(response);
>       return response;
>     } catch (e) {
>       throw e;
>     }
>   }
> ```
> 
> It works on Android and iOS side. I get this error on the flutter-web.
> 
> Request path : [GET] 'A url to make get request'
> Request data : null
> Error message : XMLHttpRequest error.
> DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.

For me get request works, it's only when I try to make a post request.

**Comment by Hannnes1** [comment]
I'm still experiencing this issue, and I assume others as well. Should I create a new one or should this be opened again?

**Comment by juzimmer** [comment]
I'm having similar issue on WEB. I've noticed that doing a post call like 
`var response = await dio.post(entryPoint + "getServicesExtras", data: {});` empty data it works.
 As soon as I do `var response = await dio.post(entryPoint + "getServicesExtras", data: {"token}: token); ` 

Also tried encoding body.

it throws: 

`Error: DioError [DioErrorType.response]: XMLHttpRequest error.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28   get current
packages/dio/src/dio_mixin.dart 819:20                                                                            assureDioError
packages/dio/src/dio_mixin.dart 678:13                                                                            _dispatchRequest
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1618:54                                 runBinary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 169:20                           handleError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 719:46                           handleError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 740:13                           _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 550:5                            [_completeError]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 606:7                            callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15  <fn>

    at Object.throw_ [as throw] (http://localhost:65368/dart_sdk.js:5048:11)
    at http://localhost:65368/packages/dio/src/interceptors/log.dart.lib.js:1243:21
    at _RootZone.runBinary (http://localhost:65368/dart_sdk.js:37263:59)
    at _FutureListener.catchError.handleError (http://localhost:65368/dart_sdk.js:32525:48)
    at handleError (http://localhost:65368/dart_sdk.js:33058:51)
    at Function._propagateToListeners (http://localhost:65368/dart_sdk.js:33084:17)
    at _Future.new.[_completeError] (http://localhost:65368/dart_sdk.js:32934:23)
    at _SyncCompleter.new.[_completeError] (http://localhost:65368/dart_sdk.js:32446:36)
    at _SyncCompleter.new.completeError (http://localhost:65368/dart_sdk.js:32373:29)
    at onError (http://localhost:65368/dart_sdk.js:32224:49)
    at _RootZone.runBinary (http://localhost:65368/dart_sdk.js:37263:59)
    at _FutureListener.then.handleError (http://localhost:65368/dart_sdk.js:32525:48)
    at handleError (http://localhost:65368/dart_sdk.js:33058:51)
    at Function._propagateToListeners (http://localhost:65368/dart_sdk.js:33084:17)
    at _Future.new.[_completeError] (http://localhost:65368/dart_sdk.js:32934:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:65368/dart_sdk.js:32970:31)
    at Object._microtaskLoop (http://localhost:65368/dart_sdk.js:37511:13)
    at _startMicrotaskLoop (http://localhost:65368/dart_sdk.js:37517:13)
    at http://localhost:65368/dart_sdk.js:33288:9
`

**Comment by Hannnes1** [comment]
Okay, so I have finally found a solution. Some people have found the same solution, but they didn't provide any detailed solutions.

The problem can be solved by enabling [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) on the server Dio is sending requests to. In my case i use a NodeJS server with express and for me it was as simple as using the [cors package](https://www.npmjs.com/package/cors). If you use something else, you can manually add these headers to the response from the server:

```
'Access-Control-Allow-Origin': '*'
'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, PATCH, DELETE' // If needed
'Access-Control-Allow-Headers': 'X-Requested-With,content-type' // If needed
'Access-Control-Allow-Credentials': true // If  needed
```

**Comment by AlexMeuer** [comment]
It's worth noting that, for production deployments, the `Access-Control-Allow-Origin` header should be set to wherever you're hosting the frontend. The wildcard `*` allows browser requests from anywhere, potentially opening you up to phishing attacks or worse.

When debugging Dio for Web, it's often simpler to just ignore the Dio error and check the Network tab in Dev Tools first. You'll be able to see info that Dio doesn't have access to.

**Comment by firestormza** [comment]
Good day all,

Testing Dio. With this simple code I get the same error. Can anyone please explain why?
```dart
  Future<void> onPressed() async {
     var dio = new Dio();
     try {
       final response = await dio.get("https://www.google.com");
       print(response.data);
     } catch (e) {
       print("WTF: $e");
     }
  }
```

**Comment by brunodmn** [comment]
this worked for me:
[https://stackoverflow.com/a/66879350/9914638](https://stackoverflow.com/a/66879350/9914638)

**Comment by flutterq2** [comment]
All Possible Working Solution Added [[Solved] Error getting sensor data: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.](https://fluttercorner.com/error-getting-sensor-data-dioerror-dioerrortype-response-xmlhttprequest-error/)

**Comment by Sarah-ben** [comment]
> httpServletResponse?.setHeader("Access-Control-Allow-Origin", "*")
>         httpServletResponse?.setHeader("Access-Control-Allow-Headers", "*")
>         httpServletResponse?.setHeader("Access-Control-Allow-Methods", "*")
>         httpServletResponse?.setHeader("Access-Control-Allow-Credentials", "true")

hello @lwabish , where did u put this ? in flutter side or api side?

**Comment by Hannnes1** [comment]
> > httpServletResponse?.setHeader("Access-Control-Allow-Origin", "*")
> >         httpServletResponse?.setHeader("Access-Control-Allow-Headers", "*")
> >         httpServletResponse?.setHeader("Access-Control-Allow-Methods", "*")
> >         httpServletResponse?.setHeader("Access-Control-Allow-Credentials", "true")
> 
> hello @lwabish , where did u put this ? in flutter side or api side?

@Sarah-ben That should be on the API side.

**Comment by Sarah-ben** [comment]
> > > httpServletResponse?.setHeader("Access-Control-Allow-Origin", "_")
> > > httpServletResponse?.setHeader("Access-Control-Allow-Headers", "_")
> > > httpServletResponse?.setHeader("Access-Control-Allow-Methods", "*")
> > > httpServletResponse?.setHeader("Access-Control-Allow-Credentials", "true")
> > 
> > 
> > hello @lwabish , where did u put this ? in flutter side or api side?
> 
> @Sarah-ben That should be on the API side.

 hello @Hannnes1  , did u faced this problem before? and how did u reselve it cuz i tried most solution but nothing worked for m

**Comment by Hannnes1** [comment]
> > > > httpServletResponse?.setHeader("Access-Control-Allow-Origin", "_")
> > > > httpServletResponse?.setHeader("Access-Control-Allow-Headers", "_")
> > > > httpServletResponse?.setHeader("Access-Control-Allow-Methods", "*")
> > > > httpServletResponse?.setHeader("Access-Control-Allow-Credentials", "true")
> > > 
> > > 
> > > hello @lwabish , where did u put this ? in flutter side or api side?
> > 
> > @Sarah-ben That should be on the API side.
> 
>  hello @Hannnes1  , did u faced this problem before? and how did u reselve it cuz i tried most solution but nothing worked for m

@Sarah-ben Yes, I have faced it before. Se my previous comment for the solution I used: https://github.com/flutterchina/dio/issues/750#issuecomment-830574911.

The exact solution will of course depend on your backend.

**Comment by Sarah-ben** [comment]
> > > > > httpServletResponse?.setHeader("Access-Control-Allow-Origin", "_")
> > > > > httpServletResponse?.setHeader("Access-Control-Allow-Headers", "_")
> > > > > httpServletResponse?.setHeader("Access-Control-Allow-Methods", "*")
> > > > > httpServletResponse?.setHeader("Access-Control-Allow-Credentials", "true")
> > > > 
> > > > 
> > > > hello @lwabish , where did u put this ? in flutter side or api side?
> > > 
> > > 
> > > @Sarah-ben That should be on the API side.
> > 
> > 
> > hello @Hannnes1  , did u faced this problem before? and how did u reselve it cuz i tried most solution but nothing worked for m
> 
> @Sarah-ben Yes, I have faced it before. Se my previous comment for the solution I used: [#750 (comment)](https://github.com/flutterchina/dio/issues/750#issuecomment-830574911).
> 
> The exact solution will of course depend on your backend.

am using laravel for API

**Comment by Hannnes1** [comment]
@Sarah-ben You are most likely seeing the error because CORS is not working on the server. I have never used laravel, but a quick Google search gave me this middleware: https://github.com/fruitcake/laravel-cors. Try installing that and see if that helps

**Comment by Sarah-ben** [comment]
> header("Access-Control-Allow-Origin: *");

did u use lravel?

**Comment by Hannnes1** [comment]
> > header("Access-Control-Allow-Origin: *");
> 
> did u use lravel?

As I said in my comment above, I have never used Laravel

**Comment by wechulimaven** [comment]
I was hitting into this problem. After a quite research .I just found a solution to this:
1. Go to `flutter\bin\cache`, then remove `flutter_tools.stamp`
2. Go to `flutter\packages\flutter_tools\lib\src` 
3. Open a file `chrome.dart`,   find `'--disable-extensions'`
4. and replace it with `--disable-web-security`
5.  save and close

_HAPPY CODING_

**Comment by udroi** [comment]
> Okay, so I have finally found a solution. Some people have found the same solution, but they didn't provide any detailed solutions.
> 
> The problem can be solved by enabling [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) on the server Dio is sending requests to. In my case i use a NodeJS server with express and for me it was as simple as using the [cors package](https://www.npmjs.com/package/cors). If you use something else, you can manually add these headers to the response from the server:
> 
> ```
> 'Access-Control-Allow-Origin': '*'
> 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, PATCH, DELETE' // If needed
> 'Access-Control-Allow-Headers': 'X-Requested-With,content-type' // If needed
> 'Access-Control-Allow-Credentials': true // If  needed
> ```

installing CORS on node worked for me..thank you for that

**Comment by YawarOsman** [comment]
> I was hitting into this problem. After a quite research .I just found a solution to this:
> 
> 1. Go to `flutter\bin\cache`, then remove `flutter_tools.stamp`
> 2. Go to `flutter\packages\flutter_tools\lib\src`
> 3. Open a file `chrome.dart`,   find `'--disable-extensions'`
> 4. and replace it with `--disable-web-security`
> 5. save and close
> 
> _HAPPY CODING_

I don't have chrome.dart file

**Comment by Rest00rer** [comment]
> 

me too

**Comment by humanolaranja** [comment]
> I was hitting into this problem. After a quite research .I just found a solution to this:
> 
>     1. Go to `flutter\bin\cache`, then remove `flutter_tools.stamp`
> 
>     2. Go to `flutter\packages\flutter_tools\lib\src`
> 
>     3. Open a file `chrome.dart`,   find `'--disable-extensions'`
> 
>     4. and replace it with `--disable-web-security`
> 
>     5. save and close
> 
> 
> _HAPPY CODING_

This just solves the problem locally, when doing `flutter build web` the problem go backs

**Comment by hgdphg** [comment]
i had same problem, but not work iOS-web and still work with window-web
