### ISSUE TITLE
when upload a big file use multipart form, the memory grow fast and OOM（用multipart 方式上传文件，内存暴涨）

### ISSUE THREAD

**Issue by binghan-iOS** [flutterchina/dio#758]
dio version：3.0.0
test platform：simulator  iPhone11 pro max（13.4）
flutter version：1.17

client code（dart ）：
 var dir=(await getApplicationDocumentsDirectory()).path;
        final videoName = dir+'/OSX10.15.2.dmg'; 
         final txtName = dir+'/file.txt'; 
       // var imgFile = File(filename);
      // Sending stream
       var fm = FormData.fromMap({
      'name': 'wendux',
      'age': 25,
      'file': MultipartFile.fromString('hellow world.'),
      'files': [
        await MultipartFile.fromFile(videoName,
            filename: 'OSX10.15.2.dmg'),
        MultipartFile.fromFileSync(txtName, filename: 'file.txt'),
      ]
    });

        await dio.post(
    "http://localhost:8080/upload",
      data: fm, // Post with Stream<List<int>>
    options: Options(
      headers: {
        HttpHeaders.contentTypeHeader: ContentType.binary,
       
       
       // HttpHeaders.contentLengthHeader: imgFile.lengthSync(),
       // HttpHeaders.authorizationHeader: "Bearer $token",
      },
    ),
  ).catchError(print);
          
server code（go）：
package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
)

func uploadHandler(w http.ResponseWriter, r *http.Request) {

	reader, err := r.MultipartReader()

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	for {
		part, err := reader.NextPart()
		if err == io.EOF {
			break
		}

		fmt.Printf("FileName=[%s], FormName=[%s]\n", part.FileName(), part.FormName())
		if part.FileName() == "" { // this is FormData
			data, _ := ioutil.ReadAll(part)
			fmt.Printf("FormData=[%s]\n", string(data))
		} else { // This is FileData
			dst, _ := os.Create("./" + part.FileName() + ".upload")
			defer dst.Close()
			io.Copy(dst, part)
		}
	}
}

func main() {
	http.HandleFunc("/upload", uploadHandler)
	http.ListenAndServe(":8080", nil)
}

**Comment by 100cm** [comment]
你内存能够读几个g....

**Comment by binghan-iOS** [comment]
> 你内存能够读几个g....

我在模拟器上测试的，正常的话上传文件上分块读的。http库上传文件就不会内存爆掉

**Comment by majingAragon** [comment]
最后怎么解决的？我上传视频文件的时候也遇到out of memory报错了

**Comment by cchamm** [comment]
這個有解決辦法嗎 ？
