### ISSUE TITLE
PUt提交Stream，并且使用了onsendProgress+provider，速度严重损耗

### ISSUE THREAD

**Issue by jol5** [flutterchina/dio#759]
感谢作者哟！
我有个问题呢？
问1：
使用PUT Stream且监听提交速率；
provider+1%的局部更新进度条

结果：
会存在很大的性能损耗；且和监听的操作长短和页面更新平率成正比。
如上传速度瞬间降低90%，页面变卡。。

问2：
不知道有什么好法子做一个流畅的上传进度。。。emmm

**Comment by nekomiyaxneko** [comment]
可以尝试一下每10%更新一次，更新时做一个动画让他看起来没那么违和感。
我在PUT的时候，设置的onSendProgress 不起作用 ，不知道是为什么。

**Comment by jol5** [comment]
需要指定content-length,才会调用onSendProgress的，作者底层有判断，这是个坑。
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lllinux"<notifications@github.com&gt;; 
发送时间: 2020年5月12日(星期二) 晚上11:04
收件人: "flutterchina/dio"<dio@noreply.github.com&gt;; 
抄送: "Jol."<790860872@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [flutterchina/dio] PUt提交Stream，并且使用了onsendProgress+provider，速度严重损耗 (#759)





 
可以尝试一下每10%更新一次，更新时做一个动画让他看起来没那么违和感。
 我在PUT的时候，设置的onSendProgress 不起作用 ，不知道是为什么。

**Comment by nekomiyaxneko** [comment]
好的，感谢
