### ISSUE TITLE
Problem when request "localhost".

### ISSUE THREAD

**Issue by Mythar** [flutterchina/dio#76]
If i make a dio call like: http://127.0.0.1:8001, i get a dio error:

DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 45818

Dose dio not support port numbers ? - only a problem on localhost ?

**Comment by RichardLindhout** [comment]
Same problem with: http://192.168.178.28:8080
Connection refused, errno = 111, address = 192.168.178.28, port = 48180

**Comment by RichardLindhout** [comment]
Same problem with normal http.post.. Looks like it has something to do with security for non-https urls.

**Comment by RichardLindhout** [comment]
Fixed it on my android device with running `adb reverse tcp:8080 tcp:8080`

**Comment by RichardLindhout** [comment]
@Mythar when you run `adb reverse tcp:8080 tcp:8080` you can connect to localhost on your device it proxies your request to your local webserver 👍

**Comment by zhongmeizhi** [comment]
> @Mythar when you run `adb reverse tcp:8080 tcp:8080` you can connect to localhost on your device it proxies your request to your local webserver 👍

thanks。谢谢

**Comment by NianyiYang** [comment]
> @Mythar when you run `adb reverse tcp:8080 tcp:8080` you can connect to localhost on your device it proxies your request to your local webserver 👍

thanks a lot. it's really helpful!

**Comment by Alii-Rabee** [comment]
how can i run adb reverse tcp:8080 tcp:8080 please?

**Comment by Syed-Waleed-Shah** [comment]
> how can i run adb reverse tcp:8080 tcp:8080 please?

hey my friend dont run any thing.... if your api is running on localhost lets say http://127.0.0.1:5000/api/users then in the flutter code you have to write http://10.0.2.2:5000/api/users  ..... and you will be able to access your api. For more details read this artice : https://medium.com/@podcoder/connecting-flutter-application-to-localhost-a1022df63130

**Comment by b-codex** [comment]
Create a mobile hotspot
connect ur PC
open cmd and get the ipv4 of your PC
replace localhost with the ip you got by running ipconfig on cmd
