### ISSUE TITLE
Http2Adapter will not receive the full response

### ISSUE THREAD

**Issue by posativ** [flutterchina/dio#762]
This is an appendum to #317 with a 100% reproducible test file and also a fix, that worked at least for me.

### Issue Info

| Info                           | Value                                                 |
| ------------------------------ | ----------------------------------------------------- 
| Platform Name                  | Dart VM
| Platform Version               | 2.7.1
| Dio Version                    | 3.0.9, master  
| Repro rate                     | 100%   
| Repro with our demo prj        | yes           
| Demo project link              | see test file below 

### Issue Description and Steps

```
~> dart test.dart
Unhandled exception:
DioError [DioErrorType.DEFAULT]: FormatException: Unterminated string (at character 149204)
..."Nuss Makronen","Eierschwämmchen","Pilaw","Seeberger Soft-Aprikosen","Klein
                                                                              ^

#0      DioMixin._dispatchRequest (package:dio/src/dio.dart:963:7)
<asynchronous suspension>
#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
#3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12
```

The server is HTTP2 compatible and the backend correctly provides a Content-Length header. The received bytes is usually ~30-60 kilobytes less of what is expected. Total response size is around 200kb.

### Test file

```dart
import 'package:dio/dio.dart';
import 'package:dio_http2_adapter/dio_http2_adapter.dart';

void main() async {
  final dio = Dio()
    ..httpClientAdapter = Http2Adapter(ConnectionManager());

  await dio.get('https://au3.de/reduce-food-waste/ingredients/list');
}
```

### Possible fix

I've checked the example setup for `http2` (https://github.com/dart-lang/http2/blob/master/example/display_headers.dart) and noticed that this example worked fine.

After a few tries, I noticed that `http2_adapter` used `endStream: false`. With the original `true` value from the http2 example, the request is completely received.

**Comment by posativ** [comment]
I mean it is still an unfixed issue lol.

**Comment by shubhamhackz** [comment]
This issue is still reproducible in latest version, please try to prioritise it.

**Comment by mennovanhout** [comment]
still an issue

**Comment by kuhnroyal** [comment]
Please create a reproducible example.

**Comment by AlexV525** [comment]
The previous condition, either `endStream: false` or every provided link is outdated. We cannot proceed with outdated information. Please submit new issues if a new reproducible example works.
