### ISSUE TITLE
Issue with lowercase content-disposition in multipart form

### ISSUE THREAD

**Issue by pmorenov** [flutterchina/dio#765]
### Issue Info

Platform Name - flutter
Platform version - 1.12.13+hotfix.9
Dio Version - 3.0.9

### Issue Description and Steps

I have a form multipart request that fails in the server with a 400 (Unable to get name from form-data). I've found the root cause:

The body contains the parts separated by 'boundaries':

>----dio-boundary-1767347126
>content-disposition: form-data; name="message"
>
>The message
>----dio-boundary-1767347126
>content-disposition: form-data; name="callback"
>
>false
>----dio-boundary-1767347126--

Probably related to [issue 641](https://github.com/flutterchina/dio/issues/641), the 'content-disposition' tags are sent in lowercase. 

Inspecting this request with CharlesProxy and changing content-disposition to Content-Disposition results in the server returning a 200 as expected.

So the body should be:

>----dio-boundary-1767347126
>Content-Disposition: form-data; name="message"
>
>The message
>----dio-boundary-1767347126
>Content-Disposition: form-data; name="preferCallBack"
>
>false
>----dio-boundary-1767347126--

**Comment by pmorenov** [comment]
The Mulesoft backend I'm working with expects 'Content-Disposition' to extract the fields:
https://help.mulesoft.com/s/article/Attachments-being-lost-in-a-Multipart-Mixed

**Comment by shaxxx** [comment]
Possible duplicate of https://github.com/flutterchina/dio/issues/641

**Comment by shaxxx** [comment]
Possible duplicate of https://github.com/flutterchina/dio/issues/641

**Comment by pmorenov** [comment]
Still an issue, please check the linked PR for a fix.

**Comment by abdulrojak288** [comment]
I got the same problem, is there a solution?

**Comment by abdulrojak288** [comment]
> Still an issue, please check the linked PR for a fix.

I got the same problem, is there a solution?

**Comment by orzzp** [comment]
I got the same problem, is there a solution?
