### ISSUE TITLE
一毛一样的代码 ，在手机上request 403, pc上正常 / Same code, request 403 on mobile, normal on pc

### ISSUE THREAD

**Issue by sewerganger** [flutterchina/dio#771]
#46 # Issue Info
[√] Flutter (Channel unknown, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.592],   
    locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

### Issue Description and Steps
可能是什么情况 / What could be the case
![image](https://user-images.githubusercontent.com/45007226/81078678-1c513c00-8f21-11ea-9df7-03c005d15808.png)

**Comment by Jay-57blocks** [comment]
请问这个问题解决了吗？
