### ISSUE TITLE
关于解决https 在ios 超时的问题

### ISSUE THREAD

**Issue by 100cm** [flutterchina/dio#786]
先自问自答：
### 1.  为什么出现这个问题？
答： OCSP Stapling 失效
### 2.  为什么IOS有问题，安卓没问题？
答： 因为谷歌不满意这个[方案](https://blog.wirelessmoves.com/2015/03/ocsp-stapling-and-android-that-doesnt-care.html)
### 3.  解决方案
  1.换证书
2.  
```
1. 使用 ssl_stapling_file 配置，从一个外部文件获取ocsp信息 ngx_ssl_stapling_file
2. 使用 ssl_stapling_responder配置，nginx会用这个设置覆盖证书里面的Authority Information Access信息，使得请求ocsp被发送到设置的服务器

这里推荐第二种，如果在多台机器上部署的话第一种比较麻烦
```
https://github.com/dlecorfec/ocsp-proxy 
 可以参考如下配置
```
ssl_stapling on;
ssl_stapling_verify on;
ssl_trusted_certificate /etc/ssl/ca-certs.pem;
ssl_stapling_responder http://YOUR_PROXY_IP:8080/; 
```
3. 如果是使用k8S + nginx-ingress 部署
这是我自己亲测的解决方式

首先将 nginx-ingress 更新到 [0.31+](https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md) 这里有相关的变动日志。关于部署的冲突可以自行判断。

4. 如果是使用k8S + traefik 部署
这个就要自己解决了😂

### 如何测试是否成功？

```
openssl s_client -connect ${host}:443 -servername ${host} -status -tlsextdebug < /dev/null 2>&1 | grep -i "OCSP response"
```

将其中的 `${host}` 改成自己的域名即可

```
OCSP response:
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
```
输出如上及说明已经解决了。

另外希望作者能够关注下我的另外一个formdata的问题。。不想自己本地改了。

**Comment by 100cm** [comment]
此情况目前测试下来是使用lets-encrypt的情况。

**Comment by v7lin** [comment]
docker swarm + traefik 已经哭晕在厕所了 ...

**Comment by 100cm** [comment]
> docker swarm + traefik 已经哭晕在厕所了 ...

建议换证书。。快捷。

**Comment by v7lin** [comment]
执行你的命令，返回是这样的是可以么？
```shell
OCSP response: no response sent
```

**Comment by v7lin** [comment]
另外发现一个完整可以测试域名证书的 https://www.immuniweb.com/ssl/?id=pg21dT3w

**Comment by 100cm** [comment]
不可以 正确的是我上面的

**Comment by v7lin** [comment]
我这边换了证书后，还是'no response sent'，iOS 13上已经不在卡了
```shell
OCSP response: no response sent
```

**Comment by openmynet** [comment]
按下面的配置修好 `OCSP Stapling` 后问题还是没有得到缓解
>  lets-encrypt 基于acme.sh
```nginx
server{
  listen 80;
  listen 443 ssl;
  ....
  ssl_certificate /var/.acme.sh/***/fullchain.cer;
  ...
  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_trusted_certificate /var/.acme.sh/***/ca.cer; # 与 fullchain.cer位于相同目录
  resolver 8.8.8.8 8.8.4.4 valid=86400s; # dns
  resolver_timeout 5s;
}
```
验证方法1. 按@100cm的
```
export host = ***.com
openssl s_client -connect ${host}:443 -servername ${host} -status -tlsextdebug < /dev/null 2>&1 | grep -i "OCSP response"

```
验证方法2：
https://certificate.revocationcheck.com/***.com

两种方法都测试通过了，但是没有缓解，似乎不是不仅仅是 OCSP Stapling 的问题
目前的情况暂时还不清楚是app的原因还好https的原因，情况有待测试

**Comment by kevinfujiang** [comment]
openssl ocsp -no_nonce -respout ./ocsp_resp.der  -issuer ./ca.cer  -cert ./mycom.cer -url http://ocsp.int-x3.letsencrypt.org/  -header "HOST" "ocsp.int-x3.letsencrypt.org"
获取ocsp响应： ocsp_resp.der 
然后配置到nginx上
ssl_stapling_file    /usr/local/nginx/conf/cert/ocsp_resp.der;
nginx 重启后可以验证通过。
