### ISSUE TITLE
关于响应Json的小问题

### ISSUE THREAD

**Issue by wanyt** [flutterchina/dio#79]
拦截服务器响应的时候，json数据是这样的：

{code: 10000, message: 成功, data: {smsId: 2018101114235542318000012, checkCode: 117665}}

code和10000的前后应该有冒号，应该像是这样的：

{
  "code": "10000",
  "message": "",
  "data": {
    "smsId": "201810101803293000000015",
    "checkCode": "087878"
  }
}

**Comment by wendux** [comment]
这个是没问题的，只不过输出的数据没有显示双引号。
Response的toString()方法实现如下
```
  @override
  String toString() => "[data]=" + data.toString();
```
如果data是Map或List的话，toString后输出就是没有双引号，但data数据是完成的。
