### ISSUE TITLE
Form key be changed when form value is List<MultipartFile>

### ISSUE THREAD

**Issue by wwtssu** [flutterchina/dio#792]
this is my code
Map form contain a key screenshots with datatype List\<File\>
```
form.forEach((k,v){
    if(v is File){
      form[k] = MultipartFile.fromFileSync(v.path,);
    }
    if(v is List<File>){
      List<MultipartFile> array = List();
      for(int i = 0; i < v.length; i++){
        if(v[i] == null) continue;
        array.add(MultipartFile.fromFileSync(v[i].path));
      }
      form[k] = array;
    }
  });
  print(form);
  FormData formData = FormData.fromMap(form);
  Dio dio = Dio();
  dio.post(url,data: formData,options: option);
```
it is print output text
![image](https://user-images.githubusercontent.com/57695674/82311762-b7094a80-99f8-11ea-9d80-6dfd90fe1ea8.png)

it is server received data
![image](https://user-images.githubusercontent.com/57695674/82311955-fcc61300-99f8-11ea-823a-9b9a9d936665.png)

form key screenshots be changed to screenshots[]

**Comment by mohamedahmedhassan00** [comment]
i olso have this issue with the same case
