### ISSUE TITLE
using dio with streams

### ISSUE THREAD

**Issue by heshesh2010** [flutterchina/dio#797]
Hi ,
i came from http package and i want to ask how to use streams like that :

Future<Stream<CarData>> getCars() async {
  UserDataUser _user = await getCurrentUser();
  Map<String, String> headers = {
    HttpHeaders.authorizationHeader:
        "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImNiMzlkYzQ1ZTNmZDkyOTliOTZhYjRlNzk5OWFkZWNhMDUxZmMyOWNlYjU1YmU4MDhlOWYwZGU3MWYwM2ZiZTk2Nzc5YzU1ZmQ5YjJlZjc2In0.eyJhdWQiOiIxIiwianRpIjoiY2IzOWRjNDVlM2ZkOTI5OWI5NmFiNGU3OTk5YWRlY2EwNTFmYzI5Y2ViNTViZTgwOGU5ZjBkZTcxZjAzZmJlOTY3NzljNTVmZDliMmVmNzYiLCJpYXQiOjE1ODk4MDA5ODEsIm5iZiI6MTU4OTgwMDk4MSwiZXhwIjoxNjIxMzM2OTgxLCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.f5XW3z8HhvjDhCiIcQvk_4iA6vKonGGaiuGIgdOD6qaEHhU9Rob_6xWG8GnpuMaw5oztcybCnLR1wVlw44sPvONv5ZwTMFywCvHoYZK4Rae60jWHkGS2kL6pf1SX86AhsUoJjNWO_xRZhXEvGi9pH7XL4Z1DQgXT2syKy8cYMWe9MRYEpYF0XaQs5UFzR8tuPPlDQ7g9qb2q4rE-88YtpjbWNxk77zmpXqZSEcGTCavIpgk9oqosSEBHT2PsCE0v1Lm4j2zslKodKmcZo5wRfF1tn26LzeFn3TH0a7miJF9eJ8GfhcIE5SvqSErY9wEhwj5vdQaWeBtCwOm4ZmDkdxSPOV7o-8ELAJVER-VPadiJHUgRC-ORldwZRQOy5biAyh8b-Sht6rJcBeQGrESnU4a-vHsLfo0GIqPGUQUFWDHiYauaVkqKi5Ow-qNTYY9S-UX1A0nDv3c4N4aV7rwIAWXQ3Rqv0AflGOKezOw2iTwE574WuG3cjt2xCjx8tE-f88HZe2JQDz10aMeGgI7Kp4_pxu5WIyVf-S_k7WxUbf0RoXA7nJ6sKXp1JKqJt8aO8PXU_g6tjDgQtXqkb0UkYLul1EnN4rfaDtEaWCudcozJa5Fwmccie1w4z4KiMgKlwmwXtVfE412UHTu1HOs3DpwlwGtoHooVZhyRGbrbkAE",
  };
  final String url = '${GlobalConfiguration().getString('api_base_url')}cars';

  final client = new http.Client();
  http.Request request =
      new http.Request("GET", Uri.parse(url)); // create get request
  http.StreamedResponse response = await client.send(request)
    ..headers.addAll(headers); // sends request and waits for response stream

  print(response.statusCode.toString());
  return response.stream
      .transform(utf8.decoder)
      .transform(json.decoder)
      .map((data) => Helper.getData(data))
      .expand((data) => (data as List))
      .map((data) {
    return carData.fromJson(data);
  });
}

**Comment by hongyiweiwu** [comment]
Since Dio’s http methods return Futures, you can just use Stream.fromFuture to convert it into a Stream.
