### ISSUE TITLE
list in query params encoding url bug

### ISSUE THREAD

**Issue by julek-kal** [flutterchina/dio#799]
### Issue Info

| Info                           | Value                                                 |      
| ------------------------------ | ----------------------------------------------------- | 
| Platform Name                  | flutter                      |     
| Platform Version               | 1.17.1                            |     
| Dio Version                    |3.0.9                                |     
| Repro rate                     |  all the time (100%)  |    

### Issue Description and Steps

When I send request with list of enums in queryParams 

(for example {'a' :1,'b': 2, color:[Colors.red, Colors.white]})

in URI query params i get "a=1&b=2&**color[]=RED&color[]=WHITE**"
the square brackets in key name isn't good
I think that urlEncode in utils.dart doesn't work properly

**Comment by frameset** [comment]
This seems to be the root cause of an issue I'm having with a library using dio. Hopefully your pull request gets merged. 👍
https://github.com/OpenAPITools/openapi-generator/issues/6681

**Comment by julek-kal** [comment]
still exist

**Comment by frameset** [comment]
Still an issue

**Comment by dalewking** [comment]
Thinking about it more Dio should not be adding the braces, it should be up to the user to put it on the query parameter name

**Comment by frameset** [comment]
Dale's last point is essentially my feeling on the matter.

**Comment by dalewking** [comment]
No, it did not magically go away

**Comment by frameset** [comment]
Not fixed

**Comment by frameset** [comment]
Not fixed.

**Comment by lyio** [comment]
> Thinking about it more Dio should not be adding the braces, it should be up to the user to put it on the query parameter name

I like this approach.

We are using DIO in Flutter and our backend API just changed the way they accept query params from the `?foo[]=bar&foo[]=baz` syntax to the `?foo=bar&foo=baz` syntax and we need a way to reflect that somehow.

But from what I gathered, there is no way to influence how DIO encodes the params at the moment, correct?

**Comment by julek-kal** [comment]
Yes, it's right. But this will change when  [#808](url) be merged

**Comment by jonasbark** [comment]
@julek-kal I tried the changes from your PR but I don't see how the PR will fix query parameters? They're still transmitted in an encoded format:
```
https://api.***/tasks/?maxResults=100&page=0&projectIds=%28402%29
```
instead of `projectIds=[120]`
I might be missing the point though.

**Comment by praveenkutta08** [comment]
Has the issue been resolved?

**Comment by af-the** [comment]
no 👎

**Comment by kuhnroyal** [comment]
There is an implementation for this available in the 4.0.0 beta that allows to configure the format for a whole request.

I think this needs to go further as I already found a case where the format for a query parameter is different from the `x-www-url-encoded` body format.
I have created a draft PR for discussion here: #1063

**Comment by kuhnroyal** [comment]
Thanks @wendux !

**Comment by keylinwu-wmg** [comment]
I had to add a function that works for a list of Enums in my special case that I needed  so I just called it from any Map
```
extension MapQueryParameterExtension on Map<String, dynamic> {
  Map<String, dynamic> addParameterWithArray({
    String parameterName,
    List<dynamic> elements,
  }) {
    final currentParameters = this;
    Map<String, dynamic> newValues = {};

    elements.asMap().forEach((index, element) {
      newValues[parameterName[index]] = element;
    });

    currentParameters.addAll(newValues);
    return currentParameters;
  }
}

```

this basically does what @lyio mentioned
 
```
parameterName[0] = element1
parameterName[1] = element2
parameterName[2] = element3
```
and it worked for me as a temporal solution

```
query
.addParameterWithArray(
          parameterName: 'types',
          elements: [1,2,3,4,5],
        )
```

**Comment by kuhnroyal** [comment]
If you are using the 4.0.0 preview version, then there is support for this. See https://github.com/flutterchina/dio/pull/1063

@wendux I think this issue can be closed now.
