### ISSUE TITLE
使用最基础的post方式报错问题，get正常

### ISSUE THREAD

**Issue by HeberLee** [flutterchina/dio#80]
## Steps to Reproduce

 Dio dio = new Dio();// 配置dio实例
    dio.options.baseUrl="https://36.2XX.94.241:1XXX65";
    FormData formData = new FormData.from({
    'token':token,
    'idCard':idCard,
    'name':realname,
    'seat':seatNum,
    'plateNum':plateNum,
    });

    Response data = await dio.post("/jihui/XXXXXXX!authCarOwner.action", data: formData);
    print(data);

## Logs
[ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 3451): DioError [DioErrorType.DEFAULT]: HandshakeException: Handshake error in client (OS Error: 
E/flutter ( 3451): 	WRONG_VERSION_NUMBER(tls_record.cc:242))
E/flutter ( 3451): #0      _OwnerVerifyPageState._ownerVerify (package:flutter_app_sidebar/pages/owner_verify_page.dart:71:21)
E/flutter ( 3451): <asynchronous suspension>
E/flutter ( 3451): #1      _OwnerVerifyPageState.build.<anonymous closure> (package:flutter_app_sidebar/pages/owner_verify_page.dart:367:25)
E/flutter ( 3451): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
E/flutter ( 3451): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
E/flutter ( 3451): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 3451): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 3451): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter ( 3451): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 3451): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter ( 3451): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 3451): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 3451): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 3451): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 3451): #13     _invoke1 (dart:ui/hooks.dart:142:13)
E/flutter ( 3451): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)

**Comment by HeberLee** [comment]
有人吗，麻烦看一下，万分感激

**Comment by wendux** [comment]
这貌似是Https链接建立不成功，你这个https服务或证书有问题吧

**Comment by kaisar420** [comment]
你们的问题解决了吗？ 我在代码里面写的也是http 不过还是不对
IOS模拟器能正常运行 不过安卓模拟器运行不了
`/**
   * Http 交互
   */
  void _httpClient() async {
    var url = "http://localhost:8082/iparhanSoft/user/register";
    await   http.post(url,body: {"username":phoneController.text,"password":passController.text}).then((response){
      print("post方式->status: ${response.statusCode}");
      print("post方式->body: ${response.body}");
      int result = int.parse(response.body);
      if(result == 20001){
        Navigator.push(context, new MaterialPageRoute(builder: (context) => MyHomePage()));
      }else{

      }
    });`
