### ISSUE TITLE
dio传json参数会被压扁,用前端axios测试传到后端是没问题的

### ISSUE THREAD

**Issue by saviourdog** [flutterchina/dio#800]
dio传json参数会被压扁,用前端axios测试传到后端是没问题的

**Comment by saviourdog** [comment]
![image](https://user-images.githubusercontent.com/22761043/82899668-f3572080-9f8d-11ea-9061-99f3611f0f21.png)

**Comment by saviourdog** [comment]
![image](https://user-images.githubusercontent.com/22761043/82904706-6b751480-9f95-11ea-9cf6-2565deccc685.png)

**Comment by 100cm** [comment]
这个问题我早就提过了。formdata的问题。作者就是不修。我本地改好了。你需要的话我截图发你

**Comment by saviourdog** [comment]
> 这个问题我早就提过了。formdata的问题。作者就是不修。我本地改好了。你需要的话我截图发你

谢谢大佬,代码多的话还是发代码方便copy啊

**Comment by Shrike-zjm** [comment]
> 这个问题我早就提过了。formdata的问题。作者就是不修。我本地改好了。你需要的话我截图发你

兄弟 我也遇到了FormData的问题 中文字符串的表单值在后台会被解析成文件...兄弟方便发一下解决方案吗 感谢

**Comment by Shrike-zjm** [comment]
>兄弟 我找到解决方案了 注释掉form_data.dart里面的四行之后就解决了
