### ISSUE TITLE
[Feature] Caching plugin for Flutter WEB

### ISSUE THREAD

**Issue by fvisticot** [flutterchina/dio#806]
Is there any DIO Plugin available to cache WEB requests with Flutter WEB ?
Current Cache Plugin is based on sqlite who is not Flutter WEB compatible yet.

**Comment by being-yash-t** [comment]
> Is there any DIO Plugin available to cache WEB requests with Flutter WEB ?
> Current Cache Plugin is based on sqlite who is not Flutter WEB compatible yet.

Did you get any solution to this?
