### ISSUE TITLE
上传文件的问题

### ISSUE THREAD

**Issue by leielyq** [flutterchina/dio#809]
最近更新到最新版，上传 文件就运行不正常了。
这是2.2.2版本写法，测试是可以的。
FormData formData = FormData.from({
      "file": UploadFileInfo(file, file.length().toString() + ".jpeg"),
      "effect": "topic"
    });
这是3.0.9版本的写法，测试之后后台无法接收到文件，能拿到effect的值
   FormData formData = FormData.fromMap({
      "effect": "topic"
    });
    formData.files.add(MapEntry("file", MultipartFile.fromFileSync(file.path,filename: 'nice.jpg')));
在设置dio.options.contentType = 'multipart/form-data';属性之后，本地测试是可以拿到值。

但是线上测试还是拿不到值。如果移除"effect": "topic"这个值，文件也是可以上传的。

唉，我不知道哪里写的不对

**Comment by liyang1518** [comment]
一样得问题，老哥怎么解决得

**Comment by dupengtao** [comment]
`    FormData formData = new FormData.fromMap({
      'files': await MultipartFile.fromFile(
        image.path,
        filename: name,
        contentType: MediaType.parse('image/$suffix'),
      ),
      'uuid': GlobalConfig().curPlatformConfig.uuid,
    });
    Dio dio = Dio();

    var response = await dio.post<String>(
        url,
        data: formData,
      );`


我这样写是可以上传 成功的

**Comment by vickyleu** [comment]
> 一样得问题，老哥怎么解决得

    "boundary="后面加formData的boundary,一次传几个formData就加几个boundary,拼接起来!!

    header["content-type"] = "multipart/form-data;boundary=${formData.boundary}";
    header["Content-Type"] = header["content-type"];
    header["Content-type"] = header["content-type"];
