### ISSUE TITLE
flutter web empty response header

### ISSUE THREAD

**Issue by mhalizadeh** [flutterchina/dio#811]
### New Issue Checklist

- 

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter web                      |      |
| Flutter Version               |  Channel beta, 1.18.0-11.1.pre, on Linux                              |      |
| Dio Version                    |  ^3.0.9|      |
| Android Studio / Xcode Version | Android Studio (version 4.0)  |      |
| Repro rate                     | all the time (100%) |      |
| Repro with our demo prj        | |      |
| Demo project link              |  |      |

### Issue Description and Steps

hi everyone
I have a problem with response headers in POST request in web version.
response header is empty 
but in google chrome network inspect everything is fine

### flutter doctor output
`[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-11.1.pre at /home/mhalizadeh/Android/flutter.beta
    • Framework revision 2738a1148b (2 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/mhalizadeh/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/mhalizadeh/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome
• No issues found!
`

**Comment by temirfe** [comment]
Have the same problem, except in my case there is only 'content-type' in response headers. I need X-Pagination-.. info. Works fine with android device. dio 3.0.9

**Comment by janek515** [comment]
@temirfe did you manage to find the cause?
