### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: 

### ISSUE THREAD

**Issue by LvJson** [flutterchina/dio#832]
flutter ( 4037): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: HttpException: , uri = https://imtm.cgcczp.com:8095/api/Account/Login
E/flutter ( 4037): #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:963:7)
E/flutter ( 4037): <asynchronous suspension>
E/flutter ( 4037): #1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
E/flutter ( 4037): #2      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
E/flutter ( 4037): #3      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter ( 4037): #4      new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter ( 4037): #5      _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 4037): #6      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 4037): #7      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 4037): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 4037): #9      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 4037): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 4037): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 4037): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 4037): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 4037): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 4037): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 4037):

**Comment by bardez** [comment]
I ha the same problem. This issue must to be reopened.

**Comment by arasu33** [comment]
Facing Same Issue

**Comment by yousifAlneamy** [comment]
This should be reopened

**Comment by iamnabink** [comment]
Faced same issue, This should be reopened

**Comment by wonpyohong** [comment]
Same here

**Comment by aboutlan** [comment]
I ran into the same error when locked. Has anyone solved this error?

**Comment by Chidhambararajan** [comment]
me too same error

**Comment by polkacast-dev** [comment]
same error, local debug
