### ISSUE TITLE
Unable to send raw bytes as post request body

### ISSUE THREAD

**Issue by Maldus512** [flutterchina/dio#837]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / android                          |      |
| Platform Version               | 9.0                              |      |
| Dio Version                    | 3.0.9                                  |      |
| Android Studio / Xcode Version | VSCode     |      |
| Repro rate                     | all the time (100%)    |      |

### Issue Description and Steps

I wish to upload a file to a server by simply sending it as raw binary data in the request body. I was previously using the `http` library, but I was drawn to `dio` to use the progress feature.

I am unable to send the binary data, plain and simple. If I use a `Uint8List` as data it is converted to String as is, thus displaying a Dart list instead of the actual data:

```
POST / HTTP/1.1
user-agent: Dart/2.8 (dart:io)
content-type: application/x-www-form-urlencoded
accept-encoding: gzip
content-length: 22
host: 192.168.1.169

[99, 105, 97, 111, 10]
```  

I also tried using a file stream as data, which brings me closer but still inserts some kind of length indicators between my data (in this case, the string "ciao" is the binary content):

```
POST / HTTP/1.1
user-agent: Dart/2.8 (dart:io)
content-type: application/x-www-form-urlencoded
transfer-encoding: chunked
accept-encoding: gzip
host: 192.168.1.169

5
ciao

0

```

On the other end, if I use the `Uint8List` value as body with the http library, it is normally sent as raw bytes.

This is the Dart code that I'm using to send the request:
```
  var content = await file.readAsBytes();
    Response response = await Dio().post(url,
        //data: file.openRead(),
        data: content,
        options: Options(contentType: Headers.formUrlEncodedContentType),
        onSendProgress: (count, total) => print("$count, $total"));

```

Is there a way I haven't found yet to properly send raw bytes? For various reasons I cannot use multiform data requests to upload my file.

**Comment by pomarec** [comment]
@Maldus512 #307  could help you

**Comment by subsub** [comment]
I have the same problem. Do you figure out how to send binary-data?

**Comment by Maldus512** [comment]
@subsub No, I haven't. I had to work with a different library to fix the issue and the need/occasion to look at this again has not emerged yet

**Comment by amm-catapult** [comment]
I don't know if this helps, but here are a couple of supporting points:

1.  In your first example I agree this is not the body you want, but in second example (where you say you "also tried using a file stream as data"), the body actually looks correct and the additional numbers are a mandatory part of sending your intended data when it is using `transfer-encoding: chunked` (i.e. [Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding)).
    * In this mode, the extra numbers in between are necessary for the receiving end to correctly reassemble the raw data, and likewise the final `0` says "there are no more bytes, hence this is the end of the body".
    * In this case, a properly-implemented HTTP 1.1 receiver will get exactly the string you're trying to send, i.e. `'ciao\n'`, or the byte sequence 99, 105, 97, 111, 10.
    * I understand that maybe you don't want it to use chunked transfer encoding, perhaps because your receiver doesn't respect the `transfer-encoding: chunked` header, but I suspect Dio makes the decision to do this because it's necessary to support streaming of data (where a stream usually implies a body with a length that can't be known in advance).
2.  Underlying Dio might be a [`HttpClientRequest`](https://api.dart.dev/stable/2.12.4/dart-io/HttpClientRequest-class.html) which, through trial and error, I found has:
    1. A `write(Object?)` function that (I think) calls `toString()` on your argument, hence causing the string `'[99, 105, 97, 111, 10]'` to be sent in your example; and
    2. An `add(List<int>)` function that can take a `Uint8List` like you have and just send it as those raw bytes.

I don't know Dio at all yet, at the time of writing, so I don't know if it has a recommended way to send raw (`Uint8List`) data, and I also don't know Dart well enough to know how to convert a `Uint8List` into a raw binary string... but knowing that a Dart string is UTF-16, I'm not sure if that would be efficient to do anyway for a large amount of data.

**Comment by edwardaux** [comment]
I know this is kind of an old issue, but I recently spent a bit of time facing the same issue. In case anyone else has this problem, here's how I managed to achieve it.

FWIW, in my particular case, I'm trying to upload to an S3 bucket using a presigned url. The secret sauce for me was that if using a `Stream`, then you also need to provide a `content-length` header too (otherwise it'll fall back to chunking).

The following minimal code works just fine:
```
Future<void> uploadData(String url, Uint8List bytes) async {
  BaseOptions options = BaseOptions(
    headers: {
      'content-length': bytes.length,
    },
  );

  final dio = Dio(options);
  await dio.put(
    url,
    data: Stream.fromIterable(bytes.map((e) => [e])),
  );
}
```
I haven't tried loading large files yet (eg. a video), but it works for some simple cases that I've tried so far. 

One other thing that I noticed is that it also works if I pass `MultipartFile.fromBytes(bytes).finalize()` as the `data` parameters (instead of using `Stream.fromIterable()`) which hopefully might be useful later when I'm reading large files - I guess we'll see.

**Comment by chejdj** [comment]
> 

`MultipartFile.fromBytes(bytes).finalize()` In my test, use `MultipartFile.fromBytes(bytes).finalize()` is faster 30% than 'Stream.fromIterable(bytes.map((e) => [e]))'.

**Comment by RafatMeraz** [comment]
> 

It works well for uploading, but I wanted to measure the onUploadProgress which is not working for me, for instance, I f I upload 6298880 bytes chunk it show 6298880(sent)/6298880(total) at once in the starting of request. Have any solution for it!?
