### ISSUE TITLE
Http2Adapter Test  error

### ISSUE THREAD

**Issue by 350054665** [flutterchina/dio#838]
test("Http2 Test", () async {
      var dio = Dio()
      ..options.baseUrl = "https://www.ustc.edu.cn/"
//      ;
      ..httpClientAdapter = Http2Adapter(ConnectionManager(idleTimeout: 5000));

    Response<String> response;
    response = await dio.get("2062/list.htm");
    print(response.data);
    expect(response.statusCode, 200);
    });

TimeoutException after 0:00:30.000000: Test timed out after 30 seconds

Do not add Http2Adapter， is OK.

**Comment by hongyiweiwu** [comment]
#760
