### ISSUE TITLE
Dio response headers null in Flutter Web

### ISSUE THREAD

**Issue by chitgoks** [flutterchina/dio#840]
Hi , i wish to ask if there is something that dio needs in order to get access to response headers in flutter web?

it works fine in android. i want to get the the cookies but it's always null.

res.headers[HttpHeaders.setCookieHeader];

i already set the cookies as httpOnly: false so this should be accessible by javascript but even so, nothing gets written in the browser's document.cookie.

I had tried the urls with a simple ajax , the cookies can be seen in the browser and it works ok with another url call and outputting req.cookies.

could this be a flutter issue?

**Comment by chitgoks** [comment]
Closing this. will

**Comment by talhabalaj** [comment]
How did you fix your issue? I am having the same issue.

**Comment by chitgoks** [comment]
if i remember, they have a different class for the web in getting it.
