### ISSUE TITLE
Timeout  doesn't work

### ISSUE THREAD

**Issue by kamike** [flutterchina/dio#843]
dio: 3.0.9
Flutter version 1.17.2
Dart version 2.8.3

BaseOptions options = new BaseOptions(
        baseUrl: Configure.BASE_URL,
        connectTimeout: 1000,
        receiveTimeout: 2000,
        contentType: Headers.jsonContentType);
    _dio = new Dio(options);

I waited for more than a minute before something went wrong:

SocketException: Failed host lookup xx.com, OS Error: No address associated with hostname, errno = 7

No matter what the setting is, the result is the same, I just want to return a network error faster, what should I do??

**Comment by huiwen0212** [comment]
Is the url a public domain? if no have you set that url in your host file?

**Comment by kamike** [comment]
> Is the url a public domain? if no have you set that url in your host file?

the url a public domain，I set Timeout=2000，It should return the result within 2 seconds instead of waiting a minute or two

**Comment by HannibalKcc** [comment]
Duplicate of #3

**Comment by HannibalKcc** [comment]
#786

**Comment by jpgpuyo** [comment]
Hello, I have timeout issues with 3.0.9. In my opinion, this issue should be reopen, except if this issue has been fixed in the latest version of dio.
