### ISSUE TITLE
connectTimeout is not working when device is connected to a wifi which is not connected to internet

### ISSUE THREAD

**Issue by codepgq** [flutterchina/dio#844]
When the mobile phone is connected to WiFi, but WiFi cannot access the network, the timeout mechanism does not work

**Comment by eduardo-cervantes** [comment]
I am experiencing the same problem. Has anyone found an alternative?

**Comment by gabcarneiro** [comment]
This is still an issue.

**Comment by sunnyxibei** [comment]
it happens now

**Comment by Twinsen81** [comment]
Still an issue in 3.0.10

**Comment by TheVinhLuong** [comment]
This is still an issue.

**Comment by JanMelvinBautista** [comment]
Does anyone found a workaround for this?

**Comment by cvlnomen** [comment]
I just created a pull request for this issue.
I hope that @wendux (or somebody else) can look at it as soon as possible!

**Comment by cvlnomen** [comment]
The issue has not magically gone away.

**Comment by cvlnomen** [comment]
This is still an issue
