### ISSUE TITLE
Request doesn't work in 4g !

### ISSUE THREAD

**Issue by NicolasCELLA** [flutterchina/dio#852]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info
Platform: Android, Ios
Flutter: 1.17.4
Dio Version: 3.0.9

### Issue Description and Steps

Hello, I have a problem with some users !

The api of the application was down during 3 hours, some who tried to use the application during this period and now can't make a request 3 days later in 4g, but in Wi-Fi it works ! 

Any idea why no more requests work for them after few days ?

Thank for your help 😇

**Comment by NicolasCELLA** [comment]
It's strange but the problem was in the setting of ios => Mobile Data => (app) turn off 

Ios have automaticaly turn off application data when the api was down !

**Comment by xuzheng94** [comment]
I have the same problem，under the 4G network 🙋‍♂️
I used network diagnosis, the result is DNS resolution failure

Flutter: 1.17.0
Dio Version: 3.0.9

**Comment by litang0908** [comment]
Same problem, some iOS 14 users can not access my server under 4G , but can do with WIFI.
Is there any resolution or any one knows why ?

**Comment by AliPunjabi** [comment]
@litang0908 same issue on android greater then 10, it work when connects using 4g with vpn and wifi but not on 4g

**Comment by kuhnroyal** [comment]
Any problem regarding this is not related to Dio.
Dio uses the Dart platform libraries on mobile devices, so will have the same problem with the plain Dart HttpClient.
You can maybe try the `native_dio_adapter` and see if that works.
