### ISSUE TITLE
How to know the time period server response in the Dio library?

### ISSUE THREAD

**Issue by huubao2309** [flutterchina/dio#854]
I use postman, it returns `status`, `time period`, `size` of the response, ...

![image](https://user-images.githubusercontent.com/18402446/86865787-e33c7000-c0f9-11ea-8574-38975e05666b.png)

How to get values in `Dio` lib? (I need it to write log)

**Comment by huubao2309** [comment]
keep it open

**Comment by hamidwaezi** [comment]
i have same problem

**Comment by kuhnroyal** [comment]
You can build yourself a custom interceptor.

**Comment by adminant** [comment]
Is there a chance somebody already made one?

**Comment by kuhnroyal** [comment]
I don't know of one. Another suggestion is using the Dart DevTools which traces HTTP calls.
