### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: Too many open files, errno = 24)

### ISSUE THREAD

**Issue by mohammadnejad** [flutterchina/dio#868]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | -----------------------------------------------------|---- |
| Platform Name                  |ios   |                        
| Dio Version                   |  3.0.9    |                                
| Android Studio  | Android Studio 4.0.1     |            

I have this error in IOS platform when call many apis.

DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: Too many open files, errno = 24)

**Comment by shen-lan** [comment]
This error is reported in the Android emulator ？

**Comment by mohammadnejad** [comment]
Yes, in Android emulator I have error too.

**Comment by FrantisekGazo** [comment]
@mohammadnejad Did you manage to fix this?
