### ISSUE TITLE
MultipartFile Upload: Converting object to an encodable object failed: Instance of 'FormData'

### ISSUE THREAD

**Issue by lllleow** [flutterchina/dio#869]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Flutter                          |      |
| Platform Version               | 1.17.2                              |      |
| Dio Version                    | 3.0.9                                  |      |
| Android Studio / Xcode Version | VSCode / Xcode 11              |      |
| Repro rate                     | 100%   |      |

### Issue Description and Steps

Hello, i am trying to upload an image to a server. I've used the guides provided in the documentation to get the process started.

The error message that i am receiving is:
**DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'FormData'**

My code is:
![image](https://user-images.githubusercontent.com/24416845/88221153-6bfaf600-cc3a-11ea-8eff-3ecd32c46bdb.png)

![image](https://user-images.githubusercontent.com/24416845/88221180-75845e00-cc3a-11ea-9550-bd9d5c41390e.png)

**Comment by 13213334722** [comment]
我也碰到了相同的问题：Converting object to an encodable object failed: Instance of 'FormData

**Comment by ejrgeek** [comment]
I'm having the same error:

Code:
```
MultipartFile file = await MultipartFile.fromFile(image.path);
responseDio = await dio.request(
    endpointUpdateImageProfile,
    options: Options(
    method: "POST",
        headers: {
            'Content-Type': 'multipart/form-data',
            'Authorization': 'token $token',
        },
    ),
    data: {'profile': file},
);
```

Error:
```
ERRO: DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile'
I/flutter ( 6127): #0      _JsonStringifier.writeObject  (dart:convert/json.dart:687:7))
I/flutter ( 6127): #1      _JsonStringifier.writeMap  (dart:convert/json.dart:768:7))
I/flutter ( 6127): #2      _JsonStringifier.writeJsonValue  (dart:convert/json.dart:723:21))
I/flutter ( 6127): #3      _JsonStringifier.writeObject  (dart:convert/json.dart:678:9))
I/flutter ( 6127): #4      _JsonStringStringifier.printOn  (dart:convert/json.dart:876:17))
I/flutter ( 6127): #5      _JsonStringStringifier.stringify  (dart:convert/json.dart:861:5))
I/flutter ( 6127): #6      JsonEncoder.convert  (dart:convert/json.dart:261:30))
I/flutter ( 6127): #7      JsonCodec.encode  (dart:convert/json.dart:171:45))
I/flutter ( 6127): #8      DefaultTransformer.transformRequest 
package:dio/src/transformer.dart:62
I/flutter ( 6127): #9      DioMixin._transformData 
package:dio/src/dio.dart:1014
I/flutter ( 6127): #10     DioMixin._dispatchRequest 
package:dio/src/dio.dart:921
I/flutter ( 6127): #11     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:dio/src/dio.dart:849
I/flutter ( 6127): #12     DioM

```

![dioerror](https://user-images.githubusercontent.com/17034932/95792064-12deb380-0cb9-11eb-9ad0-34e232f93e6a.png)

**Comment by chuongdevJC** [comment]
Did anyone resolve this issue pls ?

**Comment by Jagrajsinghji** [comment]
Try adding  `MediaType`
  ```
MultipartFile mFile = await MultipartFile.fromFile(
        photo.path, filename: fileName,
        contentType: MediaType("image", fileName.split(".").last),);
```

The `MediaType` class is defined in [http_parser](https://pub.dev/packages/http_parser), so make sure you use ths package

**Comment by pedrolacerda81** [comment]
> Try adding `MediaType`
> 
> ```
> MultipartFile mFile = await MultipartFile.fromFile(
>       photo.path, filename: fileName,
>       contentType: MediaType("image", fileName.split(".").last),);
> ```
> 
> The `MediaType` class is defined in [http_parser](https://pub.dev/packages/http_parser), so make sure you use ths package

@Jagrajsinghji  added and still same error

**Comment by kateile** [comment]
same error. Any solution

**Comment by ahmedalrifai** [comment]
Any solution am having the same issue?

**Comment by MarcoGolin** [comment]
same error. Any solution? =(

**Comment by Jagrajsinghji** [comment]
Could anyone of you share you code snippet?

**Comment by MarcoGolin** [comment]
> Could anyone of you share you code snippet?

`  List<int> imageBytes = await pickedFile.readAsBytes();

      // List<int> imageData = await compresFotoListInt(imageBytes, 320, 320);

      MultipartFile multipartFile = MultipartFile.fromBytes(
        imageBytes,
        filename: 'load_image.png',
      );

      String encodedFileImageSmall = base64Encode(imageBytes);
      widget.resultMultiPartImage(multipartFile);
      setState(() {
        foto = encodedFileImageSmall;
      });
    }`

**Comment by MarcoGolin** [comment]
> > Could anyone of you share you code snippet?
> 
> ` List imageBytes = await pickedFile.readAsBytes();
> 
> ```
>       MultipartFile multipartFile = MultipartFile.fromBytes(
>     imageBytes,
>     filename: 'load_image.png',
>   );
> 
>   String encodedFileImageSmall = base64Encode(imageBytes);
>   widget.resultMultiPartImage(multipartFile);
>   setState(() {
>     foto = encodedFileImageSmall;
>   });
> }`
> ```

  Future<Produto> save(Produto produto) async {
    return Api.withAuth()
        .instance
        .post('/produto/save', data: produto.toJson())
        .then((response) {
      Produto p = Produto.fromJson(response.data);
      return p;
    }).catchError((onError) {
      print(onError);
    });
  }

**Comment by MarcoGolin** [comment]
> Could anyone of you share you code snippet?

solved, I wasn't using the FormData correctly, trying to send as Json

**Comment by abdelrahmanelmarakby** [comment]
> 
> 
> > Could anyone of you share you code snippet?
> 
> solved, I wasn't using the FormData correctly, trying to send as Json

tell us how did you solved this

**Comment by secret3579** [comment]
> > Could anyone of you share you code snippet?
> 
> solved, I wasn't using the FormData correctly, trying to send as Json

Please give your code example for this issue?

**Comment by tatraef** [comment]
There was the same error because the Logging Interceptor, which tried to json.encode my FormData.

working code just:
  ```
var file = File(path);
  var fileName = file.path.split('/').last;
  FormData formData = FormData.fromMap({
    "file": await MultipartFile.fromFile(file.path, filename: fileName),
  });
  
  Response resp = await dio.post(endpoint, data: formData);
```

**Comment by tinkokowin96** [comment]
hope this help
`
      final file = await dio.MultipartFile.fromFile(
        _image?.path ?? "",
        filename: _image?.name,
      );

      final body = dio.FormData.fromMap({
        "email": _emailController.text,
        "password": _passwordController.text,
        "name": _nameController.text,
        "phone": _phoneController.text,
        "file": file
      });
`

**Comment by icemanbsi** [comment]
I have similar problem and I think I know the answer. We are looking at the wrong place.
The issue is triggered by jsonEncode function  which trying to encode FormData instance. Since the FormData cannot be encoded to json string, it will trigger this error. 

So the next step is find out where you place your debug print or similar function which called the jsonEncode. It might be on your interpreter too.

**Comment by devmemory** [comment]
> 

Thanks for icemanbsi. I could figure out why I faced this error. So obviously the problem was where I print whenever I call an API. And to see the request options without debugging mode, I'm configuring some parts. And one of them was **where I encode requestOptions.data**. And after I blocked that part conditionally, I could solve it perfectly.

**Comment by devmemory** [comment]
> I have similar problem and I think I know the answer. We are looking at the wrong place. The issue is triggered by jsonEncode function which trying to encode FormData instance. Since the FormData cannot be encoded to json string, it will trigger this error.
> 
> So the next step is find out where you place your debug print or similar function which called the jsonEncode. It might be on your interpreter too.

Thanks for icemanbsi. I could figure out why I faced this error.
According to what is written here, the problem was where I print whenever I call an API. And to see the request options without debugging mode, I'm configuring some parts.
And one of them was where I encode requestOptions.data. And after I blocked that part conditionally, I could solve it perfectly. :)

**Comment by zzz1029335886** [comment]
The problem occurred on log printing json.encode the data extends InterceptorsWrapper

**Comment by sulthanalihsan** [comment]
> The problem occurred on log printing json.encode the data extends InterceptorsWrapper

how you solve that problem?

**Comment by Oliul-Hasnat-Rafi** [comment]
FormData data =  FormData.fromMap({
      'key': 'f8b0266d23d2f048bb5.',
      'image': await MultipartFile.fromFile(filePath, filename: filename)
    });
    var response =
        await dio.post('https://api.imgbb.com/1/upload', data: data);
        
 it's work for me

**Comment by dakshatsuraasa** [comment]
same issue no solution

**Comment by MalikAbdMusleh** [comment]
> > Could anyone of you share you code snippet?
> 
> solved, I wasn't using the FormData correctly, trying to send as Json

worked thanks ♥ ♥
