### ISSUE TITLE
Example of SSL Pinning

### ISSUE THREAD

**Issue by ernestomar** [flutterchina/dio#87]
After review the documentation I can't found how to implement SSL Pinning. Is possible add an example to documentation?

**Comment by wendux** [comment]
done, https://github.com/flutterchina/dio#https-certificate-verification

**Comment by stwonary** [comment]
@wendux  
```
Pinning is an optional mechanism that can be used to improve the security of a service or site that relies on SSL Certificates. Pinning allows you to specify a cryptographic identity that should be accepted by users visiting your site.
```

Basically is to avoid Man in the Middle attack using a proxy(Charles Proxy for example) and monitoring the App traffic. The self-signed certificate can be installed in the phone manually and the App will see it as valid. `badCertificateCallback` will never be called.

`badCertificateCallback` is only called when a server certificate cannot be authenticated by any of our trusted root certificates.


We need an `onCertificateCallback` to properly implement an SSL pinning mechanism.

**Comment by nEdAy** [comment]
We need SSL Pinning by SHA-256(Subject Public Key Info)

**Comment by minhngvan** [comment]
Need too.

**Comment by sagarnayak** [comment]
An update on sha256 certificate pinning?

**Comment by sagarnayak** [comment]
found a lib - https://pub.dev/packages/http_certificate_pinning
