### ISSUE TITLE
Flutter Web Missing Headers

### ISSUE THREAD

**Issue by LucaIaconelli** [flutterchina/dio#870]
Hello,

I'm making a post-call to my server that returns a "set-cookie" and everything returns perfectly in the chrome console.

This is the server's cors configuration:

```
exposedHeaders: ["Set-Cookie", 'Content-Type', 'Authorization', "X-Api-Key"],
allowedHeaders: ['Content-Type', 'Authorization', "X-Api-Key"]
```

This is how I make the request through Flutter

```
dioLibrary.BaseOptions options = new dioLibrary.BaseOptions(
            baseUrl: this.url,
            headers: {
              "Accept": "application/json",
            },
          );
DioForBrowser _d = DioForBrowser(options);
var adapter = BrowserHttpClientAdapter();
adapter.withCredentials = true;
_d.httpClientAdapter = adapter;
response = await _d.post(
    this.url,
    options: dioLibrary.Options(
              headers: header,
      ),
      data: body,
);
```

The Chrome browser does not automatically save the token and above all Flutter web not print all the headers available (which are seen in the console).

Is there such a way for me to be able to print all headers in Flutter web?

Thanks in advance

**Comment by tstrg** [comment]
@LucaIaconelli I'm facing the same issue. Did you find the solution?

**Comment by LucaIaconelli** [comment]
Well, basically the browser automatically handles the cookie so I can do my HTTP request correctly but no I'm still not able to see the cookie in chrome tab and flutter not print all headers as chrome console does.

**Comment by tstrg** [comment]
@LucaIaconelli Thank you for fast response. 

There is a Set-Cookie option in the Response header. I'm trying to figure out why are not cookies written to the browser. I've set the BrowserHttpClientAdapter() withCredentials to true based on the https://github.com/flutterchina/dio/issues/585 

Based on your answer I understand the headers printed in Flutter from Dio are limited on a specific set, which is not the issue.

**Comment by ngsanti** [comment]
in my case, chrome was blocking the cookies from being saved since i was only testing and running on localhost.
you can unblock it by accessing `chrome://flags` on chrome see: https://support.google.com/chrome/thread/34237768?hl=en
