### ISSUE TITLE
what path can find by setTrustedCertificates

### ISSUE THREAD

**Issue by lx19990999** [flutterchina/dio#871]
dio = Dio(BaseOptions(baseUrl: API_BASE_URL, contentType: Headers.formUrlEncodedContentType));
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate  = (client) {
      client.findProxy = (uri) {
        //proxy all request to localhost:8888
        return "PROXY 192.168.31.100:8888";
      };
      SecurityContext sc = SecurityContext();
      sc.setTrustedCertificates("assets/cert/prod/server.crt");
      HttpClient httpClient = HttpClient(context: sc);
      return httpClient;
    };

here is my code, i put the crt file into assets, but log always DioError [DioErrorType.DEFAULT]: FileSystemException: Cannot open file

please help me, thank you

**Comment by qcuong97** [comment]
Same problem

**Comment by qcuong97** [comment]
import 'package:dio/adapter.dart';

**Comment by linmq** [comment]
> I solved import 'package:dio/adapter.dart';

Hey, could you please your code how it will worked? 
Thank you.
I import the 'package:dio/adapter.dart'; , that doesn't help.

**Comment by qcuong97** [comment]
> I figured out the problem,
> Make sure you have added `assets/cert/prod/server.crt` to pubspec.yaml

It's interesting, I don't need to add it
