### ISSUE TITLE
希望在dio中获取多个 set-cookie

### ISSUE THREAD

**Issue by Gyueqi** [flutterchina/dio#873]
当我的返回头里面有 多个set-cookie 的时候 这边只能获取到第一个 set-cookie ，如果需要多个set-cookie 要怎么操作 更改哪里     望作者可以及时回复 谢谢

**Comment by wendux** [comment]
set-cookie 值是一个数组

**Comment by Gyueqi** [comment]
> set-cookie值是一个数组

我知道啊 但是我这边数组只能获取到第一个  其他的都不显示   使用了  cookie 管理 但是还是没用 只能获取到第一个 其他都获取不到

**Comment by easazade** [comment]
به انگلیسی بنویسید عزیزان. گاو دکفته بازاره مگه ره؟
