### ISSUE TITLE
dio 在使用post 请求中，携带FormData时，后台服务器接收到的内容为空。

### ISSUE THREAD

**Issue by SunLongbri** [flutterchina/dio#876]
### Dio version

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

  使用版本：dio: ^3.0.9

### 代码描述

  _initData(String netURL) async {
    Response response;
    Dio dio = Dio();
    dio.options.contentType = 'multipart/form-data';
    //在上文dio使用的代码中加入如下代码，即添加了Log拦截器
    dio.interceptors.add(LogInterceptor());
    //设置代理
    DefaultHttpClientAdapter adapter = dio.httpClientAdapter;
    adapter.onHttpClientCreate = (HttpClient client) {
      if (client == null) {
        client = HttpClient();
      }
      client.findProxy = (url) {
        return HttpClient.findProxyFromEnvironment(url, environment: {
          "http_proxy": netURL,
        });
      };
      return client;
    };
    FormData formData = FormData.fromMap({
      "params": {"msg": "测试成功！！！！！！！！！！！"}
    });
    Map<String, dynamic> testJson = {
      "params": {"msg": "测试成功！！！！！！！！！！！"}
    };
//    var bytes1 = await formData.readAsBytes();

//    print('上传内容为：${testJson.toString()}');
    response = await dio.post(
      netURL,
      data: formData,
      options: Options(contentType: "multipart/form-data"),
      onSendProgress: (received, total) {
        if (total != -1) {
          print((received / total * 100).toStringAsFixed(0) + "%");
        }
      },
    );

    if (response != null) {
      print(
          'responseData:${response.data},responseData.statusCode:${response.statusCode}');
    }

//    response = await dio.post(netURL,
//        queryParameters:      {
//          "params": {"msg": "测试成功！！！！！！！！！！！"}
//        }
//        , options: Options(contentType: "multipart/form-data"));
  }

### 代码调用

    _initData('http://192.168.40.210:8850/tool/test');

### 结果

I/flutter (20680): *** Request ***
I/flutter (20680): uri: http://192.168.40.210:8850/tool/test
I/flutter (20680): method: POST
I/flutter (20680): responseType: ResponseType.json
I/flutter (20680): followRedirects: true
I/flutter (20680): connectTimeout: 0
I/flutter (20680): receiveTimeout: 0
I/flutter (20680): extra: {}
I/flutter (20680): headers:
I/flutter (20680):  content-type: multipart/form-data
I/flutter (20680): 
I/flutter (20680): 12%
I/flutter (20680): 67%
I/flutter (20680): 86%
I/flutter (20680): 87%
I/flutter (20680): 100%
I/flutter (20680): *** Response ***
I/flutter (20680): uri: http://192.168.40.210:8850/tool/test
I/flutter (20680): statusCode: 200
I/flutter (20680): headers:
I/flutter (20680):  content-type: text/plain;charset=UTF-8
I/flutter (20680):  date: Thu, 30 Jul 2020 06:06:16 GMT
I/flutter (20680):  content-length: 0
I/flutter (20680): 
I/flutter (20680): responseData:,responseData.statusCode:200     此处返回的responseData为空。应该为测试成功！！！！！！！！！！！
I/flutter (20680): didChangeAppLifecycleState: AppLifecycleState.inactive
I/flutter (20680): didChangeAppLifecycleState: AppLifecycleState.paused

而postman测试的结果正常：

![image](https://user-images.githubusercontent.com/26838223/88887736-9159b680-d26f-11ea-9dc8-422825b44442.png)

**Comment by shen-lan** [comment]
```
contentType: Headers.formUrlEncodedContentType
```
试试

**Comment by SunLongbri** [comment]
我加在这个地方：

    response = await dio.post(
      netURL,
      data: formData,
      options: Options(contentType: Headers.formUrlEncodedContentType),
      onSendProgress: (received, total) {
        if (total != -1) {
          print((received / total * 100).toStringAsFixed(0) + "%");
        }
      },
    );

返回结果还是没有数据：

I/flutter (29487): *** Request ***
I/flutter (29487): uri: http://192.168.40.210:8850/tool/test
I/flutter (29487): method: POST
I/flutter (29487): responseType: ResponseType.json
I/flutter (29487): followRedirects: true
I/flutter (29487): connectTimeout: 0
I/flutter (29487): receiveTimeout: 0
I/flutter (29487): extra: {}
I/flutter (29487): headers:
I/flutter (29487):  content-type: application/x-www-form-urlencoded
I/flutter (29487): 
I/flutter (29487): 12%
I/flutter (29487): 67%
I/flutter (29487): 86%
I/flutter (29487): 87%
I/flutter (29487): 100%
I/flutter (29487): *** Response ***
I/flutter (29487): uri: http://192.168.40.210:8850/tool/test
I/flutter (29487): statusCode: 200
I/flutter (29487): headers:
I/flutter (29487):  content-type: text/plain;charset=UTF-8
I/flutter (29487):  date: Thu, 30 Jul 2020 07:12:40 GMT
I/flutter (29487):  content-length: 0
I/flutter (29487): 
I/flutter (29487): responseData:,responseData.statusCode:200

**Comment by shen-lan** [comment]
抓包看一下吧 也许是有返回

**Comment by SunLongbri** [comment]
嗯，这个后台给我的解答是，我穿过去的参数为空，所以返回结果为空。而用postman测试的时候，后台可以拿到数据。
对了，我用  var bytes1 = await formData1.readAsBytes(); 这种进行传输时，后台能够拿到数据，但是数据是字节，后台说又无法解析。

**Comment by SunLongbri** [comment]
解决了，是fordata穿参的问题，后者需要加上引号才行。

**Comment by Ucoon** [comment]
> 解决了，是fordata穿参的问题，后者需要加上引号才行。

**Comment by Ucoon** [comment]
是哪里需要加上引号呢
