### ISSUE TITLE
Token拦截器里的onError，使用 dio.interceptors.errorLock.lock() 无效

### ISSUE THREAD

**Issue by JDNew** [flutterchina/dio#877]
dio 3.0.7

我创建了个Token拦截器，在onError里处理当token过期时，进行刷新的逻辑。

当我只有一个请求时，过程还是正常的，但当有多个请求同时进行时，我按照Example的例子使用了`dio.interceptors.errorLock.lock()`
但我发现，即使使用了这个，其它请求同样也会因token失效的错误进入onError，导致`dio.interceptors.errorLock.lock()`多次被调用。似乎这个锁没有用。

它们不是应该在那里阻塞吗？直到我unlock？

**Comment by JDNew** [comment]
目前我主要做的处理是，增加一个completer来判断：
`
    Future<Null> _lockFuture;

    onError: (DioError error) {
    //print(error);
    // Assume 401 stands for token expired
    if (error.response?.statusCode == 401) {
      RequestOptions options = error.response.request;
      // If the token has been updated, repeat directly.

       if (dio.interceptors.errorLock.locked) {
          if (_lockFuture != null) {
            await _lockFuture;
          }
        }
     
      if (csrfToken != options.headers["csrfToken"]) {
        options.headers["csrfToken"] = csrfToken;
        //repeat
        return dio.request(options.path, options: options);
      }
      // update token and repeat
      // Lock to block the incoming request until the token updated
      dio.lock();
      dio.interceptors.responseLock.lock();
      dio.interceptors.errorLock.lock();
    
       var completer = new Completer<Null>();
        _lockFuture = completer.future;

      return tokenDio.get("/token").then((d) {
        //update csrfToken
        options.headers["csrfToken"] = csrfToken = d.data['data']['token'];
      }).whenComplete(() {
        dio.unlock();
        dio.interceptors.responseLock.unlock();
        dio.interceptors.errorLock.unlock();

        completer.complete();
        _lockFuture = null;

      }).then((e) {
        //repeat
        return dio.request(options.path, options: options);
      });
    }
    return error;
  }));`

**Comment by JDNew** [comment]
#590

**Comment by wendux** [comment]
拦截器锁的作用范围和dio实例是相关的，不同dio实例之间是相互隔离的，建议全局用同一个dio实例。如果业务场景需要创建多个dio实例，可以用你这种方法去同步多个dio实例。

**Comment by JDNew** [comment]
> 拦截器锁的作用范围和dio实例是相关的，不同dio实例之间是相互隔离的，建议全局用同一个dio实例。如果业务场景需要创建多个dio实例，可以用你这种方法去同步多个dio实例。

你好，我当前是只有一个dio实例的，我用的是单例模式来包裹dio，我在onRequest里调用dio.lock()，确实其它一同发起的request都被lock住了，但在onError里调用dio.interceptors.errorLock.lock()，其它的error照样能进入onError()。

**Comment by wendux** [comment]
3.0.10已修复

**Comment by supermebing** [comment]
> 3.0.10已修复
3.0.10还是有问题

**Comment by leafney** [comment]
I have been following this issue.

I also encountered this problem in the previous `v3.0.10` for `但我发现，即使使用了这个，其它请求同样也会因token失效的错误进入onError` , but did not find a better solution. 

Seeing that the author updated to `v4.0.0` today, it was found to be normal after testing.


my test：
```
Restarted application in 618ms.
flutter: 发起请求:[ http://172.21.40.40:9999/api/v1/test ],请求数据：[ null ]
flutter: no token,get token first
flutter: 从本地获取到token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTY5NDcxMzAsImlzcyI6IlNlY3JldF9WYWxsZXkiLCJ1aWQiOiIxIn0.eQKcW29tQYAqtgxEPLefrMSkgP-GSWPJBFx7OI-dS74
flutter: 后端返回 access_token 已过期的错误码，需要刷新 access_token
flutter: 从本地获取refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTk1Mzg1OTcsImlzcyI6IlNlY3JldF9WYWxsZXkiLCJ1aWQiOiIxIn0.ndYRA-8CH4xtI-Y246g3NvlO2i4xtLHdFmSoCYNAUKE
flutter: 刷新请求到了新的token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTY5NDcyODEsImlzcyI6IlNlY3JldF9WYWxsZXkiLCJ1aWQiOiIxIn0.HTgYUo41l4tVdUIagguYwJ28IDlgNl6ahhwuiYfcEGM
flutter: 刷新token成功，解锁请求
flutter: 重新发起请求 null
flutter: 发起请求:[ http://172.21.40.40:9999/api/v1/test ],请求数据：[ null ]
flutter: have token,use it
flutter: errData -- 200 -- {code: 200, message: 这是返回的数据, data: {}, error: }
flutter: 正常响应
flutter: 拦截器捕获*正常*返回结果：{"code":200,"message":"这是返回的数据","data":{},"error":""}
flutter: response -- {"code":200,"message":"这是返回的数据","data":{},"error":""}
flutter: success -- 200 -- 这是返回的数据
flutter: 发起请求:[ http://172.21.40.40:9999/api/v1/test ],请求数据：[ null ]
flutter: have token,use it
flutter: errData -- 200 -- {code: 200, message: 这是返回的数据, data: {}, error: }
flutter: 正常响应
flutter: 拦截器捕获*正常*返回结果：{"code":200,"message":"这是返回的数据","data":{},"error":""}
flutter: response2 -- {"code":200,"message":"这是返回的数据","data":{},"error":""}
flutter: 发起请求:[ http://172.21.40.40:9999/api/v1/test ],请求数据：[ null ]
flutter: have token,use it
flutter: errData -- 200 -- {code: 200, message: 这是返回的数据, data: {}, error: }
flutter: 正常响应
flutter: 拦截器捕获*正常*返回结果：{"code":200,"message":"这是返回的数据","data":{},"error":""}
flutter: response3 -- {"code":200,"message":"这是返回的数据","data":{},"error":""}

```
