### ISSUE TITLE
Dio sends empty form body in POST request

### ISSUE THREAD

**Issue by neeraj87** [flutterchina/dio#88]
I am sending the following POST request to my node.js server:

```
import 'package:dio/dio.dart';
import 'dart:io';

print("--- userData: $userData"); // its a Map<String, dynamic>
Dio dio = new Dio();
dio.options.headers = {
  'Authorization': 'Bearer ' + prefs.getString("TOKEN"),
  'uuid': _uuid
};
dio.options.contentType = ContentType.parse("application/json");

FormData formData = new FormData.from(userData);

print("--- updated user info: $formData");

Response response = await dio.post("https://myapi.com/api/user/update", data: formData);

if(response.statusCode == 200) {
  Scaffold.of(context).showSnackBar(new SnackBar(
    content: new Text("User Info Updated"),
  ));
} else {
  Map<String, dynamic> _responseMap = json.decode(response.data);
  Scaffold.of(context).showSnackBar(new SnackBar(
    content: new Text(_responseMap['message']),
  ));
}
```

where the userData and formData print statement prints out something like this:

```
{
  first_name: John,
  last_name: Doe,
  age: 56,
  gender: Male,
  phone: 8888888888,
  email: john@gmail.com,
  others: some text and some other stuff
}
```

However on my server side I get an empty body. However when I do the same thing with Flutter's http:

```
Map<String, String> headersMap = {
  'Content-Type' : 'application/json',
  'Authorization' : 'Bearer ' + prefs.getString("TOKEN"),
  'uuid': _uuid
};

http.post(
    'https://myapi.com/api/user/update',
    body: json.encode(userData),
    headers: headersMap
).then((http.Response response){
  if(response.statusCode == 200) {
    Scaffold.of(context).showSnackBar(new SnackBar(
      content: new Text("User Info Updated"),
    ));
  }
});
```

I receive the data on server side. 

I even tried the Dio code by commenting the **dio.options.contentType** line but I still get empty request body. What is going on? What am I missing?

**Comment by wendux** [comment]
you should send post request directly as follows:
```dart
Response response = await dio.post("https://myapi.com/api/user/update", data: userData);
```
In your situation, shouldn't use `FormData`，because using `FormData` will lead the dio to set request `contentType`  as  "multipart/form-data"。

**Comment by neeraj87** [comment]
Thanks, it worked.

**Comment by RaoSaqib7860** [comment]
well

**Comment by toykam** [comment]
But what about the case of sending file to the server using post request

**Comment by toykam** [comment]
> 
> 
> you should send post request directly as follows:
> 
> ```dart
> Response response = await dio.post("https://myapi.com/api/user/update", data: userData);
> ```
> 
> In your situation, you shouldn't use `FormData`，because using `FormData` will lead the dio to set request `contentType` as "multipart/form-data"。

But what about the case of sending file to the server using post request

**Comment by tharwatsamy** [comment]
> > you should send post request directly as follows:
> > ```dart
> > Response response = await dio.post("https://myapi.com/api/user/update", data: userData);
> > ```
> > 
> > 
> > In your situation, you shouldn't use `FormData`，because using `FormData` will lead the dio to set request `contentType` as "multipart/form-data"。
> 
> But what about the case of sending file to the server using post request

u can use FormData but don't specify a content type if u specified a content type the body will be empty  I tried it and it worked that way

**Comment by Izudinalqasam** [comment]
hi guys, i face this issue, i have tried the ways above but none of them can resolve my issue

this is my setup and data
- Dio
` static final option = BaseOptions(
      baseUrl: AppConfig.instance.baseUrl, connectTimeout: 50000, receiveTimeout: 50000);

  static final interceptor = PrettyDioLogger(
      requestHeader: true,
      requestBody: true,
      responseBody: true,
      responseHeader: false,
      error: true,
      compact: true,
      maxWidth: 90);

  final Dio dio = Dio(option)
    ..interceptors.add(interceptor);`
    
- method send
`Future<Response> postFileDigital(
      FormData formFileDigital, String token) async {
    dio.options.headers['authorization'] = "Bearer " + token;
    return await dio.post(FILE_DIGITAL_UPLOAD_URL, data: formFileDigital);
  }`
  
  this is form
  `FormData.fromMap(<String, dynamic>{
      "attendance_date": currentDates.first,
      "check_in": currentDates[1].substring(0, 8),
      "lat": geoLocation.latitude.toString(),
      "lng": geoLocation.longitude.toString(),
      "status_health": "HEALTHY",
      // "photo": await MultipartFile.fromFile(file.path)
    }`
    
    i have been log the request data is exist when sending data to server but the server read empty data.
    anyone can help me ?
    
    my dio version =>  dio: ^3.0.9

**Comment by RaoSaqib7860** [comment]
O well done for response

**Comment by mayma93** [comment]
Hi, i face this issue, @Izudinalqasam did you solve it?

**Comment by RaoSaqib7860** [comment]
Are you here

**Comment by mayma93** [comment]
yes

**Comment by RaoSaqib7860** [comment]
Please explain issue

**Comment by mayma93** [comment]
i am trying to upload images using dio FormData, the request body containing two parts:  
-images: array of images
-element: element information (json)
when i log my FormData the data exist, but it seems the server is recieving an empty data.. 
i got 400 (bad request) with message : required request part 'element' is not present

**Comment by Izudinalqasam** [comment]
@mayma93 not yet, for that case i use alternative http package and it work fine coexisting with dio

**Comment by mayma93** [comment]
can you share your code please?

**Comment by RaoSaqib7860** [comment]
Sure!  if you face any problem then let me know

static Future addProduct(
    {AddProductBlock provider, List<Asset> images}) async {
  List<MultipartFile> imageList = new List<MultipartFile>();

  for (Asset asset in images) {
    final String _fileName = asset.name;
    ByteData byteData = await asset.getByteData();
    List<int> imageData = byteData.buffer.asUint8List();
    MultipartFile multipartFile = new MultipartFile.fromBytes(
      imageData,
      filename: _fileName,
      contentType: MediaType("image", "jpg"),
    );
    imageList.add(multipartFile);
  }
  print('name ${provider.pNameCon.text}');
  print('status ${provider.publishstatus}');
  print('tags ${provider.listofTags}');
  print('discription ${provider.disCon.text}');
  print('variants ${provider.listOfVariantforUploading}');
  print('fetured ${provider.listTimes}');
  print('Categories ${provider.furtherdetailids[0]}');
  print('SubCategories ${provider.furtherdetailids[1]}');
  print('Brand ${provider.furtherdetailids[2]}');
  print('Unit ${provider.furtherdetailids[3]}');
  print('product type ${provider.producttype}');
  print('list of images $imageList}');

  FormData formData = FormData.fromMap({
    'name': '${provider.pNameCon.text}',
    'image': imageList,
    'description': '${provider.disCon.text}',
    'status': '${provider.publishstatus == true ? 0 : 1}',
    'tags': provider.listofTags,
    'use_variants': '${provider.useVariant}',
    'variants': jsonEncode(provider.listOfVariantforUploading),
    'Product_type': '${provider.producttype == true ? 0 : 1}',
    'category': '${provider.furtherdetailids[0]}',
    'subcategory': '${provider.furtherdetailids[1]}',
    'brand': '${provider.furtherdetailids[2]}',
    'units': '${provider.furtherdetailids[3]}',
  });

  try {
    var responce = await Dio().post('$baseUrl$addproduct',
        data: formData,
        options: Options(
            headers: headerforApi,
            responseType: ResponseType.json,
            contentType: "application/json",
            followRedirects: false,
            validateStatus: (status) {
              return status <= 500;
            }));
    var data = responce.data;
    provider.setisloading(false);
    if (responce.statusCode == 201) {
      Navigator.of(provider.scaffoldKey.currentContext).pop();
      Navigator.of(provider.scaffoldKey.currentContext).pop();
      Navigator.push(
          provider.scaffoldKey.currentContext,
          MaterialPageRoute(
              builder: (c) => ChangeNotifierProvider(
                  create: (_) => DrawerBlock(),
                  child: RetailerDrawerPage())));
    }
    print('add product data is = $data');
    print('add product responce = ${responce.statusCode}');
  } catch (e) {}
}

**Comment by RaoSaqib7860** [comment]
it's a multi-part image uploading

**Comment by RaoSaqib7860** [comment]
also changing values in Dio package like this

String encodeMap(data, DioEncodeHandler handler, {bool encode = true}) {
  var urlData = StringBuffer('');
  var first = true;
  var leftBracket = encode ? '%5B' : '[';
  var rightBracket = encode ? '%5D' : ']';
  var encodeComponent = encode ? Uri.encodeQueryComponent : (e) => e;
  void urlEncode(dynamic sub, String path) {
    if (sub is List) {
      for (var i = 0; i < sub.length; i++) {
        urlEncode(sub[i],
            '$path${(sub[i] is Map || sub[i] is List) ? i : ''}');
      }
    } else if (sub is Map) {
      sub.forEach((k, v) {
        if (path == '') {
          urlEncode(v, '${encodeComponent(k)}');
        } else {
          urlEncode(v, '$path$leftBracket${encodeComponent(k)}$rightBracket');
        }
      });
    } else {
      var str = handler(path, sub);
      var isNotEmpty = str != null && str.trim().isNotEmpty;
      if (!first && isNotEmpty) {
        urlData.write('&');
      }
      first = false;
      if (isNotEmpty) {
        urlData.write(str);
      }
    }
  }

  urlEncode(data, '');
  return urlData.toString();
}

**Comment by lalaviiie** [comment]
i used MultipartFile.fromFile and i got Unsupported Media Type.. he use the default content type application/octet-stream

**Comment by RaoSaqib7860** [comment]
I think your files is not right . Please send me responce

**Comment by RaoSaqib7860** [comment]
Please send me api output

**Comment by RaoSaqib7860** [comment]
In case of multi part image's

**Comment by lalaviiie** [comment]
Future<dynamic> createSpareParts(Element element, List<File> images) async {
FormData formData = FormData();

    if (images != null) {
      for (File item in images)
        formData.files.addAll([
          MapEntry(
              "images",
              await MultipartFile.fromFile(item.path,
                  filename: item.path.split('/').last)),
        ]);
    }
formData.fields.add(MapEntry("element", element.toString()));
final response = await _dio.post('/api/element/',  data: formData);
}

the output : 415
{"timestamp":1613122248141,"status":415,"error":"Unsupported Media Type","message":"Content type 'application/octet-stream' not supported","path":"/api/element/"}

**Comment by lalaviiie** [comment]
Future createElement(element element, List images) async {
    FormData formData = FormData();

    if (images != null) {
      for (File item in images)
        formData.files.addAll([
          MapEntry(
              "images",
              await MultipartFile.fromFile(item.path,
                  filename: item.path.split('/').last)),
        ]);
    }
    formData.fields.add(MapEntry("element", element.toString()));
    final response = await _dio.post('/api/element/', data: formData);
  }


the output: 415
{"timestamp":1613122248141,"status":415,"error":"Unsupported Media Type","message":"Content type 'application/octet-stream' not supported","path":"/api/element/"}

**Comment by RaoSaqib7860** [comment]
Thanks, I'll check it out. And then respond you

**Comment by huynguyennovem** [comment]
Just tried with this and success:

```
data: json.encode(null)
```

**Comment by MostafaSolimanMO** [comment]
> Future createElement(element element, List images) async { FormData formData = FormData();
> 
> ```
> if (images != null) {
>   for (File item in images)
>     formData.files.addAll([
>       MapEntry(
>           "images",
>           await MultipartFile.fromFile(item.path,
>               filename: item.path.split('/').last)),
>     ]);
> }
> formData.fields.add(MapEntry("element", element.toString()));
> final response = await _dio.post('/api/element/', data: formData);
> ```
> 
> }
> 
> the output: 415 {"timestamp":1613122248141,"status":415,"error":"Unsupported Media Type","message":"Content type 'application/octet-stream' not supported","path":"/api/element/"}

I am having this issue with dio ^5.3.2
Did you solve it?
