### ISSUE TITLE
Nested FormData

### ISSUE THREAD

**Issue by ConfidenceYobo** [flutterchina/dio#881]
I am creating this issue as #354 does not have any fix and yet the issue is closed.

I am so having issue using nested formData. when I use formData in another formData I receive "Instance of FormData" in my backend. Is there a better way to implement this or is it an issue you may consider fixing?

**Comment by ConfidenceYobo** [comment]
As until now I still haven't found a fix

**Comment by davidcz95** [comment]
@ConfidenceYobo have you found any workaround? I have spent 2 days on this and nothing... I think I will.just have to ask my backend guy to.rewrite database, split request for sending nested info and images/files and make nested info json type...

**Comment by ConfidenceYobo** [comment]
@davidcz95 still no fix yet. I had use underscore to separate nested values

**Comment by zartek-apps** [comment]
Please fix this. I need to send data to server as nested formdata. Can we have a fix for this?
