### ISSUE TITLE
type '_OneByteString' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by easazade** [flutterchina/dio#883]
This is an error I get only in release mode (weird) when I'm trying to parse response body of a network request i made into a json map. I put down the code and also the error stacktrace below.
the other wierd thing i should mention is that it only happens sometimes. not all the time. but for the apps i have released on the market when i check the crash reports on firebase this error is also reported there. (it does not cause a crash, though)

**I found out that it happens sometimes but when it happens it keeps happening when i send the same request or sometimes other request over and over. until i quit the app and run it again.**

**Error stacktrace :**
```
I/flutter (31714): type '_OneByteString' is not a subtype of type 'Map<String, dynamic>'
I/flutter (31714): #0      Server.getUser (package:mehrgan/data/network/server.dart:83)
I/flutter (31714): <asynchronous suspension>
I/flutter (31714): #1      Future.wait.<anonymous closure> (dart:async/future.dart:0)
I/flutter (31714): <asynchronous suspension>
I/flutter (31714): type '_OneByteString' is not a subtype of type 'Map<String, dynamic>'
I/flutter (31714): #0      Server.getCourses (package:mehrgan/data/network/server.dart:101)
I/flutter (31714): <asynchronous suspension>
I/flutter (31714): #1      Future.wait.<anonymous closure> (dart:async/future.dart:0)
I/flutter (31714): <asynchronous suspension>
```

**my code :**

```dart
Response response = await _dio.get('user/info');
Map<String, dynamic> json = jsonDecode(jsonEncode(response.data));
```

**additional info :**
platform i test on : android
platform version : 8.0
dio version : 3.0.9
report rate : 5 % of the time only in release mode

**Comment by easazade** [comment]
this is still an issue.

**Comment by ralphnoel13** [comment]
In Release mode, the app is working fine, but after few hours i got this same issue, for me also but if i clear the cache its working perfectly...

**Comment by easazade** [comment]
by clearing cache you mean the application cache?

**Comment by ralphnoel13** [comment]
Yeah @easazade

**Comment by easazade** [comment]
i guess it could be a cache problem since whenever i quit app and launch it again. everything works fine.

**Comment by ralphnoel13** [comment]
Actually, What's the solution for this issue to overcome  @easazade

**Comment by zeuscode** [comment]
this is issue is still, i. meet.

**Comment by Maged12** [comment]
I have the same problem too and it is in shared preferences when I use this line
    bool isFirstTime = Global.prefs?.getBool('isFirstTime') ?? "true";
And the error is 
type '_OneByteString' is not a subtype of type 'bool' 
Any solution ?

**Comment by iamsannyrai** [comment]
@Maged12 you are passing string value in bool type when a value from your shared preference is null.

Should be following..

`bool isFirstTime = Global.prefs?.getBool('isFirstTime') ?? true;`

**Comment by fanchou** [comment]
+1

**Comment by farhan-lapasar** [comment]
Still happen

**Comment by StitchC** [comment]
+1
my issue is info: type '_TwoByteString' is not a subtype of type 'bool'
what a serious!

**Comment by altush1983** [comment]
+1
 type '_OneByteString' is not a subtype of type 'int' of 'index'
in
`final code = response.data["code"];`

**Comment by oleksandrm1608** [comment]
hey, any solution for that ?? it's still an issue for me

**Comment by mouryaavadhesh** [comment]
hey, any solution for that ?? it's still an issue for me
| exception: type '_OneByteString' is not a subtype of type 'Map<String, dynamic>' | [device_info: OPPO_CPH2127_53a2372f1831d9ec_qcom]

**Comment by a475893401** [comment]
type '_OneByteString' is not a subtype of type 'int' of 'index'

**Comment by subzero911** [comment]
I have the similar issue
`type '_TwoByteString' is not a subtype of type 'Map<String, dynamic>'. Error thrown null.`
![image](https://user-images.githubusercontent.com/12999702/169392074-6e11bc36-0859-441c-87c3-7f8163f2a833.png)

**Comment by matiazar** [comment]
I have the same problem. On one device, with released app.

**Comment by dimas-ibnu** [comment]
how can i fix it ? its still appear on my crashlytics

**Comment by Asquare17** [comment]
this is still an issue.

@easazade how did you resolve this? 
It happens only in release mode and to less than 5% of users.

**Comment by easazade** [comment]
@Asquare17  I didn't. it just didn't happen for me when i built the app apk. it just happened sometimes when i ran app in release mode directly on device

**Comment by PawanFyers** [comment]
We have seen the same issue on Crashlytics console:
`io.flutter.plugins.firebase.crashlytics.FlutterError: Exception type '_OneByteString' is not a subtype of type 'int'`

**Comment by FDuhen** [comment]
+1

**Comment by MeherBa** [comment]
how to fix it ? its still appear on my crashlytics console

**Comment by maxzod** [comment]
still appearing on `sentry.io` console

**Comment by IguJl15** [comment]
I am getting the same error when trying to parse a value from api to bool. But I realized that the api I am using is sending boolean in text (`"true"` instead of the _true_ boolean `true`). In our case, this occurs as a safety measure against null values. We created a CustomBoolean enum that has a `not_selected` value to prevent null values from being returned from the api:

``` dart
enum CustomBoolean {
  TRUE,
  FALSE,
  NOT_SELECTED;
}
```

If it is your case I've solved this creating a simple parser:

``` dart
  static CustomBoolean parse(String source) {
    source
      ..replaceAll(" ", "_")
      ..toUpperCase()
      ..trim();

    switch (source) {
      case "TRUE":
        return CustomBoolean.TRUE;
      case "FALSE":
        return CustomBoolean.FALSE;
      default:
        return CustomBoolean.NOT_SELECTED;
    }
  }
```

By doing this we are converting the string from the api to a enum value. To get a bool value you can change the enumeration values on switch statement to booleans has well, in my case I prefered setting values on the enum:

``` dart
enum CustomBoolean {
  TRUE(true),
  FALSE(false),
  NOT_SELECTED(false);

  final bool value;

  const CustomBoolean(this.value);

  static CustomBoolean parse(String source) {
    source
      ..replaceAll(" ", "_")
      ..toUpperCase()
      ..trim();

    switch (source) {
      case "TRUE":
        return CustomBoolean.TRUE;
      case "FALSE":
        return CustomBoolean.FALSE;
      default:
        return CustomBoolean.NOT_SELECTED;
    }
  }
}
```

> Remembering that this is a solution for boolean values where I use enum, but you can use the parse as a standalone function returning boolan value directly.

**Comment by WiRight** [comment]
Check your StackTrace. The first 10 lines will be enough. 

Cover your `runApp` with `runZonedGuarded` or `try/catch` with getting StackTrace/StackTrace.current and in 90% it will be some Map with wrong key data

**Comment by ousvat** [comment]
I still have this issue: `FlutterError: type '_OneByteString' is not a subtype of type 'Map<String, dynamic>' in type cast`

**Comment by mouryaavadhesh** [comment]
Any solution for this?

**Comment by AlexV525** [comment]
This should be fixed already in cce167e.

**Comment by IguJl15** [comment]
@mouryaavadhesh @ousvat 

Can you paste here the StackTrace and the code where the error occurs? So then we can suggest something. But, just as @WiRight pointed above, most of the time this error occurs when accessing a key that exists in a map but with wrong type than what you expect.

In my case, API was returning a string `"true"` instead of the boolean value `true` or `false`. And i was tring to pass the `jsonFromApi["boolValue"]` directly to a `boolean` parameter. 

To solve this, i made a simple parser to read the string and pass it to boolean.
<details><summary>Details</summary>
<p>

``` dart
static bool? tryParseBoolean(String source) {
    source
      ..toUpperCase()
      ..trim();

    switch (source) {
      case "TRUE":
        return true;
      case "FALSE":
        return false;
      default:
        return null;
    }
  }
```

</p>
</details>

**Comment by zakaria02** [comment]
A value of type '_OneByteString' can't be assigned to a variable of type 'String?'. any solution for that?
