### ISSUE TITLE
Transformer 中对json对象生成的兼容问题

### ISSUE THREAD

**Issue by Handy045** [flutterchina/dio#89]
fastjson对于Double和Float类型的字段，如果在转为字符串时过长，在序列化的过程中，fastjson会默认将其转化为科学计数法。

对网络返回的json串转换时，如果出现科学计数法的json会抛异常。
/Users/liujie/Library/Flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-1.0.6/lib/src/transformer.dart:105

异常内容：
Launching lib/main.dart on iPhone XS Max in debug mode...
Starting Xcode build...
Xcode build done.                                            4.0s
Syncing files to device iPhone XS Max...
[VERBOSE-2:shell.cc(182)] Dart Error: Unhandled exception:
DioError [DioErrorType.DEFAULT]: FormatException: Unexpected character (at character 1242)
...,"labelCn":"广西","latitude":23.673975D,"longitude":108.333555D,"parentDis...
                                       ^

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by wendux** [comment]
由于json.encode不支持，所有不行，除非自己实现一个encode.
