### ISSUE TITLE
 For request with OPTIONS method, body erased after fetching

### ISSUE THREAD

**Issue by pinball83** [flutterchina/dio#893]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |                       |   flutter   |
| Platform Version               |                         |   1.17.1    |
| Dio Version                    |                                |    3.0.10   |
| Android Studio / Xcode Version |             |    Android Studio 4.0  |
| Repro rate                     | all the time (100%)    |   all the time (100%   |
| Repro with our demo prj        | does it happen with our demo project?            |   yes   |
| Demo project link              | link to a demo project that highlights the issue |      yes|

### Issue Description and Steps

Request with OPTIONS method, body erased after fetching

**Comment by jamesmoore255** [comment]
Can confirm this is happening with me as well. I have downgraded to 3.0.9 and it works fine.

The response data is always returning as null in any request with Options().
