### ISSUE TITLE
type 'FormData' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by pratamatama** [flutterchina/dio#896]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | ios / android                          |      |
| Platform Version               | 13.6 / 9.0                              |      |
| Dio Version                    | ^3.0.9                                  |      |
| Android Studio / Xcode Version | Android Studio 4.0.1 / Xcode 11.6              |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        | Yes            |      |
| Demo project link              | - |      |

### Issue Description and Steps

Issue:
```
type 'FormData' is not a subtype of type 'Map<String, dynamic>'
```

The issue happened when uploading files using `FormData.fromMap(data)`.

```dart
final Map<String, dynamic> data = Map<String, dynamic>();
        data['title'] = event.title;
        data['chronology'] = event.chronology;
        data['images'] = event.images; // List<MultipartFile>
        data['participants'] = event.participants;

final Response response =
          await httpClient.post('fieldReports', data: FormData.fromMap(data));
```

**Comment by pratamatama** [comment]
My bad, it was my logger.

**Comment by gautamswostik** [comment]
how did you fix it btw?
