### ISSUE TITLE
dio 异常拦截器不起作用

### ISSUE THREAD

**Issue by DNetORM** [flutterchina/dio#904]
异常从这里抛出来了

if (statusOk) {
        return checkIfNeedEnqueue(interceptors.responseLock, () => ret);
      } else {
        throw DioError(
          response: ret,
          error: 'Http status error [${responseBody.statusCode}]',
          type: DioErrorType.RESPONSE,
        );
      }
    } catch (e) {
      throw assureDioError(e, options);
    }

我这里加的异常拦截 没有走到
dio.interceptors
        .add(InterceptorsWrapper(onRequest: (RequestOptions options) async {
      // Do something before request is sent
      return options; //continue
      // If you want to resolve the request with some custom data，
      // you can return a `Response` object or return `dio.resolve(data)`.
      // If you want to reject the request with a error message,
      // you can return a `DioError` object or return `dio.reject(errMsg)`
    }, onResponse: (Response response) async {
      // Do something with response data
      return response; // continue
    }, onError: (DioError e) async {
      // Do something with response error

**Comment by DNetORM** [comment]
具体的现象就是 我dio里增加了异常拦截器，前台页面调用dio,前台页面我没有对dio进行try catch处理，因为dio我统一添加了异常拦截，现在的问题是，在debug模式，vscode调试，首先插件的源码里先抛了一个异常，然后拦截器捕获，最后异常又抛到了前台，那我这个一阿昌拦截器起到什么作用？没有替我前台页面去处理啊，我还要再加上try catch机制么，那拦截器的其意义不大

**Comment by ipcjs** [comment]
格式下代码吧(;¬_¬)

异常拦截器不是做这个用的，你觉得每次try...catch麻烦，可以写个函数：
```
void _onErrorToLog(dynamic error, StackTrace st) {
  L.warn('runCatching.onError', error: error, stackTrace: st);
}

/// 捕获异步函数[block]抛出的异常
Future<R> runCatchingFuture<R>(Future<R> block(), [Function onError = _onErrorToLog]) => block().catchError(onError);
```
