### ISSUE TITLE
抓包修改接口数据后报错：DioError [DioErrorType.RESPONSE]: Http status error [400]

### ISSUE THREAD

**Issue by mry1** [flutterchina/dio#906]
#### 错误描述：
1. 正常情况下通过接口请求数据是没问题的，通过Charles抓包修改接口中的数据后，代码中就会报错，提示DioError [DioErrorType.RESPONSE]: Http status error [400]
2. 用Charles通过map的方式修改接口数据不会报错，但是返回的response.data会变成String类型，正常应该是map类型

**Comment by pmrajani** [comment]
Why dio throw error in release mode for iOS?
ios debug and android release/debug build works fine.

using :   dio: ^3.0.10

ERROR: DioError [DioErrorType.RESPONSE]: Http status error [400] \nSTACK: #0      DioMixin._dispatchRequest (package:dio/src/dio.dart:966)\n<asynchronous suspension>\n#1      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart)\n<asynchronous suspension>

**Comment by mry1** [comment]
问题还是没修复

**Comment by popeyelau** [comment]
@mry1 
```dart
Options(validateStatus: (status) => true)
```
 尝试将 `validateStatus` 直接返回 `true` 试试

**Comment by iloveq** [comment]
> #### DIO版本：3.0.4
> #### 错误描述：
> 1. 正常情况下通过接口请求数据是没问题的，通过Charles抓包修改接口中的数据后，代码中就会报错，提示DioError [DioErrorType.RESPONSE]: Http status error [400]
> 2. 用Charles通过map的方式修改接口数据不会报错，但是返回的response.data会变成String类型，正常应该是map类型

3.0.10 还未修复

**Comment by iloveq** [comment]
3.0.10 还未修复辛苦再重新 reopen 下

**Comment by xiaobo57block** [comment]
When the IOS Release is loading, lock the screen immediately and unlock it in a few seconds. The interface invocation fails. Debug version works.

**Comment by xiaobo57block** [comment]
In DIO 4.0.0, when the interface is loading, lock the screen immediately, unlock after a few seconds, the interface call fails. Debug version works.

**Comment by xiaobo57block** [comment]
In DIO 4.0.0, when the interface is loading, lock the screen immediately, unlock after a few seconds, the interface call fails. is loading, lock the screen immediately, unlock after a few seconds, the interface call fails. The error message is as follows:
DioError [DioErrorType.other]: HttpException: , uri = https://xxxx
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>

**Comment by loveppp** [comment]
4.0.0 DioError [DioErrorType.other]: HttpException: Both Content-Length and Transfer-Encoding are specified, at most one is allowed.   use charles to change the response data   the error was hinted

**Comment by Linnxh** [comment]
dio 4.0  DioError [DioErrorType.other]: HttpException: Both Content-Length and Transfer-Encoding are specified, at most one is allowed, uri = http:
