### ISSUE TITLE
flutter 1.20.2 dio 3.0.10 还是会有这个超时的问题

### ISSUE THREAD

**Issue by xinde** [flutterchina/dio#911]
flutter 1.17.3 dio 3.0.9 还是会又这个问题

_Originally posted by @xinde in https://github.com/flutterchina/dio/issues/377#issuecomment-643943411_

**Comment by heimabailang** [comment]
遇到过，有人解决了？

**Comment by xinde** [comment]
> 遇到过，有人解决了？

暂时还没看到

**Comment by xinde** [comment]
:(

**Comment by iOSQiao** [comment]
我遇到了，不管是用trycatch还是用catchError都无法捕获异常 Http status error [404]，页面直接卡死了。只要请求都url不正确，App就会卡死。
