### ISSUE TITLE
Question about keep alive

### ISSUE THREAD

**Issue by tapkain** [flutterchina/dio#912]
Does the underlying http handler has support for keep-alive? Because it looks like dart is not caching tls handshake and the request are slower.

**Comment by tapkain** [comment]
up!

**Comment by lianshumin** [comment]
up

**Comment by TheCrazyT** [comment]
You are probably not interested anymore but incase someone else is searching for it I will post my findings here.

It looks like there is a `idleTimeout` (see https://github.com/cfug/dio/blob/main/dio/lib/src/adapters/io_adapter.dart#L198).
Default is 3 seconds.
So if you don't do anything for 3 seconds the connection will get closed and it will use a new connection next time.
Sadly I believe that this also seems to force a reconnection if your rest-service itself needs more than 3 seconds.
(atleast thats my observation with flutter dev tools)
Although this won't disrupt an active connection, it can still be annoying.

I'm not shure, if there is a "normal" way to configure it.
But for servers that understand http 2.0 you could probably use the example there:
[dio_http2_adapter](https://github.com/cfug/dio/blob/main/plugins/http2_adapter/README.md)
to increase the timeout.
