### ISSUE TITLE
Sharing custom interceptor between 2 Dio instance

### ISSUE THREAD

**Issue by fvisticot** [flutterchina/dio#92]
I would like to use the same Interceptor logic in 2 Dio instance.
It seems I can not do a think like

Interceptor myInerceptor = Interceptor();
myInterceptor.onSend() ...

Dio dio1 = Dio();
Dio dio2 = Dio();
dio1.interceptor=myInterceptor;
dio2.interceptor=myInterceptor;

Any solution ?

**Comment by wendux** [comment]
You can only do it separately:
```dart
dio1.interceptor.request.onSend=_onSend;
dio2.interceptor.request.onSend=_onSend;
....
```
