### ISSUE TITLE
dio: ^3.0.10 无法上传文件

### ISSUE THREAD

**Issue by lsy12-github** [flutterchina/dio#935]
Android 真机调试，代码调用到await dio.post(path, data: data);时出错无法提交到后台，报错如下：SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = x.x.x.x, port = 44409

**Comment by John-tp** [comment]
same problem happened

**Comment by John-tp** [comment]
之前用dio包上传文件到阿里云oss存储库里面一切正常，就在那一天之后，一切都变了，一直报错：
<Error>
      MethodNotAllowed
      <Message>The specified method is not allowed against this resource.</Message>
      <RequestId>5F70333A8338063837E4E2D8</RequestId>
      <HostId>img.fengyuncx.com</HostId>
      <Method>POST</Method>
      <ResourceType>Bucket</ResourceType>
    </Error>
提交工单也是好几天没有解决，突然想到是不是dio的锅，果然改成3.0.9之后一切都正常了

**Comment by xuzhongpeng** [comment]
the same problem

**Comment by SUNbrightness** [comment]
the same problem to

**Comment by wsb1689** [comment]
hi bro how to sovle it ?
