### ISSUE TITLE
DioError [DioErrorType.DEFAULT]: SocketException

### ISSUE THREAD

**Issue by coder-xb** [flutterchina/dio#936]
### DioError [DioErrorType.DEFAULT]: SocketException

- I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Flutter                          |      |
| Platform Version               | 1.20.0                              |      |
| Dio Version                    | 3.0.10                                  |      |
| Android Studio / Xcode Version | Android Studio 4.0.1 / Xcode 11.1 (11A1027)              |      |
| Repro rate                     | sometimes 90% (As long as it appears, it will always appear)    |      |
| Repro with our demo prj        | I don't know it, I haven't tried it with the demo, the time limit is tight           |      |
| Demo project link              | Sorry, This APP is in the development stage and not yet online |      |

### Issue Description

Exception message: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'goat.cacifu.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

As long as this problem occurs, restart the emulator or mobile phone to be normal, but it will recur after a while.

After testing, the server configuration is normal and correctly configured.

**Comment by missXb** [comment]
The latest discovery is that I initiated multiple requests on a page without using the Future.wait([Futures]) method. I don’t know if it is caused by this. After I changed to Future.wait([Futures]) method, it seems to be normal, but it remains to be seen.

**Comment by missXb** [comment]
After observation and testing, the problem still exists after switching to Future.wait([Futures])

**Comment by missXb** [comment]
> your problem will easily solved all u have to do is to add this line in your Android>app>main>src>AndroidManifesto.xml file
> `<uses-permission android:name="android.permission.INTERNET" /> `
> after the package name or under the manifesto tag

Thank you very much for your answer. I have configured and checked as you said. Whether the problem still exists or not remains to be seen. In addition, according to my observation during this period, I found that the problem may be whether my computer uses a proxy or not.

**Comment by coder-xb** [comment]
Hello, I encountered the same problem as the class.
