### ISSUE TITLE
Is it necessary to check _completer.isCompleted  when call cancelToken.cancel  

### ISSUE THREAD

**Issue by philos3** [flutterchina/dio#946]
## * Calling [complete] or [completeError] must be done at most once.

CancelToken class
  /// Cancel the request
  void cancel([dynamic reason]) {
    _cancelError = DioError(type: DioErrorType.CANCEL, error: reason);
    _completer.complete();
  }

is it necessary to check _completer.isCompleted

  /// Cancel the request
  void cancel([dynamic reason]) {
    _cancelError = DioError(type: DioErrorType.CANCEL, error: reason);
    if(!_completer.isCompleted){
      _completer.complete();
    }
  }

**Comment by hatemragab** [comment]
i face this exception when cancel the download again download again    Bad state: Future already completed
