### ISSUE TITLE
on download get (getaddrinfo: get result from proxy gai_error = 0)

### ISSUE THREAD

**Issue by ali-1989** [flutterchina/dio#948]
Hi,  I see 'getaddrinfo: get result from proxy gai_error = 0' when download from any link.

### Issue Info

Platform Name                  flutter- android (api 24, android 7)
Platform Version               flutter 1.17   
Dio Version                   3.0.10
Android Studio             3.1

**Comment by leadenpraise** [comment]
i am face with the same issue... any help will be appreciated
