### ISSUE TITLE
Dio post response is always return empty list.

### ISSUE THREAD

**Issue by shinewanna** [flutterchina/dio#953]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter / ios / android                          |      |
| Dio Version                    | ^3.0.10                                 |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2 / Xcode 11.7
<img width="870" alt="Screen Shot 2020-10-01 at 5 32 01 PM" src="https://user-images.githubusercontent.com/39454969/94801438-0aaa8c80-040c-11eb-84c3-5160257909d5.png">

              |      |
| Repro rate                     | e.g. all the time (100%) / sometimes x% / only once   |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.
`  Future<ResponseOb> postRequestWithDio(
      {String firstUrl = DEFAULT,
      String endUrl,
      Map<String, dynamic> body,
      bool isWallet = false}) async {
    String language =
        await SharedPref.getData(key: SharedPref.langauge) ?? "en";

    print(HTTP + BASE_URL + "/$language" + endUrl);
    ResponseOb rv = ResponseOb();
    Dio dio = Dio();

    return getHeader(firstUrl: firstUrl).then((header) {
      FormData fd = FormData.fromMap(body);

      dio.options.baseUrl = HTTP + BASE_URL + "/$language";
      dio.options.headers =  {
      "Authorization": await SharedPref.getData(key: SharedPref.auth),
      "ISAPI": "1",
      "Accept": "application/json",
      "Content-Type": "application/x-www-form-urlencoded",
      "website-name": firstUrl,
    };
      return dio.post(endUrl, data: fd).then((res) {
        print(res.data);
        Map<String, dynamic> map = res.data;
        if (map['status_code'] == 401) {
          rv.message = MsgState.unauthorized;
          rv.data = map['message'].toString();
        } else {
          if (res.statusCode == 200) {
            rv.message = MsgState.data;
            rv.data = res.data;
          } else {
            rv.message = MsgState.error;
            rv.data = "Data Fetching Error";
          }
        }
        return rv;
      }).catchError((e) {
        print(e.toString() + ">>");
        if (e is SocketException) {
          rv.message = MsgState.error;
          rv.data = "No Internet";
        } else {
          rv.message = MsgState.error;
          rv.data = "Data ${e.toString()} Error ";
        }
        return rv;
      });
    });
  }`

**Comment by cn-Meepo** [comment]
Hi,Have you solved the problem yet?

**Comment by shinewanna** [comment]
LoL, very delay reply.Yes, that's solved by upgrading the dio package.
