### ISSUE TITLE
is it possible to call api with relative path in web ?

### ISSUE THREAD

**Issue by leexikang** [flutterchina/dio#955]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | web                 |      |
| Platform Version               |                               |      |
| Dio Version                    | 3.0.10                                  |      |
| Android Studio / Xcode Version | Xcode 10.2.1              |      |
| Repro rate                     | all the time (100%)  |      |
| Repro with our demo project        |         |      |
| Demo project link              |  |      |

### Is is possible to use relative path in calling api ?
The situation is that both the frontend and backend on the same server, is there anyway I can set the base url so that the api will be calling on the same server ?  
 I tried to call the api with baseurl without http prefixs,  eg('/api') but got the following error. 
```dart
Unknown Exception: DioError [DioErrorType.DEFAULT]: RangeError (index): Index out of range: index should be less than 1: 1
throw_ (dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart:212:49))
_get] (dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart:579:7))
packages/dio/src/options.dart 301:29                                          get uri

```
Thanks

**Comment by shinsenter** [comment]
Same issue
