### ISSUE TITLE
flutter web - dio bloc's (freezes) ui while getting json response

### ISSUE THREAD

**Issue by kele82** [flutterchina/dio#961]
Using default flutter project simple dio.get freezes CircularProgressIndicator while receiving response.
Tested first on iphone and ipad, works fine.
Then converted project to flutter web.

//code 
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 1;
  

  void _incrementCounter() async {

    setState(() {
      _counter++;
    });

    if (_counter % 2 == 0){
      try {
        print("Call api");
        var dio = Dio();

        Response response = await dio.get('https://antara.oxyproductservices.com/all');

        if(response.statusCode == 200) {
          print('Status ok');
          print(response.data);
        }else{
          print('ERROR -- ${response.statusCode}');
        }
      }catch(error){
        print('Dio error: $error');
      }

    }

  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            _presentProgress(),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  _presentProgress() {
    if (_counter % 2 == 0){
      return CircularProgressIndicator();
    }else{
      return Text('Press (+) to send Api request');
    }
  }

}

**Comment by LucaIaconelli** [comment]
same problem here

**Comment by Oualitsen** [comment]
Same problem.
One small addition here.
I tested posting the same request with standart http in flutter it works as expected and does not hang.

**Comment by despie** [comment]
This is still the issue in `dio: ^3.0.10`

**Comment by Oualitsen** [comment]
Hello guys; I use the following adapter for the web and things works just fine for me.

`import 'dart:async';
import 'dart:typed_data';
import 'package:dio/dio.dart';
import 'package:universal_html/html.dart' as html;

class WebClientAdapter implements HttpClientAdapter {
  /// These are aborted if the client is closed.
  final _xhrs = <html.HttpRequest>[];

  /// Whether to send credentials such as cookies or authorization headers for
  /// cross-site requests.
  ///
  /// Defaults to `false`.
  ///
  /// You can also override this value in Options.extra['withCredentials'] for each request
  bool withCredentials = false;

  @override
  Future<ResponseBody> fetch(RequestOptions options, Stream<List<int>> requestStream, Future cancelFuture) async {
    var xhr = html.HttpRequest();
    _xhrs.add(xhr);

    xhr
      ..open(options.method, options.uri.toString(), async: true)
      ..responseType = 'blob'
      ..withCredentials = options.extra['withCredentials'] ?? withCredentials;
    options.headers.remove(Headers.contentLengthHeader);
    options.headers.forEach((key, v) => xhr.setRequestHeader(key, '$v'));
    var completer = Completer<ResponseBody>();

    xhr.onLoad.first.then((_) {
      // TODO: Set the response type to "arraybuffer" when issue 18542 is fixed.
      var blob = xhr.response ?? html.Blob([]);
      var reader = html.FileReader();

      reader.onLoad.first.then((_) {
        var body = reader.result as Uint8List;

        completer.complete(
          ResponseBody.fromBytes(
            body,
            xhr.status,
            headers: xhr.responseHeaders.map((k, v) => MapEntry(k, v.split(','))),
            statusMessage: xhr.statusText,
            isRedirect: xhr.status == 302 || xhr.status == 301,
          ),
        );
      });

      reader.onError.first.then((error) {
        completer.completeError(
          DioError(
            type: DioErrorType.RESPONSE,
            error: error,
            request: options,
          ),
          StackTrace.current,
        );
      });

      reader.readAsArrayBuffer(blob);
    });

    xhr.onError.first.then((_) {
      // Unfortunately, the underlying XMLHttpRequest API doesn't expose any
      // specific information about the error itself.
      completer.completeError(
        DioError(
          type: DioErrorType.RESPONSE,
          error: 'XMLHttpRequest error.',
          request: options,
        ),
        StackTrace.current,
      );
    });

    cancelFuture?.then((_) {
      if (xhr.readyState < 4 && xhr.readyState > 0) {
        try {
          xhr.abort();
        } catch (e) {
          // ignore
        }
      }
    });

    if (requestStream == null) {
      xhr.send();
    } else {
      List<int> r = [];
      List<List<int>> listOfLists = await requestStream.toList();
      for (int i = 0; i < listOfLists.length; i++) {
        r.addAll(listOfLists[i]);
      }
      xhr.send(Uint8List.fromList(r));
    }
    return completer.future.whenComplete(() {
      _xhrs.remove(xhr);
    });
  }

  /// Closes the client.
  ///
  /// This terminates all active requests.
  @override
  void close({bool force = false}) {
    if (force) {
      for (var xhr in _xhrs) {
        xhr.abort();
      }
    }
    _xhrs.clear();
  }
}
`

**Comment by Oualitsen** [comment]
This worked for me for the **Web**
The issue was actually using functional transformations to the request body. When the request body if a long byte array the UI just freezes.
I tried to come out with so many theories (Java-wise) with multi-threading but ended up changing the functional transformation to a for loop.
Please check out the code and let me know if it works for you.
`class WebClientAdapter implements HttpClientAdapter {
  final _xhrs = <html.HttpRequest>[];

  bool withCredentials = false;

  @override
  Future<ResponseBody> fetch(
      RequestOptions options, Stream<List<int>> requestStream, Future cancelFuture) async {
    var xhr = html.HttpRequest();
    _xhrs.add(xhr);

    xhr
      ..open(options.method, options.uri.toString(), async: true)
      ..responseType = 'blob'
      ..withCredentials = options.extra['withCredentials'] ?? withCredentials;
    options.headers.remove(Headers.contentLengthHeader);
    options.headers.forEach((key, v) => xhr.setRequestHeader(key, '$v'));
    var completer = Completer<ResponseBody>();

    xhr.onLoad.first.then((_) {
      var blob = xhr.response ?? html.Blob([]);
      var reader = html.FileReader();

      reader.onLoad.first.then((_) {
        var body = reader.result as Uint8List;

        completer.complete(
          ResponseBody.fromBytes(
            body,
            xhr.status,
            headers: xhr.responseHeaders.map((k, v) => MapEntry(k, v.split(','))),
            statusMessage: xhr.statusText,
            isRedirect: xhr.status == 302 || xhr.status == 301,
          ),
        );
      });

      reader.onError.first.then((error) {
        completer.completeError(
          DioError(
            type: DioErrorType.RESPONSE,
            error: error,
            request: options,
          ),
          StackTrace.current,
        );
      });

      reader.readAsArrayBuffer(blob);
    });

    xhr.onError.first.then((_) {
      completer.completeError(
        DioError(
          type: DioErrorType.RESPONSE,
          error: 'XMLHttpRequest error.',
          request: options,
        ),
        StackTrace.current,
      );
    });

    cancelFuture?.then((_) {
      if (xhr.readyState < 4 && xhr.readyState > 0) {
        try {
          xhr.abort();
        } catch (e) {
          // ignore
        }
      }
    });

    if (requestStream == null) {
      xhr.send();
    } else {
      List<int> r = [];
      List<List<int>> listOfLists = await requestStream.toList();
      for (int i = 0; i < listOfLists.length; i++) {
        r.addAll(listOfLists[i]);
      }
      xhr.send(Uint8List.fromList(r));
    }
    return completer.future.whenComplete(() {
      _xhrs.remove(xhr);
    });
  }

  @override
  void close({bool force = false}) {
    if (force) {
      for (var xhr in _xhrs) {
        xhr.abort();
      }
    }
    _xhrs.clear();
  }
}
`

**Comment by Oualitsen** [comment]
> This is still an issue in `dio: ^3.0.10`
> And this holds true not only for the web, but also for both iOS & Android.
> As soon as the data starts to load, the UI becomes unresponsive for a while.

Checkout My solution above and I hope it'll work for you too on the web.

**Comment by rajivrajan** [comment]
A simpler solution is to understand what 'await' does. The reason your requests are getting queued, is because await explicitly asks that of the framework. the solution would be to use 
```
dio.get('https://antara.oxyproductservices.com/all').then((result){
   add(ApiResponseEvent(result));
}).catchError((error){
 //catch and handle error
});

```

**Comment by kele82** [comment]
Can anyone confirm this?
Remi doesn't think so.
https://stackoverflow.com/questions/62823273/why-in-this-code-await-is-not-blocking-ui-in-flutter

**Comment by maicolstracci** [comment]
Same problem here

**Comment by arthurdlima** [comment]
I'm still having this problem on flutter web. Any solutions?

**Comment by moniaS** [comment]
Same problem here

**Comment by altafkhan8719** [comment]
same problem here , it taking 3 to 4 second to load data,
same URL on postman it take 500 to 600 millisecond.
please provide a solution

**Comment by Oualitsen** [comment]
Salam @altafkhan8719
Here is the solution I adopted after hours of googling
Below is a modified version of web adapter.

`import 'dart:async';
import 'dart:typed_data';
import 'package:dio/dio.dart';
import 'package:universal_html/html.dart' as html;

class WebClientAdapter implements HttpClientAdapter {
  final _xhrs = <html.HttpRequest>[];

  bool withCredentials = false;

  @override
  Future<ResponseBody> fetch(
      RequestOptions options, Stream<List<int>> requestStream, Future cancelFuture) async {
    var xhr = html.HttpRequest();
    _xhrs.add(xhr);

    xhr
      ..open(options.method, options.uri.toString(), async: true)
      ..responseType = 'blob'
      ..withCredentials = options.extra['withCredentials'] ?? withCredentials;
    options.headers.remove(Headers.contentLengthHeader);
    options.headers.forEach((key, v) => xhr.setRequestHeader(key, '$v'));
    var completer = Completer<ResponseBody>();

    xhr.onLoad.first.then((_) {
      var blob = xhr.response ?? html.Blob([]);
      var reader = html.FileReader();

      reader.onLoad.first.then((_) {
        var body = reader.result as Uint8List;

        completer.complete(
          ResponseBody.fromBytes(
            body,
            xhr.status,
            headers: xhr.responseHeaders.map((k, v) => MapEntry(k, v.split(','))),
            statusMessage: xhr.statusText,
            isRedirect: xhr.status == 302 || xhr.status == 301,
          ),
        );
      });

      reader.onError.first.then((error) {
        completer.completeError(
          DioError(
            type: DioErrorType.RESPONSE,
            error: error,
            request: options,
          ),
          StackTrace.current,
        );
      });

      reader.readAsArrayBuffer(blob);
    });

    xhr.onError.first.then((_) {
      completer.completeError(
        DioError(
          type: DioErrorType.RESPONSE,
          error: 'XMLHttpRequest error.',
          request: options,
        ),
        StackTrace.current,
      );
    });

    cancelFuture?.then((_) {
      if (xhr.readyState < 4 && xhr.readyState > 0) {
        try {
          xhr.abort();
        } catch (e) {
          // ignore
        }
      }
    });

    if (requestStream == null) {
      xhr.send();
    } else {
      List<int> r = [];
      List<List<int>> listOfLists = await requestStream.toList();
      for (int i = 0; i < listOfLists.length; i++) {
        r.addAll(listOfLists[i]);
      }
      xhr.send(Uint8List.fromList(r));
    }
    return completer.future.whenComplete(() {
      _xhrs.remove(xhr);
    });
  }

  @override
  void close({bool force = false}) {
    if (force) {
      for (var xhr in _xhrs) {
        xhr.abort();
      }
    }
    _xhrs.clear();
  }
}
`
In the initialization of my web services I use dio with this web adapter like below
`Future<void> initDio() async {
  GetIt instance = GetIt.instance;
  Dio dio = Dio(BaseOptions(baseUrl: getUrlBase()));

  if (kIsWeb) {
    CookieManager manager = CookieManager(CookieJar());
    dio.interceptors.add(manager);

--------------------->    dio.httpClientAdapter = WebClientAdapter();
  } else {
    

  }

  
}`

**Comment by xellDart** [comment]
same error

**Comment by giaur500** [comment]
Is that web only issue? On Android/iOS I don't get any difference, both default http client and dio give the same load time and no freezes. I use dio to make simple rest calls, but response may be large in some cases. Overall, response and load time is similar to default http client and native Android OkHttp with gson.

**Comment by livotov** [comment]
@giaur500 I just quickly checked with Android on the same endpoint/dataset - it seems it happens there too. Not as badly as for web - ~1.5 sec complete UI freeze (Android) vs 15 sec freeze on web.  But freeze still happens. Just not noticeable on smaller datasets in comparison to web, I suppose.

**Comment by giaur500** [comment]
Do you use isolates to parse json? I see no freezes and response size is ~400 kB. Dio version 4.0.0, but 3.10 was ok to as far as I remember.

**Comment by livotov** [comment]
No isolates. Just Retrofit + Dio. My response is 1.5 MB in size, could it make difference? 

there is an "update in progress" spinner in appbar of my app, so it is clearly visible:

- "refresh" button pressed
- progress indicator starts spinning, spins for about 5 to 7 seconds - this is transmission time for 1.5 MB
- then it freezes (entire UI too - I cannot swipe pages or list) for 1 to 1.5 sec
- then data gets updated, everything unfreezes

simply replacing Retrofit/Dio call to HTTP client one + manual obj.fromJson(...) - gets same 5-7 secs timing for the network but no any freeze then. The timing for obj.fromJson(jsonDecode(...)) for this payload is only 157 ms

so it seems this functional transformation of the request body "eats" the main thread (even if run in isolate) and this most noticeably affects web targets. Dunno whether this is a language/compiler or flutter issue or not.

**Comment by giaur500** [comment]
Try to use Dio (without Retrofit) to see what happens.  Also, you should notice Dio has its defualt transformer for json, maybe it causes freezes?

I use raw reponse this way:
`Response<String> response = await dio.get(....)` so I guess no transformation is used in this case.

**Comment by maares** [comment]
Hi guys, I'm also interested in this particular subject. Making a request with Dio on Flutter Web freezes completely the UI. After 2 days without any elegant solution to the problem, decided to switch request client for certain api calls with http. Literally no issues when switching.

Has anyone come up with a solution?
Thanks in advance

**Comment by Mooibroek** [comment]
Still having this in the latest version of dio (4.0.0). I tried using an isolate to do the json_decode but still a good bit of jank after the response comes in. If needed I can provide a test project to simulate this behaviour. Anyone else got a viable solution to the problem?

**Comment by maares** [comment]
@Mooibroek unfortunatelly the only work around at least for me was to make request with different client for web, mobile works good, but probably will finally migrate all to only one request client in order not to have extra logic by using 2 clients. :(

**Comment by Mooibroek** [comment]
I've got the problem on macos now, ill try the mobile and see how that goes.

**Comment by livotov** [comment]
Just FYI - we completely abandoned both DIO and Retrofit due to that. 
We still use json_serializable for mapping complex JSON objects and for the rest we do use the plain HTTP client. It does not add much boilerplate and remains flexible.

**Comment by livotov** [comment]
@maares mobile works faster (probably due to native code) but is affected by the same issue - the lag is just much smaller in comparison to the web. So, IMO, no need to use 2 clients, just move away from DIO/Retrofit. As I mentioned above - standard HTTP package syntax is quite nice and simple, still flexible

**Comment by Mooibroek** [comment]
Yeah lag on mobile is also there, but less then on macos. Shame really. For now its not a deal breaker for this project, but definitely something to take into account for new projects in the future.

**Comment by giaur500** [comment]
How do you use basic http client on web? In my case no matter what I do, I'm getting exception "Unsupported operation: Platform._version", even if I do what they suggested, exception is still there.

**Comment by maares** [comment]
@livotov thanks for actually observing lag is on mobile as well, honestly I did not notice on Mobile. A shame, this was actually one of the first packages I installed when starting playing around with flutter.

Hopefully at some point this will be addressed

**Comment by bayufajariyanto** [comment]
I encountered a similar issue, but I managed to solve it by simply adding validateStatus to my Dio configuration:

```dart
Dio(BaseOptions(
  baseUrl: Urls.base,
  headers: {
    'Content-Type': 'application/json',
  },
  connectTimeout: const Duration(seconds: 2),
  receiveTimeout: const Duration(seconds: 2),
  validateStatus: (status) => status! >= 200 && status < 500,
));
```

With `validateStatus`, I allow Dio to treat all responses with status codes from 200 to 499 as valid, preventing unnecessary exceptions for client errors (like 400 or 401), which I can then handle within my application.
