### ISSUE TITLE
dio: ^3.0.9 post 请求 data传参，后台拿不到请求参数，改成queryParameters之后请求参数过长直接400

### ISSUE THREAD

**Issue by shiner0** [flutterchina/dio#963]
dio: ^3.0.9 post 请求 data传参，后台拿不到请求参数，改成queryParameters之后请求参数过长直接400

**Comment by cn-Meepo** [comment]
请问解决了吗？我也是有时候拿不到body里的参数

**Comment by 18363853135** [comment]
有解决思路吗。我也遇到这个问题  参数过长 queryParameters 报错。data传参数。后台拿不到
