### ISSUE TITLE
Slow on web?

### ISSUE THREAD

**Issue by fischerscode** [flutterchina/dio#964]
I've noticed that dio seems to be about 9 times slower then http when fetching 1mb of data on web.
That seems weird to me. Am I doing something wrong?

```dart
// activate the download here: https://www.speedtestx.de/
import 'package:dio/dio.dart' as dio;
import 'package:http/http.dart' as http;

void main() async {

  await getHttp();
  await getDio();
}

Future<void> getDio() async {
  DateTime start = DateTime.now();
  try {
    await dio.Dio().get("https://www.speedtestx.de/testfiles/data_1mb.test");
    print("Dio: ${DateTime.now().difference(start)}");
  } catch (e) {
    print(e);
  }
}

Future<void> getHttp() async{
  DateTime start = DateTime.now();
  try {
    await http.get("https://www.speedtestx.de/testfiles/data_1mb.test");
    print("Http: ${DateTime.now().difference(start)}");
  } catch (e) {
    print(e);
  }
}
```
Output:
> Http: 0:00:00.490000
> Dio: 0:00:04.583000

I am using dio `3.0.10` and dart `2.11.0-213.1.beta (beta)`.

**Comment by peterlauri** [comment]
We also experience the same problem.

**Comment by LucaIaconelli** [comment]
Is there any news about it?

**Comment by peterlauri** [comment]
> Is there any news about it?

We migrated away to use basic http.Client provided by Flutter/Dart.

**Comment by LucaIaconelli** [comment]
With http provided by Flutter/Dart,  how do you set up withCredentials variable in BrowserClient?

**Comment by peterlauri** [comment]
> With http provided by Flutter/Dart, how do you set up withCredentials variable in BrowserClient?

Our app uses JWT authentication, so we just use plain headers for doing that. 

```
http.get(url, headers={'Authorization': 'JWT $token'})
```

**Comment by LucaIaconelli** [comment]
But unfortunately, this doesn't solve my problem using Cookies

**Comment by LucaIaconelli** [comment]
There is no plan to update this library for solving this problem? @wendux 

Thanks in advance

**Comment by nstrelow** [comment]
Is dio still slow on web?

**Comment by coduy96** [comment]
> Is dio still slow on web?

yes

**Comment by woprandi** [comment]
Few seconds before uploading a file...

**Comment by amirmhmdi** [comment]
I'm on flutter 2.2.2 and every thing okay on android and iOS ! but on web is so slow.
I used dio 3.0.0 and dio 4.0.0 but it took about 3 sec to fetch data but when I use http.get it take about 100ms .
any update ?

**Comment by intraector** [comment]
same problem

**Comment by jgoyvaerts** [comment]
This issue has been fixed on our fork of dio, [dio_http](https://github.com/dart-tools/dio_http).

Package is available here: https://pub.dev/packages/dio_http

**Comment by tomekit** [comment]
Nowadays with Flutter: `3.19.5` and
```
http: ^1.2.1
dio: ^5.4.2+1
```
I find them both unacceptably slow on Web, however on desktop or mobile it is just fine.

https://github.com/flutter/flutter/issues/146494
