### ISSUE TITLE
"Stream" response type not working on Flutter Web

### ISSUE THREAD

**Issue by hivesey** [flutterchina/dio#966]
### New Issue Checklist

- [Y ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

"Stream" response type is not working on Flutter web; the below code works fine on mobile platform but the request posted to the server is never returned on web.

Response<ResponseBody> rs = await Dio().get<ResponseBody>(url,
 options: Options(responseType: ResponseType.stream), // set responseType to `stream`
);

**Comment by renenucci** [comment]
Hi guys, have some news into this? I'm facing the same issue with flutter 2 SDK.
the await never returns after the request is send (only in web). Android and iOS works fine.

[]s

**Comment by mrsrmn** [comment]
this issue is still happening.

**Comment by kuhnroyal** [comment]
This will never work with current XHR based implementation. Generally please don't comment on issues that have been closed 4 years ago.
