### ISSUE TITLE
Http2Adapter uses always http2 even when endpoint doesn't support it

### ISSUE THREAD

**Issue by FrantisekGazo** [flutterchina/dio#972]
### Issue Info

| Info                           | Value                                                 |
| ------------------------------ | ----------------------------------------------------- |
| Platform Name                  | flutter                          |
| Platform Version               | 1.20.4                              |     
| Dio Version                    | 3.0.10                                  |     
| Http2Adapter Version                    | 1.0.1                                  |   
| Android Studio / Xcode Version | Android Studio 4.0.1              |     
| Repro rate                     | all the time (100%)  |  
| Repro with our demo prj        |  no          |      |

### Issue Description and Steps

When I make post request to an endpoint that doesn't support http2 the request fails with error like here https://github.com/flutterchina/dio/issues/486 , but it doesn't happen if endpoint supports http2. 

The http1 should still be supported as a fallback and not force to use http2 always.

**Comment by sd148684** [comment]
We are facing the same issue here, is there any plan for implement a http/1.1 downgrade strategy, or have a workaround at least?
