### ISSUE TITLE
CONNECT_TIMEOUT too many times

### ISSUE THREAD

**Issue by asiaWang** [flutterchina/dio#975]
when i request a url,CONNECT_TIMEOUT happened too many times,can you help me to solve this issue?

I/flutter ( 7221): DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out [5000ms]
I/flutter ( 7221): 
E/flutter ( 7221): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out [5000ms]
E/flutter ( 7221): #0      DioMixin._request._errorInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:870:17)
E/flutter ( 7221): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 7221): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 7221): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 7221): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 7221): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 7221): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 7221): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 7221): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 7221): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7221): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 7221): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 7221): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 7221): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by chendeji** [comment]
I have same problem. When upload files this problem happens many times.

**Comment by wozhizhizhi** [comment]
TIMEOUT usually a network problem, please check whether network permissions have been added

**Comment by sj1910** [comment]
I have same problem.Check to make sure the network is ok, as is the native interface.

**Comment by Defuera** [comment]
I confirm, this happens to me as well. In my case I observe this behavior if I fire several calls at the same time. 3-4 calls will make sure that I will get SocketTimeoutError. Then if I do polling too often (1 sec vs 5 sec) I observe this behavior as well.

**Comment by luandnguyen** [comment]
This is still an issue.

**Comment by lisimmo** [comment]
This issue is still happening!

**Comment by nEdAy** [comment]
This issue is still happening!

**Comment by spiritinlife** [comment]
This happens randomly when uploading files on 3.0.9 and 3.0.10

**Comment by brunoalfred** [comment]
Im also facing the challenge, somebody help??/

**Comment by a83988029** [comment]
same problem

**Comment by catmaomao** [comment]
same problem too

**Comment by koteesy** [comment]
Same problem, just randomly

**Comment by yemidada** [comment]
same issue

**Comment by tamoyal** [comment]
I also have this issue. It should not be closed

**Comment by HuberyYang** [comment]
same issue, but it appeared in release mode

**Comment by jgoyvaerts** [comment]
Apps running on mobile devices suffer from unstable network conditions, since the user can be moving around while using the app. For example, the user can enter an elevator, go underground, or just enter a zone of bad reception. 
This can cause connection timeouts, which are not caused by Dio. Your app should be able to handle timeouts of any request.

**Comment by HuberyYang** [comment]
谢谢！

**Comment by Calvin2274** [comment]
same here

**Comment by HuberyYang** [comment]
谢谢！

**Comment by HuberyYang** [comment]
谢谢！

**Comment by toppert** [comment]
same problem i keep getting timeout error pls help

**Comment by sunqihui222** [comment]
Me too, i used package Dio 4.0.6, but still the same.

**Comment by HuberyYang** [comment]
谢谢！

**Comment by tarekmabdallah91** [comment]
this problem still occurs till now !

**Comment by OmarBakry-Globalits** [comment]
This problem still occurs till now I don't know why this issue marked as closed please open it again I'm using the latest version of Dio (dio: ^5.0.1) and still getting connection timeout every time although the code was working yesterday without any update !!!

**Comment by HuberyYang** [comment]
谢谢！

**Comment by drttcrh** [comment]
i have the same problem, how to resolve it

**Comment by he15his** [comment]
I have same problem

**Comment by ClarkLusm** [comment]
Same issue. That was such a disappointment!
