### ISSUE TITLE
Unable to send null values in formdata

### ISSUE THREAD

**Issue by iJamesPHP** [flutterchina/dio#977]
I am creating a FormData object like so:

`dio.FormData _formData = dio.FormData.fromMap(vals);`

Unfortunately `.fromMap` removes null values, I need to send null values, is there any way supported by Dio to do this? As opposed to a work around, I can work around around it on my own accord.

Thanks

**Comment by iJamesPHP** [comment]
Months later I run into this being a problem again, is there any way to do this?

**Comment by michalgauza** [comment]
I have same issue. Why formdata can't have null values?

**Comment by osamasaeed** [comment]
I also have same issue. I can not send empty string or null value via FormData.
