### ISSUE TITLE
Cannot able to send api key through headers

### ISSUE THREAD

**Issue by basha97** [flutterchina/dio#978]
options: Options(
          headers: {
            "X-Api-Key": "kdjfglasdk-alskdfj",
          },
        ),

Hii , I am sending post request to my server with api key , but i cannot able to access this key in my server.

**Comment by SameerChorge94** [comment]
Facing the same issue.
Any solution or workaround on this issue yet?

**Comment by basha97** [comment]
@SameerChorge94 Please downgrade the dio package and try it . it may work

**Comment by SameerChorge94** [comment]
> 
> 
> @SameerChorge94 Please downgrade the dio package and try it . it may work

@basha97 dio Package working for the Android devices i.e headers are forwarded to the API,

**Comment by basha97** [comment]
No dude i had'nt worked in web.

**Comment by hdyluo** [comment]
same issue

**Comment by SameerChorge94** [comment]
@hdyluo It's related to the CORS issue for the web. 
I faced the same issue with **http** package also, and after handling the CORS in our API side solved the headers issue in web for us.
