### ISSUE TITLE
CancelToken not working if data is Stream

### ISSUE THREAD

**Issue by huangbinjie** [flutterchina/dio#986]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. Dart                          |      |
| Platform Version               | e.g. 2.9.3                             |      |
| Dio Version                    | e.g.  3.0.10                                 |      |

### Issue Description and Steps

Just simple set data to Stream:

```dart
final cancelToken = CancelToken()
client.interceptors.add(InterceptorsWrapper(onRequest: (options) {
  options.cancelToken = cancelToken;
  return options;
})
client.put(url, data: File('x').openRead())
cancelToken.cancel()
```

Will throw HttpException while not DioErrorType.CANCEL:

```dart
HttpException: Content size below specified contentLength.  0 bytes written but expected 2078449.
```

Have any test case with cancel on Stream?

**Comment by johnnycook** [comment]
same issue here
