### ISSUE TITLE
What is the right way to read the response data (json) and response status code?

### ISSUE THREAD

**Issue by neeraj87** [flutterchina/dio#99]
I am following this [documentation](https://github.com/flutterchina/dio/blob/flutter/example/options.dart) to understand how to read the response data and response status code but I am still unable to figure this out.

When I send a POST request to my server I get 

`{
    "message": "New image added"
}`

The request is successful and the data goes through, however I need to show this message to the user.

This is my code:

```
Dio dio = new Dio();
dio.options.headers = {
  'Authorization': 'Bearer ' + prefs.getString("TOKEN")
};
dio.options.responseType = ResponseType.JSON;

List<UploadFileInfo> uploadFileInfoList = new List<UploadFileInfo>();
uploadFileInfoList.add(new UploadFileInfo(new File(image.path), basename(image.path)));

FormData formData = new FormData();
formData.add("userId", userId);
formData.add("image", new UploadFileInfo(new File(image.path), basename(image.path)));

Response<Map> response = await dio.post("https://myapi.com", data: formData);

print('-- statusCode $response.statusCode'); //gives [data]={message: New image added}.statusCode
print('---- response data $response'); //gives data [data]={message: New image added}
print("---- response data $response.data['message']"); //gives [data]={message: New image added}.data['message']

if(response.statusCode == 200) {
  //does not go into this if statement
  Navigator.pop(context);
} else {
  Scaffold.of(context).showSnackBar(new SnackBar(
    content: new Text(response.data['message']),
  ));
}
```

What is the right way to read status code and json from the response?

**Comment by wendux** [comment]
There  is a mistake  in your string  , The correct  code  as follows:
```dart
print('statuscode ${ response. statusCode}'); 
```


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by neeraj87** [comment]
Ok, so the print statement was incorrect, but what about the **if** statement where I am checking if statusCode == 200? it never goes there.

**Comment by wendux** [comment]
It's possible  the value of `statusCode`  is not 200,  you can print the `statusCode` to check. By the way, `await` must be in `async` function.
