### ISSUE TITLE
因为浏览器不支持跨域请求，希望能完善这个问题

### ISSUE THREAD

**Issue by zhuyonghao** [flutterchina/dio#997]
因为浏览器不支持跨域请求，希望能完善这个问题

**Comment by chentianxin** [comment]
> 因为浏览器不支持跨域请求，希望能完善这个问题

解决办法
前端：jsonp、fetch
后端：设置响应头（access-control-allow-origin）

**Comment by zhuyonghao** [comment]
使用中间件shelf或shelf_prox解决web请求跨域，会有options二次请求，dio的request请求添加请求头，参数会在Access-Control-Request-Headers后边。
![image](https://user-images.githubusercontent.com/18735317/101151647-eca41700-365c-11eb-806b-7b59e844bb59.png)
